### ISSUE TITLE
DECIMAL value is out of range in '(4, 0)'

### ISSUE THREAD

**Issue by ChenPeng2013** [pingcap/tidb#20698] opened 2020-10-28 11:28 UTC
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
Drop table if exists t;
CREATE TABLE `t` (
  `col_bigint_key_signed` bigint(20) DEFAULT NULL,
  `col_year_key_signed` year(4) DEFAULT NULL,
  `pk` int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
SELECT  t1.pk, t2.pk from t t1 left join t t2 on t1. `col_bigint_key_signed` = t2. `col_year_key_signed`  where t1. `col_bigint_key_signed` != -840 order by t1.pk, t2.pk;
alter table t add index `col_year_key_signed` (`col_year_key_signed`);
SELECT  t1.pk, t2.pk from t t1 left join t t2 on t1. `col_bigint_key_signed` = t2. `col_year_key_signed`  where t1. `col_bigint_key_signed` != -840 order by t1.pk, t2.pk;
```
### 2. What did you expect to see? (Required)
```
mysql> SELECT  t1.pk, t2.pk from t t1 left join t t2 on t1. `col_bigint_key_signed` = t2. `col_year_key_signed`  where t1. `col_bigint_key_signed` != -840 order by t1.pk, t2.pk;
Empty set (0.00 sec)

mysql> alter table t add index `col_year_key_signed` (`col_year_key_signed`);
Query OK, 0 rows affected (0.26 sec)

mysql> SELECT  t1.pk, t2.pk from t t1 left join t t2 on t1. `col_bigint_key_signed` = t2. `col_year_key_signed`  where t1. `col_bigint_key_signed` != -840 order by t1.pk, t2.pk;
Empty set (0.00 sec)
```
### 3. What did you see instead (Required)
```
mysql> SELECT  t1.pk, t2.pk from t t1 left join t t2 on t1. `col_bigint_key_signed` = t2. `col_year_key_signed`  where t1. `col_bigint_key_signed` != -840 order by t1.pk, t2.pk;
Empty set (0.00 sec)

mysql> alter table t add index `col_year_key_signed` (`col_year_key_signed`);
Query OK, 0 rows affected (0.26 sec)

mysql> SELECT  t1.pk, t2.pk from t t1 left join t t2 on t1. `col_bigint_key_signed` = t2. `col_year_key_signed`  where t1. `col_bigint_key_signed` != -840 order by t1.pk, t2.pk;
ERROR 1690 (22003): DECIMAL value is out of range in '(4, 0)'
```
### 4. What is your TiDB version? (Required)

```
master ccd48eeb4d586fa082b2358fbf1dbf77647e64bc and release-4.0 66ac9fc31f1733e5eb8d11891ec1b38f9c422817
```

## SIG slack channel

 [#sig-exec](https://slack.tidb.io/invite?team=tidb-community&channel=sig-exec&ref=high-performance)

## Score

- 300

## Mentor

* @lzmhhh123

**Comment by dyzsr** [comment] 2020-10-30 13:51
Is it a duplicate of #20101?

**Comment by lzmhhh123** [comment] 2020-11-06 09:54
Solved by https://github.com/pingcap/tidb/pull/20338

**Closed** 2020-11-06 09:53 UTC
Labels: challenge-program, severity/major, sig/execution, status/help-wanted, type/bug, type/duplicate
