### ISSUE TITLE
confused to set tidb_slow_log_threshold in session scope

### ISSUE THREAD

**Issue by siddontang** [pingcap/tidb#14586] opened 2020-02-02 13:52 UTC
## General Question

We can set tidb_slow_log_threshold in session scope, but this change doesn't only affect the session, but affect the TiKV server which the session belongs to, IMO, this is confused, maybe we should introduce another scope like `server`.

**Comment by nullnotnil** [comment] 2020-08-06 20:04
I believe this is caused by the same problem as https://github.com/pingcap/tidb/issues/18989

See [my explanation](https://github.com/pingcap/tidb/issues/18989#issuecomment-670083360)  on what I think causes this. I believe the MySQL-like name for server scope is "instance". There is a FR for it here: https://github.com/pingcap/tidb/issues/9298

**Comment by tisonkun** [comment] 2021-09-01 11:26
Duplicate of #18989

**Closed by tisonkun** 2021-09-01 11:26 UTC
Labels: duplicate, type/question
