### ISSUE TITLE
TiKV crashed

### ISSUE THREAD

**Issue by alex-quan-001** [pingcap/tidb#22795] opened 2021-02-18 14:30 UTC
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
use mysql client tool load data 

### 2. What did you expect to see? (Required)
TiKV crashed

### 3. What did you see instead (Required)
Seven tikv one of the tivk process crashed. The log is as follows:
![image](https://user-images.githubusercontent.com/77444503/108371955-41593600-7239-11eb-9ca0-203e34ae4d69.png)

[2021/02/15 18:57:48.925 +08:00] [FATAL] [lib.rs:481] ["no entry found for key"] [backtrace="stack backtrace:
   0: tikv_util::set_panic_hook::{{closure}}
             at components/tikv_util/src/lib.rs:480
   1: std::panicking::rust_panic_with_hook
             at library/std/src/panicking.rs:581
   2: std::panicking::begin_panic_handler::{{closure}}
             at library/std/src/panicking.rs:484
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at library/std/src/sys_common/backtrace.rs:141
   4: rust_begin_unwind
             at library/std/src/panicking.rs:483
   5: core::panicking::panic_fmt
             at library/core/src/panicking.rs:85
   6: core::option::expect_failed
             at library/core/src/option.rs:1230
   7: core::option::Option<T>::expect
             at /rustc/b1496c6e606dd908dd651ac2cce89815e10d7fc5/library/core/src/option.rs:349
      <std::collections::hash::map::HashMap<K,V,S> as core::ops::index::Index<&Q>>::index
             at /rustc/b1496c6e606dd908dd651ac2cce89815e10d7fc5/library/std/src/collections/hash/map.rs:1095
      raftstore::store::fsm::store::StoreFsmDelegate<EK,ER,T>::maybe_create_peer_internal
            at /home/jenkins/agent/workspace/uild_tikv_multi_branch_v5.0.0-rc/tikv/components/raftstore/src/store/fsm/store.rs:1676
      raftstore::store::fsm::store::StoreFsmDelegate<EK,ER,T>::maybe_create_peer
             at /home/jenkins/agent/workspace/uild_tikv_multi_branch_v5.0.0-rc/tikv/components/raftstore/src/store/fsm/store.rs:1620
      raftstore::store::fsm::store::StoreFsmDelegate<EK,ER,T>::on_raft_message
             at /home/jenkins/agent/workspace/uild_tikv_multi_branch_v5.0.0-rc/tikv/components/raftstore/src/store/fsm/store.rs:1552
   8: raftstore::store::fsm::store::StoreFsmDelegate<EK,ER,T>::handle_msgs
             at /home/jenkins/agent/workspace/uild_tikv_multi_branch_v5.0.0-rc/tikv/components/raftstore/src/store/fsm/store.rs:560
      <raftstore::store::fsm::store::RaftPoller<EK,ER,T> as batch_system::batch::PollHandler<raftstore::store::fsm::peer::PeerFsm<EK,ER>,raftstore::store::fsm::store::StoreFsm<EK>>>::handle_control
             at /home/jenkins/agent/workspace/uild_tikv_multi_branch_v5.0.0-rc/tikv/components/raftstore/src/store/fsm/store.rs:784
      batch_system::batch::Poller<N,C,Handler>::poll
             at /home/jenkins/agent/workspace/uild_tikv_multi_branch_v5.0.0-rc/tikv/components/batch-system/src/batch.rs:284
   9: batch_system::batch::BatchSystem<N,C>::spawn::{{closure}}
             at /home/jenkins/agent/workspace/uild_tikv_multi_branch_v5.0.0-rc/tikv/components/batch-system/src/batch.rs:396
      std::sys_common::backtrace::__rust_begin_short_backtrace
    at /rustc/b1496c6e606dd908dd651ac2cce89815e10d7fc5/library/std/src/sys_common/backtrace.rs:125
  10: std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}
            at /rustc/b1496c6e606dd908dd651ac2cce89815e10d7fc5/library/std/src/thread/mod.rs:470
      <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/b1496c6e606dd908dd651ac2cce89815e10d7fc5/library/std/src/panic.rs:308
      std::panicking::try::do_call
             at /rustc/b1496c6e606dd908dd651ac2cce89815e10d7fc5/library/std/src/panicking.rs:381
      std::panicking::try
             at /rustc/b1496c6e606dd908dd651ac2cce89815e10d7fc5/library/std/src/panicking.rs:345
      std::panic::catch_unwind
             at /rustc/b1496c6e606dd908dd651ac2cce89815e10d7fc5/library/std/src/panic.rs:382
      std::thread::Builder::spawn_unchecked::{{closure}}
             at /rustc/b1496c6e606dd908dd651ac2cce89815e10d7fc5/library/std/src/thread/mod.rs:469
      core::ops::function::FnOnce::call_once{{vtable.shim}}
             at /rustc/b1496c6e606dd908dd651ac2cce89815e10d7fc5/library/core/src/ops/function.rs:227
  11: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/b1496c6e606dd908dd651ac2cce89815e10d7fc5/library/alloc/src/boxed.rs:1042
      <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/b1496c6e606dd908dd651ac2cce89815e10d7fc5/library/alloc/src/boxed.rs:1042
      std::sys::unix::thread::Thread::new::thread_start
             at library/std/src/sys/unix/thread.rs:89
  12: start_thread
  13: __clone
"] [location=/home/jenkins/agent/workspace/uild_tikv_multi_branch_v5.0.0-rc/tikv/components/raftstore/src/store/fsm/store.rs:1676] [thread_name=raftstore-13-1]

### 4. What is your TiDB version? (Required)
Release Version: v5.0.0-rc
Edition: Community
Git Commit Hash: fd4437dde445012f5b75e5d4f336433cb076c1ee
Git Branch: heads/refs/tags/v5.0.0-rc
UTC Build Time: 2021-01-12 06:00:03
GoVersion: go1.13
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false

**Comment by BusyJay** [comment] 2021-02-19 14:51
Can you also provide all (or 1000 lines of) logs before panicking?

**Comment by BusyJay** [comment] 2021-02-19 15:19
Known issue: https://github.com/tikv/tikv/issues/8783.

**Comment by aytrack** [comment] 2021-05-25 08:55
should we close this issue while It's a known issue and was fixed?

**Comment by tisonkun** [comment] 2021-09-01 11:24
Duplicate of tikv/tikv#8783 .

**Closed by tisonkun** 2021-09-01 11:24 UTC
Labels: type/bug, duplicate
