### ISSUE TITLE
Different decimal results returned by HashAgg when enable-chunk-rpc is true/false

### ISSUE THREAD

**Issue by SunRunAway** [pingcap/tidb#13280] opened 2019-11-08 06:05 UTC
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

```mysql
CREATE TABLE tt(a INT, b INT, c INT, d INT);
INSERT INTO tt VALUES (1,1,1,1), (2,2,4,2), (3,3,9,3);
```

2. What did you expect to see?

```
[tikv-client]
# Enable chunk encoded data for coprocessor requests.
enable-chunk-rpc = true
```

```mysql
MySQL [test]> SELECT sum(c/d)  FROM tt  group by a, b;
+----------+
| sum(c/d) |
+----------+
|   1.0000 |
|   2.0000 |
|   3.0000 |
+----------+
3 rows in set (0.00 sec)

MySQL [test]> desc SELECT sum(c/d)  FROM tt  group by a, b;
+-----------------------+----------+-----------+-----------------------------------------------------------------------------+
| id                    | count    | task      | operator info                                                               |
+-----------------------+----------+-----------+-----------------------------------------------------------------------------+
| HashAgg_9             | 8000.00  | root      | group by:Column#10, Column#9, funcs:sum(Column#8)                           |
| └─TableReader_10  | 8000.00  | root      | data:HashAgg_5                                                              |
|   └─HashAgg_5     | 8000.00  | cop[tikv] | group by:Column#1, Column#2, funcs:sum(div(cast(Column#3), cast(Column#4))) |
|     └─TableScan_8 | 10000.00 | cop[tikv] | table:tt, range:[-inf,+inf], keep order:false, stats:pseudo                 |
+-----------------------+----------+-----------+-----------------------------------------------------------------------------+
4 rows in set (0.00 sec)
```

3. What did you see instead?

```
[tikv-client]
# Enable chunk encoded data for coprocessor requests.
enable-chunk-rpc = false
```

```mysql
MySQL [test]> SELECT sum(c/d)  FROM tt  group by a, b;
+-------------+
| sum(c/d)    |
+-------------+
| 1.000000000 |
| 2.000000000 |
| 3.000000000 |
+-------------+
3 rows in set (0.01 sec)

MySQL [test]> desc SELECT sum(c/d)  FROM tt  group by a, b;
+-----------------------+----------+-----------+-----------------------------------------------------------------------------+
| id                    | count    | task      | operator info                                                               |
+-----------------------+----------+-----------+-----------------------------------------------------------------------------+
| HashAgg_9             | 8000.00  | root      | group by:Column#10, Column#9, funcs:sum(Column#8)                           |
| └─TableReader_10  | 8000.00  | root      | data:HashAgg_5                                                              |
|   └─HashAgg_5     | 8000.00  | cop[tikv] | group by:Column#1, Column#2, funcs:sum(div(cast(Column#3), cast(Column#4))) |
|     └─TableScan_8 | 10000.00 | cop[tikv] | table:tt, range:[-inf,+inf], keep order:false, stats:pseudo                 |
+-----------------------+----------+-----------+-----------------------------------------------------------------------------+
4 rows in set (0.00 sec)
```

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

Only appears in commit 79756747e, because `hashagg` can be push down in this commit temparorily and disabled in following commit, so this issue can reappear,

**Comment by SunRunAway** [comment] 2019-11-08 06:06
@breeswish @mapleFU

**Comment by SunRunAway** [comment] 2019-11-08 08:43
After investigating with @breeswish 
if `enable-chunk-rpc` is false or `steaming` is true, TiDB uses non-chunk format to communicate with TiKV. Tikv sends decimals with precision=10, fraction=9 in this situation.

**Comment by nullnotnil** [comment] 2020-07-21 22:46
I tested this against master, and it looks fixed to me:
```sql
mysql> DROP TABLE IF EXISTS tt;
Query OK, 0 rows affected, 1 warning (0.00 sec)

mysql> CREATE TABLE tt(a INT, b INT, c INT, d INT);
Query OK, 0 rows affected (0.11 sec)

mysql> INSERT INTO tt VALUES (1,1,1,1), (2,2,4,2), (3,3,9,3);
Query OK, 3 rows affected (0.02 sec)
Records: 3  Duplicates: 0  Warnings: 0

mysql> SELECT sum(c/d)  FROM tt  group by a, b;
+----------+
| sum(c/d) |
+----------+
|   2.0000 |
|   3.0000 |
|   1.0000 |
+----------+
3 rows in set (0.00 sec)
```
At this point I edited my config file, and set `enable-chunk-rpc = false`. Then repeating the test:
```sql
..
mysql> SELECT sum(c/d)  FROM tt  group by a, b;
+----------+
| sum(c/d) |
+----------+
|   2.0000 |
|   1.0000 |
|   3.0000 |
+----------+
3 rows in set (0.00 sec)

mysql> 
mysql> EXPLAIN SELECT sum(c/d)  FROM tt  group by a, b;
+---------------------------+---------+-----------+---------------+-------------------------------------------------------------------------------------------+
| id                        | estRows | task      | access object | operator info                                                                             |
+---------------------------+---------+-----------+---------------+-------------------------------------------------------------------------------------------+
| HashAgg_9                 | 2.40    | root      |               | group by:test.tt.a, test.tt.b, funcs:sum(Column#7)->Column#6                              |
| └─TableReader_10          | 2.40    | root      |               | data:HashAgg_5                                                                            |
|   └─HashAgg_5             | 2.40    | cop[tikv] |               | group by:test.tt.a, test.tt.b, funcs:sum(div(cast(test.tt.c), cast(test.tt.d)))->Column#7 |
|     └─TableFullScan_8     | 3.00    | cop[tikv] | table:tt      | keep order:false, stats:pseudo                                                            |
+---------------------------+---------+-----------+---------------+-------------------------------------------------------------------------------------------+
4 rows in set (0.00 sec)
```

I will leave this open for a bit, since this is not an area I understand well. But please let me know if my understanding is correct. Thanks!

**Comment by wshwsh12** [comment] 2020-12-08 03:51
Can't reproduce.. I think the issue has been fixed now.

**Closed** 2020-12-08 03:52 UTC
Labels: Priority/P3, component/coprocessor, severity/major, sig/execution, status/can't-reproduce, type/bug
