### ISSUE TITLE
TiDB v3.1.1 count distinct error

### ISSUE THREAD

**Issue by Still4** [pingcap/tidb#17487] opened 2020-05-28 11:05 UTC
last night upgraded from 3.0.9, regular calculation shows login user doubled, and I tested like this

```
mysql> select count(1) from user_login where date = '2020-05-01';
+----------+
| count(1) |
+----------+
|  3172208 | 
+----------+
1 row in set (0.42 sec)

mysql> select count(distinct uid) from user_login where date = '2020-05-01';
+---------------------+
| count(distinct uid) |
+---------------------+
|             3172035 | 
+---------------------+
1 row in set (2.31 sec)

mysql> select count(1) from (select uid from user_login where date = '2020-05-01' group by uid) a;
+----------+
| count(1) |
+----------+
|  1702076 | 
+----------+
1 row in set (2.14 sec)
```
2nd and 3rd sql should return same result but not

and I tried single uid, turns out right result
```
mysql> select * from user_login where date = '2020-05-01' and uid = '370949677000635';
+-----------------+--------+----------+------------+---------------+---------------+---------+------------+--------------------------------------------+-----------------+
| uid             | server | timezone | date       | time          | pf            | country | appVersion | deviceId                                   | ip              |
+-----------------+--------+----------+------------+---------------+---------------+---------+------------+--------------------------------------------+-----------------+
| 370949677000635 |    635 |        8 | 2020-05-01 | 1588266344684 | market_global | US      | 1.250.176  | emula_b7935eb333354fe9b8fd5585a2dd801fFB88 | 136.49.80.72    | 
| 370949677000635 |    635 |        0 | 2020-05-01 | 1588284207900 | market_global | US      | 1.250.176  | emula_b7935eb333354fe9b8fd5585a2dd801fFB88 | 166.172.121.184 | 
+-----------------+--------+----------+------------+---------------+---------------+---------+------------+--------------------------------------------+-----------------+
2 rows in set (0.01 sec)

mysql> select count(distinct uid) from user_login where date = '2020-05-01' and uid = '370949677000635';
+---------------------+
| count(distinct uid) |
+---------------------+
|                   1 | 
+---------------------+
1 row in set (0.02 sec)
```
seems something happened when rows get bigger

**Comment by wwar** [comment] 2020-06-05 04:18
@Still4 Please paste the result of `show create table user_login`. Thanks!

**Comment by Still4** [comment] 2020-06-05 04:22
@wwar
```
CREATE TABLE `user_login` (
  `uid` varchar(40) NOT NULL,
  `server` int(11) DEFAULT NULL,
  `timezone` int(11) NOT NULL DEFAULT 0,
  `date` date NOT NULL DEFAULT '0000-00-00',
  `time` bigint(20) NOT NULL,
  `pf` varchar(20) DEFAULT NULL,
  `country` varchar(20) DEFAULT NULL,
  `appVersion` varchar(20) DEFAULT NULL,
  `deviceId` varchar(255) DEFAULT NULL,
  `ip` varchar(40) DEFAULT NULL,
  PRIMARY KEY (`uid`,`timezone`,`date`),
  KEY `idx_time` (`time`),
  KEY `idx_server` (`server`),
  KEY `idx_date` (`date`),
  KEY `idx_deviceId_date` (`deviceId`,`date`),
  KEY `idx_ip_timezone_date` (`ip`,`timezone`,`date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin
```

**Comment by SunRunAway** [comment] 2020-08-26 05:24
Duplicate of https://github.com/pingcap/tidb/issues/17148

@Still4 Please upgrade to the newest 4.0.X version.

**Closed by SunRunAway** 2020-08-26 05:24 UTC
Labels: severity/critical, sig/execution, type/bug
