### ISSUE TITLE
IT mysql_test insert failed 

### ISSUE THREAD

**Issue by jebter** [pingcap/tidb#33257] opened 2022-03-19 07:20 UTC
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
https://ci.pingcap.net/blue/organizations/jenkins/tidb_ghpr_integration_common_test/detail/tidb_ghpr_integration_common_test/10243/pipeline/#step-455-log-177
[2022-03-19T03:09:11.558Z] time="2022-03-19T07:14:00+08:00" level=error msg="run test [insert] err: sql:EXECUTE stmt;: failed to run query \n\"EXECUTE stmt;\" \n around line 1027, \nwe need(64):\nEXECUTE stmt;\n\nError 1062: Duplicate entry '8' for key 'PRIMARY'\nbut got(64):\nEXECUTE stmt;\nError 1062: Duplicate entry '8' for key 'PRIMARY'\n\n"

[2022-03-19T03:09:11.558Z] time="2022-03-19T07:14:00+08:00" level=warning msg="Create new db&{0 0xc0003a67a8 0 {0 0} [0xc0012e9a70] map[] 0 1 0xc0000370e0 false map[0xc0012e9a70:map[0xc0012e9a70:true]] map[] 0 0 0 0 <nil> 0 0 0 0 0x48ae40}"

### 4. What is your TiDB version? (Required)
master & v6.0.0

**Comment by Reminiscent** [comment] 2022-03-23 02:49
Related to https://github.com/pingcap/tidb/issues/32339

**Comment by qw4990** [comment] 2022-03-23 10:28
> Duplicate with #32339

It seems like this issue doesn't have the same reason as #32339. After reproducing it locally, I found it just was caused by an unnecessary blank line:
```
we need(64):
EXECUTE stmt;

Error 1062: Duplicate entry '8' for key 'PRIMARY'
but got(64):
EXECUTE stmt;
Error 1062: Duplicate entry '8' for key 'PRIMARY'
```

**Comment by qw4990** [comment] 2022-03-23 13:27
It's weird that when I try to solve it, the error becomes like this:
```
we need(65):
EXECUTE stmt;
Error 1062: Duplicate entry '8' for key 'PRIMARY'
but got(65):
EXECUTE stmt;

Error 1062: Duplicate entry '8' for key 'PRIMARY'
```
A blank line is required again, so I guess this issue has been resolved by some PR.
I'll close this issue now, and if it happens again, please let me know.

**Comment by qw4990** [comment] 2022-03-30 07:53
![AYJ9lo6lw8](https://user-images.githubusercontent.com/7499936/160780518-7612592b-87ee-43a3-85ee-3d2da65586a8.png)

**Closed** 2022-03-30 08:13 UTC
Labels: type/bug, sig/planner, severity/major, affects-6.0
