### ISSUE TITLE
Result of function ROUND is different from MySQL

### ISSUE THREAD

**Issue by SunRunAway** [pingcap/tidb#11205] opened 2019-07-11 06:19 UTC
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

```mysql
SELECT ROUND( 'hello', -7787 ) ;
```

2. What did you expect to see?

```mysql
mysql> SELECT ROUND( 'hello', -7787 ) ;
+-------------------------+
| ROUND( 'hello', -7787 ) |
+-------------------------+
|                     NaN |
+-------------------------+
1 row in set, 1 warning (0.00 sec)
```

3. What did you see instead?

```mysql
mysql> SELECT ROUND( 'hello', -7787 ) ;
+-------------------------+
| ROUND( 'hello', -7787 ) |
+-------------------------+
|                       0 |
+-------------------------+
1 row in set, 1 warning (0.00 sec)

mysql> show warnings;
+---------+------+-------------------------------------------+
| Level   | Code | Message                                   |
+---------+------+-------------------------------------------+
| Warning | 1292 | Truncated incorrect DOUBLE value: 'hello' |
+---------+------+-------------------------------------------+
1 row in set (0.00 sec)
```

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
8c20289c7

**Comment by wjhuang2016** [comment] 2019-07-15 08:11
In MySQL 8.0.15:
```
mysql> SELECT ROUND( 'hello', -7787 ) ;
+-------------------------+
| ROUND( 'hello', -7787 ) |
+-------------------------+
|                       0 |
+-------------------------+
1 row in set, 1 warning (0.01 sec)

mysql> show warnings;
+---------+------+-------------------------------------------+
| Level   | Code | Message                                   |
+---------+------+-------------------------------------------+
| Warning | 1292 | Truncated incorrect DOUBLE value: 'hello' |
+---------+------+-------------------------------------------+
1 row in set (0.00 sec)
```

**Comment by nullnotnil** [comment] 2020-07-14 15:05
It looks like TiDB uses the MySQL 8.0 behavior here (with correct error code and message). Functions are not explicitly documented in the docs yet, but until it is known to affect a user this should be categorized as a compatibility issue and not a bug.

It is not expected to specify decimals (i.e. `ROUND(number, decimals)`) as a negative value.

**Comment by wjhuang2016** [comment] 2020-07-14 15:51
> It looks like TiDB uses the MySQL 8.0 behavior here (with correct error code and message). Functions are not explicitly documented in the docs yet, but until it is known to affect a user this should be categorized as a compatibility issue and not a bug.
> 
> It is not expected to specify decimals (i.e. `ROUND(number, decimals)`) as a negative value.

@SunRunAway @nullnotnil  Can we close this issue?

**Comment by nullnotnil** [comment] 2020-07-15 01:07
Yes, I think it is acceptable to close as "won't fix". We can review if there are requests to the counter.

**Closed by nullnotnil** 2020-07-15 01:07 UTC
Labels: component/expression, status/help-wanted, type/compatibility, type/wontfix
