### ISSUE TITLE
 [aggregate.go:393]["parallel hash aggregation panicked"] [error="runtime error: index out of range [0] with length 0"]

### ISSUE THREAD

**Issue by wjhuang2016** [pingcap/tidb#23670] opened 2021-03-30 08:05 UTC
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

[log3.sql.zip](https://github.com/pingcap/tidb/files/6227430/log3.sql.zip)
source log3.sql;

### 2. What did you expect to see? (Required)
No panic
### 3. What did you see instead (Required)
```
[aggregate.go:393] ["parallel hash aggregation panicked"] [error="runtime error: index out of range [0] with length 0"] [errorVerbose="runtime error: index out of range [0] with length 0
github.com/pingcap/tidb/executor.recoveryHashAgg
	/Users/pingcap/workspace/build-darwin-amd64-4.0/go/src/github.com/pingcap/tidb/executor/aggregate.go:391
github.com/pingcap/tidb/executor.(*HashAggFinalWorker).run.func1
	/Users/pingcap/workspace/build-darwin-amd64-4.0/go/src/github.com/pingcap/tidb/executor/aggregate.go:682
runtime.gopanic
	/usr/local/go/src/runtime/panic.go:679
runtime.goPanicIndex
	/usr/local/go/src/runtime/panic.go:75
github.com/pingcap/tidb/util/chunk.(*Column).AppendInt64
	/Users/pingcap/workspace/build-darwin-amd64-4.0/go/src/github.com/pingcap/tidb/util/chunk/column.go:209
github.com/pingcap/tidb/util/chunk.(*Chunk).AppendInt64
	/Users/pingcap/workspace/build-darwin-amd64-4.0/go/src/github.com/pingcap/tidb/util/chunk/chunk.go:557
github.com/pingcap/tidb/executor/aggfuncs.(*percentileOriginal4Int).AppendFinalResult2Chunk
	/Users/pingcap/workspace/build-darwin-amd64-4.0/go/src/github.com/pingcap/tidb/executor/aggfuncs/func_percentile.go:175
github.com/pingcap/tidb/executor.(*HashAggFinalWorker).getFinalResult
	/Users/pingcap/workspace/build-darwin-amd64-4.0/go/src/github.com/pingcap/tidb/executor/aggregate.go:648
github.com/pingcap/tidb/executor.(*HashAggFinalWorker).run
	/Users/pingcap/workspace/build-darwin-amd64-4.0/go/src/github.com/pingcap/tidb/executor/aggregate.go:692
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1357"] [stack="github.com/pingcap/tidb/executor.recoveryHashAgg
	/Users/pingcap/workspace/build-darwin-amd64-4.0/go/src/github.com/pingcap/tidb/executor/aggregate.go:393
github.com/pingcap/tidb/executor.(*HashAggFinalWorker).run.func1
	/Users/pingcap/workspace/build-darwin-amd64-4.0/go/src/github.com/pingcap/tidb/executor/aggregate.go:682
runtime.gopanic
	/usr/local/go/src/runtime/panic.go:679
runtime.goPanicIndex
	/usr/local/go/src/runtime/panic.go:75
github.com/pingcap/tidb/util/chunk.(*Column).AppendInt64
	/Users/pingcap/workspace/build-darwin-amd64-4.0/go/src/github.com/pingcap/tidb/util/chunk/column.go:209
github.com/pingcap/tidb/util/chunk.(*Chunk).AppendInt64
	/Users/pingcap/workspace/build-darwin-amd64-4.0/go/src/github.com/pingcap/tidb/util/chunk/chunk.go:557
github.com/pingcap/tidb/executor/aggfuncs.(*percentileOriginal4Int).AppendFinalResult2Chunk
	/Users/pingcap/workspace/build-darwin-amd64-4.0/go/src/github.com/pingcap/tidb/executor/aggfuncs/func_percentile.go:175
github.com/pingcap/tidb/executor.(*HashAggFinalWorker).getFinalResult
	/Users/pingcap/workspace/build-darwin-amd64-4.0/go/src/github.com/pingcap/tidb/executor/aggregate.go:648
github.com/pingcap/tidb/executor.(*HashAggFinalWorker).run
	/Users/pingcap/workspace/build-darwin-amd64-4.0/go/src/github.com/pingcap/tidb/executor/aggregate.go:692"]
```

### 4. What is your TiDB version? (Required)
master

**Comment by zz-jason** [comment] 2021-03-31 05:43
@wjhuang2016 seems the panic stack is the same with https://github.com/pingcap/tidb/issues/23662, maybe they have the same root cause?

@lzmhhh123 PTAL

**Comment by wjhuang2016** [comment] 2021-03-31 06:09
> @wjhuang2016 seems the panic stack is the same with https://github.com/pingcap/tidb/issues/23662, maybe they have the same root cause?
> 
> @lzmhhh123 PTAL

I guess not， I used the fresh build tidb，it should contain the fix of that issue.

**Comment by zimulala** [comment] 2021-03-31 08:31
I can reproduce it on release-5.0.

**Comment by ichn-hu** [comment] 2021-03-31 08:36
> I can reproduce it on release-5.0.

did you use tikv as storage or unistore?

**Comment by ichn-hu** [comment] 2021-03-31 08:52
data has been simplified, source the following data

[data.sql.gz](https://github.com/pingcap/tidb/files/6235199/data.sql.gz)

and the panic is caused by

```
(SELECT /*+  stream_agg() */ approx_percentile(col_13, 81) aggCol
   FROM
     (SELECT *
      FROM tbl_2
      WHERE col_13 in ('Nbr')
      ORDER BY col_11,
               col_12) ordered_tbl
   FOR UPDATE)
EXCEPT
  (SELECT /*+  hash_agg() */ approx_percentile(col_10, 85) aggCol
   FROM
     (SELECT *
      FROM tbl_2
      WHERE col_12 >= 'Charlie'
      ORDER BY col_11,
               col_12) ordered_tbl) ;
```

**Comment by ichn-hu** [comment] 2021-03-31 09:21
@zimulala @zz-jason @wjhuang2016 this panic is fixed by https://github.com/pingcap/tidb/pull/23687, 5.0-release has this panic, because the fix PR has not yet been merged into 5.0-release, I tested on the fix PR, and it is fixed https://github.com/pingcap/tidb/pull/23703

**Comment by ichn-hu** [comment] 2021-03-31 09:21
@wjhuang2016 I think it is safe to close this issue.

**Comment by XuHuaiyu** [comment] 2021-03-31 09:37
dup with https://github.com/pingcap/tidb/issues/23662, thus we remove the `bug` and `critical` label

**Closed** 2021-04-02 02:52 UTC
Labels: sig/execution, type/duplicate
