### ISSUE TITLE
1690 - BIT value is out of range in '(1)'

### ISSUE THREAD

**Issue by lyzw** [pingcap/tidb#13584] opened 2019-11-19 08:34 UTC
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
we use 'insert ... ON DUPLICATE KEY UPDATE ' in our program,it works on mysql,but don't on tidb when update bit(1) column.
The DDL  like this:
`
CREATE TABLE `BIT_TEST` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `BIT_TEST` bit(1) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin AUTO_INCREMENT=30002;
`
the update sql :
`
INSERT INTO BIT_TEST ( id, BIT_TEST )
VALUES
	( 1, B'1' ) 
	ON DUPLICATE KEY UPDATE BIT_TEST = VALUES(BIT_TEST);
`

2. What did you expect to see?
it can work on tidb,and the column is update success

3. What did you see instead?
it works on mysql,but throw error on tidb 
`
INSERT INTO BIT_TEST ( id, BIT_TEST )
VALUES
	( 1, B'1' ) 
	ON DUPLICATE KEY UPDATE BIT_TEST = VALUES(BIT_TEST)
> 1690 - BIT value is out of range in '(1)'
> 时间: 0.032s
`

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

Release Version: v3.0.3
Git Commit Hash: 836982c617fbaa42d74616eb9ba9ed4cae46c46b
Git Branch: HEAD
UTC Build Time: 2019-08-30 02:42:42
GoVersion: go version go1.12 linux/amd64
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false

**Comment by lyzw** [comment] 2019-11-25 11:49
the problem can be solved in this way：
`
INSERT INTO `test`.`BIT_TEST`(`id`, `BIT_TEST`, `TININT_TEST`, `TININT_TEST2`) VALUES (1, b'0') on DUPLICATE key UPDATE BIT_TEST =1&  VALUES(BIT_TEST);
`

**Comment by nullnotnil** [comment] 2020-07-18 02:26
I tried to reproduce this against master, but it looks like it's been fixed. I tried both the case that a row already existed that was duplicate, and a fresh insert:

```sql
DROP TABLE IF EXISTS t1;
CREATE TABLE t1 ( id int(11) NOT NULL PRIMARY KEY AUTO_INCREMENT, b bit(1) NOT NULL);
INSERT INTO t1 ( id, b ) VALUES ( 1, B'1' ) ON DUPLICATE KEY UPDATE b = VALUES(b);

-- second test: row exists but needs to be updated

DROP TABLE IF EXISTS t1;
CREATE TABLE t1 ( id int(11) NOT NULL PRIMARY KEY AUTO_INCREMENT, b bit(1) NOT NULL);
INSERT INTO t1 ( id, b ) VALUES ( 1, B'0' );
INSERT INTO t1 ( id, b ) VALUES ( 1, B'1' ) ON DUPLICATE KEY UPDATE b = VALUES(b);

..

mysql> DROP TABLE IF EXISTS t1;
Query OK, 0 rows affected (0.25 sec)

mysql> CREATE TABLE t1 ( id int(11) NOT NULL PRIMARY KEY AUTO_INCREMENT, b bit(1) NOT NULL);
Query OK, 0 rows affected (0.09 sec)

mysql> INSERT INTO t1 ( id, b ) VALUES ( 1, B'1' ) ON DUPLICATE KEY UPDATE b = VALUES(b);
Query OK, 1 row affected (0.02 sec)

mysql> 
mysql> -- second test: row exists but needs to be updated
mysql> 
mysql> DROP TABLE IF EXISTS t1;
Query OK, 0 rows affected (0.21 sec)

mysql> CREATE TABLE t1 ( id int(11) NOT NULL PRIMARY KEY AUTO_INCREMENT, b bit(1) NOT NULL);
Query OK, 0 rows affected (0.09 sec)

mysql> INSERT INTO t1 ( id, b ) VALUES ( 1, B'0' );
Query OK, 1 row affected (0.02 sec)

mysql> INSERT INTO t1 ( id, b ) VALUES ( 1, B'1' ) ON DUPLICATE KEY UPDATE b = VALUES(b);
Query OK, 2 rows affected (0.01 sec)


mysql> select tidb_version()\G
*************************** 1. row ***************************
tidb_version(): Release Version: v4.0.0-beta.2-782-gb72e47e6d
Edition: Community
Git Commit Hash: b72e47e6db8863c08e47714391cf937b0f1c3269
Git Branch: master
UTC Build Time: 2020-07-15 01:26:06
GoVersion: go1.13
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
1 row in set (0.01 sec)
```

I am going to close this issue now, but please feel free to re-open with additional detail if I've missed something. I would be happy to help try and reproduce. Thanks!

**Closed by nullnotnil** 2020-07-18 02:26 UTC
Labels: type/bug
