### ISSUE TITLE
tidb oom when import into and kill one of tikv with global sort

### ISSUE THREAD

**Issue by Lily2025** [pingcap/tidb#48697] opened 2023-11-20 02:21 UTC
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
tidb （8c/16g）
tidb_enable_dist_task='on' and enable global sort
1、run import into
2、kill one of tikv

### 2. What did you expect to see? (Required)
import into can success and no oom

### 3. What did you see instead (Required)
one of tidb oom

some components oom at 2023-11-18 04:29:09
Expected
    <string>: tc-tidb-1
to equal
    <string>: 

### 4. What is your TiDB version? (Required)
git hash：23314d9d402e545dae9df57606f0ead3e67e0cd7

**Comment by D3Hunter** [comment] 2023-11-20 06:58
any logs, or heap profile?  it's hard to find root cause by current info.

**Comment by Benjamin2037** [comment] 2023-11-30 06:07
Has done memory usage refactor since 7.6 code， close this issue first。

**Closed by Benjamin2037** 2023-11-30 06:07 UTC
Labels: type/bug, severity/major, component/ddl, may-affects-7.5
