### ISSUE TITLE
MetricRetriever doesn't support mTLS when calling pd

### ISSUE THREAD

**Issue by tirsen** [pingcap/tidb#26568] opened 2021-07-26 09:12 UTC
### 1. Minimal reproduce step (Required)

Set up a cluster using e.g. `tidb-operator` with full intra-cluster mTLS enabled. Watch the logs and you will eventually find the following error:

```
query metric error: Get "http://https//tidb-pd-1.tidb-pd-peer.mynamespace.svc:2379/pd/api/v1/config": dial tcp: lookup https on 172.20.0.10:53: no such host
github.com/pingcap/tidb/telemetry.readSQLMetric
	/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/telemetry/data_window.go:116
github.com/pingcap/tidb/telemetry.RotateSubWindow
	/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/telemetry/data_window.go:193
github.com/pingcap/tidb/domain.(*Domain).TelemetryRotateSubWindowLoop.func1
	/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/domain/domain.go:1100
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1371
```

### 2. What did you expect to see? (Required)

That it connects to pd using mTLS.

### 3. What did you see instead (Required)

That it fails to connect to pd using mTLS.

### 4. What is your TiDB version? (Required)

```
mysql> select tidb_version()\G
*************************** 1. row ***************************
tidb_version(): Release Version: v5.1.0
Edition: Community
Git Commit Hash: 8acd5c88471cb7b4d4c4a8ed73b4d53d6833f13e
Git Branch: heads/refs/tags/v5.1.0
UTC Build Time: 2021-06-24 07:10:32
GoVersion: go1.16.4
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
```

The issue is that the following code doesn't support https:// URLs:
https://github.com/pingcap/tidb/blob/cc5e161ac06827589c4966674597c137cc9e809c/domain/infosync/info.go#L687-L692

And the following code should in case of mTLS pass in a `Roundtripper` transport that has a tls.Config set up with the mTLS client certificate:
https://github.com/pingcap/tidb/blob/4172f473dad30a53878a4539ad6d5cbf3b03e722/executor/metrics_reader.go#L109-L111

**Comment by gregwebs** [comment] 2021-07-26 15:42
duplicate of #26524 This report is a little better, so we could close the original.

**Comment by dveeden** [comment] 2021-07-26 15:58
I can see multiple options for fixing this:

Make the test more generic:
```go
 if strings.HasPrefix(pdAddrs[0], "http") { // http or https 
 	url = fmt.Sprintf("%s%s", pdAddrs[0], pdapi.Config) 
 } else { 
 	url = fmt.Sprintf("http://%s%s", pdAddrs[0], pdapi.Config) 
 }
```

Add an else if:
```go
 if strings.HasPrefix(pdAddrs[0], "http://") {
 	url = fmt.Sprintf("%s%s", pdAddrs[0], pdapi.Config) 
 } else if strings.HasPrefix(pdAddrs[0], "https://") {
 	url = fmt.Sprintf("%s%s", pdAddrs[0], pdapi.Config) 
 } else { 
 	url = fmt.Sprintf("http://%s%s", pdAddrs[0], pdapi.Config) 
 }
```

With a regexp:
```go
 hasPrefix, err := regexp.MatchString("^https?://"", pdAddrs[0])
 if err != nil {
     fmt.Errorf("Failed to check for protocol in PD Address %s", pdAddrs[0])
 }
 if hasPrefix
 	url = fmt.Sprintf("http://%s%s", pdAddrs[0], pdapi.Config) 
 } else { 
 	url = fmt.Sprintf("%s%s", pdAddrs[0], pdapi.Config) 
 } 
```

And besides this: adding a test would be good. Splitting out this stuff into a new function that only deals with adding a protocol if it is missing would make testing this easier.

Besides the protocol, is anything else needed to get mTLS working? (e.g. specifying a CA)

**Comment by bb7133** [comment] 2021-07-27 11:04
> I can see multiple options for fixing this:

IMO the "generic" way(first option) should be good enough. Actually, I'm not familiar with the scheme/protocol, PTAL @breeswish @rleungx @lysu

**Comment by bb7133** [comment] 2021-07-27 11:11
> And besides this: adding a test would be good. Splitting out this stuff into a new function that only deals with adding a protocol if it is missing would make testing this easier.

I agree with the 'new function' proposal, there was a proposal filed by me before: #25179. Looks that the idea is similar to yours.

> Besides the protocol, is anything else needed to get mTLS working? (e.g. specifying a CA)

Yes, I think the TLS configurations are required...or we cannot communicate with PD. Basically the following codes can be followed:

- https://github.com/pingcap/tidb/blob/cc5e161ac06827589c4966674597c137cc9e809c/store/driver/tikv_driver.go#L124
- https://github.com/pingcap/tidb/blob/16d947d7cb9cdb1e0a8ed9276cd4198a4ab52d28/server/tidb_test.go#L376

**Comment by lysu** [comment] 2021-07-27 11:16
> Besides the protocol, is anything else needed to get mTLS working? (e.g. specifying a CA)

Besides schema, maybe can use `InternalHTTPClient` which will be init with CA/Cert if tidb configured with TLS like other code snippet

https://github.com/pingcap/tidb/blob/2b461e0ea7f76b62e8b58f113e1eb4187d756869/server/http_handler.go#L1275-L1276

**Comment by breeswish** [comment] 2021-08-31 02:09
@crazycs520 Please pay attention to this issue, which has been met in cloud.

**Closed** 2021-09-23 05:36 UTC
Labels: type/bug, help wanted, sig/sql-infra, severity/moderate, component/pd
