### ISSUE TITLE
TiDB download mirror is much slower than MySQL

### ISSUE THREAD

**Issue by wwar** [pingcap/tidb#14287] opened 2019-12-30 16:31 UTC
## Bug Report

1. What did you do?

I have 600mbps down, which is not uncommon here. I downloaded both TiDB and MySQL.

2. What did you expect to see?

TiDB is a smaller package, but much slower to download than MySQL.

3. What did you see instead?

MySQL 8.0:
```
$ time wget https://dev.mysql.com/get/Downloads/MySQL-8.0/mysql-8.0.18-linux-glibc2.12-x86_64.tar.xz                                                                     |
--2019-12-30 09:24:17--  https://dev.mysql.com/get/Downloads/MySQL-8.0/mysql-8.0.18-linux-glibc2.12-x86_64.tar.xz                                                                        |
Resolving dev.mysql.com (dev.mysql.com)... 137.254.60.11                                                                                                                                 |
Connecting to dev.mysql.com (dev.mysql.com)|137.254.60.11|:443... connected.                                                                                                             |
HTTP request sent, awaiting response... 302 Found                                                                                                                                        |
Location: https://cdn.mysql.com//Downloads/MySQL-8.0/mysql-8.0.18-linux-glibc2.12-x86_64.tar.xz [following]                                                                              |
--2019-12-30 09:24:17--  https://cdn.mysql.com//Downloads/MySQL-8.0/mysql-8.0.18-linux-glibc2.12-x86_64.tar.xz                                                                           |
Resolving cdn.mysql.com (cdn.mysql.com)... 23.59.157.177                                                                                                                                 |
Connecting to cdn.mysql.com (cdn.mysql.com)|23.59.157.177|:443... connected.                                                                                                             |
HTTP request sent, awaiting response... 200 OK                                                                                                                                           |
Length: 503854832 (481M) [text/plain]                                                                                                                                                    |
Saving to: ‘mysql-8.0.18-linux-glibc2.12-x86_64.tar.xz.1’                                                                                                                                |
                                                                                                                                                                                         |
mysql-8.0.18-linux-glibc2.12-x86_64.tar.xz.1   100%[=================================================================================================>] 480.51M  76.4MB/s    in 6.5s     |
                                                                                                                                                                                         |
2019-12-30 09:24:24 (74.3 MB/s) - ‘mysql-8.0.18-linux-glibc2.12-x86_64.tar.xz.1’ saved [503854832/503854832]                                                                             |
                                                                                                                                                                                         |

real    0m7.151s
user    0m0.307s

```

TiDB:
```
$ time wget http://download.pingcap.org/tidb-latest-linux-amd64.tar.gz
--2019-12-30 09:28:07--  http://download.pingcap.org/tidb-latest-linux-amd64.tar.gz
Resolving download.pingcap.org (download.pingcap.org)... 47.246.24.231, 47.246.24.232, 47.246.24.225, ...
Connecting to download.pingcap.org (download.pingcap.org)|47.246.24.231|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 343554265 (328M) [application/x-compressed]
Saving to: ‘tidb-latest-linux-amd64.tar.gz.1’

tidb-latest-linux-amd64.tar.gz.1               100%[=================================================================================================>] 327.64M  5.51MB/s    in 58s     

2019-12-30 09:29:06 (5.63 MB/s) - ‘tidb-latest-linux-amd64.tar.gz.1’ saved [343554265/343554265]


real    0m58.707s
user    0m0.123s
sys     0m0.952s
```

In this example, TiDB was more than 10x slower to download, but this was a good day. It is often even slower than this (2-3MB/s versus 76MB/s)

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

This was downloading latest daily build.

**Comment by Icemap** [comment] 2019-12-31 01:58
Not a bug.

**Comment by sykp241095** [comment] 2020-01-08 07:04
@wwar After a few actions of tuning CDN, the speed is now: 25MiB/s:
![image](https://user-images.githubusercontent.com/1237528/71957148-f09a9f80-3227-11ea-9e67-cc8d74a3b86e.png)

The reason is the dns resolving is not working very well, after fix this, the speed is now: 25MiB/s, but we are still tuning.

**Comment by wwar** [comment] 2020-01-08 16:54
It has gotten worse, not better :-(

```
$ time wget http://download.pingcap.org/tidb-latest-linux-amd64.tar.gz
--2020-01-08 09:47:19--  http://download.pingcap.org/tidb-latest-linux-amd64.tar.gz
Resolving download.pingcap.org (download.pingcap.org)... 64.71.142.113, 64.71.142.59, 64.71.142.58, ...
Connecting to download.pingcap.org (download.pingcap.org)|64.71.142.113|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 344839814 (329M) [application/x-compressed]
Saving to: ‘tidb-latest-linux-amd64.tar.gz.2’

tidb-latest-linux-amd64.tar.gz.2                                                      100%[=========================================================================================================================================================================================================================>] 328.86M  1018KB/s    in 5m 54s  

2020-01-08 09:53:14 (952 KB/s) - ‘tidb-latest-linux-amd64.tar.gz.2’ saved [344839814/344839814]


real    5m55.393s
user    0m0.701s
sys     0m4.625s
$ time wget https://dev.mysql.com/get/Downloads/MySQL-8.0/mysql-8.0.18-linux-glibc2.12-x86_64.tar.xz    
--2020-01-08 09:53:42--  https://dev.mysql.com/get/Downloads/MySQL-8.0/mysql-8.0.18-linux-glibc2.12-x86_64.tar.xz
Resolving dev.mysql.com (dev.mysql.com)... 137.254.60.11
Connecting to dev.mysql.com (dev.mysql.com)|137.254.60.11|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://cdn.mysql.com//Downloads/MySQL-8.0/mysql-8.0.18-linux-glibc2.12-x86_64.tar.xz [following]
--2020-01-08 09:53:43--  https://cdn.mysql.com//Downloads/MySQL-8.0/mysql-8.0.18-linux-glibc2.12-x86_64.tar.xz
Resolving cdn.mysql.com (cdn.mysql.com)... 23.59.157.177
Connecting to cdn.mysql.com (cdn.mysql.com)|23.59.157.177|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 503854832 (481M) [text/plain]
Saving to: ‘mysql-8.0.18-linux-glibc2.12-x86_64.tar.xz.2’

mysql-8.0.18-linux-glibc2.12-x86_64.tar.xz.2                                          100%[=========================================================================================================================================================================================================================>] 480.51M  77.1MB/s    in 6.4s    

2020-01-08 09:53:50 (74.6 MB/s) - ‘mysql-8.0.18-linux-glibc2.12-x86_64.tar.xz.2’ saved [503854832/503854832]


real    0m7.247s
user    0m0.399s
sys     0m0.778s

```

**Comment by wwar** [comment] 2020-01-09 02:38
Here is an example in AWS' us-west-2 region (oregon). It is a little bit better than my download speeds, but still worse than MySQL (I'm on the west coast):
```
[ec2-user@ip-172-30-0-173 ~]$ time wget https://dev.mysql.com/get/Downloads/MySQL-8.0/mysql-8.0.18-linux-glibc2.12-x86_64.tar.xz 
--2020-01-09 02:29:53--  https://dev.mysql.com/get/Downloads/MySQL-8.0/mysql-8.0.18-linux-glibc2.12-x86_64.tar.xz
Resolving dev.mysql.com (dev.mysql.com)... 137.254.60.11
Connecting to dev.mysql.com (dev.mysql.com)|137.254.60.11|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://cdn.mysql.com//Downloads/MySQL-8.0/mysql-8.0.18-linux-glibc2.12-x86_64.tar.xz [following]
--2020-01-09 02:29:53--  https://cdn.mysql.com//Downloads/MySQL-8.0/mysql-8.0.18-linux-glibc2.12-x86_64.tar.xz
Resolving cdn.mysql.com (cdn.mysql.com)... 23.36.53.20
Connecting to cdn.mysql.com (cdn.mysql.com)|23.36.53.20|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 503854832 (481M) [text/plain]
Saving to: ‘mysql-8.0.18-linux-glibc2.12-x86_64.tar.xz’

100%[===========================================================================================================>] 503,854,832  157MB/s   in 3.1s   

2020-01-09 02:29:57 (157 MB/s) - ‘mysql-8.0.18-linux-glibc2.12-x86_64.tar.xz’ saved [503854832/503854832]


real	0m3.595s
user	0m0.410s
sys	0m0.963s
[ec2-user@ip-172-30-0-173 ~]$ time wget http://download.pingcap.org/tidb-latest-linux-amd64.tar.gz
--2020-01-09 02:30:00--  http://download.pingcap.org/tidb-latest-linux-amd64.tar.gz
Resolving download.pingcap.org (download.pingcap.org)... 47.246.17.230, 47.246.17.231, 47.246.17.232, ...
Connecting to download.pingcap.org (download.pingcap.org)|47.246.17.230|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 344194819 (328M) [application/x-compressed]
Saving to: ‘tidb-latest-linux-amd64.tar.gz’

100%[===========================================================================================================>] 344,194,819 8.13MB/s   in 40s    

2020-01-09 02:30:42 (8.19 MB/s) - ‘tidb-latest-linux-amd64.tar.gz’ saved [344194819/344194819]


real	0m41.945s
user	0m0.089s
sys	0m0.704s
```

If I try east coast USA (AWS us-east-1) the speeds for TiDB are better (22 MB/s vs. 127MB/s for MySQL). MySQL uses Akamai ($$$), but there are other options which perform better that are still low cost.

**Comment by n0vad3v** [comment] 2020-01-09 05:38
We've switched to cloudfront CDN for our oversea users, maybe you can try it again now.

Here is the `wget` report from one of my servers at Online.net, France.
```
root@novanetwork-fr:~# wget download.pingcap.org/tidb-latest-linux-amd64.tar.gz
--2020-01-09 05:34:16--  http://download.pingcap.org/tidb-latest-linux-amd64.tar.gz
Resolving download.pingcap.org (download.pingcap.org)... 2600:9000:2113:9c00:17:4e87:d0c0:93a1, 2600:9000:2113:8e00:17:4e87:d0c0:93a1, 2600:9000:2113:9000:17:4e87:d0c0:93a1, ...
Connecting to download.pingcap.org (download.pingcap.org)|2600:9000:2113:9c00:17:4e87:d0c0:93a1|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 344194819 (328M) [application/x-tar]
Saving to: ‘tidb-latest-linux-amd64.tar.gz’

tidb-latest-linux-amd64.ta 100%[======================================>] 328.25M   437MB/s    in 0.8s    

2020-01-09 05:34:17 (437 MB/s) - ‘tidb-latest-linux-amd64.tar.gz’ saved [344194819/344194819]
```

And here is the `wget` from Vultr, SFO.

```
root@novanetwork-sfo:~# wget http://download.pingcap.org/tidb-latest-linux-amd64.tar.gz
--2020-01-09 05:36:58--  http://download.pingcap.org/tidb-latest-linux-amd64.tar.gz
Resolving download.pingcap.org (download.pingcap.org)... 2600:9000:209c:f600:17:4e87:d0c0:93a1, 2600:9000:209c:be00:17:4e87:d0c0:93a1, 2600:9000:209c:8a00:17:4e87:d0c0:93a1, ...
Connecting to download.pingcap.org (download.pingcap.org)|2600:9000:209c:f600:17:4e87:d0c0:93a1|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 344194819 (328M) [application/x-tar]
Saving to: ‘tidb-latest-linux-amd64.tar.gz’

tidb-latest-linux-amd64.ta 100%[======================================>] 328.25M   151MB/s    in 2.2s    

2020-01-09 05:37:00 (151 MB/s) - ‘tidb-latest-linux-amd64.tar.gz’ saved [344194819/344194819]
```

**Comment by wwar** [comment] 2020-01-09 15:29
Thank you for fixing! It is now much faster for me too:
```
$ time wget http://download.pingcap.org/tidb-latest-linux-amd64.tar.gz
--2020-01-09 08:28:50--  http://download.pingcap.org/tidb-latest-linux-amd64.tar.gz
Resolving download.pingcap.org (download.pingcap.org)... 99.84.74.27, 99.84.74.32, 99.84.74.12, ...
Connecting to download.pingcap.org (download.pingcap.org)|99.84.74.27|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 344194819 (328M) [application/x-tar]
Saving to: ‘tidb-latest-linux-amd64.tar.gz.1’

tidb-latest-linux-amd64.tar.gz.1                                                               100%[===================================================================================================================================================================================================================================================>] 328.25M  58.9MB/s    in 5.8s    

2020-01-09 08:28:57 (56.3 MB/s) - ‘tidb-latest-linux-amd64.tar.gz.1’ saved [344194819/344194819]


real	0m6.134s
user	0m0.053s
sys	0m0.663s
```

**Comment by n0vad3v** [comment] 2020-01-09 15:54
I'm glad it helps. :)

**Comment by wwar** [comment] 2020-01-11 04:27
Sadly the mirrors seem to have changed back, and the issue is back :(
```
$ wget http://download.pingcap.org/tidb-latest-linux-amd64.tar.gz
--2020-01-10 21:26:14--  http://download.pingcap.org/tidb-latest-linux-amd64.tar.gz
Resolving download.pingcap.org (download.pingcap.org)... .64.71.142.59, 64.71.142.54, 64.71.142.58, ...
Connecting to download.pingcap.org (download.pingcap.org)|64.71.142.59|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 346418647 (330M) [application/x-compressed]
Saving to: ‘tidb-latest-linux-amd64.tar.gz.1’

tidb-latest-linux-amd64.tar.gz.1                                                              1%[===>                                                                                                                                                                                                                                      ]   5.82M   116KB/s    eta 23m 29s
```

**Comment by n0vad3v** [comment] 2020-01-14 03:40
Sorry for that, that's a temporary outage due to our CDN's problem, it should be fine now.

**Comment by wwar** [comment] 2020-01-15 02:34
Thanks @n0vad3v . You can close this issue, it's working again :-)

**Closed** 2020-01-15 03:35 UTC
Labels: type/bug
