### ISSUE TITLE
Incompatible cast json

### ISSUE THREAD

**Issue by breeswish** [pingcap/tidb#9593] opened 2019-03-07 07:50 UTC
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

TiDB:

```sql
mysql> use test;
Database changed
mysql> CREATE TABLE t1 (jdoc JSON);
Query OK, 0 rows affected (0.01 sec)

mysql> INSERT INTO t1 VALUES('{"key1": "value1", "key2": "value2"}');
Query OK, 1 row affected (0.00 sec)

mysql> INSERT INTO t1 VALUES(NULL);
Query OK, 1 row affected (0.00 sec)

mysql> INSERT INTO t1 VALUES('1');
Query OK, 1 row affected (0.00 sec)

mysql> INSERT INTO t1 VALUES('0');
Query OK, 1 row affected (0.00 sec)

mysql> INSERT INTO t1 VALUES('5');
Query OK, 1 row affected (0.00 sec)

mysql> SELECT * from t1 where jdoc;
ERROR 1105 (HY000): other error: cannot convert {"key1": "value1", "key2": "value2"}(type json.BinaryJSON) to bool
```

2. What did you expect to see?

MySQL:

```sql
mysql> use test;
Database changed
mysql> CREATE TABLE t1 (jdoc JSON);
Query OK, 0 rows affected (0.06 sec)

mysql> INSERT INTO t1 VALUES('{"key1": "value1", "key2": "value2"}');
Query OK, 1 row affected (0.01 sec)

mysql> INSERT INTO t1 VALUES(NULL);
Query OK, 1 row affected (0.00 sec)

mysql> INSERT INTO t1 VALUES('1');
Query OK, 1 row affected (0.00 sec)

mysql> INSERT INTO t1 VALUES('0');
Query OK, 1 row affected (0.00 sec)

mysql> INSERT INTO t1 VALUES('5');
Query OK, 1 row affected (0.00 sec)

mysql> SELECT * from t1 where jdoc;
+------+
| jdoc |
+------+
| 1    |
| 5    |
+------+
2 rows in set, 1 warning (0.00 sec)

mysql> show warnings;
+---------+------+------------------------------------------------------------------+
| Level   | Code | Message                                                          |
+---------+------+------------------------------------------------------------------+
| Warning | 3156 | Invalid JSON value for CAST to INTEGER from column jdoc at row 1 |
+---------+------+------------------------------------------------------------------+
1 row in set (0.00 sec)
```

**Comment by nullnotnil** [comment] 2020-07-23 22:38
Confirming I can still reproduce a different result from MySQL, but the error no longer occurs:
```sql
DROP TABLE IF EXISTS t1;
CREATE TABLE t1 (jdoc JSON);
INSERT INTO t1 VALUES('{"key1": "value1", "key2": "value2"}');
INSERT INTO t1 VALUES(NULL);
INSERT INTO t1 VALUES('1');
INSERT INTO t1 VALUES('0');
INSERT INTO t1 VALUES('5');
SELECT * from t1 where jdoc;

..

mysql> SELECT * from t1 where jdoc;
Empty set (0.00 sec)

mysql> 
mysql> SELECT tidb_version()\G
*************************** 1. row ***************************
tidb_version(): Release Version: v4.0.0-beta.2-821-gfe07417e6
Edition: Community
Git Commit Hash: fe07417e6b2f28eb334117d44640d0760d7e9866
Git Branch: master
UTC Build Time: 2020-07-22 12:51:37
GoVersion: go1.13
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
1 row in set (0.00 sec)
```

I believe that this may now be the same bug as https://github.com/pingcap/tidb/issues/12233

**Comment by nullnotnil** [comment] 2020-11-18 05:57
Closing as a duplicate of https://github.com/pingcap/tidb/issues/12233

**Closed by nullnotnil** 2020-11-18 05:57 UTC
Labels: severity/major, sig/execution, type/bug, type/duplicate
