### ISSUE TITLE
Incorrect description of tidb_build_stats_concurrency

### ISSUE THREAD

**Issue by 15767637775** [pingcap/tidb#57262] opened 2024-11-10 02:21 UTC
## Enhancement
the parameter `tidb_build_stats_concurrency`'s description: "the task is divided into multiple small tasks. Each task only works on one column or index" is wrong.

It actually controls the number of tables and partitions executed each time, so the document needs to be modified: https://docs.pingcap.com/zh/tidb/v6.5/statistics#tidb_build_stats_concurrency

**Comment by Rustin170506** [comment] 2024-11-11 02:18
Duplicate of https://github.com/pingcap/docs/issues/19364

**Closed by Rustin170506** 2024-11-11 02:18 UTC
Labels: type/enhancement
