### ISSUE TITLE
Performance enhance possiblity

### ISSUE THREAD

**Issue by nathan-gao** [pingcap/tidb#19598] opened 2020-08-30 12:32 UTC
## Performance Questions

I am using TiDB 4.04  and I think I have observed two performance bottlenecks. I have used sysbench(32 tables, 100000 lines data, point select test）to test the performance and generate flame graphs as follows.
![img1](https://user-images.githubusercontent.com/62699642/91658876-8dcf7e80-eafe-11ea-857e-aa2bb15ea8df.png)

I think the efficiency of 
```
executor.(*ExecStmt).FinishExecuteStmt
and
server.bufferedReadConn.Read
```
might have some way to improve.

![img2](https://user-images.githubusercontent.com/62699642/91658909-c3746780-eafe-11ea-901b-9db36d77215b.png)

![img3](https://user-images.githubusercontent.com/62699642/91658913-cff8c000-eafe-11ea-8455-20c593e3273b.png)

**Comment by nullnotnil** [comment] 2020-08-31 20:51
Thank you for the feedback!

The first issue looks like a duplicate of https://github.com/pingcap/tidb/issues/19539 - would you agree?

**Comment by jebter** [comment] 2024-06-05 11:34
The issue has not been updated for too long, so I will close it. If there are any updates, you can reopen it.

**Closed by jebter** 2024-06-05 11:34 UTC
Labels: type/question, type/performance
