### ISSUE TITLE
tidb failed to pass tpc-c test

### ISSUE THREAD

**Issue by wangpeibin713** [pingcap/tidb#2706] opened 2017-02-22 07:46 UTC
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

I have run the tpc-c test with 
* https://github.com/pingcap/tpcc-mysql
* https://github.com/Percona-Lab/tpcc-mysql

2. What did you expect to see?
get the benchmark like
```
<Constraint Check> (all must be [OK])
 [transaction percentage]
        Payment: 43.482682% (>=43.0%) [OK]
   Order-Status: 4.348866% (>= 4.0%) [OK]
       Delivery: 4.342884% (>= 4.0%) [OK]
    Stock-Level: 4.348866% (>= 4.0%) [OK]
 [response time (at least 90% passed)]
      NewOrder: 100.000000%  [OK]
      Payment: 100.000000%  [OK]
      Order Stat: 100.000000%  [OK]
      Delivery: 100.000000%  [OK]
      Slev: 100.000000%  [OK]
 NewOrder Total: 7268
 Payment Total: 7269
 Order Stat Total: 727
 Delivery Total: 726
 Slev Total: 727

<TpmC>
7265.215 TpmC
```
3. What did you see instead?
out error message like 

``` 
  payment 1:2
  0, 00000,
  payment 2:2
  neword 14:1
  0, 00000,
```
```
<Constraint Check> (all must be [OK])
 [transaction percentage]
        Payment: -nan% (>=43.0%) [NG] *
   Order-Status: -nan% (>= 4.0%) [NG] *
       Delivery: -nan% (>= 4.0%) [NG] *
    Stock-Level: -nan% (>= 4.0%) [NG] *
 [response time (at least 90% passed)]
      New-Order: -nan%  [NG] *
        Payment: -nan%  [NG] *
   Order-Status: -nan%  [NG] *
       Delivery: -nan%  [NG] *
    Stock-Level: -nan%  [NG] *

<TpmC>
                 0.000 TpmC
```

4. What version of Go are you using (`go version`)?

**Comment by shenli** [comment] 2017-02-22 07:49
@wangpeibin713 Thanks for your report! We will fix it.

**Comment by andelf** [comment] 2017-02-28 02:10
tpcc1000 test:

```
2017/02/28 10:01:13 conn.go:333: [error] lastCmd �
EINGESEESE, runtime error: invalid memory address or nil pointer dereference, goroutine 7235352 [running]:
github.com/pingcap/tidb/server.(*clientConn).Run.func1(0xc4cb2872c0)
        /home/jenkins/workspace/TIDB_POST_COMMIT_FLOW/go/src/github.com/pingcap/tidb/server/conn.go:332 +0xe2
panic(0xd844a0, 0xc420010070)
        /usr/local/go/src/runtime/panic.go:458 +0x243
github.com/pingcap/tidb/plan.(*typeInferrer).Leave(0xc4ff86e810, 0x1463460, 0xc487eccb40, 0x1463420, 0xc4eb2f5c00, 0x1470201)
        /home/jenkins/workspace/TIDB_POST_COMMIT_FLOW/go/src/github.com/pingcap/tidb/plan/typeinferer.go:62 +0x1022
github.com/pingcap/tidb/ast.(*ColumnNameExpr).Accept(0xc487eccb40, 0x145e060, 0xc4ff86e810, 0x1464220, 0xc4b8ab5ce0, 0xc47f07a700)
        /home/jenkins/workspace/TIDB_POST_COMMIT_FLOW/go/src/github.com/pingcap/tidb/ast/expressions.go:360 +0x11a
github.com/pingcap/tidb/ast.(*SelectField).Accept(0xc4b8ab5ce0, 0x145e060, 0xc4ff86e810, 0x1464220, 0xc436ab4240, 0xc420912801)
        /home/jenkins/workspace/TIDB_POST_COMMIT_FLOW/go/src/github.com/pingcap/tidb/ast/dml.go:294 +0xfa
github.com/pingcap/tidb/ast.(*FieldList).Accept(0xc500ec67b0, 0x145e060, 0xc4ff86e810, 0xc4dd9ff690, 0xc4209128f0, 0x1)
        /home/jenkins/workspace/TIDB_POST_COMMIT_FLOW/go/src/github.com/pingcap/tidb/ast/dml.go:318 +0xc6
github.com/pingcap/tidb/ast.(*SelectStmt).Accept(0xc500806b00, 0x145e060, 0xc4ff86e810, 0x114c052598, 0x40e00f, 0x17bb420)
        /home/jenkins/workspace/TIDB_POST_COMMIT_FLOW/go/src/github.com/pingcap/tidb/ast/dml.go:491 +0x449
github.com/pingcap/tidb/plan.InferType(0xc4d8abe540, 0x1464260, 0xc500806b00, 0xc44c0524e0, 0x1035f0c)
        /home/jenkins/workspace/TIDB_POST_COMMIT_FLOW/go/src/github.com/pingcap/tidb/plan/typeinferer.go:35 +0xac
github.com/pingcap/tidb/plan.Optimize(0x146fb40, 0xc4de6af110, 0x1464260, 0xc500806b00, 0x7fcace585000, 0xc420422360, 0xc4ff86e76b, 0xa, 0xa, 0x0)
        /home/jenkins/workspace/TIDB_POST_COMMIT_FLOW/go/src/github.com/pingcap/tidb/plan/optimizer.go:60 +0x78
github.com/pingcap/tidb/executor.(*ExecuteExec).Build(0xc44d474980, 0x1473140, 0xc4c5e87b80)
        /home/jenkins/workspace/TIDB_POST_COMMIT_FLOW/go/src/github.com/pingcap/tidb/executor/prepared.go:243 +0x328
github.com/pingcap/tidb/executor.(*statement).Exec(0xc4f07d0660, 0x146fb40, 0xc4de6af110, 0x0, 0x0, 0x0, 0x0)
        /home/jenkins/workspace/TIDB_POST_COMMIT_FLOW/go/src/github.com/pingcap/tidb/executor/adapter.go:115 +0x5ff
github.com/pingcap/tidb.runStmt(0x146fb40, 0xc4de6af110, 0x145de60, 0xc4f07d0660, 0x3, 0x3, 0x145de60, 0xc4f07d0660)
        /home/jenkins/workspace/TIDB_POST_COMMIT_FLOW/go/src/github.com/pingcap/tidb/tidb.go:176 +0x7d
github.com/pingcap/tidb.(*session).ExecutePreparedStmt(0xc4de6af110, 0xc40000000f, 0xc4ff86e780, 0x3, 0x3, 0x0, 0x0, 0xc4ff86e76b, 0xa)
        /home/jenkins/workspace/TIDB_POST_COMMIT_FLOW/go/src/github.com/pingcap/tidb/session.go:598 +0x11e
github.com/pingcap/tidb/server.(*TiDBStatement).Execute(0xc4c5dd1450, 0xc4ff86e780, 0x3, 0x3, 0x3, 0x3, 0xc4ff86e75a, 0x1)
        /home/jenkins/workspace/TIDB_POST_COMMIT_FLOW/go/src/github.com/pingcap/tidb/server/driver_tidb.go:63 +0x6b
github.com/pingcap/tidb/server.(*clientConn).handleStmtExecute(0xc4cb2872c0, 0xc4ff86e751, 0x24, 0x24, 0x25, 0x0)
        /home/jenkins/workspace/TIDB_POST_COMMIT_FLOW/go/src/github.com/pingcap/tidb/server/conn_stmt.go:166 +0x4cb
github.com/pingcap/tidb/server.(*clientConn).dispatch(0xc4cb2872c0, 0xc4ff86e751, 0x25, 0x24, 0x0, 0x0)
        /home/jenkins/workspace/TIDB_POST_COMMIT_FLOW/go/src/github.com/pingcap/tidb/server/conn.go:458 +0x801
github.com/pingcap/tidb/server.(*clientConn).Run(0xc4cb2872c0)
        /home/jenkins/workspace/TIDB_POST_COMMIT_FLOW/go/src/github.com/pingcap/tidb/server/conn.go:349 +0x139
github.com/pingcap/tidb/server.(*Server).onConn(0xc420906740, 0x146f420, 0xc4200295c8)
        /home/jenkins/workspace/TIDB_POST_COMMIT_FLOW/go/src/github.com/pingcap/tidb/server/server.go:209 +0x13e
created by github.com/pingcap/tidb/server.(*Server).Run
        /home/jenkins/workspace/TIDB_POST_COMMIT_FLOW/go/src/github.com/pingcap/tidb/server/server.go:173 +0x96
```

**Comment by andelf** [comment] 2017-02-28 07:16
with many error message:

```
error at thread_main
2006, HY000, MySQL server has gone away
```

The tpc-c test finally prints the results:

```
<Raw Results>
  [0] sc:0 lt:34  rt:35385136  fl:17701 avg_rt: 177.5 (5)
  [1] sc:0 lt:19  rt:35411995  fl:17717 avg_rt: 135.3 (5)
  [2] sc:0 lt:0  rt:3548224  fl:1775 avg_rt: -nan (5)
  [3] sc:0 lt:0  rt:3546723  fl:1774 avg_rt: -nan (80)
  [4] sc:0 lt:3  rt:3538230  fl:1770 avg_rt: 1300.4 (20)
 in 3600 sec.

<Raw Results2(sum ver.)>
  [0] sc:0  lt:34  rt:35385605  fl:17701
  [1] sc:0  lt:19  rt:35412471  fl:17717
  [2] sc:0  lt:0  rt:3548225  fl:1775
  [3] sc:0  lt:0  rt:3546731  fl:1774
  [4] sc:0  lt:3  rt:3538230  fl:1770

<Constraint Check> (all must be [OK])
 [transaction percentage]
        Payment: 33.93% (>=43.0%) [NG] *
   Order-Status: 0.00% (>= 4.0%) [NG] *
       Delivery: 0.00% (>= 4.0%) [NG] *
    Stock-Level: 5.36% (>= 4.0%) [OK]
 [response time (at least 90% passed)]
      New-Order: 0.00%  [NG] *
        Payment: 0.00%  [NG] *
   Order-Status: -nan%  [NG] *
       Delivery: -nan%  [NG] *
    Stock-Level: 0.00%  [NG] *

<TpmC>
                 0.567 TpmC
```

**Comment by shenli** [comment] 2017-02-28 07:27
@andelf 
@coocood is working on this.

**Comment by andelf** [comment] 2017-03-01 15:19
partially fixed. still some NG(not good) results .

```
<Raw Results>
  [0] sc:0 lt:2468  rt:13421555  fl:6722 avg_rt: 127.6 (5)
  [1] sc:0 lt:2737  rt:12886877  fl:6440 avg_rt: 75.8 (5)
  [2] sc:0 lt:0  rt:1834474  fl:917 avg_rt: -nan (5)
  [3] sc:0 lt:0  rt:1835461  fl:917 avg_rt: -nan (80)
  [4] sc:780 lt:138  rt:0  fl:0 avg_rt: 64.4 (20)
 in 10800 sec.

<Raw Results2(sum ver.)>
  [0] sc:0  lt:2468  rt:13421589  fl:6722
  [1] sc:0  lt:2737  rt:12886906  fl:6440
  [2] sc:0  lt:0  rt:1834476  fl:917
  [3] sc:0  lt:0  rt:1835461  fl:917
  [4] sc:780  lt:138  rt:0  fl:0

<Constraint Check> (all must be [OK])
 [transaction percentage]
        Payment: 44.70% (>=43.0%) [OK]
   Order-Status: 0.00% (>= 4.0%) [NG] *
       Delivery: 0.00% (>= 4.0%) [NG] *
    Stock-Level: 14.99% (>= 4.0%) [OK]
 [response time (at least 90% passed)]
      New-Order: 0.00%  [NG] *
        Payment: 0.00%  [NG] *
   Order-Status: -nan%  [NG] *
       Delivery: -nan%  [NG] *
    Stock-Level: 84.97%  [NG] *

<TpmC>
                 13.711 TpmC
```

**Comment by andelf** [comment] 2017-03-01 18:09
NG reports is due to MYSQL_DATA_TRUNCATED error.
maybe caused by different return value size.

**Comment by andelf** [comment] 2017-03-01 20:45
```sql
SELECT o_id, o_entry_d, COALESCE(o_carrier_id,0) FROM orders WHERE o_w_id = ? AND o_d_id = ? AND o_c_id = ? AND o_id = (SELECT MAX(o_id) FROM orders WHERE o_w_id = ? AND o_d_id = ? AND o_c\
_id = ?)
```

in MySQL:  COALESCE(o_carrier_id,0) is an int(4)
in TiDB:  COALESCE(o_carrier_id,0) seems to be a decimal.  Is StmtFetch support limited?

**Comment by tiancaiamao** [comment] 2017-03-03 09:13
PTAL @coocood

**Comment by andelf** [comment] 2017-03-07 05:49
COALESCE() fixed in #2788

**Comment by andelf** [comment] 2017-03-07 05:52
Now TiDB can't run multithread TPC-C tests:


payment 1:10
1105, HY000, [201] can not retry select for update statement

TiDB log:

```
2017/03/07 13:32:13 2pc.go:485: [info] 2PC clean up done, tid: 390296956597698580
2017/03/07 13:32:13 simple.go:134: [info] [176] execute rollback statement
2017/03/07 13:32:13 txn.go:169: [info] [kv] Rollback txn 390296956637020167
2017/03/07 13:32:13 session.go:267: [warning] [170] finished txn:<nil>, [170] can not retry select for update statement
2017/03/07 13:32:13 session.go:554: [warning] [170] session error:
/home/ubuntu/go/src/github.com/pingcap/tidb/session.go:329: [170] can not retry select for update statement
/home/ubuntu/go/src/github.com/pingcap/tidb/session.go:268:
/home/ubuntu/go/src/github.com/pingcap/tidb/tidb.go:189:
{
  "currDBName": "tpcc100",
  "id": 170,
  "preparedStmtCount": 35,
  "stauts": 0,
  "strictMode": false,
  "user": "root@172.233.1.113"
}
2017/03/07 13:32:13 conn.go:356: [warning] [170] dispatch error:
id:170, addr:172.233.1.113:39024 status:0, collation:latin1_swedish_ci, user:root
commit
/home/ubuntu/go/src/github.com/pingcap/tidb/session.go:329: [170] can not retry select for update statement
/home/ubuntu/go/src/github.com/pingcap/tidb/session.go:268:
/home/ubuntu/go/src/github.com/pingcap/tidb/tidb.go:189:
/home/ubuntu/go/src/github.com/pingcap/tidb/session.go:556:
/home/ubuntu/go/src/github.com/pingcap/tidb/server/conn.go:661:
```

**Comment by andelf** [comment] 2017-03-12 10:23
@wangpeibin713 

Fixed. :)
try update tidb-server and run TPC-C test.

**Closed** 2017-09-13 13:33 UTC
Labels: bug
