### ISSUE TITLE
Incorrect result of index look up scan

### ISSUE THREAD

**Issue by victorggsimida** [pingcap/tidb#7811] opened 2018-09-28 10:10 UTC
1. table schema

```
CREATE TABLE `table123` (
  `id` int(11) NOT NULL DEFAULT '0',
  `oln` varchar(255) NOT NULL DEFAULT '',
  `old` varchar(255) NOT NULL DEFAULT '',
  `nnm` varchar(255) NOT NULL DEFAULT '',
  `ndo` varchar(255) NOT NULL DEFAULT '',
  `updatetime` datetime NOT NULL,
  `synctime` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`,`updatetime`),
  KEY `id` (`id`),
  KEY `oln` (`oln`,`old`),
  KEY `nnm` (`nnm`,`ndo`)
) ENGINE=InnoDB DEFAULT

```

2. execute sql

execute sql and select columns(with some colmun not in pk key)

there is two row data with the same pk value.

but if i only select pk column ,the data is right.

```
mysql> select id,updatetime,synctime  from table123 where id=15271137;
+----------+---------------------+---------------------+
| id      | updatetime          | synctime            |
+----------+---------------------+---------------------+
| 15271137 | 2018-09-19 15:32:56 | 2018-09-20 00:48:05 |
| 15271137 | 2018-09-19 15:32:56 | 2018-09-20 00:48:05 |
+----------+---------------------+---------------------+
2 rows in set (0.00 sec)

mysql> explain select id,updatetime,synctime  from table123 where id=15271137;
+--------------------+-------+------+--------------------------------------------------------------------------+
| id                 | count | task | operator info                                                            |
+--------------------+-------+------+--------------------------------------------------------------------------+
| IndexLookUp_13     | 4.03  | root |                                                                          |
| 鈹溾攢IndexScan_11 | 4.03  | cop  | table:table123, index:id, range:[15271137,15271137], keep order:false |
| 鈹斺攢TableScan_12 | 4.03  | cop  | table:table123, keep order:false                                       |
+--------------------+-------+------+--------------------------------------------------------------------------+
3 rows in set (0.00 sec)

mysql> select id,updatetime,oln  from table123 where id=15271137;
+----------+---------------------+------------------+
| id      | updatetime          | oln          |
+----------+---------------------+------------------+
| 15271137 | 2018-09-19 15:32:56 | 11111 |
| 15271137 | 2018-09-19 15:32:56 | 1111 |
+----------+---------------------+------------------+


mysql> select id,updatetime  from table123 where id=15271137;
+----------+---------------------+
| id      | updatetime          |
+----------+---------------------+
| 15271137 | 2018-09-19 15:32:56 |
+----------+---------------------+
1 row in set (0.00 sec)

mysql> explain select id,updatetime  from table123 where id=15271137;
+-------------------+-------+------+--------------------------------------------------------------------------------------+
| id                | count | task | operator info                                                                        |
+-------------------+-------+------+--------------------------------------------------------------------------------------+
| IndexReader_9     | 7.06  | root | index:IndexScan_8                                                                    |
| 鈹斺攢IndexScan_8 | 7.06  | cop  | table:table123, index:id, updatetime, range:[15271137,15271137], keep order:false |
+-------------------+-------+------+--------------------------------------------------------------------------------------+
2 rows in set (0.00 sec)

```

3. version info

```
| Release Version: v2.1.0-beta-229-g5404e2e
Git Commit Hash: 5404e2eaae27b9ce31264a4eff0a41aa92ffe328
Git Branch: master
UTC Build Time: 2018-08-14 01:46:09
GoVersion: go version go1.10.2 linux/amd64
Race Enabled: false
TiKV Min Version: 2.1.0-alpha.1-ff3dd160846b7d1aed9079c389fc188f7f5ea13e |
TiKV
Release Version:   2.1.0-beta
Git Commit Hash:   96022a982b6b34d9cd8b690cf6d4b0b85ffae247
Git Commit Branch: master
UTC Build Time:    2018-08-06 11:53:06
Rust Version:      rustc 1.29.0-nightly (4f3c7a472 2018-07-17)
```

4. my opinion

```
maybe the data in `id` index is wrong.
this row data is insert by sql ' insert into table select * from ...'



before thie case, i have another case with the same problem:  sql print out unbelieve result
```

5. my test

```
create another table with 

create table test456 like table123;
insert into test456 select * From table123;
and execute the same sql:

the result is fine. all is ok.
and explain is the same 
```

**Comment by eurekaka** [comment] 2018-09-28 10:53
The plan looks reasonable, second query uses index scan because selected columns are covered by primary key index.

The table `table123` should be corrupted, could you please provide the steps you use to build `table123`? thanks

**Comment by lamxTyler** [comment] 2018-09-28 10:55
@victorggsimida Could you run `admin check table table123` and see the result?

**Comment by victorggsimida** [comment] 2018-09-28 14:21
@eurekaka   i know the plan is ok. i do not doubt that.


i doubt about the result.  i show the plan to explain the reason for this case.


the key is the wrong result!

**Comment by lysu** [comment] 2018-09-28 14:44
@victorggsimida It seems meet table/index inconsistent question..

maybe we need more detail reproduce step to build `table123`

is it load to table `t` first then put into `table123` using `insert into table123 select * from t`??

which isolation-level are used during `insert into table123 select * from t`?

**Comment by victorggsimida** [comment] 2018-09-28 14:49
@lysu thank you for your answer

1. user mydumper to dump one from mysql 5.7
2. user loader to load one to table123(change the name)  with option : -B table -S one
3. update table123 :  insert into table123 select * from t.   t is a table   which is synced from mysql

**Comment by lysu** [comment] 2018-09-29 07:33
@victorggsimida thanks your detail feedback...I tried but cannot reproduce in my env

- can you reproduce it ~~? (e.g. create new table1234, then `insert into table1234 select * from t` and `admin check table table1234`)
- what about `t`'s schema?  what different between `t` and `table123`~? after execute insert-select any warning(execute `show warnings`)
- again,  which isolation-level are used during insert into table123 select * from t? there are known problem when user use `read-committed` isolation level may cause table/index inconsistent problem, you can check this by see tidb-server log file whether contains any `READ-COMMITED` if insert is executed by program or script.

**Comment by victorggsimida** [comment] 2018-09-29 08:37
@lysu  appreciate your work. thank you.

1. reproduce it? i am not sure. i can 
2. t schema is almost the same as table1234 but this t table has no pk key.
and the sql is insert ignore into  select * from t;
warnings: we did not notice. we did not user show warnigns
 
3. REPEATABLE-READ.  we did not change the iso level.

**Comment by victorggsimida** [comment] 2018-10-11 08:48
@lysu  

1. how  to rebuild the table ? 
2. the probility of corrupt table is high? or low? how to monitor this problem? amin check every table in tidb?

**Comment by lysu** [comment] 2018-10-11 09:08
hi @victorggsimida 

1. I mean run try `insert into table1234 select * from t and admin check table tableX` several times, and try to reproduct it?

2. this question is almost never happens, it's bug if it happen

**Comment by lysu** [comment] 2018-10-11 09:13
@victorggsimida  is any tidb error log during `insert into table1234 select * from t ` in 2018-09-28?

**Comment by crazycs520** [comment] 2018-10-11 09:35
Hi, @victorggsimida , I have a question. From your issue description, the primary key of table123 is (id, updatetime), but there is 2 same primary id record in table123;
```sql
mysql> select id,updatetime,synctime  from table123 where id=15271137;
+----------+---------------------+---------------------+
| id      | updatetime          | synctime            |
+----------+---------------------+---------------------+
| 15271137 | 2018-09-19 15:32:56 | 2018-09-20 00:48:05 |
| 15271137 | 2018-09-19 15:32:56 | 2018-09-20 00:48:05 |
+----------+---------------------+---------------------+
2 rows in set (0.00 sec)
```
If you load data from mysql, Could you check the original data table to see if there are 2 same primary id record?

**Comment by victorggsimida** [comment] 2018-10-12 03:15
@crazycs520  this two rows is  inserted by  sql "insert into  table123 select * from  source"  and not by using loader.

And I  check the original data in source table and find it has one row data.

**Comment by crazycs520** [comment] 2018-10-12 03:19
@victorggsimida , Could you provide the table schema of the `source` table？

**Comment by crazycs520** [comment] 2018-10-12 03:51
@victorggsimida em... the table schema of souce are not same with table123, `insert into table123 select * from source` will return `Column count doesn't match value count at row 1`.
 I still cannot reproduce the bug, if you can reproduce, could you provide a sql script to reproduce this bug, include create table `table123`, `source`, and insert data to souse and so on... Thanks very much.

**Comment by victorggsimida** [comment] 2018-10-12 07:14
@crazycs520  sry , mislead u. when   insert into table123 (columns except synctime) ,  select  (columns) from source,  not using *.

**Comment by tiancaiamao** [comment] 2018-10-15 14:50
Obviously, the data was broken, this means potential bugs.
Is there any error in the TiDB log at that time? it maybe helpful for us to debug

**Comment by jackysp** [comment] 2018-10-31 11:11
This potential bug may relate to https://github.com/pingcap/mydumper/pull/3 .

**Comment by nullnotnil** [comment] 2020-07-10 17:09
I am going to close this issue as stale, but feel free to reopen it if you are able to reproduce the corruption in the latest version.

Thanks!

**Closed by nullnotnil** 2020-07-10 17:09 UTC
Labels: component/executor, type/bug
