### ISSUE TITLE
table partition prune similar table structure but don't return same sql plan

### ISSUE THREAD

**Issue by dmf1721511982** [pingcap/tidb#41179] opened 2023-02-08 01:28 UTC
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

CREATE TABLE quarterly_report_status1 (
    report_id INT NOT NULL,
    report_status VARCHAR(20) NOT NULL,
    report_updated TIMESTAMP(3) NOT NULL 
)
PARTITION BY RANGE ( FLOOR(UNIX_TIMESTAMP(report_updated)*1000 )) (
    PARTITION p0 VALUES LESS THAN ( UNIX_TIMESTAMP('2008-01-01 00:00:00')*1000 ),
    PARTITION p1 VALUES LESS THAN ( UNIX_TIMESTAMP('2008-04-01 00:00:00') *1000),
    PARTITION p2 VALUES LESS THAN ( UNIX_TIMESTAMP('2008-07-01 00:00:00') *1000),
    PARTITION p3 VALUES LESS THAN ( UNIX_TIMESTAMP('2008-10-01 00:00:00') *1000),
    PARTITION p4 VALUES LESS THAN ( UNIX_TIMESTAMP('2009-01-01 00:00:00') *1000),
    PARTITION p5 VALUES LESS THAN ( UNIX_TIMESTAMP('2009-04-01 00:00:00') *1000),
    PARTITION p6 VALUES LESS THAN ( UNIX_TIMESTAMP('2009-07-01 00:00:00') *1000 ),
    PARTITION p7 VALUES LESS THAN ( UNIX_TIMESTAMP('2009-10-01 00:00:00') *1000 ),
    PARTITION p8 VALUES LESS THAN ( UNIX_TIMESTAMP('2010-01-01 00:00:00') *1000),
    PARTITION p9 VALUES LESS THAN (MAXVALUE)
);

CREATE TABLE quarterly_report_status2 (
    report_id INT NOT NULL,
    report_status VARCHAR(20) NOT NULL,
    report_updated TIMESTAMP(3) NOT NULL 
)
PARTITION BY RANGE ( FLOOR(UNIX_TIMESTAMP(`report_updated`)) ) (
    PARTITION p0 VALUES LESS THAN ( UNIX_TIMESTAMP('2008-01-01 00:00:00')),
    PARTITION p1 VALUES LESS THAN ( UNIX_TIMESTAMP('2008-04-01 00:00:00') ),
    PARTITION p2 VALUES LESS THAN ( UNIX_TIMESTAMP('2008-07-01 00:00:00') ),
    PARTITION p3 VALUES LESS THAN ( UNIX_TIMESTAMP('2008-10-01 00:00:00') ),
    PARTITION p4 VALUES LESS THAN ( UNIX_TIMESTAMP('2009-01-01 00:00:00') ),
    PARTITION p5 VALUES LESS THAN ( UNIX_TIMESTAMP('2009-04-01 00:00:00') ),
    PARTITION p6 VALUES LESS THAN ( UNIX_TIMESTAMP('2009-07-01 00:00:00')  ),
    PARTITION p7 VALUES LESS THAN ( UNIX_TIMESTAMP('2009-10-01 00:00:00')  ),
    PARTITION p8 VALUES LESS THAN ( UNIX_TIMESTAMP('2010-01-01 00:00:00') ),
    PARTITION p9 VALUES LESS THAN (MAXVALUE)
);

SET tidb_partition_prune_mode = 'dynamic';
SHOW  VARIABLES LIKE '%tidb_partition_prune_mode%';

 EXPLAIN ANALYZE SELECT COUNT(*) FROM quarterly_report_status1 AS h WHERE h.report_updated>= '2008-11-02 00:00:00.000' AND h.report_updated< '2008-11-02 15:36:37.000';

 EXPLAIN ANALYZE SELECT COUNT(*) FROM quarterly_report_status2 AS h WHERE h.report_updated>= '2008-11-02 00:00:00.000' AND h.report_updated< '2008-11-02 15:36:37.000';

### 2. What did you expect to see? (Required)

these two sqls return same sql plan

### 3. What did you see instead (Required)
the sql 1 return
![image](https://user-images.githubusercontent.com/110949082/217404946-51052e79-809f-45e3-88b6-556b31d2aafb.png)
and the sql 2 return
![image](https://user-images.githubusercontent.com/110949082/217404972-c3f13a94-6749-46b0-a78a-1b65cf53883a.png)

### 4. What is your TiDB version? (Required)
6.5.0

**Comment by Yisaer** [comment] 2023-02-17 02:56
Did u analyze the partition table after u enable `dynamic` partition prune mode? Optimizer needs the partition table has been analyzed, if not so, tidb will still use static plan even u enabled dynamic partition prune mode as the document mentioned https://docs.pingcap.com/tidb/stable/partitioned-table#dynamic-pruning-mode

**Comment by Yisaer** [comment] 2023-02-20 01:51
I think the unexpected behavior is caused by the un-analyzed partition table as I explained before, thus I will close this issue now, feel free to comment or reopen if u have any further comments.

**Closed by Yisaer** 2023-02-20 01:51 UTC
Labels: type/bug, sig/planner, severity/major, affects-6.5, affects-6.6

**Comment by dmf1721511982** [comment] 2023-03-08 09:09
i have ANALYZE TABLE quarterly_report_status1;
and ANALYZE TABLE quarterly_report_status2;
bug the sql1 return
![image](https://user-images.githubusercontent.com/110949082/223670930-b7cf64a7-e490-43f7-964a-b91e09aa7125.png)
and the sql2 return 
![image](https://user-images.githubusercontent.com/110949082/223671025-1d4b28df-911a-4353-b657-6d7f51c19c84.png)
