### ISSUE TITLE
TiDB crashed while analyzing table in tpcc with `tidb_analyze_version=2`

### ISSUE THREAD

**Issue by PragmaTwice** [pingcap/tidb#26547] opened 2021-07-26 04:20 UTC
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```shell
mysql -Be RESTORE DATABASE * from 's3://benchmark/tpcc-1000-new'
```

```
mysql> set tidb_analyze_version=1;
Query OK, 0 rows affected (0.03 sec)

mysql> analyze table tpcc.customer;
Query OK, 0 rows affected (59.23 sec)

mysql> set tidb_analyze_version=2;
Query OK, 0 rows affected (0.03 sec)

mysql> analyze table tpcc.customer;
ERROR 2013 (HY000): Lost connection to MySQL server during query
```

### 4. What is your TiDB version? (Required)
```
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| tidb_version()

                                                                            |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Release Version: v5.2.0-alpha-316-g014005ab6
Edition: Community
Git Commit Hash: 014005ab68b5c9a28795d13c1ca685cf46a3be7e
Git Branch: master
UTC Build Time: 2021-07-17 09:44:18
GoVersion: go1.16.4
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.14 sec)
```

**Comment by winoros** [comment] 2021-07-28 13:50
I guess this is caused by OOM. I'll contact you for more information.

**Comment by winoros** [comment] 2021-08-05 07:55
It will be improved in the next sprint. Move down the severity.

**Comment by winoros** [comment] 2021-11-23 09:47
closed via https://github.com/pingcap/tidb/pull/28999

**Closed by winoros** 2021-11-23 09:47 UTC
Labels: type/bug, sig/planner, severity/moderate
