### ISSUE TITLE
Is there a plan to support polygon type, When?

### ISSUE THREAD

**Issue by csunny** [pingcap/tidb#10123] opened 2019-04-11 07:17 UTC
When we use the parser, the mysql datatype polygon is not supported,  Is there a plan to support it?

When?

**Comment by lysu** [comment] 2019-04-11 11:11
Hi @csunny, TiDB has no roadmap to support Geometry function in the short term.

and you just want to parser support this? if so, make parser support syntax is easier, also welcome issue parser PR :D

**Comment by morgo** [comment] 2020-12-07 17:24
I am going to close this as a duplicate of https://github.com/pingcap/tidb/issues/6347

Please feel free to re-open this issue if you have additional questions. Thanks!

**Closed by morgo** 2020-12-07 17:24 UTC
Labels: component/parser, type/question
