### ISSUE TITLE
Strange index issue

### ISSUE THREAD

**Issue by 474420502** [pingcap/tidb#7663] opened 2018-09-11 03:18 UTC
## Description
```
+---------------+------------+----------+--------------+-------------+-----------+-------------+----------+--------+------+------------+---------+---------------+
| Table         | Non_unique | Key_name | Seq_in_index | Column_name | Collation | Cardinality | Sub_part | Packed | Null | Index_type | Comment | Index_comment |
+---------------+------------+----------+--------------+-------------+-----------+-------------+----------+--------+------+------------+---------+---------------+
| log_ad_result |          0 | PRIMARY  |            1 | channel     | A         |           0 |     NULL | NULL   | YES  | BTREE      |         |               |
| log_ad_result |          0 | PRIMARY  |            2 | ad_id       | A         |           0 |     NULL | NULL   | YES  | BTREE      |         |               |
| log_ad_result |          0 | PRIMARY  |            3 | ts_update   | A         |           0 |     NULL | NULL   | YES  | BTREE      |         |               |
+---------------+------------+----------+--------------+-------------+-----------+-------------+----------+--------+------+------------+---------+---------------+
mysql> select count(1) from log_ad_result use index(`PRIMARY`) WHERE ad_id='ad-3808341' limit 1;
+----------+
| count(1) |
+----------+
|       35 |
+----------+
1 row in set (3.55 sec)

mysql> select count(1) from log_ad_result use index(`PRIMARY`) WHERE ad_id='ad-3808341' and ts_update >= '2018-09-10' limit 1;
+----------+
| count(1) |
+----------+
|       36 |
+----------+
1 row in set (36.44 sec)

+----------------------------+----------+------+---------------------------------------------------------------------------------------------------------+
| id                         | count    | task | operator info                                                                                           |
+----------------------------+----------+------+---------------------------------------------------------------------------------------------------------+
| Limit_11                   | 1.00     | root | offset:0, count:1                                                                                       |
| └─StreamAgg_27             | 1.00     | root | funcs:count(col_0)                                                                                      |
|   └─IndexReader_28         | 1.00     | root | index:StreamAgg_15                                                                                      |
|     └─StreamAgg_15         | 1.00     | cop  | funcs:count(1)                                                                                          |
|       └─Selection_26       | 3333.33  | cop  | eq(log.log_ad_result.ad_id, "ad-3808341"), ge(log.log_ad_result.ts_update, 2018-09-10 00:00:00.000000)  |
|         └─IndexScan_25     | 10000.00 | cop  | table:log_ad_result, index:channel, ad_id, ts_update, range:[NULL,+inf], keep order:false, stats:pseudo |
+----------------------------+----------+------+---------------------------------------------------------------------------------------------------------+
6 rows in set (0.01 sec)


mysql> explain select count(1) from log_ad_result use index(`PRIMARY`) WHERE ad_id='ad-3808341' limit 1;
+----------------------------+----------+------+---------------------------------------------------------------------------------------------------------+
| id                         | count    | task | operator info                                                                                           |
+----------------------------+----------+------+---------------------------------------------------------------------------------------------------------+
| Limit_11                   | 1.00     | root | offset:0, count:1                                                                                       |
| └─StreamAgg_27             | 1.00     | root | funcs:count(col_0)                                                                                      |
|   └─IndexReader_28         | 1.00     | root | index:StreamAgg_15                                                                                      |
|     └─StreamAgg_15         | 1.00     | cop  | funcs:count(1)                                                                                          |
|       └─Selection_26       | 3333.33  | cop  | eq(log.log_ad_result.ad_id, "ad-3808341")                                                               |
|         └─IndexScan_25     | 10000.00 | cop  | table:log_ad_result, index:channel, ad_id, ts_update, range:[NULL,+inf], keep order:false, stats:pseudo |
+----------------------------+----------+------+---------------------------------------------------------------------------------------------------------+
6 rows in set (0.00 sec)
```

超级诡异!
## SIG slack channel

 [#sig-planner](https://slack.tidb.io/invite?team=tidb-community&channel=sig-planner&ref=high-performance)

## Score

300

## Mentor

- @lzmhhh123

**Comment by zz-jason** [comment] 2020-04-11 09:40
Hi @474420502, Could you post a minimal reproduce step here so that we can investigate this issue? We need at least these informations:

- result of `show create table log_ad_result;`
- tidb version, that's the result `select tidb_version();`

**Comment by 474420502** [comment] 2020-04-13 07:12
@zz-jason  sorry,  i go to another company.  this index `where ad_id  = '%%'` is fast in theory.  the index of update time is used in first, so is very slow.  i forget more!

**Comment by wjhuang2016** [comment] 2020-12-04 13:34
Close this issue because it can not reproduce.

**Closed by wjhuang2016** 2020-12-04 13:34 UTC
Labels: challenge-program, severity/moderate, sig/planner, status/can't-reproduce, status/help-wanted, type/bug
