### ISSUE TITLE
server: session variables was not changed when execute the mysql command 'ComChangeUser'

### ISSUE THREAD

**Issue by knull-cn** [pingcap/tidb#33699] opened 2022-04-02 17:04 UTC
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
- set some session variable 
- execute 'ComChangeUser'
- show the session variable , the values was the previous session setted(not the default values)

### 2. What did you expect to see? (Required)
show session variable should the default values.

### 3. What did you see instead (Required)
the values was the previous session setted

### 4. What is your TiDB version? (Required)

v5.3.0

**Comment by knull-cn** [comment] 2022-04-02 17:07
check code by java was here:
```java
import java.sql.*;

import com.mysql.cj.jdbc.JdbcConnection;

public class Client {
    public static void main(String args[]) {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            JdbcConnection con = (JdbcConnection) DriverManager.getConnection("jdbc:mysql://localhost:4000/test", "root", "tidb");

            ResultSet rs = con.createStatement().executeQuery("select @a;");
            if (rs.next()) {
                String i = rs.getString(1);
                System.out.println("before set : a= " + i);
            }
            con.createStatement().execute("set @a = 1;");
            rs.close();
            rs = con.createStatement().executeQuery("select @a;");
            if (rs.next()) {
                String i = rs.getString(1);
                System.out.println("after set : a= " + i);
            }
           // switch anther user.
            con.changeUser("tidb", "tidb");

            rs = con.createStatement().executeQuery("select @a;");
            if (rs.next()) {
                String i = rs.getString(1);
                System.out.println("after changeUser : a= " + i);
            }

            con.close();
        } catch (Exception e) {
            System.out.println(e);
        }
    }
}
```

**Comment by knull-cn** [comment] 2022-04-02 17:20
After https://github.com/pingcap/tidb/pull/24991, TiDB  create new ctx object in `clientConn::openSessionAndDoAuth` https://github.com/pingcap/tidb/blob/v5.2.0/server/conn.go#L768-L776 . 

but in handleChangeUser, `ctx` only call `close` but not set `nil` , so can't create new `ctx`, and use old session variables , see here : https://github.com/pingcap/tidb/blob/v5.2.0/server/conn.go#L2170-L2178

this was import with v5.2.0 and affected all version after v5.2.0

**Comment by bb7133** [comment] 2022-04-03 02:04
@knull-cn Thanks! Since you've found the root cause, are you interested in closing it by a PR?

**Comment by knull-cn** [comment] 2022-04-03 04:47
> @knull-cn Thanks! Since you've found the root cause, are you interested in closing it by a PR?

yes , I'll PR later

**Closed** 2022-04-08 06:54 UTC
Labels: type/bug, sig/sql-infra, severity/major, affects-5.2, affects-5.3, affects-5.4, affects-6.0

**Comment by tiancaiamao** [comment] 2022-05-07 01:21
**!!- Note for cherry-picker -!!**: the fix PR for this one would introduce other bug https://github.com/pingcap/tidb/issues/33892
So they must be handled together!
