### ISSUE TITLE
no database selectd error?

### ISSUE THREAD

**Issue by denghuancong** [pingcap/tidb#7681] opened 2018-09-12 14:01 UTC
tidb version: v2.0.4
2 proxysql proxy, proxysql-1.4.8-1-centos7.x86_64.rpm
3 tidb server
3 pd server
3 tikv server
-----------------------------------------
we use github.com/go-xorm/xorm("version 0.7.0")  to connect tidb cluster, we create multi connections connect to the proxy, some connection return "No database selected", some are succeed .

we found tidb log , the log as following:
```
2018/09/11 19:47:41.598 server.go:305: [info] [con:45890] close connection
2018/09/11 19:48:34.357 conn.go:487: [warning] [con:13864] dispatch error:
id:13864, addr:10.18.180.138:46364 status:2, collation:utf8_general_ci, user:root
"SELECT `id`, `path`, `action_node_name`, `source_project_id`, `listen_project_id`, `status`, `create_time`, `modify_time`, `delete_time` FROM `t_cross_cluster_watch_item` WHERE (action_node_name=?)"
[planner:1046]No database selected
/home/jenkins/workspace/build_tidb_2.0/go/src/github.com/pingcap/tidb/plan/preprocess.go:506:
/home/jenkins/workspace/build_tidb_2.0/go/src/github.com/pingcap/tidb/plan/preprocess.go:36:
/home/jenkins/workspace/build_tidb_2.0/go/src/github.com/pingcap/tidb/executor/prepared.go:131:
/home/jenkins/workspace/build_tidb_2.0/go/src/github.com/pingcap/tidb/session/session.go:875:
/home/jenkins/workspace/build_tidb_2.0/go/src/github.com/pingcap/tidb/server/conn_stmt.go:52:
2018/09/11 19:48:34.381 conn.go:487: [warning] [con:13864] dispatch error:
id:13864, addr:10.18.180.138:46364 status:2, collation:utf8_general_ci, user:root
"SELECT `id`, `path`, `action_node_name`, `source_project_id`, `listen_project_id`, `status`, `create_time`, `modify_time`, `delete_time` FROM `t_cross_cluster_watch_item` WHERE (action_node_name=?)"
[planner:1046]No database selected
/home/jenkins/workspace/build_tidb_2.0/go/src/github.com/pingcap/tidb/plan/preprocess.go:506:
/home/jenkins/workspace/build_tidb_2.0/go/src/github.com/pingcap/tidb/plan/preprocess.go:36:
/home/jenkins/workspace/build_tidb_2.0/go/src/github.com/pingcap/tidb/executor/prepared.go:131:
/home/jenkins/workspace/build_tidb_2.0/go/src/github.com/pingcap/tidb/session/session.go:875:
/home/jenkins/workspace/build_tidb_2.0/go/src/github.com/pingcap/tidb/server/conn_stmt.go:52:
2018/09/11 19:48:34.413 conn.go:487: [warning] [con:13864] dispatch error:
id:13864, addr:10.18.180.138:46364 status:2, collation:utf8_general_ci, user:root
"SELECT `id`, `path`, `action_node_name`, `source_project_id`, `listen_project_id`, `status`, `create_time`, `modify_time`, `delete_time` FROM `t_cross_cluster_watch_item` WHERE (action_node_name=?)"
[planner:1046]No database selected
/home/jenkins/workspace/build_tidb_2.0/go/src/github.com/pingcap/tidb/plan/preprocess.go:506:
/home/jenkins/workspace/build_tidb_2.0/go/src/github.com/pingcap/tidb/plan/preprocess.go:36:
/home/jenkins/workspace/build_tidb_2.0/go/src/github.com/pingcap/tidb/executor/prepared.go:131:
/home/jenkins/workspace/build_tidb_2.0/go/src/github.com/pingcap/tidb/session/session.go:875:
/home/jenkins/workspace/build_tidb_2.0/go/src/github.com/pingcap/tidb/server/conn_stmt.go:52:
```

**Comment by shenli** [comment] 2018-09-12 14:04
@denghuancong Thanks for your feedback!
1046 error is a MySQL standard error. Please refer to [mysql error code document](https://dev.mysql.com/doc/refman/5.7/en/error-messages-server.html#error_er_no_db_error).

**Comment by jackysp** [comment] 2018-09-12 14:10
Thanks for your feedback, @denghuancong ! 
Seems it depends on your proxy algorithm. If you use a random algorithm, it may cause this problem.

**Comment by shenli** [comment] 2018-09-14 10:18
@denghuancong A friendly ping. Is your problem solved?

**Comment by denghuancong** [comment] 2018-10-09 06:59
@shenli not yeah，we can't reproduce this problem right now .
proxysql said that it was tidb return this error.

**Comment by jackysp** [comment] 2018-10-11 02:47
Hi @denghuancong , the error is returned by TiDB. It means the session needs a context to set the `use database` first. Usually it caused by the random dispatch of the proxy. I think we could not to determine that the root cause of this error is the one who returned the error.
I'll close this issue. If you can reproduce it, please be free to reopen it.

**Closed by jackysp** 2018-10-11 02:47 UTC
Labels: question
