### ISSUE TITLE
conv be pushed down to tikv

### ISSUE THREAD

**Issue by ChenPeng2013** [pingcap/tidb#34975] opened 2022-05-26 07:03 UTC
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
use test;
drop table if exists UK_GCOL_STORED_176092;
CREATE TABLE `UK_GCOL_STORED_176092` (
  `COL1` bit(16) DEFAULT NULL,
  UNIQUE KEY `UK_COL1` (`COL1`) /*!80000 INVISIBLE */
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
insert into UK_GCOL_STORED_176092 values(0x15AC), (0xB0B), (0xBC9), (0x11A3), (0x1055), (0x5CB), (0xC3C), (0xB25), (0x88D), (0x1220), (0x156F), (0x975), (0x190F), (0x11E6), (0x93C), (0x14B1), (0x1889), (0x71B), (0x1484), (0x133C), (0x577), (0x907), (0x8A3), (0x1598), (0xE45), (0x4C6), (0x12A2), (0x1917), (0xE57), (0x1227), (0x4D2), (0x16B8), (0x7E0), (0x990), (0x18CF), (0x233), (0x357), (0x351), (0xF01), (0x13D5), (0xCED), (0x124D), (0xB01), (0x1992), (0x7D5), (0x11AD), (0x804), (0x830), (0xBA0), (0x13FF), (0x144F), (0xE7D);
select * from  UK_GCOL_STORED_176092 where conv(col1, 2, 16);
```
### 3. What did you see instead (Required)
```
mysql> select * from  UK_GCOL_STORED_176092 where conv(col1, 2, 16);
ERROR 9002 (HY000): TiKV server timeout
```
### 4. What is your TiDB version? (Required)

master

**Comment by windtalker** [comment] 2022-05-26 10:45
`select cast(col1 as signed) d from  UK_GCOL_STORED_176092 where cast(col1 as signed) > 3132` also will make TiKV crash

**Comment by wshwsh12** [comment] 2022-05-26 12:08
Minimum steps to reproduce：
```
drop table t;
create table t (a varchar(10));
insert into t values("");
select * from t where conv(a,2,16);
```

**Comment by zanmato1984** [comment] 2022-05-27 11:10
This bug exists since 4.0, downgrading to major.

**Comment by zanmato1984** [comment] 2022-05-30 14:26
Closing.

**Closed by zanmato1984** 2022-05-30 14:26 UTC
Labels: type/bug, component/tikv, severity/major, affects-4.0, affects-5.0, affects-5.1, affects-5.2, affects-5.3, affects-5.4, affects-6.0, affects-6.1
