### ISSUE TITLE
The result of 'varbinary + 1' is incorrect

### ISSUE THREAD

**Issue by wan1y** [pingcap/tidb#23411] opened 2021-03-18 10:25 UTC
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```mysql
mysql> create table t1(col1 varbinary(20));
Query OK, 0 rows affected (0.38 sec)

mysql> insert into t1 values(".1pingcap");
Query OK, 1 row affected (0.05 sec)

```

### 2. What did you expect to see? (Required)
```mysql
mysql> select col1, col1 + 1 from t1;
+-----------+----------+
| col1      | col1 + 1 |
+-----------+----------+
| .1pingcap |      1.1 |
+-----------+----------+
1 row in set (0.07 sec)

```
### 3. What did you see instead (Required)
```mysql
mysql> select col1, col1 + 1 from t1;
+-----------+----------+
| col1      | col1 + 1 |
+-----------+----------+
| .1pingcap |        1 |
+-----------+----------+
1 row in set (0.06 sec)

```
### 4. What is your TiDB version? (Required)
```mysql
Release Version: v4.0.0-beta.2-2393-g3cfb984
Edition: Community
Git Commit Hash: 3cfb984211901c3416ec539658ac86d2cb64e81f
Git Branch: master
UTC Build Time: 2021-03-18 02:41:26
GoVersion: go1.13.5
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
```

**Comment by ichn-hu** [comment] 2021-05-10 04:40
Hi @wanliyi , it seems like a corner case caused by invalid parameter, so I would suggest change the severity to moderate, please help change the label if you agree.

**Comment by jebter** [comment] 2024-06-25 02:42
```
TiDB root@127.0.0.1:test> create table t1(col1 varbinary(20));
Query OK, 0 rows affected
Time: 0.074s
TiDB root@127.0.0.1:test> insert into t1 values(".1pingcap");
Query OK, 1 row affected
Time: 0.003s
TiDB root@127.0.0.1:test> select col1, col1 + 1 from t1;
+-----------+----------+
| col1      | col1 + 1 |
+-----------+----------+
| .1pingcap | 1.1      |
+-----------+----------+

1 row in set
Time: 0.006s
TiDB root@127.0.0.1:test> select tidb_version() \G
***************************[ 1. row ]***************************
tidb_version() | Release Version: v8.1.0
Edition: Community
Git Commit Hash: 945d07c5d5c7a1ae212f6013adfb187f2de24b23
Git Branch: HEAD
UTC Build Time: 2024-05-21 03:52:40
GoVersion: go1.21.10
Race Enabled: false
Check Table Before Drop: false
Store: tikv

1 row in set
Time: 0.001s
```
Please try the latest version. I will close it, if there are any updates, you can reopen it.

**Closed by jebter** 2024-06-25 02:42 UTC
Labels: type/bug, sig/execution, severity/moderate
