### ISSUE TITLE
Truncated integer error when regexp is pushed down to TiKV

### ISSUE THREAD

**Issue by pcqz** [pingcap/tidb#52176] opened 2024-03-28 03:56 UTC
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

create table t(a varchar(10));
create table t1(a varchar(64));
insert into t1 values('316-354');
with test as (select case when a regexp '^[0-9]+\\.*[0-9]+$' then case when a<400 then '1' end end flg from t1) select max(flg) from test;
replace into t(a) with test as (select case when a regexp '^[0-9]+\\.*[0-9]+$' then case when a<400 then '1' end end flg from t1) select max(flg) from test;

### 2. What did you expect to see? (Required)

Warning but not error is reported.

### 3. What did you see instead (Required)

```
mysql> with test as (select case when a regexp '^[0-9]+\\.*[0-9]+$' then case when a<400 then '1' end end flg from t1) select max(flg) from test;
+----------+
| max(flg) |
+----------+
| NULL     |
+----------+
1 row in set, 1 warning (0.01 sec)

mysql> show warnings;
+---------+------+-----------------------------------------------------------------+
| Level   | Code | Message                                                         |
+---------+------+-----------------------------------------------------------------+
| Warning | 1292 | evaluation failed: Truncated incorrect INTEGER value: '316-354' |
+---------+------+-----------------------------------------------------------------+
1 row in set (0.00 sec)

mysql> replace into t(a) with test as (select case when a regexp '^[0-9]+\\.*[0-9]+$' then case when a<400 then '1' end end flg from t1) select max(flg) from test;
ERROR 1292 (22007): Truncated incorrect INTEGER value: '316-354'

mysql> INSERT INTO mysql.expr_pushdown_blacklist VALUES('regexp','tikv','');
Query OK, 1 row affected (0.00 sec)

mysql> ADMIN reload expr_pushdown_blacklist;
Query OK, 0 rows affected (0.01 sec)

mysql> replace into t(a) with test as (select case when a regexp '^[0-9]+\\.*[0-9]+$' then case when a<400 then '1' end end flg from t1) select max(flg) from test;
Query OK, 1 row affected (0.00 sec)
Records: 1  Duplicates: 0  Warnings: 0
```

### 4. What is your TiDB version? (Required)

v7.5.0

**Comment by XuHuaiyu** [comment] 2024-03-29 02:47
Since the query is non-recursive, we can treat the CTE as a view. Simplifying the case further, we can create a minimal reproducible example:
``` sql
create table t(a varchar(10));
create table t1(a varchar(64));
insert into t1 values('316-354');
select if(a, 1, 0) from t1;
insert into t select if(a, 1, 0) from t1;
set @@sql_mode='';
insert into t select if(a, 1, 0) from t1;
```
The issue arises because the type of 'a' is inferred as a double, and a cast (as double) is wrapped around 'a'. When 'a' is converted to a double, truncation occurs, leading to an error. This behavior is expected in both TiDB and MySQL5.7 and is controlled by the sql_mode.

In non-write statements, this error is outputted as a warning, while in write statements, it is returned as an error. If we set the sql_mode to '', the insert statement can execute successfully, and the error is converted to a warning.

For MySQL5.7:
``` sql
mysql> select @@sql_mode;
+-------------------------------------------------------------------------------------------------------------------------------------------+
| @@sql_mode                                                                                                                                |
+-------------------------------------------------------------------------------------------------------------------------------------------+
| ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION |
+-------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)

mysql> insert into t select if(a, 1, 0) from t1;
ERROR 1292 (22007): Truncated incorrect DOUBLE value: '316-354'

mysql> select version();
+-----------+
| version() |
+-----------+
| 5.7.23    |
+-----------+

mysql> select if(a, 1, 0) from t1;
+-------------+
| if(a, 1, 0) |
+-------------+
|           1 |
+-------------+
1 row in set, 1 warning (0.00 sec)

mysql> set @@sql_mode='';
Query OK, 0 rows affected, 1 warning (0.00 sec)

mysql> select @@sql_mode;
+------------+
| @@sql_mode |
+------------+
|            |
+------------+
1 row in set (0.00 sec)

mysql> select if(a, 1, 0) from t1;
+-------------+
| if(a, 1, 0) |
+-------------+
|           1 |
+-------------+
1 row in set, 1 warning (0.00 sec)

mysql> insert into t select if(a, 1, 0) from t1;
Query OK, 1 row affected, 1 warning (0.01 sec)
Records: 1  Duplicates: 0  Warnings: 1
```

MySQL 8.0 seems to have modified this behavior. Regardless of whether sql_mode is set, the insert operation can be executed successfully, and no warnings are returned.

For MySQL8.0:
``` sql
mysql> select version();
+-----------+
| version() |
+-----------+
| 8.0.36    |
+-----------+
1 row in set (0.00 sec)

mysql> select @@sql_mode;
+-----------------------------------------------------------------------------------------------------------------------+
| @@sql_mode                                                                                                            |
+-----------------------------------------------------------------------------------------------------------------------+
| ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION |
+-----------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)

mysql> select if(a, 1, 0) from t1;
+-------------+
| if(a, 1, 0) |
+-------------+
|           1 |
+-------------+
1 row in set (0.01 sec)

mysql> insert into t select if(a, 1, 0) from t1;
Query OK, 1 row affected (0.01 sec)
Records: 1  Duplicates: 0  Warnings: 0
```

**Comment by XuHuaiyu** [comment] 2024-03-29 02:59
I have submitted a bug report to MySQL to request confirmation on whether this behavior modification was intentional.
https://bugs.mysql.com/bug.php?id=114509

**Comment by SeaRise** [comment] 2024-04-01 08:14
Another case without pushdown tikv.
```
drop table if exists t1;
create table t1(a varchar(64));
insert into t1 values('316-354');

replace into t(a)  
select 
    case when a regexp '^[0-9]+\.[0-9]+$' then 
	    (if(a < 400, 1, 0))
	else null end from t1;
ERROR 1292 (22007): Truncated incorrect DOUBLE value: '316-354'

explain replace into t(a)  
select 
    case when a regexp '^[0-9]+\.[0-9]+$' then 
	    (if(a < 400, 1, 0))
	else null end from t1;
+---------------------------+---------+-----------+---------------+--------------------------------------------------------------------------------------------------------------+
| id                        | estRows | task      | access object | operator info                                                                                                |
+---------------------------+---------+-----------+---------------+--------------------------------------------------------------------------------------------------------------+
| Insert_1                  | N/A     | root      |               | N/A                                                                                                          |
| └─Projection_5            | 1.00    | root      |               | case(regexp(test.t1.a, ^[0-9]+.[0-9]+$), if(lt(cast(test.t1.a, double BINARY), 400), 1, 0), <nil>)->Column#4 |
|   └─TableReader_7         | 1.00    | root      |               | data:TableFullScan_6                                                                                         |
|     └─TableFullScan_6     | 1.00    | cop[tikv] | table:t1      | keep order:false, stats:pseudo                                                                               |
+---------------------------+---------+-----------+---------------+--------------------------------------------------------------------------------------------------------------+
```

**Comment by XuHuaiyu** [comment] 2024-04-28 08:35
[bugs.mysql.com/bug.php?id=114509](https://bugs.mysql.com/bug.php?id=114509)

As this is a MySQL bug confirmed by the MySQL verification team, I'll close this issue

**Closed by XuHuaiyu** 2024-04-28 08:35 UTC
Labels: type/bug, sig/execution, severity/major, may-affects-5.4, may-affects-6.1, may-affects-6.5, may-affects-7.1, affects-7.5, affects-8.1
