### ISSUE TITLE
Pessimistic transactions may see inconsistent data while doing partitioning DDLs concurrently

### ISSUE THREAD

**Issue by zyguan** [pingcap/tidb#21655] opened 2020-12-10 17:14 UTC
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

Similar to #21498, partitioning DDLs may also cause inconsistent read.

Case 1
```sql
/* init */ drop table if exists t;
/* init */ create table t (id int primary key, v int) partition by range (id) (partition p0 values less than (4), partition p_rest values less than maxvalue);
/* init */ insert into t values (1, 10);

/* txn */ begin;
/* txn */ insert into t values (1, 11) on duplicate key update id = values(id), v = values(v);
/* ddl */ alter table t drop partition p0;
/* ddl */ insert into t values (1, 12) on duplicate key update id = values(id), v = values(v);
/* txn */ select * from t for update; -- (1, 11), (1, 12)
/* txn */ commit; -- OK
```

Case 2
```sql
/* init */ drop table if exists t;
/* init */ create table t (id int primary key, v int) partition by range (id) (partition p0 values less than (4), partition p1 values less than (6));
/* init */ insert into t values (1, 10), (3, 30), (5, 50);

/* txn */ begin;
/* ddl */ alter table t add partition (partition p2 values less than (8));
/* ddl */ insert into t values (6, 60);
/* ddl */ insert into t values (4, 40);
/* txn */ select * from t for update; -- can see (4, 40) but cannot see (6, 60)
/* txn */ commit; -- E8028
```

### 2. What did you expect to see? (Required)

For case 1, it should be only 1 row returned.

For case 2, if we see (4, 40) in txn, we should also see (6, 60) because insert(6, 60) happened before insert(4, 40).

### 3. What did you see instead (Required)

As described in reproduce steps

### 4. What is your TiDB version? (Required)

release-4.0 (2862cd727b4a29c5623f99453fb8d6e7b448004d)

**Comment by cfzjywxk** [comment] 2020-12-28 02:36
It's related to https://github.com/pingcap/tidb/issues/21498, the meda and data inconsistency may cause problem. A complete solution is needed for such issues.

**Comment by cfzjywxk** [comment] 2021-01-07 07:49
As it is a sub-problem of #21498, close this issue and link it as a sub-task.

**Comment by cfzjywxk** [comment] 2021-03-25 13:47
@zyguan 
Seems it's still not fixed yet for the partition table changing, though the transaction could not commit successfully but the reading result is incorrect.

**Comment by zhuo-zhi** [comment] 2021-05-25 10:05
MySql will commit the current transaction when encountering DDL statement. Here is the [document](https://dev.mysql.com/doc/internals/en/transactions-life-cycle.html).

> The normal transaction is committed in a similar way (by going over all engines in thd->transaction.all list) but at different times:
> 
> - When the user issues an SQL COMMIT statement
> 
> - Implicitly, when the server begins handling a DDL statement or SET AUTOCOMMIT={0|1} statement

In order to make TIDB compatible with MySql. I suggest that we also change our transaction logic to behave the same way as MySql. In this way, this inconsistency will also disappear.

**Comment by cfzjywxk** [comment] 2021-05-25 11:36
> MySql will commit the current transaction when encountering DDL statement. Here is the [document](https://dev.mysql.com/doc/internals/en/transactions-life-cycle.html).
> 
> > The normal transaction is committed in a similar way (by going over all engines in thd->transaction.all list) but at different times:
> > 
> > * When the user issues an SQL COMMIT statement
> > * Implicitly, when the server begins handling a DDL statement or SET AUTOCOMMIT={0|1} statement
> 
> In order to make TIDB compatible with MySql. I suggest that we also change our transaction logic to behave the same way as MySql. In this way, this inconsistency will also disappear.

@zhuo-zhi 
The `ddl` and `txn` related statements in the issue description are executed in different sessions, currently TiDB does not have meta data lock like utilities like MySQL, so the transaction executing DML statements may fail because of the concurrent DDLs. In this issue, the in-transaction current read returns unexpected results when partition table is used.

**Comment by zhuo-zhi** [comment] 2021-05-26 06:32
Oh you are right. I didn't notice that the ddl is executed concurrently in another session. Thanks for explanation!

**Comment by cfzjywxk** [comment] 2021-05-26 07:02
> Oh you are right. I didn't notice that the ddl is executed concurrently in another session. Thanks for explanation!
> 
> We might either need to use the latest schema for partition table when execute forUpdateRead, or need to lock the schema meta data in the concurrent ddl execution.

@zhuo-zhi 
Yes, we're considering this, it's difficult to implement a distributed meta data lock mechanism and this may hurt performance a lot. Any suggestions？

**Comment by qw4990** [comment] 2021-06-16 13:00
I cannot reproduce this issue on Master now, is it fixed? @cfzjywxk @zhuo-zhi

**Closed** 2021-07-22 07:20 UTC
Labels: severity/major, sig/sql-infra, sig/transaction, status/can't-reproduce, type/bug
