### ISSUE TITLE
upgrade from v4.0.0 to v5.0.2, report "panic in the recoverable goroutine"

### ISSUE THREAD

**Issue by seiya-annie** [pingcap/tidb#25144] opened 2021-06-04 06:33 UTC
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
performance.feedback-probability: 0.05
upgrade from v4.0.0 to v5.0.2, then check log 
[2021/06/04 09:54:28.823 +08:00] [INFO] [region_cache.go:971] ["switch region leader to specific leader due to kv return NotLeader"] [regionID=23] [currIdx=1] [leaderStoreID=3]
[2021/06/04 09:54:32.212 +08:00] [INFO] [domain.go:1249] ["updateStatsWorker exited."]
[2021/06/04 09:54:32.213 +08:00] [ERROR] [misc.go:113] ["panic in the recoverable goroutine"] [label=domain] [funcInfo=updateStatsWorker] [r={}] [stack="goroutine 740 [running]:\ngithub.com/pingcap/tidb/util.GetStack(...)\n\t/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/util/misc.go:74\ngithub.com/pingcap/tidb/util.Recover(0x39affbd, 0x6, 0x39cf0b9, 0x11, 0x0, 0xc0006e4300)\n\t/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/util/misc.go:117 +0x326\npanic(0x37a6c60, 0xc00406cdc0)\n\t/usr/local/go/src/runtime/panic.go:679 +0x1b2\ngithub.com/pingcap/tidb/statistics.decodeFeedbackForIndex(0xc000faf580, 0xc001fce630, 0xc003ff3e90, 0x0)\n\t/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/statistics/feedback.go:910 +0x6c5\ngithub.com/pingcap/tidb/statistics.DecodeFeedback(0xc0041a4279, 0xf3, 0x3bd87, 0xc000faf580, 0xc003ff3e90, 0x0, 0xc000328c00, 0x0, 0x0)\n\t/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/statistics/feedback.go:993 +0x108\ngithub.com/pingcap/tidb/statistics/handle.(*Handle).handleSingleHistogramUpdate(0xc00082fb90, 0x405e100, 0xc0012c8640, 0xc0006c2000, 0x3fe, 0x400, 0x0, 0x0)\n\t/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/statistics/handle/update.go:799 +0x490\ngithub.com/pingcap/tidb/statistics/handle.(*Handle).HandleUpdateStats.func1(0xc000c158c8, 0xc00082fb90, 0x405e100, 0xc0012c8640, 0x0, 0x0)\n\t/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/statistics/handle/update.go:707 +0x79f\ngithub.com/pingcap/tidb/statistics/handle.(*Handle).HandleUpdateStats(0xc00082fb90, 0x405e100, 0xc0012c8640, 0x405e100, 0xc0012c8640)\n\t/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/statistics/handle/update.go:728 +0x121\ngithub.com/pingcap/tidb/domain.(*Domain).updateStatsWorker(0xc000c95040, 0x406c2a0, 0xc000fab900, 0x4039f20, 0xc0005bc990)\n\t/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/domain/domain.go:1274 +0x43a\ncreated by github.com/pingcap/tidb/domain.(*Domain).UpdateTableStatsLoop\n\t/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/domain/domain.go:1139 +0x1c7\n"]

### 4. What is your TiDB version? (Required)
---------------------------------------------------------------------+
| Release Version: v5.0.2
Edition: Community
Git Commit Hash: f610f8bd01b09790f9915fd174bd191b8148f26e
Git Branch: heads/refs/tags/v5.0.2
UTC Build Time: 2021-06-02 02:00:45
GoVersion: go1.13
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false |
+----------------------------------

**Comment by bb7133** [comment] 2021-06-04 09:52
Looks that it is related to stats feedback, PTAL @rebelice

**Comment by rebelice** [comment] 2021-11-24 05:59
Close it because it can not be reproduce.

**Closed by rebelice** 2021-11-24 05:59 UTC
Labels: type/bug, sig/planner, severity/major
