### ISSUE TITLE
Weird Same Value Update Between Two or More Transactions

### ISSUE THREAD

**Issue by chengpohi** [pingcap/tidb#7644] opened 2018-09-07 14:50 UTC
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
```sql
CREATE TABLE `t` (
  `a` int(11) NOT NULL AUTO_INCREMENT,
  `b` int(11) DEFAULT NULL,
  PRIMARY KEY (`a`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;
insert into t values(1, 0);
```

```scala
  #scala
  val c1 = buildConnectionClient
  val c2 = buildConnectionClient
  val c3 = buildConnectionClient
  println("Initial Value")
  fetchAndPrint("select b from t where a = 1", c3)
  println("-" * 10)
  (0 to 10).foreach(i => {
    c1.setAutoCommit(false)
    update("update t set b=2 where a=1", c2)
    fetchAndPrint("select b from t where a = 1", c1)
    update("update t set b=0 where a=1", c1)
    c1.commit()
  })
  c1.close()
  c2.close()
  c3.close()
```
 

2. What did you expect to see?

Maybe like :)

```
2
2
2
2
2
2
2
2
2
2
2
```

or 

```
0
0
0
0
0
0
...
```

3. What did you see instead?

```
Initial Value
0
----------
2
0
2
0
2
0
2
0
2
0
2
```

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

**master branch**

---

Hello, I have seen this interesting issue :) [Same transaction returns different results when i ran multiply times](https://stackoverflow.com/questions/52097939/same-transaction-returns-different-results-when-i-ran-multiply-times) and try to investigate it, finally find this is caused by **TiDB** will ignore the **same value** update by:

```go
		cmp, err := newData[i].CompareDatum(sc, &oldData[i])
		if err != nil {
			return false, handleChanged, newHandle, errors.Trace(err)
		}
		if cmp != 0 {
                 ...
```

https://github.com/pingcap/tidb/blob/master/executor/write.go#L74

but this will cause the **strange behavior** like **PO** asked, for the **same value** will not be updated, but for **different value** will be updated and committed in the multi **Transactions**, 
Since the other **transaction** maybe modified the **value**, _but it's not seen by the same value transaction_. I have created a flow in the answer, maybe it's clearer to explain it.

I am trying to think about whether can just removed **cmp** check rule, this can be ensured  **same value** and **different value** always can be updated and committed.

Thanks

**Comment by shenli** [comment] 2018-09-07 14:52
@chengpohi Thanks for your feedback! Please post the full output of "tidb-server -V or run select tidb_version();" in the issue.

**Comment by chengpohi** [comment] 2018-09-07 14:55
@shenli it's from the master branch:

```
Release Version: v2.1.0-rc.1-67-gb2bfd8f
Git Commit Hash: b2bfd8f91a0cb633d379979e23801f2b1a2dfee9
Git Branch: master
UTC Build Time: 2018-09-07 05:02:59
GoVersion: go version go1.11 darwin/amd64
Race Enabled: false
TiKV Min Version: 2.1.0-alpha.1-ff3dd160846b7d1aed9079c389fc188f7f5ea13e
Check Table Before Drop: false
```

**Comment by shenli** [comment] 2018-09-07 15:32
@chengpohi 
`master` is a branch, but not a version. There are about 50 commits per week in TiDB's master branch. It is our dev branch. So we need the exactly GitHash to make the issue investigation clear.

I read the stackoverflow post. I should point out that TiDB does not support the `READ_COMMITTED` isolation anymore.  We disabled it a few weeks ago.

And there is one thing I can not understand: Why should we update a row even if it is not changed in an `update` statement?

**Comment by crazycs520** [comment] 2018-09-07 16:01
@chengpohi Hi, I try to run your test code. You may should add `c1.begin()` to begin a transaction.
Then out put will ok:
```
initial
0,
2,
2,
2,
2,
2,
2,
2,
2,
2,
2,
```

**Comment by chengpohi** [comment] 2018-09-07 16:43
@shenli ok, Thanks

> Why should we update a row even if it is not changed in an update statement?

How should we handle the other transaction committed data?  if override it like currently doing(if i am wrong, please call out), but current transaction still compare the **new data** with  **old data**(**SNAPSHOT**?) that started from the current **transaction**.

Problem is:  if **new data** is same as **old data**, it will actually skip this update even if the data already updated by other **transaction**?  Is it right?

**Comment by chengpohi** [comment] 2018-09-07 16:45
Hi @crazycs520 ,  what's meaning of put `c1.begin()` to begin a transaction? Do you mean put it before `update("update t set b=0 where a=1", c1)`?

**Comment by crazycs520** [comment] 2018-09-07 16:49
@chengpohi, add  ` c1.begin()`  before `fetchAndPrint("select b from t where a = 1", c1)`

**Comment by chengpohi** [comment] 2018-09-07 16:53
@crazycs520 for my understanding, the **PO** want to simulate between **transaction 1** there is another **transaction 2** updated the value, if add `c1.begin()` after **transaction 2**, I think this is meanness?

**Comment by crazycs520** [comment] 2018-09-07 16:59
@chengpohi , then you should add  `c1.begin() ` before `update("update t set b=2 where a=1", c2)`.
BTW, for transaction 2, you also should add `begin` and `commit` for `c2`.

**Comment by chengpohi** [comment] 2018-09-08 05:16
Hi @crazycs520 , I think if you do as you suggested, the output should not be:

```
0,
2,
2,
...
```
Is it right? if I am wrong, please correct me.

**Comment by wjhuang2016** [comment] 2021-01-06 05:56
Close this issue because it can not be reproduced.

**Closed by wjhuang2016** 2021-01-06 05:56 UTC
Labels: severity/moderate, sig/transaction, status/can't-reproduce, type/bug
