### ISSUE TITLE
Systems supporting made in China

### ISSUE THREAD

**Issue by cluyun** [pingcap/tidb#25594] opened 2021-06-21 03:11 UTC
It is suggested to support [winning the bid for Qilin](http://www.cs2c.com.cn/),[UOS](https://www.chinauos.com/) and other China databases

**Comment by tisonkun** [comment] 2021-06-21 03:15
Thanks for your report @cluyun . Please translate the content to English so that everyone in our community can follow it.

For the topic itself, generally we use issue to track bug and development task.

If it is a wish, i.e., you don't want to implement the integration, you can go to [AskTUG](https://asktug.com/) and speak out you wish.

If it is a proposal with design, you can go to [TiDB Internals](https://internals.tidb.io/) to share the design and see whether or not and if so, how we can achieve it.

**Comment by cluyun** [comment] 2021-06-21 06:26
> Thanks for your report @cluyun . Please translate the content to English so that everyone in our community can follow it.
> 
> For the topic itself, generally we use issue to track bug and development task.
> 
> If it is a wish, i.e., you don't want to implement the integration, you can go to [AskTUG](https://asktug.com/) and speak out your wish.
> 
> If it is a proposal with design, you can go to [TiDB Internals](https://internals.tidb.io/) to share the design and see whether or not and if so, how we can achieve it.

updated,Please check

**Comment by tisonkun** [comment] 2021-06-21 06:30
@cluyun thanks for your updating! You can take a the follow suggestion I posted above. We have some dedicated channel for different topic and this issue is highly likely be overwhelmed by other traffic. But anyway, you can keep the issue open since we don't forbid it.

**Comment by cluyun** [comment] 2021-06-21 06:31
> @cluyun thanks for your updating! You can take a the follow suggestion I posted above. We have some dedicated channels for different topic and this issue is highly likely overwhelmed by other traffic. But anyway, you can keep the issue open since we don't forbid it.

If you support it, please remember to update the document.

[https://docs.pingcap.com/tidb/stable/hardware-and-software-requirements#linux-os-version-requirements](https://docs.pingcap.com/tidb/stable/hardware-and-software-requirements#linux-os-version-requirements)

**Comment by cluyun** [comment] 2021-06-21 06:33
You seem to have paid attention, but there is no continuous follow-up：[https://asktug.com/t/topic/33963](https://asktug.com/t/topic/33963)

**Comment by tisonkun** [comment] 2021-06-21 06:38
Thanks for your information on https://github.com/pingcap/tidb/issues/25594#issuecomment-864767212 . You may comment on the AskTUG thread and ask for follow-ups and your suggestion on updating document on demand.

Beware that all participants in the community are volunteers. If you do not receive any feedback in a reasonable amount of time (say, a week or two), feel free to send a follow-up post to notify. Or just like creating this issue, but we might back to AskTUG for the result because the topic is about wishing list that is not a bug or development task GitHub issue is intended to track.

**Comment by cluyun** [comment] 2021-06-21 06:54
#25594

> Thanks for your information on [#25594 (comment)](https://github.com/pingcap/tidb/issues/25594#issuecomment-864767212) . You may comment on the AskTUG thread and ask for follow-ups and your suggestion on updating document on demand.
> 
> Beware that all participants in the community are volunteers. If you do not receive any feedback in a reasonable amount of time (say, a week or two), feel free to send a follow-up post to notify. Or just like creating this issue, but we might back to AskTUG for the result because the topic is about wishing list that is not a bug or development task GitHub issue is intended to track.

I feel that this may be a document problem. I made a mistake in the document warehouse：[https://github.com/pingcap/docs/issues/5812](https://github.com/pingcap/docs/issues/5812)

**Comment by tisonkun** [comment] 2021-06-21 07:29
@cluyun make sense. Then what about closing this PR since it is superseded by pingcap/docs#5812

**Closed** 2021-06-21 07:41 UTC
Labels: type/feature-request
