### ISSUE TITLE
segmentation violation in the buildColumnAndConstraint

### ISSUE THREAD

**Issue by hawkingrei** [pingcap/tidb#35639] opened 2022-06-22 04:15 UTC
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
 [FAIL]  planner/core TestIssue33175
err=exit status 2
[2022/06/17 20:39:33.182 +08:00] [INFO] [tidb.go:74] ["new domain"] [store=2f205aa9-1d78-48a8-8d7e-3c6b7f8e0934] ["ddl lease"=0s] ["stats lease"=-1ns] ["index usage sync lease"=0s]
unexpected fault address 0x0
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x80 addr=0x0 pc=0x388616d]
goroutine 88 [running]:
runtime.throw({0x57b9fd6?, 0xc00013b6f5?})
	/usr/local/go/src/runtime/panic.go:992 +0x71 fp=0xc0001f21f0 sp=0xc0001f21c0 pc=0x146dd91
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:825 +0x305 fp=0xc0001f2240 sp=0xc0001f21f0 pc=0x1486365
github.com/pingcap/tidb/ddl.buildColumnAndConstraint({0x6a19130, 0xc0004bb110}, 0xc00013b6f5?, 0xc000255f7f, 0x14a62f9?, {0x57bf40a, 0x7}, {0x57cacdd, 0xb})
	/go/tidb/ddl/ddl_api.go:764 +0xad fp=0xc0001f23c0 sp=0xc0001f2240 pc=0x388616d
github.com/pingcap/tidb/ddl.buildColumnsAndConstraints({0x6a19130, 0xc0004bb110}, {0xc000ba2c00, 0x29, 0x14a7ab7?}, {0x0, 0x0, 0x0}, {0x57bf40a, 0x7}, ...)
	/go/tidb/ddl/ddl_api.go:650 +0x265 fp=0xc0001f25b8 sp=0xc0001f23c0 pc=0x38850e5
github.com/pingcap/tidb/ddl.buildTableInfoWithStmt({0x6a19130, 0xc0004bb110}, 0xc0002c9c70, {0x57bf40a, 0x7}, {0x0, 0x0}, 0x0)
	/go/tidb/ddl/ddl_api.go:2119 +0x24c fp=0xc0001f27c8 sp=0xc0001f25b8 pc=0x38968ac
github.com/pingcap/tidb/ddl.buildTableInfoWithCheck({0x6a19130, 0xc0004bb110}, 0x39818af?, {0x57bf40a, 0x7}, {0x0, 0x0}, 0xc000bae1e0?)
	/go/tidb/ddl/ddl_api.go:2063 +0x95 fp=0xc0001f2840 sp=0xc0001f27c8 pc=0x3895e35
github.com/pingcap/tidb/ddl.BuildTableInfoFromAST(0x534ea00?)
	/go/tidb/ddl/ddl_api.go:2057 +0x53 fp=0xc0001f28b0 sp=0xc0001f2840 pc=0x3895d53
github.com/pingcap/tidb/infoschema/perfschema.Init.func1()
	/go/tidb/infoschema/perfschema/init.go:51 +0x137 fp=0xc0001f29f8 sp=0xc0001f28b0 pc=0x3981797
sync.(*Once).doSlow(0x95a5c68, 0x5935740)
	/usr/local/go/src/sync/once.go:68 +0x102 fp=0xc0001f2ac8 sp=0xc0001f29f8 pc=0x14cc982
sync.(*Once).Do(0x95a5c68, 0x4bdd545?)
	/usr/local/go/src/sync/once.go:59 +0x47 fp=0xc0001f2af0 sp=0xc0001f2ac8 pc=0x14cc847
github.com/pingcap/tidb/infoschema/perfschema.Init()
	/go/tidb/infoschema/perfschema/init.go:75 +0x47 fp=0xc0001f2b10 sp=0xc0001f2af0 pc=0x3981f27
github.com/pingcap/tidb/domain.(*Domain).Init(0xc000b6c640, 0x0, 0xc0001baa08)
	/go/tidb/domain/domain.go:754 +0xaa fp=0xc0001f31c0 sp=0xc0001f2b10 pc=0x39d304a
github.com/pingcap/tidb/session.(*domainMap).Get.func1()
	/go/tidb/session/tidb.go:85 +0x665 fp=0xc0001f3448 sp=0xc0001f31c0 pc=0x4bdd545
github.com/pingcap/tidb/util.RunWithRetry(0x1e, 0x1f4, 0xc0001f3530)
	/go/tidb/util/misc.go:65 +0x94 fp=0xc0001f34a0 sp=0xc0001f3448 pc=0x2b03a34
github.com/pingcap/tidb/session.(*domainMap).Get(0x8b5f9c0, {0x69e0f00, 0xc000c52e40})
	/go/tidb/session/tidb.go:73 +0x31a fp=0xc0001f35e8 sp=0xc0001f34a0 pc=0x4bdcdfa
github.com/pingcap/tidb/session.createSessionWithOpt({0x69e0f00, 0xc000c52e40}, 0x0)
	/go/tidb/session/session.go:2992 +0x76 fp=0xc0001f3770 sp=0xc0001f35e8 pc=0x4bd56f6
github.com/pingcap/tidb/session.createSession(...)
	/go/tidb/session/session.go:2988
github.com/pingcap/tidb/session.runInBootstrapSession({0x69e0f00, 0xc000c52e40}, 0x5936c88)
	/go/tidb/session/session.go:2958 +0x65 fp=0xc0001f3858 sp=0xc0001f3770 pc=0x4bd51e5
github.com/pingcap/tidb/session.BootstrapSession({0x69e0f00, 0xc000c52e40})
	/go/tidb/session/session.go:2853 +0x1f1 fp=0xc0001f39c8 sp=0xc0001f3858 pc=0x4bd4751
github.com/pingcap/tidb/testkit.bootstrap({0x69e4330?, 0xc000b061a0}, {0x69e0f00?, 0xc000c52e40}, 0x0?)
	/go/tidb/testkit/mockstore.go:49 +0x8d fp=0xc0001f3a50 sp=0xc0001f39c8 pc=0x4f0552d
github.com/pingcap/tidb/testkit.CreateMockStoreAndDomain({0x69e4330?, 0xc000b061a0}, {0x0, 0x0, 0x0})
	/go/tidb/testkit/mockstore.go:42 +0xce fp=0xc0001f3ad0 sp=0xc0001f3a50 pc=0x4f0542e
github.com/pingcap/tidb/planner/core_test.TestIssue33175(0x0?)
	/go/tidb/planner/core/integration_test.go:6540 +0x59 fp=0xc0001f3ea8 sp=0xc0001f3ad0 pc=0x4fb0979
testing.tRunner(0xc000b061a0, 0x59364e8)
	/usr/local/go/src/testing/testing.go:1439 +0x214 fp=0xc0001f3fb0 sp=0xc0001f3ea8 pc=0x160c254
testing.(*T).Run.func1()
	/usr/local/go/src/testing/testing.go:1486 +0x48 fp=0xc0001f3fe0 sp=0xc0001f3fb0 pc=0x160da08
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc0001f3fe8 sp=0xc0001f3fe0 pc=0x14a4ba1
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1486 +0x725

```

**Comment by tiancaiamao** [comment] 2024-02-28 08:48
It panics during `session.BootstrapSession`, I can not reproduce this panic.
Maybe it's caused by some global variable used by the test cases, and the test run parallelly, I'm not sure.

It's a long time since this issue been created, I think it's safe to close it.
We can reopen it if we found reproduce for this issue.

**Closed by tiancaiamao** 2024-02-28 08:48 UTC
Labels: type/bug, component/test, sig/sql-infra, severity/major, affects-6.2, affects-6.3, affects-6.4, affects-6.5, affects-6.6, affects-7.0, affects-7.1, affects-7.5
