### ISSUE TITLE
TiDB returned error 8027 and was up and down for several mins while injecting iochaos on one of three tikvs.

### ISSUE THREAD

**Issue by Andrewmatilde** [pingcap/tidb#30258] opened 2021-11-30 05:15 UTC
### 1. Minimal reproduce step (Required)
Get a test cluster with three tikvs.
Run bench :
sysbench oltp_insert prepare --mysql-port=$port --mysql-host=127.0.0.1 --mysql-user=root --tables=32 --table-size=100000000 --num-threads=64
After 5min
Inject iochaos with iodelay(100ms) on the all write operation one tikv.([iochaos](https://chaos-mesh.org/docs/simulate-io-chaos-on-kubernetes/))
After 5min
Clear payload & iochaos.

These series of operations should be implemented on three tikvs.

### 2. What did you expect to see? (Required)
TiDB not return error & QPS was stable.
### 3. What did you see instead (Required)
TiDB return error 8027 (Information schema is out of date: schema failed to update in 1 lease, please make sure TiDB can connect to TiKV) and QPS  up and down from 0 to 4  64 which uesd to be 64.
### 4. What is your TiDB version? (Required)
TiDB operator version: 1.2.4
TiDB : v5.2.1
Chaos-Mesh: v2.0.4

**Comment by bb7133** [comment] 2022-01-14 02:45
Looks that it is caused by TiDB-server cannot communicate with TiKV. 

I will close this issue since we cannot reproduce it and the root cause is unclear.

@Andrewmatilde Please feel free to reopen it when we have an environment to reproduce this issue.

**Closed by bb7133** 2022-01-14 02:45 UTC
Labels: type/bug, sig/sql-infra, severity/major, affects-5.2
