### ISSUE TITLE
ERROR 1105 (HY000): encoding failed

### ISSUE THREAD

**Issue by ChenPeng2013** [pingcap/tidb#25220] opened 2021-06-07 11:36 UTC
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

release-5.0

```
use test;
source [test.txt](https://github.com/pingcap/tidb/files/6608442/test.txt);
select count(*) from UK_MU13117 where col1;
```
### 2. What did you expect to see? (Required)
Don't have error info

### 3. What did you see instead (Required)
```
mysql> select count(*) from UK_MU13117 where col1;                                                                                             ERROR 1105 (HY000): encoding failed
```

### 4. What is your TiDB version? (Required)

```
Release Version: v5.0.2
Edition: Community
Git Commit Hash: dc40a093a0058b95fc859f60d4b84337dbdff9f6
Git Branch: heads/refs/tags/v5.0.2
UTC Build Time: 2021-06-05 02:21:35
GoVersion: go1.13
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
```

**Comment by wshwsh12** [comment] 2021-06-08 09:59
Duplicate of #23322

**Closed by wshwsh12** 2021-06-08 09:59 UTC
Labels: severity/major, sig/execution, type/bug
