### ISSUE TITLE
TestWriteWriteConflict Failed

### ISSUE THREAD

**Issue by zimulala** [pingcap/tidb#1520] opened 2016-07-29 05:45 UTC
FAIL: isolation_test.go:93: testIsolationSuite.TestWriteWriteConflict

isolation_test.go:62:
    c.Assert(kv.IsRetryableError(err), IsTrue)
... obtained bool = false

**Comment by ngaut** [comment] 2016-08-19 03:11
Ping

**Comment by disksing** [comment] 2016-08-19 04:55
It is caused by a logical flaw in our old lock-resolver implementation. It happens when 4 transactions executes like this:
* _T0_ (startTS=50) leaves a `Lock(50)` on _K1_ then be terminated.
* _T1_ (startTS=60) wants to write _K1_, it prepares a `Prewrite (60,K1)` command.
* _T2_ (startTS=70) encounters the Lock when it tries to read _K1_. After reading _PrimaryLock_, it prepares a `RollbackThenGet (50, K1)` command.
* _T3_ (startTS=80) also encounters the Lock and prepares a `RollbackThenGet(50,K1)`.
* Server receives _T3_'s `RollbackThenGet(50,K1)` and deletes the Lock.
* Server receives _T1_'s `Prewrite (60,K1)` and leaves a `Lock(60)` on _K1_.
* Server receives _T2_'s `RollbackThenGet (50, K1)`. The 'Rollback' part is success since the Lock is already deleted by _T3_, but the 'Get' will encounter the Lock left by _T1_.
* Client believe 'RollbackThenGet' should never report an error so it aborts the transaction.

The problem does not exists after we switch to the new 'LockResolver', so I just close it.

**Closed** 2016-08-19 04:56 UTC
Labels: bug
