### ISSUE TITLE
Memory leak observed after the fix of #2944

### ISSUE THREAD

**Issue by dbjoa** [pingcap/tidb#3023] opened 2017-04-10 02:36 UTC
Please answer these questions before submitting your issue. Thanks!

1. What did you do?

cluster configuration: 
- 3 tidb-server
- 3 pd-server
- 3 tikv-server
- 1 nginx (as a load balancer of the tidb-servers)

workload and test tool: YCSB-B bencmark for 24 hours:
  - recordcount=30000000
  - operationcount=1500000000
  - workload=com.yahoo.ycsb.workloads.CoreWorkload
  - readallfields=true
  - readproportion=0.95
  - updateproportion=0.05
  - scanproportion=0
  - insertproportion=0
  - requestdistribution=zipfian
  - threads=50
  - target=5000

2. What did you expect to see?
From the TiDB dashboard of grafana, the trend of the memory usage should be flat even though the accumulated number of test queries are increasing.

3. What did you see instead?
However, the trend is increasing linearly according to the accumulated numer. 
In my case, the memory usage of each of tidb server increases from 30M to 120M. 
The memory increasing issue is observed from the fix of #2944.  

From the memory profiling by using pprof (inuse_space), I've observed that "net/http.(*Transport).dialConn" is increased significantly.

4. What version of Go are you using (`go version`)?
go1.8

**Comment by tiancaiamao** [comment] 2017-04-19 04:26
Thanks for your feedback.

We know a leak problem that connections are open but never close, and it was fixed in https://github.com/pingcap/tidb/pull/3066 . 
Maybe the problem you described is caused by it. You could try the latest master branch.

**Closed** 2017-05-04 01:36 UTC
