### ISSUE TITLE
MySQL outperform tidb on some queries

### ISSUE THREAD

**Issue by jonemeng** [pingcap/tidb#9009] opened 2019-01-10 12:00 UTC
## Question

建表语句如下：CREATE TABLE `mingyi_resource_qa` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `key` varchar(255) NOT NULL COMMENT '唯一键',
  `title` varchar(255) NOT NULL COMMENT '标题',
  `title_url` varchar(255) NOT NULL COMMENT '标题url',
  `hospital_doctor` varchar(255) DEFAULT NULL 
  `hospital_level` varchar(255) DEFAULT NULL ,
  `answer` varchar(1024) DEFAULT NULL ,
  `img` varchar(255) DEFAULT NULL COMMENT '图片、缩略图、头像图',
  `from` varchar(255) NOT NULL COMMENT '资源方',
  `description` varchar(1024) NOT NULL COMMENT '摘要',
  `rationality_score` tinyint(2) NOT NULL DEFAULT '0' COMMENT '合理性分数',
  `relativity_score` tinyint(2) NOT NULL DEFAULT '0' COMMENT '相关性分数',
  `authority_score` tinyint(2) NOT NULL DEFAULT '0' COMMENT '权威性分数',
  `timeliness_score` tinyint(2) NOT NULL DEFAULT '0' COMMENT '时效性分数',
  `quality_score` tinyint(2) NOT NULL DEFAULT '0' COMMENT '质量分数',
  `total` tinyint(2) NOT NULL DEFAULT '0' COMMENT '总分',
  `status` tinyint(1) NOT NULL DEFAULT '0' ,
  `user` varchar(255) NOT NULL COMMENT '操作者',
  `create_time` datetime NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '导入时间',
  `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '操作时间',
  `ps` varchar(255) DEFAULT NULL COMMENT '备注',
  `json` varchar(4096) DEFAULT NULL COMMENT 'json数据',
  `tag` varchar(255) DEFAULT NULL COMMENT 'tag标签',
  `isShow` tinyint(4) NOT NULL DEFAULT '0' ,
  `is_search` tinyint(1) NOT NULL DEFAULT '0' ,
  `is_same` tinyint(1) NOT NULL DEFAULT '0' ,
  `is_PA` tinyint(1) NOT NULL DEFAULT '0' ,
  `is_authority` tinyint(1) NOT NULL DEFAULT '0' ,
  `version` varchar(10) DEFAULT '2018-11.2' COMMENT '版本',
  `is_tier` tinyint(1) NOT NULL DEFAULT '0' ,
  `isAuthority` tinyint(2) NOT NULL DEFAULT '0' ,
  `wap_url` varchar(255) NOT NULL ,
  `siteid` varchar(255) NOT NULL COMMENT '站点id',
  `taskid` int(12) NOT NULL COMMENT '所属任务批次id',
  `validity` tinyint(2) NOT NULL DEFAULT '0' COMMENT '当条数据解析状态，1解析合法 0解析不合法',
  `specification` tinyint(2) NOT NULL DEFAULT '0' COMMENT '页面规范检测状态，0未检测，1不合格，2合格',
  `isSo` tinyint(2) NOT NULL DEFAULT '0' ,
  `isMingyi` tinyint(2) NOT NULL DEFAULT '1' ,
  `deleteFlag` tinyint(2) NOT NULL DEFAULT '0',
  `speciDetail` varchar(4096) NOT NULL DEFAULT '' ,
  `validityDetail` varchar(4096) DEFAULT NULL ,
  `wapUrl` varchar(255) NOT NULL COMMENT 'wapUrl',
  `type` tinyint(2) NOT NULL DEFAULT '3' ,
  `is_index` tinyint(2) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `url` (`title_url`),
  KEY `key` (`key`),
  KEY `from` (`from`),
  KEY `status` (`status`),
  KEY `isShow` (`isShow`,`is_same`),
  KEY `issearch` (`is_search`),
  KEY `siteid` (`siteid`),
  KEY `is_index` (`is_index`),
  KEY `specification` (`specification`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin AUTO_INCREMENT=872275193

这样一条查询需要5分钟左右，数据量有4000W左右，tikv三台机器
select count(*) as totalNum from mingyi_resource_qa  where (status=1 or status=0) and validity=1;

![default](https://user-images.githubusercontent.com/17735904/50967200-5d466580-1512-11e9-8318-f9770686fc66.png)

**Comment by winoros** [comment] 2019-01-10 12:18
Is tikv busy at that time? You can use grafana monitor to check this. See [文档/Coprocessor 指标解释](https://github.com/pingcap/docs-cn/blob/master/op-guide/dashboard-tikv-info.md#coprocessor)

Also, please provide your TiDB version. You can use `select tidb_version()` to get the result.

**Comment by jonemeng** [comment] 2019-01-11 02:41
which quota is very important？ let me show some metric 
![default](https://user-images.githubusercontent.com/17735904/51009917-fc0fa800-158c-11e9-97d3-2a7892d3f2ad.png)
![default](https://user-images.githubusercontent.com/17735904/51009962-1b0e3a00-158d-11e9-963b-56d9e5fe9e91.png)
![default](https://user-images.githubusercontent.com/17735904/51009972-22cdde80-158d-11e9-91a0-73a83b582e4d.png)
![default](https://user-images.githubusercontent.com/17735904/51010006-43963400-158d-11e9-8d50-dd4ff3da6f0d.png)
![default](https://user-images.githubusercontent.com/17735904/51010033-67f21080-158d-11e9-8273-5e9e0c4f1113.png)

**Comment by zz-jason** [comment] 2019-01-11 02:47
@jonemeng Does the `create table` statements in MySQL and TiDB are the same? Could you post the **json** formatted execution plan in MySQL by:
```sql
explain format = json
select count(*) as totalNum
from mingyi_resource_qa
where (status=1 or status=0)
  and validity=1;
```

From the TiDB execution plan posted by you in the above, the execution of this query is so simple, I have two suspicions:
- The execution time is dominated by the double read and filter, or:
- The execution time is dominated by `HashAgg_7` executed on TiKV regions by TiKV coprocessor.

So, in order to identify the root cause, except for the TiKV coprocessor metrics, could you give us:
- the whole TiKV cluster metrics? you can download a pdf version through the grafana monitor.
- the full log of tikv-server and tidb-server at that time, including slow query log if you have that config in tidb-server.
- the region distribution of that table. This info can be obtained by this python script: https://github.com/pingcap/tidb-ansible/blob/master/scripts/table-regions.py

Besides, is the query in TiDB always slow, or occasionally slow?

**Comment by jonemeng** [comment] 2019-01-11 03:52
[document.pdf](https://github.com/pingcap/tidb/files/2748001/document.pdf)
[tidb.tar.gz](https://github.com/pingcap/tidb/files/2748004/tidb.tar.gz)


MySQL explain
![default](https://user-images.githubusercontent.com/17735904/51012147-adffa200-1596-11e9-8899-175830f8fd4a.png)

your python tools not work ,i access the http interface and response as follow
![default](https://user-images.githubusercontent.com/17735904/51012288-6594b400-1597-11e9-9563-281286d10bc9.png)

**Comment by jonemeng** [comment] 2019-01-14 08:18
hi , @zz-jason ，are there any new discoveries?

**Comment by jonemeng** [comment] 2019-01-16 04:14
my table size about 40G,and i have 3 tikvs  ,now my tidb configure is 
**commit-timeout = "41s"
grpc-connection-count = 16**
if i increase the connection size ,is there will be better?

**Comment by jonemeng** [comment] 2019-01-16 04:19
this is my cluster configure ，plz help me check it.thanks very much!
[tidb.txt](https://github.com/pingcap/tidb/files/2762603/tidb.txt)
[tikv.txt](https://github.com/pingcap/tidb/files/2762604/tikv.txt)

**Comment by jebter** [comment] 2024-06-05 05:27
The issue has not been updated for too long, so I will close it. If there are any updates, you can reopen it.

**Closed by jebter** 2024-06-05 05:27 UTC
Labels: type/question
