### ISSUE TITLE
start tidb-server failed on loading plugin test

### ISSUE THREAD

**Issue by purelind** [pingcap/tidb#27162] opened 2021-08-12 11:50 UTC
## Bug Report

```shell
[2021-08-12T11:10:56.854Z] + rm -rf /tmp/tidb

[2021-08-12T11:10:56.855Z] + mkdir -p plugin-so

[2021-08-12T11:10:56.855Z] + cp /home/jenkins/agent/workspace/tidb_ghpr_build/go/src/github.com/pingcap/enterprise-plugin/audit/audit-1.so ./plugin-so/

[2021-08-12T11:10:56.855Z] + cp /home/jenkins/agent/workspace/tidb_ghpr_build/go/src/github.com/pingcap/enterprise-plugin/whitelist/whitelist-1.so ./plugin-so/

[2021-08-12T11:10:57.112Z] + sleep 5

[2021-08-12T11:10:57.112Z] + /home/jenkins/agent/workspace/tidb_ghpr_build/go/src/github.com/pingcap/tidb/bin/tidb-server -plugin-dir=/home/jenkins/agent/workspace/tidb_ghpr_build/go/src/github.com/pingcap/tidb/plugin-so -plugin-load=audit-1,whitelist-1

[2021-08-12T11:11:02.381Z] + mysql -h 127.0.0.1 -P 4000 -u root -e 'select tidb_version()'

[2021-08-12T11:11:02.381Z] ERROR 2003 (HY000): Can't connect to MySQL server on '127.0.0.1' (111)
```

ci link
1. https://ci.pingcap.net/blue/organizations/jenkins/tidb_ghpr_build/detail/tidb_ghpr_build/19675/pipeline/

**Comment by bb7133** [comment] 2021-12-07 05:24
Close this issue since it is not reproducible, and the reason is not clear. We can reopen it if it happens again.

**Closed by bb7133** 2021-12-07 05:24 UTC
Labels: type/bug, component/test, sig/sql-infra, severity/major
