### ISSUE TITLE
data race in expression package

### ISSUE THREAD

**Issue by eurekaka** [pingcap/tidb#12575] opened 2019-10-09 08:34 UTC
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?

I run unit test on master branch, and data race was reported.

2. What did you expect to see?

No data race.

3. What did you see instead?

```
[2019-10-09T07:39:23.880Z] WARNING: DATA RACE
[2019-10-09T07:39:23.880Z] Read at 0x00c0010f6990 by goroutine 89:
[2019-10-09T07:39:23.880Z]   github.com/pingcap/tidb/statistics/handle.(*Handle).columnStatsFromStorage()
[2019-10-09T07:39:23.880Z]       /home/jenkins/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/statistics/handle/handle.go:406 +0x1ad3
[2019-10-09T07:39:23.880Z]   github.com/pingcap/tidb/statistics/handle.(*Handle).tableStatsFromStorage()
[2019-10-09T07:39:23.880Z]       /home/jenkins/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/statistics/handle/handle.go:509 +0x5ca
[2019-10-09T07:39:23.880Z]   github.com/pingcap/tidb/statistics/handle.(*Handle).Update()
[2019-10-09T07:39:23.880Z]       /home/jenkins/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/statistics/handle/handle.go:175 +0x6a1
[2019-10-09T07:39:23.880Z]   github.com/pingcap/tidb/domain.(*Domain).loadStatsWorker()
[2019-10-09T07:39:23.880Z]       /home/jenkins/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/domain/domain.go:961 +0x584
[2019-10-09T07:39:23.880Z] 
[2019-10-09T07:39:23.880Z] Previous write at 0x00c0010f6990 by goroutine 82:
[2019-10-09T07:39:23.880Z]   github.com/pingcap/tidb/expression.DisableParseJSONFlag4Expr()
[2019-10-09T07:39:23.880Z]       /home/jenkins/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/expression/util.go:578 +0xb5
[2019-10-09T07:39:23.880Z]   github.com/pingcap/tidb/expression.(*compareFunctionClass).generateCmpSigs()
[2019-10-09T07:39:23.880Z]       /home/jenkins/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/expression/builtin_compare.go:1274 +0x158
[2019-10-09T07:39:23.880Z]   github.com/pingcap/tidb/expression.(*compareFunctionClass).getFunction()
[2019-10-09T07:39:23.880Z]       /home/jenkins/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/expression/builtin_compare.go:1264 +0x1c7
[2019-10-09T07:39:23.880Z]   github.com/pingcap/tidb/expression.newFunctionImpl()
[2019-10-09T07:39:23.880Z]       /home/jenkins/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/expression/scalar_function.go:137 +0x2de
[2019-10-09T07:39:23.880Z]   github.com/pingcap/tidb/planner/core.(*expressionRewriter).newFunction()
[2019-10-09T07:39:23.880Z]       /home/jenkins/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/expression/scalar_function.go:157 +0x1e9
[2019-10-09T07:39:23.880Z]   github.com/pingcap/tidb/planner/core.(*expressionRewriter).constructBinaryOpFunction()
[2019-10-09T07:39:23.880Z]       /home/jenkins/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/planner/core/expression_rewriter.go:195 +0x14db
[2019-10-09T07:39:23.880Z]   github.com/pingcap/tidb/planner/core.(*expressionRewriter).binaryOpToExpression()
[2019-10-09T07:39:23.880Z]       /home/jenkins/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/planner/core/expression_rewriter.go:1045 +0x280
[2019-10-09T07:39:23.880Z]   github.com/pingcap/tidb/planner/core.(*expressionRewriter).Leave()
[2019-10-09T07:39:23.880Z]       /home/jenkins/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/planner/core/expression_rewriter.go:880 +0x1890
[2019-10-09T07:39:23.880Z]   github.com/pingcap/parser/ast.(*BinaryOperationExpr).Accept()
[2019-10-09T07:39:23.880Z]       /home/jenkins/workspace/tidb_ghpr_unit_test/go/pkg/mod/github.com/pingcap/parser@v0.0.0-20190923031704-33636bc5e5d6/ast/expressions.go:206 +0x22e
[2019-10-09T07:39:23.880Z]   github.com/pingcap/parser/ast.(*ParenthesesExpr).Accept()
[2019-10-09T07:39:23.880Z]       /home/jenkins/workspace/tidb_ghpr_unit_test/go/pkg/mod/github.com/pingcap/parser@v0.0.0-20190923031704-33636bc5e5d6/ast/expressions.go:942 +0x152
[2019-10-09T07:39:23.880Z]   github.com/pingcap/tidb/planner/core.(*PlanBuilder).rewriteExprNode()
[2019-10-09T07:39:23.880Z]       /home/jenkins/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/planner/core/expression_rewriter.go:139 +0x72
[2019-10-09T07:39:23.880Z]   github.com/pingcap/tidb/planner/core.(*PlanBuilder).rewriteWithPreprocess()
[2019-10-09T07:39:23.880Z]       /home/jenkins/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/planner/core/expression_rewriter.go:109 +0x26a
[2019-10-09T07:39:23.880Z]   github.com/pingcap/tidb/planner/core.(*PlanBuilder).buildProjection()
[2019-10-09T07:39:23.880Z]       /home/jenkins/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/planner/core/logical_plan_builder.go:769 +0x814
[2019-10-09T07:39:23.880Z]   github.com/pingcap/tidb/planner/core.(*PlanBuilder).buildSelect()
[2019-10-09T07:39:23.880Z]       /home/jenkins/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/planner/core/logical_plan_builder.go:2148 +0xae9
[2019-10-09T07:39:23.880Z]   github.com/pingcap/tidb/planner/core.(*PlanBuilder).Build()
[2019-10-09T07:39:23.881Z]       /home/jenkins/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/planner/core/planbuilder.go:353 +0x1025
[2019-10-09T07:39:23.881Z]   github.com/pingcap/tidb/planner.optimize()
[2019-10-09T07:39:23.881Z]       /home/jenkins/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/planner/optimize.go:74 +0x224
[2019-10-09T07:39:23.881Z]   github.com/pingcap/tidb/planner.Optimize()
[2019-10-09T07:39:23.881Z]       /home/jenkins/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/planner/optimize.go:52 +0x222
[2019-10-09T07:39:23.881Z]   github.com/pingcap/tidb/executor.(*Compiler).Compile()
[2019-10-09T07:39:23.881Z]       /home/jenkins/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/compiler.go:62 +0x28c
[2019-10-09T07:39:23.881Z]   github.com/pingcap/tidb/session.(*session).execute()
[2019-10-09T07:39:23.881Z]       /home/jenkins/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/session/session.go:1103 +0x887
[2019-10-09T07:39:23.881Z]   github.com/pingcap/tidb/session.(*session).Execute()
[2019-10-09T07:39:23.881Z]       /home/jenkins/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/session/session.go:1056 +0xee
[2019-10-09T07:39:23.881Z]   github.com/pingcap/tidb/util/testkit.(*TestKit).Exec()
[2019-10-09T07:39:23.881Z]       /home/jenkins/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/util/testkit/testkit.go:144 +0x103
[2019-10-09T07:39:23.881Z]   github.com/pingcap/tidb/util/testkit.(*TestKit).MustQuery()
[2019-10-09T07:39:23.881Z]       /home/jenkins/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/util/testkit/testkit.go:229 +0x208
[2019-10-09T07:39:23.881Z]   github.com/pingcap/tidb/expression_test.(*testIntegrationSuite).TestCompareBuiltin()
[2019-10-09T07:39:23.881Z]       /home/jenkins/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/expression/integration_test.go:3211 +0x820
[2019-10-09T07:39:23.881Z]   github.com/pingcap/tidb/expression_test.(*testIntegrationSuite).TestCompareBuiltin()
[2019-10-09T07:39:23.881Z]       /home/jenkins/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/expression/integration_test.go:3180 +0x1ae
```

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

0237e0219e8258f50adf37f8c5140e405ad0bf14

**Comment by wshwsh12** [comment] 2020-12-09 08:28
I can't reproduce the problem.  The last appeared time is 2 month ago or earlier. Maybe it has been fixed.  I close the issue now.  We can reopen this issue when the problem appear again.

**Closed by wshwsh12** 2020-12-09 08:28 UTC
Labels: component/expression, component/test, severity/major, sig/execution, status/can't-reproduce, type/bug
