### ISSUE TITLE
SpillAction blocks servermemorylimit global kill

### ISSUE THREAD

**Issue by wshwsh12** [pingcap/tidb#41329] opened 2023-02-13 06:38 UTC
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

1. Run a sql need spilling long time. 
2. Trigger spill action
3. Trigger global kill.
4. SQL can't exit in time, until spill is finished.

### 4. What is your TiDB version? (Required)
master, v6.5

**Comment by XuHuaiyu** [comment] 2023-02-13 10:21
Test script:
[issue41329.txt](https://github.com/pingcap/tidb/files/10721162/issue41329.txt)

Some hacks for easily reproduce the problem(base commit: 79ae1e3c1f0ab30223c75a3d4b3bd82e0f971d68):
``` diff
diff --git a/executor/join.go b/executor/join.go
index 91533be225..2aab0f43e7 100644
--- a/executor/join.go
+++ b/executor/join.go
@@ -222,6 +222,7 @@ func (e *HashJoinExec) Open(ctx context.Context) error {
 // and sends the chunks to multiple channels which will be read by multiple join workers.
 func (fetcher *probeSideTupleFetcher) fetchProbeSideChunks(ctx context.Context, maxChunkSize int) {
 	hasWaitedForBuild := false
+	time.Sleep(time.Second)
 	for {
 		if fetcher.finished.Load() {
 			return
diff --git a/executor/table_reader.go b/executor/table_reader.go
index 3e29dfe27b..79f9415480 100644
--- a/executor/table_reader.go
+++ b/executor/table_reader.go
@@ -17,6 +17,7 @@ package executor
 import (
 	"bytes"
 	"context"
+	"fmt"
 	"time"
 
 	"github.com/pingcap/failpoint"
@@ -248,6 +249,10 @@ func (e *TableReaderExecutor) Next(ctx context.Context, req *chunk.Chunk) error
 		}
 		return tableName
 	}), e.ranges)
+	if e.ctx.GetSessionVars().ConnectionID > 0 {
+		logutil.BgLogger().Warn(fmt.Sprintf("tablereader %d reads data", e.id))
+		e.memTracker.Consume(2 << 30)
+	}
 	if err := e.resultHandler.nextChunk(ctx, req); err != nil {
 		e.feedback.Invalidate()
 		return err
diff --git a/util/chunk/row_container.go b/util/chunk/row_container.go
index 7ae1a67879..6cf427642c 100644
--- a/util/chunk/row_container.go
+++ b/util/chunk/row_container.go
@@ -132,6 +132,7 @@ func (c *RowContainer) SpillToDisk() {
 			return
 		}
 		c.actionSpill.setStatus(spilling)
+		time.Sleep(2 * time.Second)
 		defer c.actionSpill.cond.Broadcast()
 		defer c.actionSpill.setStatus(spilledYet)
 	}
@@ -392,6 +393,8 @@ func (a *SpillDiskAction) Action(t *memory.Tracker) {
 
 	a.cond.L.Lock()
 	for a.cond.status == spilling {
+		logutil.BgLogger().Warn("spilling")
+		time.Sleep(20 * time.Second)
 		a.cond.Wait()
 	}
 	a.cond.L.Unlock()
diff --git a/util/servermemorylimit/servermemorylimit.go b/util/servermemorylimit/servermemorylimit.go
index 511a86703d..0809fcaa8d 100644
--- a/util/servermemorylimit/servermemorylimit.go
+++ b/util/servermemorylimit/servermemorylimit.go
@@ -119,7 +119,11 @@ func killSessIfNeeded(s *sessionToBeKilled, bt uint64, sm util.SessionManager) {
 	if instanceStats.HeapInuse > MemoryMaxUsed.Load() {
 		MemoryMaxUsed.Store(instanceStats.HeapInuse)
 	}
-	if instanceStats.HeapInuse > bt {
+	top1 := memory.MemUsageTop1Tracker.Load()
+
+	if top1 != nil && top1.SessionID > 0 {
+		time.Sleep(500 * time.Microsecond)
+		//if instanceStats.HeapInuse > bt {
 		t := memory.MemUsageTop1Tracker.Load()
 		if t != nil {
 			if info, ok := sm.GetProcessInfo(t.SessionID); ok {

```

**Comment by XuHuaiyu** [comment] 2023-02-13 10:26
From the log `[2023/02/13 18:17:05.944 +08:00] [WARN] [tracker.go:458] ["global memory controller, NeedKill signal is received successfully"] [connID=2199023255955]
`, we know that global memory controller sends the kill signal successfully.

But it fails to kill the query, because the spill action is ongoing, and tryLastAction is waiting on the `mu.lock`.
https://github.com/pingcap/tidb/blob/be740110f454ef78e0ea41b244e9de4c315547f2/util/memory/tracker.go#L441-L462


Full log:
``` sh
[2023/02/13 18:17:04.943 +08:00] [WARN] [table_reader.go:253] ["tablereader 12 reads data"]
[2023/02/13 18:17:04.944 +08:00] [WARN] [table_reader.go:253] ["tablereader 12 reads data"]
[2023/02/13 18:17:04.944 +08:00] [INFO] [row_container.go:378] ["memory exceeds quota, spill to disk now."] [consumed=4294977536] [quota=3221225472]
[2023/02/13 18:17:04.944 +08:00] [WARN] [row_container.go:396] [spilling]
[2023/02/13 18:17:04.950 +08:00] [WARN] [servermemorylimit.go:130] ["global memory controller tries to kill the top1 memory consumer"] [connID=2199023255955] ["sql digest"=4a8206b967b81ce1e68282ae5c541bd1f21c65adc82c72c5e5f48de2647ed69e] ["sql text"="desc analyze select * from t join t s"] [tidb_server_memory_limit=107374182400] ["heap inuse"=319438848] ["sql memory usage"=4295009226]
[2023/02/13 18:17:05.944 +08:00] [WARN] [table_reader.go:253] ["tablereader 10 reads data"]
[2023/02/13 18:17:05.944 +08:00] [WARN] [tracker.go:458] ["global memory controller, NeedKill signal is received successfully"] [connID=2199023255955]
[2023/02/13 18:17:10.050 +08:00] [WARN] [servermemorylimit.go:96] ["global memory controller failed to kill the top-consumer in 5s"] [connID=2199023255955] ["sql digest"=4a8206b967b81ce1e68282ae5c541bd1f21c65adc82c72c5e5f48de2647ed69e] ["sql text"="desc analyze select * from t join t s"] ["sql memory usage"=6442484434]
[2023/02/13 18:17:14.749 +08:00] [INFO] [update.go:1181] ["[stats] auto analyze triggered"] [sql="analyze table `test`.`t`"] [reason="table unanalyzed"]
[2023/02/13 18:17:14.759 +08:00] [INFO] [handle.go:1593] ["[stats] incrementally update modifyCount"] [tableID=97] [curModifyCnt=1024] [results.BaseModifyCnt=1024] [modifyCount=0]
[2023/02/13 18:17:14.759 +08:00] [INFO] [handle.go:1615] ["[stats] directly update count"] [tableID=97] [results.Count=1024] [count=1024]
[2023/02/13 18:17:14.765 +08:00] [INFO] [analyze.go:589] ["analyze table `test`.`t` has finished"] [partition=] ["job info"="auto analyze table all columns with 256 buckets, 500 topn, 1 samplerate"] ["start time"=2023/02/13 18:17:14.751 +08:00] ["end time"=2023/02/13 18:17:14.764 +08:00] [cost=13.263732ms]
[2023/02/13 18:17:15.150 +08:00] [WARN] [servermemorylimit.go:96] ["global memory controller failed to kill the top-consumer in 10s"] [connID=2199023255955] ["sql digest"=4a8206b967b81ce1e68282ae5c541bd1f21c65adc82c72c5e5f48de2647ed69e] ["sql text"="desc analyze select * from t join t s"] ["sql memory usage"=6442484434]
[2023/02/13 18:17:20.250 +08:00] [WARN] [servermemorylimit.go:96] ["global memory controller failed to kill the top-consumer in 15s"] [connID=2199023255955] ["sql digest"=4a8206b967b81ce1e68282ae5c541bd1f21c65adc82c72c5e5f48de2647ed69e] ["sql text"="desc analyze select * from t join t s"] ["sql memory usage"=6442484434]
[2023/02/13 18:17:24.944 +08:00] [WARN] [expensivequery.go:118] ["memory exceeds quota"] [cost_time=20.001953699s] [cop_time=0.000391786s] [request_count=4] [num_cop_tasks=4] [process_avg_time=0s] [process_p90_time=0s] [process_max_time=0s] [process_max_addr=store1] [wait_avg_time=0s] [wait_p90_time=0s] [wait_max_time=0s] [wait_max_addr=store1] [stats=t:pseudo] [conn_id=2199023255955] [user=root] [database=test] [table_ids="[97,97]"] [txn_start_ts=439427642148257792] [mem_max="6442492874 Bytes (6.00 GB)"] [sql="desc analyze select * from t join t s"]
[2023/02/13 18:17:24.946 +08:00] [INFO] [conn.go:1158] ["command dispatched failed"] [conn=2199023255955] [connInfo="id:2199023255955, addr:127.0.0.1:62541 status:10, collation:utf8mb4_0900_ai_ci, user:root"] [command=Query] [status="inTxn:0, autocommit:1"] [sql="desc analyze select * from t join t s"] [txn_mode=PESSIMISTIC] [timestamp=439427642148257792] [err="Out Of Memory Quota![conn_id=2199023255955]\ngithub.com/pingcap/tidb/executor.(*probeSideTupleFetcher).handleProbeSideFetcherPanic\n\t/Users/xuhuaiyu/Development/GOPATH/src/github.com/pingcap/tidb/executor/join.go:392\ngithub.com/pingcap/tidb/util.(*WaitGroupWrapper).RunWithRecover.func1.1\n\t/Users/xuhuaiyu/Development/GOPATH/src/github.com/pingcap/tidb/util/wait_group_wrapper.go:168\nruntime.gopanic\n\t/Users/xuhuaiyu/.gvm/gos/go1.19/src/runtime/panic.go:884\ngithub.com/pingcap/tidb/util/memory.(*PanicOnExceed).Action\n\t/Users/xuhuaiyu/Development/GOPATH/src/github.com/pingcap/tidb/util/memory/action.go:148\ngithub.com/pingcap/tidb/util/memory.(*Tracker).Consume.func2\n\t/Users/xuhuaiyu/Development/GOPATH/src/github.com/pingcap/tidb/util/memory/tracker.go:449\ngithub.com/pingcap/tidb/util/memory.(*Tracker).Consume\n\t/Users/xuhuaiyu/Development/GOPATH/src/github.com/pingcap/tidb/util/memory/tracker.go:461\ngithub.com/pingcap/tidb/executor.(*TableReaderExecutor).Next\n\t/Users/xuhuaiyu/Development/GOPATH/src/github.com/pingcap/tidb/executor/table_reader.go:254\ngithub.com/pingcap/tidb/executor.Next\n\t/Users/xuhuaiyu/Development/GOPATH/src/github.com/pingcap/tidb/executor/executor.go:324\ngithub.com/pingcap/tidb/executor.(*probeSideTupleFetcher).fetchProbeSideChunks\n\t/Users/xuhuaiyu/Development/GOPATH/src/github.com/pingcap/tidb/executor/join.go:246\ngithub.com/pingcap/tidb/executor.(*HashJoinExec).fetchAndProbeHashTable.func1\n\t/Users/xuhuaiyu/Development/GOPATH/src/github.com/pingcap/tidb/executor/join.go:374\ngithub.com/pingcap/tidb/util.(*WaitGroupWrapper).RunWithRecover.func1\n\t/Users/xuhuaiyu/Development/GOPATH/src/github.com/pingcap/tidb/util/wait_group_wrapper.go:172\nruntime.goexit\n\t/Users/xuhuaiyu/.gvm/gos/go1.19/src/runtime/asm_amd64.s:1594"]
[2023/02/13 18:17:24.958 +08:00] [WARN] [servermemorylimit.go:112] ["global memory controller killed the top1 memory consumer successfully"]

```

**Comment by XuHuaiyu** [comment] 2024-05-08 09:55
Verified and fixed by https://github.com/pingcap/tidb/issues/50511

**Closed by XuHuaiyu** 2024-05-08 09:55 UTC
Labels: type/bug, sig/execution, severity/major, affects-6.5, affects-7.0, affects-7.1, affects-7.5, affects-8.1
