### ISSUE TITLE
plan cache probabilistic failure

### ISSUE THREAD

**Issue by keeplearning20221** [pingcap/tidb#34589] opened 2022-05-12 02:40 UTC
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

1、100 concurrent inserts （use plan cache）
2、delete insert data
3、100 concurrent inserts （may can not use plan cache）
### 2. What did you expect to see? (Required)
insert always use plan cache
### 3. What did you see instead (Required)
may can not use plan cache
### 4. What is your TiDB version? (Required)

Release Version: v6.0.0
Edition: Community
Git Commit Hash: 36a9810441ca0e496cbd22064af274b3be771081
Git Branch: HEAD
UTC Build Time: 2022-04-08 09:31:25
GoVersion: go1.18
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false ))
[归档.zip](https://github.com/pingcap/tidb/files/8674623/default.zip)
clinic:

-f="2022-05-12T09:25:00+08:00" -t="2022-05-12T09:55:00+08:00"

**Comment by yudongusa** [comment] 2022-05-12 06:12
We currently don't support plan cache other than SELECT. @qw4990 please help to confirm.

**Comment by keeplearning20221** [comment] 2022-05-12 06:20
<img width="532" alt="image" src="https://user-images.githubusercontent.com/97376271/168004076-4a15b690-d18f-4747-ab67-b6dc11527412.png">
from Queries Using Plan Cache OPS monitor，You can see that the plan cache is used for the first time.
Grafana monitoring information is wrong？

**Comment by keeplearning20221** [comment] 2022-05-12 06:31
> We currently don't support plan cache other than SELECT. @qw4990 please help to confirm.

<img width="967" alt="image" src="https://user-images.githubusercontent.com/97376271/168006233-c7cba4ac-43a0-4567-b2f6-8f6e1b2cd7b0.png">
https://docs.pingcap.com/zh/tidb/v6.0/sql-prepared-plan-cache

**Comment by Reminiscent** [comment] 2022-05-12 08:05
@keeplearning20221 The problem seems like https://github.com/pingcap/tidb/issues/34295. Please check the `performance.server-memory-quota` and the memory usage of the TiDB server when the plan cache can't be used.

**Comment by qw4990** [comment] 2022-05-12 08:07
> @keeplearning20221 The problem seems like #34295. Please check the `performance.server-memory-quota` and the memory usage of the TiDB server when the plan cache can't be used.

Yes, there is an implicit safe-guard memory protection strategy that when the server's memory usage is large than a fixed threshold the optimizer can evict some elements in the cache.
So please check your `server-memory-quota` config and memory-usage metircs. @keeplearning20221

**Comment by keeplearning20221** [comment] 2022-05-12 08:54
> > @keeplearning20221 The problem seems like #34295. Please check the `performance.server-memory-quota` and the memory usage of the TiDB server when the plan cache can't be used.
> 
> Yes, there is an implicit safe-guard memory protection strategy that when the server's memory usage is large than a fixed threshold the optimizer can evict some elements in the cache. So please check your `server-memory-quota` config and memory-usage metrics. @keeplearning20221

Looks like this is the reason, thanks

**Comment by keeplearning20221** [comment] 2022-05-12 08:54
> > @keeplearning20221 The problem seems like #34295. Please check the `performance.server-memory-quota` and the memory usage of the TiDB server when the plan cache can't be used.
> 
> Yes, there is an implicit safe-guard memory protection strategy that when the server's memory usage is large than a fixed threshold the optimizer can evict some elements in the cache. So please check your `server-memory-quota` config and memory-usage metrics. @keeplearning20221

Looks like this is the reason, thanks

**Comment by qw4990** [comment] 2022-05-12 15:27
> > > @keeplearning20221 The problem seems like #34295. Please check the `performance.server-memory-quota` and the memory usage of the TiDB server when the plan cache can't be used.
> > 
> > 
> > Yes, there is an implicit safe-guard memory protection strategy that when the server's memory usage is large than a fixed threshold the optimizer can evict some elements in the cache. So please check your `server-memory-quota` config and memory-usage metrics. @keeplearning20221
> > Tidb-server memory usage does not exceed the limit.
> > Server memory usage exceeds server-memory-quota limit.

Could you please show us your TiDB server memory usage metrics as well? You can find it in `TiDB-Server` panel.
![image](https://user-images.githubusercontent.com/7499936/168111627-2df884da-199a-4073-afd8-c55390b3fae8.png)

**Comment by keeplearning20221** [comment] 2022-05-14 03:53
![image](https://user-images.githubusercontent.com/97376271/168409764-2ae78de9-3a61-432e-8da7-dc6f18ef91e7.png)

Confirmed to be a bug.

**Comment by qw4990** [comment] 2022-05-16 02:47
> > > @keeplearning20221 The problem seems like #34295. Please check the `performance.server-memory-quota` and the memory usage of the TiDB server when the plan cache can't be used.
> > 
> > 
> > Yes, there is an implicit safe-guard memory protection strategy that when the server's memory usage is large than a fixed threshold the optimizer can evict some elements in the cache. So please check your `server-memory-quota` config and memory-usage metrics. @keeplearning20221
> 
> <img alt="image" width="686" src="https://user-images.githubusercontent.com/97376271/168035019-bcdeb2e4-5446-4052-ab0e-6c4dd5c78fb2.png">
> 
> <img alt="image" width="985" src="https://user-images.githubusercontent.com/97376271/168035152-dd61f5b9-08f2-46e9-a9bc-0d1018bd63f1.png">
> 
> Tidb-server memory usage does not exceed the limit. Server memory usage exceeds server-memory-quota limit. If restart tikv to release memory, the plan cache can be used. Is there a problem with the server-memory-quota limit.

Seems like it caused by this bug(https://github.com/pingcap/tidb/issues/34613), we'll fix it this week.

**Comment by AilinKid** [comment] 2022-05-19 02:47
should we close this since https://github.com/pingcap/tidb/issues/34613 is closed？

**Comment by keeplearning20221** [comment] 2022-05-19 02:51
Can be closed, this problem has been fixed

**Closed** 2022-05-19 02:51 UTC
Labels: type/bug, sig/planner, severity/moderate, epic/plan-cache
