### ISSUE TITLE
DATA RACE in the logutil.InitLogger

### ISSUE THREAD

**Issue by hawkingrei** [pingcap/tidb#40799] opened 2023-01-28 08:03 UTC
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
 === RUN   TestLongBinaryPlan
==================
WARNING: DATA RACE
Write at 0x00000d407e20 by goroutine 195369:
  google.golang.org/grpc/grpclog.SetLoggerV2()
      external/org_golang_google_grpc/grpclog/loggerv2.go:76 +0x21a
  github.com/grpc-ecosystem/go-grpc-middleware/logging/zap.ReplaceGrpcLoggerV2WithVerbosity()
      external/com_github_grpc_ecosystem_go_grpc_middleware/logging/zap/grpclogger.go:63 +0x1f6
  github.com/pingcap/tidb/util/logutil.initGRPCLogger()
      util/logutil/log.go:137 +0xce
  github.com/pingcap/tidb/util/logutil.InitLogger()
      util/logutil/log.go:114 +0x191
  github.com/pingcap/tidb/planner/core_test.TestLongBinaryPlan()
      planner/core/binary_plan_test.go:292 +0x293
  testing.tRunner()
      GOROOT/src/testing/testing.go:1446 +0x216
  testing.(*T).Run.func1()
      GOROOT/src/testing/testing.go:1493 +0x47
Previous read at 0x00000d407e20 by goroutine 195366:
  google.golang.org/grpc/internal/grpclog.InfoDepth()
      external/org_golang_google_grpc/internal/grpclog/grpclog.go:37 +0x93
  google.golang.org/grpc/grpclog.(*componentData).InfoDepth()
      external/org_golang_google_grpc/grpclog/component.go:36 +0x16b
  google.golang.org/grpc/internal/channelz.AddTraceEvent()
      external/org_golang_google_grpc/internal/channelz/funcs.go:340 +0x428
  google.golang.org/grpc/internal/channelz.Infof()
      external/org_golang_google_grpc/internal/channelz/logging.go:43 +0xd3
  google.golang.org/grpc.(*connectivityStateManager).updateState()
      external/org_golang_google_grpc/clientconn.go:418 +0x1b4
  google.golang.org/grpc.(*ccBalancerWrapper).UpdateState()
      external/org_golang_google_grpc/balancer_conn_wrappers.go:351 +0xc7
  google.golang.org/grpc/internal/balancer/gracefulswitch.(*balancerWrapper).UpdateState()
      external/org_golang_google_grpc/internal/balancer/gracefulswitch/gracefulswitch.go:317 +0x2eb
  google.golang.org/grpc.(*pickfirstBalancer).UpdateSubConnState()
      external/org_golang_google_grpc/pickfirst.go:145 +0x566
  google.golang.org/grpc/internal/balancer/gracefulswitch.(*balancerWrapper).UpdateSubConnState()
      external/org_golang_google_grpc/internal/balancer/gracefulswitch/gracefulswitch.go:266 +0x13b
  google.golang.org/grpc/internal/balancer/gracefulswitch.(*Balancer).UpdateSubConnState()
      external/org_golang_google_grpc/internal/balancer/gracefulswitch/gracefulswitch.go:223 +0x312
  google.golang.org/grpc.(*ccBalancerWrapper).handleSubConnStateChange()
      external/org_golang_google_grpc/balancer_conn_wrappers.go:218 +0x304
  google.golang.org/grpc.(*ccBalancerWrapper).watcher()
      external/org_golang_google_grpc/balancer_conn_wrappers.go:125 +0x263
  google.golang.org/grpc.newCCBalancerWrapper.func1()
      external/org_golang_google_grpc/balancer_conn_wrappers.go:76 +0x39
Goroutine 195369 (running) created at:
  testing.(*T).Run()
      GOROOT/src/testing/testing.go:1493 +0x75d
  testing.runTests.func1()
      GOROOT/src/testing/testing.go:1846 +0x99
  testing.tRunner()
      GOROOT/src/testing/testing.go:1446 +0x216
  testing.runTests()
      GOROOT/src/testing/testing.go:1844 +0x7ec
  testing.(*M).Run()
      GOROOT/src/testing/testing.go:1726 +0xa84
  github.com/pingcap/tidb/testkit/testmain.(*testingM).Run()
      testkit/testmain/wrapper.go:27 +0x42
  go.uber.org/goleak.VerifyTestMain()
      external/org_uber_go_goleak/testmain.go:53 +0x70
  github.com/pingcap/tidb/planner/core.TestMain()
      planner/core/main_test.go:72 +0xc29
  main.main()
      bazel-out/k8-fastbuild/bin/planner/core/core_test_/testmain.go:1588 +0x5e8
Goroutine 195366 (finished) created at:
  google.golang.org/grpc.newCCBalancerWrapper()
      external/org_golang_google_grpc/balancer_conn_wrappers.go:76 +0x4ba
  google.golang.org/grpc.DialContext()
      external/org_golang_google_grpc/clientconn.go:285 +0x2004
  github.com/tikv/client-go/v2/internal/locate.createKVHealthClient()
      external/com_github_tikv_client_go_v2/internal/locate/region_cache.go:2643 +0x6c4
  github.com/tikv/client-go/v2/internal/locate.invokeKVStatusAPI()
      external/com_github_tikv_client_go_v2/internal/locate/region_cache.go:2587 +0x171
  github.com/tikv/client-go/v2/internal/locate.(*Store).requestLiveness.func1()
      external/com_github_tikv_client_go_v2/internal/locate/region_cache.go:2546 +0x51
  golang.org/x/sync/singleflight.(*Group).doCall.func2()
      external/org_golang_x_sync/singleflight/singleflight.go:189 +0xb4
  golang.org/x/sync/singleflight.(*Group).doCall()
      external/org_golang_x_sync/singleflight/singleflight.go:191 +0x111
  golang.org/x/sync/singleflight.(*Group).DoChan.func1()
      external/org_golang_x_sync/singleflight/singleflight.go:129 +0x71
================== 
```

**Comment by YangKeao** [comment] 2023-02-08 10:51
This issue is a little weird: the data race is in the following codes:

```
func TestLongBinaryPlan(t *testing.T) {
	originCfg := config.GetGlobalConfig()
	newCfg := *originCfg
	f, err := os.CreateTemp("", "tidb-slow-*.log")
	require.NoError(t, err)
	newCfg.Log.SlowQueryFile = f.Name()
	config.StoreGlobalConfig(&newCfg)
	defer func() {
		config.StoreGlobalConfig(originCfg)
		require.NoError(t, f.Close())
		require.NoError(t, os.Remove(newCfg.Log.SlowQueryFile))
	}()
	require.NoError(t, logutil.InitLogger(newCfg.Log.ToLogConfig()))
```

However, when calling the `require.NoError(t, logutil.InitLogger(newCfg.Log.ToLogConfig()))`, I don't think there has been a goroutine setupped for other workloads. The `read` goroutine shown in the issue is part of the `client-go`. I don't think that goroutine is started by this test. I wonder whether these tests are executed concurrently :thinking:

**Comment by hawkingrei** [comment] 2023-02-11 05:31
TestLongBinaryPlan have a flaky test too.

```
    binary_plan_test.go:314: 
        	Error Trace:	/home/jenkins/.tidb/tmp/63a9840cd0739f2c243bb46478607469/execroot/__main__/bazel-out/k8-fastbuild/bin/planner/core/core_test_/core_test.runfiles/__main__/planner/core/binary_plan_test.go:314
        	Error:      	"1052064" is not less than "1048576"
        	Test:       	TestLongBinaryPlan
```

**Comment by YangKeao** [comment] 2024-01-05 07:32
This issue seems too weird (as the code path is really short and simple), and it seems that it's irreproducible, so I'll close it. Once it appears again, feel free to re-open it.

**Closed by YangKeao** 2024-01-05 07:32 UTC
Labels: type/bug, component/test, sig/sql-infra, severity/major, affects-6.6, affects-7.0, affects-7.1, affects-7.5
