### ISSUE TITLE
sysbench report "Information schema is out of date"，TiKV log show "Region is unavailable"

### ISSUE THREAD

**Issue by Lily2025** [pingcap/tidb#26544] opened 2021-07-26 04:02 UTC
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

1. run sysbench work load 
tableNum = 128
tableSize = 10000000000
threads=128

run_type = 'oltp_write_only'
2. About after 20 minutes，report some error

### 2. What did you expect to see? (Required)
The workload is running normally

### 3. What did you see instead (Required)
About after 20 minutes，report some error
![4dea1c99-a6e1-4e13-b3c4-1c4e4ef443da](https://user-images.githubusercontent.com/84712107/126931270-bfec7a83-f084-49ef-95c0-8de9e6cf4756.png)

### 4. What is your TiDB version? (Required)
| Release Version: v5.1.1
Edition: Community
Git Commit Hash: fb0eaf7b44b9ddb1494bf8194d8e361c538146dc
Git Branch: heads/refs/tags/v5.1.1
UTC Build Time: 2021-07-23 13:18:59
GoVersion: go1.16.4
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false |

**Comment by sticnarf** [comment] 2021-07-26 08:28
I encountered the same problem before when I was testing high write pressure on TiDB. The root cause is probably https://github.com/tikv/tikv/issues/10169. The issue makes the region containing the schema data cannot serve read requests, so TiDB cannot update its schema in time.

This issue is expected to be solved after https://github.com/tikv/tikv/pull/10249 remove the write stall from TiKV.

**Comment by cfzjywxk** [comment] 2021-08-31 08:28
@sticnarf 
Should we close this issue by now?

**Comment by sticnarf** [comment] 2021-08-31 11:28
> 
> 
> @sticnarf
> Should we close this issue by now?

I think so. After write stall is removed, this issue should not happen.

@Lily2025 If you encounter the same problem after TiKV 5.2, free free to reopen this issue.

**Closed by sticnarf** 2021-08-31 11:28 UTC
Labels: type/bug, sig/transaction, severity/major
