### ISSUE TITLE
update query does not update expected rows

### ISSUE THREAD

**Issue by ravishetye** [pingcap/tidb#16447] opened 2020-04-15 20:03 UTC
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. What did you do?

The select query  returns one row

```
select * 
from uac.rbac_role_binding_modeldb_map  
where rbac_role_binding_modeldb_map.binding_id in (
  select id from uac.rbac_role_binding_base where name LIKE CONCAT('PROJECT_OWNER_PROJECT_%_User_',@old_owner_id) 
  ) and 
rbac_role_binding_modeldb_map.resource_id in (select id from modeldb.project where owner = @old_owner_id )
 and entity_id = @old_owner_id  and entity_type = 3 and resource_type = 2;
```

but the update query updates zero rows
```
UPDATE  uac.rbac_role_binding_modeldb_map   SET entity_id=@new_owner_id
where rbac_role_binding_modeldb_map.binding_id in (
  select id from uac.rbac_role_binding_base where name LIKE CONCAT('PROJECT_OWNER_PROJECT_%_User_',@old_owner_id) 
  ) and 
rbac_role_binding_modeldb_map.resource_id in (select id from modeldb.project where owner = @old_owner_id ) 
 and entity_id = @old_owner_id  and entity_type = 3 and resource_type = 2; 
```

### 2. What did you expect to see?
update query updates the same number of rows as returned by select

### 3. What did you see instead?
update query did not update any rows

### 4. What version of TiDB are you using? (`tidb-server -V` or run `select tidb_version();` on TiDB)
```
Release Version: v3.0.4
Git Commit Hash: 694e086e7914a8fc0eb601327edb6bcc31d2c7f2
Git Branch: HEAD
UTC Build Time: 2019-10-08 08:13:34
GoVersion: go version go1.12.10 linux/amd64
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
```

**Comment by ravishetye** [comment] 2020-04-15 20:05
not 100% sure but may be `name LIKE CONCAT('PROJECT_OWNER_PROJECT_%_User_',@old_owner_id) ` is update is creating the incorrect result?

**Comment by ravishetye** [comment] 2020-04-15 20:18
some more testing leads me to believe it is the in operator
```
rbac_role_binding_modeldb_map.binding_id in (
  select id from uac.rbac_role_binding_base
```

**Comment by ravishetye** [comment] 2020-04-15 20:36
This worked 

```
 UPDATE  uac.rbac_role_binding_modeldb_map ,  uac.rbac_role_binding_base, modeldb.project   SET rbac_role_binding_modeldb_map.entity_id=@new_owner_id
where rbac_role_binding_modeldb_map.binding_id =  rbac_role_binding_base.id and rbac_role_binding_base.name LIKE CONCAT('PROJECT_OWNER_PROJECT_%_User_',@old_owner_id) 
  and rbac_role_binding_modeldb_map.resource_id = project.id and owner = @old_owner_id  
  and rbac_role_binding_modeldb_map.entity_id = @old_owner_id  and rbac_role_binding_modeldb_map.entity_type = 3 and rbac_role_binding_modeldb_map.resource_type = 2;
```

if possible then I would expect an error instead of an update count of 0

**Comment by cfzjywxk** [comment] 2020-04-16 01:50
@ravishetye Thanks for your feedback, could you provide us the table schema related to this query or steps to reproduce this issue

**Comment by wjhuang2016** [comment] 2021-01-05 07:12
Close this issue because the bug can be reproduced, and this issue has not been active for a long time.

**Closed by wjhuang2016** 2021-01-05 07:12 UTC
Labels: severity/moderate, status/can't-reproduce, type/bug
