### ISSUE TITLE
Range Partitioned: Unsupport range by multi-columns

### ISSUE THREAD

**Issue by tshqin** [pingcap/tidb#20068] opened 2020-09-17 09:10 UTC
## Description
```
DROP TABLE IF EXISTS t_5_1_1_6_partition_range_02;
CREATE TABLE t_5_1_1_6_partition_range_02 ( id INT, col1 CHAR(32), col2 CHAR(32), PRIMARY KEY(id,col1) )
PARTITION BY RANGE COLUMNS (id,col1) (
  PARTITION prange1 VALUES LESS THAN (10,'h'),
  PARTITION prange2 VALUES LESS THAN (20,'m'),
  PARTITION prange3 VALUES LESS THAN (50,'z')
);
INSERT INTO t_5_1_1_6_partition_range_02 VALUES (60,'z','z');
```

TiDB 4.0.5
```
mysql> INSERT INTO t_5_1_1_6_partition_range_02 VALUES (60,'z','z');
Query OK, 1 row affected (0.01 sec)
mysql> SELECT * FROM t_5_1_1_6_partition_range_02;
+----+------+------+
| id | col1 | col2 |
+----+------+------+
| 60 | z    | z    |
+----+------+------+
1 row in set (0.00 sec)
```

MySQL 5.7.29
```
mysql> INSERT INTO t_5_1_1_6_partition_range_02 VALUES (60,'z','z');
ERROR 1526 (HY000): Table has no partition for value from column_list
```

## SIG slack channel
[#sig-exec](https://slack.tidb.io/invite?team=tidb-community&channel=sig-exec&ref=high-performance)

## Score
- 300

## Mentor
 * @qw4990

**Comment by lysu** [comment] 2020-09-23 03:43
it's not a bug,  just as create table's warning info, the current range partition could not support ranged by multi-columns and treat it as a normal table(just as show create table said), so it seems "can insert out of range"

```
CREATE TABLE t_5_1_1_6_partition_range_02 ( id INT, col1 CHAR(32), col2 CHAR(32), PRIMARY KEY(id,col1) )
    -> PARTITION BY RANGE COLUMNS (id,col1) (
    ->   PARTITION prange1 VALUES LESS THAN (10,'h'),
    ->   PARTITION prange2 VALUES LESS THAN (20,'m'),
    ->   PARTITION prange3 VALUES LESS THAN (50,'z')
    -> );
Query OK, 0 rows affected, 1 warning (0.014 sec)

MySQL [test]> show warnings;
+---------+------+---------------------------------------------------+
| Level   | Code | Message                                           |
+---------+------+---------------------------------------------------+
| Warning | 8200 | Unsupported partition type, treat as normal table |
+---------+------+---------------------------------------------------+
1 row in set (0.001 sec)

MySQL [test]> show create table t_5_1_1_6_partition_range_02;
+------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Table                        | Create Table                                                                                                                                                                                                               |
+------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| t_5_1_1_6_partition_range_02 | CREATE TABLE `t_5_1_1_6_partition_range_02` (
  `id` int(11) NOT NULL,
  `col1` char(32) NOT NULL,
  `col2` char(32) DEFAULT NULL,
  PRIMARY KEY (`id`,`col1`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin |
+------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.001 sec)
```

current maybe we should support multi columns range in right time because many users maybe need it

cc @tiancaiamao @imtbkcat @zz-jason @scsldb @morgo  do we need support it in 5.0 ?

**Comment by nullnotnil** [comment] 2020-09-23 03:51
Even though it caused some confusion, I like that this is a warning, instead of an error :-) It could be important for compatibility with restoring logical backups.

To answer your question though, I am not sure about the relative priority of multi-column range. I think we can leave it as `priority/awaiting-more-evidence` until a user reports it as an issue, and has a compelling use-case?

**Comment by crazycs520** [comment] 2020-10-13 07:44
Should be supported in https://github.com/bb7133/tidb/pull/26

**Comment by mjonss** [comment] 2022-09-23 12:36
Closing this since the support has been added in #36636.

**Closed by mjonss** 2022-09-23 12:36 UTC
Labels: sig/execution, type/feature-request, feature/accepted, component/tablepartition
