### ISSUE TITLE
using syncer to synchronize binlog to tidb error from Alibaba Cloud's RDS (mysql5.6).

### ISSUE THREAD

**Issue by ericisme** [pingcap/tidb#9515] opened 2019-02-28 14:54 UTC
syncer.log显示如下，
注：Syncer 同步前检查全都ok, 就是阿里云不显示sql_model, 因此tidb(2.1.4)这边用了默认sql_model(未修改)。

syncer.go:784: [info] [ddl][schema]erp [start]USE `erp`; CREATE TABLE `SLLX_0228` (`SKU` varchar(255),`num` varchar(255),`CK` varchar(255));
2019/02/28 22:45:34 meta.go:135: [info] save position to file, binlog-name:mysql-bin.002187 binlog-pos:200059840 binlog-gtid:
2019/02/28 22:45:34 syncer.go:792: [info] [ddl][end]USE `erp`; CREATE TABLE `SLLX_0228` (`SKU` varchar(255),`num` varchar(255),`CK` varchar(255));
2019/02/28 22:45:34 syncer.go:1006: [info] flush all jobs meta = syncer-binlog = (mysql-bin.002187, 200059840), syncer-binlog-gtid = 
2019/02/28 22:45:34 meta.go:135: [info] save position to file, binlog-name:mysql-bin.002187 binlog-pos:200059840 binlog-gtid:
2019/02/28 22:45:34 main.go:79: [error] /home/jenkins/workspace/build_tidb_enterprise_tools_master/go/src/github.com/pingcap/tidb-enterprise-tools/syncer/syncer.go:680: gen insert sqls failed: insert columns and data mismatch in length: 3 vs 4, schema: erp, table: sllx_0228
/home/jenkins/workspace/build_tidb_enterprise_tools_master/go/src/github.com/pingcap/tidb-enterprise-tools/syncer/syncer.go:189:  
2019/02/28 22:45:34 syncer.go:917: [info] print status exits, err:context canceled

**Comment by csuzhangxc** [comment] 2019-02-28 15:17
I think the error was caused by `implict_primary_key` column in RDS.
You can read the doc for DM about this, it's similar.
<https://github.com/pingcap/tidb-tools/blob/docs/docs/dm/zh_CN/vendors/aliyun-rds.md#implict_primary_key-%E9%80%A0%E6%88%90%E5%90%8C%E6%AD%A5%E4%B8%AD%E6%96%AD>

**Comment by ericisme** [comment] 2019-03-01 00:47
@csuzhangxc thank you very much, i think that must be the problem

**Comment by ericisme** [comment] 2019-03-01 06:53
@csuzhangxc I check my aliyun RDS params today, and found that 
feature params `implict_primary_key`  is only in mysql5.5,  in RDS mysql5.6 has not that setting, 
and i search baidu show mysql5.6 officail has a other method to deal with no pk table sync problem, 
eg: http://www.ywnds.com/?p=12775 

"
2. 官方为了解决这个问题，在5.6.6及以后版本引入参数slave_rows_search_algorithms ，用于指示备库在apply_binlog_event时使用的算法，slave_rows_search_algorithms的文档描述的非常清晰，该变量由三个值的组合组成（就三种算法）：TABLE_SCAN，INDEX_SCAN， HASH_SCAN，可以任意组合。其中TABLE_SCAN与INDEX_SCAN是已经存在的，也是默认组合配置，表示如果有索引就用索引，否则使用全表扫描。本文主要研究HASH_SCAN的实现方式。
"

that means that no pk table sync binlog feature is mysql offcially? and tidb will supoort that feature or not?

**Comment by morgo** [comment] 2019-03-01 16:25
> that means that no pk table sync binlog feature is mysql offcially? and tidb will supoort that feature or not?

There is a feature like this in MySQL 8.0 called `sql_require_primary_key`.  It works a little bit differently though, it's not implicit but an error if a table is missing a primary key.

**Comment by csuzhangxc** [comment] 2019-03-02 01:17
@ericisme I think `slave_rows_search_algorithms` is used to control how the rows are searched for matches when applying SQL to downstream.
But your problem is trying to construct a SQL with 4 values (in binlog) and 3 columns (in downstream table structure).
You can check your upstream table structure to confirm how many columns (4 or 3) exist in ``` `erp`.`sllx_0228` ``` and is there any implicit column.

**Comment by csuzhangxc** [comment] 2019-05-05 07:15
@ericisme have you solved the problem?

**Comment by jebter** [comment] 2024-06-05 06:24
The issue has not been updated for too long, so I will close it. If there are any updates, you can reopen it.

**Closed by jebter** 2024-06-05 06:24 UTC
Labels: type/question, component/tools, component/syncer
