### ISSUE TITLE
Unexpected DELETE caused by COLLATE

### ISSUE THREAD

**Issue by sayJason** [pingcap/tidb#32802] opened 2022-03-03 09:38 UTC
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```sql
DROP TABLE IF EXISTS t0;
CREATE TABLE IF NOT EXISTS t0(c0 NUMERIC);
INSERT INTO t0 VALUES(NULL);
DELETE FROM t0 WHERE t0.c0 OR ('a' COLLATE 'binary');
```

### 2. What did you expect to see? (Required)
DELETE should not delete the NULL row, because the where clause is evaluated as NULL.
### 3. What did you see instead (Required)
```sql
mysql> DELETE FROM t0 WHERE t0.c0 OR ('a' COLLATE 'binary');
Query OK, 1 row affected (0.01 sec)
```
### 4. What is your TiDB version? (Required)
```sql
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| tidb_version()

                                                                       |
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Release Version: v5.4.0
Edition: Community
Git Commit Hash: 55f3b24c1c9f506bd652ef1d162283541e428872
Git Branch: heads/refs/tags/v5.4.0
UTC Build Time: 2022-01-25 08:39:26
GoVersion: go1.16.4
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false |
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)
```

**Comment by sayJason** [comment] 2022-03-03 09:40
I notice this issue https://github.com/pingcap/tidb/issues/32382, where the UPDATE statement have the similar or same where clause. Does the same reason cause these two problems?

**Comment by zanmato1984** [comment] 2022-04-24 10:45
There are several caveats in this issue:

1. The `OR` expression, along with `NULL` on either side, doesn't behave as you expected. For example, if you replace `('a' COLLATE 'binary')` with `1`, on MySQL 8.0:
```
mysql> DELETE FROM t0 WHERE t0.c0 OR 1;
Query OK, 1 row affected (0.01 sec)
```
Meaning `NULL OR 1` evaluates to `1`, not `NULL`. So your basic assumption about this case is wrong.

2. The real problem in this case is `('a' COLLATE 'binary')` evaluates to `1`, through some unexpected implicit cast, on TiDB. Meanwhile MySQL 8.0 will report:
```
mysql> DELETE FROM t0 WHERE t0.c0 OR ('a' COLLATE 'utf8mb4_bin');
ERROR 1292 (22007): Truncated incorrect DOUBLE value: 'a'
```
(I had to replace `binary` with `utf8mb4_bin` as MySQL 8.0 doesn't recognize `binary` as a valid collate for `utf8mb4` charset, but it's irrelevant with this issue).
Apparently MySQL 8.0 prohibits the implicit cast from a string literal `'a'` to a double, but TiDB allows it.

So I think we should target point 2 above. And the priority might be lowered to moderate or minor.

@sayJason PTAL.

**Comment by zanmato1984** [comment] 2022-04-24 11:05
There are several caveats in this issue:

1. The `OR` expression, along with `NULL` on either side, doesn't behave as you expected. For example, if you replace `('a' COLLATE 'binary')` with `1`, on MySQL 8.0:
```
mysql> DELETE FROM t0 WHERE t0.c0 OR 1;
Query OK, 1 row affected (0.01 sec)
```
Meaning `NULL OR 1` evaluates to `1`, not `NULL`. So your basic assumption about this case is wrong.

2. The real problem in this case is `('a' COLLATE 'binary')` evaluates to `1`, through some unexpected implicit cast, on TiDB. Meanwhile MySQL 8.0 will report:
```
mysql> DELETE FROM t0 WHERE t0.c0 OR ('a' COLLATE 'utf8mb4_bin');
ERROR 1292 (22007): Truncated incorrect DOUBLE value: 'a'
```
(I had to replace `binary` with `utf8mb4_bin` as MySQL 8.0 doesn't recognize `binary` as a valid collate for `utf8mb4` charset, but it's irrelevant with this issue).
Apparently MySQL 8.0 prohibits the implicit cast from a string literal `'a'` to a double, but TiDB allows it.

So I think we should target point 2 above. And the priority might be lowered to moderate or minor.

@sayJason PTAL.

**Comment by XuHuaiyu** [comment] 2022-04-26 03:00
I run the case using the following commits, it seems this bug has be fixed already.
release-5.4 11dbb917d1099bd034679d2f9f25ab1b0f0dda9d
release-6.0 36a9810441ca0e496cbd22064af274b3be771081
master 79a66d7bdbdd746903596ea6762de07e6e67a6a2

**Comment by sayJason** [comment] 2022-04-26 09:41
> There are several caveats in this issue:
> 
> 1. The `OR` expression, along with `NULL` on either side, doesn't behave as you expected. For example, if you replace `('a' COLLATE 'binary')` with `1`, on MySQL 8.0:
> 
> ```
> mysql> DELETE FROM t0 WHERE t0.c0 OR 1;
> Query OK, 1 row affected (0.01 sec)
> ```
> 
> Meaning `NULL OR 1` evaluates to `1`, not `NULL`. So your basic assumption about this case is wrong.
> 
> 2. The real problem in this case is `('a' COLLATE 'binary')` evaluates to `1`, through some unexpected implicit cast, on TiDB. Meanwhile MySQL 8.0 will report:
> 
> ```
> mysql> DELETE FROM t0 WHERE t0.c0 OR ('a' COLLATE 'utf8mb4_bin');
> ERROR 1292 (22007): Truncated incorrect DOUBLE value: 'a'
> ```
> 
> (I had to replace `binary` with `utf8mb4_bin` as MySQL 8.0 doesn't recognize `binary` as a valid collate for `utf8mb4` charset, but it's irrelevant with this issue). Apparently MySQL 8.0 prohibits the implicit cast from a string literal `'a'` to a double, but TiDB allows it.
> 
> So I think we should target point 2 above.
> 
> @sayJason PTAL.

Thanks for your reply. The first point is correct that NULL OR 1 should be 1 not NULL. The second point should be focused. I've made a mistake.

**Comment by zanmato1984** [comment] 2022-05-05 04:17
Found something worth noting, in TiDB:
```
mysql> DELETE FROM t0 WHERE t0.c0 OR (_binary'a' collate binary);
Query OK, 1 row affected (0.00 sec)

mysql> DELETE FROM t0 WHERE t0.c0 OR ('a' collate utf8mb4_bin);
ERROR 1292 (22007): Truncated incorrect INTEGER value: 'a'
```

Seems like a collation issue. Changing labels.

**Comment by Defined2014** [comment] 2022-06-14 07:51
I can't reproduce it in release-5.4, release-6.0 and master branch. Also can't reproduce the not truncated problem with binary collation. So close this issue, if you still have problems, feel free to reopen it and leave comments here.

**Closed by Defined2014** 2022-06-14 07:51 UTC
Labels: type/bug, sig/sql-infra, severity/major, may-affects-4.0, may-affects-5.1, may-affects-5.2, may-affects-5.3, may-affects-5.4, may-affects-5.0, affects-6.0, affects-6.1

**Comment by sayJason** [comment] 2022-08-03 15:04
I reproduce this case with following commands
```cmd
tiup playground 5.4.0
mysql --comments --host 127.0.0.1 --port 4000 -u root -p
```
And entering the following SQL statements
```cmd
DROP TABLE IF EXISTS t0;
CREATE TABLE IF NOT EXISTS t0(c0 NUMERIC);
INSERT INTO t0 VALUES(NULL);
DELETE FROM t0 WHERE t0.c0 OR ('a' COLLATE 'binary');
```

TiUP version
```
1.8.2 tiup
Go Version: go1.17.5
Git Ref: v1.8.2
GitHash: a2912cf0470d651ce724e6c4e79871ec772abe38
```
TiDB version
```
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| tidb_version()

                                                                       |
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Release Version: v5.4.0
Edition: Community
Git Commit Hash: 55f3b24c1c9f506bd652ef1d162283541e428872
Git Branch: heads/refs/tags/v5.4.0
UTC Build Time: 2022-01-25 08:39:26
GoVersion: go1.16.4
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false |
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)
```

**Comment by sayJason** [comment] 2022-08-03 15:17
I try the same case as follows in the latest version with `tiup playground`
```cmd 
DROP TABLE IF EXISTS t0;
CREATE TABLE IF NOT EXISTS t0(c0 NUMERIC);
INSERT INTO t0 VALUES(NULL);
DELETE FROM t0 WHERE t0.c0 OR ('a' COLLATE 'binary');
```
An error is generated as follows
```cmd
mysql> DELETE FROM t0 WHERE t0.c0 OR ('a' COLLATE 'binary');
ERROR 1253 (42000): COLLATION 'binary' is not valid for CHARACTER SET 'utf8mb4'
```
Then I check the default collation for CHARACTER SET 'utf8mb4'.
The following case seems to become correct.
```cmd 
DROP TABLE IF EXISTS t0;
CREATE TABLE IF NOT EXISTS t0(c0 NUMERIC);
INSERT INTO t0 VALUES(NULL);
DELETE FROM t0 WHERE t0.c0 OR ('a' COLLATE 'utf8mb4_bin'); -- ERROR 1292 (22007): Truncated incorrect INTEGER value: 'a'
```
It seems this problem has been fixed.

TiDB version
```cmd
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| tidb_version()

                                                                       |
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Release Version: v6.1.0
Edition: Community
Git Commit Hash: 1a89decdb192cbdce6a7b0020d71128bc964d30f
Git Branch: heads/refs/tags/v6.1.0
UTC Build Time: 2022-06-05 05:15:11
GoVersion: go1.18.2
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false |
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)
```

**Comment by sayJason** [comment] 2022-08-03 15:21
I also try this in the latest release version https://github.com/pingcap/tidb/releases/tag/v5.4.2 with the same case 
```cmd
DROP TABLE IF EXISTS t0;
CREATE TABLE IF NOT EXISTS t0(c0 NUMERIC);
INSERT INTO t0 VALUES(NULL);
DELETE FROM t0 WHERE t0.c0 OR ('a' COLLATE 'binary');
```
It seems to be fixed.
```cmd
mysql> DELETE FROM t0 WHERE t0.c0 OR ('a' COLLATE 'binary');
ERROR 1292 (22007): Truncated incorrect DOUBLE value: 'a'
```

TiDB version
```cmd
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| tidb_version()

   |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Release Version:
Edition: Community
Git Commit Hash:
Git Branch:
UTC Build Time: 2022-08-03 15:07:21
GoVersion: go1.18.3
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)
```

**Comment by sayJason** [comment] 2022-08-12 07:09
@Defined2014 PTAL

**Comment by Defined2014** [comment] 2022-08-12 07:18
> @Defined2014 PTAL

Sorry, I don't get your point about the problem. If you are using v5.4.0, I think you can update to v5.4.2.

**Comment by sayJason** [comment] 2022-08-12 08:11
> I can't reproduce it in release-5.4, release-6.0 and master branch. Also can't reproduce the not truncated problem with binary collation. So close this issue, if you still have problems, feel free to reopen it and leave comments here.

I try to reply your comment [on 14 Jun](https://github.com/pingcap/tidb/issues/32802#issuecomment-1154840544).
I already update to v5.4.2. But I do find this bug in v5.4.0 (`tiup playground 5.4.0`). Now, it disappears in v5.4.2.

**Comment by Defined2014** [comment] 2022-08-12 08:46
@sayJason I think the root case is we default enable the `new_collations_enabled_on_first_bootstrap` on v6.0.0. When  `new_collations_enabled_on_first_bootstrap` disabled, TiDB will not consider anything with collation.

You can see the docs
https://docs.pingcap.com/tidb/stable/tidb-configuration-file#new_collations_enabled_on_first_bootstrap

**Comment by sayJason** [comment] 2022-08-12 08:57
Thanks, I get your point. The problem should not exist on v6.0.0, and it does disappear.
