### ISSUE TITLE
baseBuiltinFunc.evalInt() should never be called, please contact the TiDB team for help

### ISSUE THREAD

**Issue by breeswish** [pingcap/tidb#12203] opened 2019-09-16 09:45 UTC
## Bug Report

```
mysql> SELECT DISTINCT MIN( ( ( NULLIF( `col_set_key`, ( FROM_UNIXTIME( NULL, ( SESSION_USER() ) ) ) ) ) - '2010-08-13 11:06:31.010738' ) / 0 ) AS field1, MIN( FORMAT( ( HEX( ( ! ( CONVERT( ( SCHEMA() ) USING latin1 ) ) ) ) ), 'gembhbqxxilftdzowxktyudkupgsecwhcdhjlcvspdwvsstqpoateuoxmwsmteettbsntuafuncaoflbhtuuimccwurklwksgksoorfghsiheywcfplhfylrsmzqufmvdmckdzkpmusyduyuzonwgoafuxcagbpqscnhkzpngzbhxssjesip' ) ) AS field2 FROM `table10_int_autoinc` GROUP BY NULL / `col_decimal` HAVING RADIANS( 3415417367407099904 );
--------------
SELECT DISTINCT MIN( ( ( NULLIF( `col_set_key`, ( FROM_UNIXTIME( NULL, ( SESSION_USER() ) ) ) ) ) - '2010-08-13 11:06:31.010738' ) / 0 ) AS field1, MIN( FORMAT( ( HEX( ( ! ( CONVERT( ( SCHEMA() ) USING latin1 ) ) ) ) ), 'gembhbqxxilftdzowxktyudkupgsecwhcdhjlcvspdwvsstqpoateuoxmwsmteettbsntuafuncaoflbhtuuimccwurklwksgksoorfghsiheywcfplhfylrsmzqufmvdmckdzkpmusyduyuzonwgoafuxcagbpqscnhkzpngzbhxssjesip' ) ) AS field2 FROM `table10_int_autoinc` GROUP BY NULL / `col_decimal` HAVING RADIANS( 3415417367407099904 )
--------------

ERROR 1105 (HY000): baseBuiltinFunc.evalInt() should never be called, please contact the TiDB team for help
```

**Comment by breeswish** [comment] 2019-09-27 09:56
See https://github.com/pingcap/tidb/issues/12200 for schema and data.

**Comment by qw4990** [comment] 2020-08-24 08:42
Same with https://github.com/pingcap/tidb/issues/12202, I will fix it soon.

**Comment by jebter** [comment] 2020-11-09 10:17
Unsupported behavior, not a bug

**Comment by breeswish** [comment] 2020-11-09 11:41
@jebter Why is it not a bug?

**Comment by wshwsh12** [comment] 2020-11-10 02:27
Fixed by https://github.com/pingcap/tidb/pull/14571

**Closed** 2020-11-10 03:27 UTC
Labels: Priority/P3, component/expression

**Comment by jebter** [comment] 2020-11-10 06:44
After discussion, it is still defined as a bug.
