### ISSUE TITLE
'show create table'  gets snapshot in repeatable read isolation level

### ISSUE THREAD

**Issue by wengsy150943** [pingcap/tidb#43730] opened 2023-05-11 12:38 UTC
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

initial schema:

```
create table table0 (a int);
```

create 2 sessions and execute queries below:

```
session1 > begin;
session1 > show create table table0;
session2 > insert into table0 values(1);
session1 > select * from table0;
```

### 2. What did you expect to see? (Required)

The last select return:
```
+------+
| a    |
+------+
|    1 |
+------+
1 row in set (0.00 sec)
```
as MySQL5.7 acts.

### 3. What did you see instead (Required)

The last select return `Empty set (0.01 sec)`. This means that TiDB gets snapshot when execute `show create table`. It's not compatible with MySQL5.7.

Another evidence is that, when we change the operation session2 executes into a ddl in the case above. For example, change `insert into table0 values(1);` into `alter table table0 add column (c int);`. TiDB will block this ddl, while MySQL will not.

I'm not sure if it's a bug, since the snapshot behavior of TiDB is not completely the same with MySQL. Though it's saied that `show create table` is completely compatible with MySQL.

### 4. What is your TiDB version? (Required)

| Release Version: v6.5.0
Edition: Community
Git Commit Hash: 706c3fa3c526cdba5b3e9f066b1a568fb96c56e3
Git Branch: heads/refs/tags/v6.5.0
UTC Build Time: 2022-12-27 03:50:44
GoVersion: go1.19.3
Race Enabled: false
TiKV Min Version: 6.2.0-alpha
Check Table Before Drop: false
Store: tikv |

**Comment by Defined2014** [comment] 2023-05-12 02:09
I think this is the root case for https://github.com/pingcap/tidb/issues/43650

**Comment by wengsy150943** [comment] 2023-05-12 02:33
> I think this is the root case for #43650

I build another case for #43650, which may help.

```
create table table0 (a int);
alter table table0 add index idx0 (a);
```

```
session1 > begin;
session1 > select * from table0 for update;
session2 > alter table table0 rename index idx0 to idx1; -- blocked
session3 >show create table table0; -- index name is idx1, but rename index is still blocked, as the case in 43650
```

Since `select for update` gets the current snapshot, it seems that any session1 with snapshot can trigger this phenomenon.

**Comment by Defined2014** [comment] 2023-05-12 02:40
> > I think this is the root case for #43650
> 
> I build another case for #43650, which may help.
> 
> ```
> create table table0 (a int);
> alter table table0 add index idx0 (a);
> ```
> 
> ```
> session1 > begin;
> session1 > select * from table0 for update;
> session2 > alter table table0 rename index idx0 to idx1; -- blocked
> session3 >show create table table0; -- index name is idx1, but rename index is still blocked, as the case in 43650
> ```
> 
> Since `select for update` gets the current snapshot, it seems that any session1 with snapshot can trigger this phenomenon.

Yes, this is the expected behavior of metadata locks. https://docs.pingcap.com/tidb/v7.0/metadata-lock

**Comment by wengsy150943** [comment] 2023-05-12 03:09
> Yes, this is the expected behavior of metadata lock. https://docs.pingcap.com/tidb/v7.0/metadata-lock
> 
> Oh, sorry. I miss connect a issue which should be #43652.

Thx for your reply, yet I'm still confused with the correctness of case above.

If block `rename index` is expected, in my opinion,`show create table table0;` should get index name `idx0` in the case above. But it gets `idx1`. Is it also expected?

**Comment by Defined2014** [comment] 2023-05-12 03:30
> > Yes, this is the expected behavior of metadata lock. https://docs.pingcap.com/tidb/v7.0/metadata-lock
> > Oh, sorry. I miss connect a issue which should be #43652.
> 
> Thx for your reply, yet I'm still confused with the correctness of case above.
> 
> If block `rename index` is expected, in my opinion,`show create table table0;` should get index name `idx0` in the case above. But it gets `idx1`. Is it also expected?

You can see that the state of ddl operation is done which means that the ddl has completed, but not all tidb-server have been synced yet (blocked by MDL).
<img width="1411" alt="image" src="https://github.com/pingcap/tidb/assets/17435596/fc66ce36-a935-42b3-8ad2-3ce51af1a8cb">

So if you create a new session with a bigger start_ts, it could see `idx1` is expected.

**Comment by wengsy150943** [comment] 2023-05-12 03:43
> > > Yes, this is the expected behavior of metadata lock. https://docs.pingcap.com/tidb/v7.0/metadata-lock
> > > Oh, sorry. I miss connect a issue which should be #43652.
> > 
> > 
> > Thx for your reply, yet I'm still confused with the correctness of case above.
> > If block `rename index` is expected, in my opinion,`show create table table0;` should get index name `idx0` in the case above. But it gets `idx1`. Is it also expected?
> 
> You can see that the state of ddl operation is done which means that the ddl has completed, but not all tidb-server have been synced yet (blocked by MDL). <img alt="image" width="1411" src="https://user-images.githubusercontent.com/17435596/237861682-fc66ce36-a935-42b3-8ad2-3ce51af1a8cb.png">
> 
> So if you create a new session with a bigger start_ts, it could see `idx1` is expected. But you should get `idx0` in old session(session1).

Got it, but this may cause some display mistakes, because ddl is shown as blocked in CLI while it's done in fact.

When I use `ctrl+c` to terminate ddl, CLI returns ` -- query aborted`. But `admin show ddl jobs;` shows that this ddl is done and it will not be aborted.

<img width="411" alt="image" src="https://github.com/pingcap/tidb/assets/43516416/da33c210-92b4-4ada-b614-b7d27b188784">

**Comment by Defined2014** [comment] 2023-05-12 03:47
Yes, in TiDB you should use [`admin cancel ddl`](https://docs.pingcap.com/tidb/stable/sql-statement-admin-cancel-ddl) query to do this. Because not all ddl job could be canceled.

**Comment by wengsy150943** [comment] 2023-05-12 04:05
> Yes, in TiDB you should use [`admin cancel ddl`](https://docs.pingcap.com/tidb/stable/sql-statement-admin-cancel-ddl) query to do this. Because not all ddl job could be canceled in any state.

Thx for your answer. So the ddl behavior in TiDB is similar as my description below?

When a new session begins a ddl with a old session has an uncommitted txn, it will execute this ddl but not block(this is not so consist with doc). Then it will not sync it to the old session until old session commits. So it performs as blocked while it's done in fact.

Therefore, even I use `admin cancel ddl jobs` to kill ddl, it cannot be cancelled, too. BTW, the failure info returned by `admin cancel ddl jobs` is not consist with doc.

<img width="617" alt="image" src="https://github.com/pingcap/tidb/assets/43516416/0311d5c5-8cd7-4a48-b947-52a28402fdf2">

**Comment by Defined2014** [comment] 2023-05-12 05:29
> > Yes, in TiDB you should use [`admin cancel ddl`](https://docs.pingcap.com/tidb/stable/sql-statement-admin-cancel-ddl) query to do this. Because not all ddl job could be canceled in any state.
> 
> Thx for your answer. So the ddl behavior in TiDB is similar as my description below?
> 
> When a new session begins a ddl with a old session has an uncommitted txn, it will execute this ddl but not block(this is not so consist with doc). Then it will not sync it to the old session until old session commits. So it performs as blocked while it's done in fact.
> 
> Therefore, even I use `admin cancel ddl jobs` to kill ddl, it cannot be cancelled, too. BTW, the failure info returned by `admin cancel ddl jobs` is not consist with doc.
> 
> <img alt="image" width="617" src="https://user-images.githubusercontent.com/43516416/237866794-0311d5c5-8cd7-4a48-b947-52a28402fdf2.png">

It depends on which ddl operations you use. The rename index has only one state, so it will block on "done -> sync". It won't have this problem if you do other ddl jobs like `add index` etc.

**Comment by wengsy150943** [comment] 2023-05-12 05:34
> > > Yes, in TiDB you should use [`admin cancel ddl`](https://docs.pingcap.com/tidb/stable/sql-statement-admin-cancel-ddl) query to do this. Because not all ddl job could be canceled in any state.
> > 
> > 
> > Thx for your answer. So the ddl behavior in TiDB is similar as my description below?
> > When a new session begins a ddl with a old session has an uncommitted txn, it will execute this ddl but not block(this is not so consist with doc). Then it will not sync it to the old session until old session commits. So it performs as blocked while it's done in fact.
> > Therefore, even I use `admin cancel ddl jobs` to kill ddl, it cannot be cancelled, too. BTW, the failure info returned by `admin cancel ddl jobs` is not consist with doc.
> > <img alt="image" width="617" src="https://user-images.githubusercontent.com/43516416/237866794-0311d5c5-8cd7-4a48-b947-52a28402fdf2.png">
> 
> It depends on which ddl operations you use. The rename index has only one state, so it will block on "done -> sync". It won't have this problem if you do other ddl jobs like `add index` etc.

Got it, thx.

**Comment by jebter** [comment] 2024-09-04 02:58
The issue has not been updated for too long, so I will close it，if there are any updates, you can reopen it.

**Closed by jebter** 2024-09-04 02:58 UTC
Labels: type/bug, duplicate, sig/transaction
