### ISSUE TITLE
goleak TestDeferConstraintCheckForDelete

### ISSUE THREAD

**Issue by hawkingrei** [pingcap/tidb#36880] opened 2022-08-04 03:35 UTC
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
[2022-08-04T03:33:35.436Z] --- PASS: TestDeferConstraintCheckForDelete (2.43s)

[2022-08-04T03:33:35.436Z] PASS

[2022-08-04T03:33:35.436Z] coverage: 23.8% of statements

[2022-08-04T03:33:35.436Z] goleak: Errors on successful test run: found unexpected goroutines:

[2022-08-04T03:33:35.436Z] [Goroutine 21702 in state semacquire, 1 minutes, with sync.runtime_Semacquire on top of the stack:

[2022-08-04T03:33:35.436Z] goroutine 21702 [semacquire, 1 minutes]:

[2022-08-04T03:33:35.436Z] sync.runtime_Semacquire(0xc00492f750?)

[2022-08-04T03:33:35.436Z] 	GOROOT/src/runtime/sema.go:56 +0x25

[2022-08-04T03:33:35.436Z] sync.(*WaitGroup).Wait(0xc003d87020?)

[2022-08-04T03:33:35.436Z] 	GOROOT/src/sync/waitgroup.go:136 +0x52

[2022-08-04T03:33:35.436Z] github.com/pingcap/tidb/store/copr.(*copIteratorTaskSender).run(0xc003db8040)

[2022-08-04T03:33:35.436Z] 	store/copr/coprocessor.go:516 +0xec

[2022-08-04T03:33:35.436Z] created by github.com/pingcap/tidb/store/copr.(*copIterator).open

[2022-08-04T03:33:35.436Z] 	store/copr/coprocessor.go:493 +0x4ce

[2022-08-04T03:33:35.436Z] 

[2022-08-04T03:33:35.436Z]  Goroutine 21701 in state select, 1 minutes, with github.com/pingcap/tidb/store/copr.(*copIteratorWorker).sendToRespCh on top of the stack:

[2022-08-04T03:33:35.436Z] goroutine 21701 [select, 1 minutes]:

[2022-08-04T03:33:35.436Z] github.com/pingcap/tidb/store/copr.(*copIteratorWorker).sendToRespCh(0xc003d91d60?, 0xc00397ecd0?, 0xc004162c00?, 0xd0?)

[2022-08-04T03:33:35.436Z] 	store/copr/coprocessor.go:581 +0x1b5

[2022-08-04T03:33:35.436Z] github.com/pingcap/tidb/store/copr.(*copIteratorWorker).handleCopResponse(0xc003d91d60, 0xc0038bfe08, 0xc003db8000?, 0xc00397ecd0, {0xc003957200, 0x179, 0x179}, 0x0, 0xc003874780, 0xc004162c00, ...)

[2022-08-04T03:33:35.436Z] 	store/copr/coprocessor.go:1038 +0x16a5

[2022-08-04T03:33:35.436Z] github.com/pingcap/tidb/store/copr.(*copIteratorWorker).handleTaskOnce(0xc003d91d60, 0xc0038bfe08, 0xc003874780, 0xc004162c00?)

[2022-08-04T03:33:35.436Z] 	store/copr/coprocessor.go:820 +0x11af

[2022-08-04T03:33:35.436Z] github.com/pingcap/tidb/store/copr.(*copIteratorWorker).handleTask(0xc003d91d60, {0x4b44438, 0xc003d89a10}, 0xc00670cf50?, 0xc004162c00)

[2022-08-04T03:33:35.436Z] 	store/copr/coprocessor.go:702 +0x1b8

[2022-08-04T03:33:35.436Z] github.com/pingcap/tidb/store/copr.(*copIteratorWorker).run(0xc003d91d60, {0x4b44438, 0xc003d89a10})

[2022-08-04T03:33:35.436Z] 	store/copr/coprocessor.go:444 +0x105

[2022-08-04T03:33:35.436Z] created by github.com/pingcap/tidb/store/copr.(*copIterator).open

[2022-08-04T03:33:35.436Z] 	store/copr/coprocessor.go:476 +0x9f

[2022-08-04T03:33:35.436Z] ]

[2022-08-04T03:33:35.436Z] --

[2022-08-04T03:33:35.436Z] Coverage runner: Not collecting coverage for failed test.

[2022-08-04T03:33:35.436Z] The following commands failed with status 1

```

**Comment by hawkingrei** [comment] 2022-08-04 03:36
https://ci.pingcap.net/blue/organizations/jenkins/tidb_ghpr_unit_test/detail/tidb_ghpr_unit_test/63744/pipeline

**Comment by tiancaiamao** [comment] 2022-08-05 02:00
I can't reproduce it on my local PC.

**Comment by jebter** [comment] 2024-09-03 09:47
Please try the latest version. I will close it,if there are any updates, you can reopen it.

**Closed by jebter** 2024-09-03 09:47 UTC
Labels: type/bug, component/test, sig/transaction, severity/major, may-affects-4.0, may-affects-5.1, may-affects-5.2, may-affects-5.3, may-affects-5.4, may-affects-5.0, may-affects-6.0, may-affects-6.1, may-affects-6.2, affects-6.3, affects-6.4, affects-6.5, affects-6.6, affects-7.0, affects-7.1, affects-7.5, affects-8.1
