### ISSUE TITLE
ERROR 1105 (HY000): Can't find column Column#8 in schema Column: [test.tb1.tb1_f2,test.tb2.tb2_f2] Unique key: []

### ISSUE THREAD

**Issue by Flynn-Zh** [pingcap/tidb#39833] opened 2022-12-12 08:17 UTC
### 1. Minimal reproduce step (Required)

create database test;
use test;
drop table if exists tb1;
CREATE TABLE tb1 (
  tb1_f1 char(40) NOT NULL,
  tb1_f2 char(150),
  tb1_tb2_f1 char(40) NOT NULL,
  PRIMARY KEY (tb1_f1)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

drop table if exists tb2;
CREATE TABLE tb2 (
  tb2_f1 char(40) NOT NULL,
  tb2_f2 char(128) NOT NULL,
  PRIMARY KEY (tb2_f1)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

select ifnull(tb1.tb1_f2, tb2.tb2_f2) as new_f2 from tb1 left join tb2 on tb1.tb1_f1=tb2.tb2_f1 order by upper(convert(new_f2 using gbk)) collate gbk_bin limit 0,100;

### 2. What did you expect to see? (Required)
ok
### 3. What did you see instead (Required)
ERROR 1105 (HY000): Can't find column Column#8 in schema Column: [test.tb1.tb1_f2,test.tb2.tb2_f2] Unique key: []
### 4. What is your TiDB version? (Required)
Release Version: v6.1.2

**Comment by seiya-annie** [comment] 2022-12-13 02:05
in mysql 8.0.23
```sql
mysql> use test;
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed
mysql> drop table if exists tb1;
Query OK, 0 rows affected, 1 warning (0.00 sec)

mysql> CREATE TABLE tb1 (
    -> tb1_f1 char(40) NOT NULL,
    -> tb1_f2 char(150),
    -> tb1_tb2_f1 char(40) NOT NULL,
    -> PRIMARY KEY (tb1_f1)
    -> ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
Query OK, 0 rows affected (0.01 sec)

mysql> drop table if exists tb2;
Query OK, 0 rows affected, 1 warning (0.00 sec)

mysql> CREATE TABLE tb2 (
    -> tb2_f1 char(40) NOT NULL,
    -> tb2_f2 char(128) NOT NULL,
    -> PRIMARY KEY (tb2_f1)
    -> ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
Query OK, 0 rows affected (0.01 sec)

mysql> select ifnull(tb1.tb1_f2, tb2.tb2_f2) as new_f2 from tb1 left join tb2 on tb1.tb1_f1=tb2.tb2_f1 order by upper(convert(new_f2 using gbk)) collate gbk_bin limit 0,100;
Empty set (0.00 sec)

MySQL> 
```

**Comment by fixdb** [comment] 2022-12-13 07:23
Minimal repro:
```sql
explain select ifnull(tb1.tb1_f2, tb2.tb2_f2) as new_f2 
  from tb1 join tb2 on tb1.tb1_f1=tb2.tb2_f1 
  order by upper(convert(new_f2 using gbk))
  limit 1;
ERROR 1105 (HY000): Can't find column Column#6 in schema Column: [test.tb1.tb1_f2,test.tb2.tb2_f2] Unique key: []
```
Looks like bug happens in resolver. @AilinKid

**Comment by qw4990** [comment] 2024-04-28 06:37
Can't reproduce it again, it might have been fixed by some PR:
```
mysql> select ifnull(tb1.tb1_f2, tb2.tb2_f2) as new_f2 from tb1 left join tb2 on tb1.tb1_f1=tb2.tb2_f1 order by upper(convert(new_f2 using gbk)) collate gbk_bin limit 0,100;
Empty set (0.01 sec)

mysql> 
mysql> 
mysql> 
mysql> 
mysql> explain select ifnull(tb1.tb1_f2, tb2.tb2_f2) as new_f2 
    ->   from tb1 join tb2 on tb1.tb1_f1=tb2.tb2_f1 
    ->   order by upper(convert(new_f2 using gbk))
    ->   limit 1;
+-------------------------------------+----------+-----------+---------------+-----------------------------------------------------------------------------------------------------------+
| id                                  | estRows  | task      | access object | operator info                                                                                             |
+-------------------------------------+----------+-----------+---------------+-----------------------------------------------------------------------------------------------------------+
| Projection_10                       | 1.00     | root      |               | ifnull(test.tb1.tb1_f2, test.tb2.tb2_f2)->Column#6                                                        |
| └─Projection_44                     | 1.00     | root      |               | test.tb1.tb1_f2, test.tb2.tb2_f2                                                                          |
|   └─TopN_13                         | 1.00     | root      |               | Column#7, offset:0, count:1                                                                               |
|     └─Projection_45                 | 12500.00 | root      |               | test.tb1.tb1_f2, test.tb2.tb2_f2, upper(convert(ifnull(test.tb1.tb1_f2, test.tb2.tb2_f2), gbk))->Column#7 |
|       └─MergeJoin_15                | 12500.00 | root      |               | inner join, left key:test.tb1.tb1_f1, right key:test.tb2.tb2_f1                                           |
|         ├─TableReader_39(Build)     | 10000.00 | root      |               | data:TableFullScan_38                                                                                     |
|         │ └─TableFullScan_38        | 10000.00 | cop[tikv] | table:tb2     | keep order:true, stats:pseudo                                                                             |
|         └─TableReader_37(Probe)     | 10000.00 | root      |               | data:TableFullScan_36                                                                                     |
|           └─TableFullScan_36        | 10000.00 | cop[tikv] | table:tb1     | keep order:true, stats:pseudo                                                                             |
+-------------------------------------+----------+-----------+---------------+-----------------------------------------------------------------------------------------------------------+
9 rows in set (0.01 sec)
```

**Closed by qw4990** 2024-04-28 06:37 UTC
Labels: type/bug, sig/planner, severity/major, may-affects-4.0, may-affects-5.1, may-affects-5.2, may-affects-5.3, may-affects-5.4, may-affects-5.0, affects-6.0, affects-6.1, affects-6.2, affects-6.3, affects-6.4, affects-6.6, affects-7.0, affects-7.1, affects-7.5, affects-8.1
