### ISSUE TITLE
the execution info is not right in explain analyze result

### ISSUE THREAD

**Issue by crazycs520** [pingcap/tidb#18582] opened 2020-07-15 07:52 UTC
## Bug Report

Please answer these questions before submitting your issue. Thanks!

The `time` of cop task in `execution info` shouldn't be `0s`. 

### 2. What did you expect to see? (Required)

```sql
infinity_boe> explain analyze select count(*) from if_user_backpackdata where _tidb_rowid<1000000000;
+-------------------------+----------+---------+-----------+----------------------------+---------------------------------------------------------------------------+-------------------------------------------+-----------+------+
| id                      | estRows  | actRows | task      | access object              | execution info                                                            | operator info                             | memory    | disk |
+-------------------------+----------+---------+-----------+----------------------------+---------------------------------------------------------------------------+-------------------------------------------+-----------+------+
| StreamAgg_17            | 1.00     | 1       | root      |                            | time:2.534501ms, loops:2                                                  | funcs:count(Column#12)->Column#10         | 372 Bytes | N/A  |
| └─TableReader_18        | 1.00     | 1       | root      |                            | time:2.529481ms, loops:2, rpc num: 1, rpc time:2.473521ms, proc keys:5099 | data:StreamAgg_9                          | 201 Bytes | N/A  |
|   └─StreamAgg_9         | 1.00     | 1       | cop[tikv] |                            | time:2ms, loops:5                                                         | funcs:count(1)->Column#12                 | N/A       | N/A  |
|     └─TableRangeScan_16 | 18859.33 | 4833    | cop[tikv] | table:if_user_backpackdata | time:2ms, loops:5                                                         | range:[-inf,1000000000), keep order:false | N/A       | N/A  |
+-------------------------+----------+---------+-----------+----------------------------+---------------------------------------------------------------------------+-------------------------------------------+-----------+------+
4 rows in set
```

### 3. What did you see instead (Required)

```sql
infinity_boe> explain analyze select count(*) from if_user_backpackdata where _tidb_rowid<1000000;
+-------------------------+----------+---------+-----------+----------------------------+----------------------------------------------------------------------+----------------------------------------+-----------+------+
| id                      | estRows  | actRows | task      | access object              | execution info                                                       | operator info                          | memory    | disk |
+-------------------------+----------+---------+-----------+----------------------------+----------------------------------------------------------------------+----------------------------------------+-----------+------+
| StreamAgg_17            | 1.00     | 1       | root      |                            | time:501.141µs, loops:2                                              | funcs:count(Column#12)->Column#10      | 372 Bytes | N/A  |
| └─TableReader_18        | 1.00     | 1       | root      |                            | time:496.721µs, loops:2, rpc num: 1, rpc time:435.461µs, proc keys:0 | data:StreamAgg_9                       | 189 Bytes | N/A  |
|   └─StreamAgg_9         | 1.00     | 1       | cop[tikv] |                            | time:0s, loops:1                                                     | funcs:count(1)->Column#12              | N/A       | N/A  |
|     └─TableRangeScan_16 | 18859.33 | 0       | cop[tikv] | table:if_user_backpackdata | time:0s, loops:1                                                     | range:[-inf,1000000), keep order:false | N/A       | N/A  |
+-------------------------+----------+---------+-----------+----------------------------+----------------------------------------------------------------------+----------------------------------------+-----------+------+
4 rows in set
```

### 4. Affected version (Required)

```sql
infinity_boe> select * from information_schema.cluster_info;
+------+-----------------+-----------------+--------------+------------------------------------------+---------------------------+----------------+
| TYPE | INSTANCE        | STATUS_ADDRESS  | VERSION      | GIT_HASH                                 | START_TIME                | UPTIME         |
+------+-----------------+-----------------+--------------+------------------------------------------+---------------------------+----------------+
| tidb | 0.0.0.0:4000    | 0.0.0.0:10080   | 4.0.0-beta.2 | 8a6554a21f8f770612b148dcf69ca2b875ef3eaa | 2020-07-15T15:47:00+08:00 | 2m12.628476s   |
| pd   | 127.0.0.1:2379  | 127.0.0.1:2379  | 4.1.0-alpha  | 56d4c3d2237f5bf6fb11a794731ed1d95c8020c2 | 2020-07-15T11:43:30+08:00 | 4h5m42.628479s |
| tikv | 127.0.0.1:20160 | 127.0.0.1:20180 | 4.1.0-alpha  | 8b1fc4fc67f6d74a46a86d731eb5c152cbf0dfa8 | 2020-07-15T15:46:00+08:00 | 3m12.62848s    |
+------+-----------------+-----------------+--------------+------------------------------------------+---------------------------+----------------+
```

**Comment by wjhuang2016** [comment] 2020-11-24 06:20
Close this issue because it can not reproduce.

**Closed** 2020-11-24 06:20 UTC
Labels: component/infoschema, severity/moderate, status/can't-reproduce, type/bug
