### ISSUE TITLE
During S3 backup, errors may occur if there is "/" at the end of the endpoint

### ISSUE THREAD

**Issue by tongtongyin** [pingcap/tidb#30128] opened 2021-11-24 11:12 UTC
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

<img width="2545" alt="1" src="https://user-images.githubusercontent.com/37565148/143226293-1d8c9b92-3829-48b1-ad2a-79d375e27c68.png">

![2](https://user-images.githubusercontent.com/37565148/143226449-149338ee-13bc-454a-9790-49c21f61cb3d.png)

when S3 backup or restore, If "/" is added last in the endpoint, an error may occur

2. What did you expect to see?

Whether "/" is added last, the backup can be successful

3. What did you see instead?

4. What version of BR and TiDB/TiKV/PD are you using?

br -4.0.11
br -5
The above problem occurs only when there is data in instance. Therefore, when br version is 4.0.11, this problem will not occur when backing up empty instances, because the system library will not be backed up; However, when the br version is 5, even for empty instances, Br the system library will be backed up during backup.

5. Operation logs
   - Please upload `br.log` for BR if possible
   - Please upload `tidb-lightning.log` for TiDB-Lightning if possible
   - Please upload `tikv-importer.log` from TiKV-Importer if possible
   - Other interesting logs

6. Configuration of the cluster and the task
   - `tidb-lightning.toml` for TiDB-Lightning if possible
   - `tikv-importer.toml` for TiKV-Importer if possible
   - `topology.yml` if deployed by TiUP

7. Screenshot/exported-PDF of Grafana dashboard or metrics' graph in Prometheus if possible

**Comment by kennytm** [comment] 2021-11-30 07:51
duplicate of #30104

**Closed by kennytm** 2021-11-30 07:51 UTC
Labels: type/bug, severity/major, component/br
