### ISSUE TITLE
lightning oom when import 600G data 

### ISSUE THREAD

**Issue by seiya-annie** [pingcap/tidb#43808] opened 2023-05-15 06:11 UTC
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

1. import 600G csv data with local backend
2. table schema
----------------------------------------------------------------+
| user_data1 | CREATE TABLE `user_data1` (
  `uid` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `data` mediumblob NOT NULL,
  `update_data` blob NOT NULL,
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` datetime DEFAULT NULL,
  PRIMARY KEY (`uid`) /*T![clustered_index] CLUSTERED */,
  KEY `k_1` (`update_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin AUTO_INCREMENT=5850196 |

### 2. What did you expect to see? (Required)
import successfully
### 3. What did you see instead (Required)
![20230515-141045](https://github.com/pingcap/tidb/assets/53471087/0c79d269-33d4-4581-aa1a-7c4bb8533e99)

### 4. What is your TiDB version? (Required)
master

**Comment by seiya-annie** [comment] 2023-05-15 06:12
[lightning.log.2023-05-15T03.40.00Z.gz](https://github.com/pingcap/tidb/files/11474617/lightning.log.2023-05-15T03.40.00Z.gz)

**Comment by D3Hunter** [comment] 2023-05-15 08:55
lightning version is not master

[2023/05/15 03:40:00.111 +00:00] [INFO] [info.go:49] ["Welcome to TiDB-Lightning"] [release-version=v7.0.0] [git-hash=428a3da6af495bcc87ec2635fe7f8f909290449d] [git-branch=heads/refs/tags/v7.0.0] [go-version=go1.20.3] [utc-build-time="2023-05-08 08:16:07"] [race-enabled=false]


this might be a duplicate of https://github.com/pingcap/tidb/issues/43728

**Closed** 2023-12-22 06:41 UTC
Labels: type/bug, severity/major, component/lightning, may-affects-5.1, may-affects-5.2, may-affects-5.3, may-affects-5.4, may-affects-6.1, may-affects-6.5, may-affects-7.1, affects-7.5
