### ISSUE TITLE
get error while deduplicate the result of a left join

### ISSUE THREAD

**Issue by javajeans** [pingcap/tidb#8824] opened 2018-12-26 02:23 UTC
## Bug Report

Please answer these questions before submitting your issue. Thanks!
我有一张用户表，一张部门表，一张用户部门关联表；
sql如下：
```
SELECT DISTINCT u.id,
  u.username,
	u.realname,
	u.telephone,
	u.email,
	u.status 
FROM
	sys_users u
	LEFT JOIN sys_users_departments ud ON ud.user_id = u.id 
WHERE
	1 = 1 
	AND u.is_del = 0 
	AND u.STATUS = 1 
	AND ud.user_id IS NULL
```
>mysql 上是正常的

如果去掉 AND ud.user_id IS NULL是正常的
```
SELECT DISTINCT u.id,
  u.username,
	u.realname,
	u.telephone,
	u.email,
	u.status 
FROM
	sys_users u
	LEFT JOIN sys_users_departments ud ON ud.user_id = u.id 
WHERE
	1 = 1 
	AND u.is_del = 0 
	AND u.STATUS = 1
````

**Comment by javajeans** [comment] 2018-12-26 02:38
tidb version ：Release Version: v2.1.0-rc.3-353-gef7082d

create sql：
```
CREATE TABLE `sys_users` (
  `id` varchar(32) CHARACTER SET utf8 NOT NULL,
  `code` varchar(20) CHARACTER SET utf8 NOT NULL COMMENT '用户编号',
  `username` varchar(50) CHARACTER SET utf8 DEFAULT NULL COMMENT '用户名',
  `password` varchar(60) NOT NULL DEFAULT '123456' COMMENT '用户密码',
  `realname` varchar(60) CHARACTER SET utf8 DEFAULT NULL COMMENT '用户姓名',
  `telephone` varchar(20) CHARACTER SET utf8 DEFAULT NULL COMMENT '手机号码',
  `email` varchar(50) CHARACTER SET utf8 DEFAULT NULL COMMENT '邮箱',
  `status` int(1) NOT NULL COMMENT '状态,0否1是',
  `gender` int(1) DEFAULT '0' COMMENT '性别，1:男；0:女',
  `type` varchar(20) CHARACTER SET utf8 DEFAULT NULL COMMENT '类型,使用，分隔',
  `origin` int(1) DEFAULT NULL COMMENT '创建来源，0系统；1，微信',
  `avatar` varchar(255) CHARACTER SET utf8 DEFAULT NULL COMMENT '头像',
  `remark` varchar(255) CHARACTER SET utf8 DEFAULT NULL COMMENT '备注',
  `created_time` datetime DEFAULT NULL,
  `created_by` varchar(32) CHARACTER SET utf8 DEFAULT NULL,
  `updated_time` datetime DEFAULT NULL,
  `updated_by` varchar(32) CHARACTER SET utf8 DEFAULT NULL,
  `birthday` varchar(20) DEFAULT NULL,
  `is_del` int(1) NOT NULL DEFAULT '1' COMMENT '删除状态',
  PRIMARY KEY (`id`)
) 

CREATE TABLE `sys_users_departments` (
  `id` varchar(32) NOT NULL,
  `user_id` varchar(32) NOT NULL,
  `department_id` varchar(32) CHARACTER SET utf8mb4 NOT NULL,
  `created_time` datetime DEFAULT NULL,
  `created_by` varchar(32) DEFAULT NULL,
  `updated_time` datetime DEFAULT NULL,
  `updated_by` varchar(32) DEFAULT NULL,
  `is_del` int(1) DEFAULT NULL,
  `remark` varchar(200) DEFAULT NULL,
  PRIMARY KEY (`id`)
)
```

**Comment by zz-jason** [comment] 2018-12-26 02:50
@javajeans Can't reproduce on the latest master and 2.1.2:
```sql
TiDB(root@127.0.0.1:test) > SELECT DISTINCT u.id,   u.username,     u.realname,     u.telephone,     u.email,     u.status  FROM     sys_users u     LEFT JOIN sys_users_departments ud ON ud.user_id = u.id  WHERE     1 = 1      AND u.is_del = 0      AND u.STATUS = 1      AND ud.user_id IS NULL;
Empty set (0.00 sec)
```

```sql
TiDB(root@127.0.0.1:test) > SELECT DISTINCT u.id,   u.username,     u.realname,     u.telephone,     u.email,     u.status  FROM     sys_users u     LEFT JOIN sys_users_departments ud ON ud.user_id = u.id  WHERE     1 = 1      AND u.is_del = 0      AND u.STATUS = 1;
Empty set (0.01 sec)
```

**Comment by wjhuang2016** [comment] 2020-12-01 11:41
Close this issue because it's no active for a long time.

**Closed by wjhuang2016** 2020-12-01 11:41 UTC
Labels: severity/major, sig/execution, status/can't-reproduce, type/bug
