### ISSUE TITLE
Support `SELECT FOR UPDATE SKIP LOCKED`

### ISSUE THREAD

**Issue by you06** [pingcap/tidb#32555] opened 2022-02-23 06:47 UTC
## Feature Request

**Is your feature request related to a problem? Please describe:**

In some scenarios, there are hot modify on a specific row, mostly, `SELECT FOR UPDATE` statement is used to avoid the lost update anomaly. A pessimistic lock will block other conflict transactions from acquiring the pessimistic lock, so it'll lead to a long lock wait and decrease of transaction throughput.

When sharding a hot row into rows, the current TiDB is not able to get an unlocked row.

**Describe the feature you'd like:**

Support `SKIP LOCKED` syntax, which will skip the locked rows and remove them from the resultset. Compare with `NOWAIT`, `SKIP LOCKED` never reports locked errors. See https://dev.mysql.com/doc/refman/8.0/en/innodb-locking-reads.html#innodb-locking-reads-nowait-skip-locked.

**Describe alternatives you've considered:**

No.

**Teachability, Documentation, Adoption, Migration Strategy:**

For scenarios that have high contention row, it's able to shard it into multiple rows and try locking rows without waiting.

e.g., every transaction needs to check if the quota is still enough, the following case avoids the contention in one row.

```
/* init */ drop table if exists quotas;
/* init */ create table quotas(id int primary key, quota int);
/* init */ insert into quotas values(1, 5), (2, 10), (3, 20);

/* t1 */ begin;
/* t2 */ begin;
/* t3 */ begin;

/* t1 */ select * from quotas where quota >= 10 limit 1 for update; -- (2, 10)
/* t2 */ select * from quotas where quota >= 10 limit 1 for update skip locked; - (3, 20)
/* t3 */ select * from quotas where quota >= 10 limit 1 for update skip locked; -- 0 rows

/* t1 */ commit;
/* t2 */ commit;
/* t3 */ commit;
```

**Comment by morgo** [comment] 2022-02-24 01:11
Hi @you06 

This looks to be a duplicate of https://github.com/pingcap/tidb/issues/18207 , so I am going to close this issue for house keeping reasons.

But thank you for mentioning the scenarios. I agree that it's a very useful feature!

**Closed by morgo** 2022-02-24 01:11 UTC
Labels: type/feature-request
