### ISSUE TITLE
v7.1.3, NONCLUSTED INDEX, hash partition table, report "Internal error: UnionExec chunk column count mismatch, req: 3, result: 4"

### ISSUE THREAD

**Issue by seiya-annie** [pingcap/tidb#49509] opened 2023-12-15 10:51 UTC
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
``` sql
# in session-1
set global tidb_enable_clustered_index=off;

# in session-2
create table tbl_30 ( col_221 tinyint unsigned default 41 , primary key idx_72 ( col_221 ) , key idx_73 ( col_221 ) , unique key idx_74 ( col_221 ) ) collate utf8_general_ci partition by hash ( col_221 ) partitions 6;
insert  into tbl_30 set col_221 = 3 on duplicate key update col_221 = 147;
delete tbl_30 from tbl_30 where col_221 is null order by tbl_30.col_221 limit 402;
replace into tbl_30 set col_221 = 50;
replace into tbl_30 set col_221 = 116;
insert  into tbl_30  values ( 49 ) , ( 208 ) on duplicate key update col_221 = 21;
select /*+   */ approx_count_distinct( col_221 ) aggCol from (select   * from tbl_30 where (col_221) = (114) or (col_221) = (114) or (col_221) = (210) order by col_221  ) ordered_tbl group by col_221 order by aggCol for update;
insert  into tbl_30 set col_221 = 242;

select   col_221 from tbl_30 where tbl_30.col_221 not in ( 132 , 178 , 197 ) or not( tbl_30.col_221 not in ( 137 , 139 , 64 , 17 , 199 ) ) order by tbl_30.col_221 limit 144 for update;

```

### 2. What did you expect to see? (Required)
sql execute successfully
### 3. What did you see instead (Required)
```
mysql> select   col_221 from tbl_30 where tbl_30.col_221 not in ( 132 , 178 , 197 ) or not( tbl_30.col_221 not in ( 137 , 139 , 64 , 17 , 199 ) ) order by tbl_30.col_221 limit 144 for update;
ERROR 1105 (HY000): Internal error: UnionExec chunk column count mismatch, req: 3, result: 4
mysql> 

```
### 4. What is your TiDB version? (Required)

7.1.3

**Comment by XuHuaiyu** [comment] 2023-12-15 12:51
This issue can only be reproduced when `@@global.tidb_enable_clustered_index` is OFF;

**Comment by mjonss** [comment] 2023-12-15 13:48
Verified with 7.1, could not reproduce in release-6.5 or release-7.5 branches.

**Comment by XuHuaiyu** [comment] 2023-12-15 14:18
I can not reproduce this issue on the master branch. With binary search, I found that this issue was fixed by https://github.com/pingcap/tidb/pull/42694

**Comment by qw4990** [comment] 2024-03-25 07:02
Close it since it has been fixed by https://github.com/pingcap/tidb/pull/42694

**Closed by qw4990** 2024-03-25 07:02 UTC
Labels: type/bug, sig/planner, severity/major, may-affects-5.4, may-affects-6.1, affects-7.1
