### ISSUE TITLE
The function of if with enum type is not same with mysql

### ISSUE THREAD

**Issue by lilinghai** [pingcap/tidb#24494] opened 2021-05-08 10:29 UTC
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```sql
create table t(a int,b enum("b","y","1"));
insert into t values(0,"y"),(1,"b"),(null,null),(2,"1");
SELECT count(*) FROM t where if(a,b ,null);
```
### 2. What did you expect to see? (Required)
2
### 3. What did you see instead (Required)
1
the result of mysql 8.0.24 is 2
### 4. What is your TiDB version? (Required)

Release Version: v4.0.0-beta.2-2807-g289dcfefd-dirty
Edition: Community
Git Commit Hash: 289dcfefdd159345972f71cf42c9d6e594255290
Git Branch: master
UTC Build Time: 2021-05-06 15:11:16
GoVersion: go1.13
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false

**Comment by wshwsh12** [comment] 2021-05-10 05:07
Duplicate of https://github.com/pingcap/tidb/issues/23114
Only one issue is enough, I will fix it soon.

**Closed by wshwsh12** 2021-05-10 05:07 UTC
Labels: severity/major, sig/execution, type/bug
