### ISSUE TITLE
analyze partition table panic when using dynamic mode

### ISSUE THREAD

**Issue by aytrack** [pingcap/tidb#36643] opened 2022-07-28 02:49 UTC
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```sql
drop table if exists rptn;
create table rptn (a bigint primary key, b varchar(20)) partition by range(a) (partition p0 values less than (10), partition p1 values less than (20), partition p2 values less than (30));
insert into rptn values (1, 'a'), (2, 'b'), (3, 'c'), (14, 'd'), (16, 'e'), (18, 'f'), (20, 'h'), (25, 'i'), (27, 'j'), (29, 'k');
set tidb_analyze_version = 2;
set tidb_partition_prune_mode = 'dynamic';
analyze table rptn;  -- repeat several times
```

### 2. What did you expect to see? (Required)
analzye success
### 3. What did you see instead (Required)
analyze panic 
```sql
MySQL root@127.0.0.1:test> analyze table rptn;
(1105, '[stats]: some partition level statistics are not in statistics version 2, please set tidb_analyze_version to 2 and analyze the this table')
MySQL root@127.0.0.1:test> analyze table rptn;
(1105, '[stats]: some partition level statistics are not in statistics version 2, please set tidb_analyze_version to 2 and analyze the this table')
MySQL root@127.0.0.1:test> analyze table rptn;
(1105, '[stats]: some partition level statistics are not in statistics version 2, please set tidb_analyze_version to 2 and analyze the this table')
MySQL root@127.0.0.1:test> analyze table rptn;
(1105, 'runtime error: invalid memory address or nil pointer dereference')
```
### 4. What is your TiDB version? (Required)
```sql
MySQL root@127.0.0.1:test> select tidb_version()\G
Reconnecting...
***************************[ 1. row ]***************************
tidb_version() | Release Version: v5.0.6
Edition: Community
Git Commit Hash: 6416f8d601472892d245b950dfd5547e857a1a33
Git Branch: heads/refs/tags/v5.0.6
UTC Build Time: 2021-12-23 12:25:11
GoVersion: go1.13.4
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
```

**Comment by Yisaer** [comment] 2022-08-03 10:11
The panic stack is located as following:

```sh
[2022/08/03 18:06:01.181 +08:00] [ERROR] [conn.go:736] ["connection running loop panic"] [conn=7] [lastSQL="analyze table rptn"] [err="runtime error: invalid memory address or nil pointer dereference"] [stack="goroutine 1053 [running]:
github.com/pingcap/tidb/server.(*clientConn).Run.func1(0x6c94ee0, 0xc00120c570, 0xc0007ecc00)
\t/Users/pingcap/workspace/optimization-build-tidb-darwin-amd/go/src/github.com/pingcap/tidb/server/conn.go:734 +0xee
panic(0x622f4c0, 0x895bfb0)
\t/usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/pingcap/tidb/executor.(*ExecStmt).Exec.func1(0xc00167fa20, 0xc000cc6b30, 0xc000cc6b10)
\t/Users/pingcap/workspace/optimization-build-tidb-darwin-amd/go/src/github.com/pingcap/tidb/executor/adapter.go:302 +0x501
panic(0x622f4c0, 0x895bfb0)
\t/usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/pingcap/tidb/statistics.(*FMSketch).NDV(...)
\t/Users/pingcap/workspace/optimization-build-tidb-darwin-amd/go/src/github.com/pingcap/tidb/statistics/fmsketch.go:63
github.com/pingcap/tidb/statistics/handle.(*Handle).MergePartitionStats2GlobalStats(0xc000eb38c0, 0x6ceda20, 0xc0007ecd00, 0xc001bee7b0, 0x6ce0300, 0xc0017b9e00, 0x33, 0x0, 0x1, 0x1, ...)
\t/Users/pingcap/workspace/optimization-build-tidb-darwin-amd/go/src/github.com/pingcap/tidb/statistics/handle/handle.go:452 +0x1804
github.com/pingcap/tidb/executor.(*AnalyzeExec).Next(0xc0016f23f0, 0x6c94ee0, 0xc001bee8d0, 0xc001964370, 0x64d6fa0, 0x8a06b00)
\t/Users/pingcap/workspace/optimization-build-tidb-darwin-amd/go/src/github.com/pingcap/tidb/executor/analyze.go:173 +0x1461
github.com/pingcap/tidb/executor.Next(0x6c94ee0, 0xc001bee8d0, 0x6c9c920, 0xc0016f23f0, 0xc001964370, 0x0, 0x0)
\t/Users/pingcap/workspace/optimization-build-tidb-darwin-amd/go/src/github.com/pingcap/tidb/executor/executor.go:277 +0x225
github.com/pingcap/tidb/executor.(*ExecStmt).handleNoDelayExecutor(0xc00167fa20, 0x6c94ee0, 0xc001bee8a0, 0x6c9c920, 0xc0016f23f0, 0x0, 0x0, 0x0, 0x0)
\t/Users/pingcap/workspace/optimization-build-tidb-darwin-amd/go/src/github.com/pingcap/tidb/executor/adapter.go:537 +0x2d6
github.com/pingcap/tidb/executor.(*ExecStmt).handleNoDelay(0xc00167fa20, 0x6c94ee0, 0xc001bee840, 0x6c9c920, 0xc0016f23f0, 0x89e5900, 0x6c94e01, 0x0, 0x0, 0x0, ...)
\t/Users/pingcap/workspace/optimization-build-tidb-darwin-amd/go/src/github.com/pingcap/tidb/executor/adapter.go:418 +0x1e7
github.com/pingcap/tidb/executor.(*ExecStmt).Exec(0xc00167fa20, 0x6c94ee0, 0xc001bee840, 0x0, 0x0, 0x0, 0x0)
\t/Users/pingcap/workspace/optimization-build-tidb-darwin-amd/go/src/github.com/pingcap/tidb/executor/adapter.go:368 +0x471
github.com/pingcap/tidb/session.runStmt(0x6c94ee0, 0xc001bee810, 0xc0007ecd00, 0x6cb4ac0, 0xc00167fa20, 0x0, 0x0, 0x0, 0x0)
\t/Users/pingcap/workspace/optimization-build-tidb-darwin-amd/go/src/github.com/pingcap/tidb/session/session.go:1530 +0x2a9
github.com/pingcap/tidb/session.(*session).ExecuteStmt(0xc0007ecd00, 0x6c94ee0, 0xc001bee480, 0x6cba760, 0xc0017e9040, 0x0, 0x0, 0x0, 0x0)
\t/Users/pingcap/workspace/optimization-build-tidb-darwin-amd/go/src/github.com/pingcap/tidb/session/session.go:1425 +0x858
github.com/pingcap/tidb/server.(*TiDBContext).ExecuteStmt(0xc00120ca20, 0x6c94ee0, 0xc001bee480, 0x6cba760, 0xc0017e9040, 0xc0005344e0, 0x6c94ee0, 0xc001bee480, 0xc000cc7148)
\t/Users/pingcap/workspace/optimization-build-tidb-darwin-amd/go/src/github.com/pingcap/tidb/server/driver_tidb.go:218 +0x68
github.com/pingcap/tidb/server.(*clientConn).handleStmt(0xc0007ecc00, 0x6c94ee0, 0xc001bee480, 0x6cba760, 0xc0017e9040, 0x8a06b00, 0x0, 0x0, 0x1, 0x0, ...)
\t/Users/pingcap/workspace/optimization-build-tidb-darwin-amd/go/src/github.com/pingcap/tidb/server/conn.go:1623 +0x134
github.com/pingcap/tidb/server.(*clientConn).handleQuery(0xc0007ecc00, 0x6c94e20, 0xc0009dc980, 0xc00196e0a1, 0x12, 0x0, 0x0)
\t/Users/pingcap/workspace/optimization-build-tidb-darwin-amd/go/src/github.com/pingcap/tidb/server/conn.go:1496 +0x44f
github.com/pingcap/tidb/server.(*clientConn).dispatch(0xc0007ecc00, 0x6c94e20, 0xc0009dc980, 0xc00196e0a0, 0x13, 0x12, 0x0, 0x0)
\t/Users/pingcap/workspace/optimization-build-tidb-darwin-amd/go/src/github.com/pingcap/tidb/server/conn.go:1030 +0x698
github.com/pingcap/tidb/server.(*clientConn).Run(0xc0007ecc00, 0x6c94ee0, 0xc00120c570)
\t/Users/pingcap/workspace/optimization-build-tid"]
```

The problem is fixed in https://github.com/pingcap/tidb/pull/23962, and dyamic partition_prune_mode and v2 tidb analyze version is stable in the latest version.

**Closed by Yisaer** 2022-08-03 10:11 UTC
Labels: type/bug, sig/planner, severity/moderate, affects-5.0
