### ISSUE TITLE
interval() wrong results with 64-bit integers

### ISSUE THREAD

**Issue by morgo** [pingcap/tidb#31788] opened 2022-01-18 23:22 UTC
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

Both MySQL and TiDB have wrong results when using the `INTERVAL()` sql function and 64-bit integers, but the bugs differ. See: https://dev.mysql.com/doc/refman/8.0/en/comparison-operators.html#function_interval

```sql
DROP TABLE IF EXISTS t1;
CREATE TABLE t1 (
    id INT NOT NULL PRIMARY KEY auto_increment,
  `col_5` tinyint(4) DEFAULT '109',
  `col_7` bigint(20) NOT NULL
);

INSERT INTO `t1` VALUES (3,57,4816720515551702398),(4,-76,7635266288681458392),(5,-118,732177212084557133),(6,NULL,5549735173285411483),
(9,115,8545214179437112779),(13,-100,1197431970803945571),(17,77,2425700499002615980);
SELECT col_5, col_7, interval(1, col_7, col_5) FROM t1 ORDER BY id;
```

### 2. What did you expect to see? (Required)

All expressions should yield 2?

### 3. What did you see instead (Required)

```sql
mysql [localhost:8027] {msandbox} (test) > SELECT col_5, col_7, interval(1, col_7, col_5) FROM t1 ORDER BY id;
+-------+---------------------+---------------------------+
| col_5 | col_7               | interval(1, col_7, col_5) |
+-------+---------------------+---------------------------+
|    57 | 4816720515551702398 |                         0 | # incorrect
|   -76 | 7635266288681458392 |                         0 | # incorrect
|  -118 |  732177212084557133 |                         0 | # incorrect
|  NULL | 5549735173285411483 |                         0 | # incorrect
|   115 | 8545214179437112779 |                         0 | # incorrect
|  -100 | 1197431970803945571 |                         0 | # incorrect
|    77 | 2425700499002615980 |                         0 | # incorrect
+-------+---------------------+---------------------------+
7 rows in set (0.00 sec)

tidb> SELECT col_5, col_7, interval(1, col_7, col_5) FROM t1 ORDER BY id;
+-------+---------------------+---------------------------+
| col_5 | col_7               | interval(1, col_7, col_5) |
+-------+---------------------+---------------------------+
|    57 | 4816720515551702398 |                         0 | # incorrect
|   -76 | 7635266288681458392 |                         2 | 
|  -118 |  732177212084557133 |                         2 | 
|  NULL | 5549735173285411483 |                         2 |
|   115 | 8545214179437112779 |                         0 | # incorrect
|  -100 | 1197431970803945571 |                         2 | 
|    77 | 2425700499002615980 |                         0 | # incorrect
+-------+---------------------+---------------------------+
7 rows in set (0.00 sec)
```

### 4. What is your TiDB version? (Required)

```sql
tidb> SELECT tidb_version()\G
*************************** 1. row ***************************
tidb_version(): Release Version: v5.5.0-alpha-136-g50704075a
Edition: Community
Git Commit Hash: 50704075afa7c0e3f2aa1fc9a66f440884a8f3fe
Git Branch: master
UTC Build Time: 2022-01-18 00:29:17
GoVersion: go1.16.9
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
1 row in set (0.00 sec)

```

**Comment by morgo** [comment] 2022-01-19 00:40
More cases:
```sql
DROP TABLE IF EXISTS t2;
CREATE TABLE `t2` (
 id INT NOT NULL PRIMARY KEY auto_increment,
  `col_20` bigint(20) NOT NULL,
  `col_21` smallint(6) NOT NULL,
  `col_22` decimal(24,10) DEFAULT NULL,
  `col_23` tinyint(4) NOT NULL DEFAULT '71',
  `col_25` tinyint(4) DEFAULT '18',
  `col_27` char(77)
);

INSERT INTO `t2` VALUES (1,7100316839031869279,7890,5374.1310000000,115,81,'du'),(2,-1538327168691339339,9320,154542.9000000000,-29,-126,'SfwoyjUEzgg'),(3,7477750043422686780,-24236,73146.0700000000,-57,-86,'dHvEZpLboMrJl'),(4,-5351625993410825218,15435,43.9700000000,124,-75,''),(5,4324675134788174691,27335,24458.2200000000,87,-33,'SHEFsbVhAm'),(6,-2464749073928323845,-20194,7094.7800000000,-9,10,'aILHs'),(7,1612862134678978722,-28719,2165.9600000000,-13,-106,'vRqTNSfUyKmT'),(8,-1332605720804808277,14103,83.9000000000,-56,-83,'IauAORTtGzTBpTH'),(9,3578924923120355253,28677,17579.3277000000,54,-73,'EyfBsYIYEEtdpxnLRG'),(10,-5264378678660537921,3061,24378.1910000000,-4,57,'SERElSBYsHMr'),(11,-7007042174416568578,-9315,504.3000000000,-52,-31,'abpNXDmOjRypBr'),(12,1043969013821250466,-7855,121719.8100000000,118,-36,'AR'),(13,-4165241964413081812,-12084,632869.3000000000,-24,21,'nSWYrpTH'),(14,7598655043502682515,2717,573.0000000000,63,-86,'CsWIuxlSjU'),(15,843692250940253380,-8004,0.5440000000,49,118,'PxLIccTsprySmvGk'),(16,-3680941745704954084,29551,NULL,-13,-19,'AxZEVqTbS'),(17,875085249683513463,11207,4.6950000000,-79,-46,'beJydTGIYh'),(18,5888267793391993829,5371,94.6300000000,-109,89,'SapBPqczTWWSN'),(19,8430588238965475410,17907,54795.0000000000,-115,13,'zCJa'),(20,-7059114302359027040,19533,667.0000000000,-23,20,'exIYxgdNdACMbHG');

select
 interval( mid( interval( left( col_22 , 4 ) , col_21 , col_27 ) , 4 , 7 ) , col_22 , col_25 ) as index0expr,
 col_20,
 col_23,
 interval( interval( mid( interval( left( col_22 , 4 ) , col_21 , col_27 ) , 4 , 7 ) , col_22 , col_25 ) , col_20 , col_23 ) as intervalresult
from t2 
order by id;
```

**Comment by mengxin9014** [comment] 2022-06-30 02:16
Maybe it is not a bug?

**Comment by zanmato1984** [comment] 2022-07-08 03:22
I think this is an UB in MySQL, given that MySQL doc doesn't say anything about how cases like this are handled. So I agree that this is not a bug.

I'm closing it for now. Feel free to reopen if anyone found something new.

**Closed by zanmato1984** 2022-07-08 03:22 UTC
Labels: type/bug, sig/execution, severity/major, affects-5.0, affects-5.1, affects-5.2, affects-5.3, affects-5.4, affects-6.0, affects-6.1
