### ISSUE TITLE
Although the CASE WHEN clause returns the same value as the direct concatenation, NULLIF yields different results in each case

### ISSUE THREAD

**Issue by akuluasan** [pingcap/tidb#56552] opened 2024-10-11 03:11 UTC
### 1. Minimal reproduce step (Required)

```sql
select nullif(SPACE(20), case when false then ('TEST') else ('l' || 'o') end) as c1;
select nullif(SPACE(20), ('l' || 'o')) as c1;
```

### 2. What did you expect to see? (Required)
The condition for CASE WHEN is FALSE, so this clause should return the result of (l || o). This statement should return the same value as SELECT NULLIF(SPACE(5), ('l' || 'o')) AS c1;, but the actual result is not the same.
So they should both return SPACE(20) or both return NULL.

### 3. What did you see instead (Required)
They return different results
```sql
select nullif(SPACE(20), case when false then ('TEST') else ('l' || 'o') end) as c1;
+----------------------+
| c1                   |
+----------------------+
|                      |
+----------------------+
1 row in set, 2 warnings (0.00 sec)

select nullif(SPACE(20), ('l' || 'o')) as c1;
+------+
| c1   |
+------+
| NULL |
+------+
1 row in set, 2 warnings (0.00 sec)

```
### 4. What is your TiDB version? (Required)

```
 select version();
+--------------------+
| version()          |
+--------------------+
| 8.0.11-TiDB-v7.5.1 |
+--------------------+
1 row in set (0.00 sec)

```

**Comment by windtalker** [comment] 2024-10-15 07:27
This is the same as #56553 
For
```
select nullif(SPACE(20), case when false then ('TEST') else ('l' || 'o') end) as c1;
```
The return type of `case when false then ('TEST') else ('l' || 'o') end` is string, so `nullif` compare `space(20)`(string type) and `'0'`(string type), which is false, so it return `space(20)`
For
```
select nullif(SPACE(20), ('l' || 'o')) as c1;
``` 
it need to compare `space(20)`(string type) and `0`(int type) directly, when compare string type with int type, TiDB/MySQL will use double compare, so both `space(20)` and `0` will be converted to double, `space(20)` will be converted to 0, so `nullif(SPACE(20), ('l' || 'o'))` returns `NULL`

I test this in MySQL 8.0.27, the behavior is the same as TiDB. I will close this issue as not a bug.

**Closed by windtalker** 2024-10-15 07:27 UTC
Labels: type/bug, sig/execution, severity/major, may-affects-5.4, may-affects-6.1, may-affects-6.5, may-affects-7.1, may-affects-7.5, may-affects-8.1, impact/wrong-result
