### ISSUE TITLE
When I change the table name, I have to restart the tidb service

### ISSUE THREAD

**Issue by panghuchi** [pingcap/tidb#15045] opened 2020-02-29 13:58 UTC
I have a table 'tx_product'.
I write a simple query code:
![image](https://user-images.githubusercontent.com/43361137/75608776-9807c480-5b3d-11ea-91cf-6f5d4e2d2802.png)
It works.

But when change table name to 'tx_product_1'. It still work. If I restart tidb server, table not exsit exception will be throw.

So when I modify the table structure, do I have to restart the tidb server??

**Comment by shenli** [comment] 2020-02-29 14:05
@navychi Thanks for your feedback!
Please keep the issue template and fill it. We need some information such as version, reproducible steps.

**Comment by nullnotnil** [comment] 2020-07-23 19:12
I believe the cause may be that you have an existing transaction open. You don't have to restart the TiDB service, executing `ROLLBACK` should be sufficient.

**Comment by jebter** [comment] 2024-06-05 08:45
The issue has not been updated for too long, so I will close it. If there are any updates you can reopen it.

**Closed by jebter** 2024-06-05 08:45 UTC
Labels: type/question
