### ISSUE TITLE
ERROR 1105 (HY000): Can't find column xxx in schema Column

### ISSUE THREAD

**Issue by 15767637775** [pingcap/tidb#39651] opened 2022-12-06 03:54 UTC
### 1. Minimal reproduce step (Required)
```
create table t_process_node (
    id int,
    process_id int,
    is_allowed_end int,
    sort_num int    
);
create table t_process_alarm_rel (
    process_id int,
    alarm_num int,
    init_alarm_num int
);
SELECT 
    group_concat(
        a.is_allowed_end
        ORDER BY 
            a.sort_num
    ) is_allowed_end
FROM
    (
        SELECT
            ifnull(node.is_allowed_end, '0') as is_allowed_end,
            node.process_id as process_id,
            node.sort_num as sort_num,
            rel.init_alarm_num AS alarm_number
        FROM
            t_process_node node,
            t_process_alarm_rel rel
        WHERE
            node.process_id = rel.process_id
            and rel.alarm_num in ("111")
        ORDER BY node.id  -- tidb remove this line, Query OK
    ) as a 
GROUP BY 
    a.process_id;
ERROR 1105 (HY000): Can't find column test.t_process_node.sort_num in schema Column: [Column#10,test.t_process_node.process_id,test.t_process_node.id] Unique key: []
```

### 2. What did you expect to see? (Required)
mysql works well, but I got an issue on tidb, I hope tidb can Query OK

### 3. What did you see instead (Required)
ERROR 1105 (HY000): Can't find column test.t_process_node.sort_num in schema Column: [Column#10,test.t_process_node.process_id,test.t_process_node.id] Unique key: []

### 4. What is your TiDB version? (Required)
v6.1.2

**Comment by tiancaiamao** [comment] 2022-12-06 05:53
@chrysan Seems the preprocess does not handle the alias well, PTAL

**Comment by fixdb** [comment] 2022-12-07 06:22
Hi @15767637775, thanks for reporting this issue.
As a walk-around, you can try to `set @@tidb_remove_orderby_in_subquery=on;` to avoid the issue temporarily.

**Comment by 15767637775** [comment] 2022-12-07 06:30
> Hi @15767637775, thanks for reporting this issue. As a walk-around, you can try to `set @@tidb_remove_orderby_in_subquery=on;` to avoid the issue temporarily.

I've tried, It dose not work.
```
mysql> set @@tidb_remove_orderby_in_subquery=on;
Query OK, 0 rows affected (0.00 sec)

mysql> 
mysql> 
mysql> SELECT 
    ->     group_concat(
    ->         a.is_allowed_end
    ->         ORDER BY 
    ->             a.sort_num
    ->     ) is_allowed_end
    -> FROM
    ->     (
    ->         SELECT
    ->             ifnull(node.is_allowed_end, '0') as is_allowed_end,
    ->             node.process_id as process_id,
    ->             node.sort_num as sort_num,
    ->             rel.init_alarm_num AS alarm_number
    ->         FROM
    ->             t_process_node node,
    ->             t_process_alarm_rel rel
    ->         WHERE
    ->             node.process_id = rel.process_id
    ->             and rel.alarm_num in ("111")
    ->         ORDER BY node.id  -- tidb remove this line, Query OK
    ->     ) as a 
    -> GROUP BY 
    ->     a.process_id;
ERROR 1105 (HY000): Can't find column a.t_process_node.sort_num in schema Column: [a.t_process_node.process_id,a.t_process_node.is_allowed_end] Unique key: []
```

**Comment by fixdb** [comment] 2022-12-07 06:33
@15767637775 
Oops, sorry. You are right. I tested it on the wrong query. 
It looks like the error happens before it goes into optimizer preprocess stage.

**Comment by Qiuchi0918** [comment] 2023-01-06 05:23
@15767637775 Might caused by function group_concat. Having you tried somehow replacing it?

**Comment by qw4990** [comment] 2024-04-28 06:38
Can't reproduce it again, it might have been fixed by some PR:
```
mysql> SELECT 
    ->     group_concat(
    ->         a.is_allowed_end
    ->         ORDER BY 
    ->             a.sort_num
    ->     ) is_allowed_end
    -> FROM
    ->     (
    ->         SELECT
    ->             ifnull(node.is_allowed_end, '0') as is_allowed_end,
    ->             node.process_id as process_id,
    ->             node.sort_num as sort_num,
    ->             rel.init_alarm_num AS alarm_number
    ->         FROM
    ->             t_process_node node,
    ->             t_process_alarm_rel rel
    ->         WHERE
    ->             node.process_id = rel.process_id
    ->             and rel.alarm_num in ("111")
    ->         ORDER BY node.id  -- tidb remove this line, Query OK
    ->     ) as a 
    -> GROUP BY 
    ->     a.process_id;
Empty set (0.01 sec)

mysql>
```

**Closed by qw4990** 2024-04-28 06:38 UTC
Labels: type/bug, sig/planner, severity/major, affects-5.0, affects-5.1, affects-5.2, affects-5.3, affects-5.4, may-affects-4.0, affects-6.0, affects-6.1, affects-6.2, affects-6.3, affects-6.4, affects-6.5, affects-6.6, affects-7.0, affects-7.1, affects-7.5, affects-8.1
