### ISSUE TITLE
Can't find column when using group concat

### ISSUE THREAD

**Issue by seiya-annie** [pingcap/tidb#35944] opened 2022-07-05 04:10 UTC
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

create table t1(a int, c int);
create table t2(a int, c int);
insert into t1 values (1,1),(1,2),(2,3),(2,4);
insert into t2 values (1,1),(1,2),(2,3),(2,4);
select group_concat(c order by (select group_concat(c order by a) from t2 where a=t1.a)) from t1;

### 2. What did you expect to see? (Required)
no error
### 3. What did you see instead (Required)
<=v4.0.14, report :
mysql> select group_concat(c order by (select group_concat(c order by a) from t2 where a=t1.a)) from t1;
ERROR 1105 (HY000): Can't find column Column#7 in schema Column: [test.t1.c] Unique key: []
>4.0.14, report:
mysql> select group_concat(c order by (select group_concat(c order by a) from t2 where a=t1.a)) from t1;
ERROR 1105 (HY000): Can't find column Column#10 in schema Column: [test2.t1.c] Unique key: []

### 4. What is your TiDB version? (Required)

4.0-6.1

**Comment by seiya-annie** [comment] 2022-07-05 04:11
looks similar with https://github.com/pingcap/tidb/issues/22573

**Comment by seiya-annie** [comment] 2022-07-05 04:14
![group_cancat](https://user-images.githubusercontent.com/53471087/177248107-faccb210-77aa-42d0-a9c0-2a5dff7b694e.jpeg)
report by PTS team, this sql can execute on v3.0.5

**Comment by qw4990** [comment] 2024-04-28 07:13
Can't reproduce this issue, it might have been fixed by some PR:
```
mysql> select group_concat(c order by (select group_concat(c order by a) from t2 where a=t1.a)) from t1;
+-----------------------------------------------------------------------------------+
| group_concat(c order by (select group_concat(c order by a) from t2 where a=t1.a)) |
+-----------------------------------------------------------------------------------+
| 2,1,4,3                                                                           |
+-----------------------------------------------------------------------------------+
1 row in set (0.01 sec)

```

**Closed by qw4990** 2024-04-28 07:13 UTC
Labels: type/bug, sig/planner, severity/major, affects-4.0, affects-5.0, affects-5.1, affects-5.2, affects-5.3, affects-5.4, affects-6.0, affects-6.1, affects-6.2, affects-6.3, affects-6.4, affects-6.5, affects-6.6, affects-7.0, affects-7.1, affects-7.5, affects-8.1
