### ISSUE TITLE
mysql-connector-java get metadata.Isnull doesn't meet expectations

### ISSUE THREAD

**Issue by wowdba** [pingcap/tidb#19651] opened 2020-09-01 06:56 UTC
### 1. Minimal reproduce step 
mysql-connector-java version: 5.1.49 & 8.0.15
1.Create table
```
MySQL [yxytest]> CREATE TABLE `test1` (
    ->   `id` bigint(20) NOT NULL /*T![auto_rand] AUTO_RANDOM(5) */,
    ->   `gmt_create` timestamp NULL COMMENT 'time',
    ->   PRIMARY KEY (`id`)
    -> ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
```
2.Running code(java)
```
Connection con=simplecon.getConnection();
try {
    PreparedStatement ps=con.prepareStatement(sql);
    ResultSetMetaData re=ps.getMetaData();
    int count=re.getColumnCount();
    for(int i=1;i<=count;i++)
    {

        System.out.print(re.getColumnLabel(i)+" ");
        System.out.print(re.isNullable(i)+" ");
    }
```

### 2. What did you expect to see? 
```
id 0 gmt_create 1
```
### 3. What did you see instead 
```
id 0 gmt_create 0
```
MySQL return  “id 0 gmt_create 1”
### 4. What is your TiDB version? 

4.0.4

**Comment by nullnotnil** [comment] 2020-09-02 02:29
I believe this is a duplicate of https://github.com/pingcap/tidb/issues/18488. Here is an sql only test-case using `mysql --column-type-info`:

```sql
DROP TABLE IF EXISTS test1;
CREATE TABLE test1 (
 id bigint(20) NOT NULL PRIMARY KEY auto_increment,
 gmt_create timestamp
);
SELECT * FROM test1;

..

mysql> CREATE TABLE test1 (
    ->  id bigint(20) NOT NULL PRIMARY KEY auto_increment,
    ->  gmt_create timestamp
    -> );
Query OK, 0 rows affected (0.08 sec)

mysql> 
mysql> SELECT * FROM test1;
Field   1:  `id`
Catalog:    `def`
Database:   `test`
Table:      `test1`
Org_table:  `test1`
Type:       LONGLONG
Collation:  binary (63)
Length:     20
Max_length: 0
Decimals:   0
Flags:      NOT_NULL PRI_KEY AUTO_INCREMENT NUM 

Field   2:  `gmt_create`
Catalog:    `def`
Database:   `test`
Table:      `test1`
Org_table:  `test1`
Type:       TIMESTAMP
Collation:  binary (63)
Length:     19
Max_length: 0
Decimals:   0
Flags:      NOT_NULL BINARY 


0 rows in set (0.00 sec)

mysql> SELECT tidb_version()\G
*************************** 1. row ***************************
tidb_version(): Release Version: v4.0.0-beta.2-1118-g1cab3d594
Edition: Community
Git Commit Hash: 1cab3d59471a536b5d3d8dca7b07b209f9e8e363
Git Branch: master
UTC Build Time: 2020-09-01 13:58:35
GoVersion: go1.13
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
1 row in set (0.00 sec)
```

**Comment by ZenoTan** [comment] 2020-09-02 03:12
It is a duplicate issue.

**Comment by SunRunAway** [comment] 2020-11-11 13:56
Duplicate of #18488

**Closed by SunRunAway** 2020-11-11 13:56 UTC
Labels: type/bug, type/duplicate
