### ISSUE TITLE
planner wrongly pushed enum/set filter into tiflash side

### ISSUE THREAD

**Issue by lilinghai** [pingcap/tidb#27125] opened 2021-08-11 12:16 UTC
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```sql
create table t1(a int);
create table t2(a varchar(20),b set("a","b"));
alter table t1 set tiflash replica 2;
alter table t2 set tiflash replica 2;
select max( length(t2.a)) from  t1 right join  t2 on (t2. b is NULL);
```
the plan is 
```
+------------------------------------------------------+----------+-------------------+---------------+--------------------------------------------------------+
| id                                                   | estRows  | task              | access object | operator info                                          |
+------------------------------------------------------+----------+-------------------+---------------+--------------------------------------------------------+
| StreamAgg_13                                         | 1.00     | root              |               | funcs:max(Column#10)->Column#6                         |
| └─Projection_44                                      | 1.00     | root              |               | length(rs.t2.a)->Column#10                             |
|   └─Projection_42                                    | 1.00     | root              |               | rs.t2.a                                                |
|     └─TopN_16                                        | 1.00     | root              |               | Column#9:desc, offset:0, count:1                       |
|       └─Projection_43                                | 10000.00 | root              |               | rs.t2.a, length(rs.t2.a)->Column#9                     |
|         └─HashJoin_19                                | 10000.00 | root              |               | CARTESIAN right outer join, right cond:isnull(rs.t2.b) |
|           ├─Projection_40(Build)                     | 1.00     | root              |               | rs.t2.a, rs.t2.b                                       |
|           │ └─TopN_26                                | 1.00     | root              |               | Column#8:desc, offset:0, count:1                       |
|           │   └─Projection_41                        | 1.00     | root              |               | rs.t2.a, rs.t2.b, length(rs.t2.a)->Column#8            |
|           │     └─TableReader_37                     | 1.00     | root              |               | data:ExchangeSender_36                                 |
|           │       └─ExchangeSender_36                | 1.00     | batchCop[tiflash] |               | ExchangeType: PassThrough                              |
|           │         └─Projection_38                  | 1.00     | batchCop[tiflash] |               | rs.t2.a, rs.t2.b                                       |
|           │           └─TopN_35                      | 1.00     | batchCop[tiflash] |               | Column#7:desc, offset:0, count:1                       |
|           │             └─Projection_39              | 8000.00  | batchCop[tiflash] |               | rs.t2.a, rs.t2.b, length(rs.t2.a)->Column#7            |
|           │               └─Selection_34             | 8000.00  | batchCop[tiflash] |               | not(isnull(length(rs.t2.a)))                           |
|           │                 └─TableFullScan_33       | 10000.00 | batchCop[tiflash] | table:t2      | keep order:false, stats:pseudo                         |
|           └─TableReader_23(Probe)                    | 10000.00 | root              |               | data:TableFullScan_22                                  |
|             └─TableFullScan_22                       | 10000.00 | cop[tiflash]      | table:t1      | keep order:false, stats:pseudo                         |
+------------------------------------------------------+----------+-------------------+---------------+--------------------------------------------------------+
```
### 2. What did you expect to see? (Required)
successfully
### 3. What did you see instead (Required)
ERROR 1105 (HY000): close of nil channel
```
[2021/08/11 20:15:31.617 +08:00] [ERROR] [conn.go:919] ["connection running loop panic"] [conn=221] [lastSQL="select max( length(t2.a)) from  t1 right join  t2 on (t2. b is NULL)"] [err="close of nil channel"] [stack="goroutine 5750755 [running]:
github.com/pingcap/tidb/server.(*clientConn).Run.func1(0x4028ad0, 0xc003ec00f0, 0xc001e0e000)
\t/home/jenkins/agent/workspace/build_tidb_multi_branch_master/go/src/github.com/pingcap/tidb/server/conn.go:917 +0xf5
panic(0x36de1e0, 0x3f9e590)
\t/usr/local/go/src/runtime/panic.go:965 +0x1b9
github.com/pingcap/tidb/executor.(*ExecStmt).Exec.func1(0xc0021c4820, 0xc0087d6b00, 0xc0087d6ae0)
\t/home/jenkins/agent/workspace/build_tidb_multi_branch_master/go/src/github.com/pingcap/tidb/executor/adapter.go:333 +0x4d4
panic(0x36de1e0, 0x3f9e590)
\t/usr/local/go/src/runtime/panic.go:965 +0x1b9
github.com/pingcap/tidb/executor.(*HashJoinExec).Close(0xc0042b5600, 0x0, 0xc0086dd650)
\t/home/jenkins/agent/workspace/build_tidb_multi_branch_master/go/src/github.com/pingcap/tidb/executor/join.go:117 +0x47
github.com/pingcap/tidb/executor.(*baseExecutor).Close(0xc008893800, 0x2b, 0x4029588)
\t/home/jenkins/agent/workspace/build_tidb_multi_branch_master/go/src/github.com/pingcap/tidb/executor/executor.go:180 +0x7e
github.com/pingcap/tidb/executor.(*ProjectionExec).Close(0xc008893800, 0x0, 0x0)
\t/home/jenkins/agent/workspace/build_tidb_multi_branch_master/go/src/github.com/pingcap/tidb/executor/projection.go:328 +0x138
github.com/pingcap/tidb/executor.(*SortExec).Close(0xc001d2cdc0, 0x0, 0x0)
\t/home/jenkins/agent/workspace/build_tidb_multi_branch_master/go/src/github.com/pingcap/tidb/executor/sort.go:80 +0xee
github.com/pingcap/tidb/executor.(*baseExecutor).Close(0xc008893900, 0x2a, 0x4029588)
\t/home/jenkins/agent/workspace/build_tidb_multi_branch_master/go/src/github.com/pingcap/tidb/executor/executor.go:180 +0x7e
github.com/pingcap/tidb/executor.(*ProjectionExec).Close(0xc008893900, 0x0, 0xc0086dd740)
\t/home/jenkins/agent/workspace/build_tidb_multi_branch_master/go/src/github.com/pingcap/tidb/executor/projection.go:328 +0x138
github.com/pingcap/tidb/executor.(*baseExecutor).Close(0xc008893a00, 0x2c, 0x4029588)
\t/home/jenkins/agent/workspace/build_tidb_multi_branch_master/go/src/github.com/pingcap/tidb/executor/executor.go:180 +0x7e
github.com/pingcap/tidb/executor.(*ProjectionExec).Close(0xc008893a00, 0x306a85a, 0xc001d2cdc0)
\t/home/jenkins/agent/workspace/build_tidb_multi_branch_master/go/src/github.com/pingcap/tidb/executor/projection.go:328 +0x138
github.com/pingcap/tidb/executor.(*baseExecutor).Close(0xc008893b00, 0x3111b45, 0xc008893900)
\t/home/jenkins/agent/workspace/build_tidb_multi_branch_master/go/src/github.com/pingcap/tidb/executor/executor.go:180 +0x7e
github.com/pingcap/tidb/executor.(*StreamAggExec).Close(0xc008893b00, 0xc0018ff440, 0xc0087d6800)
\t/home/jenkins/agent/workspace/build_tidb_multi_branch_master/go/src/github.com/pingcap/tidb/executor/aggregate.go:1276 +0xb6
github.com/pingcap/parser/terror.Call(0xc0087d6a58)
\t/nfs/cache/mod/github.com/pingcap/parser@v0.0.0-20210806073423-d4a88481405f/terror/terror.go:282 +0x3f
github.com/pingcap/tidb/executor.(*ExecStmt).Exec(0xc0021c4820, 0x4028ad0, 0xc0086dd410, 0x0, 0x0, 0x3fd9400, 0xc0018ff440)
\t/home/jenkins/agent/workspace/build_tidb_multi_branch_master/go/src/github.com/pingcap/tidb/executor/adapter.go:389 +0x41f
github.com/pingcap/tidb/session.runStmt(0x4028ad0, 0xc0086dc180, 0xc003954a00, 0x4041280, 0xc0021c4820, 0x0, 0x0, 0x0, 0x0)
\t/home/jenkins/agent/workspace/build_tidb_multi_branch_master/go/src/github.com/pingcap/tidb/session/session.go:1783 +0x37f
github.com/pingcap/tidb/session.(*session).ExecuteStmt(0xc003954a00, 0x4028ad0, 0xc0086dc180, 0x4045fa8, 0xc0087d8960, 0x0, 0x0, 0x0, 0x0)
\t/home/jenkins/agent/workspace/build_tidb_multi_branch_master/go/src/github.com/pingcap/tidb/session/session.go:1677 +0xab1
github.com/pingcap/tidb/server.(*TiDBContext).ExecuteStmt(0xc007d78a50, 0x4028ad0, 0xc0086dc180, 0x4045fa8, 0xc0087d8960, 0xc0096d8d40, 0x4028ad0, 0xc0086dc180, 0x2fdf)
\t/home/jenkins/agent/workspace/build_tidb_multi_branch_master/go/src/github.com/pingcap/tidb/server/driver_tidb.go:218 +0x6b
github.com/pingcap/tidb/server.(*clientConn).handleStmt(0xc001e0e000, 0x4028a28, 0xc0086dc180, 0x4045fa8, 0xc0087d8960, 0x5d87a98, 0x0, 0x0, 0x1, 0x0, ."]
```
### 4. What is your TiDB version? (Required)

Release Version: v5.2.0-alpha-549-g6720fcd40
Edition: Community
Git Commit Hash: 6720fcd40ff90f11c2f678bb42bb288474854c19
Git Branch: master
UTC Build Time: 2021-08-09 03:22:37
GoVersion: go1.16.4
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false

**Comment by wshwsh12** [comment] 2021-11-16 13:20
Now the sql will get the error.
```
[tidb]> select max( length(t2.a)) from  t1 right join  t2 on (t2. b is NULL);
ERROR 1815 (HY000): expression test.t2.b cannot be pushed down
```

**Comment by bestwoody** [comment] 2022-07-18 12:29
tiflash doesn't support Mysql.TypeSet push down, however optizer generate a TiFlash push down plan, which cause the executor throw "cannot be pushed down" error. 
<img width="1157" alt="截屏2022-07-18 20 28 34" src="https://user-images.githubusercontent.com/89765764/179511203-036522da-d476-4f51-9d89-7def3cbef40b.png">

**Comment by bestwoody** [comment] 2022-07-19 07:39
I found "test.t2.b" is not checked during planner stage, which is not supported to push down tiflash since it's MySql.TypeSet collumn.

**Comment by hi-rustin** [comment] 2023-11-27 07:15
After debugging the issue, we discovered that during post-optimization, the `InjectProjBelowSort` rule introduced the projection `Projection_39 8000.00 mpp[tiflash] test.t2.a, test.t2.b, length(test.t2.a)->Column#7`. Consequently, there isn't a straightforward solution available at this moment.

**Comment by qw4990** [comment] 2024-04-28 08:29
Can't reproduce this issue, it might have been fixed by some other PR:
```
mysql> create table t1(a int);
Query OK, 0 rows affected (0.07 sec)

mysql> create table t2(a varchar(20),b set("a","b"));
Query OK, 0 rows affected (0.07 sec)

mysql> alter table t1 set tiflash replica 2;
Query OK, 0 rows affected (0.07 sec)

mysql> alter table t2 set tiflash replica 2;
Query OK, 0 rows affected (0.07 sec)

mysql> select max( length(t2.a)) from  t1 right join  t2 on (t2. b is NULL);
+--------------------+
| max( length(t2.a)) |
+--------------------+
|               NULL |
+--------------------+
1 row in set (0.00 sec)

mysql> explain select max( length(t2.a)) from  t1 right join  t2 on (t2. b is NULL);
+------------------------------------------------------+----------+--------------+---------------+----------------------------------------------------------+
| id                                                   | estRows  | task         | access object | operator info                                            |
+------------------------------------------------------+----------+--------------+---------------+----------------------------------------------------------+
| StreamAgg_13                                         | 1.00     | root         |               | funcs:max(Column#10)->Column#6                           |
| └─Projection_44                                      | 1.00     | root         |               | length(test.t2.a)->Column#10                             |
|   └─Projection_42                                    | 1.00     | root         |               | test.t2.a                                                |
|     └─TopN_16                                        | 1.00     | root         |               | Column#9:desc, offset:0, count:1                         |
|       └─Projection_43                                | 10000.00 | root         |               | test.t2.a, length(test.t2.a)->Column#9                   |
|         └─HashJoin_18                                | 10000.00 | root         |               | CARTESIAN right outer join, right cond:isnull(test.t2.b) |
|           ├─Projection_40(Build)                     | 1.00     | root         |               | test.t2.a, test.t2.b                                     |
|           │ └─TopN_27                                | 1.00     | root         |               | Column#8:desc, offset:0, count:1                         |
|           │   └─Projection_41                        | 1.00     | root         |               | test.t2.a, test.t2.b, length(test.t2.a)->Column#8        |
|           │     └─TableReader_37                     | 1.00     | root         |               | MppVersion: 2, data:ExchangeSender_36                    |
|           │       └─ExchangeSender_36                | 1.00     | mpp[tiflash] |               | ExchangeType: PassThrough                                |
|           │         └─Projection_38                  | 1.00     | mpp[tiflash] |               | test.t2.a, test.t2.b                                     |
|           │           └─TopN_35                      | 1.00     | mpp[tiflash] |               | Column#7:desc, offset:0, count:1                         |
|           │             └─Projection_39              | 8000.00  | mpp[tiflash] |               | test.t2.a, test.t2.b, length(test.t2.a)->Column#7        |
|           │               └─Selection_34             | 8000.00  | mpp[tiflash] |               | not(isnull(length(test.t2.a)))                           |
|           │                 └─TableFullScan_33       | 10000.00 | mpp[tiflash] | table:t2      | pushed down filter:empty, keep order:false, stats:pseudo |
|           └─TableReader_24(Probe)                    | 10000.00 | root         |               | MppVersion: 2, data:ExchangeSender_23                    |
|             └─ExchangeSender_23                      | 10000.00 | mpp[tiflash] |               | ExchangeType: PassThrough                                |
|               └─TableFullScan_22                     | 10000.00 | mpp[tiflash] | table:t1      | keep order:false, stats:pseudo                           |
+------------------------------------------------------+----------+--------------+---------------+----------------------------------------------------------+
19 rows in set (0.00 sec)
```

**Closed by qw4990** 2024-04-28 08:29 UTC
Labels: type/bug, sig/planner, severity/major, affects-6.0, affects-6.1, affects-6.2, affects-6.3, affects-6.5, affects-6.6, affects-7.0, affects-7.1, affects-7.5, affects-8.1
