### ISSUE TITLE
Blocking issues at 'TestT' of store/mockstore/unistore/cophandler/cop_handler_test.go

### ISSUE THREAD

**Issue by charlesxsh** [pingcap/tidb#27000] opened 2021-08-09 01:17 UTC
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
Simply run the unit test TestT at store/mockstore/unistore/cophandler/cop_handler_test.go

### 2. What did you expect to see? (Required)
All coroutines/channels exit/close properly

### 3. What did you see instead (Required)
Some blocking issues found at 

github.com/pingcap/badger@v1.5.1-0.20200908111422-2e78ee155d19/blob.go:468
```go
func (h *blobGCHandler) run(c *y.Closer) {
	defer c.Done()
	for {
		select {           <------- line 468
		case discardInfo := <-h.discardCh:
			h.handleDiscardInfo(discardInfo)
			err := h.doGCIfNeeded()
			if err != nil {
				log.Error("handle discardInfo", zap.Error(err))
			}
		case <-c.HasBeenClosed():
			return
		}
	}
}

```

github.com/pingcap/badger@v1.5.1-0.20200908111422-2e78ee155d19/cache/cache.go:311
```go
func (c *Cache) processItems() {
	for {
		select {
		case e := <-c.setBuf:   <-------- line 311
			if e.del {
				c.policy.Del(e.key)
				continue
			}
			c.handleNewItem(e.key, e.cost)
		case <-c.stop:
			return
		}
	}
}

```

github.com/pingcap/badger@v1.5.1-0.20200908111422-2e78ee155d19/cache/policy.go:64
```go
func (p *policy) processItems() {
	for {
		select {     <------- line 64
		case items := <-p.itemsCh:
			p.Lock()
			p.admit.Push(items)
			p.Unlock()
		case <-p.stop:
			return
		}
	}
}

```

github.com/pingcap/badger@v1.5.1-0.20200908111422-2e78ee155d19/db.go:341
```go
	go func() {
		lc := db.closers.memtable
		for {
			select {                 <------ line 341
			case db.memTableCh <- memtable.New(arenaSize(db.opt), db.lc.reserveFileID()):
			case <-lc.HasBeenClosed():
				lc.Done()
				return
			}
		}
	}()
```

github.com/pingcap/badger@v1.5.1-0.20200908111422-2e78ee155d19/db.go:913
```go
func (db *DB) runFlushMemTable(c *y.Closer) error {
	defer c.Done()

	for ft := range db.flushChan {    <------- line 913
		if ft.mt == nil {
			return nil
		}
```

github.com/pingcap/badger@v1.5.1-0.20200908111422-2e78ee155d19/writer.go:141
```go
func (w *writeWorker) runWriteLSM(lc *y.Closer) {
	defer lc.Done()
	runtime.LockOSThread()
	for {
		t, ok := <-w.writeLSMCh      <------- line 141
		if !ok {
			close(w.mergeLSMCh)
			return
		}
		start := time.Now()
		w.writeLSM(t.reqs)
		w.metrics.WriteLSMDuration.Observe(time.Since(start).Seconds())
	}
}
```

github.com/pingcap/badger@v1.5.1-0.20200908111422-2e78ee155d19/writer.go:154
```go
func (w *writeWorker) runMergeLSM(lc *y.Closer) {
	defer lc.Done()
	for task := range w.mergeLSMCh {          <--------- line 154
		task.mt.MergeListToSkl()
		task.guard.Done()
	}
}
```

github.com/pingcap/badger@v1.5.1-0.20200908111422-2e78ee155d19/writer.go:73
```go
func (w *writeWorker) runFlusher(lc *y.Closer) {
	defer lc.Done()
	for {
		select {    <------ line 73
		case t := <-w.flushCh:
			start := time.Now()
			err := fileutil.Fdatasync(t.logFile)
			w.metrics.VlogSyncDuration.Observe(time.Since(start).Seconds())
			if err != nil {
				w.done(t.reqs, err)
				continue
			}
			w.writeLSMCh <- t
		case <-lc.HasBeenClosed():
			close(w.writeLSMCh)
			return
		}
	}
}
```

mod/github.com/pingcap/badger@v1.5.1-0.20200908111422-2e78ee155d19/writer.go:94

```go
func (w *writeWorker) runWriteVLog(lc *y.Closer) {
	defer lc.Done()
	for {
		var r *request
		select {    <------- line 94
		case task := <-w.ingestCh:
			w.ingestTables(task)
		case r = <-w.writeCh:
			reqs := make([]*request, len(w.writeCh)+1)
			reqs[0] = r
			w.pollWriteCh(reqs[1:])
			if err := w.writeVLog(reqs); err != nil {
				return
			}
		case <-lc.HasBeenClosed():
			w.closeWriteVLog()
			return
		}
	}
}

```

### 4. What is your TiDB version? (Required)
commit b8107d7e51d26a400d8ff0d6a64cf307e4485f19

These blocking issues might or might not directly caused by the usages of third party libraries, please take a look and redirect to the corresponding repository if possible, thanks.

**Comment by sticnarf** [comment] 2021-12-21 08:45
Sorry, I cannot reproduce this on the commit you told me and also cannot reproduce it on master. The test just runs successfully and exits.

Could you please try again with the latest master? Or does it require some special configurations?

**Comment by jebter** [comment] 2024-06-11 03:05
The issue has not been updated for too long, so I will close it. If there are any updates, you can reopen it.

**Closed by jebter** 2024-06-11 03:05 UTC
Labels: component/test, sig/transaction
