### ISSUE TITLE
Query execution failed.

### ISSUE THREAD

**Issue by Nickelth** [pingcap/tidb#55483] opened 2024-08-17 09:51 UTC
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```sql
CREATE TABLE t0(c0 BOOL UNSIGNED CHECK (((((66058967)^(false)))<(true))) NOT NULL DEFAULT false , c1 NUMERIC ZEROFILL NOT NULL , c2 TEXT(33) , c3 TINYINT ZEROFILL  AS (c0) VIRTUAL UNIQUE )PARTITION BY RANGE(c3) (PARTITION p0 VALUES LESS THAN (910),\nPARTITION p1 VALUES LESS THAN (1820),\nPARTITION p2 VALUES LESS THAN (2730),PARTITION p23 VALUES LESS THAN MAXVALUE);
INSERT IGNORE  INTO t0(c1, c0) VALUES (NULL, NULL);

SELECT t0.c1 FROM t0 WHERE '4' AND (t0.c3 IN (SELECT c3 FROM t0 WHERE t0.c3 BETWEEN 12877 AND 14560) AND t0.c3 IN (SELECT c3 FROM t0 WHERE t0.c3 BETWEEN 13650 AND 15255));
```

### 2. What did you expect to see? (Required)

query executed successfully.

### 3. What did you see instead (Required)

At first query executed successfully, but after waiting about 1 min, executing same SELECT statement reported:

```sql
mysql> SELECT t0.c1 FROM t0 WHERE '4' AND (t0.c3 IN (SELECT c3 FROM t0 WHERE t0.c3 BETWEEN 12877 AND 14560) AND t0.c3 IN (SELECT c3 FROM t0 WHERE t0.c3 BETWEEN 13650 AND 15255));
ERROR 1105 (HY000): Internal error, needPartitionHandle != ret, tp(1)
```

### 4. What is your TiDB version? (Required)
```sql
 Release Version: v8.3.0-alpha-50-gb59f5ecb47-dirty
Edition: Community
Git Commit Hash: b59f5ecb472d831f867b079e0a409caef9f4a290
Git Branch: master
UTC Build Time: 2024-07-31 18:41:32
GoVersion: go1.22.5
Race Enabled: false
Check Table Before Drop: false
Store: tikv 
```
tikv was set up with partitioned raft kv

**Comment by Defined2014** [comment] 2024-09-11 06:59
The error information is related with partition table. The partition handle is for global index.

And I think we already reimplement the logical for global index and I can't reproduce this issue in master branch and b59f5ecb472d831f867b079e0a409caef9f4a290 commit. So I decided to close this issue firstly. If you still have question, feel free to reopen it.

**Closed by Defined2014** 2024-09-11 06:59 UTC
Labels: type/bug, severity/moderate
