### ISSUE TITLE
Expression Syntax Error

### ISSUE THREAD

**Issue by Icemap** [pingcap/tidb#35307] opened 2022-06-11 16:53 UTC
## Bug Report

When I used an `Expression Syntax` the point of `Abstract Syntax Tree` will output by the error message.

### 1. Minimal reproduce step (Required)

```sql
DROP TABLE IF EXISTS testFULLTEXTSearchInnoDB;
CREATE TABLE testFULLTEXTSearchInnoDB (id INT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY, title VARCHAR(200), body TEXT, FULLTEXT (title , body)) ENGINE=InnoDB;
INSERT INTO testFULLTEXTSearchInnoDB (title, body) VALUES ('MySQL Tutorial','DBMS stands for DataBase ...'), ('How To Use MySQL Well','After you went through a ...'), ('Optimizing MySQL','In this tutorial we will show ...'), ('1001 MySQL Tricks','1. Never run mysqld as root. 2. ...'), ('MySQL vs. YourSQL','In the following database comparison ...'), ('MySQL Security','When configured properly, MySQL ...');
SELECT * FROM testFULLTEXTSearchInnoDB WHERE MATCH (title, body) AGAINST ('database' IN NATURAL LANGUAGE MODE);
```

### 2. What did you expect to see? (Required)

```sql
+----+-------------------+------------------------------------------+
| id | title             | body                                     |
+----+-------------------+------------------------------------------+
| 1  | MySQL Tutorial    | DBMS stands for DataBase ...             |
| 5  | MySQL vs. YourSQL | In the following database comparison ... |
+----+-------------------+------------------------------------------+
```

### 3. What did you see instead (Required)

```
(1105, 'UnknownType: *ast.MatchAgainst')
```

### 4. What is your TiDB version? (Required)

```sql
+------------------------------------------+
| VERSION()                                |
+------------------------------------------+
| 5.7.25-TiDB-v5.5.0-alpha-1165-g06737ecd2 |
+------------------------------------------+
```

**Comment by morgo** [comment] 2022-06-11 23:51
This is a duplicate of https://github.com/pingcap/tidb/issues/1793

**Closed by morgo** 2022-06-11 23:51 UTC
Labels: type/bug
