### ISSUE TITLE
<autogenerated>:testIsolationSuite.SetUpSuite failed

### ISSUE THREAD

**Issue by lilinghai** [pingcap/tidb#19263] opened 2020-08-18 09:21 UTC
:testIsolationSuite.SetUpSuite

```
[2020-08-17T08:14:03.145Z] ----------------------------------------------------------------------
[2020-08-17T08:14:03.145Z] FAIL: <autogenerated>:1: testIsolationSuite.SetUpSuite
[2020-08-17T08:14:03.145Z] 
[2020-08-17T08:14:03.145Z] session_test.go:198:
[2020-08-17T08:14:03.145Z]     c.Assert(err, IsNil)
[2020-08-17T08:14:03.145Z] ... value *errors.withStack = [privilege:8049]mysql.tables_priv ("[privilege:8049]mysql.tables_priv")
[2020-08-17T08:14:03.145Z] 

```

 Latest failed builds: 
https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tidb_ghpr_check_2/detail/tidb_ghpr_unit_test/45105/pipeline/38

**Comment by tiancaiamao** [comment] 2020-08-25 03:30
This  is caused by the environment.
PD is not available.

```
[2020/08/17 16:14:02.903 +08:00] [ERROR] [session.go:1434] ["active transaction fail"] [error="rpc error: code = Unknown desc = can not get timestamp, may be not leader"]
[errorVerbose="rpc error: code = Unknown desc = can not get timestamp, may be not leader
```

```
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1357
github.com/pingcap/errors.AddStack
	/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/pkg/mod/github.com/pingcap/errors@v0.11.5-0.20200729012136-4e113ddee29e/errors.go:174
github.com/pingcap/errors.Trace
	/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/pkg/mod/github.com/pingcap/errors@v0.11.5-0.20200729012136-4e113ddee29e/juju_adaptor.go:15
github.com/pingcap/tidb/store/tikv/oracle/oracles.(*tsFuture).Wait
	/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/store/tikv/oracle/oracles/pd.go:89
github.com/pingcap/tidb/session.(*txnFuture).wait
	/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/session/txn.go:371
github.com/pingcap/tidb/session.(*TxnState).changePendingToValid
	/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/session/txn.go:169
github.com/pingcap/tidb/session.(*session).Txn
	/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/session/session.go:1433
github.com/pingcap/tidb/executor.(*executorBuilder).getSnapshotTS
	/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/executor/builder.go:1336
github.com/pingcap/tidb/executor.buildNoRangeTableReader
	/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/executor/builder.go:2424
github.com/pingcap/tidb/executor.(*executorBuilder).buildTableReader
	/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/executor/builder.go:2478
github.com/pingcap/tidb/executor.(*executorBuilder).build
	/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/executor/builder.go:209
github.com/pingcap/tidb/executor.(*ExecStmt).buildExecutor
	/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/executor/adapter.go:705
github.com/pingcap/tidb/executor.(*ExecStmt).Exec
	/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/executor/adapter.go:315
github.com/pingcap/tidb/session.runStmt
	/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/session/session.go:1196
github.com/pingcap/tidb/session.(*session).ExecuteStmt
	/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/session/session.go:1161
github.com/pingcap/tidb/session.(*session).Execute
	/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/session/session.go:1074
github.com/pingcap/tidb/privilege/privileges.(*MySQLPrivilege).loadTable
	/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/privilege/privileges/cache.go:523
github.com/pingcap/tidb/privilege/privileges.(*MySQLPrivilege).LoadTablesPrivTable
	/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/privilege/privileges/cache.go:494
github.com/pingcap/tidb/privilege/privileges.(*MySQLPrivilege).LoadAll
	/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/privilege/privileges/cache.go:300
github.com/pingcap/tidb/privilege/privileges.(*Handle).Update
	/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/privilege/privileges/cache.go:1362
github.com/pingcap/tidb/domain.(*Domain).LoadPrivilegeLoop
	/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/domain/domain.go:845
github.com/pingcap/tidb/session.BootstrapSession
	/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/session/session.go:1786
github.com/pingcap/tidb/session_test.(*testSessionSuiteBase).SetUpSuite
	/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/session/session_test.go:197
reflect.Value.call
	/usr/local/go/src/reflect/value.go:460
reflect.Value.Call
	/usr/local/go/src/reflect/value.go:321
github.com/pingcap/check.(*suiteRunner).runFixture.func1
	/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:799
github.com/pingcap/check.(*suiteRunner).forkCall.func1
	/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:739
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1357
```

**Comment by tiancaiamao** [comment] 2020-08-27 16:07
@wjhuang2016   I remember you mentioned that PD fail to start is caused by port conflict?
So that fix also address this issue?

**Comment by wjhuang2016** [comment] 2020-08-27 16:51
> @wjhuang2016 I remember you mentioned that PD fail to start is caused by port conflict?
> So that fix also address this issue?

It's not caused by port conflict. I think this problem was fixed by https://github.com/pingcap/tidb/pull/19382

**Comment by tiancaiamao** [comment] 2020-10-09 02:05
There are no fails in this case recently, I guess it's already fixed, so I'd like to close it.

**Closed by tiancaiamao** 2020-10-09 02:05 UTC
Labels: component/test
