### ISSUE TITLE
Does tidb not support all MySQL 8.x features? Is there a support schedule?

### ISSUE THREAD

**Issue by canfeit** [pingcap/tidb#14699] opened 2020-02-09 00:45 UTC
Does tidb not support all MySQL 8.0 features?
Is there a support schedule?

**Comment by lonng** [comment] 2020-02-10 01:46
Hi, @canfeit, TiDB doesn't support all MySQL 8.0 features fully but most of the important features have been implemented, is there any unsupported feature you occurred in your POC?

**Comment by canfeit** [comment] 2020-02-10 09:44
@lonng, Are there any plans to support MySQL8 schema-less document store and NoSQL API.

**Comment by lonng** [comment] 2020-02-10 10:54
@canfeit Sorry, recently we should have no plans to support this feature.

**Comment by nullnotnil** [comment] 2020-07-23 19:14
You can track the progress of the MySQL X Protocol in https://github.com/pingcap/tidb/issues/1109

As @lonng indicated, there are no current plans to implement it.

**Comment by nullnotnil** [comment] 2020-08-06 22:18
I am going to close this issue as a duplicate of #1109. Please subscribe to updates in this issue to track the progress. Thanks!

**Closed by nullnotnil** 2020-08-06 22:18 UTC
Labels: type/duplicate, type/question
