### ISSUE TITLE
tidb panic with “err="runtime error: index out of range [17] with length 17"” when add and drop column

### ISSUE THREAD

**Issue by Lily2025** [pingcap/tidb#54254] opened 2024-06-27 01:06 UTC
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1、run tpcc
2、add and drop column

### 2. What did you expect to see? (Required)
no panic

### 3. What did you see instead (Required)
tidb panic
`[2024/06/26 16:50:08.323 +08:00] [ERROR] [conn.go:1024] ["connection running loop panic"] [conn=419434458] [session_alias=] [lastSQL="UPDATE stock SET s_quantity = ?, s_ytd = s_ytd + ?, s_order_cnt = s_order_cnt + 1, s_remote_cnt = s_remote_cnt + ? WHERE s_i_id = ? AND s_w_id = ? [arguments: (42, 9, 0, 24789, 2738)]"] [err="runtime error: index out of range [17] with length 17"] [stack="github.com/pingcap/tidb/pkg/server.(*clientConn).Run.func1\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/server/conn.go:1027\nruntime.gopanic\n\t/usr/local/go/src/runtime/panic.go:914\ngithub.com/pingcap/tidb/pkg/executor.(*Compiler).Compile.func1\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/executor/compiler.go:57\nruntime.gopanic\n\t/usr/local/go/src/runtime/panic.go:914\nruntime.goPanicIndex\n\t/usr/local/go/src/runtime/panic.go:114\ngithub.com/pingcap/tidb/pkg/planner/core.GetUpdateColumnsInfo\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/planner/core/logical_plan_builder.go:5849\ngithub.com/pingcap/tidb/pkg/planner/core.(*Update).buildTbl2UpdateColumns\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/planner/core/foreign_key.go:336\ngithub.com/pingcap/tidb/pkg/planner/core.(*Update).buildOnUpdateFKTriggers\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/planner/core/foreign_key.go:224\ngithub.com/pingcap/tidb/pkg/planner/core.buildPointUpdatePlan\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/planner/core/point_get_plan.go:1970\ngithub.com/pingcap/tidb/pkg/planner/core.tryUpdatePointPlan\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/planner/core/point_get_plan.go:1910\ngithub.com/pingcap/tidb/pkg/planner/core.TryFastPlan\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/planner/core/point_get_plan.go:923\ngithub.com/pingcap/tidb/pkg/planner.Optimize\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/planner/optimize.go:224\ngithub.com/pingcap/tidb/pkg/planner/core.generateNewPlan\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/planner/core/plan_cache.go:297\ngithub.com/pingcap/tidb/pkg/planner/core.GetPlanFromPlanCache\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/planner/core/plan_cache.go:246\ngithub.com/pingcap/tidb/pkg/planner.OptimizeExecStmt\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/planner/optimize.go:541\ngithub.com/pingcap/tidb/pkg/planner.Optimize\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/planner/optimize.go:163\ngithub.com/pingcap/tidb/pkg/executor.(*Compiler).Compile\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/executor/compiler.go:99\ngithub.com/pingcap/tidb/pkg/session.(*session).ExecuteStmt\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/session/session.go:2098\ngithub.com/pingcap/tidb/pkg/server.(*TiDBContext).ExecuteStmt\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/server/driver_tidb.go:294\ngithub.com/pingcap/tidb/pkg/server.(*clientConn).executePreparedStmtAndWriteResult\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/server/conn_stmt.go:306\ngithub.com/pingcap/tidb/pkg/server.(*clientConn).executePlanCacheStmt\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/server/conn_stmt.go:234\ngithub.com/pingcap/tidb/pkg/server.(*clientConn).handleStmtExecute\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/server/conn_stmt.go:225\ngithub.com/pingcap/tidb/pkg/server.(*clientConn).dispatch\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/server/conn.go:1386\ngithub.com/pingcap/tidb/pkg/server.(*clientConn).Run\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/server/conn.go:1125\ngithub.com/pingcap/tidb/pkg/server.(*Server).onConn\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/server/server.go:739"]`

### 4. What is your TiDB version? (Required)
./tidb-server -V
 Release Version: v8.2.0-alpha
Edition: Community
Git Commit Hash: 486995620a0efa69105a710ca2bab800e95bd937
Git Branch: heads/refs/tags/v8.2.0-alpha
UTC Build Time: 2024-06-25 11:46:19
GoVersion: go1.21.10
Race Enabled: false
Check Table Before Drop: false
Store: unistore
2024-06-26T16:22:33.898+0800

**Comment by crazycs520** [comment] 2024-06-27 07:21
According to the phenomenon, I feel that issue is the same as #48457, and another related issue is maybe #41622.

**Comment by lance6716** [comment] 2024-11-06 07:23
@crazycs520 Can we close this issue?

**Comment by crazycs520** [comment] 2024-11-13 08:31
This issue root cause is same with #53634

**Closed by crazycs520** 2024-11-13 08:31 UTC
Labels: type/bug, severity/major, component/ddl, affects-8.1, impact/panic, affects-8.2, affects-8.5
