### ISSUE TITLE
BR: PiTR unable to communicate with PD(etcd) via TLS

### ISSUE THREAD

**Issue by db-will** [pingcap/tidb#38775] opened 2022-10-31 20:57 UTC
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

use v6.2 br backup and restore data to new cluster

### 2. What did you expect to see? (Required)
should be able to restore data to new cluster successfully

### 3. What did you see instead (Required)
```
Detail BR log in /var/log/br.log Error: restore log from A_CURRENT_TIMESTAMP to A_PAST_TIMESTAMP, but the current existed log from A_PAST_TIMESTAMP to A_PAST_TIMESTAMP: [BR:Common:ErrInvalidArgument]invalid argument
```
A_PAST_TIMESTAMP are the same timestamp point

### 4. What is your TiDB version? (Required)

6.2

**Comment by db-will** [comment] 2022-10-31 20:58
@3pointer

**Comment by 3pointer** [comment] 2022-11-01 02:29
The root cause is checkpoint didn't moving forward.

And the reason of checkpoint didn't moving forward is TiKV didn't start watch task thread.
```
{"level":"WARN","caller":"errors.rs:135","message":"backup stream meet error","time":"xxx","err":"during connecting to the etcd: Etcd meet error transport error: transport error","context":"failed to start watch tasks"}
```

we should keep retrying to start the watch threads and I think we need add some check before we start log backup via br. @joccau

**Comment by YuJuncen** [comment] 2022-11-09 07:54
Do you using the client key with `SEC-1 EC` format? For now, tonic supports `PKCS #8` and `RSA` keys only.

You can use the following command to transform the `SEC-1 EC` key into `PKCS #8` key:

```bash
openssl pkcs8 -in $key -nocrypt -topk8 -out $key.pk8
```

And we can try to use the new generated key then.

**Comment by 3pointer** [comment] 2022-11-09 08:37
> Are you using the client key with `SEC1 EC` format? For now, tonic supports `PKCS #8` and `RSA` keys only.
> 
> You can use the following command to transform the `SEC-1 EC` key into `PKCS #8` key:
> 
> ```shell
> openssl pkcs8 -in $key -nocrypt -topk8 -out $key.pk8
> ```
> 
> And we can try to use the new generated key then.

please give more information about why tonic not support `SEC1 EC` keys

**Comment by YuJuncen** [comment] 2022-11-10 07:09
@3pointer Generally, it seems `ring` *doesn't support SEC1-formatted EC keys* for now (https://github.com/briansmith/ring/pull/1456 not yet merged), and `rustls` used a [workaround](https://github.com/rustls/rustls/pull/998/files) (Aha, which is almost exactly the openssl convert command did.), however it seems `tonic` [doesn't utilize the workaround for now](https://github.com/hyperium/tonic/issues/1143).

**Comment by 3pointer** [comment] 2022-11-15 03:53
It's more like these four DNS names `*.adhoc2-tidb-peer , *.adhoc2-ticdc-peer ,*.adhoc2-tikv-peer,*.adhoc2-pd-peer` cause webpki checks failed.  See the issue https://github.com/briansmith/webpki/issues/265. 

A workaround is remove these four names out of SAN in certificate.

**Comment by 3pointer** [comment] 2023-01-25 02:37
```
[2023/01/25 10:30:25.271 +08:00] [WARN] [errors.rs:155] ["backup stream meet error"] [verbose_err="Etcd(GRpcStatus(Status { code: Unknown, message: \"transport error\", source: Some(tonic::transport::Error(Transport, hyper::Error(Io, Custom { kind: Other, error: \"error:14094412:SSL routines:ssl3_read_bytes:sslv3 alert bad certificate:ssl/record/rec_layer_s3.c:1544:SSL alert number 42\" }))) }))"] [err="Etcd meet error grpc request error: status: Unknown, message: \"transport error\", details: [], metadata: MetadataMap { headers: {} }"] [context="failed to get backup stream task"]
```

**Closed** 2023-03-20 09:35 UTC
Labels: type/bug, severity/major, component/br, affects-6.5, affects-6.6, affects-7.0
