### ISSUE TITLE
support to create a table/database from `TableInfo`/`DbInfo`

### ISSUE THREAD

**Issue by 5kbpers** [pingcap/tidb#11916] opened 2019-08-28 10:05 UTC
## Feature Request

**Is your feature request related to a problem? Please describe:**

In backup&restore, we persist `TableInfo` & `DbInfo` to back up table/db schema, and then need to create a table/db from it when restoring data.

**Describe the feature you'd like:**

Because we will integrate restore function to tidb, it is better to expose a function to generate a Create Xxx SQL from `XxxInfo` firstly (which it is useful to our back&restore tool).
And we require to use `TableInfo`/`DbInfo` to create a table/db directly after we integrate restore to tidb, is there any way to achieve this currently?

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by 5kbpers** [comment] 2019-08-28 10:05
@zimulala PTAL

**Comment by zz-jason** [comment] 2020-07-22 05:37
@5kbpers Could you describe more about the problem and use case of this feature with some examples. I'm a little confused. For example:

> In backup&restore, we persist TableInfo & DbInfo to back up table/db schema, and then need to create a table/db from it when restoring data.

What does `TableInfo` and `DbInfo` mean, and where are they persisted?

> Because we will integrate restore function to tidb, it is better to expose a function to generate a Create Xxx SQL from XxxInfo firstly (which it is useful to our back&restore tool).

Why not persist the `create table` statement at first then use this statement to create the target table in the destination TiDB cluster?

**Comment by scsldb** [comment] 2020-08-27 06:55
`Create Table` with TableInfo looks like it would only be used for backup and recovery, data migration, and not a general purpose feature.

**Comment by IANTHEREAL** [comment] 2020-08-28 07:58
> expose a function to generate a Create Xxx SQL from XxxInfo firstly (which it is useful to our back&restore tool).

 TiDB has the function `ConstructResultOfShowCreateTable` 

> we require to use TableInfo/DbInfo to create a table/db directly after we integrate restore to tidb, is there any way to achieve this currently?

duplicate of https://github.com/pingcap/tidb/issues/15795

**Comment by 5kbpers** [comment] 2020-08-28 07:59
@zz-jason @scsldb  For now we do create table/db by constructing a create sql, and seems not any problem while we integrate to tidb, this issue will be closed.

**Closed by IANTHEREAL** 2020-08-28 07:58 UTC
Labels: feature/discussing, type/enhancement, type/feature-request
