### ISSUE TITLE
exception of syntactic/semantics check 

### ISSUE THREAD

**Issue by dbsid** [pingcap/tidb#27614] opened 2021-08-26 12:30 UTC
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

run the tpcc consistent check again the tpc-c dataset. With the extra space after count function, the query failed with semantics check.
```
benchmarksql@5.7.25-TiDB-v5.2.0-alpha-437-g0dd392976>set sql_mode="STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"
    -> ;
Query OK, 0 rows affected (0.00 sec)

benchmarksql@5.7.25-TiDB-v5.2.0-alpha-437-g0dd392976>(select o_w_id, o_d_id, sum(o_ol_cnt) from bmsql_oorder  group by o_w_id, o_d_id) except (select ol_w_id, ol_d_id, count (ol_o_id) from bmsql_order_line
group by ol_w_id, ol_d_id);
ERROR 1305 (42000): FUNCTION benchmarksql.count does not exist
```

### 2. What did you expect to see? (Required)
```
benchmarksql@5.7.25-TiDB-v5.2.0-alpha-437-g0dd392976>(select o_w_id, o_d_id, sum(o_ol_cnt) from bmsql_oorder  group by o_w_id, o_d_id) except (select ol_w_id, ol_d_id, count(ol_o_id) from bmsql_order_line group by ol_w_id, ol_d_id);
Empty set (4.96 sec)
```

### 3. What did you see instead (Required)
```
benchmarksql@5.7.25-TiDB-v5.2.0-alpha-437-g0dd392976>(select o_w_id, o_d_id, sum(o_ol_cnt) from bmsql_oorder  group by o_w_id, o_d_id) except (select ol_w_id, ol_d_id, count (ol_o_id) from bmsql_order_line
group by ol_w_id, ol_d_id);
ERROR 1305 (42000): FUNCTION benchmarksql.count does not exist
```

### 4. What is your TiDB version? (Required)

```

Release Version: v5.2.0-alpha-437-g0dd392976
Edition: Community
Git Commit Hash: 0dd39297677a835c19ec3cbeed67f88b451aba95
Git Branch: hz-poc-sharding
UTC Build Time: 2021-08-24 08:54:24
GoVersion: go1.16.6
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)
```

**Comment by zanmato1984** [comment] 2022-06-10 09:24
Moving to sig sql-infra.

**Comment by zimulala** [comment] 2022-06-14 13:03
@dbsid 
Please show us the table of `bmsql_oorder` and `bmsql_order_line`.

**Comment by zanmato1984** [comment] 2022-06-16 10:50
Minimal reproduce:

```
create table bmsql_order_line(ol_w_id int, ol_d_id int, ol_o_id int);
set sql_mode="STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION";
select ol_w_id, ol_d_id, count (ol_o_id) from bmsql_order_line
group by ol_w_id, ol_d_id;
ERROR 1305 (42000): FUNCTION test.count does not exist
```

**Comment by zanmato1984** [comment] 2022-06-16 10:51
> Looks that this bug is related to `except`:
> 
> ```
> tidb> (select o_w_id, o_d_id, sum(o_ol_cnt) from bmsql_oorder  group by o_w_id, o_d_id) union (select ol_w_id, ol_d_id, count (ol_o_id) from bmsql_order_line group by ol_w_id, ol_d_id);
> 
> ERROR 1146 (42S02): Table 'test.bmsql_oorder' doesn't exist
> ```
> 
> Mark it as 'sig/execution'.

No. Your error is `Table 'test.bmsql_oorder' doesn't exist`. You probably didn't even create that table?

**Comment by zanmato1984** [comment] 2022-06-16 13:41
OK, OK OK...

Seems the parse can't recognize agg functions with a little extra space between the function name and the subsequent `()`.

This is a perfectly valid query:
```
select ol_w_id, ol_d_id, count(ol_o_id) from bmsql_order_line group by ol_w_id, ol_d_id;
0 rows in set (0.00 sec)
```

This is the same query with an extra space between `count` and `(ol_o_id)` under `only_full_group_by` SQL mode:
```
set sql_mode="only_full_group_by";
select ol_w_id, ol_d_id, count (ol_o_id) from bmsql_order_line group by ol_w_id, ol_d_id;
ERROR 1055 (42000): Expression #3 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'test.bmsql_order_line.ol_o_id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by
```
The agg function `count` is recognized as a scalar function and its input `ol_o_id` is not in group by list, thus the error.

This is the same query with an extra space between `count` and `(ol_o_id)` under non-full-groupby SQL mode:
```
set sql_mode="";
select ol_w_id, ol_d_id, count (ol_o_id) from bmsql_order_line group by ol_w_id, ol_d_id;
ERROR 1305 (42000): FUNCTION test.count does not exist
```
The agg function `count` is recognized as a scalar function. Its input `ol_o_id` is permitted due to the specific SQL mode. And later the planner just finds there is no such scalar function `count`.

@zimulala

**Comment by YangKeao** [comment] 2022-09-23 07:39
@zanmato1984 @dbsid I don't know whether this is expected. This behavior is controlled by the `IGNORE_SPACE` sql mode. For example:

```sql
create table bmsql_order_line(ol_w_id int, ol_d_id int, ol_o_id int);
set sql_mode="STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION,IGNORE_SPACE";
select ol_w_id, ol_d_id, COUNT (ol_o_id) from bmsql_order_line group by ol_w_id,
 ol_d_id;
```

Will succeed. I found related logic here https://github.com/pingcap/tidb/blob/master/parser/misc.go#L970 : 

```go
        checkBtFuncToken := false
	if s.r.peek() == '(' {
		checkBtFuncToken = true
	} else if s.sqlMode.HasIgnoreSpaceMode() {
		s.skipWhitespace()
		if s.r.peek() == '(' {
			checkBtFuncToken = true
		}
	}
	if checkBtFuncToken {
		if tok := btFuncTokenMap[string(data)]; tok != 0 {
			return tok
		}
	}
	tok, ok := tokenMap[string(data)]
	if !ok && s.supportWindowFunc {
		tok = windowFuncTokenMap[string(data)]
	}
	return tok
```

Then if the sql mode doesn't contain `IGNORE_SPACE`, `count` is considered as an identifier.

**Comment by YangKeao** [comment] 2022-12-30 06:11
I think it's expected, and is compatible with MySQL? See:

```
mysql> (select o_w_id, o_d_id, sum(o_ol_cnt) from bmsql_oorder  group by o_w_id, o_d_id) except (select ol_w_id, ol_d_id, count (ol_o_id) from bmsql_order_line
    -> group by ol_w_id, ol_d_id);
ERROR 1630 (42000): FUNCTION test.count does not exist. Check the 'Function Name Parsing and Resolution' section in the Reference Manual

mysql> set sql_mode="IGNORE_SPACE";
Query OK, 0 rows affected (0.00 sec)

mysql> select ol_w_id, ol_d_id, COUNT (ol_o_id) from bmsql_order_line group by ol_w_id,  ol_d_id;
Empty set (0.00 sec)
```

See the document of [IGNORE_SPACE](https://dev.mysql.com/doc/refman/5.7/en/sql-mode.html#sqlmode_ignore_space) and [Function Name Parsing and Resolution](https://dev.mysql.com/doc/refman/5.7/en/function-resolution.html) for more information :thinking: .

I'd close this issue. If you have more comments / opinions on this behavior, feel free to comment or reopen this issue :heart: .

**Closed by YangKeao** 2022-12-30 06:11 UTC
Labels: type/bug, sig/sql-infra, severity/major, affects-6.0, affects-6.1, affects-6.2, affects-6.3, affects-6.4, affects-6.5
