### ISSUE TITLE
stats of an empty table is always pseudo even after analyzing

### ISSUE THREAD

**Issue by SunRunAway** [pingcap/tidb#15965] opened 2020-04-01 10:33 UTC
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. What did you do?

```
mysql> create table tzz(a int);
Query OK, 0 rows affected (0.01 sec)
mysql> analyze table tzz;
Query OK, 0 rows affected (0.01 sec)
mysql> desc select * from tzz;
+-----------------------+----------+-----------+---------------+--------------------------------+
| id          | estRows | task   | access object | operator info         |
+-----------------------+----------+-----------+---------------+--------------------------------+
| TableReader_5     | 10000.00 | root   |        | data:TableFullScan_4      |
| └─TableFullScan_4   | 10000.00 | cop[tikv] | table:tzz   | keep order:false, stats:pseudo |
+-----------------------+----------+-----------+---------------+--------------------------------+
2 rows in set (0.01 sec)
```

### 4. What version of TiDB are you using? (`tidb-server -V` or run `select tidb_version();` on TiDB)

master branch with commit 94fb1bf

**Comment by francis0407** [comment] 2020-04-02 02:32
Duplicate of #15581

**Closed by francis0407** 2020-04-02 02:32 UTC
Labels: component/statistics, type/bug
