### ISSUE TITLE
5.0.2 upgrade to 5.1.0, "sql analyze" in dashboard keep running, no result reported

### ISSUE THREAD

**Issue by seiya-annie** [pingcap/tidb#25419] opened 2021-06-15 07:19 UTC
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
check in tidb.log, can find:
[2021/06/15 15:12:24.327 +08:00] [ERROR] [select_result.go:389] ["invalid cop task execution summaries length"] [conn=35] [expected=2] [received=0]
[2021/06/15 15:12:32.258 +08:00] [INFO] [grpclogger.go:77] ["ccResolverWrapper: sending new addresses to cc: [{http://172.16.5.101:2379  <nil> 0 <nil>}]"] [system=grpc] [grpc_log=true]
[2021/06/15 15:12:32.264 +08:00] [ERROR] [select_result.go:389] ["invalid cop task execution summaries length"] [conn=51] [expected=2] [received=0]
[2021/06/15 15:12:32.691 +08:00] [INFO] [grpclogger.go:77] ["ccResolverWrapper: sending new addresses to cc: [{http://172.16.5.101:2379  <nil> 0 <nil>}]"] [system=grpc] [grpc_log=true]

### 4. What is your TiDB version? (Required)

| Release Version: v5.1.0-20210611
Edition: Community
Git Commit Hash: 29bfbb28437609d0a524b7b84e6920dc765978c7
Git Branch: heads/refs/tags/v5.1.0-20210611
UTC Build Time: 2021-06-11 07:52:09
GoVersion: go1.16.4
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false |
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)

**Comment by crazycs520** [comment] 2021-06-16 06:50
The cause is the TiDB config `tikv-client.grpc-compression-type = "gzip"`.

When set TiDB config to `tikv-client.grpc-compression-type = "gzip"`, query some `cluster_xxx` table will both return empty result set:

* CLUSTER_PROCESSLIST 
* CLUSTER_SLOW_QUERY
* CLUSTER_STATEMENTS_SUMMARY 
* CLUSTER_STATEMENTS_SUMMARY_HISTORY   

`tikv-client.grpc-compression-type` default value is `none`, and is imported in PR https://github.com/pingcap/tidb/pull/20438. So `v5.0.5` will also have this problem. 

@cfzjywxk PTAL

**Comment by cfzjywxk** [comment] 2021-08-31 08:10
Fixed by tikv/client-go#88 and related cherry-picks.

**Closed by cfzjywxk** 2021-08-31 08:10 UTC
Labels: type/bug, sig/transaction, severity/major
