### ISSUE TITLE
tidb panic in the recoverable goroutine invalied memory address or nil pointer dereference

### ISSUE THREAD

**Issue by asd80703406** [pingcap/tidb#47672] opened 2023-10-16 10:14 UTC
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
暂时无法知道如何复现
### 2. What did you expect to see? (Required)
tidb稳定运行。暂时无法升级到较新版本，希望能够知道根因，从而有一定的办法去规避问题发生。
### 3. What did you see instead (Required)
tidb 不定期发生重启
### 4. What is your TiDB version? (Required)
![image](https://github.com/pingcap/tidb/assets/6261813/f9e0b09a-c6c9-4806-865b-19e8126350d8)

集群：tidb cluster 三台虚拟机服务器，每台服务器运行tidb + tikv + PD
配置信息：24C 128G

tidb-stderr Log：
![image](https://github.com/pingcap/tidb/assets/6261813/03f82546-a3b3-4904-a7d6-3193741faaea)
![image](https://github.com/pingcap/tidb/assets/6261813/2ec9e2f1-7adf-49b5-8c9e-7ab426749e95)

tidb.log
![image](https://github.com/pingcap/tidb/assets/6261813/a7ccffb1-336a-4c25-8dd8-19248b7b7161)

![image](https://github.com/pingcap/tidb/assets/6261813/11fe049f-59bf-4b3b-9763-61dd67d8c758)

**Comment by zanmato1984** [comment] 2023-10-17 14:28
Hi,
I think there are two problems in this issue:

1) TiDB panic, corresponding to the message in your tidb.log ("panic in the recoverable goroutine").
2) TiDB crash (and the consequencing restart), corresponding to the message in your tidb-stderr.log.

From the information you supplied, they seem **independent**. In other words, it is **not** the panic causing the crash.

Regarding to the panic, it might be a known issue of https://github.com/pingcap/tidb/issues/30426, which is caused by a wrong plan of pipelined window function. To confirm that, you can find the query which uses a window function in your workload, see if it causes the error (panic, but supposingly it shouldn't crash TiDB). Then try turn this variable (https://docs.pingcap.com/tidb/stable/system-variables#tidb_enable_pipelined_window_function) to `OFF`, run the same query and see if the error is gone.

Regarding to the crash, not much useful information for us to tell the reason. Please attach a complete tidb-stderr.log then we can see what happened.

Thanks.

**Comment by zanmato1984** [comment] 2023-11-01 10:08
I'm closing this issue since we gave our analysis and didn't get feedback for a while. Feel free to reopen it if you have anything new.

Thanks.

**Closed by zanmato1984** 2023-11-01 10:08 UTC
Labels: type/bug, sig/execution, severity/minor, may-affects-5.3, may-affects-5.4, may-affects-6.1, may-affects-6.5, may-affects-7.1, may-affects-7.5
