### ISSUE TITLE
float incorrectly convert to bool in XOR

### ISSUE THREAD

**Issue by Illyrix** [pingcap/tidb#16677] opened 2020-04-21 12:15 UTC
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. What did you do?

execute `select 0.1 xor 0;`

### 2. What did you expect to see?

return 1

### 3. What did you see instead?

return 0:
mysql> select 0.1 xor 0;
+-----------+
| 0.1 xor 0 |
+-----------+
|         0 |
+-----------+

### 4. What version of TiDB are you using? (`tidb-server -V` or run `select tidb_version();` on TiDB)
5.7.25-TiDB-v4.0.0-beta.2-305-g94011e606

**Comment by SunRunAway** [comment] 2020-04-21 12:50
Duplicate of #12867

**Closed by SunRunAway** 2020-04-21 12:50 UTC
Labels: type/bug
