### ISSUE TITLE
Prepared statement  is not casting user variable correctly in TiDB.

### ISSUE THREAD

**Issue by ramanich1** [pingcap/tidb#31415] opened 2022-01-06 19:12 UTC
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```sql
drop table if exists t;
CREATE TABLE t (t_date DATETIME NULL);
PREPARE ps FROM 'INSERT INTO t SET t_date = NULLIF(?, '''')';
SET @t_date = NOW();
EXECUTE ps USING @t_date;
DEALLOCATE PREPARE ps;
```

### 2. What did you expect to see? (Required)
```sql
mysql> EXECUTE ps USING @t_date;
Query OK, 1 row affected (0.00 sec)
```
### 3. What did you see instead (Required)
```sql
mysql> EXECUTE ps USING @t_date;
ERROR 1292 (22007): Incorrect datetime value: ''
```
### 4. What is your TiDB version? (Required)

```sql
| Release Version: v5.4.0-alpha-264-g6efa36df6
Edition: Community
Git Commit Hash: 6efa36df6cff325106f67ecfe3d79816ba37ca6a
Git Branch: master
UTC Build Time: 2021-12-28 02:03:55
GoVersion: go1.17.2
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false |
```

**Comment by djshow832** [comment] 2022-01-07 08:03
It isn't related to plan-cache because as described in the steps, the plan cache is not used. @tiancaiamao

**Comment by yudongusa** [comment] 2022-01-07 09:00
@tiancaiamao @ramanich1 please verify if plan cache is used or not.

**Comment by winoros** [comment] 2022-01-07 09:38
```
mysql> select nullif(now(), '');
+---------------------+
| nullif(now(), '')   |
+---------------------+
| 2022-01-07 17:37:31 |
+---------------------+
1 row in set, 1 warning (0.00 sec)
```

Seems that there's an unnecessary truncate error happened inside the NULLIF.

Transfer to expr side.

**Comment by winoros** [comment] 2022-01-07 09:39
There should be the workaround that we don't use strict mode in the SQL mode.

**Comment by ramanich1** [comment] 2022-01-07 19:18
> @tiancaiamao @ramanich1 please verify if plan cache is used or not.
@tiancaiamao
This is to confirm that plan cache is not used .Select @@last_plan_from_cache =0

**Comment by zanmato1984** [comment] 2022-05-16 07:26
Handling to planner as this seems a problem during compile.

**Comment by Yisaer** [comment] 2022-07-08 07:53
For both mysql 5.7 and 8.0, the behavior like following:
```sql
MySQL [test]> CREATE TABLE t (t_date DATETIME NULL);
Query OK, 0 rows affected (0.00 sec)

MySQL [test]> PREPARE ps FROM 'INSERT INTO t SET t_date = NULLIF(?, '''')';
UTE ps USING @t_date;Query OK, 0 rows affected (0.01 sec)
Statement prepared

MySQL [test]> SET @t_date = NOW();
Query OK, 0 rows affected (0.00 sec)

MySQL [test]> EXECUTE ps USING @t_date;
Query OK, 1 row affected (0.01 sec)

MySQL [test]> INSERT INTO t SET t_date = NULLIF(NOW(), '''');
ERROR 1292 (22007): Incorrect datetime value: ''' for column 'NOW()' at row 1
```

In tidb, as `STRICT_TRANS_TABLES` is enabled by default in sql_mode, the behavior described in the issue is expected.

If you want to execute the query successfully instead of returning error, you should do it like fowllowing:

```sql
mysql> SET SESSION sql_mode = 'ANSI';
Query OK, 0 rows affected (0.00 sec)

mysql> PREPARE ps FROM 'INSERT INTO t SET t_date = NULLIF(?,''hhh'')';
Query OK, 0 rows affected (0.01 sec)

mysql> SET @t_date = NOW();
Query OK, 0 rows affected (0.00 sec)

mysql> EXECUTE ps USING @t_date;
Query OK, 1 row affected, 1 warning (0.00 sec)
```

In other word, The current behavior is expected instead of a bug.

**Comment by Yisaer** [comment] 2022-07-11 03:19
I will close this issue as the behavior is expected as I described above, feel free to comment if you have any problem.

**Closed by Yisaer** 2022-07-11 03:19 UTC
Labels: type/bug, sig/planner, severity/major, affects-5.4, affects-6.0, affects-6.1
