### ISSUE TITLE
tidb cannot modify column null to null, the reverse is ok

### ISSUE THREAD

**Issue by ljhmily** [pingcap/tidb#9522] opened 2019-03-01 08:33 UTC
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
ALTER TABLE `test`.`employees` 
MODIFY COLUMN `id` int(11) NOT NULL FIRST;

2. What did you expect to see?
success

3. What did you see instead?
1105 - unsupported modify column null to not nulll

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
Release Version: v2.1.5-1-g0bd6b1b
Git Commit Hash: 0bd6b1b60816bf8a2022e657d7a472311548d82e
Git Branch: release-2.1
UTC Build Time: 2019-02-28 08:17:03
GoVersion: go version go1.11.2 linux/amd64
Race Enabled: false
TiKV Min Version: 2.1.0-alpha.1-ff3dd160846b7d1aed9079c389fc188f7f5ea13e
Check Table Before Drop: false

**Comment by XuHuaiyu** [comment] 2019-03-01 08:42
hi, @ljhmily , I can not reproduce your problem.
Can you provide us the result of `show create table test.employees`

**Comment by ljhmily** [comment] 2019-03-07 10:28
mysql> ALTER TABLE test.employees
    -> MODIFY COLUMN id int(11) NOT NULL FIRST;
ERROR 1105 (HY000): unsupported modify column null to not null

not null to null is ok, reverse not

CREATE TABLE `employees` (
  `id` int(11) DEFAULT NULL,
  `fname` varchar(30) DEFAULT NULL,
  `separated` date DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin
PARTITION BY RANGE ( year(`separated`) ) (
  PARTITION p0 VALUES LESS THAN (1991),
  PARTITION p1 VALUES LESS THAN (1996),
  PARTITION p2 VALUES LESS THAN (2001),
  PARTITION p3 VALUES LESS THAN (2003)
)

**Comment by crazycs520** [comment] 2019-03-07 11:36
@ljhmily , 2.1.5 not support change column from null to not null, Currently only master version support this.

**Comment by ljhmily** [comment] 2019-03-14 06:57
when will this feature be released?

**Comment by nullnotnil** [comment] 2020-07-23 17:02
I can confirm that this has been fixed. Here is a full test case:

 ```sql
DROP TABLE IF EXISTS t1;
CREATE TABLE t1 (
 id INT NOT NULL PRIMARY KEY auto_increment,
 b INT NULL,
 c INT NULL
);

INSERT INTO t1 VALUES (1, 1, NULL);
ALTER TABLE t1 MODIFY COLUMN b INT NOT NULL;
SHOW CREATE TABLE t1\G
ALTER TABLE t1 MODIFY COLUMN c INT NOT NULL;
SHOW CREATE TABLE t1\G
```

TiDB 2.1 behavior:

```sql
mysql> ALTER TABLE t1 MODIFY COLUMN b INT NOT NULL;
ERROR 1105 (HY000): unsupported modify column null to not null
mysql> SHOW CREATE TABLE t1\G
*************************** 1. row ***************************
       Table: t1
Create Table: CREATE TABLE `t1` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `b` int(11) DEFAULT NULL,
  `c` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin AUTO_INCREMENT=30002
1 row in set (0.00 sec)

mysql> ALTER TABLE t1 MODIFY COLUMN c INT NOT NULL;
ERROR 1105 (HY000): unsupported modify column null to not null
mysql> SHOW CREATE TABLE t1\G
*************************** 1. row ***************************
       Table: t1
Create Table: CREATE TABLE `t1` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `b` int(11) DEFAULT NULL,
  `c` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin AUTO_INCREMENT=30002
1 row in set (0.00 sec)
```

Behavior in master:
```sql
mysql> ALTER TABLE t1 MODIFY COLUMN b INT NOT NULL;
Query OK, 0 rows affected (0.14 sec)

mysql> SHOW CREATE TABLE t1\G
*************************** 1. row ***************************
       Table: t1
Create Table: CREATE TABLE `t1` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `b` int(11) NOT NULL,
  `c` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin AUTO_INCREMENT=30002
1 row in set (0.00 sec)

mysql> ALTER TABLE t1 MODIFY COLUMN c INT NOT NULL;
ERROR 1138 (22004): Invalid use of NULL value
mysql> SHOW CREATE TABLE t1\G
*************************** 1. row ***************************
       Table: t1
Create Table: CREATE TABLE `t1` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `b` int(11) NOT NULL,
  `c` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin AUTO_INCREMENT=30002
1 row in set (0.00 sec)
```

The second ALTER TABLE fails because there is an existing NULL value, but the error is the same as in MySQL:

```sql
mysql [localhost:8021] {msandbox} (test) > ALTER TABLE t1 MODIFY COLUMN c INT NOT NULL;
ERROR 1138 (22004): Invalid use of NULL value
```

I am going to close this issue now, but please feel free to reopen if you have further questions. Thanks!

**Closed by nullnotnil** 2020-07-23 17:02 UTC
Labels: type/question
