### ISSUE TITLE
5.0.0 upgrade to 5.0.1-pre, report "table reader fetch next chunk failed"

### ISSUE THREAD

**Issue by seiya-annie** [pingcap/tidb#24148] opened 2021-04-20 03:53 UTC
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1. upgrade cluster from v5.0.0 to 5.0.1
2. get  the following errorsin tidb.log
[2021/04/20 11:34:44.347 +08:00] [WARN] [coprocessor.go:882] ["other error"] [txnStartTS=424382217400877073] [regionID=61] [storeAddr=172.16.4.139:20160] [error="other error: default not found: key:7480000000000000175F72800000000000EADE, maybe read truncated/dropped table data?"]
[2021/04/20 11:34:47.579 +08:00] [WARN] [coprocessor.go:882] ["other error"] [txnStartTS=424382218252845077] [regionID=61] [storeAddr=172.16.4.139:20160] [error="other error: default not found: key:7480000000000000175F72800000000000EADE, maybe read truncated/dropped table data?"]
[2021/04/20 11:34:47.579 +08:00] [ERROR] [distsql.go:1097] ["table reader fetch next chunk failed"] [error="other error: default not found: key:7480000000000000175F72800000000000EADE, maybe read truncated/dropped table data?"]

### 2. What did you expect to see? (Required)
no error
### 3. What did you see instead (Required)
[2021/04/20 11:34:47.579 +08:00] [ERROR] [distsql.go:1097] ["table reader fetch next chunk failed"] [error="other error: default not found: key:7480000000000000175F72800000000000EADE, maybe read truncated/dropped table data?"]

### 4. What is your TiDB version? (Required)

| Release Version: v5.0.1
Edition: Community
Git Commit Hash: 4141f837ad4655a567119db743b7b752a95f5aa2
Git Branch: heads/refs/tags/v5.0.1
UTC Build Time: 2021-04-17 04:28:49
GoVersion: go1.13
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)

MySQL [(none)]>

**Comment by wjhuang2016** [comment] 2021-06-18 07:16
The root cause is the same as https://github.com/tikv/tikv/issues/10353, so I closed this issue now.

**Closed** 2021-06-18 07:16 UTC
Labels: severity/major, type/bug, type/duplicate
