### ISSUE TITLE
infoschemaV2's lifetime is limited and may cause statistics wrongly deleted

### ISSUE THREAD

**Issue by winoros** [pingcap/tidb#57994] opened 2024-12-04 14:00 UTC
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

In a big cluster testing, the `StatsCacheImpl.Update` may execute more than 20 minutes in current situation.
It may exceeds the valid lifetime of the infoschema and raise the fake error which tells that a table doesn't exist.

It's a dangerous behavior for statistics because stats needs the infoschema to decide whether a table exists or not.
The fake error may cause the stats of a table wrongly deleted.

### 4. What is your TiDB version? (Required)

current master

**Comment by Rustin170506** [comment] 2024-12-09 03:57
duplicate of https://github.com/pingcap/tidb/issues/57952

**Closed by Rustin170506** 2024-12-09 03:57 UTC
Labels: type/bug, sig/planner, severity/major, affects-8.5
