### ISSUE TITLE
Error when updating the same row by calling different instance of tidb

### ISSUE THREAD

**Issue by cberescu** [pingcap/tidb#19417] opened 2020-08-24 17:10 UTC
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

I am using tidb as a session holder for users , this happens when i update a row multiple times very fast. I am using 2 tidb instances and proxysql that can send the request to either instance.  

### 2. What did you expect to see? (Required)
To not receive any errors. 

### 3. What did you see instead (Required)

SQLSTATE[HY000]: General error: 9007 Write conflict, txnStartTS=418981749670543365, conflictStartTS=418981749591900161, conflictCommitTS=418981749814722561, key={tableID=291, handle=3339451} primary={tableID=291, indexID=2, indexValues={1848500256434552832, 3339451, }} [try again later]

### 4. What is your TiDB version? (Required)
tidb_version(): Release Version: v4.0.3
Edition: Community
Git Commit Hash: 0529b1b493e46aae71bbe34cbe24515a2eb1b47c
Git Branch: heads/refs/tags/v4.0.3
UTC Build Time: 2020-07-24 12:06:35
GoVersion: go1.13
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
1 row in set (0.00 sec)

**Comment by nullnotnil** [comment] 2020-08-24 21:26
I believe I understand why it is happening. To reproduce I started 9 additional copies of tidb-server so that I have 10 running locally:

```bash
for i in {1..9}; do
 ./bin/tidb-server --store=tikv --path="127.0.0.1:2379" -P 400$i -status 1008$i &
done;
```

I then created a hyopothetical table:
```sql
DROP TABLE IF EXISTS users;
CREATE TABLE users (
 id INT NOT NULL PRIMARY KEY auto_increment,
 username VARCHAR(100) NOT NULL,
 login_count INT DEFAULT '0',
 INDEX (username)
);

INSERT INTO users (username) VALUES ('a'), ('b'), ('c'), ('d'), ('e'), ('f');
```

My load script is as follows:
```bash
#!/bin/bash
# generate-load.sh PORT

PORT=$1
echo "Starting load thread to MySQL on Port $PORT";

for i in {1..100}; do 
 mysql -P $PORT test -e "UPDATE users SET login_count = login_count +1 WHERE username='c'" || exit "An update statement failed!!!"
 echo -n ".";
done;
```

So I can create the 10 threads with:
```bash
for i in {0..9}; do
 ./generate-load.sh 400$i &
done;
```

Which generates warnings of:
```
[2020/08/24 15:11:02.668 -06:00] [WARN] [session.go:464] [sql] [conn=1164] [label=general] [error="[kv:9007]Write conflict, txnStartTS=418985662858919948, conflictStartTS=418985662872027150, conflictCommitTS=418985662872027151, key={tableID=49, handle=3} primary={tableID=49, handle=3} [try again later]"] [txn="Txn{state=invalid}"]
[2020/08/24 15:11:02.668 -06:00] [WARN] [session.go:663] [retrying] [conn=1164] [schemaVersion=25] [retryCnt=0] [queryNum=0] [sql="UPDATE users SET login_count = login_count +1 WHERE username='c'"]
[2020/08/24 15:11:02.672 -06:00] [INFO] [2pc.go:717] ["2PC clean up done"] [conn=1164] [txnStartTS=418985662858919948]
[2020/08/24 15:11:02.675 -06:00] [WARN] [session.go:681] ["transaction association"] [conn=1164] ["retrying txnStartTS"=418985662911348737] ["original txnStartTS"=418985662858919948]
```

## Suspected Cause

Even though the default transaction model is pessimistic locking, optimistic locking is used for autocommit statements. This is mentioned under (5) here: https://docs.pingcap.com/tidb/stable/pessimistic-transaction#difference-with-mysql-innodb

But, what is also happening in my case is the statements are successfully being retried, because it is safe to do so for autocommit statements. We can see this because I never received a client error message about statement-failed:

```
nullnotnil@ubuntu:~/bugs$ for i in {0..9}; do  ./generate-load.sh 400$i & done;
[1] 294567
[2] 294568
[3] 294569
[4] 294570
[5] 294571
[6] 294572
[7] 294573
[8] 294574
[9] 294575
[10] 294576
Starting load thread to MySQL on Port 4000
nullnotnil@ubuntu:~/bugs$ Starting load thread to MySQL on Port 4004
Starting load thread to MySQL on Port 4003
Starting load thread to MySQL on Port 4002
Starting load thread to MySQL on Port 4001
Starting load thread to MySQL on Port 4005
Starting load thread to MySQL on Port 4006
Starting load thread to MySQL on Port 4007
Starting load thread to MySQL on Port 4008
Starting load thread to MySQL on Port 4009
........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
[1]   Done                    ./generate-load.sh 400$i
[2]   Done                    ./generate-load.sh 400$i
[3]   Done                    ./generate-load.sh 400$i
[4]   Done                    ./generate-load.sh 400$i
[5]   Done                    ./generate-load.sh 400$i
[6]   Done                    ./generate-load.sh 400$i
[7]   Done                    ./generate-load.sh 400$i
[8]   Done                    ./generate-load.sh 400$i
[9]-  Done                    ./generate-load.sh 400$i
[10]+  Done                    ./generate-load.sh 400$i
```

When I change the test script to use `START TRANSACTION; UPDATE users SET login_count = login_count +1 WHERE username='c'; COMMIT;` it is a lot less noisy, because with pessimistic transactions the conflicts are only shown at debug verbosity (fixed in https://github.com/pingcap/tidb/pull/18365).

My proposal would be to change the debug level of retryable conflicts from warn -> debug.

@cberescu Did I understand this right? If you are receiving client errors, that means that the number of retries is being exceeded. You could try [increasing the retry count](https://docs.pingcap.com/tidb/stable/optimistic-transaction#automatic-retry), or explicitly forcing pessimistic locking by wrapping statements in a transaction. This may help as optimistic works best when the conflict rate is low.

**Comment by nullnotnil** [comment] 2020-08-24 21:31
@jackysp @cfzjywxk Do you agree with the analysis here / what do you think about changing the log level for safe retry of optimistic transactions?

**Comment by cfzjywxk** [comment] 2020-08-25 02:31
> @jackysp @cfzjywxk Do you agree with the analysis here / what do you think about changing the log level for safe retry of optimistic transactions?
@nullnotnil 
I think the analysis is correct, for conflict rows updating it's better to use the pessimistic transaction mode which requires explicit `begin` or `start transaction`.
If the commit retry is enabled for a non-autocommit transaction with optimistic transaction mode, the commit retry may change the transaction isolation level. I think we still need to trace it, how about changing the `WARN` log level into `INFO`.

@jackysp What do you think.

**Comment by cberescu** [comment] 2020-08-25 08:31
@nullnotnil yes, i receive client errors i could also duplicate with only one instance of tidb. I will try to enable automatic retry and see what happens.

**Comment by cberescu** [comment] 2020-08-25 16:46
So, after enabling autoretry and increasing tidb_retry_limit to 30  i still receive the errors. My next step will be to use BEGIN TRANSACTION and see what happens.

**Comment by nullnotnil** [comment] 2020-08-27 18:19
@cberescu Thanks for the update. Pessimistic is a better fit when you have this many conflicts.

With optimistic, it is more expensive in the case of a conflict because it actually incurs the cost of making the changes before discovering the conflict. Pessimistic acquires the locks before attempting to make the changes, and if it doesn't acquire the lock it won't make the change (which should be cheaper).

**Comment by nullnotnil** [comment] 2020-11-05 16:47
There is a behavior change in TiDB 4.0.6 which should help resolve this issue. See: https://github.com/pingcap/tidb/pull/19796

Autocommit transactions will now switch to pessimistic for retries. This is mentioned in the release notes, but updates to the documentation are pending in https://github.com/pingcap/docs/pull/4165

**Closed** 2021-01-12 08:47 UTC
Labels: type/question
