### ISSUE TITLE
upgrade fail from v4.0.15 to v4.0.16 

### ISSUE THREAD

**Issue by seiya-annie** [pingcap/tidb#30603] opened 2021-12-10 04:10 UTC
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

install v4.0.15 , upgrade to v4.0.16

### 2. What did you expect to see? (Required)
upgrade success

### 3. What did you see instead (Required)
[2021/12/10 12:07:51.950 +08:00] [INFO] [manager.go:188] ["start campaign owner"] [ownerInfo="[bindinfo] /tidb/bindinfo/owner"]
[2021/12/10 12:07:51.956 +08:00] [ERROR] [distsql.go:1048] ["inconsistent index handles"] [index=PRIMARY] [index_cnt=1] [table_cnt=0] [missing_handles="[612489562207289345]"] [total_handles="[612489562207289345]"]
[2021/12/10 12:07:51.956 +08:00] [WARN] [cache.go:310] ["load mysql.db fail"] [error="inconsistent index PRIMARY handle count 1 isn't equal to value count 0"]
[2021/12/10 12:07:51.956 +08:00] [FATAL] [terror.go:256] ["unexpected error"] [error="[privilege:8049]mysql.db"] [stack="github.com/pingcap/parser/terror.MustNil\n\t/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/pkg/mod/github.com/pingcap/parser@v0.0.0-20210421190550-451a84cf120a/terror/terror.go:256\nmain.createStoreAndDomain\n\t/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/tidb-server/main.go:259\nmain.main\n\t/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/tidb-server/main.go:179\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:203"] [stack="github.com/pingcap/parser/terror.MustNil\n\t/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/pkg/mod/github.com/pingcap/parser@v0.0.0-20210421190550-451a84cf120a/terror/terror.go:256\nmain.createStoreAndDomain\n\t/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/tidb-server/main.go:259\nmain.main\n\t/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/tidb-server/main.go:179\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:203"]
~        
### 4. What is your TiDB version? (Required)

 ["Git Commit Hash"=75f81d2d7faae72575c4e471ec0b96756796284a]

**Comment by seiya-annie** [comment] 2021-12-10 04:12
[tidb.log](https://github.com/pingcap/tidb/files/7690082/tidb.log)

**Comment by seiya-annie** [comment] 2021-12-10 04:44
cluster info please find in:  https://clinic.pingcap.com:4433/diag/files?uuid=386a8fb8ce979d77-8d9c239d502fb376-d1d311cfa29069de

**Comment by seiya-annie** [comment] 2021-12-10 06:03
minor reproduce steps:
1. enable_streaming: true
2. create role r1;  grant lock tables on t.* TO 'r1'@'%';
3. upgrade to v4.0.16

**Comment by morgo** [comment] 2021-12-10 15:17
Advice for whoever fixes this:

If you need to use a bootstrap task to modify the table, be careful not to just take the next number along (`upgradeToVer53`). This is because bootstrap numbers are shared across all versions, so you will prevent that task from running if someone eventually upgrades to a newer version, leading to an inconsistent state.

What you instead need to do is se e if you can merge the changes you need to do with the existing `upgradeToVer53` from a later version, and make `upgradeToVer53`  work in TiDB 4.0. In this case it looks like this is possible:

```
func upgradeToVer53(s Session, ver int64) {
	if ver >= version53 {
		return
	}
	// when upgrade from old tidb and no `tidb_enable_strict_double_type_check` in GLOBAL_VARIABLES, init it with 1`
	sql := fmt.Sprintf("INSERT IGNORE INTO %s.%s (`VARIABLE_NAME`, `VARIABLE_VALUE`) VALUES ('%s', '%d')",
		mysql.SystemDB, mysql.GlobalVariablesTable, variable.TiDBEnableStrictDoubleTypeCheck, 0)
	mustExecute(s, sql)
}
```

There is no harm in running that SQL in TIDB 4.0.

**Comment by morgo** [comment] 2021-12-15 17:03
@seiya-annie I took a look at this, but I can not reproduce :(

I don't think this relates to `enable-streaming`, but it is quite possible that the role `r1` is related. But I think it is not a change between v4.0.15 and v4.0.16 because there are no bootstrap tasks which change the schema definition:

```
$ git diff v4.0.15..upstream/release-4.0 --stat | grep "bootstrap\|privilege"
 privilege/privileges/privileges_test.go     |  11 ++
```


Is it possible it could be an install based on an earlier version? It looks like 4.0.13 introduced some changes to bootstrap to handle our messy bootstrap numbering, but it could have bugs.

**Comment by Defined2014** [comment] 2023-05-06 02:53
I don't think this issue will be updated anymore, so close it first.

**Closed by Defined2014** 2023-05-06 02:53 UTC
Labels: type/bug, sig/sql-infra, severity/major, affects-4.0, affects-6.0, affects-6.1, affects-6.2, affects-6.3, affects-6.4, affects-6.5, affects-6.6, affects-7.0, affects-7.1
