### ISSUE TITLE
Suppress log level for "Unsupported collation when new collation is enabled" message

### ISSUE THREAD

**Issue by borissavelev** [pingcap/tidb#38317] opened 2022-10-07 17:16 UTC
## Feature Request

**Is your feature request related to a problem? Please describe:**
Some clients (like proxysql monitor thread) unfortunately have no way to configure collation. And always set up default from mariadb/mysql client library `latin1_swedish_ci`.
This leads to log flood:

`[2022/10/07 17:14:06.056 +00:00] [WARN] [collate.go:222] ["[ddl:1273]Unsupported collation when new collation is enabled: 'latin1_swedish_ci'"]`

```sh
grep latin1_swedish_ci /tidb-deploy/tidb-3306/log/tidb.log |wc -l
1334274
```

**Describe the feature you'd like:**
Change log level for this message

**Describe alternatives you've considered:**
Remove warning completely 

**Teachability, Documentation, Adoption, Migration Strategy:**
https://github.com/sysown/proxysql/blob/f0799a43d8145ae3d138d7bc512581b2433df732/deps/mariadb-client-library/mariadb_lib.c.collation.patch

https://github.com/sysown/proxysql/blob/f0799a43d8145ae3d138d7bc512581b2433df732/lib/MySQL_Monitor.cpp#L1167

**Comment by yiwen92** [comment] 2022-10-10 08:40
I think it should put out some warning messages to remind users about the unsupport collation issue was happened, because it will be useful for further debug.

**Comment by dveeden** [comment] 2022-11-07 16:00
Isn't this a duplicate of https://github.com/pingcap/tidb/issues/36057 ?

**Comment by xhebox** [comment] 2022-11-08 03:03
> Isn't this a duplicate of #36057 ?

Oh, indeed. Maybe we can close this issue.

**Closed** 2022-11-08 06:09 UTC
Labels: type/enhancement
