### ISSUE TITLE
how to get record counts?

### ISSUE THREAD

**Issue by DavisLinDB** [pingcap/tidb#3303] opened 2017-05-19 01:54 UTC
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

I want to know how many records in a table which should be 500+millions records.
I use 2 methods to count.
1. 
select count(1) from testdata;
ERROR 1105 (HY000): [try again later]: backoffer.maxSleep 15000ms is exceeded, errors:
stale_epoch:<> 
send tikv request error: read tcp 10.140.0.8:60374->10.140.0.5:20160: i/o timeout, ctx: region_id:26325 region_epoch
:<conf_ver:3 version:1294 > peer:<id:26326 store_id:1 > , try next peer later
stale_epoch:<> 

What's problem and how to fix?

2.
select * FROM INFORMATION_SCHEMA.TABLES where TABLE_SCHEMA = 'test';
+---------------+--------------+------------+------------+--------+---------+------------+------------+-------------
---+-------------+-----------------+--------------+-----------+----------------+-------------+-------------+--------
----+-------------------+-----------+----------------+---------------+
| TABLE_CATALOG | TABLE_SCHEMA | TABLE_NAME | TABLE_TYPE | ENGINE | VERSION | ROW_FORMAT | TABLE_ROWS | AVG_ROW_LENG
TH | DATA_LENGTH | MAX_DATA_LENGTH | INDEX_LENGTH | DATA_FREE | AUTO_INCREMENT | CREATE_TIME | UPDATE_TIME | CHECK_T
IME | TABLE_COLLATION   | CHECK_SUM | CREATE_OPTIONS | TABLE_COMMENT |
+---------------+--------------+------------+------------+--------+---------+------------+------------+-------------
---+-------------+-----------------+--------------+-----------+----------------+-------------+-------------+--------
----+-------------------+-----------+----------------+---------------+
| def           | test         | testdata   | BASE TABLE | InnoDB |      10 | Compact    |          0 |             
 0 |       16384 |               0 |            0 |         0 |           NULL | NULL        | NULL        | NULL   
    | latin1_swedish_ci |      NULL |                |               |
| def           | test         | sequence   | BASE TABLE | InnoDB |      10 | Compact    |          0 |             
 0 |       16384 |               0 |            0 |         0 |           NULL | NULL        | NULL        | NULL   
    | latin1_swedish_ci |      NULL |                |               |
| def           | test         | sequenceK  | BASE TABLE | InnoDB |      10 | Compact    |          0 |             
 0 |       16384 |               0 |            0 |         0 |           NULL | NULL        | NULL        | NULL   
    | latin1_swedish_ci |      NULL |                |               |

INFORMATION_SCHEMA.TABLES return wrong result.
sequenceK has 1000 records.
testdata has 500+ millions records

2. What did you expect to see?
how many records in a table.

3. What did you see instead?
error message.

4. What version of TiDB are you using (`tidb-server -V`)?
2017/05/17 04:24:38 printer.go:32: [info] Version:
2017/05/17 04:24:38 printer.go:33: [info] Git Commit Hash: b2a7b87
2017/05/17 04:24:38 printer.go:34: [info] UTC Build Time: 2017-05-13 04:52:43

**Comment by ngaut** [comment] 2017-05-23 23:27
Thank you for your report. Could you post the log of tikv-server?

**Comment by DavisLinDB** [comment] 2017-05-24 02:26
@ngaut 

sorry, i don't keep the log that time...

**Comment by ngaut** [comment] 2017-05-24 02:57
That's OK, Could you reproduce the issue ?

**Comment by DavisLinDB** [comment] 2017-05-24 07:10
@ngaut

I fill in a testdata table by the statement:
insert Into testdata (id, cid, agold,bgold,adddate)
select UUID() as uuid,cast(rand()*100000 as SIGNED) as cid,cast(rand()*10000000 as SIGNED ) as agold,cast(rand()*10000000 as SIGNED ) as bgold, DATE_ADD("2016-01-01", INTERVAL RAND() * 364 DAY) as adddate from sequencek a , sequencek b limit 50000;

insert 50000 records one time.
I make a loop to generate and count at the same time.
TiKV shows lots of message, I cann't know which is correct log.

**Comment by nullnotnil** [comment] 2020-07-10 16:05
Hi! I am going to close this issue due to staleness, but please feel free to re-open if you can still reproduce. Thanks!

**Closed by nullnotnil** 2020-07-10 16:05 UTC
Labels: type/bug
