### ISSUE TITLE
FOUND_ROWS returns unexpected result

### ISSUE THREAD

**Issue by suli1991** [pingcap/tidb#17718] opened 2020-06-05 09:10 UTC
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

1步

### 2. What did you expect to see? (Required)
返回没有limit限制的结果

### 3. What did you see instead (Required)
返回的是limit限制后的结果
### 4. Affected version (Required)
5.7.25-TiDB-v3.0.11

**Comment by wwar** [comment] 2020-06-05 11:49
I believe this is a duplicate of https://github.com/pingcap/tidb/issues/14448

cc @zz-jason

**Comment by zz-jason** [comment] 2020-06-06 00:37
> I believe this is a duplicate of #14448
> 
> cc @zz-jason

Yeah, we are going to discuss whether this feature should be supported in TiDB 5.0

**Comment by zz-jason** [comment] 2020-06-06 00:39
@suli1991 Thanks for your reporting, you can follow https://github.com/pingcap/tidb/issues/14448 to trace the progress. I'm going to close this issue due to it's duplicated with https://github.com/pingcap/tidb/issues/14448.

**Closed by zz-jason** 2020-06-06 00:39 UTC
Labels: component/executor, type/bug
