### ISSUE TITLE
the oom-action doesn't work in "select * from partition table" statement

### ISSUE THREAD

**Issue by ChenPeng2013** [pingcap/tidb#17049] opened 2020-05-08 12:52 UTC
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. What did you do?

oom-action=cancel
```
drop table if exists t;
set tidb_mem_quota_query=-1;
create table t(a int) PARTITION BY RANGE(a) (
        PARTITION p0 VALUES LESS THAN (5),
        PARTITION p1 VALUES LESS THAN (10),
        PARTITION p2 VALUES LESS THAN (15),
        PARTITION p3 VALUES LESS THAN MAXVALUE
        );
insert into t values(1),(2),(3),(4),(10);
set tidb_mem_quota_query=500;
select * from t;  # mem_max=572
```
### 2. What did you expect to see?
```
mysql> select * from t;
ERROR 1105 (HY000): Out Of Memory Quota![conn_id=54]
```
### 3. What did you see instead?
```
mysql> select * from t;
+------+
| a    |
+------+
|    1 |
|    2 |
|    3 |
|    4 |
|   10 |
+------+
5 rows in set (0.00 sec)
```
### 4. What version of TiDB are you using? (`tidb-server -V` or run `select tidb_version();` on TiDB)
```
Release Version: v4.0.0-rc.1-45-gdb432776d-dirty
Git Commit Hash: db432776d1f01815cb1116b68bcaaf59a93be019
Git Branch: release-4.0
UTC Build Time: 2020-05-08 09:23:04
GoVersion: go1.13.1
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
```

**Comment by tiancaiamao** [comment] 2020-05-12 06:43
I tried to limit the concurrenty in https://github.com/pingcap/tidb/pull/16815
@XuHuaiyu seems to have some better ideas, so I've assign this to him.

**Comment by XuHuaiyu** [comment] 2020-06-17 05:02
This is expected behavior.

Union will read data from the children concurrently, thus the total memory usage exceeds the threshold indefinitely.

**Closed** 2020-07-13 03:02 UTC
Labels: component/executor, epic/memory-management, type/bug

**Comment by SunRunAway** [comment] 2021-04-29 06:35
Why it's not a bug?
