### ISSUE TITLE
txn: memory of previous execution can not be released when retrying a transaction

### ISSUE THREAD

**Issue by AndreMouche** [pingcap/tidb#56837] opened 2024-10-25 08:09 UTC
## Enhancement
When retrying a transaction, for example, when we meet lock-conflict error, the memory of the previous execution can not be released until the txn commits successfully. It may cause conflict txn killed by tidb_mem_quota_query or make TiDB OOM

This issue was fix in https://github.com/tikv/client-go/pull/1451 since v8.4.0, while  I think we need PR to fix it in lower versions.

**Comment by cfzjywxk** [comment] 2024-10-29 01:31
Related issue https://github.com/tikv/client-go/issues/1375.
Some evaluations are needed for the cherrr-pick fix. If it's decided to pick the fix to release version, this issue could be marked with "bug" label for the pick.

**Comment by cfzjywxk** [comment] 2024-10-29 02:56
After some discussions, the issue would be fixed in the release versions, changing the label to "bug".

For versions >= v8.4, the issue is already fixed as the new ART memdb is used by default instead of the red-black tree one.

For versions < v8.4, the fix would be picked for RB-tree memdb, the solution is:
1. When write conflict error is encounterred, the `memdb.Cleanup` would be called to revert the staging memory content of the current statement.
2. Do not delete the nodes in index tree in the memdb and mark them with delete flags, as in most cases the to be written keys are the same retrying the statement. The value log is reverted like before.
3. Reuse the nodes when retrying the statement.

**Closed** 2024-11-20 12:32 UTC
Labels: type/bug, sig/transaction, severity/major, affects-5.4, affects-6.1, affects-6.5, affects-7.1, affects-7.5, affects-8.1
