### ISSUE TITLE
the max function return errors

### ISSUE THREAD

**Issue by ljhmily** [pingcap/tidb#8113] opened 2018-10-31 02:22 UTC
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
select max(count) from amp_kafka_info;
| count              | int(11)       | YES  |      | NULL              |       |
the count column has number and NULL values

this statement can be execute at early time, but it return errors now

2. What did you expect to see?
+------------+
| max(count) |
+------------+
|        254 |
+------------+

3. What did you see instead?
where ever i do, it will return
[Err] 2013 (HY000) - Lost connection to MySQL server during query

in tidb-server
2018/10/30 18:33:15.154 server.go:314: [info] con:32 new connection 10.133.147.109:59344
2018/10/30 18:33:15.239 conn.go:427: [error] lastCmd SELECT IFNULL(max(t.count), 0) FROM amp_kafka_info t, runtime error: index out of range, goroutine 86996 [running]:
github.com/pingcap/tidb/server.(*clientConn).Run.func1(0xc007188270, 0xc002c81dff)
        /home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/server/conn.go:425 +0x10c
panic(0x11d0ec0, 0x224bf40)
        /usr/local/go/src/runtime/panic.go:513 +0x1b9
github.com/pingcap/tidb/util/chunk.(*column).isNull(...)
        /home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/util/chunk/column.go:71
github.com/pingcap/tidb/util/chunk.Row.IsNull(...)
        /home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/util/chunk/row.go:222
github.com/pingcap/tidb/util/chunk.Compare(0xc001895590, 0x0, 0x0, 0xc002c80ef8, 0x41103e3800000000)
        /home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/util/chunk/compare.go:173 +0xc34
github.com/pingcap/tidb/statistics.(*Histogram).outOfRange(0xc002361950, 0xf, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x10)
        /home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/statistics/histogram.go:685 +0x4e
github.com/pingcap/tidb/statistics.(*Column).getColumnRowCount(0xc002361950, 0xc007188410, 0xc009b926f0, 0x1, 0x1, 0x255b7, 0xc007b4f980, 0xc007b4f980, 0x0)
        /home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/statistics/histogram.go:772 +0x2fe
github.com/pingcap/tidb/statistics.(*HistColl).GetRowCountByColumnRanges(0xc009618330, 0xc007188410, 0x1a, 0xc009b926f0, 0x1, 0x1, 0x0, 0x1, 0x0)
        /home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/statistics/table.go:426 +0xd4
github.com/pingcap/tidb/statistics.(*HistColl).Selectivity(0xc009618330, 0x153ac80, 0xc00084ec40, 0xc009014640, 0x1, 0x1, 0x1a, 0x181, 0x1)
        /home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/statistics/selectivity.go:215 +0xcc1
github.com/pingcap/tidb/planner/core.(*DataSource).getStatsByFilter(0xc0093bbe40, 0xc009014640, 0x1, 0x1, 0xc0093bbe00)
        /home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/planner/core/stats.go:80 +0x389
github.com/pingcap/tidb/planner/core.(*DataSource).deriveStats(0xc0093bbe40, 0xc002c814e0, 0xeff814, 0xc0093bbe48)
        /home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/planner/core/stats.go:93 +0x10c
github.com/pingcap/tidb/planner/core.(*LogicalTopN).deriveStats(0xc00273abd0, 0xeff463, 0xc0085e8c80, 0x0)
        /home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/planner/core/stats.go:164 +0x46
github.com/pingcap/tidb/planner/core.(*LogicalAggregation).deriveStats(0xc0003e9c00, 0xc002c81608, 0x6d3739, 0x0)
        /home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/planner/core/stats.go:211 +0x57
github.com/pingcap/tidb/planner/core.(*LogicalProjection).deriveStats(0xc0086e9ef0, 0x0, 0xc0086e9ef0, 0x0)
        /home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/planner/core/stats.go:195 +0x4c
github.com/pingcap/tidb/planner/core.physicalOptimize(0x153a740, 0xc0086e9ef0, 0xc0086e9ef0, 0x153a740, 0xc0086e9ef0, 0x0)
        /home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/planner/core/optimizer.go:126 +0x35
github.com/pingcap/tidb/planner/core.DoOptimize(0x377, 0x153a740, 0xc0086e9ef0, 0x153a740, 0xc0086e9ef0, 0x1, 0x0)
        /home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/planner/core/optimizer.go:100 +0x7e
github.com/pingcap/tidb/planner.Optimize(0x153ac80, 0xc00084ec40, 0x150d6e0, 0xc009609400, 0x1524ca0, 0xc0009826c0, 0x22c0900, 0x0, 0x0, 0x0)
        /home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/planner/optimize.go:67 +0x2b6
github.com/pingcap/tidb/executor.(*Compiler).Compile(0xc002c81980, 0x7f2481eba540, 0xc007b4edc0, 0x1516fe0, 0xc009609400, 0x0, 0x0, 0x0)
        /home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/executor/compiler.go:49 +0x1d2
github.com/pingcap/tidb/session.(*session).execute(0xc00084ec40, 0x7f2481eba540, 0xc007b4edc0, 0xc007f00ac1, 0x34, 0x203001, 0x203001, 0xc0085e8500, 0xc005e3a000, 0x30)
        /home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/session/session.go:796 +0x6ba
2018/10/30 18:33:15.239 server.go:316: [info] con:32 close connection

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
Release Version: v2.1.0-rc.3-45-g95edaf0
Git Commit Hash: 95edaf02e0c0446b14af2847af1300fe4778b11e
Git Branch: master
UTC Build Time: 2018-10-16 08:45:34
GoVersion: go version go1.11 linux/amd64
Race Enabled: false
TiKV Min Version: 2.1.0-alpha.1-ff3dd160846b7d1aed9079c389fc188f7f5ea13e
Check Table Before Drop: false

**Comment by XuHuaiyu** [comment] 2018-10-31 02:29
hi, @ljhmily 
Thanks for your feedback.
What's the column type of `count`?

**Comment by zz-jason** [comment] 2020-04-11 09:47
Hi @ljhmily, I'm going to close this issue since it's hard to reproduce. Feel free to reopen it if it appears again.

**Closed by zz-jason** 2020-04-11 09:47 UTC
Labels: type/bug
