### ISSUE TITLE
left join query return different result 

### ISSUE THREAD

**Issue by aytrack** [pingcap/tidb#47477] opened 2023-10-09 08:55 UTC
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
from asktug: https://asktug.com/t/topic/1013225

### 4. What is your TiDB version? (Required)
v6.5.3

**Comment by elsa0520** [comment] 2023-10-11 09:58
Please give use the **All explain analyze information** (need to include all columns)
and the create table statement

**Comment by chrysan** [comment] 2023-10-30 08:31
Downgrade to major since no reproduce steps sofar, will upgrade it to critical after reproduce steps are provided.

**Comment by elsa0520** [comment] 2023-12-22 07:20
Could not reproduce it. Just close it.

**Closed by elsa0520** 2023-12-22 07:20 UTC
Labels: type/bug, sig/planner, severity/major, may-affects-5.4, may-affects-6.1, affects-6.5, may-affects-7.1, affects-7.5
