### ISSUE TITLE
register error after initialized is prohibited

### ISSUE THREAD

**Issue by lilinghai** [pingcap/tidb#29412] opened 2021-11-03 12:36 UTC
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

[1.txt](https://github.com/pingcap/tidb/files/7467505/1.txt)
```sql
source 1.txt
select sum( distinct `col_int_undef_unsigned`) as x from table_75_latin1_undef as t1 having x > some (select `col_float_undef_signed` from table_10_latin1_undef as t2 where x in (col_double_undef_signed));
/*
+------------------------------------+---------+-----------+---------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| id                                 | estRows | task      | access object | operator info                                                                                                                                                                   |
+------------------------------------+---------+-----------+---------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Selection_13                       | 0.64    | root      |               | Column#55                                                                                                                                                                       |
| └─Apply_15                         | 0.80    | root      |               | CARTESIAN semi join, other cond:or(gt(cast(Column#55, double BINARY), Column#83), if(ne(Column#84, 0), NULL, 0))                                                                |
|   ├─Selection_17(Build)            | 0.80    | root      |               | if(isnull(Column#55), NULL, 1)                                                                                                                                                  |
|   │ └─StreamAgg_19                 | 1.00    | root      |               | funcs:sum(distinct Column#92)->Column#55                                                                                                                                        |
|   │   └─Projection_44              | 75.00   | root      |               | cast(rs.table_75_latin1_undef.col_int_undef_unsigned, decimal(48,31) BINARY)->Column#92                                                                                         |
|   │     └─TableReader_23           | 75.00   | root      |               | data:TableFullScan_22                                                                                                                                                           |
|   │       └─TableFullScan_22       | 75.00   | cop[tikv] | table:t1      | keep order:false, stats:pseudo                                                                                                                                                  |
|   └─Selection_24(Probe)            | 0.80    | root      |               | ne(Column#85, 0)                                                                                                                                                                |
|     └─StreamAgg_39                 | 1.00    | root      |               | funcs:min(Column#89)->Column#83, funcs:sum(Column#90)->Column#84, funcs:count(Column#91)->Column#85                                                                             |
|       └─TableReader_40             | 1.00    | root      |               | data:StreamAgg_28                                                                                                                                                               |
|         └─StreamAgg_28             | 1.00    | cop[tikv] |               | funcs:min(rs.table_10_latin1_undef.col_float_undef_signed)->Column#89, funcs:sum(isnull(rs.table_10_latin1_undef.col_float_undef_signed))->Column#90, funcs:count(1)->Column#91 |
|           └─Selection_38           | 8.00    | cop[tikv] |               | eq(cast(Column#55, double BINARY), rs.table_10_latin1_undef.col_double_undef_signed)                                                                                            |
|             └─TableFullScan_37     | 10.00   | cop[tikv] | table:t2      | keep order:false, stats:pseudo                                                                                                                                                  |
+------------------------------------+---------+-----------+---------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
*/
```

### 2. What did you expect to see? (Required)
successfully
### 3. What did you see instead (Required)
ERROR 1105 (HY000): register error after initialized is prohibited
### 4. What is your TiDB version? (Required)

Release Version: v5.3.0-alpha-1304-ga96deabe7
Edition: Community
Git Commit Hash: a96deabe7e46385722cf96f7fc254de86fd5bd1a
Git Branch: master
UTC Build Time: 2021-11-02 05:14:52
GoVersion: go1.16.4
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false

**Comment by kennytm** [comment] 2021-11-04 09:51
can you also copy the line from the log containing the stacktrace?

**Comment by time-and-fate** [comment] 2021-11-04 10:08
> can you also copy the line from the log containing the stacktrace?

Part of the stack trace:
```
[2021/11/04 15:07:13.303 +08:00] [INFO] [conn.go:1058] ["command dispatched failed"] [conn=9] [connInfo="id:9, addr:127.0.0.1:38340 status:10, collation:utf8_general_ci, user:root"] [command=Query] [status="inTxn:0, autocommit:1"] [sql="select sum( distinct `col_int_undef_unsigned`) as x from table_75_latin1_undef as t1 having x > some (select `col_float_undef_signed` from table_10_latin1_undef as t2 where x in (col_double_undef_signed))"] [txn_mode=PESSIMISTIC] [err="register error after initialized is prohibited
github.com/pingcap/tidb/executor.(*recordSet).Next.func1
        /home/timeandfate/code/tidb/executor/adapter.go:143
runtime.gopanic
        /usr/lib/go/src/runtime/panic.go:1038
github.com/pingcap/tidb/parser/terror.ErrClass.initError
        /home/timeandfate/code/tidb/parser/terror/terror.go:165
github.com/pingcap/tidb/parser/terror.ErrClass.NewStdErr
        /home/timeandfate/code/tidb/parser/terror/terror.go:195
github.com/pingcap/tidb/util/dbterror.ErrClass.NewStd
        /home/timeandfate/code/tidb/util/dbterror/terror.go:56
github.com/pingcap/tidb/expression.ExpressionsToPBList
        /home/timeandfate/code/tidb/expression/expr_to_pb.go:41
github.com/pingcap/tidb/planner/core.(*PhysicalSelection).ToPB
        /home/timeandfate/code/tidb/planner/core/plan_to_pb.go:95
github.com/pingcap/tidb/executor.constructDistExec
        /home/timeandfate/code/tidb/executor/builder.go:2603
```

The cause has been located. 
The direct reason is incorrect usage of the `terror` at https://github.com/pingcap/tidb/blob/dcbfda914ad0b2647edc39788e0a6e8b5d90717d/expression/expr_to_pb.go#L41
The root cause is that `Flen` and `Decimal` of the `FieldType` of a `CorrelatedColumn` are not set correctly, which is introduced in https://github.com/pingcap/tidb/pull/26651. I'll fix this one soon.

**Comment by kennytm** [comment] 2021-11-04 10:57
All uses of `dbterror.ClassOptimizer.NewStd(mysql.ErrInternal)` should be replaced by a global constant too. There are 6 places.

**Comment by time-and-fate** [comment] 2021-11-04 12:10
Minimal reproduce:
```
create table t1(a int);
create table t2(a double);
insert into t1 value(20);
select sum(distinct a) as x from t1 having x > some ( select a from t2 where x in (a));
```

**Comment by time-and-fate** [comment] 2021-11-04 12:29
This issue is expected to be closed by https://github.com/pingcap/tidb/pull/29457.
I created https://github.com/pingcap/tidb/issues/29465 to track the incorrect usage of `(ErrClass).NewStd()`.

**Closed** 2021-11-04 23:49 UTC
Labels: type/bug, sig/execution, severity/major
