### ISSUE TITLE
result is not expected when ORDER BY Window function

### ISSUE THREAD

**Issue by winoros** [pingcap/tidb#10591] opened 2019-05-24 07:41 UTC
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

```
CREATE TABLE tj(j JSON, i INT DEFAULT 7);
INSERT INTO tj(j) VALUES ('1');
INSERT INTO tj(j) VALUES ('2');
INSERT INTO tj(j) VALUES ('3');
INSERT INTO tj(j) VALUES ('4');
INSERT INTO tj(j) VALUES ('5');
INSERT INTO tj(j) VALUES (NULL);
INSERT INTO tj(j) VALUES ('3.14');
INSERT INTO tj(j) VALUES ('[1,2,3]');

SELECT DISTINCT i,NTILE(3) OVER (ORDER BY i), SUM(i) OVER (order by i), COUNT(*) OVER (order by i) FROM tj ORDER BY NTILE(3) OVER (ORDER BY i);
```

2. What did you expect to see?

The result is ordered by the second column which is `NTILE(3) OVER (ORDER BY i)`

3. What did you see instead?

The order is random.

```
mysql> SELECT DISTINCT i,NTILE(3) OVER (ORDER BY i), SUM(i) OVER (order by i), COUNT(*) OVER (order by i) FROM tj ORDER BY NTILE(3) OVER (ORDER BY i);
+------+----------------------------+--------------------------+----------------------------+
| i    | NTILE(3) OVER (ORDER BY i) | SUM(i) OVER (order by i) | COUNT(*) OVER (order by i) |
+------+----------------------------+--------------------------+----------------------------+
|    7 |                          3 |                       56 |                          8 |
|    7 |                          2 |                       56 |                          8 |
|    7 |                          1 |                       56 |                          8 |
+------+----------------------------+--------------------------+----------------------------+
3 rows in set (0.01 sec)

mysql> SELECT DISTINCT i,NTILE(3) OVER (ORDER BY i), SUM(i) OVER (order by i), COUNT(*) OVER (order by i) FROM tj ORDER BY NTILE(3) OVER (ORDER BY i);
+------+----------------------------+--------------------------+----------------------------+
| i    | NTILE(3) OVER (ORDER BY i) | SUM(i) OVER (order by i) | COUNT(*) OVER (order by i) |
+------+----------------------------+--------------------------+----------------------------+
|    7 |                          1 |                       56 |                          8 |
|    7 |                          3 |                       56 |                          8 |
|    7 |                          2 |                       56 |                          8 |
+------+----------------------------+--------------------------+----------------------------+
3 rows in set (0.00 sec)

mysql> SELECT DISTINCT i,NTILE(3) OVER (ORDER BY i), SUM(i) OVER (order by i), COUNT(*) OVER (order by i) FROM tj ORDER BY NTILE(3) OVER (ORDER BY i);
+------+----------------------------+--------------------------+----------------------------+
| i    | NTILE(3) OVER (ORDER BY i) | SUM(i) OVER (order by i) | COUNT(*) OVER (order by i) |
+------+----------------------------+--------------------------+----------------------------+
|    7 |                          2 |                       56 |                          8 |
|    7 |                          3 |                       56 |                          8 |
|    7 |                          1 |                       56 |                          8 |
+------+----------------------------+--------------------------+----------------------------+
3 rows in set (0.00 sec)
```

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

## SIG slack channel

 [#sig-planner](https://slack.tidb.io/invite?team=tidb-community&channel=sig-planner&ref=high-performance)

## Score

- 900

## Mentor

* @lzmhhh123

**Comment by winoros** [comment] 2019-05-24 07:43
This is caused by a know issue that if one expression occurs both in select fields and order by fields. We'll calculate it twice.
Before window function is okay. But since window function' output is influenced by the data order if no order is set in window's definition. So the result of two window function may not be the same.

**Comment by nullnotnil** [comment] 2020-07-14 15:11
This has been fixed in master. I'll leave it open for now because it's triaged for the 4.0 backlog, but if I repeat the select several times it is deterministic:
```sql
DROP TABLE IF EXISTS tj;
CREATE TABLE tj(j JSON, i INT DEFAULT 7);
INSERT INTO tj(j) VALUES ('1');
INSERT INTO tj(j) VALUES ('2');
INSERT INTO tj(j) VALUES ('3');
INSERT INTO tj(j) VALUES ('4');
INSERT INTO tj(j) VALUES ('5');
INSERT INTO tj(j) VALUES (NULL);
INSERT INTO tj(j) VALUES ('3.14');
INSERT INTO tj(j) VALUES ('[1,2,3]');

SELECT DISTINCT i,NTILE(3) OVER (ORDER BY i), SUM(i) OVER (order by i), COUNT(*) OVER (order by i) FROM tj ORDER BY NTILE(3) OVER (ORDER BY i);
SELECT DISTINCT i,NTILE(3) OVER (ORDER BY i), SUM(i) OVER (order by i), COUNT(*) OVER (order by i) FROM tj ORDER BY NTILE(3) OVER (ORDER BY i);
SELECT DISTINCT i,NTILE(3) OVER (ORDER BY i), SUM(i) OVER (order by i), COUNT(*) OVER (order by i) FROM tj ORDER BY NTILE(3) OVER (ORDER BY i);
SELECT DISTINCT i,NTILE(3) OVER (ORDER BY i), SUM(i) OVER (order by i), COUNT(*) OVER (order by i) FROM tj ORDER BY NTILE(3) OVER (ORDER BY i);
SELECT DISTINCT i,NTILE(3) OVER (ORDER BY i), SUM(i) OVER (order by i), COUNT(*) OVER (order by i) FROM tj ORDER BY NTILE(3) OVER (ORDER BY i);
SELECT DISTINCT i,NTILE(3) OVER (ORDER BY i), SUM(i) OVER (order by i), COUNT(*) OVER (order by i) FROM tj ORDER BY NTILE(3) OVER (ORDER BY i);
SELECT DISTINCT i,NTILE(3) OVER (ORDER BY i), SUM(i) OVER (order by i), COUNT(*) OVER (order by i) FROM tj ORDER BY NTILE(3) OVER (ORDER BY i);
SELECT DISTINCT i,NTILE(3) OVER (ORDER BY i), SUM(i) OVER (order by i), COUNT(*) OVER (order by i) FROM tj ORDER BY NTILE(3) OVER (ORDER BY i);
SELECT DISTINCT i,NTILE(3) OVER (ORDER BY i), SUM(i) OVER (order by i), COUNT(*) OVER (order by i) FROM tj ORDER BY NTILE(3) OVER (ORDER BY i);
SELECT DISTINCT i,NTILE(3) OVER (ORDER BY i), SUM(i) OVER (order by i), COUNT(*) OVER (order by i) FROM tj ORDER BY NTILE(3) OVER (ORDER BY i);
SELECT DISTINCT i,NTILE(3) OVER (ORDER BY i), SUM(i) OVER (order by i), COUNT(*) OVER (order by i) FROM tj ORDER BY NTILE(3) OVER (ORDER BY i);
SELECT tidb_version()\G

..

mysql> SELECT DISTINCT i,NTILE(3) OVER (ORDER BY i), SUM(i) OVER (order by i), COUNT(*) OVER (order by i) FROM tj ORDER BY NTILE(3) OVER (ORDER BY i);
+------+----------------------------+--------------------------+----------------------------+
| i    | NTILE(3) OVER (ORDER BY i) | SUM(i) OVER (order by i) | COUNT(*) OVER (order by i) |
+------+----------------------------+--------------------------+----------------------------+
|    7 |                          1 |                       56 |                          8 |
|    7 |                          2 |                       56 |                          8 |
|    7 |                          3 |                       56 |                          8 |
+------+----------------------------+--------------------------+----------------------------+
3 rows in set (0.01 sec)

mysql> SELECT DISTINCT i,NTILE(3) OVER (ORDER BY i), SUM(i) OVER (order by i), COUNT(*) OVER (order by i) FROM tj ORDER BY NTILE(3) OVER (ORDER BY i);
+------+----------------------------+--------------------------+----------------------------+
| i    | NTILE(3) OVER (ORDER BY i) | SUM(i) OVER (order by i) | COUNT(*) OVER (order by i) |
+------+----------------------------+--------------------------+----------------------------+
|    7 |                          1 |                       56 |                          8 |
|    7 |                          2 |                       56 |                          8 |
|    7 |                          3 |                       56 |                          8 |
+------+----------------------------+--------------------------+----------------------------+
3 rows in set (0.00 sec)

mysql> SELECT DISTINCT i,NTILE(3) OVER (ORDER BY i), SUM(i) OVER (order by i), COUNT(*) OVER (order by i) FROM tj ORDER BY NTILE(3) OVER (ORDER BY i);
+------+----------------------------+--------------------------+----------------------------+
| i    | NTILE(3) OVER (ORDER BY i) | SUM(i) OVER (order by i) | COUNT(*) OVER (order by i) |
+------+----------------------------+--------------------------+----------------------------+
|    7 |                          1 |                       56 |                          8 |
|    7 |                          2 |                       56 |                          8 |
|    7 |                          3 |                       56 |                          8 |
+------+----------------------------+--------------------------+----------------------------+
3 rows in set (0.00 sec)

mysql> SELECT DISTINCT i,NTILE(3) OVER (ORDER BY i), SUM(i) OVER (order by i), COUNT(*) OVER (order by i) FROM tj ORDER BY NTILE(3) OVER (ORDER BY i);
+------+----------------------------+--------------------------+----------------------------+
| i    | NTILE(3) OVER (ORDER BY i) | SUM(i) OVER (order by i) | COUNT(*) OVER (order by i) |
+------+----------------------------+--------------------------+----------------------------+
|    7 |                          1 |                       56 |                          8 |
|    7 |                          2 |                       56 |                          8 |
|    7 |                          3 |                       56 |                          8 |
+------+----------------------------+--------------------------+----------------------------+
3 rows in set (0.00 sec)

mysql> SELECT DISTINCT i,NTILE(3) OVER (ORDER BY i), SUM(i) OVER (order by i), COUNT(*) OVER (order by i) FROM tj ORDER BY NTILE(3) OVER (ORDER BY i);
+------+----------------------------+--------------------------+----------------------------+
| i    | NTILE(3) OVER (ORDER BY i) | SUM(i) OVER (order by i) | COUNT(*) OVER (order by i) |
+------+----------------------------+--------------------------+----------------------------+
|    7 |                          1 |                       56 |                          8 |
|    7 |                          2 |                       56 |                          8 |
|    7 |                          3 |                       56 |                          8 |
+------+----------------------------+--------------------------+----------------------------+
3 rows in set (0.00 sec)

mysql> SELECT DISTINCT i,NTILE(3) OVER (ORDER BY i), SUM(i) OVER (order by i), COUNT(*) OVER (order by i) FROM tj ORDER BY NTILE(3) OVER (ORDER BY i);
+------+----------------------------+--------------------------+----------------------------+
| i    | NTILE(3) OVER (ORDER BY i) | SUM(i) OVER (order by i) | COUNT(*) OVER (order by i) |
+------+----------------------------+--------------------------+----------------------------+
|    7 |                          1 |                       56 |                          8 |
|    7 |                          2 |                       56 |                          8 |
|    7 |                          3 |                       56 |                          8 |
+------+----------------------------+--------------------------+----------------------------+
3 rows in set (0.00 sec)

mysql> SELECT DISTINCT i,NTILE(3) OVER (ORDER BY i), SUM(i) OVER (order by i), COUNT(*) OVER (order by i) FROM tj ORDER BY NTILE(3) OVER (ORDER BY i);
+------+----------------------------+--------------------------+----------------------------+
| i    | NTILE(3) OVER (ORDER BY i) | SUM(i) OVER (order by i) | COUNT(*) OVER (order by i) |
+------+----------------------------+--------------------------+----------------------------+
|    7 |                          1 |                       56 |                          8 |
|    7 |                          2 |                       56 |                          8 |
|    7 |                          3 |                       56 |                          8 |
+------+----------------------------+--------------------------+----------------------------+
3 rows in set (0.00 sec)

mysql> SELECT DISTINCT i,NTILE(3) OVER (ORDER BY i), SUM(i) OVER (order by i), COUNT(*) OVER (order by i) FROM tj ORDER BY NTILE(3) OVER (ORDER BY i);
+------+----------------------------+--------------------------+----------------------------+
| i    | NTILE(3) OVER (ORDER BY i) | SUM(i) OVER (order by i) | COUNT(*) OVER (order by i) |
+------+----------------------------+--------------------------+----------------------------+
|    7 |                          1 |                       56 |                          8 |
|    7 |                          2 |                       56 |                          8 |
|    7 |                          3 |                       56 |                          8 |
+------+----------------------------+--------------------------+----------------------------+
3 rows in set (0.00 sec)

mysql> SELECT DISTINCT i,NTILE(3) OVER (ORDER BY i), SUM(i) OVER (order by i), COUNT(*) OVER (order by i) FROM tj ORDER BY NTILE(3) OVER (ORDER BY i);
+------+----------------------------+--------------------------+----------------------------+
| i    | NTILE(3) OVER (ORDER BY i) | SUM(i) OVER (order by i) | COUNT(*) OVER (order by i) |
+------+----------------------------+--------------------------+----------------------------+
|    7 |                          1 |                       56 |                          8 |
|    7 |                          2 |                       56 |                          8 |
|    7 |                          3 |                       56 |                          8 |
+------+----------------------------+--------------------------+----------------------------+
3 rows in set (0.00 sec)

mysql> SELECT DISTINCT i,NTILE(3) OVER (ORDER BY i), SUM(i) OVER (order by i), COUNT(*) OVER (order by i) FROM tj ORDER BY NTILE(3) OVER (ORDER BY i);
+------+----------------------------+--------------------------+----------------------------+
| i    | NTILE(3) OVER (ORDER BY i) | SUM(i) OVER (order by i) | COUNT(*) OVER (order by i) |
+------+----------------------------+--------------------------+----------------------------+
|    7 |                          1 |                       56 |                          8 |
|    7 |                          2 |                       56 |                          8 |
|    7 |                          3 |                       56 |                          8 |
+------+----------------------------+--------------------------+----------------------------+
3 rows in set (0.01 sec)

mysql> SELECT DISTINCT i,NTILE(3) OVER (ORDER BY i), SUM(i) OVER (order by i), COUNT(*) OVER (order by i) FROM tj ORDER BY NTILE(3) OVER (ORDER BY i);
+------+----------------------------+--------------------------+----------------------------+
| i    | NTILE(3) OVER (ORDER BY i) | SUM(i) OVER (order by i) | COUNT(*) OVER (order by i) |
+------+----------------------------+--------------------------+----------------------------+
|    7 |                          1 |                       56 |                          8 |
|    7 |                          2 |                       56 |                          8 |
|    7 |                          3 |                       56 |                          8 |
+------+----------------------------+--------------------------+----------------------------+
3 rows in set (0.00 sec)

mysql> SELECT tidb_version()\G
*************************** 1. row ***************************
tidb_version(): Release Version: v4.0.0-beta.2-762-g77aecd4b2
Edition: Community
Git Commit Hash: 77aecd4b27e79a97215eb4fdd68f68f2ddf67d21
Git Branch: master
UTC Build Time: 2020-07-13 01:43:31
GoVersion: go1.13
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
1 row in set (0.00 sec)
```

**Comment by lzmhhh123** [comment] 2020-11-02 07:58
Can not reproduce. Both on master branch and release-4.0 branch.

**Closed** 2020-11-02 07:58 UTC
Labels: challenge-program, severity/major, sig/planner, status/can't-reproduce, status/help-wanted, type/bug
