### ISSUE TITLE
The default order of `WHERE ... IN ...` clause is different with MySQL

### ISSUE THREAD

**Issue by Mini256** [pingcap/tidb#37285] opened 2022-08-23 01:38 UTC
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```sql
CREATE TABLE T1(a INT PRIMARY KEY);
INSERT INTO T1 VALUES(5), (4), (3), (2), (1);
SELECT * FROM T1 WHERE a IN (4, 3, 5, 2, 1);
```

### 2. What did you expect to see? (Required)

MySQL:

```
MySQL root@127.0.0.1:test> SELECT * FROM T1 WHERE a IN (4, 3, 5, 2, 1);
+---+
| a |
+---+
| 1 |
| 2 |
| 3 |
| 4 |
| 5 |
+---+
5 rows in set
Time: 0.045s
```

### 3. What did you see instead (Required)

TiDB:

```
mysql> SELECT * FROM T1 WHERE a IN (4, 3, 5, 2, 1);
+---+
| a |
+---+
| 4 |
| 3 |
| 5 |
| 2 |
| 1 |
+---+
5 rows in set (0.00 sec)
```

### 4. What is your TiDB version? (Required)

```
mysql> SELECT tidb_version()\G
*************************** 1. row ***************************
tidb_version(): Release Version: v6.3.0-alpha
Edition: Community
Git Commit Hash: 8b5b724d8a932239303a1d0ba547323eb0e5161b
Git Branch: heads/refs/tags/v6.3.0-alpha
UTC Build Time: 2022-08-19 14:25:37
GoVersion: go1.18.5
Race Enabled: false
TiKV Min Version: 6.2.0-alpha
Check Table Before Drop: false
Store: tikv
1 row in set (0.00 sec)
```

**Comment by windtalker** [comment] 2022-08-23 07:13
For two reasons I think we should not treat it as a bug, even not a minor bug:
- The sql itself does not require the result order
- TiDB is a distributed database, if the sql does not require result order, it is normal that the order of result is not stable(We can not sync the execution between different nodes)

So I think we can just close this issue as `Not A Bug`. @Mini256 @zanmato1984

**Comment by Mini256** [comment] 2022-08-24 03:02
@windtalker Thank you for your explanation, this is a test case I encountered when testing the ORM framework Prisma. However, this case does not exclude cockroachdb and mongodb, which may mean that they also follow the default sorting rules.

https://github.com/prisma/prisma-engines/blob/ccf3dc944acdabb431947150e12b984b34c538cd/query-engine/connector-test-kit-rs/query-engine-tests/tests/queries/batch/in_selection_batching.rs#L39

**Closed** 2023-08-15 09:24 UTC
Labels: type/bug, type/compatibility, sig/execution, severity/minor

**Comment by janpio** [comment] 2024-04-23 18:24
Has this ordering issue been fixed @Mini256?
