### ISSUE TITLE
ddl_slow_threshold value range should be [1:4294967295]

### ISSUE THREAD

**Issue by seiya-annie** [pingcap/tidb#35265] opened 2022-06-09 08:16 UTC
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```sql
mysql> set global ddl_slow_threshold=4294967296;
Query OK, 0 rows affected (0.00 sec)

mysql> show global variables like 'ddl_slow_threshold';
+--------------------+-------+
| Variable_name      | Value |
+--------------------+-------+
| ddl_slow_threshold | 0     |
+--------------------+-------+
1 row in set (0.00 sec)

mysql> set global ddl_slow_threshold=0;
Query OK, 0 rows affected (0.00 sec)

mysql> show global variables like 'ddl_slow_threshold';
+--------------------+-------+
| Variable_name      | Value |
+--------------------+-------+
| ddl_slow_threshold | 300   |
+--------------------+-------+
1 row in set (0.00 sec)

mysql> 

```
### 2. What did you expect to see? (Required)
what's  ddl_slow_threshold=0 means? 0 is a valid value for ddl_slow_threshold? why  ddl_slow_threshold=0  be truncated to ddl_slow_threshold=300?

the max value for ddl_slow_threshold is 4294967295? this range is not write in document. 
ddl_slow_threshold = 4294967296 should be truncated to 4294967295, not truncated to 0.

### 3. What did you see instead (Required)
1. ddl_slow_threshold = 4294967296 is truncated to 0, what will happen,when ddl_slow_threshold =0
2. ddl_slow_threshold = 0 should be truncated to 1

### 4. What is your TiDB version? (Required)

Git Commit Hash: 1a89decdb192cbdce6a7b0020d71128bc964d30f
Git Branch: heads/refs/tags/v6.1.0
UTC Build Time: 2022-06-05 05:15:11
GoVersion: go1.18.2

**Comment by morgo** [comment] 2022-06-12 00:00
> the max value for ddl_slow_threshold is 4294967295? this range is not write in document.

This is a duplicate of https://github.com/pingcap/tidb/issues/35048 - it has a PR open to fix this already.

The type for the variable is just the default of string. So the range is not shown in the documentation, and the sysvar type validation doesn't apply. In the code to set the value, it will truncate out of range values to the default value.

**Closed** 2022-06-12 22:40 UTC
Labels: type/bug, sig/sql-infra, severity/moderate
