### ISSUE TITLE
fatal error table already exists after upgrade ，TIDB can not start up

### ISSUE THREAD

**Issue by liuzx8888** [pingcap/tidb#47255] opened 2023-09-25 10:49 UTC
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

   upgrade : tiup cluster upgrade <cluster-name> v7.1.1

### 2. What did you expect to see? (Required)
![image](https://github.com/pingcap/tidb/assets/10862577/d58ea318-8aa5-4b44-82ac-ecfdfcc4260a)
```
[2023/09/25 18:24:59.048 +08:00] [INFO] [main.go:390] ["disable Prometheus push client"]
[2023/09/25 18:24:59.048 +08:00] [INFO] [store.go:76] ["new store"] [path=tikv://192.168.2.182:2379,192.168.2.183:2379,192.168.2.184:2379]
[2023/09/25 18:24:59.048 +08:00] [INFO] [systime_mon.go:26] ["start system time monitor"]
[2023/09/25 18:24:59.048 +08:00] [ERROR] [cpu.go:65] [GetCgroupCPU] [error="error when reading cpu system time from cgroup v1 at /sys/fs/cgroup/cpu,cpuacct/system.slice/tidb-4000.service/cpuacct.usage_sys: open /sys/fs/cgroup/cpu,cpuacct/system.slice/tidb-4000.service/cpuacct.usage_sys: no such file or directory"]
[2023/09/25 18:24:59.053 +08:00] [INFO] [pd_service_discovery.go:632] ["[pd] switch leader"] [new-leader=http://192.168.2.182:2379] [old-leader=]
[2023/09/25 18:24:59.053 +08:00] [INFO] [pd_service_discovery.go:197] ["[pd] init cluster id"] [cluster-id=7165894089526527080]
[2023/09/25 18:24:59.054 +08:00] [INFO] [client.go:600] ["[pd] changing service mode"] [old-mode=UNKNOWN_SVC_MODE] [new-mode=PD_SVC_MODE]
[2023/09/25 18:24:59.054 +08:00] [INFO] [tso_client.go:230] ["[tso] switch dc tso global allocator serving address"] [dc-location=global] [new-address=http://192.168.2.182:2379]
[2023/09/25 18:24:59.054 +08:00] [INFO] [tso_dispatcher.go:318] ["[tso] tso dispatcher created"] [dc-location=global]
[2023/09/25 18:24:59.054 +08:00] [INFO] [client.go:648] ["[pd] service mode changed"] [old-mode=UNKNOWN_SVC_MODE] [new-mode=PD_SVC_MODE]
[2023/09/25 18:24:59.054 +08:00] [INFO] [tikv_driver.go:200] ["using API V1."]
[2023/09/25 18:24:59.055 +08:00] [INFO] [store.go:82] ["new store with retry success"]
[2023/09/25 18:24:59.056 +08:00] [INFO] [region_cache.go:2658] ["change store resolve state"] [store=2] [addr=192.168.2.182:20160] [from=unresolved] [to=resolved] [liveness-state=reachable]
[2023/09/25 18:24:59.056 +08:00] [INFO] [region_cache.go:2658] ["change store resolve state"] [store=7] [addr=192.168.2.183:20160] [from=unresolved] [to=resolved] [liveness-state=reachable]
[2023/09/25 18:24:59.056 +08:00] [INFO] [region_cache.go:2658] ["change store resolve state"] [store=1] [addr=192.168.2.184:20160] [from=unresolved] [to=resolved] [liveness-state=reachable]
[2023/09/25 18:24:59.060 +08:00] [FATAL] [terror.go:309] ["unexpected error"] [error="[meta:1050]table already exists"] [stack="github.com/pingcap/tidb/parser/terror.MustNil\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/parser/terror/terror.go:309\nmain.createStoreAndDomain\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/tidb-server/main.go:344\nmain.main\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/tidb-server/main.go:243\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:267"] [stack="github.com/pingcap/tidb/parser/terror.MustNil\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/parser/terror/terror.go:309\nmain.createStoreAndDomain\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/tidb-server/main.go:344\nmain.main\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/tidb-server/main.go:243\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:267"]

```

### 4. What is your TiDB version? (Required)
target: v7.1.1

i have only 1 tidb node and can not start normal now,So i can not connect  mysql --host 127.0.0.1 --port 4000 -u root,
how can i do this like #41104
 [manually delete the mysql.tidb_ddl_backfill and mysql.tidb_ddl_backfill_history with the old version tidb-server to solve this problem.

**Comment by seiya-annie** [comment] 2023-09-26 02:32
hi， could you please send us your source version?

**Comment by seiya-annie** [comment] 2023-09-26 03:56
i tried with v6.5.2 upgrade to v7.1.1, the cluster can be successfully upgrade to v7.1.1

**Comment by liuzx8888** [comment] 2023-09-26 05:53
@seiya-annie 
![80258cd8e7122fd87640f7e3b91b393](https://github.com/pingcap/tidb/assets/10862577/b8c70c02-896f-40f6-a0b1-1a20db7e6a19)

**Comment by liuzx8888** [comment] 2023-09-27 05:35
> i tried with v6.5.2 upgrade to v7.1.1, the cluster can be successfully upgrade to v7.1.1

6.6.0-alpha

**Comment by okJiang** [comment] 2023-09-27 05:53
@liuzx8888 I am sorry the relevant expert has gone on vacation. You may not get a more detailed analysis until 10 days later.

Please note

> Alpha releases might have some bugs and are available for users to test the latest features.
> ref https://docs.pingcap.com/tidb/stable/versioning#alpha-releases

If you want to discuss with colleagues in the community, you can go to asktug.com to post and discuss. 

If your situation is urgent, you can contact the relevant personnel to subscribe to advanced services https://cn.pingcap.com/contact/

**Comment by D3Hunter** [comment] 2024-04-28 02:41
as it happens on a internal version, and not able to reproduce in afficial released version, closed it.

**Closed by D3Hunter** 2024-04-28 02:41 UTC
Labels: type/bug, component/ddl, affects-8.1
