### ISSUE TITLE
sysbench OLTP is not stable when rand-type is pareto

### ISSUE THREAD

**Issue by zhangjinpeng1987** [pingcap/tidb#8305] opened 2018-11-14 03:02 UTC
## Bug Report

1. What did you do?
i find there is something wrong when i bench oltp read write case with rand-type is **pareto**.

When the rand-type is **uniform**, the qps is stable and perform good.
```
[ 24s ] thds: 32 tps: 1910.00 qps: 38202.93 (r/w/o: 26744.95/5920.99/5536.99) lat (ms,99%): 32.53 err/s: 0.00 reconn/s: 0.00
[ 25s ] thds: 32 tps: 1947.70 qps: 38951.97 (r/w/o: 27268.78/6015.07/5668.12) lat (ms,99%): 26.68 err/s: 0.00 reconn/s: 0.00
[ 26s ] thds: 32 tps: 1882.11 qps: 37610.18 (r/w/o: 26313.53/5835.34/5461.32) lat (ms,99%): 34.95 err/s: 0.00 reconn/s: 0.00
[ 27s ] thds: 32 tps: 1946.93 qps: 38953.53 (r/w/o: 27291.97/6005.77/5655.79) lat (ms,99%): 27.66 err/s: 0.00 reconn/s: 0.00
[ 28s ] thds: 32 tps: 1971.04 qps: 39432.76 (r/w/o: 27588.53/6078.12/5766.11) lat (ms,99%): 25.74 err/s: 0.00 reconn/s: 0.00
[ 29s ] thds: 32 tps: 1972.05 qps: 39463.01 (r/w/o: 27642.70/6073.15/5747.15) lat (ms,99%): 26.20 err/s: 0.00 reconn/s: 0.00
[ 30s ] thds: 32 tps: 1925.16 qps: 38523.14 (r/w/o: 26939.19/5922.48/5661.46) lat (ms,99%): 27.17 err/s: 0.00 reconn/s: 0.00
[ 31s ] thds: 32 tps: 1983.10 qps: 39701.08 (r/w/o: 27787.46/6096.25/5817.37) lat (ms,99%): 25.74 err/s: 0.00 reconn/s: 0.00
[ 32s ] thds: 32 tps: 1980.80 qps: 39449.85 (r/w/o: 27623.10/6060.44/5766.32) lat (ms,99%): 25.28 err/s: 0.00 reconn/s: 0.00
[ 33s ] thds: 32 tps: 1971.82 qps: 39555.34 (r/w/o: 27695.44/6151.43/5708.47) lat (ms,99%): 24.83 err/s: 0.00 reconn/s: 0.00
[ 34s ] thds: 32 tps: 1968.24 qps: 39309.77 (r/w/o: 27526.34/6000.73/5782.70) lat (ms,99%): 29.19 err/s: 0.00 reconn/s: 0.00
[ 35s ] thds: 32 tps: 1962.98 qps: 39228.65 (r/w/o: 27431.75/6111.94/5684.95) lat (ms,99%): 29.19 err/s: 0.00 reconn/s: 0.00
[ 36s ] thds: 32 tps: 1949.21 qps: 38939.21 (r/w/o: 27259.94/5975.65/5703.62) lat (ms,99%): 30.26 err/s: 0.00 reconn/s: 0.00
[ 37s ] thds: 32 tps: 1948.00 qps: 39059.94 (r/w/o: 27390.96/5972.99/5695.99) lat (ms,99%): 29.72 err/s: 0.00 reconn/s: 0.00
[ 38s ] thds: 32 tps: 1965.04 qps: 39220.77 (r/w/o: 27397.54/6132.12/5691.11) lat (ms,99%): 25.74 err/s: 0.00 reconn/s: 0.00
[ 39s ] thds: 32 tps: 1941.95 qps: 38891.03 (r/w/o: 27234.32/5964.85/5691.86) lat (ms,99%): 33.12 err/s: 0.00 reconn/s: 0.00
```

But when i change the rand-type to **pareto**, TiDB is very unstable, the output is like this:
```
[ 112s ] thds: 32 tps: 217.02 qps: 4304.30 (r/w/o: 3012.21/815.06/477.03) lat (ms,99%): 219.36 err/s: 0.00 reconn/s: 0.00
[ 113s ] thds: 32 tps: 52.00 qps: 1028.05 (r/w/o: 717.04/207.01/104.01) lat (ms,99%): 23.95 err/s: 0.00 reconn/s: 0.00
[ 114s ] thds: 32 tps: 36.00 qps: 731.09 (r/w/o: 514.07/135.02/82.01) lat (ms,99%): 2680.11 err/s: 0.00 reconn/s: 0.00
[ 115s ] thds: 32 tps: 390.00 qps: 7821.97 (r/w/o: 5471.98/1516.99/833.00) lat (ms,99%): 4280.32 err/s: 0.00 reconn/s: 0.00
[ 116s ] thds: 32 tps: 840.87 qps: 16852.45 (r/w/o: 11794.21/3267.50/1790.73) lat (ms,99%): 4517.90 err/s: 0.00 reconn/s: 0.00
[ 117s ] thds: 32 tps: 961.89 qps: 19168.82 (r/w/o: 13434.47/3659.58/2074.76) lat (ms,99%): 314.45 err/s: 0.00 reconn/s: 0.00
[ 118s ] thds: 32 tps: 1071.35 qps: 21557.02 (r/w/o: 15096.92/4168.36/2291.75) lat (ms,99%): 292.60 err/s: 0.00 reconn/s: 0.00
[ 119s ] thds: 32 tps: 1045.87 qps: 20844.36 (r/w/o: 14583.15/3999.49/2261.71) lat (ms,99%): 262.64 err/s: 0.00 reconn/s: 0.00
[ 120s ] thds: 32 tps: 457.06 qps: 9083.24 (r/w/o: 6353.87/1744.24/985.13) lat (ms,99%): 253.35 err/s: 0.00 reconn/s: 0.00
[ 121s ] thds: 32 tps: 0.00 qps: 0.00 (r/w/o: 0.00/0.00/0.00) lat (ms,99%): 0.00 err/s: 0.00 reconn/s: 0.00
[ 122s ] thds: 32 tps: 0.00 qps: 0.00 (r/w/o: 0.00/0.00/0.00) lat (ms,99%): 0.00 err/s: 0.00 reconn/s: 0.00
[ 123s ] thds: 32 tps: 6.00 qps: 113.99 (r/w/o: 77.99/23.00/13.00) lat (ms,99%): 3511.19 err/s: 0.00 reconn/s: 0.00
[ 124s ] thds: 32 tps: 472.05 qps: 9499.93 (r/w/o: 6654.65/1813.18/1032.10) lat (ms,99%): 4358.09 err/s: 0.00 reconn/s: 0.00
[ 125s ] thds: 32 tps: 809.96 qps: 16237.12 (r/w/o: 11357.38/3140.83/1738.91) lat (ms,99%): 4683.57 err/s: 0.00 reconn/s: 0.00
```

2. What did you expect to see?
The QPS is stable, and the .99 latency is reasonable(below 50ms).

3. What did you see instead?
The QPS can drop to 0, and the .99 latency can reach to several seconds.

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
Release Version: v2.1.0-rc.3-140-g47ac8ae
Git Commit Hash: 47ac8aef1971b84b317b3179c1d2e4ce06468eb8
Git Branch: master
UTC Build Time: 2018-11-03 04:12:14

Further more, i turn off the txn-latch:
```
txn_local_latches:
  enabled: false
```

**Comment by tiancaiamao** [comment] 2018-11-14 03:08
Thanks for your report, I'll take a look. @zhangjinpeng1987

**Comment by zhangjinpeng1987** [comment] 2018-11-14 03:35
After i enable the txn-latch, the QPS will not drop to 0, but the performance is extremely low. By the way, i have 32 tables, and 5000,000 rows for each table.
```
[ 9s ] thds: 32 tps: 89.01 qps: 2061.19 (r/w/o: 1431.13/435.04/195.02) lat (ms,99%): 1648.20 err/s: 0.00 reconn/s: 0.00
[ 10s ] thds: 32 tps: 104.99 qps: 2135.80 (r/w/o: 1491.86/418.96/224.98) lat (ms,99%): 893.56 err/s: 0.00 reconn/s: 0.00
[ 11s ] thds: 32 tps: 86.01 qps: 1677.20 (r/w/o: 1181.14/312.04/184.02) lat (ms,99%): 831.46 err/s: 0.00 reconn/s: 0.00
[ 12s ] thds: 32 tps: 81.99 qps: 1569.86 (r/w/o: 1092.90/302.97/173.98) lat (ms,99%): 1304.21 err/s: 0.00 reconn/s: 0.00
[ 13s ] thds: 32 tps: 71.01 qps: 1440.14 (r/w/o: 1015.10/275.03/150.01) lat (ms,99%): 909.80 err/s: 0.00 reconn/s: 0.00
[ 14s ] thds: 32 tps: 53.00 qps: 1034.97 (r/w/o: 721.98/201.99/111.00) lat (ms,99%): 1280.93 err/s: 0.00 reconn/s: 0.00
[ 15s ] thds: 32 tps: 80.00 qps: 1518.94 (r/w/o: 1059.96/292.99/165.99) lat (ms,99%): 1129.24 err/s: 0.00 reconn/s: 0.00
[ 16s ] thds: 32 tps: 90.99 qps: 1899.69 (r/w/o: 1339.78/364.94/194.97) lat (ms,99%): 1258.08 err/s: 0.00 reconn/s: 0.00
[ 17s ] thds: 32 tps: 78.01 qps: 1630.19 (r/w/o: 1136.13/321.04/173.02) lat (ms,99%): 831.46 err/s: 0.00 reconn/s: 0.00
[ 18s ] thds: 32 tps: 61.01 qps: 1245.12 (r/w/o: 865.09/250.02/130.01) lat (ms,99%): 995.51 err/s: 0.00 reconn/s: 0.00
[ 19s ] thds: 32 tps: 106.98 qps: 2089.55 (r/w/o: 1469.69/387.92/231.95) lat (ms,99%): 1304.21 err/s: 0.00 reconn/s: 0.00
[ 20s ] thds: 32 tps: 52.01 qps: 1084.20 (r/w/o: 757.14/218.04/109.02) lat (ms,99%): 1129.24 err/s: 0.00 reconn/s: 0.00
[ 21s ] thds: 32 tps: 92.99 qps: 1847.87 (r/w/o: 1292.91/348.98/205.99) lat (ms,99%): 1304.21 err/s: 0.00 reconn/s: 0.00
[ 22s ] thds: 32 tps: 57.00 qps: 1157.99 (r/w/o: 807.99/226.00/124.00) lat (ms,99%): 1032.01 err/s: 0.00 reconn/s: 0.00
[ 23s ] thds: 32 tps: 61.00 qps: 1104.06 (r/w/o: 776.04/190.01/138.01) lat (ms,99%): 1648.20 err/s: 0.00 reconn/s: 0.00
[ 24s ] thds: 32 tps: 96.01 qps: 2041.18 (r/w/o: 1425.13/414.04/202.02) lat (ms,99%): 1589.90 err/s: 0.00 reconn/s: 0.00
[ 25s ] thds: 32 tps: 127.99 qps: 2542.86 (r/w/o: 1788.90/479.97/273.98) lat (ms,99%): 669.89 err/s: 0.00 reconn/s: 0.00
[ 26s ] thds: 32 tps: 65.00 qps: 1210.01 (r/w/o: 834.00/246.00/130.00) lat (ms,99%): 960.30 err/s: 0.00 reconn/s: 0.00
[ 27s ] thds: 32 tps: 52.97 qps: 992.52 (r/w/o: 714.65/167.92/109.95) lat (ms,99%): 1869.60 err/s: 0.00 reconn/s: 0.00
[ 28s ] thds: 32 tps: 87.04 qps: 1905.82 (r/w/o: 1313.56/403.17/189.08) lat (ms,99%): 1589.90 err/s: 0.00 reconn/s: 0.00
[ 29s ] thds: 32 tps: 88.00 qps: 1696.06 (r/w/o: 1194.05/317.01/185.01) lat (ms,99%): 1427.08 err/s: 0.00 reconn/s: 0.00
[ 30s ] thds: 32 tps: 51.00 qps: 1015.97 (r/w/o: 713.98/191.99/110.00) lat (ms,99%): 1013.60 err/s: 0.00 reconn/s: 0.00
[ 31s ] thds: 32 tps: 84.00 qps: 1668.96 (r/w/o: 1171.97/319.99/177.00) lat (ms,99%): 1453.01 err/s: 0.00 reconn/s: 0.00
```

**Comment by nullnotnil** [comment] 2020-07-11 13:12
I tried to reproduce this on master (where several things have changed since 2018: the default is now pessimistic locking):

```bash
#  Prepare 32 tables, 5M rows each

sysbench /usr/share/sysbench/oltp_read_write.lua --mysql-host=127.0.0.1 --mysql-port=4000 --mysql-user=root --mysql-db=test --table-size=5000000 --tables=32 prepare

# run uniform first

sleep 1200

sysbench /usr/share/sysbench/oltp_read_write.lua --mysql-host=127.0.0.1 --mysql-port=4000 --mysql-user=root --mysql-db=test --table-size=5000000 --tables=32 --rand-type=uniform --threads=32 --time=1200 --report-interval=1 run | tee uniform.txt

# Garbage collection is set to 10mins (default) - so test length is longer.
# Sleep for 20 minutes in between to give GC a fair chance to catch up.

sleep 1200

# run pareto

sysbench /usr/share/sysbench/oltp_read_write.lua --mysql-host=127.0.0.1 --mysql-port=4000 --mysql-user=root --mysql-db=test --table-size=5000000 --tables=32 --rand-type=pareto --threads=32 --time=1200 --report-interval=1 run | tee pareto.txt

```

Pareto is now stable - there are no periods where tps drops to zero. May I suggest we close this issue as stale for now?

Output from test runs attached.

[pareto.txt](https://github.com/pingcap/tidb/files/4906812/pareto.txt)
[uniform.txt](https://github.com/pingcap/tidb/files/4906813/uniform.txt)

**Comment by nullnotnil** [comment] 2020-07-20 15:40
Closing this issue for now.

**Closed by nullnotnil** 2020-07-20 15:40 UTC
Labels: type/bug, type/performance
