### ISSUE TITLE
SELECT 'a'='a ' , 'a'='A' , 'a'='A ' not same to MySQL in TiDB

### ISSUE THREAD

**Issue by yangwenmai** [pingcap/tidb#12806] opened 2019-10-18 02:12 UTC
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

```sh
mysql> select 'a'='a ' , 'a'='A' , 'a'='A ';
```

2. What did you expect to see?

```sh
mysql> select 'a'='a ' , 'a'='A' , 'a'='A ';
'a'='a '	'a'='A'	'a'='A '
1	1	1
```

3. What did you see instead?

```sh
mysql> select 'a'='a ' , 'a'='A' , 'a'='A ';
'a'='a '	'a'='A'	'a'='A '
0	0	0
```

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

tidb-server(e1ba30914)

more details: https://asktug.com/t/mysqlslap-tidb-varbinary-varchar-select-bug/1434

**Comment by winoros** [comment] 2019-10-18 03:33
I think this is a known compability issue instead of bug.

**Comment by edytagarbarz** [comment] 2019-11-13 09:39
Based on this [comment](https://github.com/pingcap/tidb/blob/6b9703bc5f8c77ce3350c8880958b44fef53b7b7/expression/builtin_like.go#L65) comparing is case sensitive because of tikv. This comment is 2 years old. Is compatibility with tikv still more important than compatibility with MySQL?

**Comment by nullnotnil** [comment] 2020-08-06 14:28
The root cause of this, is that TiDB defaults to binary collation. MySQL defaults to a case-insensitive collation.

Support for collations is currently experimental in TiDB. When enabled, the behavior will be the same as MySQL:
```sql
mysql> select 'a'='a ' , 'a'='A' , 'a'='A ';
+----------+---------+----------+
| 'a'='a ' | 'a'='A' | 'a'='A ' |
+----------+---------+----------+
|        1 |       1 |        1 |
+----------+---------+----------+
1 row in set (0.00 sec)

mysql> SELECT tidb_version()\G
*************************** 1. row ***************************
tidb_version(): Release Version: v4.0.0-beta.2-893-g4e829aaee
Edition: Community
Git Commit Hash: 4e829aaee7b656aa807814708ae05af5233302af
Git Branch: master
UTC Build Time: 2020-08-04 12:40:52
GoVersion: go1.13
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
1 row in set (0.00 sec)
```

If you would like to test this out, the instructions for enabling new collations are [documented here](https://docs.pingcap.com/tidb/stable/character-set-and-collation#new-framework-for-collations).

You can track the progress of collation work in this project: https://github.com/pingcap/tidb/projects/33

I am going to close this issue for now, since it is a duplicate of https://github.com/pingcap/tidb/projects/33. Please feel free to re-open if you would like to ask additional questions. Thanks!

**Closed by nullnotnil** 2020-08-06 14:28 UTC
Labels: type/compatibility
