### ISSUE TITLE
can't get partition column name, use parser module

### ISSUE THREAD

**Issue by daiguadaidai** [pingcap/tidb#7715] opened 2018-09-16 05:41 UTC
## can't get partition column name, use parser module
I use partition module parse create table Statement, but can't get partition name

my code:
```
	sql := `
CREATE TABLE test.mf_fd_cache (
  id bigint(18) NOT NULL AUTO_INCREMENT COMMENT '注释',
  uptime datetime NOT NULL DEFAULT '1000-10-10 10:10:10' Comment '注释',
  PRIMARY KEY (id)
) ENGINE=InnoDb  DEFAULT CHARSET=Utf8mb4 COLLATE=Utf8mb4_general_ci comment="注释"
 PARTITION BY RANGE(uptime)(
     PARTITION p0 VALUES LESS THAN (TO_DAYS('2010-04-15')),
     PARTITION p19 VALUES LESS ThAN  MAXVALUE
 );
    `

	sqlParser := parser.New()
	stmtNodes, err := sqlParser.Parse(sql, "", "")
	if err != nil {
		fmt.Printf("Syntax Error: %v", err)
	}

	// 循环每一个sql语句进行解析, 并且生成相关审核信息
	for _, stmtNode := range stmtNodes {
		createTableStmt := stmtNode.(*ast.CreateTableStmt)
		fmt.Printf("Schema: %v, Table: %v\n", createTableStmt.Table.Schema.String(),
		createTableStmt.Table.Name.String())

		fmt.Println("Partition type:", createTableStmt.Partition.Tp.String())
		fmt.Println("Partition cols:", createTableStmt.Partition.ColumnNames)
		// 字段
		for _, columnName := range createTableStmt.Partition.ColumnNames {
			fmt.Printf("%v, ", columnName)
		}

		// partition 定义
		for _, definition := range createTableStmt.Partition.Definitions {
			fmt.Printf("partition definition： %v, %v, %v \n",
				definition.Name, definition.Comment, definition.MaxValue)
		}

		fmt.Println("")
	}
```
Output:
```
Schema: test, Table: mf_fd_cache
Partition type: RANGE
Partition cols: []
partition definition： p0, , false 
partition definition： p19, , false 
```
`Partition.ColumnNames` not found value or expression

what should I do

**Comment by jackysp** [comment] 2018-09-16 12:02
Thanks for your feedback, @daiguadaidai ! PTAL @tiancaiamao .

**Comment by daiguadaidai** [comment] 2018-09-16 12:14
@jackysp @tiancaiamao 
I have solved it.
`createTableStmt.Partition.ColumnNames` only use `range partition range columns(id, uptime)` have value.

**Comment by jackysp** [comment] 2018-09-16 13:04
Nice to see that the problem is solved.
@daiguadaidai , I will close this issue.

**Comment by daiguadaidai** [comment] 2018-09-16 13:40
> Nice to see that the problem is solved.
> @daiguadaidai , I will close this issue.

nopthanks

**Closed** 2018-09-17 05:44 UTC
Labels: question
