### ISSUE TITLE
Optimizer may not choose the best query plan for TPC-H

### ISSUE THREAD

**Issue by JaySon-Huang** [pingcap/tidb#17295] opened 2020-05-19 11:47 UTC
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

On DBaas / AWS EC2, deploy a cluster with TiFlash
(2 TiDB, 3 PD, 3 TiKV, 3 TiFlash. TiKV & TiFlash deployed in the same host)

Load TPC-H dataset  (scale factor=10) with `tiup bench`:
```
tiup bench tpch prepare \
    --host ${tidb_host} --port 4000 --db tpch_10 --password ${password} \
    --sf 10 \
    --tiflash \
    --analyze --tidb_build_stats_concurrency 8 --tidb_distsql_scan_concurrency 30
```

### 2. What did you expect to see? (Required)

If we create TiFlash replica for those tables, all performance of queries for those tables won't decrease.

### 3. What did you see instead (Required)

TiDB can NOT choose the best plan for some queries.
On DBaas: Q8, Q16 is not the best.
On AWS EC2: Q3, Q5, Q8, Q16 is not the best.

For Q8: use TiKV engine isolation is better.
For Q16: use TiFlash engine isolation is better.

You can check these links to see more details result:
* [TPC-H on AWS EC2 (3.0 vs 4.0)](https://docs.google.com/spreadsheets/d/1J1wQDABav-Ex24ZiNFxRiN07iGeVkFMXd_44Eoq1Y0I/edit#gid=0)，"raw statistics" tab
* [TPC-H benchmark on DBaaS](https://docs.google.com/spreadsheets/d/1vip9fg05Ix33vPG1H4E7YGpbsHO3EC4MBUe-901Cs2s/edit#gid=0)

### 4. Affected version (Required)

v4.0.0-rc.1

**Comment by zz-jason** [comment] 2020-06-02 02:27
@lzmhhh123 PTAL as well.

**Comment by lzmhhh123** [comment] 2020-06-02 09:53
I have reproduced it on TPC-H 50G.

For Q8:
- when "join lineitem" table, the better plan is to choose `index join + TiKV`, but CBO chooses `hash join + TiFlash` in this case.

For Q16:
- when "join partsupp" table, the better plan is to choose `hash join + TiFlash`, but CBO choose `index join + TiKV` in this case.

At last:
- I debug the cost estimation step by step, then found that if the join results estimation is more accurate. They can be both chosen the right plan.

**Comment by lzmhhh123** [comment] 2020-06-02 09:56
For the two cases, the probe sides of the joins both have the composite primary key as the join key. So I think we can improve the join result estimation by considering the `unique key`.

**Comment by zz-jason** [comment] 2020-06-02 15:40
> For the two cases, the probe sides of the joins both have the composite primary key as the join key. So I think we can improve the join result estimation by considering the `unique key`.

@lzmhhh123 can we use the two strategies described in  https://github.com/pingcap/tidb/issues/17185 to fix this issue? These two strategies are:
1. [estimate the row count of join result by the foreign key assumption](https://github.com/pingcap/tidb/issues/17185#issuecomment-637192027)
2. [make NDV estimation more accurate by checking indexes firstly](https://github.com/pingcap/tidb/issues/17185#issuecomment-637248968)

**Comment by lzmhhh123** [comment] 2020-06-03 03:04
[stats_issue17295.zip](https://github.com/pingcap/tidb/files/4720795/stats_issue17295.zip)
Here are the statistics.

**Comment by lzmhhh123** [comment] 2020-06-03 03:06
> > For the two cases, the probe sides of the joins both have the composite primary key as the join key. So I think we can improve the join result estimation by considering the `unique key`.
> 
> @lzmhhh123 can we use the two strategies described in #17185 to fix this issue? These two strategies are:
> 
> 1. [estimate the row count of join result by the foreign key assumption](https://github.com/pingcap/tidb/issues/17185#issuecomment-637192027)
> 2. [make NDV estimation more accurate by checking indexes firstly](https://github.com/pingcap/tidb/issues/17185#issuecomment-637248968)

For TPC-H, there is none foreign key for a table. So in my opinion, maybe the second improvement is effective.

**Comment by zz-jason** [comment] 2020-06-03 05:35
> For TPC-H, there is none foreign key for a table.

Yes. The first strategy is based on an implicit foreign key assumption. It assumes that the join key on table B(child table) can be found in table A(parent table). The join result row count estimation can be improved to another formula Based on this assumption.

**Comment by lzmhhh123** [comment] 2020-12-17 03:38
The root cause for this issue is the same as https://github.com/pingcap/tidb/issues/17185. So I mark this duplicated and close it.

**Closed** 2020-12-17 03:38 UTC
Labels: severity/major, sig/planner, type/bug, type/duplicate
