### ISSUE TITLE
HEX + CONVERT / INSERT with utf8 returns different values with MySQL

### ISSUE THREAD

**Issue by espresso98** [pingcap/tidb#32599] opened 2022-02-24 05:28 UTC
### 1. Minimal reproduce step
```sql
select hex(convert(char(2557 using latin1) using utf8));
SELECT HEX(INSERT(_utf8 0xD18FD18E, 2, 1, 0x20));
```
### 2. What did you expect to see? 
```sql
mysql>  select hex(convert(char(2557 using latin1) using utf8));
+--------------------------------------------------+
| hex(convert(char(2557 using latin1) using utf8)) |
+--------------------------------------------------+
| 09C3BD                                           |
+--------------------------------------------------+
1 row in set, 1 warning (0.01 sec)

mysql> SELECT HEX(INSERT(_utf8 0xD18FD18E, 2, 1, 0x20));
+-------------------------------------------+
| HEX(INSERT(_utf8 0xD18FD18E, 2, 1, 0x20)) |
+-------------------------------------------+
| D18F20                                    |
+-------------------------------------------+
1 row in set, 1 warning (0.01 sec)

mysql> select version();
+-----------+
| version() |
+-----------+
| 8.0.28    |
+-----------+
1 row in set (0.03 sec)
```

### 3. What did you see instead 
```sql
tidb> select hex(convert(char(2557 using latin1) using utf8));
+--------------------------------------------------+
| hex(convert(char(2557 using latin1) using utf8)) |
+--------------------------------------------------+
| 093F                                             |
+--------------------------------------------------+
1 row in set (0.01 sec)

tidb> SELECT HEX(INSERT(_utf8 0xD18FD18E, 2, 1, 0x20));
+-------------------------------------------+
| HEX(INSERT(_utf8 0xD18FD18E, 2, 1, 0x20)) |
+-------------------------------------------+
| D120D18E                                  |
+-------------------------------------------+
1 row in set (0.02 sec)
```

### 4. What is your TiDB version? 
```
tidb_version(): Release Version: v5.5.0-alpha-210-g11f4ca802
Edition: Community
Git Commit Hash: 11f4ca802083ee38d5972730ba8f9b72395316fb
Git Branch: master
UTC Build Time: 2022-02-24 04:52:01
GoVersion: go1.17.2
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
```

**Comment by aytrack** [comment] 2022-02-24 09:09
for the first case, it's may cause by this as describe in https://docs.pingcap.com/tidb/stable/character-set-and-collation#character-sets-and-collations-supported-by-tidb

> TiDB incorrectly treats latin1 as a subset of utf8. This can lead to unexpected behaviors when you store characters that differ between latin1 and utf8 encodings. It is strongly recommended to the utf8mb4 character set. See [TiDB #18955](https://github.com/pingcap/tidb/issues/18955) for more details.

but there maybe another bug here
```sql
MySQL root@127.0.0.1:(none)> select char(2557 using latin1)
'utf-8' codec can't decode byte 0xfd in position 1: invalid start byte
MySQL root@127.0.0.1:(none)> use test;
Packet sequence number wrong - got 5 expected 1
```

case 2:
tidb has the same behavior with mysql 8.0.23

```sql
mysql> select version();
+-----------+
| version() |
+-----------+
| 8.0.26    |
+-----------+
1 row in set (0.04 sec)

mysql> SELECT HEX(INSERT(_utf8 0xD18FD18E, 2, 1, 0x20));
+-------------------------------------------+
| HEX(INSERT(_utf8 0xD18FD18E, 2, 1, 0x20)) |
+-------------------------------------------+
| D18F20                                    |
+-------------------------------------------+
1 row in set, 1 warning (0.04 sec)


# mysql 8.0.23

MySQL root@172.16.5.103:test> SELECT HEX(INSERT(_utf8 0xD18FD18E, 2, 1, 0x20));
+-------------------------------------------+
| HEX(INSERT(_utf8 0xD18FD18E, 2, 1, 0x20)) |
+-------------------------------------------+
| D120D18E                                  |
+-------------------------------------------+

1 row in set
Time: 0.062s
MySQL root@172.16.5.103:test>
MySQL root@172.16.5.103:test> select version();
+-----------+
| version() |
+-----------+
| 8.0.23    |
+-----------+


```

**Comment by aytrack** [comment] 2022-02-24 09:13
tidb v5.3.0 has a same behavior  with mysql 8.0.26, but since v5.4.0 the behavior is changed.
```sql
MySQL root@127.0.0.1:(none)> select tidb_version()\G
***************************[ 1. row ]***************************
tidb_version() | Release Version: v5.3.0
Edition: Community
Git Commit Hash: 4a1b2e9fe5b5afb1068c56de47adb07098d768d6
Git Branch: heads/refs/tags/v5.3.0
UTC Build Time: 2021-11-24 13:31:24
GoVersion: go1.16.5
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false

1 row in set
Time: 0.001s
MySQL root@127.0.0.1:(none)> SELECT HEX(INSERT(_utf8 0xD18FD18E, 2, 1, 0x20));
                         ->
+-------------------------------------------+
| HEX(INSERT(_utf8 0xD18FD18E, 2, 1, 0x20)) |
+-------------------------------------------+
| D18F20                                    |
+-------------------------------------------+
```

**Comment by espresso98** [comment] 2022-02-24 16:40
Thanks. I am working on MySQL v.8.0.28

**Comment by solotzg** [comment] 2022-06-06 04:02
For mysql 8.0.29, ` LENGTH(INSERT(_utf8 0xD18FD18E, 2, 1, 0x20))` is 3 but `LENGTH(INSERT(0xD18FD18E, 2, 1, 0x20))` is 4.

```
mysql> select version();
+-----------+
| version() |
+-----------+
| 8.0.29    |
+-----------+
1 row in set (0.00 sec)

mysql> SELECT LENGTH(INSERT(_utf8 0xD18FD18E, 2, 1, 0x20));
+----------------------------------------------+
| LENGTH(INSERT(_utf8 0xD18FD18E, 2, 1, 0x20)) |
+----------------------------------------------+
|                                            3 |
+----------------------------------------------+
1 row in set, 1 warning (0.00 sec)

mysql> SELECT HEX(INSERT(_utf8 0xD18FD18E, 2, 1, 0x20));
+-------------------------------------------+
| HEX(INSERT(_utf8 0xD18FD18E, 2, 1, 0x20)) |
+-------------------------------------------+
| D18F20                                    |
+-------------------------------------------+
1 row in set, 1 warning (0.00 sec)

mysql> SELECT HEX(INSERT(0xD18FD18E, 2, 1, 0x20));
+-------------------------------------+
| HEX(INSERT(0xD18FD18E, 2, 1, 0x20)) |
+-------------------------------------+
| D120D18E                            |
+-------------------------------------+
1 row in set (0.00 sec)

mysql> SELECT LENGTH(INSERT(0xD18FD18E, 2, 1, 0x20));
+----------------------------------------+
| LENGTH(INSERT(0xD18FD18E, 2, 1, 0x20)) |
+----------------------------------------+
|                                      4 |
+----------------------------------------+
1 row in set (0.00 sec)
```

For tidb, ` LENGTH(INSERT(_utf8 0xD18FD18E, 2, 1, 0x20))` and `LENGTH(INSERT(0xD18FD18E, 2, 1, 0x20))` are 4.

```
MySQL [test]> select version();
+----------------------------+
| version()                  |
+----------------------------+
| 5.7.25-TiDB-v6.1.0-nightly |
+----------------------------+
1 row in set (0.00 sec)

MySQL [test]> SELECT LENGTH(INSERT(_utf8 0xD18FD18E, 2, 1, 0x20));
+----------------------------------------------+
| LENGTH(INSERT(_utf8 0xD18FD18E, 2, 1, 0x20)) |
+----------------------------------------------+
|                                            4 |
+----------------------------------------------+
1 row in set (0.00 sec)

MySQL [test]> SELECT HEX(INSERT(_utf8 0xD18FD18E, 2, 1, 0x20));
+-------------------------------------------+
| HEX(INSERT(_utf8 0xD18FD18E, 2, 1, 0x20)) |
+-------------------------------------------+
| D120D18E                                  |
+-------------------------------------------+
1 row in set (0.00 sec)

MySQL [test]> SELECT HEX(INSERT(0xD18FD18E, 2, 1, 0x20));
+-------------------------------------+
| HEX(INSERT(0xD18FD18E, 2, 1, 0x20)) |
+-------------------------------------+
| D120D18E                            |
+-------------------------------------+
1 row in set (0.00 sec)

MySQL [test]> SELECT LENGTH(INSERT(0xD18FD18E, 2, 1, 0x20));
+----------------------------------------+
| LENGTH(INSERT(0xD18FD18E, 2, 1, 0x20)) |
+----------------------------------------+
|                                      4 |
+----------------------------------------+
1 row in set (0.00 sec)
```

**Comment by solotzg** [comment] 2022-06-06 04:07
For tidb master, the behaviors when handling latin1 is different with mysql.

```
MySQL [test]> select version();
+----------------------------+
| version()                  |
+----------------------------+
| 5.7.25-TiDB-v6.1.0-nightly |
+----------------------------+
1 row in set (0.00 sec)

MySQL [test]> select hex(convert(char(2557 using latin1) using utf8));
+--------------------------------------------------+
| hex(convert(char(2557 using latin1) using utf8)) |
+--------------------------------------------------+
| NULL                                             |
+--------------------------------------------------+
1 row in set, 1 warning (0.00 sec)

MySQL [test]> show warnings;
+---------+------+---------------------------------------+
| Level   | Code | Message                               |
+---------+------+---------------------------------------+
| Warning | 1300 | Invalid latin1 character string: 'FD' |
+---------+------+---------------------------------------+
1 row in set (0.00 sec)
```

**Comment by solotzg** [comment] 2022-06-17 08:46
For `SELECT HEX(INSERT(_utf8 0xD18FD18E, 2, 1, 0x20));`

According to https://dev.mysql.com/doc/refman/8.0/en/string-functions.html#function_insert, `INSERT(str,pos,len,newstr)` use str as input. Convert `_utf8 0xD18FD18E` to string will be 0xD18F 0xD18E in hex.

`INSERT(_utf8 0xD18FD18E, 2, 1, 0x20)` will replace 0xD18E by 0x20 and get 0xD18F20 finally.

**Comment by zanmato1984** [comment] 2022-06-23 08:42
Seems like some encoding/collation change broke some of our old behavior, thus this issue. Changing to sig/sql-infra.

**Comment by YangKeao** [comment] 2022-10-12 08:03
This problem is caused by type infer. As the third forth arguments of `INSERT` is a binary charset/collation, the return type of INSERT is inferred as binary. The following statement can be a workaround:

```
MySQL [(none)]> SELECT HEX(INSERT(_utf8 0xD18FD18E, 2, 1, _utf8 0x20));
+-------------------------------------------------+
| HEX(INSERT(_utf8 0xD18FD18E, 2, 1, _utf8 0x20)) |
+-------------------------------------------------+
| D18F20                                          |
+-------------------------------------------------+
1 row in set (1.646 sec)
```

**Comment by YangKeao** [comment] 2022-10-12 08:37
I don't know whether the binary return type is expected (it actually sounds good). The key problem is that the insert chooses to cast charset according to the return type, but not the first argument. This change is brought by https://github.com/pingcap/tidb/pull/29905 .

**Comment by YangKeao** [comment] 2022-10-13 09:43
> well, I remember the behavior is the same with the MySQL version before 8.0.24

The behavior of `SELECT HEX(INSERT(_utf8 0xD18FD18E, 2, 1, 0x20));` is compatible with older version of MySQL (so does lpad/rpad/...)

I'll close this issue as it's expected (both problems). If you need further discussion, feel free to reopen this issue :smiley: .

**Closed by YangKeao** 2022-10-13 09:43 UTC
Labels: type/bug, sig/sql-infra, severity/major, affects-5.4, affects-6.0, affects-6.1, affects-6.2, affects-6.3
