### ISSUE TITLE
Cast string to double on join column with index return incompatible result with MySQL

### ISSUE THREAD

**Issue by pcqz** [pingcap/tidb#52167] opened 2024-03-27 14:16 UTC
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
create table t(a bigint, b varchar(50), key idx(a));
create table t1(b varchar(50));
insert into t values(13790462480960267,'13790462480960267');
insert into t values(13790462480960268,'13790462480960267');
insert into t values(13790462480960269,'13790462480960267');
insert into t1 values ('13790462480960267');
select t.a from t, t1 where t.a=t1.b;
```

### 2. What did you expect to see? (Required)

MySQL 5.7.34, 8.0.36
```
mysql> select t.a from t, t1 where t.a=t1.b;
+-------------------+
| a                 |
+-------------------+
| 13790462480960267 |
+-------------------+
1 row in set (0.00 sec)
```

However, after dropping the `idx` index, MySQL returns inconsistent result that's the same as TiDB. This looks like a bug or a special case for MySQL.
```
mysql> alter table t drop index idx;

mysql> select t.a from t, t1 where t.a=t1.b;
+-------------------+
| a                 |
+-------------------+
| 13790462480960267 |
| 13790462480960268 |
| 13790462480960269 |
+-------------------+
3 rows in set (0.00 sec)
```

### 3. What did you see instead (Required)
TiDB
```
mysql> select t.a from t, t1 where t.a=t1.b;
+-------------------+
| a                 |
+-------------------+
| 13790462480960267 |
| 13790462480960268 |
| 13790462480960269 |
+-------------------+
3 rows in set (0.00 sec)

mysql> alter table t drop index idx;

mysql> select t.a from t, t1 where t.a=t1.b;
+-------------------+
| a                 |
+-------------------+
| 13790462480960267 |
| 13790462480960268 |
| 13790462480960269 |
+-------------------+
3 rows in set (0.01 sec)
```

### 4. What is your TiDB version? (Required)

v7.6.0

**Comment by windtalker** [comment] 2024-03-28 06:46
Because for `t.a = t1.b`, `t.a` is integer type and `t1.b` is varchar, according to MySQL's compare behavior, both `t.a` and `t1.b` should be converted to double before compare
```
mysql> select cast(t.a as double) from t;
+-----------------------+
| cast(t.a as double)   |
+-----------------------+
| 1.3790462480960268e16 |
| 1.3790462480960268e16 |
| 1.3790462480960268e16 |
+-----------------------+
3 rows in set (0.00 sec)

mysql> select cast(t1.b as double) from t1;
+-----------------------+
| cast(t1.b as double)  |
+-----------------------+
| 1.3790462480960268e16 |
+-----------------------+
1 row in set (0.00 sec)

```
After cast them to double, the result is the same

**Comment by windtalker** [comment] 2024-03-28 06:55
I prefer to close this as Not A Bug since 
1. MySQL returns inconsistent result with/without index
2. The TiDB's result is correct since it is expected as `cast(string/integer as double)` may loss precision, even the results looks counter-intuitive

**Closed** 2024-03-28 23:35 UTC
Labels: type/bug, sig/execution, compatibility-mysql8

**Comment by pcqz** [comment] 2024-03-29 07:02
I have submitted a bug report to MySQL.
https://bugs.mysql.com/bug.php?id=114510
