### ISSUE TITLE
Incompatible variables of password validation in mysql.global_variables after upgrading to v6.5

### ISSUE THREAD

**Issue by pcqz** [pingcap/tidb#55838] opened 2024-09-04 03:44 UTC
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

1. deploy tidb cluster with v6.1
2. upgrade the cluster from v6.1 to v6.5
3. query related variables of password validation from mysql.global_variables

### 2. What did you expect to see? (Required)

The same variables with a new v6.5 cluster
```
mysql> select * from mysql.global_variables where variable_name like 'validate%';
+--------------------------------------+----------------+
| VARIABLE_NAME                        | VARIABLE_VALUE |
+--------------------------------------+----------------+
| validate_password.check_user_name    | ON             |
| validate_password.special_char_count | 1              |
| validate_password.length             | 8              |
| validate_password.number_count       | 1              |
| validate_password.mixed_case_count   | 1              |
| validate_password.policy             | MEDIUM         |
| validate_password.enable             | OFF            |
| validate_password.dictionary         |                |
+--------------------------------------+----------------+
8 rows in set (0.00 sec)
```

### 3. What did you see instead (Required)

```
mysql>  select * from mysql.global_variables where variable_name like 'validate%';
+--------------------------------------+----------------+
| VARIABLE_NAME                        | VARIABLE_VALUE |
+--------------------------------------+----------------+
| validate_password_check_user_name    | OFF            |
| validate_password_dictionary_file    |                |
| validate_password_special_char_count | 1              |
| validate_password_number_count       | 1              |
| validate_password_length             | 8              |
+--------------------------------------+----------------+
5 rows in set (0.00 sec)
```

### 4. What is your TiDB version? (Required)

v6.5.0

**Comment by YangKeao** [comment] 2024-09-12 06:39
It's introduced in https://github.com/pingcap/tidb/pull/38953. I think it's an expected change to improve the compatibility with MySQL (though it breaks the compatibility between multiple TiDB versions).

Maybe @CbcWestwolf can provide more background information?

**Comment by CbcWestwolf** [comment] 2024-09-12 09:42
The reason is that #38953 forgot to modify `mysql.global_variables` during upgrading like https://github.com/pingcap/tidb/blob/1dc045fa1a2780f51db8850e85af14262b9c2049/pkg/session/bootstrap.go#L2758

A workround is to manually execute `INSERT HIGH_PRIORITY IGNORE INTO mysql.global_variables VALUES (...)` and then trigger reloading global system variables by `set global xxx = yyy`.

I would fix this later.

**Comment by CbcWestwolf** [comment] 2024-11-25 05:11
I want to close this issue since it is not a bug. After upgrading, if we don't set the global variable, it will not show in `mysql.global_variables`. We can get it by `show variables like ...` or `select @@global.xxx`
```sql
TiDB root@127.0.0.1:test> select tidb_version();
+-----------------------------------------------------------+
| tidb_version()                                            |
+-----------------------------------------------------------+
| Release Version: v6.5.11-5-gae4703afc1                    |
| Edition: Community                                        |
| Git Commit Hash: ae4703afc12cd685c6e28792322dac80d64c3631 |
| Git Branch: release-6.5                                   |
| UTC Build Time: 2024-11-25 05:05:27                       |
| GoVersion: go1.20.14                                      |
| Race Enabled: false                                       |
| TiKV Min Version: 6.2.0-alpha                             |
| Check Table Before Drop: false                            |
| Store: unistore                                           |
+-----------------------------------------------------------+
1 row in set
Time: 0.008s
TiDB root@127.0.0.1:test> select * from mysql.global_variables where variable_name like 'validate%';
+--------------------------------------+----------------+
| VARIABLE_NAME                        | VARIABLE_VALUE |
+--------------------------------------+----------------+
| validate_password_number_count       | 1              |
| validate_password_dictionary_file    |                |
| validate_password_special_char_count | 1              |
| validate_password_length             | 8              |
| validate_password_check_user_name    | OFF            |
+--------------------------------------+----------------+
5 rows in set
Time: 0.007s
TiDB root@127.0.0.1:test> show variables like 'validate%';
+--------------------------------------+--------+
| Variable_name                        | Value  |
+--------------------------------------+--------+
| validate_password.check_user_name    | ON     |
| validate_password.dictionary         |        |
| validate_password.enable             | OFF    |
| validate_password.length             | 8      |
| validate_password.mixed_case_count   | 1      |
| validate_password.number_count       | 1      |
| validate_password.policy             | MEDIUM |
| validate_password.special_char_count | 1      |
+--------------------------------------+--------+
8 rows in set
Time: 0.003s
TiDB root@127.0.0.1:test> set global validate_password.length = 10;
Query OK, 0 rows affected
Time: 0.005s
TiDB root@127.0.0.1:test> show variables like 'validate%';
+--------------------------------------+--------+
| Variable_name                        | Value  |
+--------------------------------------+--------+
| validate_password.check_user_name    | ON     |
| validate_password.dictionary         |        |
| validate_password.enable             | OFF    |
| validate_password.length             | 10     |
| validate_password.mixed_case_count   | 1      |
| validate_password.number_count       | 1      |
| validate_password.policy             | MEDIUM |
| validate_password.special_char_count | 1      |
+--------------------------------------+--------+
8 rows in set
Time: 0.007s
TiDB root@127.0.0.1:test> select * from mysql.global_variables where variable_name like 'validate%';
+--------------------------------------+----------------+
| VARIABLE_NAME                        | VARIABLE_VALUE |
+--------------------------------------+----------------+
| validate_password_number_count       | 1              |
| validate_password_dictionary_file    |                |
| validate_password_special_char_count | 1              |
| validate_password_length             | 8              |
| validate_password_check_user_name    | OFF            |
| validate_password.length             | 10             |
+--------------------------------------+----------------+
6 rows in set
Time: 0.011s
```

**Closed by CbcWestwolf** 2024-11-25 05:11 UTC
Labels: type/bug, sig/sql-infra, severity/moderate, report/customer
