### ISSUE TITLE
alter table fails when changing float to decimal

### ISSUE THREAD

**Issue by kaeverens** [pingcap/tidb#11172] opened 2019-07-10 09:56 UTC
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

```
MySQL [user32]> create table decimal_test(
    -> total float
    -> );
Query OK, 0 rows affected (0.279 sec)

MySQL [user32]> alter table decimal_test change total total decimal(13,4);
```

2. What did you expect to see?

```
Query OK, 0 rows affected (0.279 sec)
```

3. What did you see instead?

```
ERROR 1105 (HY000): unsupported modify column type 246 not match origin 4
```

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

v3.0.0-rc.1-256-g1ddb31720

**Comment by winkyao** [comment] 2019-07-10 10:16
@kaeverens Thanks for your report. TiDB doesn't support change column type from float to decimal yet, get more details in the docs of the `modify column` (https://pingcap.com/docs/v3.0/reference/sql/statements/modify-column/).

We are considering to support changing the column type in the future.

**Comment by zimulala** [comment] 2020-07-02 08:00
Related to #18283

**Comment by nullnotnil** [comment] 2020-07-22 18:47
I am going to close this as a duplicate of https://github.com/pingcap/tidb/issues/18283

Please feel free to re-open if you have additional questions. Thanks!

**Closed by nullnotnil** 2020-07-22 18:47 UTC
Labels: component/DDL, type/duplicate, type/question
