### ISSUE TITLE
Support SAVEPOINT

### ISSUE THREAD

**Issue by breeswish** [pingcap/tidb#3663] opened 2017-07-07 12:09 UTC
https://dev.mysql.com/doc/refman/5.7/en/savepoint.html

**Comment by lotaku** [comment] 2017-09-08 09:27
any update?

**Comment by kocoten1992** [comment] 2017-11-25 20:00
can't write reusable module that interact with database without this feature, have to repeat my self every time

**Comment by morgo** [comment] 2018-11-25 12:53
I am going to close this issue as a duplicate of https://github.com/pingcap/tidb/issues/6840

Please feel free to re-open it if you have any questions.  Thank you!

**Closed by morgo** 2018-11-25 12:53 UTC
Labels: type/compatibility

**Comment by Allan-Nava** [comment] 2021-11-29 16:43
Any news?
