### ISSUE TITLE
column not substituted makes resolveIndices return error

### ISSUE THREAD

**Issue by xiongjiwei** [pingcap/tidb#28743] opened 2021-10-12 02:33 UTC
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```sql
 CREATE TABLE `t` (
  `a` char(1) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `b` char(1) COLLATE utf8mb4_general_ci DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

select t2.b from (select t.a as b from t union all select t.a as b from t) t2 where t2.b > 'a' collate utf8mb4_unicode_ci;
```

### 2. What did you expect to see? (Required)

`no error`

### 3. What did you see instead (Required)

`ERROR 1105 (HY000): Can't find column Column#7 in schema Column: [test.t.a] Unique key: []`

**Comment by yudongusa** [comment] 2021-12-14 01:25
@XuHuaiyu based on the offline discussion last week, should we label expression related issue with sig/execution?

**Comment by qw4990** [comment] 2021-12-22 11:10
This issue is fixed by some PR, and now the behavior is the same with MySQL that an invalid-char-set error is returned: 
```
mysql> select t2.b from (select t.a as b from t union all select t.a as b from t) t2 where t2.b > 'a' collate utf8mb4_unicode_ci;
ERROR 1253 (42000): COLLATION 'utf8mb4_unicode_ci' is not valid for CHARACTER SET 'utf8'
```

**Comment by xiongjiwei** [comment] 2021-12-22 11:28
> This issue is fixed by some PR, and now the behavior is the same with MySQL that an invalid-char-set error is returned:
> 
> ```
> mysql> select t2.b from (select t.a as b from t union all select t.a as b from t) t2 where t2.b > 'a' collate utf8mb4_unicode_ci;
> ERROR 1253 (42000): COLLATION 'utf8mb4_unicode_ci' is not valid for CHARACTER SET 'utf8'
> ```

run `set names utf8mb4` first

**Comment by qw4990** [comment] 2021-12-23 05:55
> ```sql
> ```sql
> select t2.b from (select t.a as b from t union all select t.a as b from t) t2 where t2.b > 'a' collate utf8mb4_unicode_ci;
> ```
> 
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
> ```

OK, I can reproduce it now.

**Comment by windtalker** [comment] 2022-05-21 12:30
Can not reproduce it in master, remove `affects-6.1` label

**Comment by qw4990** [comment] 2024-04-29 07:27
Can't reproduce it:
```
mysql> set names utf8mb4;
Query OK, 0 rows affected (0.00 sec)

mysql> select t2.b from (select t.a as b from t union all select t.a as b from t) t2 where t2.b > 'a' collate utf8mb4_unicode_ci;
Empty set (0.00 sec)

mysql> select t2.b from (select t.a as b from t union all select t.a as b from t) t2 where t2.b > 'a' collate utf8mb4_unicode_ci;
Empty set (0.00 sec)
```

**Closed by qw4990** 2024-04-29 07:27 UTC
Labels: type/bug, sig/planner, severity/major, affects-5.0, affects-5.1, affects-5.2, affects-5.3, affects-5.4, affects-6.0, affects-6.2, affects-6.3, affects-6.4, affects-6.5, affects-6.6, affects-7.0, affects-7.1, affects-7.5, affects-8.1
