### ISSUE TITLE
 Does TiDB automatically run any scheduled jobs that use DistSQL?

### ISSUE THREAD

**Issue by phamtai97** [pingcap/tidb#17470] opened 2020-05-28 04:30 UTC
Hi all.
I am currently using TiDB version 3.0.11. I deploy by model: 3 node TiDB on 3 servers, 5 node TiKV on 5 servers, and 5 node PD on the same server of TiKV. 

I monitor the metric of TiDB, TiKV and find the problems. In TiDB, I see metric of **DistSQL QPS** with the number of command **DAG** increase every about **10 minutes**. Then, I looked at the metrics **Total DAG Executors** of TiKV and saw that time it received many the **batch_index_scan**, **batch_table_scan** commands. 

![image](https://user-images.githubusercontent.com/38773351/83098401-b6e20c80-a0d4-11ea-94bc-ab38f0bad331.png)

And metric **Keys flow** of TiKV's RockDB has written and read commands is also increase. 

![image](https://user-images.githubusercontent.com/38773351/83098418-c95c4600-a0d4-11ea-8bb2-da5ba922029c.png)

Understandably, it will increase the number of lock errors in TiKV.

![image](https://user-images.githubusercontent.com/38773351/83098468-f90b4e00-a0d4-11ea-9ccd-10f1d3cd9215.png)

I also see the number of get and processed increased.

![image](https://user-images.githubusercontent.com/38773351/83098665-746cff80-a0d5-11ea-9b13-7f326823f18a.png)

I think that TiDB is running a schedule job in internally. I do not know what the root cause and deduce I'm still vague. **Does TiDB automatically run any scheduled jobs that use DistSQL?**.

**Comment by phamtai97** [comment] 2020-05-29 00:35
@tiancaiamao

**Comment by phamtai97** [comment] 2020-06-01 02:52
Can you help me? @tiancaiamao

**Comment by phamtai97** [comment] 2020-06-01 11:00
I check log of TiKV and see **many slow-query**:

```log
[2020/06/01 16:29:27.211 +07:00] [INFO] [tracker.rs:150] [slow-query] [internal_key_skipped_count=140913] [internal_delete_skipped_count=0] [block_cache_hit_count=16] [block_read_count=1544] [block_read_byte=18615003] [scan_first_range="Some(start: 7480000000000009D05F7280000000003FA808 end: 7480000000000009D05F72800000000043F4EC)"] [scan_ranges=1] [scan_iter_processed=140914] [scan_iter_ops=140916] [scan_is_desc=None] [tag=select] [table_id=2512] [txn_start_ts=18446744073709551615] [wait_time=1ms] [total_process_time=1.217s] [peer_id=ipv4:x.y.z:41181] [region_id=61023]
host = x.y.z source = /data/tidb/log/tikv.log
```
When I check table_id=2512 and it dose not exits in my database, but TiKV still scans it.

**Comment by phamtai97** [comment] 2020-06-02 07:08
Can you help me? @crazycs520

**Comment by tiancaiamao** [comment] 2020-06-03 07:50
TiDB run internal SQL, but it should not affect the daily usage.
From the metrics, we can see the background job runs periodically, I guess the workload is from outside, not the internal SQL.
It's better to check the slow_query log to verify that.

https://pingcap.com/docs/dev/identify-slow-queries/

**Comment by phamtai97** [comment] 2020-06-03 08:53
I check slow-query metric:

![image](https://user-images.githubusercontent.com/38773351/83616607-3fb7e700-a5b2-11ea-9b26-cb33e81f62fc.png)

It runs periodically, but it doesn't match the metric in my issues.

**Comment by VoxT** [comment] 2020-06-03 09:53
Hi @tiancaiamao 
I work with @phamtai97 
Here the slow log:
`# Time: 2020-06-01T00:30:49.037134172+07:00
# Txn_start_ts: 0
# Query_time: 11.284479731
# Parse_time: 0.000067558
# Compile_time: 0.000041354
# Is_internal: true
# Digest: ba04ada1bb2f38fbe2a83f3ef72ea4d470b48e73d19c9eb79e1e76e0f5bd12ed
# Num_cop_tasks: 0
# Prepared: false
# Has_more_results: false
# Succ: true
analyze table `bookkeeping`.`transLog` partition ``;
# Time: 2020-06-01T00:32:33.100537416+07:00
# Txn_start_ts: 0
# User: apistg@10.60.72.12
# Conn_ID: 1928008
# Query_time: 0.33686591
# Parse_time: 0.000195873
# Compile_time: 0.336493399
# DB: QUARTZ_SCHEMA_ZAS
# Is_internal: false
# Digest: cf66bd615927d5f3550c8f0b85bd80c26b5421f14b4198e2229e3fb7fccf0008
# Num_cop_tasks: 0
# Prepared: false
# Has_more_results: false
# Succ: true
# Plan: tidb_decode_plan('2AJMMAkzXzMJMAkxCSIxIiwgInV0ZjheCAAIbWI0ERsYbWI0X2JpbhEPKF9nZW5lcmFsX2NpARMBBBAyODgwMAEJQEFwYWNoZSBMaWNlbnNlIDIuBRYAMgEbGDY3MTA4ODYFVgA2BRcFBRgxMDQ4NTc2ASIIT0ZGBQfwT05MWV9GVUxMX0dST1VQX0JZLFNUUklDVF9UUkFOU19UQUJMRVMsTk9fWkVST19JTl9EQVRFLEVSUk9SX0ZPUl9ESVZJU0lPTl9CWV9aRVJPASuYRU5HSU5FX1NVQlNUSVRVVElPTiIsICJBc2lhL0hvX0NoaV9NaW5oARQUU1lTVEVNAQoQUkVQRUEFbxAtUkVBRAETUDAiCjEJMjZfNAkwCTEJcm93czoxCg==')
# Plan_digest: 85f24eb3da51e4d33e6021f984d2fa4f7548a5ee4e872bc3755a759a63436b63
/* mysql-connector-java-8.0.18 (Revision: fef2894d751d47223192b706977b4a5bc41e6be4) */SELECT  @@session.auto_increment_increment AS auto_increment_increment, @@character_set_client AS character_set_client, @@character_set_connection AS character_set_connection, @@character_set_results AS character_set_results, @@character_set_server AS character_set_server, @@collation_server AS collation_server, @@collation_connection AS collation_connection, @@init_connect AS init_connect, @@interactive_timeout AS interactive_timeout, @@license AS license, @@lower_case_table_names AS lower_case_table_names, @@max_allowed_packet AS max_allowed_packet, @@net_write_timeout AS net_write_timeout, @@performance_schema AS performance_schema, @@query_cache_size AS query_cache_size, @@query_cache_type AS query_cache_type, @@sql_mode AS sql_mode, @@system_time_zone AS system_time_zone, @@time_zone AS time_zone, @@transaction_isolation AS transaction_isolation, @@wait_timeout AS wait_timeout;
`

analyze table `zas_bookkeeping`.`transLog` partition ``; seem to be run periodically

**Comment by VoxT** [comment] 2020-06-03 09:56
> I check log of TiKV and see **many slow-query**:
> 
> ```
> [2020/06/01 16:29:27.211 +07:00] [INFO] [tracker.rs:150] [slow-query][internal_key_skipped_count=140913] [internal_delete_skipped_count=0] [block_cache_hit_count=16] [block_read_count=1544] [block_read_byte=18615003] [scan_first_range="Some(start: 7480000000000009D05F7280000000003FA808 end: 7480000000000009D05F72800000000043F4EC)"] [scan_ranges=1] [scan_iter_processed=140914] [scan_iter_ops=140916] [scan_is_desc=None] [tag=select] [table_id=2512] [txn_start_ts=18446744073709551615] [wait_time=1ms] [total_process_time=1.217s] [peer_id=ipv4:x.y.z:41181] [region_id=61023]
> host = x.y.z source = /data/tidb/log/tikv.log
> ```
> 
> When I check table_id=2512 and it dose not exits in my database, but TiKV still scans it.

I wonder why tidb keep scan a none existed table?

**Comment by tiancaiamao** [comment] 2020-06-09 07:36
> analyze table `zas_bookkeeping`.`transLog` partition ``; 

Does this SQL has the seem frequency as we have seen in the metrics?  @VoxT 

The root cause must be some SQL runs periodically, and it should be caught in caught by the tidb slow log.
https://pingcap.com/docs/dev/identify-slow-queries/

**Comment by tiancaiamao** [comment] 2020-06-09 07:37
Please keep an eye on it @zz-jason

**Comment by VoxT** [comment] 2020-06-09 11:26
> > analyze table `zas_bookkeeping`.`transLog` partition ``;
> 
> Does this SQL has the seem frequency as we have seen in the metrics? @VoxT
> 
> The root cause must be some SQL runs periodically, and it should be caught in caught by the tidb slow log.
> https://pingcap.com/docs/dev/identify-slow-queries/

I have check the slow log and the most of them is that auto analyze table.
I put those metics (tidb slowlog and tidb duration) together, you can see here:

<img width="1335" alt="Screen Shot 2020-06-09 at 18 08 56" src="https://user-images.githubusercontent.com/13825568/84140964-9aeb4d00-aa7c-11ea-9ba8-10524397eca2.png">

Can you explain those two things first:
-  Why TiDB keep scan a none existed table as I comment here: https://github.com/pingcap/tidb/issues/17470#issuecomment-638092565, it's still running now?

I grep this scan tableid=2512 in just one hour and look frequently:
<img width="1418" alt="Screen Shot 2020-06-09 at 18 20 01" src="https://user-images.githubusercontent.com/13825568/84141809-f2d68380-aa7d-11ea-8143-29a0956abcfa.png">


- Why this auto analyze table:
```
analyze table `zas_bookkeeping`.`transLog` partition ``;
```
 keep running frequently, this table only insert about 5 trans/sec?

**Comment by tiancaiamao** [comment] 2020-06-09 12:19
1. Why TiDB keep scan a none existed table

I do not know, and I need more details to verify it.

Is `zas_bookkeeping` a partitioned table? 
What's it definition?
Do you create/drop partition periodically?

If you want to see the table name of 2512, you can try this:

```
mysql> select table_name from tables where tidb_table_id = 2512;
```

Or maybe it is a partition. Check the INFORMATION_SCHEMA.PARTITIONS to find more information.



2. Why this auto analyze table keep running frequently

Would you please grep the tidb log like this, what's the result and how frequent are them?

```
[stats] auto analyze triggered
```

Auto analyze is triggered here https://github.com/pingcap/tidb/blob/master/domain/domain.go#L1141

`NeedAnalyzeTable` should not be true everytime.
And it should be run in a low frequency.
https://github.com/pingcap/tidb/blob/master/statistics/handle/update.go#L721

Could provide the tidb config file, I need to cheek the `performance/stats-lease` 
https://github.com/pingcap/tidb/blob/master/config/config.toml.example#L213 to see how frequent it runs.

**Comment by VoxT** [comment] 2020-06-10 07:58
> Is `zas_bookkeeping` a partitioned table?
> What's it definition?

Yes, it has 3 tables that hash partition (4 partitions) by field id auto-generate.

> Do you create/drop partition periodically?

No.

> If you want to see the table name of 2512, you can try this:
> 
> ```
> mysql> select table_name from tables where tidb_table_id = 2512;
> ```

I have run that query above and this query too, but all return empty.
`curl http://{TiDBIP}:10080/schema?table_id=2512`

> 
> Or maybe it is a partition. Check the INFORMATION_SCHEMA.PARTITIONS to find more information.
> 

It looks like a mess in there, includes tables that do not partition. Which info should I check?

> 
> Would you please grep the tidb log like this, what's the result and how frequent are them?
> 
> ```
> [stats] auto analyze triggered
> ```

This is how frequently it is, about 53 events an hour:
<img width="1428" alt="Screen Shot 2020-06-10 at 14 53 21" src="https://user-images.githubusercontent.com/13825568/84241812-34246d00-ab2a-11ea-9141-5cf2714bfdf0.png">

Anh this is the result within a day:
```
[2020/06/10 14:14:34.491 +07:00] [INFO] [update.go:739] ["[stats] auto analyze triggered"] [sql="analyze table `zas_bookkeeping`.`transLog` partition ``"] [reason="table unanalyzed, time since last updated 2m41.61795731ss"]
[2020/06/10 12:02:57.236 +07:00] [INFO] [update.go:739] ["[stats] auto analyze triggered"] [sql="analyze table `zas_bookkeeping`.`refundTransLog` partition ``"] [reason="too many modifications(273816/273816>0.5)"]
[2020/06/10 12:03:07.963 +07:00] [INFO] [update.go:739] ["[stats] auto analyze triggered"] [sql="analyze table `zas_bookkeeping`.`refundTransLog` partition ``"] [reason="too many modifications(273816/273816>0.5)"]
```
- transLog just run with one reason="table unanalyzed"
- refundTransLog reason="too many modifications" (note that we just insert to this table)

> Could provide the tidb config file, I need to cheek the `performance/stats-lease`

This is all config in config file:
```
port=4000
store="tikv"
path="x.y.z.2:2379,x.y.z.3:2379,x.y.z.4:2379,x.y.z.5:2379,x.y.z.6:2379"
status-port=10080

#track the memory quota of a single SQL query, if exceeds TiDB prints an entry of log or cancel query if set oom-action="cancel"
mem-quota-query = 34359738368
oom-action="log"

[binlog]
enable=true

[log.file]
filename="log/tidb.log"
```

**Comment by tiancaiamao** [comment] 2020-06-11 11:04
> This is how frequently it is, about 53 events an hour

It does not happen every 10min, so there is no clue `analyze table` leads to the DistSQL latency.

Now we have the following directions to further investigate the problem:

1. If tikv metrics shows query on id=2512 is the root cause(the every 10min peak wave pattern), we need to find out the table of 2512.
Try to fetch `http://127.0.0.1:10080/schema/${tablename}` and grep 2512 from the output.
For example, if `zas_bookkeeping` is highly suspicious, then try `curl http://127.0.0.1:10080/schema/zas_bookkeeping` and find the partition ID of this table.

After obtain the table name, search slow query log to see what's the operation on the table and match the periodical pattern.

2. Directly search the slow log to find more suspicious SQLs that match the periodical pattern, and then verify them.

@VoxT

**Comment by VoxT** [comment] 2020-06-22 03:36
Hi @tiancaiamao,
Sorry for my late response.

I have found the table name of  id=2512, it's a partition of zas_bookkeeping table.
But when I grep the slow log by that table name and no log found. I do grep 2512 and other partition of zas_bookkeeping table again and it seems to be normal with tikv [slow-query].
<img width="1423" alt="Screen Shot 2020-06-22 at 10 17 18" src="https://user-images.githubusercontent.com/13825568/85245404-a4f44f00-b471-11ea-9133-446a70c9e7f2.png">

So I came back to inspect the slow log and found a periodical pattern that matches TiDB duration peak:
- TiDB slowlog for analyze table, all of them are the table of zas_bookkeeping. It seems matches to TiDB duration peak pattern a little bit.
```
# Time: 2020-06-22T10:13:57.515077045+07:00
# Txn_start_ts: 0
# Query_time: 683.738028457
# Parse_time: 0.000065088
# Compile_time: 0.000049462
# Is_internal: true
# Digest: bf9872dd43a6ef58ba24e84578596630f56d86142d3c282e001d3ab0720624c5
# Num_cop_tasks: 0
# Prepared: false
# Has_more_results: false
# Succ: true
analyze table `zas_bookkeeping`.`transLog` partition ``;
```
Slow log (one hour per column)
<img width="1437" alt="Screen Shot 2020-06-22 at 10 22 02" src="https://user-images.githubusercontent.com/13825568/85245586-4085bf80-b472-11ea-8307-940239da8d0b.png">
TiDB duration peak (rate 1h)
<img width="1111" alt="Screen Shot 2020-06-22 at 10 28 19" src="https://user-images.githubusercontent.com/13825568/85245909-429c4e00-b473-11ea-893c-dabff45a6504.png">


- And the most matches to TiDB duration peak pattern is this slowlog:
```
# Time: 2020-06-22T09:26:51.578095301+07:00
# Txn_start_ts: 0
# User: zasbookkeeping@10.x.y.z
# Conn_ID: 3644448
# Query_time: 0.334227147
# Parse_time: 0.000197186
# Compile_time: 0.333802774
# DB: zas_bookkeeping_stg
# Is_internal: false
# Digest: 65b64d3d1edef8adcd931cbcf77a818797bb85eb36604f5d23ccc92f41b79196
# Num_cop_tasks: 0
# Prepared: false
# Has_more_results: false
# Succ: true
# Plan: tidb_decode_plan('3AJMMAkzXzMJMAkxCSIxIiwgInV0ZjheCAAIbWI0ERsYbWI0X2JpbhEPKF9nZW5lcmFsX2NpARMBBBAyODgwMAEJQEFwYWNoZSBMaWNlbnNlIDIuBRYAMgEbGDY3MTA4ODYFVgwxNjM4BQkANgUgGDEwNDg1NzYBJghPRkYFB/BPTkxZX0ZVTExfR1JPVVBfQlksU1RSSUNUX1RSQU5TX1RBQkxFUyxOT19aRVJPX0lOX0RBVEUsRVJST1JfRk9SX0RJVklTSU9OX0JZX1pFUk8BK5hFTkdJTkVfU1VCU1RJVFVUSU9OIiwgIkFzaWEvSG9fQ2hpX01pbmgBFBRTWVNURU0BChBSRVBFQQVvEC1SRUFEARNQMCIKMQkyNl80CTAJMQlyb3dzOjEK')
# Plan_digest: 85f24eb3da51e4d33e6021f984d2fa4f7548a5ee4e872bc3755a759a63436b63
/* mysql-connector-java-5.1.47 ( Revision: fe1903b1ecb4a96a917f7ed3190d80c049b1de29 ) */SELECT  @@session.auto_increment_increment AS auto_increment_increment, @@character_set_client AS character_set_client, @@character_set_connection AS character_set_connection, @@character_set_results AS character_set_results, @@character_set_server AS character_set_server, @@collation_server AS collation_server, @@collation_connection AS collation_connection, @@init_connect AS init_connect, @@interactive_timeout AS interactive_timeout, @@license AS license, @@lower_case_table_names AS lower_case_table_names, @@max_allowed_packet AS max_allowed_packet, @@net_buffer_length AS net_buffer_length, @@net_write_timeout AS net_write_timeout, @@query_cache_size AS query_cache_size, @@query_cache_type AS query_cache_type, @@sql_mode AS sql_mode, @@system_time_zone AS system_time_zone, @@time_zone AS time_zone, @@transaction_isolation AS transaction_isolation, @@wait_timeout AS wait_timeout;
```
Slow log (one hour per column)
<img width="1435" alt="Screen Shot 2020-06-22 at 10 24 59" src="https://user-images.githubusercontent.com/13825568/85245706-a4a88380-b472-11ea-9a6f-95d20dc585a8.png">

TiDB duration peak (rate 1h)
<img width="1111" alt="Screen Shot 2020-06-22 at 10 28 19" src="https://user-images.githubusercontent.com/13825568/85245909-429c4e00-b473-11ea-893c-dabff45a6504.png">

=== 

For an experiment, I will limit the auto analyze table trigger by set startTime and endTime to see any difference here. (https://pingcap.com/docs/dev/tidb-specific-system-variables/#tidb_auto_analyze_ratio)

**Comment by tiancaiamao** [comment] 2020-07-07 02:14
> And the most matches to TiDB duration peak pattern is this slowlog:


> /* mysql-connector-java-5.1.47 ( Revision: fe1903b1ecb4a96a917f7ed3190d80c049b1de29 ) */SELECT  @@session.auto_increment_increment AS auto_increment_increment, @@character_set_client AS character_set_client, @@character_set_connection AS character_set_connection, @@character_set_results AS character_set_results, @@character_set_server AS character_set_server, @@collation_server AS collation_server, @@collation_connection AS collation_connection, @@init_connect AS init_connect, @@interactive_timeout AS interactive_timeout, @@license AS license, @@lower_case_table_names AS lower_case_table_names, @@max_allowed_packet AS max_allowed_packet, @@net_buffer_length AS net_buffer_length, @@net_write_timeout AS net_write_timeout, @@query_cache_size AS query_cache_size, @@query_cache_type AS query_cache_type, @@sql_mode AS sql_mode, @@system_time_zone AS system_time_zone, @@time_zone AS time_zone, @@transaction_isolation AS transaction_isolation, @@wait_timeout AS wait_timeout;

It seems to be a new connection, and the operations follows on by this connection may be the cause. You can try to find out which service signal those queries.

**Comment by jebter** [comment] 2024-06-05 08:58
The issue has not been updated for too long, so I will close it. If there are any updates you can reopen it.

**Closed by jebter** 2024-06-05 08:58 UTC
Labels: type/question
