### ISSUE TITLE
trailing spaces handle Inconsistent when set new_collations_enabled_on_first_bootstrap 1 and 0 

### ISSUE THREAD

**Issue by vivid392845427** [pingcap/tidb#24626] opened 2021-05-13 08:56 UTC
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

create table t1(a varchar(40));
insert into t1 values('aaaaa');
insert into t1 values('aaaaa ');
select * from t1 where a = 'aaaaa';
select * from t1 where a = 'aaaaa ';

### 2. What did you expect to see? (Required)

ignore trailing spaces

mysql> select * from t1 where a ='aaaaa';
+--------+
| a      |
+--------+
| aaaaa  |
| aaaaa  |
+--------+
2 rows in set (0.01 sec)

mysql> select * from t1 where a ='aaaaa ';
+--------+
| a      |
+--------+
| aaaaa  |
| aaaaa  |
+--------+
2 rows in set (0.00 sec)

### 3. What did you see instead (Required)

match trailing spaces strictly 
```sql
mysql> select * from t1 where a = 'aaaaa';
+-------+
| a     |
+-------+
| aaaaa |
+-------+
1 row in set (0.01 sec)

mysql> select * from t1 where a = 'aaaaa ';
+--------+
| a      |
+--------+
| aaaaa  |
+--------+
1 row in set (0.00 sec)
```
### 4. What is your TiDB version? (Required)

Release Version: v5.0.1
Edition: Community
Git Commit Hash: 1145e347d3469d8e89f88dce86f6926ca44b3cd8
Git Branch: heads/refs/tags/v5.0.1
UTC Build Time: 2021-04-23 07:32:04
GoVersion: go1.13
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false

**Comment by aytrack** [comment] 2021-05-13 10:29
This may be not a bug, old collation has a different behavior from  new collation frameworks, as described in the [documentation](https://docs.pingcap.com/tidb/stable/character-set-and-collation#character-set-and-collation)

**Comment by bb7133** [comment] 2021-05-14 14:46
Exactly, I'm closing this issue @vivid392845427 @aytrack

**Closed by bb7133** 2021-05-14 14:46 UTC
Labels: sig/sql-infra, type/question
