### ISSUE TITLE
Incorrect Results by `REGEXP`

### ISSUE THREAD

**Issue by bajinsheng** [pingcap/tidb#38303] opened 2022-10-06 01:29 UTC
## Bug Report

Inconsistent results by `REGEXP`.

### 1. Minimal reproduce step (Required)

```sql
CREATE TABLE t0(c0 INT);
INSERT INTO t0(c0) VALUES (0.01);
CREATE VIEW v0(c0) AS SELECT t0.c0 FROM t0;

SELECT * FROM t0 RIGHT JOIN v0 ON DEFAULT(t0.c0); -- (NULL|0}
SELECT (v0.c0)REGEXP(v0.c0 AND t0.c0) FROM t0 RIGHT JOIN v0 ON DEFAULT(t0.c0); -- {1}
SELECT * FROM t0 RIGHT JOIN v0 ON DEFAULT(t0.c0) WHERE (v0.c0)REGEXP(v0.c0 AND t0.c0); -- Empty set
```

### 2. What did you expect to see? (Required)
The first `SELECT` returns non-empty results and the predicate `(v0.c0)REGEXP(v0.c0 AND t0.c0)` is evaluated `TRUE` in the second `SELECT`, but the third `SELECT` returns nothing. 

### 4. What is your TiDB version? (Required)

```
| Release Version: v6.4.0-alpha-12-g51a6684fb
Edition: Community
Git Commit Hash: 51a6684fb767cfd86a8312e0e6447963b927c791
Git Branch: master
UTC Build Time: 2022-10-05 12:40:23
GoVersion: go1.19.1
Race Enabled: false
TiKV Min Version: 6.2.0-alpha
Check Table Before Drop: false
Store: unistore |
```

**Comment by Yisaer** [comment] 2022-10-19 00:24
The issue has the same root cause as #38304 and fixed by https://github.com/pingcap/tidb/pull/38430

Now this is fixed in master: 

```sql
mysql> CREATE TABLE t0(c0 INT);
Query OK, 0 rows affected (0.03 sec)

mysql> INSERT INTO t0(c0) VALUES (0.01);
Query OK, 1 row affected (0.00 sec)

mysql> CREATE VIEW v0(c0) AS SELECT t0.c0 FROM t0;
Query OK, 0 rows affected (0.01 sec)

mysql> SELECT * FROM t0 RIGHT JOIN v0 ON DEFAULT(t0.c0);
+------+------+
| c0   | c0   |
+------+------+
| NULL |    0 |
+------+------+
1 row in set (0.01 sec)

mysql> SELECT (v0.c0)REGEXP(v0.c0 AND t0.c0) FROM t0 RIGHT JOIN v0 ON DEFAULT(t0.c0); 
+--------------------------------+
| (v0.c0)REGEXP(v0.c0 AND t0.c0) |
+--------------------------------+
|                              1 |
+--------------------------------+
1 row in set (0.01 sec)

mysql> SELECT * FROM t0 RIGHT JOIN v0 ON DEFAULT(t0.c0) WHERE (v0.c0)REGEXP(v0.c0 AND t0.c0);
+------+------+
| c0   | c0   |
+------+------+
| NULL |    0 |
+------+------+
1 row in set (0.00 sec)

```

**Closed by Yisaer** 2022-10-19 00:24 UTC
Labels: type/bug, sig/planner, severity/major, affects-5.0, affects-5.1, affects-5.2, affects-5.3, affects-5.4, may-affects-4.0, affects-6.0, affects-6.1, affects-6.2, affects-6.3
