### ISSUE TITLE
fatal error: sync: unlock of unlocked mutex

### ISSUE THREAD

**Issue by ChenPeng2013** [pingcap/tidb#27725] opened 2021-09-01 08:16 UTC
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
fatal error: sync: unlock of unlocked mutex

goroutine 998 [running]:
runtime.throw(0x3b9f84a, 0x1e)
	/usr/local/go/src/runtime/panic.go:1117 +0x72 fp=0xc00dd31378 sp=0xc00dd31348 pc=0x1224532
sync.throw(0x3b9f84a, 0x1e)
	/usr/local/go/src/runtime/panic.go:1103 +0x35 fp=0xc00dd31398 sp=0xc00dd31378 pc=0x1259535
sync.(*Mutex).unlockSlow(0xc0052f3be8, 0xc0ffffffff)
	/usr/local/go/src/sync/mutex.go:196 +0xd8 fp=0xc00dd313c0 sp=0xc00dd31398 pc=0x126ab38
sync.(*Mutex).Unlock(0xc0052f3be8)
	/usr/local/go/src/sync/mutex.go:190 +0x48 fp=0xc00dd313e0 sp=0xc00dd313c0 pc=0x126aa48
github.com/pingcap/tidb/sessionctx/stmtctx.(*StatementContext).CopTasksDetails(0xc0052f3b98, 0xc0088fe120)
	/home/jenkins/agent/workspace/build_tidb_multi_branch_master/go/src/github.com/pingcap/tidb/sessionctx/stmtctx/stmtctx.go:711 +0xbd6 fp=0xc00dd31778 sp=0xc00dd313e0 pc=0x1f1c0f6
github.com/pingcap/tidb/util/expensivequery.genLogFields(0xeae4e, 0xc000a767e0, 0x5df6e80, 0xc043ea79bb27c55a, 0x3960ccef0404)
	/home/jenkins/agent/workspace/build_tidb_multi_branch_master/go/src/github.com/pingcap/tidb/util/expensivequery/expensivequery.go:117 +0x308 fp=0xc00dd31ff8 sp=0xc00dd31778 pc=0x26ef2
48
github.com/pingcap/tidb/util/expensivequery.(*memoryUsageAlarm).recordSQL.func2(0xc00dd322a0)
	/home/jenkins/agent/workspace/build_tidb_multi_branch_master/go/src/github.com/pingcap/tidb/util/expensivequery/memory_usage_alarm.go:195 +0x385 fp=0xc00dd32170 sp=0xc00dd31ff8 pc=0x2
6f48e5
github.com/pingcap/tidb/util/expensivequery.(*memoryUsageAlarm).recordSQL(0xc00dd33f38, 0x40a1688, 0xc0014d95f0)
	/home/jenkins/agent/workspace/build_tidb_multi_branch_master/go/src/github.com/pingcap/tidb/util/expensivequery/memory_usage_alarm.go:213 +0x7cb fp=0xc00dd32498 sp=0xc00dd32170 pc=0x2
6f330b
github.com/pingcap/tidb/util/expensivequery.(*memoryUsageAlarm).doRecord(0xc00dd33f38, 0x31e5b7000, 0x13221298, 0x40a1688, 0xc0014d95f0)
	/home/jenkins/agent/workspace/build_tidb_multi_branch_master/go/src/github.com/pingcap/tidb/util/expensivequery/memory_usage_alarm.go:145 +0x5b8 fp=0xc00dd32608 sp=0xc00dd32498 pc=0x2
6f24f8
github.com/pingcap/tidb/util/expensivequery.(*memoryUsageAlarm).alarm4ExcessiveMemUsage(0xc00dd33f38, 0x40a1688, 0xc0014d95f0)
	/home/jenkins/agent/workspace/build_tidb_multi_branch_master/go/src/github.com/pingcap/tidb/util/expensivequery/memory_usage_alarm.go:121 +0x1c5 fp=0xc00dd33e08 sp=0xc00dd32608 pc=0x2
6f1b65
github.com/pingcap/tidb/util/expensivequery.(*Handle).Run(0xc0014880c0)
	/home/jenkins/agent/workspace/build_tidb_multi_branch_master/go/src/github.com/pingcap/tidb/util/expensivequery/expensivequery.go:82 +0x3e7 fp=0xc00dd33fd8 sp=0xc00dd33e08 pc=0x26eeb4
7
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1371 +0x1 fp=0xc00dd33fe0 sp=0xc00dd33fd8 pc=0x125f7e1
created by main.createServer
	/home/jenkins/agent/workspace/build_tidb_multi_branch_master/go/src/github.com/pingcap/tidb/tidb-server/main.go:632 +0x1c7
```
[tidb_stderr.log](https://github.com/pingcap/tidb/files/7089416/tidb_stderr.log)

### 4. What is your TiDB version? (Required)

```
Release Version: v5.2.0-alpha-790-gd58d39e94
Edition: Community
Git Commit Hash: d58d39e9476f2503a1e8790f78a0d25272d0aabe
Git Branch: master
UTC Build Time: 2021-08-31 09:53:04
GoVersion: go1.16.4
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
```

**Comment by XuHuaiyu** [comment] 2021-11-03 02:13
This may be fixed by https://github.com/pingcap/tidb/pull/29194.

**Comment by ChenPeng2013** [comment] 2022-01-04 03:16
this error happened again in release-5.4 
```
fatal error: sync: unlock of unlocked mutex

goroutine 709 [running]:
runtime.throw(0x3fccc10, 0x1e)
	/usr/local/go/src/runtime/panic.go:1117 +0x72 fp=0xc059085038 sp=0xc059085008 pc=0x1326372
sync.throw(0x3fccc10, 0x1e)
	/usr/local/go/src/runtime/panic.go:1103 +0x35 fp=0xc059085058 sp=0xc059085038 pc=0x135b375
sync.(*Mutex).unlockSlow(0xc0bdd16cb8, 0xc3ffffffff)
	/usr/local/go/src/sync/mutex.go:196 +0xd8 fp=0xc059085080 sp=0xc059085058 pc=0x136c998
sync.(*Mutex).Unlock(0xc0bdd16cb8)
	/usr/local/go/src/sync/mutex.go:190 +0x48 fp=0xc0590850a0 sp=0xc059085080 pc=0x136c8a8
runtime.call16(0x0, 0x40a7728, 0xc34b7e5268, 0x800000008)
	/usr/local/go/src/runtime/asm_amd64.s:550 +0x3e fp=0xc0590850c0 sp=0xc0590850a0 pc=0x135fbbe
runtime.reflectcallSave(0xc0590851f8, 0x40a7728, 0xc34b7e5268, 0x8)
	/usr/local/go/src/runtime/panic.go:877 +0x58 fp=0xc0590850f0 sp=0xc0590850c0 pc=0x1325938
runtime.runOpenDeferFrame(0xc001155080, 0xc34b7e5220, 0xc059085240)
	/usr/local/go/src/runtime/panic.go:851 +0x62d fp=0xc059085178 sp=0xc0590850f0 pc=0x132560d
panic(0x3d44060, 0xc34beba8e8)
	/usr/local/go/src/runtime/panic.go:965 +0x1b9 fp=0xc059085240 sp=0xc059085178 pc=0x1325bb9
runtime.goPanicIndex(0x0, 0x0)
	/usr/local/go/src/runtime/panic.go:88 +0xa5 fp=0xc059085288 sp=0xc059085240 pc=0x1323105
github.com/pingcap/tidb/sessionctx/stmtctx.(*StatementContext).CopTasksDetails.func1(0x0, 0x9, 0x0)
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/sessionctx/stmtctx/stmtctx.go:756 +0x5d fp=0xc0590852a8 sp=0xc059085288 pc=0x207935d
sort.doPivot_func(0xc0590854f0, 0xc375129400, 0x0, 0x14, 0x7f198b5573c8, 0x7f19226e0728)
	/usr/local/go/src/sort/zfuncversion.go:87 +0x462 fp=0xc059085330 sp=0xc0590852a8 pc=0x13caba2
sort.quickSort_func(0xc0590854f0, 0xc375129400, 0x0, 0x14, 0xa)
	/usr/local/go/src/sort/zfuncversion.go:143 +0x97 fp=0xc059085388 sp=0xc059085330 pc=0x13cad97
sort.Slice(0x39a1180, 0xc2644e6ee8, 0xc0590854f0)
	/usr/local/go/src/sort/slice.go:20 +0xe8 fp=0xc0590853e0 sp=0xc059085388 pc=0x13c8568
github.com/pingcap/tidb/sessionctx/stmtctx.(*StatementContext).CopTasksDetails(0xc0bdd16c60, 0x0)
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/sessionctx/stmtctx/stmtctx.go:755 +0x23b fp=0xc059085778 sp=0xc0590853e0 pc=0x207729b
github.com/pingcap/tidb/util/expensivequery.genLogFields(0x8f4469d, 0xc573768620, 0x6442b80, 0xc06c8f87d6d4625c, 0x40001a281ca3)
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/util/expensivequery/expensivequery.go:117 +0x308 fp=0xc059085ff8 sp=0xc059085778 pc=0x28dfde8
github.com/pingcap/tidb/util/expensivequery.(*memoryUsageAlarm).recordSQL.func2(0xc0590862a0)
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/util/expensivequery/memory_usage_alarm.go:195 +0x385 fp=0xc059086170 sp=0xc059085ff8 pc=0x28e5485
github.com/pingcap/tidb/util/expensivequery.(*memoryUsageAlarm).recordSQL(0xc059087f38, 0x4528d58, 0xc00a4529c0)
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/util/expensivequery/memory_usage_alarm.go:213 +0x7cb fp=0xc059086498 sp=0xc059086170 pc=0x28e3eab
github.com/pingcap/tidb/util/expensivequery.(*memoryUsageAlarm).doRecord(0xc059087f38, 0x1ce3dff000, 0x5759c2938, 0x4528d58, 0xc00a4529c0)
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/util/expensivequery/memory_usage_alarm.go:145 +0x5b8 fp=0xc059086608 sp=0xc059086498 pc=0x28e3098
github.com/pingcap/tidb/util/expensivequery.(*memoryUsageAlarm).alarm4ExcessiveMemUsage(0xc059087f38, 0x4528d58, 0xc00a4529c0)
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/util/expensivequery/memory_usage_alarm.go:121 +0x1c5 fp=0xc059087e08 sp=0xc059086608 pc=0x28e2705
github.com/pingcap/tidb/util/expensivequery.(*Handle).Run(0xc0011221f8)
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/util/expensivequery/expensivequery.go:82 +0x3e7 fp=0xc059087fd8 sp=0xc059087e08 pc=0x28df6e7
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1371 +0x1 fp=0xc059087fe0 sp=0xc059087fd8 pc=0x1361621
created by main.createServer
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/tidb-server/main.go:669 +0x1c7
```
[tidb_stderr.log](https://github.com/pingcap/tidb/files/7805166/tidb_stderr.log)

**Comment by wshwsh12** [comment] 2022-01-24 03:08
One possible reason: the function maybe reset stmtctx.StatementContext{} directly, so the lock will be reset..
https://github.com/pingcap/tidb/blob/afa1335f21895db2f5c28f53a00113b1e5f3baa2/sessionctx/variable/session.go#L1007-L1011

**Comment by LittleFall** [comment] 2022-03-18 08:00
maybe we can change the StatementContext.mu to a pointer type.

**Comment by wshwsh12** [comment] 2022-03-20 07:35
We can add some sleep in the code and reproduce the issue.
Apply the patch https://github.com/wshwsh12/tidb/commit/6b56d40ac3908b3e4688d2a1db93221c31092dcb, and run the following sqls:
```
select sleep(11);
select 1;
select 1;
```

TiDB will crash and get the stack following:
```
fatal error: sync: unlock of unlocked mutex

goroutine 380 [running]:
runtime.throw({0x1040b5b6c?, 0x14010626990?})
        /Users/shenghuiwu/go/go1.18/src/runtime/panic.go:992 +0x50 fp=0x1400f90f2b0 sp=0x1400f90f280 pc=0x10244f470
sync.throw({0x1040b5b6c?, 0x90?})
        /Users/shenghuiwu/go/go1.18/src/runtime/panic.go:978 +0x24 fp=0x1400f90f2d0 sp=0x1400f90f2b0 pc=0x10247d3e4
sync.(*Mutex).unlockSlow(0x1400fa6b3d0, 0xffffffff)
        /Users/shenghuiwu/go/go1.18/src/sync/mutex.go:220 +0x3c fp=0x1400f90f300 sp=0x1400f90f2d0 pc=0x10248cbec
sync.(*Mutex).Unlock(0x140101e0601?)
        /Users/shenghuiwu/go/go1.18/src/sync/mutex.go:214 +0x64 fp=0x1400f90f320 sp=0x1400f90f300 pc=0x10248cb84
github.com/pingcap/tidb/sessionctx/stmtctx.(*StatementContext).CopTasksDetails.func4()
        /Users/shenghuiwu/project/tidb/sessionctx/stmtctx/stmtctx.go:768 +0x2c fp=0x1400f90f340 sp=0x1400f90f320 pc=0x102f2a74c
github.com/pingcap/tidb/sessionctx/stmtctx.(*StatementContext).CopTasksDetails(0x1400fa6b360)
        /Users/shenghuiwu/project/tidb/sessionctx/stmtctx/stmtctx.go:782 +0x490 fp=0x1400f90f720 sp=0x1400f90f340 pc=0x102f2a090
github.com/pingcap/tidb/util/expensivequery.genLogFields(0x255bf58ba, 0x1400fa155e0)
        /Users/shenghuiwu/project/tidb/util/expensivequery/expensivequery.go:117 +0x278 fp=0x1400f90fd90 sp=0x1400f90f720 pc=0x1035b19c8
github.com/pingcap/tidb/util/expensivequery.logExpensiveQuery(0x14000a4f860?, 0x1400f90fe48?)
        /Users/shenghuiwu/project/tidb/util/expensivequery/expensivequery.go:179 +0x80 fp=0x1400f90fdf0 sp=0x1400f90fd90 pc=0x1035b29d0
github.com/pingcap/tidb/util/expensivequery.(*Handle).Run(0x14000ba82a0)
        /Users/shenghuiwu/project/tidb/util/expensivequery/expensivequery.go:70 +0x2dc fp=0x1400f90ffb0 sp=0x1400f90fdf0 pc=0x1035b135c
main.createServer.func1()
        /Users/shenghuiwu/project/tidb/tidb-server/main.go:694 +0x2c fp=0x1400f90ffd0 sp=0x1400f90ffb0 pc=0x10406023c
runtime.goexit()
        /Users/shenghuiwu/go/go1.18/src/runtime/asm_arm64.s:1259 +0x4 fp=0x1400f90ffd0 sp=0x1400f90ffd0 pc=0x102483274
created by main.createServer
        /Users/shenghuiwu/project/tidb/tidb-server/main.go:694 +0x3a8
```

**Comment by wshwsh12** [comment] 2022-03-21 08:18
In normal case, when the memory usage exceeds 80% and the pressure is particularly high, there is a small probability of appearing. Alternatively, you can workaround by setting memory-usage-alarm-ratio to false

**Comment by tiancaiamao** [comment] 2022-04-22 09:35
Is it caused by a data race? @wshwsh12 
Expensive query handler handling the other session's statement context... without lock protect

**Comment by XuHuaiyu** [comment] 2022-11-16 07:19
Maybe we can add an attribute like `accessByOtherSess atomic.Int` in `StatementContext`. When a session tries to access another session's StatementContext, `accessByOtherSess + 1` first.
In `InitStatementContext`, resetting `StatementContext` only when `accessByOtherSess == 0`. Otherwise, initialize a new pointer for `sc` instead of resetting the old one.

**Comment by zanmato1984** [comment] 2022-11-18 06:42
Encountered several times recently. Elevating to major.

**Closed** 2022-11-28 09:02 UTC
Labels: type/bug, sig/sql-infra, severity/major, affects-5.0, affects-5.1, affects-5.2, affects-5.3, affects-5.4, affects-6.0, affects-6.1, affects-6.2, affects-6.3, affects-6.4
