### ISSUE TITLE
Support alter table modify column type from date to datetime.

### ISSUE THREAD

**Issue by winkyao** [pingcap/tidb#4586] opened 2017-09-20 07:52 UTC
MySQL:

```
mysql> CREATE TABLE t1(a date);
Query OK, 0 rows affected (0.01 sec)

mysql> ALTER TABLE t1 MODIFY COLUMN a datetime;
Query OK, 0 rows affected (0.03 sec)
Records: 0  Duplicates: 0  Warnings: 0
```

TiDB:

```
mysql> CREATE TABLE t1(a date);
Query OK, 0 rows affected (0.08 sec)

mysql> ALTER TABLE t1 MODIFY COLUMN a datetime;
ERROR 1105 (HY000): unsupported modify column type 12 not match origin 10
```

**Comment by morgo** [comment] 2018-11-24 21:01
It might be worth suggesting tooling for DDL which is not supported in TiDB.  Maybe we can integrate the TiDB Binlog with Gh-ost?

@GregoryIan what do you think?

**Comment by nullnotnil** [comment] 2020-07-30 19:15
Confirming that the issue is still present in master:
```sql

mysql> ALTER TABLE t1 MODIFY COLUMN a datetime;
ERROR 8200 (HY000): Unsupported modify column: type datetime not match origin date
mysql> SELECT tidb_version()\G
*************************** 1. row ***************************
tidb_version(): Release Version: v4.0.0-beta.2-859-gccfc9b2ad
Edition: Community
Git Commit Hash: ccfc9b2ad0dcf8e447210de5f559d7fc208db968
Git Branch: master
UTC Build Time: 2020-07-29 09:37:45
GoVersion: go1.13
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
1 row in set (0.01 sec)
```

**Comment by AilinKid** [comment] 2020-11-13 09:15
this issue has been resolved in https://github.com/pingcap/tidb/issues/19939

**Closed by AilinKid** 2020-11-13 09:15 UTC
Labels: sig/DDL, type/compatibility
