### ISSUE TITLE
infinite print "invalid cop task execution summaries length"

### ISSUE THREAD

**Issue by ChenPeng2013** [pingcap/tidb#18591] opened 2020-07-15 12:07 UTC
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```
./bin/tidb-server
```

### 3. What did you see instead (Required)
```
[2020/07/15 20:03:15.041 +08:00] [ERROR] [select_result.go:244] ["invalid cop task execution summaries length"] [expected=1] [received=0]
[2020/07/15 20:03:18.035 +08:00] [ERROR] [select_result.go:244] ["invalid cop task execution summaries length"] [expected=1] [received=0]
[2020/07/15 20:03:18.041 +08:00] [ERROR] [select_result.go:244] ["invalid cop task execution summaries length"] [expected=1] [received=0]
[2020/07/15 20:03:21.039 +08:00] [ERROR] [select_result.go:244] ["invalid cop task execution summaries length"] [expected=1] [received=0]
[2020/07/15 20:03:21.039 +08:00] [ERROR] [select_result.go:244] ["invalid cop task execution summaries length"] [expected=1] [received=0]
[2020/07/15 20:03:24.036 +08:00] [ERROR] [select_result.go:244] ["invalid cop task execution summaries length"] [expected=1] [received=0]
[2020/07/15 20:03:24.039 +08:00] [ERROR] [select_result.go:244] ["invalid cop task execution summaries length"] [expected=1] [received=0]
[2020/07/15 20:03:27.036 +08:00] [ERROR] [select_result.go:244] ["invalid cop task execution summaries length"] [expected=1] [received=0]
[2020/07/15 20:03:27.042 +08:00] [ERROR] [select_result.go:244] ["invalid cop task execution summaries length"] [expected=1] [received=0]
[2020/07/15 20:03:27.043 +08:00] [ERROR] [select_result.go:244] ["invalid cop task execution summaries length"] [expected=1] [received=0]
[2020/07/15 20:03:30.040 +08:00] [ERROR] [select_result.go:244] ["invalid cop task execution summaries length"] [expected=1] [received=0]
[2020/07/15 20:03:30.042 +08:00] [ERROR] [select_result.go:244] ["invalid cop task execution summaries length"] [expected=1] [received=0]
[2020/07/15 20:03:33.038 +08:00] [ERROR] [select_result.go:244] ["invalid cop task execution summaries length"] [expected=1] [received=0]
[2020/07/15 20:03:33.039 +08:00] [ERROR] [select_result.go:244] ["invalid cop task execution summaries length"] [expected=1] [received=0]
[2020/07/15 20:03:36.035 +08:00] [ERROR] [select_result.go:244] ["invalid cop task execution summaries length"] [expected=1] [received=0]
[2020/07/15 20:03:36.043 +08:00] [ERROR] [select_result.go:244] ["invalid cop task execution summaries length"] [expected=1] [received=0]
```
### 4. Affected version (Required)

master: v4.0.0-beta.2-779-g9e5e2a933-dev

**Comment by SunRunAway** [comment] 2020-07-17 03:46
Duplicate of #18575

**Closed by SunRunAway** 2020-07-17 03:46 UTC
Labels: component/coprocessor, type/bug
