### ISSUE TITLE
tidb_mem_quota_query does not work in hash_join

### ISSUE THREAD

**Issue by ChenPeng2013** [pingcap/tidb#17963] opened 2020-06-11 11:10 UTC
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
drop table if exists t, t2;
create table t(a int, b int);
insert into t values(1,2), (1,-1), (10,21);
create table t2(a int);
insert into t2 values(1), (2), (3);
insert into t2 select * from t2;
insert into t2 select * from t2;
insert into t2 select * from t2;
insert into t2 select * from t2;
insert into t2 select * from t2;
insert into t2 select * from t2;
insert into t2 select * from t2;
insert into t2 select * from t2;
insert into t2 select * from t2;
insert into t2 select * from t2;
insert into t2 select * from t2;
insert into t2 select * from t2;
insert into t2 select * from t2;
insert into t2 select * from t2;
insert into t2 select * from t2;
insert into t2 select * from t2;
insert into t2 select * from t2;
set tidb_mem_quota_query=2048;
select * from t, t2 where t.a=t2.a;
# tidb_mem_quaot_query does not work, mem_max=3MB 
set tidb_mem_quota_query=1048576;
select * from t, t2 where t.a=t2.a;
```
### 3. What did you see instead (Required)
[2020/06/11 19:01:12.930 +08:00] [INFO] [set.go:207] ["set session var"] [conn=2] [name=tidb_mem_quota_query] [val=2048]
[2020/06/11 19:01:12.977 +08:00] [INFO] [row_container.go:229] ["memory exceeds quota, spill to disk now."] [consumed=16864] [quota=**2048**]
[2020/06/11 19:01:23.077 +08:00] [INFO] [coprocessor.go:893] ["[TIME_COP_PROCESS] resp_time:10.143620988s txnStartTS:417300027259748352 region_id:8 store_addr:store1"] [conn=2]
[2020/06/11 19:01:23.081 +08:00] [WARN] [expensivequery.go:167] [expensive_query] [cost_time=10.147768557s] [cop_time=0.043798705s] [request_count=1] [num_cop_tasks=1] [process_avg_time=0s] [process_p90_time=0s] [process_max_time=0s] [process_max_addr=store1] [wait_avg_time=0s] [wait_p90_time=0s] [wait_max_time=0s] [wait_max_addr=store1] [stats=t:pseudo,t2:pseudo] [conn_id=2] [user=root] [database=test] [table_ids="[202,204]"] [txn_start_ts=417300027259748352] [mem_max="3231874 Bytes (3.082155227661133 MB)"] [sql="select * from t, t2 where t.a=t2.a"]
[2020/06/11 19:01:23.083 +08:00] [WARN] [expensivequery.go:167] [expensive_query] [cost_time=10.150066935s] [cop_time=0.043798705s] [request_count=1] [num_cop_tasks=1] [process_avg_time=0s] [process_p90_time=0s] [process_max_time=0s] [process_max_addr=store1] [wait_avg_time=0s] [wait_p90_time=0s] [wait_max_time=0s] [wait_max_addr=store1] [stats=t2:pseudo,t:pseudo] [conn_id=2] [user=root] [database=test] [table_ids="[202,204]"] [txn_start_ts=417300027259748352] [mem_max="**3231874 Bytes (3.082155227661133 MB)**"] [sql="**select * from t, t2 where t.a=t2.a**"]

[2020/06/11 19:01:28.684 +08:00] [INFO] [set.go:207] ["set session var"] [conn=2] [name=tidb_mem_quota_query] [val=**1048576**]
[2020/06/11 19:01:32.642 +08:00] [INFO] [coprocessor.go:893] ["[TIME_COP_PROCESS] resp_time:3.955017932s txnStartTS:417300031389564928 region_id:8 store_addr:store1"] [conn=2]
[2020/06/11 19:01:32.642 +08:00] [INFO] [row_container.go:229] ["memory exceeds quota, spill to disk now."] [consumed=3248738] [quota=1048576]
### 4. Affected version (Required)

```
Release Version: v4.0.0-54-gef315c143-dirty
Edition: Community
Git Commit Hash: ef315c143b2ea558ecdeadd1036e35517c8e944e
Git Branch: release-4.0
UTC Build Time: 2020-06-11 06:56:00
GoVersion: go1.13.1
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
```

### 5. Root Cause Analysis
!-- should be filled by the investigator before it's closed -->

**Comment by XuHuaiyu** [comment] 2020-06-15 07:57
This is caused by https://github.com/pingcap/tidb/issues/16696

This is expected behavior:
1. We will print the expensive query log only when the element is spilled to disk already. https://github.com/pingcap/tidb/blob/master/util/chunk/row_container.go#L222-L226
2. When `set tidb_mem_quota_query=2048`, the `spillToDisk` is triggered when building hashtable. When reading from the probe side, the mem quota will be exceeded again, and `AlreadySpilledSafe` will true, thus the expensive query log will be printed.
3. When `set tidb_mem_quota_query=1048576`, the `spillToDisk` is triggered when reading the probe side. When mem quota is exceeded, `AlreadySpilledSafe` will false, thus no log is printed.

**Comment by wshwsh12** [comment] 2020-06-30 11:08
Fixed by https://github.com/pingcap/tidb/pull/16895

**Closed by wshwsh12** 2020-06-30 11:08 UTC
Labels: component/executor, epic/memory-management, severity/major, type/bug
