### ISSUE TITLE
stats' gc process wrongly deletes the statistics of tables that are not analyzed in extreme situation

### ISSUE THREAD

**Issue by winoros** [pingcap/tidb#57983] opened 2024-12-04 09:56 UTC
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

like https://github.com/pingcap/tidb/issues/57901
![Image](https://github.com/user-attachments/assets/c73edeef-8556-4346-8c17-38c2ffd3d401)
It directly uses the condition `no row in mysql.stats_histograms` without checking whether the table meta exists to decide the existence the of table.

But actually, due to poor cooperation with the DDL module. It's possible that we lost the records in mysql.stats_histograms for a table if there are plenty of DDLs executed in a row.

### 4. What is your TiDB version? (Required)

current master

**Comment by Rustin170506** [comment] 2024-12-09 03:57
duplicate of https://github.com/pingcap/tidb/issues/57901

**Comment by winoros** [comment] 2024-12-09 17:26
We use this issue to record one different case of #57901

**Closed** 2024-12-11 13:31 UTC
Labels: type/bug, sig/planner, severity/major, affects-6.5, affects-7.1, affects-7.5, affects-8.1, affects-8.5
