### ISSUE TITLE
data race in unit test

### ISSUE THREAD

**Issue by zhangjinpeng1987** [pingcap/tidb#13879] opened 2019-12-03 12:24 UTC
https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tidb_ghpr_unit_test/detail/tidb_ghpr_unit_test/18442/pipeline

```
2019-12-03T11:58:47.635Z] WARNING: DATA RACE

[2019-12-03T11:58:47.635Z] Write at 0x00c018176000 by goroutine 454:

[2019-12-03T11:58:47.635Z]   runtime.slicecopy()

[2019-12-03T11:58:47.635Z]       /usr/local/go/src/runtime/slice.go:197 +0x0

[2019-12-03T11:58:47.635Z]   github.com/pingcap/tidb/util/chunk.(*Column).resize()

[2019-12-03T11:58:47.635Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/util/chunk/column.go:284 +0x410

[2019-12-03T11:58:47.635Z]   github.com/pingcap/tidb/expression.(*builtinEQStringSig).vecEvalInt()

[2019-12-03T11:58:47.635Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/util/chunk/column.go:387 +0x3ee

[2019-12-03T11:58:47.635Z]   github.com/pingcap/tidb/expression.(*ScalarFunction).VecEvalInt()

[2019-12-03T11:58:47.635Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/expression/scalar_function.go:46 +0x70

[2019-12-03T11:58:47.635Z]   github.com/pingcap/tidb/expression.VecEval()

[2019-12-03T11:58:47.635Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/expression/expression.go:426 +0x1f4

[2019-12-03T11:58:47.635Z]   github.com/pingcap/tidb/expression.VecEvalBool()

[2019-12-03T11:58:47.635Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/expression/expression.go:288 +0xb7b

[2019-12-03T11:58:47.635Z]   github.com/pingcap/tidb/expression.vectorizedFilter()

[2019-12-03T11:58:47.635Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/expression/chunk_executor.go:451 +0xf5

[2019-12-03T11:58:47.635Z]   github.com/pingcap/tidb/expression.VectorizedFilterConsiderNull()

[2019-12-03T11:58:47.635Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/expression/chunk_executor.go:363 +0x214

[2019-12-03T11:58:47.635Z]   github.com/pingcap/tidb/executor.(*SelectionExec).Next()

[2019-12-03T11:58:47.635Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/expression/chunk_executor.go:341 +0x873

[2019-12-03T11:58:47.635Z]   github.com/pingcap/tidb/executor.Next()

[2019-12-03T11:58:47.635Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/executor.go:210 +0x167

[2019-12-03T11:58:47.635Z]   github.com/pingcap/tidb/executor.(*projectionInputFetcher).run()

[2019-12-03T11:58:47.635Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/projection.go:317 +0x3ed

[2019-12-03T11:58:47.635Z] 

[2019-12-03T11:58:47.635Z] Previous read at 0x00c018176001 by goroutine 758:

[2019-12-03T11:58:47.635Z]   [failed to restore the stack]

[2019-12-03T11:58:47.635Z] 

[2019-12-03T11:58:47.635Z] Goroutine 454 (running) created at:

[2019-12-03T11:58:47.635Z]   github.com/pingcap/tidb/executor.(*ProjectionExec).prepare()

[2019-12-03T11:58:47.635Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/projection.go:243 +0xc04

[2019-12-03T11:58:47.635Z]   github.com/pingcap/tidb/executor.(*ProjectionExec).parallelExecute()

[2019-12-03T11:58:47.635Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/projection.go:188 +0x505

[2019-12-03T11:58:47.635Z]   github.com/pingcap/tidb/executor.(*ProjectionExec).Next()

[2019-12-03T11:58:47.635Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/projection.go:163 +0x107

[2019-12-03T11:58:47.635Z]   github.com/pingcap/tidb/executor.Next()

[2019-12-03T11:58:47.635Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/executor.go:210 +0x167

[2019-12-03T11:58:47.635Z]   github.com/pingcap/tidb/executor.(*SortExec).fetchRowChunks()

[2019-12-03T11:58:47.635Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/sort.go:103 +0x62d

[2019-12-03T11:58:47.635Z]   github.com/pingcap/tidb/executor.(*SortExec).Next()

[2019-12-03T11:58:47.635Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/sort.go:78 +0x496

[2019-12-03T11:58:47.635Z]   github.com/pingcap/tidb/executor.Next()

[2019-12-03T11:58:47.635Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/executor.go:210 +0x167

[2019-12-03T11:58:47.635Z]   github.com/pingcap/tidb/executor.(*recordSet).Next()

[2019-12-03T11:58:47.635Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/adapter.go:116 +0x9b

[2019-12-03T11:58:47.635Z]   github.com/pingcap/tidb/session.drainRecordSet()

[2019-12-03T11:58:47.635Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/session/session.go:888 +0x3f0

[2019-12-03T11:58:47.635Z]   github.com/pingcap/tidb/session.execRestrictedSQL()

[2019-12-03T11:58:47.635Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/session/session.go:827 +0x1a5

[2019-12-03T11:58:47.635Z]   github.com/pingcap/tidb/session.(*session).ExecRestrictedSQL()

[2019-12-03T11:58:47.635Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/session/session.go:771 +0x1c9

[2019-12-03T11:58:47.635Z]   github.com/pingcap/tidb/executor.(*ShowExec).fetchShowTableStatus()

[2019-12-03T11:58:47.635Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/show.go:348 +0x297

[2019-12-03T11:58:47.635Z]   github.com/pingcap/tidb/executor.(*ShowExec).fetchAll()

[2019-12-03T11:58:47.635Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/show.go:149 +0x165

[2019-12-03T11:58:47.635Z]   github.com/pingcap/tidb/executor.(*ShowExec).Next()

[2019-12-03T11:58:47.635Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/show.go:86 +0x522

[2019-12-03T11:58:47.635Z]   github.com/pingcap/tidb/executor.Next()

[2019-12-03T11:58:47.635Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/executor.go:210 +0x167

[2019-12-03T11:58:47.635Z]   github.com/pingcap/tidb/executor.(*recordSet).Next()

[2019-12-03T11:58:47.636Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/adapter.go:116 +0x9b

[2019-12-03T11:58:47.636Z]   github.com/pingcap/tidb/session.GetRows4Test()

[2019-12-03T11:58:47.636Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/session/tidb.go:322 +0x35a

[2019-12-03T11:58:47.636Z]   github.com/pingcap/tidb/executor_test.(*testSuite5).TestShowTableStatus()

[2019-12-03T11:58:47.636Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/show_test.go:396 +0x64c

[2019-12-03T11:58:47.636Z]   github.com/pingcap/tidb/executor_test.(*testSuite5).TestShowTableStatus()

[2019-12-03T11:58:47.636Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/show_test.go:387 +0x184

[2019-12-03T11:58:47.636Z]   runtime.call32()

[2019-12-03T11:58:47.636Z]       /usr/local/go/src/runtime/asm_amd64.s:539 +0x3a

[2019-12-03T11:58:47.636Z]   reflect.Value.Call()

[2019-12-03T11:58:47.636Z]       /usr/local/go/src/reflect/value.go:321 +0xd3

[2019-12-03T11:58:47.636Z]   github.com/pingcap/check.(*suiteRunner).forkTest.func1()

[2019-12-03T11:58:47.636Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/pkg/mod/github.com/tiancaiamao/check@v0.0.0-20191119042138-8e73d07b629d/check.go:854 +0x9aa

[2019-12-03T11:58:47.636Z]   github.com/pingcap/check.(*suiteRunner).forkCall.func1()

[2019-12-03T11:58:47.636Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/pkg/mod/github.com/tiancaiamao/check@v0.0.0-20191119042138-8e73d07b629d/check.go:739 +0x113

[2019-12-03T11:58:47.636Z] 

[2019-12-03T11:58:47.636Z] Goroutine 758 (running) created at:

[2019-12-03T11:58:47.636Z]   github.com/pingcap/check.(*suiteRunner).forkCall()

[2019-12-03T11:58:47.636Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/pkg/mod/github.com/tiancaiamao/check@v0.0.0-20191119042138-8e73d07b629d/check.go:734 +0x4a3

[2019-12-03T11:58:47.636Z]   github.com/pingcap/check.(*suiteRunner).forkTest()

[2019-12-03T11:58:47.636Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/pkg/mod/github.com/tiancaiamao/check@v0.0.0-20191119042138-8e73d07b629d/check.go:836 +0x1b9

[2019-12-03T11:58:47.636Z]   github.com/pingcap/check.(*suiteRunner).doRun()

[2019-12-03T11:58:47.636Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/pkg/mod/github.com/tiancaiamao/check@v0.0.0-20191119042138-8e73d07b629d/check.go:666 +0x13a

[2019-12-03T11:58:47.636Z]   github.com/pingcap/check.(*suiteRunner).asyncRun.func1()

[2019-12-03T11:58:47.636Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/pkg/mod/github.com/tiancaiamao/check@v0.0.0-20191119042138-8e73d07b629d/check.go:650 +0xae

[2019-12-03T11:58:47.636Z] ==================

```

**Comment by kennytm** [comment] 2020-01-09 09:58
Duplicate of #13869.

**Closed by kennytm** 2020-01-09 09:58 UTC
Labels: component/test, type/bug
