### ISSUE TITLE
TiDB query contains user-defined variables result is different from mysql

### ISSUE THREAD

**Issue by lizhenhuan** [pingcap/tidb#39667] opened 2022-12-06 09:19 UTC
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

create table tFC_ZJSQED
(
   KHH                  CHAR(12) not null,
   ZJZH                 CHAR(14) not null,
   JSRQ                 INT not null,
   CSED                 NUMERIC(16,2) not null,
   CSDJ                 NUMERIC(16,2) not null,
   BDED                 NUMERIC(16,2) not null,
   DJJE                 NUMERIC(16,2) not null,
   XTLX                 INT not null,
   JDBH                 INT not null,
   primary key (KHH, ZJZH, JSRQ, JDBH)
) ENGINE = InnoDB;
create index iFC_ZJSQED_XTLX_JDBH on tFC_ZJSQED(XTLX,JDBH);
insert tFC_ZJSQED (KHH,ZJZH,JSRQ,CSED,CSDJ,BDED,DJJE,XTLX,JDBH) values('000100000001','00010000000101',0,5000000,0,0,0,4,1);
insert tFC_ZJSQED (KHH,ZJZH,JSRQ,CSED,CSDJ,BDED,DJJE,XTLX,JDBH) values('000100000001','00010000000101',20220927,0,0,0,100,4,1);
insert tFC_ZJSQED (KHH,ZJZH,JSRQ,CSED,CSDJ,BDED,DJJE,XTLX,JDBH) values('000100000001','00010000000101',20220928,0,0,0,-300,4,1);
insert tFC_ZJSQED (KHH,ZJZH,JSRQ,CSED,CSDJ,BDED,DJJE,XTLX,JDBH) values('000100000001','00010000000101',20220930,0,0,0,150,4,1);

Execute query sql , this sql contains user-defined variables 
SELECT @kyzj:=@kyzj+CASE WHEN JSRQ<=20220927 THEN CSED-CSDJ-BDED-DJJE ELSE 
   CASE WHEN (@cdje:=@cdje+CSDJ+BDED+DJJE)>0 THEN LEAST(-@cdje,@cdje:=0) ELSE 0 END END 
   from tFC_ZJSQED A,(select @kyzj:=0.0,@cdje:=0.0) B WHERE ZJZH='00010000000101' and KHH='000100000001' ORDER BY JSRQ  

in mysql:
![Locw5Lb8P0](https://user-images.githubusercontent.com/3417765/205870077-1d628aee-06fe-4442-ba44-9e503bc431fa.jpg)

in TiDB:
![WsilsCaTFj](https://user-images.githubusercontent.com/3417765/205870156-08368c64-34fd-4594-9ffa-e6c20802a466.jpg)

TiDB result is different from mysql

### 2. What did you expect to see? (Required)
Same result with mysql 

### 3. What did you see instead (Required)
different result from mysql 
### 4. What is your TiDB version? (Required)

<img width="396" alt="image" src="https://user-images.githubusercontent.com/3417765/205870750-7ee03498-2285-4502-b122-60dcc10e22a6.png">

**Comment by zanmato1984** [comment] 2022-12-07 09:11
Redirect to planner.

**Comment by chrysan** [comment] 2023-01-09 13:56
It's because the output order of hash join is non-deterministic. Different build/probe sides will give different results:
```
mysql> SELECT /*+ HASH_JOIN_PROBE(B) */ @KYZJ:=@KYZJ+CASE WHEN JSRQ<=20220927 THEN CSED-CSDJ-BDED-DJJE ELSE CASE WHEN (@cdje:=@cdje+CSDJ+BDED+DJJE)>0 THEN LEAST(-@cdje,@cdje:=0) ELSE 0 END END from tFC_ZJSQED A,(select @KYZJ:=0.0,@cdje:=0.0) B WHERE ZJZH='00010000000101' and KHH='000100000001' ORDER BY JSRQ;
+----------------------------------------------------------------------------------------------------------------------------------------------------------+
| @KYZJ:=@KYZJ+CASE WHEN JSRQ<=20220927 THEN CSED-CSDJ-BDED-DJJE ELSE CASE WHEN (@cdje:=@cdje+CSDJ+BDED+DJJE)>0 THEN LEAST(-@cdje,@cdje:=0) ELSE 0 END END |
+----------------------------------------------------------------------------------------------------------------------------------------------------------+
|                                                                                                                                               4999750.00 |
|                                                                                                                                                  -250.00 |
|                                                                                                                                                  -150.00 |
|                                                                                                                                                  -150.00 |
+----------------------------------------------------------------------------------------------------------------------------------------------------------+
4 rows in set (0.01 sec)

mysql> SELECT /*+ HASH_JOIN_PROBE(A) */ @KYZJ:=@KYZJ+CASE WHEN JSRQ<=20220927 THEN CSED-CSDJ-BDED-DJJE ELSE CASE WHEN (@cdje:=@cdje+CSDJ+BDED+DJJE)>0 THEN LEAST(-@cdje,@cdje:=0) ELSE 0 END END from tFC_ZJSQED A,(select @KYZJ:=0.0,@cdje:=0.0) B WHERE ZJZH='00010000000101' and KHH='000100000001' ORDER BY JSRQ;
+----------------------------------------------------------------------------------------------------------------------------------------------------------+
| @KYZJ:=@KYZJ+CASE WHEN JSRQ<=20220927 THEN CSED-CSDJ-BDED-DJJE ELSE CASE WHEN (@cdje:=@cdje+CSDJ+BDED+DJJE)>0 THEN LEAST(-@cdje,@cdje:=0) ELSE 0 END END |
+----------------------------------------------------------------------------------------------------------------------------------------------------------+
|                                                                                                                                               5000000.00 |
|                                                                                                                                               4999900.00 |
|                                                                                                                                               4999900.00 |
|                                                                                                                                               4999750.00 |
+----------------------------------------------------------------------------------------------------------------------------------------------------------+
4 rows in set (0.00 sec)
mysql> SELECT /*+ HASH_JOIN_PROBE(B) */ * from tFC_ZJSQED A,(select @KYZJ:=0.0,@cdje:=0.0) B WHERE ZJZH='00010000000101' and KHH='000100000001';
+--------------+----------------+----------+------------+------+------+---------+------+------+------------+------------+
| KHH          | ZJZH           | JSRQ     | CSED       | CSDJ | BDED | DJJE    | XTLX | JDBH | @KYZJ:=0.0 | @cdje:=0.0 |
+--------------+----------------+----------+------------+------+------+---------+------+------+------------+------------+
| 000100000001 | 00010000000101 | 20220930 |       0.00 | 0.00 | 0.00 |  150.00 |    4 |    1 |        0.0 |        0.0 |
| 000100000001 | 00010000000101 | 20220928 |       0.00 | 0.00 | 0.00 | -300.00 |    4 |    1 |        0.0 |        0.0 |
| 000100000001 | 00010000000101 | 20220927 |       0.00 | 0.00 | 0.00 |  100.00 |    4 |    1 |        0.0 |        0.0 |
| 000100000001 | 00010000000101 |        0 | 5000000.00 | 0.00 | 0.00 |    0.00 |    4 |    1 |        0.0 |        0.0 |
+--------------+----------------+----------+------------+------+------+---------+------+------+------------+------------+
4 rows in set (0.00 sec)

mysql> SELECT /*+ HASH_JOIN_PROBE(A) */ * from tFC_ZJSQED A,(select @KYZJ:=0.0,@cdje:=0.0) B WHERE ZJZH='00010000000101' and KHH='000100000001';
+--------------+----------------+----------+------------+------+------+---------+------+------+------------+------------+
| KHH          | ZJZH           | JSRQ     | CSED       | CSDJ | BDED | DJJE    | XTLX | JDBH | @KYZJ:=0.0 | @cdje:=0.0 |
+--------------+----------------+----------+------------+------+------+---------+------+------+------------+------------+
| 000100000001 | 00010000000101 |        0 | 5000000.00 | 0.00 | 0.00 |    0.00 |    4 |    1 |        0.0 |        0.0 |
| 000100000001 | 00010000000101 | 20220927 |       0.00 | 0.00 | 0.00 |  100.00 |    4 |    1 |        0.0 |        0.0 |
| 000100000001 | 00010000000101 | 20220928 |       0.00 | 0.00 | 0.00 | -300.00 |    4 |    1 |        0.0 |        0.0 |
| 000100000001 | 00010000000101 | 20220930 |       0.00 | 0.00 | 0.00 |  150.00 |    4 |    1 |        0.0 |        0.0 |
+--------------+----------------+----------+------------+------+------+---------+------+------+------------+------------+
4 rows in set (0.01 sec)
```
Please use window function instead of user-defined variables.
And it's not an issue, the result is non-deterministic by design. So close it.

**Closed** 2023-01-09 13:57 UTC
Labels: type/bug, sig/planner, severity/moderate, affects-5.0, affects-5.1, affects-5.2, affects-5.3, affects-5.4, may-affects-4.0, affects-6.0, affects-6.1, affects-6.2, affects-6.3, affects-6.4
