### ISSUE TITLE
tidb connection running loop panic when do ddl（add and drop  column）

### ISSUE THREAD

**Issue by Lily2025** [pingcap/tidb#35672] opened 2022-06-23 06:29 UTC
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
Ordinary table without prune_mode
run workload：[2022/06/21 23:52:28.850 +08:00] [INFO] [cmd.go:124] ["Start remote command"] [cmd="sysbench --mysql-user=root --db-driver=mysql --time=0 --report-interval=10 --mysql-db=test --mysql-host=tc-tidb.endless-oltp-tps-814192-1-184 --mysql-port=4000 --threads=256 --tables=32 --table-size=10000000 --mysql-ignore-errors=2013,1213,1105,8028,9007,1205,9004 --point_selects=10 oltp_point_select run"]
do ddl：
[2022/06/22 00:43:09.277 +08:00] [INFO] [util.go:65] ["alter table sbtest17 drop column sys_col1;"]
[2022/06/22 00:43:09.825 +08:00] [INFO] [util.go:65] ["alter table sbtest18 add column sys_col1 int;"]
[2022/06/22 00:43:10.346 +08:00] [INFO] [util.go:65] ["alter table sbtest18 drop column sys_col1;"]
[2022/06/22 00:43:10.893 +08:00] [INFO] [util.go:65] ["alter table sbtest19 add column sys_col1 int;"]
[2022/06/22 00:43:11.466 +08:00] [INFO] [util.go:65] ["alter table sbtest19 drop column sys_col1;"]
[2022/06/22 00:43:12.008 +08:00] [INFO] [util.go:65] ["alter table sbtest2 add column sys_col1 int;"]
[2022/06/22 00:43:12.526 +08:00] [INFO] [util.go:65] ["alter table sbtest2 drop column sys_col1;"]
[2022/06/22 00:43:13.076 +08:00] [INFO] [util.go:65] ["alter table sbtest20 add column sys_col1 int;"]
[2022/06/22 00:43:13.599 +08:00] [INFO] [util.go:65] ["alter table sbtest20 drop column sys_col1;"]
[2022/06/22 00:43:14.153 +08:00] [INFO] [util.go:65] ["alter table sbtest21 add column sys_col1 int;"]
[2022/06/22 00:43:14.675 +08:00] [INFO] [util.go:65] ["alter table sbtest21 drop column sys_col1;"]
[2022/06/22 00:43:15.229 +08:00] [INFO] [util.go:65] ["alter table sbtest22 add column sys_col1 int;"]
[2022/06/22 00:43:15.755 +08:00] [INFO] [util.go:65] ["alter table sbtest22 drop column sys_col1;"]
[2022/06/22 00:43:16.302 +08:00] [INFO] [util.go:65] ["alter table sbtest23 add column sys_col1 int;"]
[2022/06/22 00:43:16.826 +08:00] [INFO] [util.go:65] ["alter table sbtest23 drop column sys_col1;"]
[2022/06/22 00:43:17.375 +08:00] [INFO] [util.go:65] ["alter table sbtest24 add column sys_col1 int;"]
[2022/06/22 00:43:17.897 +08:00] [INFO] [util.go:65] ["alter table sbtest24 drop column sys_col1;"]
[2022/06/22 00:43:18.444 +08:00] [INFO] [util.go:65] ["alter table sbtest25 add column sys_col1 int;"]
[2022/06/22 00:43:18.966 +08:00] [INFO] [util.go:65] ["alter table sbtest25 drop column sys_col1;"]

### 2. What did you expect to see? (Required)
tidb server connection normal

### 3. What did you see instead (Required)
tidb server connection panic

```
[2022/06/21 16:38:45.457 +00:00] [ERROR] [conn.go:1023] ["connection running loop panic"] [conn=1741] [lastSQL="SELECT c FROM sbtest28 WHERE id=? [arguments: 3889606]"] [err="runtime error: index out of range [0] with length 0"] [stack="goroutine 113572860 [running]:\ngithub.com/pingcap/tidb/server.(*clientConn).Run.func1(0x42c3af0, 0xc073e56f00, 0xc00cf17a40)\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/server/conn.go:1021 +0xbd\npanic(0x3b47940, 0xc06df57ba8)\n\t/usr/local/go/src/runtime/panic.go:965 +0x1b9\ngithub.com/pingcap/tidb/server.(*clientConn).writeResultset.func1(0xc0026e6f98, 0x42c3af0, 0xc06e959260, 0xc00cf17a40)\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/server/conn.go:2081 +0x4b3\npanic(0x3b47940, 0xc06df57ba8)\n\t/usr/local/go/src/runtime/panic.go:965 +0x1b9\ngithub.com/pingcap/tidb/executor.colNames2ResultFields(0xc0749eab40, 0x0, 0x0, 0x0, 0xc01d835b0c, 0x4, 0x0, 0x1c4af65, 0x1)\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/executor/adapter.go:102 +0x610\ngithub.com/pingcap/tidb/executor.(*recordSet).Fields(0xc0749eb450, 0x42c3af0, 0xc06e959260, 0xc0026e6d68)\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/executor/adapter.go:93 +0xe5\ngithub.com/pingcap/tidb/server.(*tidbResultSet).Columns(0xc0749eb4a0, 0x42c3af0, 0xc06e959260, 0xc0749eb4f0)\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/server/driver_tidb.go:348 +0xa2\ngithub.com/pingcap/tidb/server.(*clientConn).writeChunks(0xc00cf17a40, 0x42c3af0, 0xc06e959260, 0x42dd9b0, 0xc0749eb4a0, 0x1, 0x1, 0x42c4420, 0xc06ed1af00)\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/server/conn.go:2155 +0x762\ngithub.com/pingcap/tidb/server.(*clientConn).writeResultset(0xc00cf17a40, 0x42c3af0, 0xc06e959260, 0x42dd9b0, 0xc0749eb4a0, 0x1, 0x0, 0xc0749eb400, 0x0, 0x0)\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/server/conn.go:2096 +0x2ae\ngithub.com/pingcap/tidb/server.(*clientConn).executePreparedStmtAndWriteResult(0xc00cf17a40, 0x42c3af0, 0xc06e959260, 0x42f6488, 0xc019bed180, 0xc08f824280, 0x1, 0x1, 0x0, 0x0, ...)\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/server/conn_stmt.go:251 +0x368\ngithub.com/pingcap/tidb/server.(*clientConn).handleStmtExecute(0xc00cf17a40, 0x42c3a48, 0xc06e959260, 0xc06e241381, 0x13, 0x13, 0x0, 0x0)\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/server/conn_stmt.go:205 +0x645\ngithub.com/pingcap/tidb/server.(*clientConn).dispatch(0xc00cf17a40, 0x42c3a48, 0xc06e95e880, 0xc06e241380, 0x14, 0x13, 0x0, 0x0)\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/server/conn.go:1346 +0x110f\ngithub.com/pingcap/tidb/server.(*clientConn).Run(0xc00cf17a40, 0x42c3af0, 0xc073e56f00)\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/server/conn.go:1079 +0x29b\ngithub.com/pingcap/tidb/server.(*Server).onConn(0xc000635450, 0xc00cf17a40)\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/server/server.go:553 +0xaa5\ncreated by github.com/pingcap/tidb/server.(*Server).startNetworkListener\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/server/server.go:455 +0x91c\n"]

```

### 4. What is your TiDB version? (Required)
./tidb-server -V
 Release Version: v5.3.2
Edition: Community
Git Commit Hash: de7612f2223dbdb1154c4475b4a72adc2c8c386c
Git Branch: heads/refs/tags/v5.3.2
UTC Build Time: 2022-06-20 06:44:35

**Comment by Defined2014** [comment] 2022-07-27 03:53
Can't reproduce this problem, so change the severity to moderate.

**Comment by Defined2014** [comment] 2024-09-25 06:27
Close this issue temporarily because it cannot be reproduced. Please feel free to reopen it and contact me if this issue occur again.

**Closed by Defined2014** 2024-09-25 06:27 UTC
Labels: type/bug, sig/sql-infra, severity/moderate, affects-5.3, may-affects-4.0, may-affects-5.1, may-affects-5.2, may-affects-5.4, may-affects-5.0, may-affects-6.0, may-affects-6.1, may-affects-6.2, component/ddl
