### ISSUE TITLE
Execute the command:tiup cluster exec cluster_name -N node1,node2... --command "sudo reboot" ,then tidb server is down and the process is blocked

### ISSUE THREAD

**Issue by jt20190617** [pingcap/tidb#37500] opened 2022-08-31 06:40 UTC
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

1. Deploy the TIDB cluster on physical machines
2. Execute the command: tiup cluster exec cluster_name -N node1,node2,node3 --command "sudo reboot"
3. When the machine reboot is complete,then you can see that the TIDB server is down for a long time and the process is stuck: the TIDB process exists, but there is no log output

If multiple attempts fail, restart the server where TIDB resides before the server where PD resides.I think when TIDB starts before PD, it's possible to trigger problems

### 2. What did you expect to see? (Required)
The TIDB server process is running properly and is displayed as Up

### 3. What did you see instead (Required)
Tiup Indicates that the TIDB server is Down and the process is blocked. No log is generated

### 4. What is your TiDB version? (Required)
v6.0.0

**Comment by tiancaiamao** [comment] 2022-09-01 02:14
TiDB try to connect to PD, if it can't connect to PD, after 100s, the process exit.
I think the problem is, why PD is not ready...

**Comment by jebter** [comment] 2024-09-03 08:51
The issue has not been updated for too long, so I will close it，if there are any updates, you can reopen it. You can ask new questions at https://ask.pingcap.com/ or https://asktug.com/ (Chinese) or https://ask.pingcap.com/(English)

**Closed by jebter** 2024-09-03 08:51 UTC
Labels: type/question, sig/sql-infra
