### ISSUE TITLE
Support `minus/except` and `intersect` set operations for TiDB.

### ISSUE THREAD

**Issue by lzmhhh123** [pingcap/tidb#18313] opened 2020-07-01 09:41 UTC
## Feature Request

TiDB supports `union` and `union all` set operations in v4.0.

It's better also to support `minus/except` and `intersect`.

oracle reference: https://docs.oracle.com/cd/B19306_01/server.102/b14200/queries004.htm

**Comment by SunRunAway** [comment] 2020-07-02 05:55
Duplicate of #18031

**Comment by zz-jason** [comment] 2020-07-02 05:55
Do we need to support minus and except at the same time? Although the name is different in different databases, but the functionality is the same.

**Closed** 2020-07-02 05:55 UTC
Labels: component/executor, status/help-wanted, type/feature-request

**Comment by lzmhhh123** [comment] 2020-07-02 05:58
> Do we need to support minus and except at the same time? Although the name is different in different databases, but the functionality is the same.

There are just different in grammar and parser layer. I think we can support them both.
