### ISSUE TITLE
could create partition table with FOREIGN KEY

### ISSUE THREAD

**Issue by aytrack** [pingcap/tidb#32234] opened 2022-02-10 08:27 UTC
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```sql
drop table if exists product, product_order, customer;
CREATE TABLE product (
    category INT NOT NULL, id INT NOT NULL,
    price DECIMAL,
    PRIMARY KEY(category, id)
);
CREATE TABLE customer (
    id INT NOT NULL,
    PRIMARY KEY (id)
);

--error Foreign keys are not yet supported in conjunction with partitioning
CREATE TABLE product_order (
    no INT NOT NULL AUTO_INCREMENT,
    product_category INT NOT NULL,
    product_id INT NOT NULL,
    customer_id INT NOT NULL,

    PRIMARY KEY(no),
    INDEX (product_category, product_id),
    INDEX (customer_id),

    FOREIGN KEY (product_category, product_id)
      REFERENCES product(category, id)
      ON UPDATE CASCADE ON DELETE RESTRICT,

    FOREIGN KEY (customer_id)
      REFERENCES customer(id)
    ) partition by range (no) (
    partition p0 values less than (10),
    partition p1 values less than (20)
);
```

### 2. What did you expect to see? (Required)
failed to create table `product_order` 
### 3. What did you see instead (Required)
create table `product_order` successfully
```sql
MySQL root@127.0.0.1:test> show create table  product_order\G
***************************[ 1. row ]***************************
Table        | product_order
Create Table | CREATE TABLE `product_order` (
  `no` int(11) NOT NULL AUTO_INCREMENT,
  `product_category` int(11) NOT NULL,
  `product_id` int(11) NOT NULL,
  `customer_id` int(11) NOT NULL,
  PRIMARY KEY (`no`) /*T![clustered_index] CLUSTERED */,
  KEY `product_category` (`product_category`,`product_id`),
  KEY `customer_id` (`customer_id`),
  CONSTRAINT `product_category` FOREIGN KEY (`product_category`,`product_id`) REFERENCES `product` (`category`,`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `customer_id` FOREIGN KEY (`customer_id`) REFERENCES `customer` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin
PARTITION BY RANGE (`no`)
(PARTITION `p0` VALUES LESS THAN (10),
 PARTITION `p1` VALUES LESS THAN (20))
```
### 4. What is your TiDB version? (Required)
```sql
MySQL root@127.0.0.1:test> select tidb_version()\G
***************************[ 1. row ]***************************
tidb_version() | Release Version: v5.5.0-alpha-234-g19a020c59-dirty
Edition: Community
Git Commit Hash: 19a020c59956d1f430c41ca9d168a7417dc33490
Git Branch: master
UTC Build Time: 2022-01-27 03:45:36
GoVersion: go1.17.2
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false

```

**Comment by mjonss** [comment] 2022-02-10 10:58
So the issue is that there is no error when using foreign keys on partitioned tables, when MySQL would issue one:
```
ERROR 1506 (HY000): Foreign keys are not yet supported in conjunction with partitioning
```

But since TiDB does not support Foreign keys currently I do not think we should return an error for foreign keys on partitioned tables, since we do not do it for non-partitioned tables where we also do not support it (or rather we parse it and store the constraints, but we do not check or enforce the foreign key constraints).

Reference to Foreign key support in documentation: https://docs.pingcap.com/tidb/dev/constraints#foreign-key

I think this should be a feature request and maybe even closed as a duplicate of #18209.

**Comment by bb7133** [comment] 2022-05-09 05:53
@zimulala Since it is an enhancement, I think we could keep it open.

**Closed** 2023-05-22 18:12 UTC
Labels: type/enhancement, sig/sql-infra, component/tablepartition

**Comment by akbariandev** [comment] 2025-06-11 17:00
Any update ?
