### ISSUE TITLE
testInfoschemaTableSuite.TestDataForTableStatsField test not stable

### ISSUE THREAD

**Issue by tiancaiamao** [pingcap/tidb#15264] opened 2020-03-10 10:38 UTC
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?

Find in https://github.com/pingcap/tidb/pull/15261

https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tidb_ghpr_unit_test/detail/tidb_ghpr_unit_test/26947/pipeline

FAIL: infoschema_reader_test.go:219: testInfoschemaTableSuite.TestDataForTableStatsField

2. What did you expect to see?

Success

3. What did you see instead?

```
[2020-03-10T09:52:01.311Z] ----------------------------------------------------------------------
[2020-03-10T09:52:01.311Z] FAIL: infoschema_reader_test.go:219: testInfoschemaTableSuite.TestDataForTableStatsField
[2020-03-10T09:52:01.311Z] 
[2020-03-10T09:52:01.311Z] infoschema_reader_test.go:266:
[2020-03-10T09:52:01.311Z]     tk.MustQuery("select table_rows, avg_row_length, data_length, index_length from information_schema.tables where table_name='t'").Check(
[2020-03-10T09:52:01.311Z]         testkit.Rows("3 18 54 6"))
[2020-03-10T09:52:01.311Z] /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/util/testkit/testkit.go:62:
[2020-03-10T09:52:01.311Z]     res.c.Assert(resBuff.String(), check.Equals, needBuff.String(), res.comment)
[2020-03-10T09:52:01.311Z] ... obtained string = "[0 0 0 0]\n"
[2020-03-10T09:52:01.311Z] ... expected string = "[3 18 54 6]\n"
[2020-03-10T09:52:01.311Z] ... sql:select table_rows, avg_row_length, data_length, index_length from information_schema.tables where table_name='t', args:[]
[2020-03-10T09:52:01.311Z] 
[2020-03-10T09:52:01.311Z] 
[2020-03-10T09:52:01.311Z] ----------------------------------------------------------------------
```

CI hang for 15min before exit.

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

master e4762f28e9b34bc5fc50c87a0e8de8aba4d92e10

**Comment by SunRunAway** [comment] 2020-03-10 11:22
Duplicate of #15222 
@tiancaiamao search first 😂

**Closed by SunRunAway** 2020-03-10 11:22 UTC
Labels: type/bug
