### ISSUE TITLE
request to support `ST_GeoHash()` functions

### ISSUE THREAD

**Issue by hezhiqiang** [pingcap/tidb#18047] opened 2020-06-16 04:46 UTC
希望能够支持st_geohash等函数

**Comment by zz-jason** [comment] 2020-07-09 03:59
@hezhiqiang Do you mean to support all the Spatial Geohash Functions in MysQL?

**Comment by hezhiqiang** [comment] 2020-07-09 04:09
@zz-jason support all is best~

**Comment by zz-jason** [comment] 2020-07-09 04:58
Could you describe more about the usage of these functions, for example, do you use TiDB to store spatial data and doing the spatial analysis?

**Comment by nullnotnil** [comment] 2020-07-30 19:05
I am going to close this as a duplicate of https://github.com/pingcap/tidb/issues/6347 , which is a more broad request for SPATIAL functions and indexes. Thanks!

**Closed by nullnotnil** 2020-07-30 19:05 UTC
Labels: type/duplicate, type/feature-request
