### ISSUE TITLE
Specified key was too long; max key length is xxxx bytes

### ISSUE THREAD

**Issue by yangwenmai** [pingcap/tidb#4121] opened 2017-08-09 23:47 UTC
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

In InnoDB or MyISAM and other storage engines, not based on the character set utf8 or utf8mb4 or other charset distinction between Specified key Length。

(1)CREATE TABLE t ( a varchar(769), KEY (a)) ENGINE=InnoDB CHARSET=utf8mb4;
(2)CREATE TABLE t ( a varchar(1025), KEY (a)) ENGINE=InnoDB CHARSET=utf8;
(3)CREATE TABLE t ( a varchar(251), KEY (a)) ENGINE=MyISAM CHARSET=utf8mb4;
(4)CREATE TABLE t ( a varchar(334), KEY (a)) ENGINE=MyISAM CHARSET=utf8;

2. What did you expect to see?

(1)Specified key was too long; max key length is 3072 bytes
(2)Specified key was too long; max key length is 3072 bytes
(3)Specified key was too long; max key length is 1000 bytes
(4)Specified key was too long; max key length is 1000 bytes

3. What did you see instead?

all show:

Query OK, 0 rows affected (0.00 sec)

4. What version of TiDB are you using (`tidb-server -V`)?

Git Commit Hash: 3991f38cd09bd2988691192537acf1b9e39bc48f
UTC Build Time:  2017-08-09 10:57:21

refer to #2272 and #2380 .

**Comment by shenli** [comment] 2017-08-13 07:37
@yangwenmai Thanks for your feedback!
@jackysp @tiancaiamao PTAL

**Comment by zz-jason** [comment] 2017-08-13 07:46
related to this issue https://github.com/pingcap/tidb/issues/3983

**Comment by jackysp** [comment] 2017-08-14 05:50
It seems TiDB does not divide charset length when create index.

**Comment by morgo** [comment] 2018-11-24 16:54
I don't think TiDB requires compatibility down to the engine=myisam / innodb level.  InnoDB can be different depending on the row-format as well (the default in 5.7 allows for 3072).

I believe the issue here is that in TiDB, the number in brackets is specified in bytes, whereas in MySQL it is specified in characters (I believe this is SQL standards compliant).  See:

```
create table t1 (a varchar(3072), index(a)) character set utf8mb4;
create table t2 (a varchar(3073), index(a)) character set utf8mb4;

mysql> create table t1 (a varchar(3072), index(a)) character set utf8mb4;
Query OK, 0 rows affected (0.01 sec)

mysql> create table t2 (a varchar(3073), index(a)) character set utf8mb4;
ERROR 1071 (42000): Specified key was too long; max key length is 3072 bytes
```

This could be important for the edge case that a value is truncated, and a constraint is incorrectly applied etc.

**Comment by nullnotnil** [comment] 2020-07-29 23:17
This has been fixed in master - the limits are now the same as in InnoDB:
```sql
mysql> CREATE TABLE t1 ( a varchar(769), KEY (a)) ENGINE=InnoDB CHARSET=utf8mb4;
ERROR 1071 (42000): Specified key was too long; max key length is 3072 bytes
mysql> CREATE TABLE t2 ( a varchar(1025), KEY (a)) ENGINE=InnoDB CHARSET=utf8;
ERROR 1071 (42000): Specified key was too long; max key length is 3072 bytes
mysql> CREATE TABLE t3 ( a varchar(251), KEY (a)) ENGINE=MyISAM CHARSET=utf8mb4;
Query OK, 0 rows affected (0.09 sec)

mysql> CREATE TABLE t4 ( a varchar(334), KEY (a)) ENGINE=MyISAM CHARSET=utf8;
Query OK, 0 rows affected (0.11 sec)

mysql> SELECT tidb_version()\G
*************************** 1. row ***************************
tidb_version(): Release Version: v4.0.0-beta.2-852-g1e7454c81
Edition: Community
Git Commit Hash: 1e7454c81d1f4fae464e835d1a4023a911cfa87b
Git Branch: master
UTC Build Time: 2020-07-28 01:36:23
GoVersion: go1.13
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
1 row in set (0.00 sec)
```

I am going to close this issue now. Thanks!

**Comment by brucen1030** [comment] 2020-08-03 01:33
> This has been fixed in master - the limits are now the same as in InnoDB:
> 
> ```sql
> mysql> CREATE TABLE t1 ( a varchar(769), KEY (a)) ENGINE=InnoDB CHARSET=utf8mb4;
> ERROR 1071 (42000): Specified key was too long; max key length is 3072 bytes
> mysql> CREATE TABLE t2 ( a varchar(1025), KEY (a)) ENGINE=InnoDB CHARSET=utf8;
> ERROR 1071 (42000): Specified key was too long; max key length is 3072 bytes
> mysql> CREATE TABLE t3 ( a varchar(251), KEY (a)) ENGINE=MyISAM CHARSET=utf8mb4;
> Query OK, 0 rows affected (0.09 sec)
> 
> mysql> CREATE TABLE t4 ( a varchar(334), KEY (a)) ENGINE=MyISAM CHARSET=utf8;
> Query OK, 0 rows affected (0.11 sec)
> 
> mysql> SELECT tidb_version()\G
> *************************** 1. row ***************************
> tidb_version(): Release Version: v4.0.0-beta.2-852-g1e7454c81
> Edition: Community
> Git Commit Hash: 1e7454c81d1f4fae464e835d1a4023a911cfa87b
> Git Branch: master
> UTC Build Time: 2020-07-28 01:36:23
> GoVersion: go1.13
> Race Enabled: false
> TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
> Check Table Before Drop: false
> 1 row in set (0.00 sec)
> ```
> 
> I am going to close this issue now. Thanks!

Hi,
What's the influence if in the old version we configured key more than 3072 byte?
It seems working correctly.
And what will happen if we upgrade from old version to tidb with this fix?

Is it possible to provide a configuration option to enable/disable 3072 byte key length check, for better compatibility with old tidb? Our service is already running on old tidb.

Thanks.

**Comment by nullnotnil** [comment] 2020-08-03 01:47
@brucen1030 I believe you are right, there could be a case where there could be an upgrade issue.

i.e. `VARCHAR(1024)` previously implied 1024 bytes, now it (correctly) implies 1024 characters, which could be 1024*4 = 4096 bytes. That would exceed the 3072 byte index length.

I think there is a workaround by using 3-byte utf8 instead (which would have been the default around the time TiDB had this issue, possibly completely mitigating the issue). At some point, an option to make 3-byte utf8 MySQL compatible was also added. But you can disable this if you need to as well: `check-mb4-value-in-utf8=FALSE`.

Do you mind sharing what version of TiDB you are using so that I can try and reproduce with a test case?

**Comment by brucen1030** [comment] 2020-08-03 02:14
@nullnotnil thanks to your quick reply.

Let me clarify my problem clearer.
In fact, we use tidb 2.1.8 in our service from years ago. And we defined a union key with length at most more than 1024 character. In utf8, it's more than 3072 bytes in total and didn't returned any error. (Yes, we use utf8 already. )
And we found in tidb master branch, it returned the error as per title recently. 
I understand it's innodb limitation of the key length, but our service requires about 13xx character union key length in total.
My concern is, is it risky in 2.1.8 to continue to use a union key with length 13xx charactor, or is there any invisible error happend?

And if there is no indeed influence on tidb, (as we see, it exists from years ago, and fixed for only compatibility with innodb), is it possible to provide a configuration option to disable 3072 byte check?

`MySQL [(none)]> SELECT tidb_version();
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| tidb_version()                                                                                                                                                                                                                                                                                                |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Release Version: v2.1.8
Git Commit Hash: 9a2d2da372947a50a02f9b9238a49f2db7ab9971
Git Branch: HEAD
UTC Build Time: 2019-04-12 07:48:47
GoVersion: go version go1.11.2 linux/amd64
Race Enabled: false
TiKV Min Version: 2.1.0-alpha.1-ff3dd160846b7d1aed9079c389fc188f7f5ea13e
Check Table Before Drop: false |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)
`

**Comment by nullnotnil** [comment] 2020-08-03 02:50
Thanks @brucen1030. I have 2.1.5 handy, so I tried the following testcase:
```sql
DROP TABLE IF EXISTS t1, t2;

CREATE TABLE t1 (
 id INT NOT NULL PRIMARY KEY auto_increment,
 b varchar(1024),
 c varchar(255),
 INDEX (b,c)
);

CREATE TABLE t2 (
 id INT NOT NULL PRIMARY KEY auto_increment,
 b varchar(1024),
 c varchar(255),
 INDEX (b,c)
) character set utf8mb4;
```

Against TiDB 2.1:

```sql
mysql> CREATE TABLE t1 (
    ->  id INT NOT NULL PRIMARY KEY auto_increment,
    ->  b varchar(1024),
    ->  c varchar(255),
    ->  INDEX (b,c)
    -> );
Query OK, 0 rows affected (0.11 sec)

mysql> 
mysql> CREATE TABLE t2 (
    ->  id INT NOT NULL PRIMARY KEY auto_increment,
    ->  b varchar(1024),
    ->  c varchar(255),
    ->  INDEX (b,c)
    -> ) character set utf8mb4;
Query OK, 0 rows affected (0.10 sec)

mysql> SELECT tidb_version()\G
*************************** 1. row ***************************
tidb_version(): Release Version: v2.1.5-1-g0bd6b1b
Git Commit Hash: 0bd6b1b60816bf8a2022e657d7a472311548d82e
Git Branch: release-2.1
UTC Build Time: 2019-02-28 08:17:03
GoVersion: go version go1.11.2 linux/amd64
Race Enabled: false
TiKV Min Version: 2.1.0-alpha.1-ff3dd160846b7d1aed9079c389fc188f7f5ea13e
Check Table Before Drop: false
1 row in set (0.01 sec)
```

Against master:

```
mysql> CREATE TABLE t1 (
    ->  id INT NOT NULL PRIMARY KEY auto_increment,
    ->  b varchar(1024),
    ->  c varchar(255),
    ->  INDEX (b,c)
    -> );
ERROR 1071 (42000): Specified key was too long; max key length is 3072 bytes
mysql> 
mysql> CREATE TABLE t2 (
    ->  id INT NOT NULL PRIMARY KEY auto_increment,
    ->  b varchar(1024),
    ->  c varchar(255),
    ->  INDEX (b,c)
    -> ) character set utf8mb4;
ERROR 1071 (42000): Specified key was too long; max key length is 3072 bytes
mysql> SELECT tidb_version()\G
*************************** 1. row ***************************
tidb_version(): Release Version: v4.0.0-beta.2-870-g2a8b96845
Edition: Community
Git Commit Hash: 2a8b968453520e4fcf9d6ff46c9f23b4ad23feee
Git Branch: master
UTC Build Time: 2020-07-31 08:45:35
GoVersion: go1.13
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
1 row in set (0.00 sec)
```

So from a logical restore perspective at least, it looks like this will be an issue. I did some digging into the configuration file for TiDB though, and there is an option which does as you suggested:

```
# max-index-length is used to deal with compatibility issues from v3.0.7 and previous version upgrades. It can only be in [3072, 3072*4].
max-index-length = 3072
```

If I set this to 12288, the testcase in master produces the same result as 2.1:

```sql
mysql> CREATE TABLE t1 (
    ->  id INT NOT NULL PRIMARY KEY auto_increment,
    ->  b varchar(1024),
    ->  c varchar(255),
    ->  INDEX (b,c)
    -> );
Query OK, 0 rows affected (0.09 sec)

mysql> 
mysql> CREATE TABLE t2 (
    ->  id INT NOT NULL PRIMARY KEY auto_increment,
    ->  b varchar(1024),
    ->  c varchar(255),
    ->  INDEX (b,c)
    -> ) character set utf8mb4;
Query OK, 0 rows affected (0.10 sec)

mysql> SELECT tidb_version()\G
*************************** 1. row ***************************
tidb_version(): Release Version: v4.0.0-beta.2-870-g2a8b96845
Edition: Community
Git Commit Hash: 2a8b968453520e4fcf9d6ff46c9f23b4ad23feee
Git Branch: master
UTC Build Time: 2020-07-31 08:45:35
GoVersion: go1.13
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
1 row in set (0.00 sec)
```

**Comment by brucen1030** [comment] 2020-08-03 03:45
@nullnotnil Thanks a lot!

**Comment by nullnotnil** [comment] 2020-08-03 03:49
You are welcome. I am going to reclose this issue now.

**Closed by nullnotnil** 2020-08-03 03:49 UTC
Labels: status/help-wanted, type/compatibility
