### ISSUE TITLE
Java project use jdbc connection  create  tidb table with AUTO_ID_CACHE=1 , create table failed

### ISSUE THREAD

**Issue by jisongxi** [pingcap/tidb#48014] opened 2023-10-26 11:51 UTC
use jdbc connector new version,
<dependency>
            <groupId>mysql</groupId>
            <artifactId>mysql-connector-java</artifactId>
            <version>8.0.33</version>
</dependency>

sql:
CREATE TABLE `his_config_info` (
                                   `id` bigint(64) unsigned NOT NULL,
                                   `nid` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
                                   `data_id` varchar(255) NOT NULL,
                                   `group_id` varchar(128) NOT NULL,
                                   `app_name` varchar(128) DEFAULT NULL COMMENT 'app_name',
                                   `content` longtext NOT NULL,
                                   `md5` varchar(32) DEFAULT NULL,
                                   `gmt_create` datetime NOT NULL DEFAULT '2010-05-05 00:00:00',
                                   `gmt_modified` datetime NOT NULL DEFAULT '2010-05-05 00:00:00',
                                   `src_user` text,
                                   `src_ip` varchar(20) DEFAULT NULL,
                                   `op_type` char(10) DEFAULT NULL,
                                   `tenant_id` varchar(128) DEFAULT '' COMMENT '租户字段',
                                   `encrypted_data_key` text NOT NULL COMMENT '秘钥',
                                   PRIMARY KEY (`nid`),
                                   KEY `idx_gmt_create` (`gmt_create`),
                                   KEY `idx_gmt_modified` (`gmt_modified`),
                                   KEY `idx_did` (`data_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin AUTO_ID_CACHE=1 COMMENT='多租户改造';

exception:
![image](https://github.com/pingcap/tidb/assets/9650220/f080cab7-f0be-47f8-b30f-51ac62fa4a55)

**Comment by lastincisor** [comment] 2023-10-27 08:41
use mysql-connector-java 8.0.33  + tidb  no recurrence this error.

`private static void create(Connection conn){
        JDBCRun.of(conn).runBaseExecute("DROP TABLE IF EXISTS his_config_info");
        JDBCRun.of(conn).runBaseExecute("CREATE TABLE his_config_info (\n" +
                "id bigint(64) unsigned NOT NULL,\n" +
                "nid bigint(20) unsigned NOT NULL AUTO_INCREMENT,\n" +
                "data_id varchar(255) NOT NULL,\n" +
                "group_id varchar(128) NOT NULL,\n" +
                "app_name varchar(128) DEFAULT NULL COMMENT 'app_name',\n" +
                "content longtext NOT NULL,\n" +
                "md5 varchar(32) DEFAULT NULL,\n" +
                "gmt_create datetime NOT NULL DEFAULT '2010-05-05 00:00:00',\n" +
                "gmt_modified datetime NOT NULL DEFAULT '2010-05-05 00:00:00',\n" +
                "src_user text,\n" +
                "src_ip varchar(20) DEFAULT NULL,\n" +
                "op_type char(10) DEFAULT NULL,\n" +
                "tenant_id varchar(128) DEFAULT '' COMMENT '租户字段',\n" +
                "encrypted_data_key text NOT NULL COMMENT '秘钥',\n" +
                "PRIMARY KEY (nid),\n" +
                "KEY idx_gmt_create (gmt_create),\n" +
                "KEY idx_gmt_modified (gmt_modified),\n" +
                "KEY idx_did (data_id)\n" +
                ") ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin AUTO_ID_CACHE=1 COMMENT='多租户改造'");
    }


    public static void main(String @NotNull [] args) {
        String user = "root";
        String password = "";
        try {
            Map<String,String> parameter = new HashMap<>();
            Connection conn = ConnectionBuilder.mysql("1.1.1.1:4000","db",user,password)
                    .buildSocket().appendParameter()
                    .buildParameter(parameter).appendParameter()
                    .connection();
            create( conn);
            //insert( conn,"111");
            //query( conn);
        }catch (Exception e){
            log.error(e.getMessage());
        }
    }`



It's not a bug, it's as expected

**Comment by tiancaiamao** [comment] 2023-11-29 11:08
can't reproduce on TiDB

Are you connecting to MySQL instead of TiDB?  @jisongxi 
AUTO_ID_CACHE=1 is tidb specific syntax, if you send SQL this to mysql you would get similar error message.

**Comment by dveeden** [comment] 2023-12-27 07:48
This doesn't look like a bug. It looks like the statement with `AUTO_ID_CACHE=` in it was sent to MySQL without wrapping it in TiDB specific comments. I would suggest to close this issue for now.

**Closed** 2023-12-29 07:34 UTC
Labels: type/bug, component/jdbc
