### ISSUE TITLE
Cannot use navicat to manage users

### ISSUE THREAD

**Issue by breeswish** [pingcap/tidb#3643] opened 2017-07-06 06:46 UTC
Navicat throws error "unknown column ssl_type" when trying to view users and no users are shown in the grid view after that.

Navicat version: 11.1.15 (Mac)
TiDB version: 467a01a2d01e210fbf44202870cf82ae54464167 (2017-07-05 09:11:12)

**Comment by morgo** [comment] 2019-03-21 22:04
This is caused by https://github.com/pingcap/tidb/issues/9655

I am going to close this issue to reduce duplication and will leave a comment in the other issue that it breaks Navicat compatibility.

**Closed by morgo** 2019-03-21 22:04 UTC
Labels: type/compatibility
