### ISSUE TITLE
rolling_update error

### ISSUE THREAD

**Issue by nickzhao0617** [pingcap/tidb#6934] opened 2018-06-28 13:24 UTC
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
Today, i'll update the tidb v2.0.4, but when i rolling_update pd, it has an error that ansible can't up the pd node. i tried many times, but failed, so delete the whole pd directory and retried reinstall. Now the new pd can't join the older cluster which i use official way to do it.

2. What version of PD?
Cause i delete my original downloads, so i don't know my pd version is, how to find the version is?

**Comment by jackysp** [comment] 2018-06-29 03:07
Thank you for your feedback, @nickzhao0617 !
I think deleting the pd data directory is not the right way to fix the update issue. Can you show us the error messages you met when updating the cluster?

**Comment by nickzhao0617** [comment] 2018-06-29 03:46
@jackysp 
Sorry, i have deleted the whole directory include the log file, but i used another way to fix the problem.
I remove the pd1 from the cluster and join pd4 to the cluster but failed. The pd4 has started up but can't join the cluster, instead it becoming another master pd and can't find the tikv.
here below is the log information:
2018/06/29 10:25:22.407 util.go:62: [info] Welcome to Placement Driver (PD).
2018/06/29 10:25:22.407 util.go:62: [info] Welcome to Placement Driver (PD).
2018/06/29 10:25:22.407 util.go:63: [info] Release Version: v2.0.4
2018/06/29 10:25:22.407 util.go:64: [info] Git Commit Hash: b6f9f8aeb0a5a23494204509e2bb5ce5132b715f
2018/06/29 10:25:22.407 util.go:65: [info] Git Branch: release-2.0
2018/06/29 10:25:22.407 util.go:66: [info] UTC Build Time:  2018-06-15 10:06:52
2018/06/29 10:25:22.407 metricutil.go:87: [info] start Prometheus push client
2018/06/29 10:25:22.408 server.go:96: [info] PD config - Config({FlagSet:0xc4200853e0 Version:false ClientUrls:http://10.2.0.80:2379 PeerUrls:http://10.2.0.80:2380 AdvertiseClientUrls:http://10.2.0.80:2379 AdvertisePeerUrls:http://10.2.0.80:2380 Name:pd4 DataDir:/home/tidb/deploy/data.pd InitialCluster: InitialClusterState:existing Join:http://10.2.0.76:2379 LeaderLease:3 Log:{Level:info Format:text DisableTimestamp:false File:{Filename:/home/tidb/deploy/log/pd.log LogRotate:true MaxSize:300 MaxDays:0 MaxBackups:0}} LogFileDeprecated: LogLevelDeprecated: TsoSaveInterval:3s Metric:{PushJob:pd4 PushAddress:10.2.0.78:9091 PushInterval:15s} Schedule:{MaxSnapshotCount:3 MaxPendingPeerCount:16 MaxMergeRegionSize:0 SplitMergeInterval:1h0m0s PatrolRegionInterval:100ms MaxStoreDownTime:30m0s LeaderScheduleLimit:4 RegionScheduleLimit:4 ReplicaScheduleLimit:8 MergeScheduleLimit:8 TolerantSizeRatio:5 LowSpaceRatio:0.8 HighSpaceRatio:0.6 EnableRaftLearner:false Schedulers:[{Type:balance-region Args:[] Disable:false} {Type:balance-leader Args:[] Disable:false} {Type:hot-region Args:[] Disable:false} {Type:label Args:[] Disable:false}]} Replication:{MaxReplicas:3 LocationLabels:[]} Namespace:map[] QuotaBackendBytes:0 AutoCompactionRetention:1 TickInterval:500ms ElectionInterval:3s Security:{CAPath: CertPath: KeyPath:} LabelProperty:map[] configFile:conf/pd.toml WarningMsgs:[] NamespaceClassifier:table nextRetryDelay:1000000000 disableStrictReconfigCheck:false heartbeatStreamBindInterval:{Duration:60000000000} leaderPriorityCheckInterval:{Duration:60000000000}})
2018/06/29 10:25:22.410 server.go:122: [info] start embed etcd
2018/06/29 10:25:22.410 systime_mon.go:24: [info] start system time monitor
2018/06/29 10:25:22.410 log.go:86: [info] embed: [listening for peers on  http://10.2.0.80:2380]
2018/06/29 10:25:22.410 log.go:86: [info] embed: [pprof is enabled under /debug/pprof]
2018/06/29 10:25:22.410 log.go:86: [info] embed: [listening for client requests on  10.2.0.80:2379]
2018/06/29 10:25:22.411 log.go:86: [info] etcdserver: [name = pd4]
2018/06/29 10:25:22.411 log.go:86: [info] etcdserver: [data dir = /home/tidb/deploy/data.pd]
2018/06/29 10:25:22.411 log.go:86: [info] etcdserver: [member dir = /home/tidb/deploy/data.pd/member]
2018/06/29 10:25:22.411 log.go:86: [info] etcdserver: [heartbeat = 500ms]
2018/06/29 10:25:22.411 log.go:86: [info] etcdserver: [election = 3000ms]
2018/06/29 10:25:22.411 log.go:86: [info] etcdserver: [snapshot count = 100000]
2018/06/29 10:25:22.411 log.go:86: [info] etcdserver: [advertise client URLs = http://10.2.0.80:2379]
2018/06/29 10:25:22.442 log.go:86: [info] etcdserver: [restarting member 218fd48e60c9a5a9 in cluster 3470151827867e83 at commit index 16362]
2018/06/29 10:25:22.444 log.go:86: [info] raft: [218fd48e60c9a5a9 became follower at term 5]
2018/06/29 10:25:22.444 log.go:86: [info] raft: [newRaft 218fd48e60c9a5a9 [peers: [], term: 5, commit: 16362, applied: 0, lastindex: 16362, lastterm: 5]]
2018/06/29 10:25:22.447 log.go:86: [info] mvcc: [restore compact to 14449]
2018/06/29 10:25:22.448 log.go:82: [warning] auth: [simple token is not cryptographically signed]
2018/06/29 10:25:22.450 log.go:86: [info] etcdserver: [starting server... [version: 3.2.18, cluster version: to_be_decided]]
2018/06/29 10:25:22.451 log.go:86: [info] etcdserver/membership: [added member 218fd48e60c9a5a9 [http://10.2.0.80:2380] to cluster 3470151827867e83]
2018/06/29 10:25:22.451 log.go:84: [info] etcdserver/membership: [set the initial cluster version to 3.2]
2018/06/29 10:25:22.451 log.go:86: [info] etcdserver/api: [enabled capabilities for version 3.2]
2018/06/29 10:25:25.944 log.go:86: [info] raft: [218fd48e60c9a5a9 is starting a new election at term 5]
2018/06/29 10:25:25.944 log.go:86: [info] raft: [218fd48e60c9a5a9 became candidate at term 6]
2018/06/29 10:25:25.944 log.go:86: [info] raft: [218fd48e60c9a5a9 received MsgVoteResp from 218fd48e60c9a5a9 at term 6]
2018/06/29 10:25:25.945 log.go:86: [info] raft: [218fd48e60c9a5a9 became leader at term 6]
2018/06/29 10:25:25.945 log.go:86: [info] raft: [raft.node: 218fd48e60c9a5a9 elected leader 218fd48e60c9a5a9 at term 6]
2018/06/29 10:25:25.945 server.go:156: [info] create etcd v3 client with endpoints [http://10.2.0.80:2379]
2018/06/29 10:25:25.945 log.go:86: [info] embed: [ready to serve client requests]
2018/06/29 10:25:25.945 log.go:86: [info] etcdserver: [published {Name:pd4 ClientURLs:[http://10.2.0.80:2379]} to cluster 3470151827867e83]
2018/06/29 10:25:25.945 log.go:84: [info] embed: [serving insecure client requests on 10.2.0.80:2379, this is strongly discouraged!]
2018/06/29 10:25:25.947 server.go:195: [info] init cluster id 6572108125319783302
2018/06/29 10:25:25.947 namespace_classifier.go:424: [info] load 0 namespacesInfo cost 342.475µs
2018/06/29 10:25:25.948 leader.go:88: [warning] leader is still name:"pd4" member_id:2418385232895518121 peer_urls:"http://10.2.0.80:2380" client_urls:"http://10.2.0.80:2379" , delete and campaign again
2018/06/29 10:25:25.951 tso.go:104: [info] sync and save timestamp: last 2018-06-29 10:18:00.951460631 +0800 CST save 2018-06-29 10:25:28.95107827 +0800 CST m=+6.553047641
2018/06/29 10:25:25.951 leader.go:269: [info] PD cluster leader pd4 is ready to serve
2018/06/29 11:25:22.452 log.go:84: [info] compactor: [Starting auto-compaction at revision 16335]
2018/06/29 11:25:22.454 log.go:86: [info] mvcc: [store.index: compact 16335]
2018/06/29 11:25:22.454 log.go:84: [info] compactor: [Finished auto-compaction at revision 16335]
2018/06/29 11:25:22.456 log.go:86: [info] mvcc: [finished scheduled compaction at 16335 (took 1.642787ms)]
(END)

**Comment by nickzhao0617** [comment] 2018-06-29 04:00
@jackysp 
i use pd-ctl  -u "http://10.2.0.80:2379" -d member, it shows that 
{
      "member_id": 17812497649348567289,
      "peer_urls": [
        "http://10.2.0.75:2380"
      ]
    }
which i have deleted, i think it show up when i delete member name pd1 and use the old pd1 to join back. and now it becomes this, i don't know how to delete it?

**Comment by jackysp** [comment] 2018-06-29 04:33
I'll find a pd expert to handle this. @disksing

**Comment by disksing** [comment] 2018-06-29 06:08
Through the log I figured that there was some left over data at the start of pd4. Currently we only support joining brand new pd instance. You can try again by following these steps:
- close pd4
- rm -rf /home/tidb/deploy/data.pd
- start pd4 again by joining (join="http://10.2.0.76:2379", initial-cluster="")

**Comment by nickzhao0617** [comment] 2018-06-29 07:36
@disksing 
i reinstall the system and use the ansible way to deploy pd4 node again, and add configuration you wrote into run_pd.sh, but now i can't up the pd4. Even i use the way above.
here below is the log information:
/home/jenkins/workspace/build_pd_2.0/go/src/github.com/pingcap/pd/pkg/etcdutil/etcdutil.go:82: 
/home/jenkins/workspace/build_pd_2.0/go/src/github.com/pingcap/pd/server/join.go:119: 
2018/06/29 15:23:52.739 util.go:62: [info] Welcome to Placement Driver (PD).
2018/06/29 15:23:52.739 util.go:63: [info] Release Version: v2.0.4
2018/06/29 15:23:52.739 util.go:64: [info] Git Commit Hash: b6f9f8aeb0a5a23494204509e2bb5ce5132b715f
2018/06/29 15:23:52.739 util.go:65: [info] Git Branch: release-2.0
2018/06/29 15:23:52.739 util.go:66: [info] UTC Build Time:  2018-06-15 10:06:52
2018/06/29 15:23:52.739 metricutil.go:87: [info] start Prometheus push client
2018/06/29 15:23:52.742 main.go:73: [fatal] join error etcdserver: re-configuration failed due to not enough started members

**Comment by disksing** [comment] 2018-06-29 09:56
Hi, the join fails because not enough members are started. Please try the following steps:

1. make sure `pd2` and `pd3` are both started. If not, start them then run `pd4` again.
2. use `pd-ctl` to connect one of `pd2` or `pd3` to check current member list of the cluster.
3. If there are any extra member other than `pd2` and `pd3` in the list, use `pd-ctl` to remove it from the cluster. (you may want to use `member delete id {member_id}` in case the member has no name)
4. After removing extra members, the cluster should contain 2 members (`pd2` and `pd3`). Then it should be ok to join `pd4`.

If anything goes wrong or unexpected result occurs, please upload logs of `pd2` and `pd3` for my further analysis.

**Comment by nickzhao0617** [comment] 2018-07-01 09:51
@disksing 
I have tried your way, but it still failed. 
from pd2 log:
2018/07/01 17:40:29.127 log.go:82: [warning] etcdserver: [cannot get the version of member 45f01449b8c2103f (Get http://10.2.0.80:2380/version: dial tcp 10.2.0.80:2380: connect: connection refused)]
i found that the member id is different with i using pd-ctl showed out 
here below is pd-ctl imformation
 "members": [
    {
      "member_id": 5039550289892479039,
      "peer_urls": [
        "http://10.2.0.80:2380"
      ]
    },
10.2.0.80 is the pd4, pd2: 10.2.0.76  pd3: 10.2.0.77
ps: ' --join="http://10.2.0.76:2379", --initial-cluster="" '  it can't be used in run_pd.sh file so i use official way, and also rm -rf "data.pd" directory and then rejoin the cluster, here above is log message

**Comment by disksing** [comment] 2018-07-02 02:16
hi @nickzhao0617 , have you tried the step3? what's the output of member list when query pd2 or pd3?

**Comment by nickzhao0617** [comment] 2018-07-02 02:39
@disksing 
yes, i have tried, at beginning there is pd1's id in it. I delete it and join the cluster but it still like this, no name show up. the member_id is different from pd2 logs.

**Comment by disksing** [comment] 2018-07-02 02:54
That is strange. Could you please upload all 3 PDs' log?

**Comment by nickzhao0617** [comment] 2018-07-02 03:04
@disksing 
here is pd2, pd3, pd4 logs
[pd3.log.tar.gz](https://github.com/pingcap/tidb/files/2153608/pd3.log.tar.gz)
[pd2.log.tar.gz](https://github.com/pingcap/tidb/files/2153610/pd2.log.tar.gz)
[pd4.log.tar.gz](https://github.com/pingcap/tidb/files/2153614/pd4.log.tar.gz)

**Comment by disksing** [comment] 2018-07-02 03:45
Sorry, it should be `member delete id {id}` instead of `member remove id {id}`.

**Comment by nickzhao0617** [comment] 2018-07-02 03:59
@disksing 
i really have done step3 
{
  "header": {
    "cluster_id": 6558044075533226173
  },
  "members": [
    {
      "name": "pd2",
      "member_id": 5548575893049222968,
      "peer_urls": [
        "http://10.2.0.76:2380"
      ],
      "client_urls": [
        "http://10.2.0.76:2379"
      ]
    },
    {
      "name": "pd3",
      "member_id": 11429733937335431440,
      "peer_urls": [
        "http://10.2.0.77:2380"
      ],
      "client_urls": [
        "http://10.2.0.77:2379"
      ]
    }
  ],
  "leader": {
    "name": "pd2",
    "member_id": 5548575893049222968,
    "peer_urls": [
      "http://10.2.0.76:2380"
    ],
    "client_urls": [
      "http://10.2.0.76:2379"
    ]
  },
  "etcd_leader": {
    "name": "pd2",
    "member_id": 5548575893049222968,
    "peer_urls": [
      "http://10.2.0.76:2380"
    ],
    "client_urls": [
      "http://10.2.0.76:2379"
    ]
  }
}

2018/07/02 11:48:42.805 log.go:86: [info] etcdserver/membership: [removed member 45f01449b8c2103f from cluster 7cfe09f846e2fdf7]

here above is what i have done. and pd2 log.
here below is my operation:
1.  rm -rf data.pd/member
2. ./start_pd.sh
3. use pd-ctl check:
{
  "header": {
    "cluster_id": 6558044075533226173
  },
  "members": [
    {
      "name": "pd2",
      "member_id": 5548575893049222968,
      "peer_urls": [
        "http://10.2.0.76:2380"
      ],
      "client_urls": [
        "http://10.2.0.76:2379"
      ]
    },
    {
      "name": "pd3",
      "member_id": 11429733937335431440,
      "peer_urls": [
        "http://10.2.0.77:2380"
      ],
      "client_urls": [
        "http://10.2.0.77:2379"
      ]
    },
    {
      "member_id": 17351346217827913985,
      "peer_urls": [
        "http://10.2.0.80:2380"
      ]
    }
  ],
  "leader": {
    "name": "pd2",
    "member_id": 5548575893049222968,
    "peer_urls": [
      "http://10.2.0.76:2380"
    ],
    "client_urls": [
      "http://10.2.0.76:2379"
    ]
  },
  "etcd_leader": {
    "name": "pd2",
    "member_id": 5548575893049222968,
    "peer_urls": [
      "http://10.2.0.76:2380"
    ],
    "client_urls": [
      "http://10.2.0.76:2379"
    ]
  }
}
the log message is the same with i had sent to you.

**Comment by disksing** [comment] 2018-07-02 05:50
Oh, I've noticed that `pd4` is using an earlier version than `pd2` and `pd3`. They are using the different version of _etcd_. I'll check if I can reproduce the problem. Could you change `pd4` to the same version as `pd2` and `pd3` to try again?

**Comment by disksing** [comment] 2018-07-02 06:37
I can also reproduce it locally, it is really caused by the incompatibility of the etcd version, related logs:
```
2018/06/30 19:17:59.002 log.go:82: [warning] etcdserver: [The running cluster version(3.3.0) is higher than the maximum cluster version(3.2.0) supported]
2018/06/30 19:17:59.008 main.go:92: [fatal] run server failed: incompatible with current running cluster
```

**Comment by nickzhao0617** [comment] 2018-07-02 06:44
@disksing 
i have re-downloaded  tidb 2.0.0 version and rollbacked pd4, but it still can't join the cluster
here below is my operation:
1. member delete id <pd4_member_id>
2. rm -rf /home/tidb/deploy
3. edit inventory.ini file to change the version
4. ansible-playbook local_prepare.yml
5. ansible-playbook bootstrap.yml -l 10.2.0.80
6. ansible-playbook deploy.yml -l 10.2.0.80
7. edit(--join="http://10.2.0.76:2379") run_pd.sh file
8. ./start_pd.sh
but it still error
pd4 log:
```
2018/07/02 14:21:51.765 log.go:80: [error] rafthttp: [request sent was ignored (cluster ID mismatch: peer[4d0080608a7ea738]=7cfe09f846e2fdf7, local=bb223dc95d99d4c0)]
2018/07/02 14:21:51.765 log.go:80: [error] rafthttp: [request sent was ignored (cluster ID mismatch: peer[9e9e92756c1af110]=7cfe09f846e2fdf7, local=bb223dc95d99d4c0)]  
```

pd2 log:
```
2018/07/02 14:39:20.837 log.go:80: [error] rafthttp: [request cluster ID mismatch (got bb223dc95d99d4c0 want 7cfe09f846e2fdf7)]
```
ps: i just remove the deploy directory instead of reinstall the system.

**Comment by disksing** [comment] 2018-07-02 08:00
Your pd2 and pd3 are built from master branch which contains a higher version of etcd. You can use either the master version or v2.1.beta to start pd4. v2.0.0 is too old.

**Comment by nickzhao0617** [comment] 2018-07-02 08:38
Thank you, 
     it‘s successful, but how can i check the version of pd, cause when i use v2.1.beta, ansible can't download the version, so i use the "latest" version to download it，therefor i don't know what the version is
ps: i just install the pd4. unchanged other components.

**Comment by disksing** [comment] 2018-07-04 03:41
I'm closing the issue. If there any more question feel free to reopen it.

**Closed by disksing** 2018-07-04 03:41 UTC
Labels: component/tools, question
