### ISSUE TITLE
should rewrite the ddl_query in binlog if split the ddl_query into multi ddl job

### ISSUE THREAD

**Issue by july2993** [pingcap/tidb#11410] opened 2019-07-24 06:06 UTC
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
create table a(id int);
create table b(id int);
drop table a,b;

2. What did you expect to see?
receive two ddl binlog, one is `drop table a`, one is `drop table b`

3. What did you see instead?
receive two ddl binlog, both ddl_query is `drop table a, b`

in https://github.com/pingcap/tidb/blob/f8912049f52e94d2ec09001395f7f491630d5c29/executor/ddl.go#L247
it will run one ddl job for one table, but the ddl_query is the origin query `drop table a,b`

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
```
| Release Version: v3.0.0-rc.1-339-g368119b8d
Git Commit Hash: 368119b8df10d65a7575a90de8d77def660ac5ca
Git Branch: master
UTC Build Time: 2019-07-19 07:22:03
GoVersion: go version go1.12.5 darwin/amd64
Race Enabled: false
TiKV Min Version: 2.1.0-alpha.1-ff3dd160846b7d1aed9079c389fc188f7f5ea13e
Check Table Before Drop: false |
```

**Comment by bb7133** [comment] 2020-08-27 07:16
Confirmed that this issue doesn't lead to an incorrect result, we'll try to make `drop tables` atomic, as what is changed in MySQL 8(https://dev.mysql.com/doc/refman/8.0/en/atomic-ddl.html)

**Comment by wjhuang2016** [comment] 2020-12-01 11:17
@july2993  Because it doesn't lead to an incorrect result, we don't have a plan to fix this issue. Can we mark it as won't fix and close?

**Comment by jebter** [comment] 2024-07-04 02:41
"Starting from TiDB v7.5.0, technical support for the data replication feature of TiDB Binlog is no longer provided. It is strongly recommended to use [TiCDC](https://docs.pingcap.com/tidb/dev/ticdc-overview) as an alternative solution for data replication." refer:https://docs.pingcap.com/tidb/dev/tidb-binlog-overview
The issue has not been updated for too long, so I will close it. If there are any updates, you can reopen it.

**Closed by jebter** 2024-07-04 02:41 UTC
Labels: type/bug, component/tools, component/binlog, sig/sql-infra, severity/minor
