### ISSUE TITLE
"SELECT * FROM tbl IN (subquery)" leads to full table scan

### ISSUE THREAD

**Issue by Dieken** [pingcap/tidb#21121] opened 2020-11-18 04:34 UTC
## Performance Questions

- What version of TiDB are you using?

v4.0.8

- What's the observed and your expected performance respectively?

TiDB does full table scan:
```
CREATE TABLE transaction (id BIGINT PRIMARY KEY, account_id BIGINT NOT NULL, sku BIGINT NOT NULL, INDEX (account_id));

CREATE TABLE account (id BIGINT PRIMARY KEY, name VARCHAR(200) NOT NULL);

MySQL [test]> EXPLAIN SELECT * FROM transaction WHERE account_id IN (SELECT account_id FROM transaction WHERE account_id < 1000);
+-------------------------------+----------+-----------+-------------------------------------------------+----------------------------------------------------------------------------------------------------------------+
| id                            | estRows  | task      | access object                                   | operator info                                                                                                  |
+-------------------------------+----------+-----------+-------------------------------------------------+----------------------------------------------------------------------------------------------------------------+
| HashJoin_19                   | 3323.33  | root      |                                                 | inner join, equal:[eq(test.transaction.account_id, test.transaction.account_id)]                               |
| ├─HashAgg_32(Build)           | 2658.67  | root      |                                                 | group by:test.transaction.account_id, funcs:firstrow(test.transaction.account_id)->test.transaction.account_id |
| │ └─IndexReader_39            | 3323.33  | root      |                                                 | index:IndexRangeScan_38                                                                                        |
| │   └─IndexRangeScan_38       | 3323.33  | cop[tikv] | table:transaction, index:account_id(account_id) | range:[-inf,1000), keep order:false, stats:pseudo                                                              |
| └─TableReader_43(Probe)       | 10000.00 | root      |                                                 | data:TableFullScan_42                                                                                          |
|   └─TableFullScan_42          | 10000.00 | cop[tikv] | table:transaction                               | keep order:false, stats:pseudo                                                                                 |
+-------------------------------+----------+-----------+-------------------------------------------------+----------------------------------------------------------------------------------------------------------------+

MySQL [test]> EXPLAIN SELECT * FROM transaction WHERE account_id IN (SELECT id FROM account WHERE id < 1000);
+-----------------------------+----------+-----------+-------------------+----------------------------------------------------------------------+
| id                          | estRows  | task      | access object     | operator info                                                        |
+-----------------------------+----------+-----------+-------------------+----------------------------------------------------------------------+
| HashJoin_26                 | 1250.00  | root      |                   | inner join, equal:[eq(test.account.id, test.transaction.account_id)] |
| ├─TableReader_33(Build)     | 3333.33  | root      |                   | data:TableRangeScan_32                                               |
| │ └─TableRangeScan_32       | 3333.33  | cop[tikv] | table:account     | range:[-inf,1000), keep order:false, stats:pseudo                    |
| └─TableReader_35(Probe)     | 10000.00 | root      |                   | data:TableFullScan_34                                                |
|   └─TableFullScan_34        | 10000.00 | cop[tikv] | table:transaction | keep order:false, stats:pseudo                                       |
+-----------------------------+----------+-----------+-------------------+----------------------------------------------------------------------+
```

MariaDB 10.5.6:
```
MariaDB [test]> EXPLAIN SELECT * FROM transaction WHERE account_id IN (SELECT account_id FROM transaction WHERE account_id < 1000);
+------+--------------+-------------+--------+---------------+--------------+---------+------+------+--------------------------+
| id   | select_type  | table       | type   | possible_keys | key          | key_len | ref  | rows | Extra                    |
+------+--------------+-------------+--------+---------------+--------------+---------+------+------+--------------------------+
|    1 | PRIMARY      | transaction | range  | account_id    | account_id   | 8       | NULL | 1    | Using index condition    |
|    1 | PRIMARY      | <subquery2> | eq_ref | distinct_key  | distinct_key | 8       | func | 1    |                          |
|    2 | MATERIALIZED | transaction | range  | account_id    | account_id   | 8       | NULL | 1    | Using where; Using index |
+------+--------------+-------------+--------+---------------+--------------+---------+------+------+--------------------------+
3 rows in set (0.004 sec)

MariaDB [test]> EXPLAIN SELECT * FROM transaction WHERE account_id IN (SELECT id FROM account WHERE id < 1000);
+------+-------------+-------------+--------+---------------+------------+---------+-----------------------------+------+-----------------------+
| id   | select_type | table       | type   | possible_keys | key        | key_len | ref                         | rows | Extra                 |
+------+-------------+-------------+--------+---------------+------------+---------+-----------------------------+------+-----------------------+
|    1 | PRIMARY     | transaction | range  | account_id    | account_id | 8       | NULL                        | 1    | Using index condition |
|    1 | PRIMARY     | account     | eq_ref | PRIMARY       | PRIMARY    | 8       | test.transaction.account_id | 1    | Using index           |
+------+-------------+-------------+--------+---------------+------------+---------+-----------------------------+------+-----------------------+
2 rows in set (0.001 sec)
```

- Have you compared TiDB with other databases? If yes, what's their difference?

TiDB should do the sub query first, then push down the IN clause to TiKV for a range query.

**Comment by nullnotnil** [comment] 2020-11-18 06:26
I can reproduce this issue against master initially, but if I run `ANALYZE TABLE` it corrects itself. Here is a testcase with some sample data to illustrate further:

```sql
DROP TABLE IF EXISTS account, transaction;
CREATE TABLE account (id BIGINT PRIMARY KEY auto_increment, name VARCHAR(200) NOT NULL);
CREATE TABLE transaction (id BIGINT PRIMARY KEY auto_increment, account_id BIGINT NOT NULL, sku BIGINT NOT NULL, INDEX (account_id));

INSERT INTO account SELECT NULL, HEX(RANDOM_BYTES(100)) FROM dual;
INSERT INTO account SELECT NULL, HEX(RANDOM_BYTES(100)) FROM account a JOIN account b JOIN account c;
INSERT INTO account SELECT NULL, HEX(RANDOM_BYTES(100)) FROM account a JOIN account b JOIN account c;
INSERT INTO account SELECT NULL, HEX(RANDOM_BYTES(100)) FROM account a JOIN account b JOIN account c;
INSERT INTO account SELECT NULL, HEX(RANDOM_BYTES(100)) FROM account a JOIN account b JOIN account c;

INSERT INTO transaction SELECT NULL, id, 1234 FROM account;

EXPLAIN SELECT * FROM transaction WHERE account_id IN (SELECT account_id FROM transaction WHERE account_id < 10);
EXPLAIN SELECT * FROM transaction WHERE account_id IN (SELECT id FROM account WHERE id < 10);

SELECT SLEEP(1);
ANALYZE TABLE transaction, account;

EXPLAIN SELECT * FROM transaction WHERE account_id IN (SELECT account_id FROM transaction WHERE account_id < 10);
EXPLAIN SELECT * FROM transaction WHERE account_id IN (SELECT id FROM account WHERE id < 10);
..

mysql> EXPLAIN SELECT * FROM transaction WHERE account_id IN (SELECT account_id FROM transaction WHERE account_id < 10);
+-------------------------------+----------+-----------+-------------------------------------------------+----------------------------------------------------------------------------------------------------------------+
| id                            | estRows  | task      | access object                                   | operator info                                                                                                  |
+-------------------------------+----------+-----------+-------------------------------------------------+----------------------------------------------------------------------------------------------------------------+
| HashJoin_24                   | 3323.33  | root      |                                                 | inner join, equal:[eq(test.transaction.account_id, test.transaction.account_id)]                               |
| ├─HashAgg_37(Build)           | 2658.67  | root      |                                                 | group by:test.transaction.account_id, funcs:firstrow(test.transaction.account_id)->test.transaction.account_id |
| │ └─IndexReader_44            | 3323.33  | root      |                                                 | index:IndexRangeScan_43                                                                                        |
| │   └─IndexRangeScan_43       | 3323.33  | cop[tikv] | table:transaction, index:account_id(account_id) | range:[-inf,10), keep order:false, stats:pseudo                                                                |
| └─TableReader_48(Probe)       | 10000.00 | root      |                                                 | data:TableFullScan_47                                                                                          |
|   └─TableFullScan_47          | 10000.00 | cop[tikv] | table:transaction                               | keep order:false, stats:pseudo                                                                                 |
+-------------------------------+----------+-----------+-------------------------------------------------+----------------------------------------------------------------------------------------------------------------+
6 rows in set (0.00 sec)

mysql> EXPLAIN SELECT * FROM transaction WHERE account_id IN (SELECT id FROM account WHERE id < 10);
+-----------------------------+----------+-----------+-------------------+----------------------------------------------------------------------+
| id                          | estRows  | task      | access object     | operator info                                                        |
+-----------------------------+----------+-----------+-------------------+----------------------------------------------------------------------+
| HashJoin_36                 | 12.50    | root      |                   | inner join, equal:[eq(test.account.id, test.transaction.account_id)] |
| ├─TableReader_43(Build)     | 3333.33  | root      |                   | data:TableRangeScan_42                                               |
| │ └─TableRangeScan_42       | 3333.33  | cop[tikv] | table:account     | range:[-inf,10), keep order:false, stats:pseudo                      |
| └─TableReader_45(Probe)     | 10000.00 | root      |                   | data:TableFullScan_44                                                |
|   └─TableFullScan_44        | 10000.00 | cop[tikv] | table:transaction | keep order:false, stats:pseudo                                       |
+-----------------------------+----------+-----------+-------------------+----------------------------------------------------------------------+
5 rows in set (0.00 sec)

mysql> 
mysql> SELECT SLEEP(1);
+----------+
| SLEEP(1) |
+----------+
|        0 |
+----------+
1 row in set (1.00 sec)

mysql> ANALYZE TABLE transaction, account;
Query OK, 0 rows affected (3.26 sec)

mysql> 
mysql> EXPLAIN SELECT * FROM transaction WHERE account_id IN (SELECT account_id FROM transaction WHERE account_id < 10);
+----------------------------------+---------+-----------+-------------------------------------------------+----------------------------------------------------------------------------------------------------------------+
| id                               | estRows | task      | access object                                   | operator info                                                                                                  |
+----------------------------------+---------+-----------+-------------------------------------------------+----------------------------------------------------------------------------------------------------------------+
| IndexMergeJoin_22                | 9.00    | root      |                                                 | inner join, inner:IndexLookUp_20, outer key:test.transaction.account_id, inner key:test.transaction.account_id |
| ├─StreamAgg_39(Build)            | 9.00    | root      |                                                 | group by:test.transaction.account_id, funcs:firstrow(test.transaction.account_id)->test.transaction.account_id |
| │ └─IndexReader_31               | 9.00    | root      |                                                 | index:IndexRangeScan_30                                                                                        |
| │   └─IndexRangeScan_30          | 9.00    | cop[tikv] | table:transaction, index:account_id(account_id) | range:[-inf,10), keep order:true                                                                               |
| └─IndexLookUp_20(Probe)          | 1.00    | root      |                                                 |                                                                                                                |
|   ├─IndexRangeScan_18(Build)     | 1.00    | cop[tikv] | table:transaction, index:account_id(account_id) | range: decided by [eq(test.transaction.account_id, test.transaction.account_id)], keep order:true              |
|   └─TableRowIDScan_19(Probe)     | 1.00    | cop[tikv] | table:transaction                               | keep order:false                                                                                               |
+----------------------------------+---------+-----------+-------------------------------------------------+----------------------------------------------------------------------------------------------------------------+
7 rows in set (0.00 sec)

mysql> EXPLAIN SELECT * FROM transaction WHERE account_id IN (SELECT id FROM account WHERE id < 10);
+----------------------------------+---------+-----------+-------------------------------------------------+----------------------------------------------------------------------------------------------------+
| id                               | estRows | task      | access object                                   | operator info                                                                                      |
+----------------------------------+---------+-----------+-------------------------------------------------+----------------------------------------------------------------------------------------------------+
| IndexMergeJoin_23                | 9.00    | root      |                                                 | inner join, inner:IndexLookUp_21, outer key:test.account.id, inner key:test.transaction.account_id |
| ├─TableReader_43(Build)          | 9.00    | root      |                                                 | data:TableRangeScan_42                                                                             |
| │ └─TableRangeScan_42            | 9.00    | cop[tikv] | table:account                                   | range:[-inf,10), keep order:false                                                                  |
| └─IndexLookUp_21(Probe)          | 1.00    | root      |                                                 |                                                                                                    |
|   ├─IndexRangeScan_19(Build)     | 1.00    | cop[tikv] | table:transaction, index:account_id(account_id) | range: decided by [eq(test.transaction.account_id, test.account.id)], keep order:true              |
|   └─TableRowIDScan_20(Probe)     | 1.00    | cop[tikv] | table:transaction                               | keep order:false                                                                                   |
+----------------------------------+---------+-----------+-------------------------------------------------+----------------------------------------------------------------------------------------------------+
6 rows in set (0.00 sec)

mysql> select tidb_version()\G
*************************** 1. row ***************************
tidb_version(): Release Version: v4.0.0-beta.2-1585-ga426a0e5f
Edition: Community
Git Commit Hash: a426a0e5ff45300bed9b7e569d2004c3401ec401
Git Branch: master
UTC Build Time: 2020-11-17 10:37:06
GoVersion: go1.13
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
1 row in set (0.00 sec)
```

So it looks to be a statistics issue. MySQL and MariaDB use some strange tricks to actually execute some subqueries during planning, and will sometimes dive tables for statistics. It may be hard to achieve parity in all cases.

@Dieken do you mind checking if your plan changes after running `ANALYZE TABLE`?

**Comment by Dieken** [comment] 2020-11-18 08:45
I did 'ANALYZE TABLE' on our real tables in production environment,  it indeed helps but this is really annoying,  I can't frequently analyze table because it's toooooo slow even I set `tidb_enable_fast_analyze=1`.

Somebody tells me to use hint `tidb_inlj(transaction)`,  this works great, stable behaviour, no need for manual `analyze table`! 👍🏻️ 

But the hint still fails on another similar scenario when the join key has different type:

```sql
DROP TABLE IF EXISTS account, transaction;

-- account id is VARCHAR(32)
CREATE TABLE transaction (id BIGINT PRIMARY KEY auto_increment, account_id VARCHAR(32) NOT NULL, sku BIGINT NOT NULL, INDEX (account_id));

-- account id is BIGINT
CREATE TABLE account (id BIGINT PRIMARY KEY auto_increment, name VARCHAR(200) NOT NULL);

MySQL [test]> EXPLAIN SELECT /*+ tidb_inlj(transaction) */ * FROM transaction WHERE account_id IN (SELECT id FROM account WHERE id < 1000);
+-------------------------------+---------+-----------+-------------------+------------------------------------------------------------------------------------------------------------------------------------+
| id                            | estRows | task      | access object     | operator info                                                                                                                      |
+-------------------------------+---------+-----------+-------------------+------------------------------------------------------------------------------------------------------------------------------------+
| HashJoin_11                   | 16.00   | root      |                   | semi join, equal:[eq(Column#6, Column#7)]                                                                                          |
| ├─Projection_15(Build)        | 20.00   | root      |                   | cast(test.account.id, double BINARY)->Column#7                                                                                     |
| │ └─TableReader_17            | 20.00   | root      |                   | data:TableRangeScan_16                                                                                                             |
| │   └─TableRangeScan_16       | 20.00   | cop[tikv] | table:account     | range:[-inf,1000), keep order:false                                                                                                |
| └─Projection_12(Probe)        | 20.00   | root      |                   | test.transaction.id, test.transaction.account_id, test.transaction.sku, cast(test.transaction.account_id, double BINARY)->Column#6 |
|   └─TableReader_14            | 20.00   | root      |                   | data:TableFullScan_13                                                                                                              |
|     └─TableFullScan_13        | 20.00   | cop[tikv] | table:transaction | keep order:false                                                                                                                   |
+-------------------------------+---------+-----------+-------------------+------------------------------------------------------------------------------------------------------------------------------------+
7 rows in set, 1 warning (0.001 sec)

MySQL [test]> show warnings;
+---------+------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Level   | Code | Message                                                                                                                                                                     |
+---------+------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Warning | 1815 | There are no matching table names for (transaction) in optimizer hint /*+ INL_JOIN(transaction) */ or /*+ TIDB_INLJ(transaction) */. Maybe you can use the table alias name |
+---------+------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.000 sec)

MySQL [test]> EXPLAIN SELECT /*+ tidb_inlj(transaction) */ * FROM transaction WHERE account_id IN (SELECT cast(id as char) FROM account WHERE id < 1000);
+-----------------------------------+---------+-----------+-------------------------------------------------+-----------------------------------------------------------------------------------------------+
| id                                | estRows | task      | access object                                   | operator info                                                                                 |
+-----------------------------------+---------+-----------+-------------------------------------------------+-----------------------------------------------------------------------------------------------+
| IndexJoin_13                      | 800.00  | root      |                                                 | inner join, inner:IndexLookUp_12, outer key:Column#6, inner key:test.transaction.account_id   |
| ├─HashAgg_23(Build)               | 640.00  | root      |                                                 | group by:Column#6, funcs:firstrow(Column#6)->Column#6                                         |
| │ └─Projection_24                 | 800.00  | root      |                                                 | cast(test.account.id, var_string(5))->Column#6                                                |
| │   └─TableReader_27              | 800.00  | root      |                                                 | data:Selection_26                                                                             |
| │     └─Selection_26              | 800.00  | cop[tikv] |                                                 | not(isnull(cast(test.account.id)))                                                            |
| │       └─TableRangeScan_25       | 3333.33 | cop[tikv] | table:account                                   | range:[-inf,1000), keep order:false, stats:pseudo                                             |
| └─IndexLookUp_12(Probe)           | 1.25    | root      |                                                 |                                                                                               |
|   ├─IndexRangeScan_10(Build)      | 1.25    | cop[tikv] | table:transaction, index:account_id(account_id) | range: decided by [eq(test.transaction.account_id, Column#6)], keep order:false, stats:pseudo |
|   └─TableRowIDScan_11(Probe)      | 1.25    | cop[tikv] | table:transaction                               | keep order:false, stats:pseudo                                                                |
+-----------------------------------+---------+-----------+-------------------------------------------------+-----------------------------------------------------------------------------------------------+
```

The last `EXPLAIN SELECT` shows the hint works if `id` is cast to `char`, I verified on both TiDB playground v4.0.1 and v4.0.8,  but this still doesn't work in our production environment (TiDB v4.0.1),  our production environment always show TableFullScan:

```
MySQL [ying99_fundtxn]> EXPLAIN SELECT /*+ tidb_inlj(fund_order) */ * FROM fund_order WHERE account_id IN (SELECT cast(id as char) FROM ying99_accounts.account3 WHERE id < 1000);
+---------------------------------+--------------+-----------+------------------+------------------------------------------------------------------------+
| id                              | estRows      | task      | access object    | operator info                                                          |
+---------------------------------+--------------+-----------+------------------+------------------------------------------------------------------------+
| HashJoin_9                      | xxxxxxxxx | root      |                  | semi join, equal:[eq(ying99_fundtxn.fund_order.account_id, Column#72)] |
| ├─Projection_19(Build)          | 4.34         | root      |                  | cast(ying99_accounts.account3.id, var_string(5))->Column#72            |
| │ └─TableReader_22              | 4.34         | root      |                  | data:Selection_21                                                      |
| │   └─Selection_21              | 4.34         | cop[tikv] |                  | not(isnull(cast(ying99_accounts.account3.id)))                         |
| │     └─TableRangeScan_20       | 5.42         | cop[tikv] | table:account3   | range:[-inf,1000), keep order:false                                    |
| └─TableReader_12(Probe)         | xxxxxxxxx | root      |                  | data:Selection_11                                                      |
|   └─Selection_11                | xxxxxxxxx | cop[tikv] |                  | not(isnull(ying99_fundtxn.fund_order.account_id))                      |
|     └─TableFullScan_10          | xxxxxxxxx | cop[tikv] | table:fund_order | keep order:false                                                       |
+---------------------------------+--------------+-----------+------------------+------------------------------------------------------------------------+
8 rows in set, 1 warning (0.052 sec)

MySQL [ying99_fundtxn]> show warnings;
+---------+------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Level   | Code | Message                                                                                                                                                                  |
+---------+------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Warning | 1815 | There are no matching table names for (fund_order) in optimizer hint /*+ INL_JOIN(fund_order) */ or /*+ TIDB_INLJ(fund_order) */. Maybe you can use the table alias name |
+---------+------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.051 sec)

```

**Comment by nullnotnil** [comment] 2020-11-18 15:08
@Dieken the index join hint is not working because the types do not match. See:

```sql
DROP TABLE IF EXISTS account, transaction;
CREATE TABLE account (id VARCHAR(32) NOT NULL PRIMARY KEY, name VARCHAR(200) NOT NULL);
CREATE TABLE transaction (id BIGINT PRIMARY KEY auto_increment, account_id VARCHAR(32) NOT NULL, sku BIGINT NOT NULL, INDEX (account_id));

INSERT INTO account SELECT MD5(RAND()), HEX(RANDOM_BYTES(100)) FROM dual;
INSERT INTO account SELECT MD5(RAND()), HEX(RANDOM_BYTES(100)) FROM account a JOIN account b JOIN account c;
INSERT INTO account SELECT MD5(RAND()), HEX(RANDOM_BYTES(100)) FROM account a JOIN account b JOIN account c;
INSERT INTO account SELECT MD5(RAND()), HEX(RANDOM_BYTES(100)) FROM account a JOIN account b JOIN account c;
INSERT INTO account SELECT MD5(RAND()), HEX(RANDOM_BYTES(100)) FROM account a JOIN account b JOIN account c;

INSERT INTO transaction SELECT NULL, id, 1234 FROM account;

SELECT SLEEP(1);
ANALYZE TABLE account, transaction;
..

mysql> EXPLAIN SELECT /*+ tidb_inlj(transaction) */ * FROM transaction WHERE account_id IN (SELECT id FROM account WHERE id < 1000);
+----------------------------------+---------+-----------+-------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------+
| id                               | estRows | task      | access object                                   | operator info                                                                                                                                                   |
+----------------------------------+---------+-----------+-------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------+
| IndexJoin_26                     | 808.00  | root      |                                                 | inner join, inner:IndexLookUp_25, outer key:test.account.id, inner key:test.transaction.account_id, equal cond:eq(test.account.id, test.transaction.account_id) |
| ├─TableReader_36(Build)          | 808.00  | root      |                                                 | data:Selection_35                                                                                                                                               |
| │ └─Selection_35                 | 808.00  | cop[tikv] |                                                 | lt(cast(test.account.id), 1000)                                                                                                                                 |
| │   └─TableFullScan_34           | 1010.00 | cop[tikv] | table:account                                   | keep order:false                                                                                                                                                |
| └─IndexLookUp_25(Probe)          | 1.00    | root      |                                                 |                                                                                                                                                                 |
|   ├─IndexRangeScan_23(Build)     | 1.00    | cop[tikv] | table:transaction, index:account_id(account_id) | range: decided by [eq(test.transaction.account_id, test.account.id)], keep order:false                                                                          |
|   └─TableRowIDScan_24(Probe)     | 1.00    | cop[tikv] | table:transaction                               | keep order:false                                                                                                                                                |
+----------------------------------+---------+-----------+-------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------+
7 rows in set (0.00 sec)
```

The cast method looks to not be working in master. I get the same result you have in your 4.0.1 production environment:

```sql
mysql> EXPLAIN SELECT /*+ tidb_inlj(transaction) */ * FROM transaction WHERE account_id IN (SELECT cast(id as char) FROM account WHERE id < 1000);
+---------------------------------+----------+-----------+-------------------+--------------------------------------------------------------+
| id                              | estRows  | task      | access object     | operator info                                                |
+---------------------------------+----------+-----------+-------------------+--------------------------------------------------------------+
| HashJoin_9                      | 8000.00  | root      |                   | semi join, equal:[eq(test.transaction.account_id, Column#6)] |
| ├─Projection_12(Build)          | 800.00   | root      |                   | cast(test.account.id, var_string(5))->Column#6               |
| │ └─TableReader_15              | 800.00   | root      |                   | data:Selection_14                                            |
| │   └─Selection_14              | 800.00   | cop[tikv] |                   | not(isnull(cast(test.account.id)))                           |
| │     └─TableRangeScan_13       | 3333.33  | cop[tikv] | table:account     | range:[-inf,1000), keep order:false, stats:pseudo            |
| └─TableReader_11(Probe)         | 10000.00 | root      |                   | data:TableFullScan_10                                        |
|   └─TableFullScan_10            | 10000.00 | cop[tikv] | table:transaction | keep order:false, stats:pseudo                               |
+---------------------------------+----------+-----------+-------------------+--------------------------------------------------------------+
7 rows in set, 1 warning (0.01 sec)

mysql> show warnings;
+---------+------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Level   | Code | Message                                                                                                                                                                     |
+---------+------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Warning | 1815 | There are no matching table names for (transaction) in optimizer hint /*+ INL_JOIN(transaction) */ or /*+ TIDB_INLJ(transaction) */. Maybe you can use the table alias name |
+---------+------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)
```

I think this is expected behavior - an index join really requires columns to be indexed, and the cast is preventing them from being directly compared.

**Comment by Dieken** [comment] 2020-11-19 06:26
@nullnotnil 

> the index join hint is not working because the types do not match. See:

Yes,  if `transaction.account_id` and `account.id` are both `BIGINT` or both `VARCHAR`, the hint works as expected.

> The cast method looks to not be working in master. I get the same result you have in your 4.0.1 production environment:

As I pasted in my last comment,  the hint works for `cast(id as char)` on my TiDB playground v4.0.1 and v4.0.8.

> I think this is expected behavior - an index join really requires columns to be indexed, and the cast is preventing them from being directly compared.

Both `account.id` and `transaction.account_id` are indexed, if I replace the `IN (subquery)` with `IN ('A', 'B')` the SQL execution plan doesn't have TableFullScan even without hint.

Let's summarize the scenarios,  I'm confused.

* Same data type:  the hint works as expected, no problem. Without hint, I understand table statistics isn't accurate, but still wonder why TiDB would rather choose probably slow TableFullScan instead of nested index loop.

* Different data type:
    * Without `cast`,  the hint doesn't work,  in previous comment(https://github.com/pingcap/tidb/issues/21121#issuecomment-729529148) , TiDB does cast(id as double binary) and hash join, I don't know how TiDB can cast `transaction.account_id VARCHAR(32)` to `double binary`,  isn't it easier to just cast `account.id BIGINT` to `VARCHAR`?

    * With `cast`
        * the schema described in this issue: the hint works for me (TiDB playground on macOS,  v4.0.1, v4.0.8),  but doesn't work for you (TiDB master)
        * the real schema in our production TiDB v4.0.1 cluster:  the hint doesn't work, still TableFullScan,  I copied the schema to my TiDB v4.0.1 playground on macOS, still doesn't work.  I have no idea what schema difference leads to different execution plan.

**Comment by winoros** [comment] 2020-11-19 06:38
Yeah, the given schema of @Dieken is worked well if i try it on master.
```
mysql> select tidb_version();
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| tidb_version()                                                                                                                                                                                                                                                                                                              |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Release Version: v4.0.0-beta.2-1592-g629ef0759
Edition: Community
Git Commit Hash: 629ef07597bd35586260003af298f97dd7f74cc7
Git Branch: master
UTC Build Time: 2020-11-19 05:40:52
GoVersion: go1.14.5
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)

mysql> EXPLAIN SELECT /*+ tidb_inlj(transaction) */ * FROM transaction WHERE account_id IN (SELECT id FROM account WHERE id < 1000);
+----------------------------------+---------+-----------+-------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------+
| id                               | estRows | task      | access object                                   | operator info                                                                                                                                                   |
+----------------------------------+---------+-----------+-------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------+
| IndexJoin_26                     | 1250.00 | root      |                                                 | inner join, inner:IndexLookUp_25, outer key:test.account.id, inner key:test.transaction.account_id, equal cond:eq(test.account.id, test.transaction.account_id) |
| ├─TableReader_35(Build)          | 3333.33 | root      |                                                 | data:TableRangeScan_34                                                                                                                                          |
| │ └─TableRangeScan_34            | 3333.33 | cop[tikv] | table:account                                   | range:[-inf,1000), keep order:false, stats:pseudo                                                                                                               |
| └─IndexLookUp_25(Probe)          | 1.25    | root      |                                                 |                                                                                                                                                                 |
|   ├─IndexRangeScan_23(Build)     | 1.25    | cop[tikv] | table:transaction, index:account_id(account_id) | range: decided by [eq(test.transaction.account_id, test.account.id)], keep order:false, stats:pseudo                                                            |
|   └─TableRowIDScan_24(Probe)     | 1.25    | cop[tikv] | table:transaction                               | keep order:false, stats:pseudo                                                                                                                                  |
+----------------------------------+---------+-----------+-------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------+
6 rows in set (0.00 sec)
```

And failed on 4.0.8

```
mysql> select tidb_version();
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| tidb_version()                                                                                                                                                                                                                                                                                                          |
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Release Version: v4.0.8-72-g9a4d55037
Edition: Community
Git Commit Hash: 9a4d550379d797e5480169b96f0eb3663dd49fe9
Git Branch: release-4.0
UTC Build Time: 2020-11-19 06:37:12
GoVersion: go1.14.5
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false |
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)

mysql> EXPLAIN SELECT /*+ tidb_inlj(transaction) */ * FROM transaction WHERE account_id IN (SELECT id FROM account WHERE id < 1000);
+-------------------------------+----------+-----------+-------------------+------------------------------------------------------------------------------------------------------------------------------------+
| id                            | estRows  | task      | access object     | operator info                                                                                                                      |
+-------------------------------+----------+-----------+-------------------+------------------------------------------------------------------------------------------------------------------------------------+
| HashJoin_11                   | 8000.00  | root      |                   | semi join, equal:[eq(Column#6, Column#7)]                                                                                          |
| ├─Projection_15(Build)        | 1000.00  | root      |                   | cast(test.account.id, double BINARY)->Column#7                                                                                     |
| │ └─TableReader_17            | 3333.33  | root      |                   | data:TableRangeScan_16                                                                                                             |
| │   └─TableRangeScan_16       | 3333.33  | cop[tikv] | table:account     | range:[-inf,1000), keep order:false, stats:pseudo                                                                                  |
| └─Projection_12(Probe)        | 10000.00 | root      |                   | test.transaction.id, test.transaction.account_id, test.transaction.sku, cast(test.transaction.account_id, double BINARY)->Column#6 |
|   └─TableReader_14            | 10000.00 | root      |                   | data:TableFullScan_13                                                                                                              |
|     └─TableFullScan_13        | 10000.00 | cop[tikv] | table:transaction | keep order:false, stats:pseudo                                                                                                     |
+-------------------------------+----------+-----------+-------------------+------------------------------------------------------------------------------------------------------------------------------------+
7 rows in set, 1 warning (0.00 sec)
```

**Comment by Dieken** [comment] 2020-11-19 06:49
> Yeah, the given schema of @Dieken is worked well if i try it on master.

For your record, @winoros verified case 2.1 in https://github.com/pingcap/tidb/issues/21121#issuecomment-730158842,  the hint in case 2.1 works on TiDB master, not work on TiDB 4.0.x.

**Comment by jebter** [comment] 2024-06-05 11:51
The issue has not been updated for too long, so I will close it. Please try the latest version. If there are any updates, you can reopen it.

**Closed by jebter** 2024-06-05 11:51 UTC
Labels: type/question, type/performance
