### ISSUE TITLE
UUID_SHORT() function-like supoort

### ISSUE THREAD

**Issue by vkingnew** [pingcap/tidb#9941] opened 2019-03-28 12:07 UTC
so far,as version 2.1.7,I don't find a function like MySQL's fuction UUID_SHORT(), which can auto generate incremental int values。
the following function just generate same serial:
>mysql> begin;
Query OK, 0 rows affected (0.00 sec)

>mysql> select @@tidb_current_ts;
+--------------------+
| @@tidb_current_ts  |
+--------------------+
| 407312734087282689 |
+--------------------+
1 row in set (0.00 sec)

>mysql> select @@tidb_current_ts;
+--------------------+
| @@tidb_current_ts  |
+--------------------+
| 407312734087282689 |
+--------------------+
1 row in set (0.00 sec)

any other functions like uuid_short()?

**Comment by shenli** [comment] 2019-03-28 15:46
@vkingnew Thanks for your feedback!
`uuid_short` is [still missing](https://github.com/pingcap/tidb/blob/master/expression/builtin_miscellaneous.go#L991). But I think this is not difficult to implement.

**Comment by morgo** [comment] 2019-03-29 03:01
This is a duplicate of https://github.com/pingcap/tidb/issues/4620

I actually think it is not trivial, because TiDB does not have a short `server_id`-like concept. We can not make this for the user to handle either, since `set global server_id=x` propagates to all nodes in the cluster.

**Comment by vkingnew** [comment] 2019-03-29 11:40
In deed TiDB no server-id parameters,so i ask “any other functions like uuid_short()?”，better to have a similar function 。

**Comment by morgo** [comment] 2019-03-30 13:30
@vkingnew `uuid_short` pseudo-guarantees uniqueness in a very small data type. I am not sure it is so useful if it requires a larger data type, or does not offer uniqueness.  Here is the formula that MySQL uses:
```
(server_id & 255) << 56 + (server_startup_time_in_seconds << 24)
```

**Comment by morgo** [comment] 2019-04-02 15:40
I am going to close this issue to reduce duplication with https://github.com/pingcap/tidb/issues/4620

Please feel free to re-open if you have any further questions.  Thanks!

**Closed by morgo** 2019-04-02 15:40 UTC
Labels: for new contributors, help wanted, question
