### ISSUE TITLE
tidb_enforce_mpp doesn't work as expected

### ISSUE THREAD

**Issue by hehechen** [pingcap/tidb#40528] opened 2023-01-12 05:32 UTC
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

> CREATE TABLE `sbtest1` (
  `id` bigint(20) NOT NULL,
  `k` bigint(20) NOT NULL DEFAULT '0',
  `c` char(120) NOT NULL DEFAULT '',
  `pad` varchar(4000) NOT NULL DEFAULT '',
  `create_date` date NOT NULL DEFAULT '2022-12-18',
  `aid` int(11) unsigned NOT NULL DEFAULT '0',
  `atime` time NOT NULL DEFAULT '01:00:00',
  `city` char(2) DEFAULT 'a',
  `w_id` int(11) NOT NULL DEFAULT '0',
  `w_name` varchar(10) DEFAULT 'a',
  `w_city` varchar(20) DEFAULT 'a',
  `w_year` year(4) DEFAULT '2022',
  `c_last` varchar(16) DEFAULT 'a',
  `c_street_1` varchar(20) DEFAULT 'a',
  `c_state` char(2) DEFAULT 'a',
  `c_zip` char(9) DEFAULT 'a',
  `c_phone` char(16) DEFAULT 'a',
  `c_credit` char(2) DEFAULT 'a',
  `c_credit_lim` decimal(12,2) DEFAULT '1.1',
  `c_discount` decimal(4,4) DEFAULT '0.2',
  `created` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`) /*T![clustered_index] CLUSTERED */,
  KEY `k_1` (`k`),
  KEY `aid_7` (`aid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin
PARTITION BY RANGE COLUMNS(`id`)
(PARTITION `p1` VALUES LESS THAN (500000000),
 PARTITION `p2` VALUES LESS THAN (1000000000),
 PARTITION `p3` VALUES LESS THAN (1500000000),
 PARTITION `p4` VALUES LESS THAN (2000000000),
 PARTITION `p5` VALUES LESS THAN (2500000000),
 PARTITION `p6` VALUES LESS THAN (3000000000),
 PARTITION `p7` VALUES LESS THAN (3500000000),
 PARTITION `p8` VALUES LESS THAN (4000000000),
 PARTITION `p9` VALUES LESS THAN (MAXVALUE))

 import 4 billion rows data.
1.set @@session.tidb_enforce_mpp=1;
2.explain select count(*) from sbtest1 where create_date='1997-12-18';

### 2. What did you expect to see? (Required)
Query plan choose MPP. 
### 3. What did you see instead (Required)
Query plan choose cop.
![img_v2_f9dcf74e-d4a1-4b35-b550-b3e979d09bag](https://user-images.githubusercontent.com/14118780/211985376-c7dbf0f2-bfff-4bf3-ac8c-01f437de645d.jpg)

### 4. What is your TiDB version? (Required)
v6.5.0  706c3fa3c526cdba5b3e9f066b1a568fb96c56e3

**Comment by chrysan** [comment] 2023-02-22 15:37
Similar with https://github.com/pingcap/tidb/issues/37459, @fixdb please help confirm if they can be merged to one.

**Comment by qw4990** [comment] 2024-04-29 07:58
Can't reproduce this, it might have been fixed by some PR:
```
mysql> set @@session.tidb_enforce_mpp=1;
Query OK, 0 rows affected (0.00 sec)

mysql> explain select count(*) from sbtest1 where create_date='1997-12-18';
+------------------------------+----------+--------------+---------------+-----------------------------------------------------------------------------------+
| id                           | estRows  | task         | access object | operator info                                                                     |
+------------------------------+----------+--------------+---------------+-----------------------------------------------------------------------------------+
| StreamAgg_13                 | 1.00     | root         |               | funcs:count(1)->Column#23                                                         |
| └─TableReader_42             | 10.00    | root         | partition:all | MppVersion: 2, data:ExchangeSender_41                                             |
|   └─ExchangeSender_41        | 10.00    | mpp[tiflash] |               | ExchangeType: PassThrough                                                         |
|     └─Selection_40           | 10.00    | mpp[tiflash] |               | eq(test.sbtest1.create_date, 1997-12-18 00:00:00.000000)                          |
|       └─TableFullScan_39     | 10000.00 | mpp[tiflash] | table:sbtest1 | pushed down filter:empty, keep order:false, stats:pseudo, PartitionTableScan:true |
+------------------------------+----------+--------------+---------------+-----------------------------------------------------------------------------------+
5 rows in set (0.00 sec)
```

**Closed by qw4990** 2024-04-29 07:58 UTC
Labels: type/bug, sig/planner, severity/major, may-affects-4.0, may-affects-5.1, may-affects-5.2, may-affects-5.3, may-affects-5.4, may-affects-5.0, may-affects-6.0, may-affects-6.1, may-affects-6.2, may-affects-6.3, may-affects-6.4, may-affects-6.5, affects-6.6, affects-7.0, affects-7.1, affects-7.5, affects-8.1
