### ISSUE TITLE
TestAllHistory failed in CI

### ISSUE THREAD

**Issue by fzhedu** [pingcap/tidb#30256] opened 2021-11-30 04:39 UTC
## Bug Report

Please answer these questions before submitting your issue. Thanks!
[2021-11-30T04:23:30.648Z] --- FAIL: TestAllHistory (1.19s)
[2021-11-30T04:23:30.648Z]     dbtestkit.go:72: 
[2021-11-30T04:23:30.648Z]         	Error Trace:	dbtestkit.go:72
[2021-11-30T04:23:30.648Z]         	            				http_handler_test.go:505
[2021-11-30T04:23:30.648Z]         	            				http_handler_test.go:965
[2021-11-30T04:23:30.648Z]         	Error:      	Received unexpected error:
[2021-11-30T04:23:30.648Z]         	            	commands out of sync. Did you run multiple statements at once?
[2021-11-30T04:23:30.648Z]         	Test:       	TestAllHistory
[2021-11-30T04:23:30.648Z]         	Messages:   	sql:create database tidb;, args:[]
[2021-11-30T04:23:30.648Z]     http_handler_test.go:501: 
[2021-11-30T04:23:30.648Z]         	Error Trace:	http_handler_test.go:501
[2021-11-30T04:23:30.648Z]         	            				panic.go:613
[2021-11-30T04:23:30.648Z]         	            				testing.go:741
[2021-11-30T04:23:30.648Z]         	            				dbtestkit.go:72
[2021-11-30T04:23:30.648Z]         	            				http_handler_test.go:505
[2021-11-30T04:23:30.648Z]         	            				http_handler_test.go:965
[2021-11-30T04:23:30.648Z]         	Error:      	Received unexpected error:
[2021-11-30T04:23:30.648Z]         	            	bad connection
[2021-11-30T04:23:30.648Z]         	Test:       	TestAllHistory

https://ci.pingcap.net/blue/rest/organizations/jenkins/pipelines/tidb_ghpr_check_2/runs/49084/nodes/62/steps/73/log/?start=0

### 4. What is your TiDB version? (Required)
master

**Comment by mjonss** [comment] 2021-12-01 12:05
Duplicate of https://github.com/pingcap/tidb/issues/30249 ?

**Comment by xiongjiwei** [comment] 2021-12-07 06:39
it seems the same error message with #30249 , I will assign it to you @tiancaiamao

**Comment by hawkingrei** [comment] 2021-12-07 07:03
Closed by #30306. We can re-open it if the error happens again.

**Closed by hawkingrei** 2021-12-07 07:03 UTC
Labels: type/bug, component/test, sig/sql-infra, severity/major
