### ISSUE TITLE
8200 Unsupported multi schema change 

### ISSUE THREAD

**Issue by heming79** [pingcap/tidb#21037] opened 2020-11-13 06:34 UTC
![image](https://user-images.githubusercontent.com/14069019/99036714-23869000-25bd-11eb-9108-15857e0565e5.png)
mysql can support  It  .

**Comment by AilinKid** [comment] 2020-11-13 06:48
we are on it, please focus on this issue: https://github.com/pingcap/tidb/issues/18283

**Comment by AilinKid** [comment] 2020-11-13 10:21
this issue is duplicated with https://github.com/pingcap/tidb/issues/14766, and it's under development now, if you are interested with this and wanna join into the work with us, please contact us~ thank you every much

**Comment by morgo** [comment] 2020-12-07 03:06
Closing as a duplicate of https://github.com/pingcap/tidb/issues/14766 , Thanks!

**Closed by morgo** 2020-12-07 03:06 UTC
Labels: sig/DDL, type/duplicate
