### ISSUE TITLE
TiKV from 4.0.10 upgrade to 5.1.4, TiDB Server encountered an error "tableWorker in IndexLookUpExecutor panicked"

### ISSUE THREAD

**Issue by yilongrong** [pingcap/tidb#38291] opened 2022-10-03 09:47 UTC
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

TiKV from 4.0.14 upgrade to 5.1.4, TiDB Server encountered an error "tableWorker in IndexLookUpExecutor panicked"

### 2. What did you expect to see? (Required)
TiDB server no error
### 3. What did you see instead (Required)

```
	// decode nullBitmap.
	if nullCount > 0 {
		numNullBitmapBytes := (col.length + 7) / 8
		col.nullBitmap = buffer[:numNullBitmapBytes:numNullBitmapBytes]
		buffer = buffer[numNullBitmapBytes:]
	} else {
		c.setAllNotNull(col)
	}
```

![image](https://user-images.githubusercontent.com/55389305/193548440-d42e4795-f98e-4cb2-af3c-f9dc415407e5.png)

### 4. What is your TiDB version? (Required)
v4.0.14,  v5.1.4

**Comment by zanmato1984** [comment] 2022-10-27 08:07
@ChenPeng2013 Could you reproduce the bug?

**Comment by XuHuaiyu** [comment] 2022-10-28 07:30
Discussed with @yilongrong offline, cannot reproduce it. And no error is reported after after the upgrade progress finished.

Close this issue.

**Closed by XuHuaiyu** 2022-10-28 07:30 UTC
Labels: type/bug, sig/execution, severity/critical, affects-5.1, may-affects-4.0, may-affects-5.2, may-affects-5.3, may-affects-5.4, may-affects-5.0, may-affects-6.0, may-affects-6.1, may-affects-6.2, may-affects-6.3
