### ISSUE TITLE
Write conflict when parallel insert into different tables with auto_increment key in the same database

### ISSUE THREAD

**Issue by jackysp** [pingcap/tidb#5622] opened 2018-01-11 09:23 UTC
Please answer these questions before submitting your issue. Thanks!

1. What did you do?

sysbench parallel prepare: 
table count: 200
table size: 20000
in database `test`

2. What did you expect to see?

prepare successful

3. What did you see instead?

* Txn(Mvcc(WriteConflict { start_ts: 397320469229338626, conflict_ts: 397320469229338627, key: [109, 68, 66, 58, 49, 48, 55, 0, 255, 0, 253, 0, 0, 0, 0, 0, 0, 255, 0, 72, 0, 0, 0, 0, 0, 0, 249]
* only some of tables complete insert 20000 rows.

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
Release Version: v1.1.0-alpha-409-gf4fa60d
Git Commit Hash: f4fa60d306a9cecd941cd6c3b5f0b491dfa4a55f
Git Commit Branch: master
UTC Build Time:  2018-01-11 03:40:51

**Comment by shenli** [comment] 2018-01-11 10:02
@cwen0 PTAL

**Comment by nullnotnil** [comment] 2020-07-10 16:06
Hi! I am going to close this issue due to staleness, but please feel free to re-open if you can still reproduce. Thanks!

**Closed by nullnotnil** 2020-07-10 16:06 UTC
Labels: type/bug
