### ISSUE TITLE
autoanalyze failed when a table has global index, analyze version = 1

### ISSUE THREAD

**Issue by L-maple** [pingcap/tidb#47539] opened 2023-10-11 06:21 UTC
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```SQL
set global tidb_analyze_version = 1;
use test;
CREATE TABLE t ( a int, b int, c int default 0)
  PARTITION BY RANGE (a) (
  PARTITION p0 VALUES LESS THAN (10),
  PARTITION p1 VALUES LESS THAN (20),
  PARTITION p2 VALUES LESS THAN (30),
  PARTITION p3 VALUES LESS THAN (40));
INSERT INTO t(a, b) values(1, 1), (2, 2), (3, 3), (15, 15), (25, 25), (35, 35);
ALTER TABLE t ADD UNIQUE INDEX idx(b);
set global tidb_partition_prune_mode = "dynamic";
```

### 2. What did you expect to see? (Required)
auto analyze run successfully.

### 3. What did you see instead (Required)
auto analyze run failed, global index should be handle specifically.
![image](https://github.com/pingcap/tidb/assets/20724552/90df643e-1da0-41b6-86a4-d02ae8b1b230)

### 4. What is your TiDB version? (Required)
<img width="560" alt="image" src="https://github.com/pingcap/tidb/assets/20724552/bbd41920-fc44-4b11-bf7e-868d9dbd2a21">

**Comment by Defined2014** [comment] 2024-06-25 08:30
Can't reproduce this issue right [now](https://github.com/pingcap/tidb/commit/b3ed8868027842b9d04a59711d190b25f0aea9f7), maybe fixed by re-implementation stats related codes.

**Closed** 2024-07-01 07:20 UTC
Labels: type/bug, sig/planner, severity/minor, feature/developing
