### ISSUE TITLE
Got interface conversion error when explain SQL

### ISSUE THREAD

**Issue by guo-shaoge** [pingcap/tidb#39257] opened 2022-11-20 11:50 UTC
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```
create table tbl_2 ( col_9 varchar ( 428 ) ,col_10 text ( 490 ) collate utf8mb4_bin  not null ,col_11 smallint  unsigned ,col_12 double   not null ,col_13 float    default 3220.839705208817 ,col_14 text ( 4 )   not null ,col_15 float ,col_16 varchar ( 383 ) collate utf8mb4_bin   default 'apC=1onK2m' ,col_17 varchar ( 88 )   not null default 'fP3+48_Uut2gYA$1yod' ) charset utf8mb4 collate utf8mb4_bin ;
create table tbl_5 ( col_35 varchar ( 457 ) ,col_36 char ( 69 )   not null default 'trD1piuCI!&bsaF8Q' ,col_37 bigint  unsigned not null default 3221620069009153834 ,col_38 varchar ( 255 )   not null default ')g!XFS' ,col_39 decimal ( 54 , 29 )   not  null ,col_40 char ( 112 ) collate utf8mb4_bin  not null default 'I_H4$oE$lbY@VkR#gU' ,col_41 char ( 26 ) collate utf8mb4_bin ) charset utf8mb4 collate utf8mb4_bin ;

 explain ( select    cume_dist() over w as r0 , rtrim( tbl_5.col_35 ) as r1 , tbl_5.col_35 as r2 , from_base64( tbl_5.col_40 ) as r3 , tbl_5.col_39 as r4 , quote( tbl_5.col_41 ) as r5 , rank() over w as r6 from tbl_5 where not( IsNull( tbl_5.col_37 )  )  window w as ( partition by col_37,col_35,col_36,col_39,col_38,col_41,col_40 order by col_41,col_39,col_36,col_38,col_37,col_40,col_35 rows between current row and 2 following ) order by r0,r1,r2,r3,r4,r5,r6  ) except ( select    tbl_2.col_14 as     r0 , bit_and( tbl_2.col_11 ) as r1 , var_samp( tbl_2.col_11 ) as r2 , cume_dist() over w as r3 , dense_rank() over w as r4 , unhex( tbl_2.col_9 ) as r5 , nth_value( tbl_2.col_16 , 6 ) over w as r6 from tbl_2 where tbl_2.col_13 = 211.55233091704656 and not( IsNull( tbl_2.col_16 ) ) group by tbl_2.col_11 window w as ( partition by col_17,col_12,col_10,col_14,col_9,col_15,col_13,col_11,col_16 order by col_11,col_9,col_15,col_10,col_12,col_16,col_14,col_13,col_17  ) order by r0,r1,r2,r3,r4,r5,r6 limit  16  ) order by 1 limit 965;
```

### 2. What did you expect to see? (Required)
no error
### 3. What did you see instead (Required)
got `interface conversion: expression.Expression is *expression.ScalarFunction, not *expression.Column`
### 4. What is your TiDB version? (Required)
```
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| tidb_version()
                                               |
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Release Version: v6.5.0-alpha
Edition: Community
Git Commit Hash: 3bcd5a889bded9ab23e7d077ea5c69df7982a495
Git Branch: heads/refs/tags/v6.5.0-alpha
UTC Build Time: 2022-11-19 14:34:49
GoVersion: go1.19.2
Race Enabled: false
TiKV Min Version: 6.2.0-alpha
Check Table Before Drop: false
Store: tikv |
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
```

**Comment by hawkingrei** [comment] 2022-12-06 17:56
I also found it by sqlancer.

```
[2022/12/07 01:52:21.264 +08:00] [ERROR] [conn.go:1058] ["connection running loop panic"] [conn=5075789876511637953] [lastSQL="SELECT t0.c0 FROM  t0 NATURAL RIGHT JOIN v0  WHERE (((NOT ('o4]enV')))REGEXP(((v0.c0)NOT LIKE(0.5249213420954858)))) UNION ALL SELECT t0.c0 FROM  t0 NATURAL RIGHT JOIN v0  WHERE (NOT ((((NOT ('o4]enV')))REGEXP(((v0.c0)NOT LIKE(0.5249213420954858)))))) UNION ALL SELECT t0.c0 FROM  t0 NATURAL RIGHT JOIN v0  WHERE (((((NOT ('o4]enV')))REGEXP(((v0.c0)NOT LIKE(0.5249213420954858))))) IS NULL);"] [err="interface conversion: expression.Expression is *expression.ScalarFunction, not *expression.Column"] [stack="github.com/pingcap/tidb/server.(*clientConn).Run.func1\n\t/Users/pingcap/workspace/build-common/go/src/github.com/pingcap/tidb/server/conn.go:1061\nruntime.gopanic\n\t/usr/local/go1.19.3/src/runtime/panic.go:884\ngithub.com/pingcap/tidb/executor.(*Compiler).Compile.func1\n\t/Users/pingcap/workspace/build-common/go/src/github.com/pingcap/tidb/executor/compiler.go:72\nruntime.gopanic\n\t/usr/local/go1.19.3/src/runtime/panic.go:884\nruntime.panicdottypeE\n\t/usr/local/go1.19.3/src/runtime/iface.go:262\nruntime.panicdottypeI\n\t/usr/local/go1.19.3/src/runtime/iface.go:272\ngithub.com/pingcap/tidb/planner/core.(*LogicalJoin).BuildKeyInfo\n\t/Users/pingcap/workspace/build-common/go/src/github.com/pingcap/tidb/planner/core/rule_build_key_info.go:201\ngithub.com/pingcap/tidb/planner/core.buildKeyInfo\n\t/Users/pingcap/workspace/build-common/go/src/github.com/pingcap/tidb/planner/core/rule_build_key_info.go:42\ngithub.com/pingcap/tidb/planner/core.(*LogicalJoin).PredicatePushDown\n\t/Users/pingcap/workspace/build-common/go/src/github.com/pingcap/tidb/planner/core/rule_predicate_push_down.go:243\ngithub.com/pingcap/tidb/planner/core.(*LogicalSelection).PredicatePushDown\n\t/Users/pingcap/workspace/build-common/go/src/github.com/pingcap/tidb/planner/core/rule_predicate_push_down.go:108\ngithub.com/pingcap/tidb/planner/core.(*baseLogicalPlan).PredicatePushDown\n\t/Users/pingcap/workspace/build-common/go/src/github.com/pingcap/tidb/planner/core/rule_predicate_push_down.go:81\ngithub.com/pingcap/tidb/planner/core.(*LogicalProjection).PredicatePushDown\n\t/Users/pingcap/workspace/build-common/go/src/github.com/pingcap/tidb/planner/core/rule_predicate_push_down.go:484\ngithub.com/pingcap/tidb/planner/core.(*LogicalUnionAll).PredicatePushDown\n\t/Users/pingcap/workspace/build-common/go/src/github.com/pingcap/tidb/planner/core/rule_predicate_push_down.go:493\ngithub.com/pingcap/tidb/planner/core.(*ppdSolver).optimize\n\t/Users/pingcap/workspace/build-common/go/src/github.com/pingcap/tidb/planner/core/rule_predicate_push_down.go:46\ngithub.com/pingcap/tidb/planner/core.logicalOptimize\n\t/Users/pingcap/workspace/build-common/go/src/github.com/pingcap/tidb/planner/core/optimizer.go:905\ngithub.com/pingcap/tidb/planner/core.DoOptimize\n\t/Users/pingcap/workspace/build-common/go/src/github.com/pingcap/tidb/planner/core/optimizer.go:285\ngithub.com/pingcap/tidb/planner.optimize\n\t/Users/pingcap/workspace/build-common/go/src/github.com/pingcap/tidb/planner/optimize.go:417\ngithub.com/pingcap/tidb/planner.Optimize\n\t/Users/pingcap/workspace/build-common/go/src/github.com/pingcap/tidb/planner/optimize.go:245\ngithub.com/pingcap/tidb/executor.(*Compiler).Compile\n\t/Users/pingcap/workspace/build-common/go/src/github.com/pingcap/tidb/executor/compiler.go:116\ngithub.com/pingcap/tidb/session.(*session).ExecuteStmt\n\t/Users/pingcap/workspace/build-common/go/src/github.com/pingcap/tidb/session/session.go:2168\ngithub.com/pingcap/tidb/server.(*TiDBContext).ExecuteStmt\n\t/Users/pingcap/workspace/build-common/go/src/github.com/pingcap/tidb/server/driver_tidb.go:247\ngithub.com/pingcap/tidb/server.(*clientConn).handleStmt\n\t/Users/pingcap/workspace/build-common/go/src/github.com/pingcap/tidb/server/conn.go:2093\ngithub.com/pingcap/tidb/server.(*clientConn).handleQuery\n\t/Users/pingcap/workspace/build-common/go/src/github.com/pingcap/tidb/server/conn.go:1943\ngithub.com/pingcap/tidb/server.(*clientConn).dispatch\n\t/Users/pingcap/workspace/build-common/go/src/github.com/pingcap/tidb/server/conn.go:1374\ngithub.com/pingcap/tidb/server.(*clientConn).Run\n\t/Users/pingcap/workspace/build-common/go/src/github.com/pingcap/tidb/server/conn.go:1123\ngithub.com/pingcap/tidb/server.(*Server).onConn\n\t/Users/pingcap/workspace/build-common/go/src/github.com/pingcap/tidb/server/server.go:625"]
```

**Comment by qw4990** [comment] 2024-04-28 07:17
Can't reproduce this issue, it might have been fixed by some other PR:
```
mysql>  explain ( select    cume_dist() over w as r0 , rtrim( tbl_5.col_35 ) as r1 , tbl_5.col_35 as r2 , from_base64( tbl_5.col_40 ) as r3 , tbl_5.col_39 as r4 , quote( tbl_5.col_41 ) as r5 , rank() over w as r6 from tbl_5 where not( IsNull( tbl_5.col_37 )  )  window w as ( partition by col_37,col_35,col_36,col_39,col_38,col_41,col_40 order by col_41,col_39,col_36,col_38,col_37,col_40,col_35 rows between current row and 2 following ) order by r0,r1,r2,r3,r4,r5,r6  ) except ( select    tbl_2.col_14 as     r0 , bit_and( tbl_2.col_11 ) as r1 , var_samp( tbl_2.col_11 ) as r2 , cume_dist() over w as r3 , dense_rank() over w as r4 , unhex( tbl_2.col_9 ) as r5 , nth_value( tbl_2.col_16 , 6 ) over w as r6 from tbl_2 where tbl_2.col_13 = 211.55233091704656 and not( IsNull( tbl_2.col_16 ) ) group by tbl_2.col_11 window w as ( partition by col_17,col_12,col_10,col_14,col_9,col_15,col_13,col_11,col_16 order by col_11,col_9,col_15,col_10,col_12,col_16,col_14,col_13,col_17  ) order by r0,r1,r2,r3,r4,r5,r6 limit  16  ) order by 1 limit 965;
+------------------------------------------------+----------+-----------+---------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| id                                             | estRows  | task      | access object | operator info                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
+------------------------------------------------+----------+-----------+---------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| TopN_29                                        | 965.00   | root      |               | Column#14, offset:0, count:965                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |
| └─HashJoin_34                                  | 8000.00  | root      |               | CARTESIAN anti semi join, other cond:nulleq(Column#12, from_binary(Column#47)), nulleq(Column#14, cast(test.tbl_2.col_14, double BINARY)), nulleq(cast(Column#10, double BINARY), cast(Column#43, double UNSIGNED BINARY)), nulleq(cast(Column#11, double BINARY), Column#45), nulleq(cast(Column#15, double BINARY), cast(Column#48, double BINARY)), nulleq(cast(test.tbl_5.col_35, double BINARY), Column#44), nulleq(test.tbl_5.col_39, cast(Column#46, decimal(20,0) BINARY))                                         |
|   ├─Projection_48(Build)                       | 1.00     | root      |               | test.tbl_2.col_14, Column#33->Column#43, Column#34->Column#44, Column#40->Column#45, Column#41->Column#46, Column#37->Column#47, Column#39->Column#48                                                                                                                                                                                                                                                                                                                                                                      |
|   │ └─TopN_51                                  | 1.00     | root      |               | test.tbl_2.col_14, Column#33, Column#34, Column#40, Column#41, Column#37, Column#39, offset:0, count:16                                                                                                                                                                                                                                                                                                                                                                                                                    |
|   │   └─Window_56                              | 1.00     | root      |               | cume_dist()->Column#40, dense_rank()->Column#41 over(partition by test.tbl_2.col_17, test.tbl_2.col_12, test.tbl_2.col_10, test.tbl_2.col_14, test.tbl_2.col_9, test.tbl_2.col_15, test.tbl_2.col_13, test.tbl_2.col_11, test.tbl_2.col_16 order by test.tbl_2.col_11, test.tbl_2.col_9, test.tbl_2.col_15, test.tbl_2.col_10, test.tbl_2.col_12, test.tbl_2.col_16, test.tbl_2.col_14, test.tbl_2.col_13, test.tbl_2.col_17)                                                                                              |
|   │     └─Window_57                            | 1.00     | root      |               | nth_value(test.tbl_2.col_16, 6)->Column#39 over(partition by test.tbl_2.col_17, test.tbl_2.col_12, test.tbl_2.col_10, test.tbl_2.col_14, test.tbl_2.col_9, test.tbl_2.col_15, test.tbl_2.col_13, test.tbl_2.col_11, test.tbl_2.col_16 order by test.tbl_2.col_11, test.tbl_2.col_9, test.tbl_2.col_15, test.tbl_2.col_10, test.tbl_2.col_12, test.tbl_2.col_16, test.tbl_2.col_14, test.tbl_2.col_13, test.tbl_2.col_17 range between unbounded preceding and current row)                                                 |
|   │       └─Sort_70                            | 1.00     | root      |               | test.tbl_2.col_17, test.tbl_2.col_12, test.tbl_2.col_10, test.tbl_2.col_14, test.tbl_2.col_9, test.tbl_2.col_15, test.tbl_2.col_13, test.tbl_2.col_11, test.tbl_2.col_16, test.tbl_2.col_11, test.tbl_2.col_9, test.tbl_2.col_15, test.tbl_2.col_10, test.tbl_2.col_12, test.tbl_2.col_16, test.tbl_2.col_14, test.tbl_2.col_13, test.tbl_2.col_17                                                                                                                                                                         |
|   │         └─Projection_60                    | 1.00     | root      |               | test.tbl_2.col_14, Column#33, Column#34, unhex(test.tbl_2.col_9)->Column#37, test.tbl_2.col_16, test.tbl_2.col_17, test.tbl_2.col_12, test.tbl_2.col_10, test.tbl_2.col_9, test.tbl_2.col_15, test.tbl_2.col_13, test.tbl_2.col_11                                                                                                                                                                                                                                                                                         |
|   │           └─HashAgg_61                     | 1.00     | root      |               | group by:Column#68, funcs:bit_and(Column#57)->Column#33, funcs:var_samp(Column#58)->Column#34, funcs:firstrow(Column#59)->test.tbl_2.col_9, funcs:firstrow(Column#60)->test.tbl_2.col_10, funcs:firstrow(Column#61)->test.tbl_2.col_11, funcs:firstrow(Column#62)->test.tbl_2.col_12, funcs:firstrow(Column#63)->test.tbl_2.col_13, funcs:firstrow(Column#64)->test.tbl_2.col_14, funcs:firstrow(Column#65)->test.tbl_2.col_15, funcs:firstrow(Column#66)->test.tbl_2.col_16, funcs:firstrow(Column#67)->test.tbl_2.col_17 |
|   │             └─Projection_72                | 0.00     | root      |               | test.tbl_2.col_11->Column#57, cast(test.tbl_2.col_11, double UNSIGNED BINARY)->Column#58, test.tbl_2.col_9->Column#59, test.tbl_2.col_10->Column#60, test.tbl_2.col_11->Column#61, test.tbl_2.col_12->Column#62, test.tbl_2.col_13->Column#63, test.tbl_2.col_14->Column#64, test.tbl_2.col_15->Column#65, test.tbl_2.col_16->Column#66, test.tbl_2.col_17->Column#67, test.tbl_2.col_11->Column#68                                                                                                                        |
|   │               └─TableReader_66             | 0.00     | root      |               | data:Selection_65                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
|   │                 └─Selection_65             | 0.00     | cop[tikv] |               | eq(test.tbl_2.col_13, 211.55233091704656), not(isnull(test.tbl_2.col_16))                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
|   │                   └─TableFullScan_64       | 10000.00 | cop[tikv] | table:tbl_2   | keep order:false, stats:pseudo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |
|   └─HashAgg_35(Probe)                          | 10000.00 | root      |               | group by:Column#10, Column#11, Column#12, Column#14, Column#15, test.tbl_5.col_35, test.tbl_5.col_39, funcs:firstrow(Column#14)->Column#14, funcs:firstrow(Column#10)->Column#10, funcs:firstrow(test.tbl_5.col_35)->test.tbl_5.col_35, funcs:firstrow(Column#11)->Column#11, funcs:firstrow(test.tbl_5.col_39)->test.tbl_5.col_39, funcs:firstrow(Column#12)->Column#12, funcs:firstrow(Column#15)->Column#15                                                                                                             |
|     └─Sort_37                                  | 10000.00 | root      |               | Column#14, Column#10, test.tbl_5.col_35, Column#11, test.tbl_5.col_39, Column#12, Column#15                                                                                                                                                                                                                                                                                                                                                                                                                                |
|       └─Shuffle_45                             | 10000.00 | root      |               | execution info: concurrency:5, data sources:[Projection_41]                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
|         └─Window_39                            | 10000.00 | root      |               | cume_dist()->Column#14, rank()->Column#15 over(partition by test.tbl_5.col_37, test.tbl_5.col_35, test.tbl_5.col_36, test.tbl_5.col_39, test.tbl_5.col_38, test.tbl_5.col_41, test.tbl_5.col_40 order by test.tbl_5.col_41, test.tbl_5.col_39, test.tbl_5.col_36, test.tbl_5.col_38, test.tbl_5.col_37, test.tbl_5.col_40, test.tbl_5.col_35)                                                                                                                                                                              |
|           └─Sort_44                            | 10000.00 | root      |               | test.tbl_5.col_37, test.tbl_5.col_35, test.tbl_5.col_36, test.tbl_5.col_39, test.tbl_5.col_38, test.tbl_5.col_41, test.tbl_5.col_40, test.tbl_5.col_41, test.tbl_5.col_39, test.tbl_5.col_36, test.tbl_5.col_38, test.tbl_5.col_37, test.tbl_5.col_40, test.tbl_5.col_35                                                                                                                                                                                                                                                   |
|             └─ShuffleReceiver_73               | 10000.00 | root      |               |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |
|               └─Projection_41                  | 10000.00 | root      |               | rtrim(test.tbl_5.col_35)->Column#10, test.tbl_5.col_35, from_base64(test.tbl_5.col_40)->Column#11, test.tbl_5.col_39, quote(test.tbl_5.col_41)->Column#12, test.tbl_5.col_37, test.tbl_5.col_36, test.tbl_5.col_38, test.tbl_5.col_41, test.tbl_5.col_40                                                                                                                                                                                                                                                                   |
|                 └─TableReader_43               | 10000.00 | root      |               | data:TableFullScan_42                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
|                   └─TableFullScan_42           | 10000.00 | cop[tikv] | table:tbl_5   | keep order:false, stats:pseudo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |
+------------------------------------------------+----------+-----------+---------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
22 rows in set, 3 warnings (0.01 sec)
```

**Closed by qw4990** 2024-04-28 07:17 UTC
Labels: type/bug, sig/planner, severity/major, affects-5.4, may-affects-4.0, may-affects-5.1, may-affects-5.2, may-affects-5.3, may-affects-5.0, affects-6.0, affects-6.1, affects-6.2, affects-6.3, affects-6.4, affects-6.5, affects-6.6, affects-7.0, affects-7.1, affects-7.5, affects-8.1
