### ISSUE TITLE
possible wrong error log

### ISSUE THREAD

**Issue by bearHunting** [pingcap/tidb#12281] opened 2019-09-19 14:26 UTC
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
run below sql:
"delete  from shr_production_inbound_detail_day
  where date_format(belonged_date,'%Y%m%d')='20190918'
"
in above sql,  belonged_date field has values like '2019-09-18'. In order to use less variable, I use above sql.

2. What did you expect to see?
no error.

3. What did you see instead?

[Err] 1292 - Incorrect datetime value: 'belonged_d'

Problem is that "belonged_d“ is a field, not any value. I think the error reporting logic is bugged.

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
2.1.14

**Comment by lonng** [comment] 2019-09-19 23:20
@bearHunting Thanks for your feedback, this is a BUG.

**Comment by lonng** [comment] 2019-09-19 23:33
@bearHunting Thanks for your feedback.

I cannot reproduce this error in my local environment:
1. Can you check the data source whether some incorrect `DateTime` values contain?
2. Provide the schema and some sample data if you cannot find any invalid `DateTime` in your data source to help us locate the problem.

**Comment by bearHunting** [comment] 2019-09-20 02:55
I changed sql: 
date_format(belonged_date,'%Y%m%d')='20190918'
as:
belonged_date='2019-09-18'
then it's OK. I reported similar problem once, but not able to reproduce it. Link is here [https://github.com/pingcap/tidb/issues/10171](url)

**Comment by nullnotnil** [comment] 2020-07-16 20:45
This looks to be fixed in master:
```sql
DROP TABLE IF EXISTS t1;
CREATE TABLE t1 (
 id INT NOT NULL PRIMARY KEY auto_increment,
 dcol DATE NOT NULL
);

INSERT INTO t1 (dcol) VALUES ('20190918');
SELECT * FROM t1 WHERE DATE_FORMAT(dcol, '%Y%m%d')='20190918';
DELETE FROM t1 WHERE DATE_FORMAT(dcol, '%Y%m%d')='20190918';
SELECT * FROM t1;

..

mysql> SELECT * FROM t1 WHERE DATE_FORMAT(dcol, '%Y%m%d')='20190918';
+----+------------+
| id | dcol       |
+----+------------+
|  1 | 2019-09-18 |
+----+------------+
1 row in set (0.00 sec)

mysql> DELETE FROM t1 WHERE DATE_FORMAT(dcol, '%Y%m%d')='20190918';
Query OK, 1 row affected (0.01 sec)

mysql> SELECT * FROM t1;
Empty set (0.00 sec)

mysql> SELECT tidb_version()\G
*************************** 1. row ***************************
tidb_version(): Release Version: v4.0.0-beta.2-782-gb72e47e6d
Edition: Community
Git Commit Hash: b72e47e6db8863c08e47714391cf937b0f1c3269
Git Branch: master
UTC Build Time: 2020-07-15 01:26:06
GoVersion: go1.13
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
1 row in set (0.00 sec)
```

One thing I would warn about, is that while this syntax is legal - I wouldn't recommend it. Most databases will not be able to use an index if you use a function on a column.

**Comment by nullnotnil** [comment] 2020-07-22 18:55
I am going to close this issue now, but please feel free to reopen if you have additional questions. Thanks!

**Closed by nullnotnil** 2020-07-22 18:55 UTC
Labels: type/question
