### ISSUE TITLE
The result of `show variables` is not compatible with MySQL

### ISSUE THREAD

**Issue by zimulala** [pingcap/tidb#9357] opened 2019-02-19 10:48 UTC
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
```
select @@global.sql_log_bin;
show variables like "sql_log_bin";
```

2. What did you expect to see?
Your MySQL connection id is 172
Server version: 5.7.20 Homebrew
```
mysql> select @@global.sql_log_bin;
+----------------------+
| @@global.sql_log_bin |
+----------------------+
|                    1 |
+----------------------+
1 row in set, 1 warning (0.00 sec)

mysql> show variables like "sql_log_bin";
+---------------+-------+
| Variable_name | Value |
+---------------+-------+
| sql_log_bin   | ON    |
+---------------+-------+
1 row in set (0.00 sec)
```

3. What did you see instead?
```
tidb> select @@global.sql_log_bin;
+----------------------+
| @@global.sql_log_bin |
+----------------------+
| 1                    |
+----------------------+
1 row in set (0.00 sec)

tidb> show variables like "sql_log_bin";
+---------------+-------+
| Variable_name | Value |
+---------------+-------+
| sql_log_bin   | 1     |
+---------------+-------+
1 row in set (0.02 sec)
```

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
Release Version: v3.0.0-beta-69-g84d1513b0-dirty
Git Commit Hash: 84d1513b09222c60ffba2d3397b6745e5148a603
Git Branch: master

**Comment by nullnotnil** [comment] 2020-08-03 17:12
This is a duplicate of #15131

It requires a type system for system variables, so that depending on context of `@@` or `show variables` the value can be returned correctly.

I am going to close this to reduce duplication.

**Closed by nullnotnil** 2020-08-03 17:12 UTC
Labels: status/help-wanted, type/compatibility, type/duplicate
