### ISSUE TITLE
[compatibility] TIME_TO_SEC is different from mysql

### ISSUE THREAD

**Issue by liangjiaxing** [pingcap/tidb#4162] opened 2017-08-13 19:35 UTC
1. What did you do?
ran a query `select time_to_sec('00:00:61');`

2. What did you expect to see?
The output from mysql
```
MariaDB [(none)]>  select time_to_sec('00:00:61');                                                                                    
+-------------------------+                                                                                                           
| time_to_sec('00:00:61') |                                                                                                           
+-------------------------+                                                                                                           
|                    NULL |                                                                                                           
+-------------------------+                
```                                                                                           

3. What did you see instead?
```
tidb> select time_to_sec('00:00:61');
+-------------------------+
| time_to_sec('00:00:61') |
+-------------------------+
|                      61 |
+-------------------------+

```

4. What version of TiDB are you using (`tidb-server -V`)?
Git Commit Hash: e9785fda15784bd5197f675f148e97aca97852a8
UTC Build Time:  2017-08-05 06:19:58

**Comment by zz-jason** [comment] 2017-08-23 07:28
to #4080

**Comment by morgo** [comment] 2018-11-24 17:16
I can confirm the problem is fixed:
```
mysql57> select time_to_sec('00:00:61');
+-------------------------+
| time_to_sec('00:00:61') |
+-------------------------+
|                    NULL |
+-------------------------+
1 row in set, 1 warning (0.00 sec)

Warning (Code 1292): Truncated incorrect time value: '00:00:61'

mysql> select time_to_sec('00:00:61');
+-------------------------+
| time_to_sec('00:00:61') |
+-------------------------+
|                    NULL |
+-------------------------+
1 row in set, 1 warning (0.00 sec)

Warning (Code 1292): Truncated incorrect time value: '00:00:61'
mysql> select tidb_version()\G
*************************** 1. row ***************************
tidb_version(): Release Version: v2.1.0-rc.3-219-g1e0876fe8-dirty
Git Commit Hash: 1e0876fe810a832721aac52275dd2b7792fd2892
Git Branch: flush
UTC Build Time: 2018-11-24 01:12:47
GoVersion: go version go1.11 linux/amd64
Race Enabled: false
TiKV Min Version: 2.1.0-alpha.1-ff3dd160846b7d1aed9079c389fc188f7f5ea13e
Check Table Before Drop: false
1 row in set (0.00 sec)
```

I am going to close this issue now, but please feel free to re-open if you have any questions.  Thanks!

**Closed by morgo** 2018-11-24 17:16 UTC
Labels: type/compatibility
