### ISSUE TITLE
Do PHP application(e.g. Drupal) can connect it just like MySQL ?

### ISSUE THREAD

**Issue by keithyau** [pingcap/tidb#720] opened 2015-12-14 07:30 UTC
First of all, just attended OSChina and really like pingcap's presenation.

just tried to install Drupal and point DB to port 4000, with a SQLSTATE[HY000] [2002]  ERROR

![image](https://cloud.githubusercontent.com/assets/659311/11775175/79affc88-a277-11e5-90ce-0305daeb428c.png)

Please kindly advice

**Comment by shenli** [comment] 2015-12-14 07:34
@keithyau Thanks for your report!
We will work on this issue.

**Comment by keithyau** [comment] 2015-12-14 07:49
update:

docker php code -> localhost:4000 failed
but 
local php code -> localhost:4000 successful init the db install, but it becomes a gateway timeout.


Do any test case available that TiDB + wordpress / PHP application so that i can take as reference ?

**Comment by keithyau** [comment] 2015-12-14 08:02
Question: How can i tune things like max_connection or wait timeout like i were in my.cnf ?

**Comment by shenli** [comment] 2015-12-14 08:23
@keithyau There is a system variable "max_connection".
For now we do not have a config file. You can modify it by set system variable(set name=value). Or you can change the default value for variables in mysql.global_variables table.

**Comment by morefreeze** [comment] 2015-12-14 08:46
http://stackoverflow.com/questions/1676688/php-mysql-connection-not-working-2002-no-such-file-or-directory

@keithyau About your Error 2002, please take a look at the best answer.

If you have solved Error 2002, could you post your php code briefly?

I try this code on my OSX it is ok.

    $mysqli = new mysqli("localhost", "root", "", "test", 4000);

Hope your reply.

**Comment by keithyau** [comment] 2015-12-14 08:59
@morefreeze thanks, the no such file problem solved, i found the problem more on the installation stopped at the middle. And my php application response 504 server timeour. Will try setting some max connection / wait timeout and get back to u.

thanks you guys

**Comment by keithyau** [comment] 2015-12-14 09:17
tried install php application with php-cli and got this

Calling install_drupal(Array) [264.21 sec, 6.87 MB]                           [debug]
exception 'PDOException' with message 'SQLSTATE[HY000]: General error:    [error]
2013 Lost connection to MySQL server during query' in
/var/www/html/drupal-7.41/includes/database/database.inc:2171


How can I enable query log in TiDB? So that i can find which query exactly made the timeout.

**Comment by shenli** [comment] 2015-12-14 09:26
@keithyau 
If you start tidb with tidb-server, you can see the logs in stdout. If you start tidb with docker, you can see the logs with docker logs.

**Comment by keithyau** [comment] 2015-12-14 10:25
yes thanks
@shenli 
 runtime error: index out of range, goroutine 88634 [running]:

I got this.. any parameter required to tune ?

![image](https://cloud.githubusercontent.com/assets/659311/11778530/d5b428d4-a28f-11e5-8f3c-5a9a533f7873.png)

**Comment by shenli** [comment] 2015-12-14 11:25
@keithyau I am not sure. I am installing drupal on my machine to check it out.

**Comment by shenli** [comment] 2015-12-14 13:54
@keithyau I get the following errors when install drupal. But I do not find error log from tidb-server output. Do you have any idea about this? I use the latest drupal 8.0.1.

_drupal_error_handler_real(4096, 'Argument 1 passed to Drupal\Core\Plugin\DefaultPluginManager::doGetDefinition() must be of the type array, boolean given, called in /Library/WebServer/Documents/drupal/core/lib/Drupal/Component/Plugin/Discovery/DiscoveryCachedTrait.php on line 30 and defined', '/Library/WebServer/Documents/drupal/core/lib/Drupal/Component/Plugin/Discovery/DiscoveryTrait.php', 48, Array)
_drupal_error_handler(4096, 'Argument 1 passed to Drupal\Core\Plugin\DefaultPluginManager::doGetDefinition() must be of the type array, boolean given, called in /Library/WebServer/Documents/drupal/core/lib/Drupal/Component/Plugin/Discovery/DiscoveryCachedTrait.php on line 30 and defined', '/Library/WebServer/Documents/drupal/core/lib/Drupal/Component/Plugin/Discovery/DiscoveryTrait.php', 48, Array)
Drupal\Core\Plugin\DefaultPluginManager->doGetDefinition(, 'user_role', )

**Comment by keithyau** [comment] 2015-12-14 14:23
im trying with Drupal 7 as Drupal 8 is new and not good for compatibility test to new DB.

But for both D7 and D8, both terminated the installation due to "DB go away".

and the error i see so far is

runtime error: index out of range, goroutine 88634 [running]:

what is go routine ? Or i can help to debug

**Comment by keithyau** [comment] 2015-12-16 03:55
@shenli Any hints about index out of range ? New to Go lang

**Comment by shenli** [comment] 2015-12-16 04:01
@keithyau I am working on this.

**Comment by keithyau** [comment] 2015-12-16 04:53
this is the error print on my linux build, looks like even earlier step than docker

![image](https://cloud.githubusercontent.com/assets/659311/11832516/f201e14c-a3f3-11e5-89e5-0f80fd057abc.png)

**Comment by keithyau** [comment] 2015-12-16 06:11
With the key already exists error, but still some tables created. Stopped at Insert into system, so i guess may be some syntax not supported ?

![image](https://cloud.githubusercontent.com/assets/659311/11833561/ce7113fa-a3fe-11e5-8f73-c9f8d1da9f7f.png)

**Comment by shenli** [comment] 2015-12-16 06:37
@keithyau filename is the pk of system table. And I see drupal insert two rows with the same filename value "modules/system/system.module". From the log I can find two insert statement both with the "modules/system/system.module" row. The first is "INSERT INTO main_system (filename, name, type, owner, status, schema_version, bootstrap) VALUES ('modules/system/system.module', 'system', 'module', '', '1', '7080', '0')". The second one is a huge sql which insert many rows: "INSERT INTO main_system (filename, name, type, owner, info) VALUES ('modules/update/tests/aaa_update_test.module', 'aaa_update_test', 'module', '',......('modules/system/system.module', 'system', 'module', '', 'a:14:{s:4:\"name\";s:6:\"System\";s:11:\"description\";s:54:\"Handles general site configuration for administrators.\";s:7:\"package\";s:4:\"Core\";s:7:\"version\";s:4:\"7.41\";s:4:\"core\";s:3:\"7.x\";s:5:\"files\";a:6:{i:0;s:19:\"system.archiver.inc\";i:1;s:15:\"system.mail.inc\";i:2;s:16:\"system.queue.inc\";i:3;s:14:\"system.tar.inc\";i:4;s:18:\"system.updater.inc\";i:5;s:11:\"system.test\";}s:8:\"required\";b:1;s:9:\"configure\";s:19:\"admin/config/system\";s:7:\"project\";s:6:\"drupal\";s:9:\"datestamp\";s:10:\"1445457729\";s:5:\"mtime\";i:1450160850;s:12:\"dependencies\";a:0:{}s:3:\"php\";s:5:\"5.2.4\";s:9:\"bootstrap\";i:0;}'),........". You can grep "modules/system/system.module" from tidb-server output.

I tried with mysql and installed successfully. So I think there is some thing wrong with TiDB.

**Comment by breeswish** [comment] 2017-07-07 12:14
Update with Drupal 8.3.5 + latest TiDB:

Install failed.

```
Drupal\Component\Plugin\Exception\PluginNotFoundException: Plugin ID 'contact.site_page' was not found. in Drupal\Core\Menu\MenuLinkManager->getDefinition() (line 208 of core/lib/Drupal/Core/Menu/MenuLinkManager.php).
Drupal\Core\Menu\MenuLinkManager->getDefinition('contact.site_page') (Line: 16)
Drupal\Core\Plugin\Factory\ContainerFactory->createInstance('contact.site_page', Array) (Line: 235)
Drupal\Core\Menu\MenuLinkManager->createInstance('contact.site_page') (Line: 366)
Drupal\Core\Menu\MenuLinkManager->updateDefinition('contact.site_page', Array) (Line: 43)
standard_install()
call_user_func_array('standard_install', Array) (Line: 391)
Drupal\Core\Extension\ModuleHandler->invoke('standard', 'install') (Line: 287)
Drupal\Core\Extension\ModuleInstaller->install(Array, ) (Line: 83)
Drupal\Core\ProxyClass\Extension\ModuleInstaller->install(Array, ) (Line: 1572)
install_install_profile(Array) (Line: 662)
install_run_task(Array, Array) (Line: 540)
install_run_tasks(Array) (Line: 117)
install_drupal(Object) (Line: 44)
```

**Comment by breeswish** [comment] 2017-07-10 06:44
Drupal heavily used SAVEPOINT, which TiDB does not support currently: https://github.com/pingcap/tidb/issues/3663

**Comment by sparkpos** [comment] 2018-03-05 10:36
On my MacOS, I can install  my Drupal 8 over TiDB successfully.

TiDB install: https://github.com/pingcap/tidb-docker-compose
Drupal version: 8.4.4
PHP version: 7.1

Hope it helps.

**Comment by terryzwt** [comment] 2018-03-05 10:37
On my MacOS, I can install my Drupal 8 over TiDB successfully.

TiDB install: https://github.com/pingcap/tidb-docker-compose
Drupal version: 8.4.4
PHP version: 7.1

Hope it helps.

**Comment by zimulala** [comment] 2018-03-05 11:43
@terryzwt 
Thanks for your report!

**Comment by sparkpos** [comment] 2018-03-08 13:07
but for some update operations, there will be errors. 
`Drupal\Core\Entity\EntityStorageException: SQLSTATE[HY000]: General error: 1105 line 1 column 10 near "savepoint_1" (total length 21): SAVEPOINT savepoint_1; Array ( ) in Drupal\Core\Entity\Sql\SqlContentEntityStorage->save() (line 829 of /var/www/html/core/lib/Drupal/Core/Entity/Sql/SqlContentEntityStorage.php).`

**Comment by tiancaiamao** [comment] 2018-03-08 13:35
What's the error log in TiDB? @sparkpos

**Comment by sparkpos** [comment] 2018-03-08 14:39
@tiancaiamao I install tidb by docker-compose provided by official. 
In this case, how check the logs?
I have check tidb, kv, pd logs; But I can only see info logs, can't see error logs.

**Comment by tiancaiamao** [comment] 2018-03-08 14:42
@tennix How to check TiDB log?

**Comment by shenli** [comment] 2018-03-08 14:53
@tiancaiamao I think this is the SQL which TiDB doesn't support: `SAVEPOINT savepoint_1; `.

**Comment by tennix** [comment] 2018-04-10 12:00
@tiancaiamao `docker-compose logs tidb`

**Comment by breeswish** [comment] 2018-04-10 12:45
As stated previously, currently we does not support SAVEPOINT. #3663

**Comment by morgo** [comment] 2018-11-25 12:58
I have merged https://github.com/pingcap/tidb/issues/3663 with https://github.com/pingcap/tidb/issues/6840 - Please follow this issue for updates regarding SAVEPOINT support.

Since the cause of the error is now known, I am going to close this issue for now.  Please feel free to re-open if you have any followup questions. Thanks!

**Closed by morgo** 2018-11-25 12:58 UTC
Labels: question
