### ISSUE TITLE
Partition table run SQL with `rollup` throw error `Internal : Can't find a proper physical plan for this query`

### ISSUE THREAD

**Issue by 7yyo** [pingcap/tidb#51772] opened 2024-03-14 07:08 UTC
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```sql
MySQL [test]> CREATE TABLE bank (year INT, month VARCHAR(32), day INT, profit DECIMAL(13, 7)) PARTITION BY RANGE (`day`) (PARTITION `p0` VALUES LESS THAN (1), PARTITION `pMax` VALUES LESS THAN (MAXVALUE));
Query OK, 0 rows affected (0.12 sec)

MySQL [test]> ALTER TABLE bank SET TIFLASH REPLICA 1;
Query OK, 0 rows affected (0.14 sec)

MySQL [test]> INSERT INTO bank VALUES(2000, "Jan", 1, 10.3),(2001, "Feb", 2, 22.4),(2000,"Mar", 3, 31.6);
Query OK, 3 rows affected (0.01 sec)
Records: 3  Duplicates: 0  Warnings: 0

MySQL [test]> SELECT year, month, SUM(profit) AS profit from bank GROUP BY year, month WITH ROLLUP ORDER BY year desc, month desc;
ERROR 1815 (HY000): Internal : Can't find a proper physical plan for this query
```

```sql
MySQL [test_1]> CREATE TABLE bank (year INT, month VARCHAR(32), day INT, profit DECIMAL(13, 7));
Query OK, 0 rows affected (0.12 sec)

MySQL [test_1]> ALTER TABLE bank SET TIFLASH REPLICA 1;
Query OK, 0 rows affected (0.12 sec)

MySQL [test_1]> INSERT INTO bank VALUES(2000, "Jan", 1, 10.3),(2001, "Feb", 2, 22.4),(2000,"Mar", 3, 31.6);
Query OK, 3 rows affected (0.02 sec)
Records: 3  Duplicates: 0  Warnings: 0

MySQL [test_1]> SELECT year, month, SUM(profit) AS profit from bank GROUP BY year, month WITH ROLLUP ORDER BY year desc, month desc;
+------+-------+------------+
| year | month | profit     |
+------+-------+------------+
| 2001 | Feb   | 22.4000000 |
| 2001 | NULL  | 22.4000000 |
| 2000 | Mar   | 31.6000000 |
| 2000 | Jan   | 10.3000000 |
| 2000 | NULL  | 41.9000000 |
| NULL | NULL  | 64.3000000 |
+------+-------+------------+
6 rows in set (0.02 sec)
```

### 2. What did you expect to see? (Required)
run success.
### 3. What did you see instead (Required)
Partition table throw error: `ERROR 1815 (HY000): Internal : Can't find a proper physical plan for this query`
### 4. What is your TiDB version? (Required)
`7.6`

**Comment by akuluasan** [comment] 2024-03-15 17:09
Hello,


Below is the simplified query result that still triggers the bug. The aim of this simplification is to assist developers in identifying the root cause of the issue.

```sql
-- case 1 in mysql
DROP DATABASE IF EXISTS database1;
CREATE DATABASE database1;
USE database1;

CREATE TABLE bank (year INT, month VARCHAR(32), day INT, profit DECIMAL(13, 7)) PARTITION BY RANGE (`day`) (PARTITION `p0` VALUES LESS THAN (1), PARTITION `pMax` VALUES LESS THAN (MAXVALUE));

ALTER TABLE bank SET TIFLASH REPLICA 1;

INSERT INTO bank VALUES(2000,"Mar", 3, 31.6);

SELECT year, month  from bank GROUP BY year, month WITH ROLLUP ;



+------+-------+
| year | month |
+------+-------+
| 2000 | Mar   |
| 2000 | NULL  |
| NULL | NULL  |
+------+-------+
3 rows in set (0.00 sec)

```



```sql
-- case 2 in tidb 
DROP DATABASE IF EXISTS database1;
CREATE DATABASE database1;
USE database1;

CREATE TABLE bank (year INT, month VARCHAR(32), day INT, profit DECIMAL(13, 7)) PARTITION BY RANGE (`day`) (PARTITION `p0` VALUES LESS THAN (1), PARTITION `pMax` VALUES LESS THAN (MAXVALUE));

ALTER TABLE bank SET TIFLASH REPLICA 1;

INSERT INTO bank VALUES(2000,"Mar", 3, 31.6);

SELECT year, month  from bank GROUP BY year, month WITH ROLLUP ;



ERROR 1815 (HY000): Internal : Can't find a proper physical plan for this query

```




- We've distilled the steps and SQL statements to the bare essentials needed to reproduce the issue. This ensures clarity and focuses on the core problem.
- The logic behind this simplification process was to eliminate any elements of the query that did not directly contribute to the observed bug, streamlining the diagnostic process.

Could you please confirm whether this simplification process has been beneficial for developers in diagnosing and addressing the issue?

**Comment by AilinKid** [comment] 2024-03-18 15:43
> Hello,
> 
> Below is the simplified query result that still triggers the bug. The aim of this simplification is to assist developers in identifying the root cause of the issue.
> 
> ```sql
> -- case 1 in mysql
> DROP DATABASE IF EXISTS database1;
> CREATE DATABASE database1;
> USE database1;
> 
> CREATE TABLE bank (year INT, month VARCHAR(32), day INT, profit DECIMAL(13, 7)) PARTITION BY RANGE (`day`) (PARTITION `p0` VALUES LESS THAN (1), PARTITION `pMax` VALUES LESS THAN (MAXVALUE));
> 
> ALTER TABLE bank SET TIFLASH REPLICA 1;
> 
> INSERT INTO bank VALUES(2000,"Mar", 3, 31.6);
> 
> SELECT year, month  from bank GROUP BY year, month WITH ROLLUP ;
> 
> 
> 
> +------+-------+
> | year | month |
> +------+-------+
> | 2000 | Mar   |
> | 2000 | NULL  |
> | NULL | NULL  |
> +------+-------+
> 3 rows in set (0.00 sec)
> ```
> 
> ```sql
> -- case 2 in tidb 
> DROP DATABASE IF EXISTS database1;
> CREATE DATABASE database1;
> USE database1;
> 
> CREATE TABLE bank (year INT, month VARCHAR(32), day INT, profit DECIMAL(13, 7)) PARTITION BY RANGE (`day`) (PARTITION `p0` VALUES LESS THAN (1), PARTITION `pMax` VALUES LESS THAN (MAXVALUE));
> 
> ALTER TABLE bank SET TIFLASH REPLICA 1;
> 
> INSERT INTO bank VALUES(2000,"Mar", 3, 31.6);
> 
> SELECT year, month  from bank GROUP BY year, month WITH ROLLUP ;
> 
> 
> 
> ERROR 1815 (HY000): Internal : Can't find a proper physical plan for this query
> ```
> 
> * We've distilled the steps and SQL statements to the bare essentials needed to reproduce the issue. This ensures clarity and focuses on the core problem.
> * The logic behind this simplification process was to eliminate any elements of the query that did not directly contribute to the observed bug, streamlining the diagnostic process.
> 
> Could you please confirm whether this simplification process has been beneficial for developers in diagnosing and addressing the issue?

hi~ thx for both of your efforts on this problem. I guess you forgot to wait the tiflash replica available/ready. When the ddl of setting replica is typed in, the finish of statement itself means nothing, while we need to wait all the partition of the base  table to be replicated to tiflash. You can check the `select * from information_schema.TIFLASH_REPLICA;` to see whether it's ready or not.

what I got in my local env is like below:
```
tidb> explain SELECT year, month  from bank GROUP BY year, month WITH ROLLUP ;
+------------------------------------+---------+--------------+---------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| id                                 | estRows | task         | access object | operator info                                                                                                                                                      |
+------------------------------------+---------+--------------+---------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| TableReader_44                     | 1.00    | root         | partition:all | MppVersion: 2, data:ExchangeSender_43                                                                                                                              |
| └─ExchangeSender_43                | 1.00    | mpp[tiflash] |               | ExchangeType: PassThrough                                                                                                                                          |
|   └─Projection_38                  | 1.00    | mpp[tiflash] |               | Column#6->Column#9, Column#7->Column#10                                                                                                                            |
|     └─HashAgg_36                   | 1.00    | mpp[tiflash] |               | group by:Column#6, Column#7, gid, funcs:firstrow(Column#6)->Column#6, funcs:firstrow(Column#7)->Column#7                                                           |
|       └─ExchangeReceiver_22        | 1.00    | mpp[tiflash] |               |                                                                                                                                                                    |
|         └─ExchangeSender_21        | 1.00    | mpp[tiflash] |               | ExchangeType: HashPartition, Compression: FAST, Hash Cols: [name: Column#6, collate: binary], [name: Column#7, collate: utf8mb4_bin], [name: gid, collate: binary] |
|           └─Expand_20              | 1.00    | mpp[tiflash] |               | level-projection:[<nil>->Column#6, <nil>->Column#7, 0->gid],[Column#6, <nil>->Column#7, 1->gid],[Column#6, Column#7, 3->gid]; schema: [Column#6,Column#7,gid]      |
|             └─TableFullScan_17     | 1.00    | mpp[tiflash] | table:bank    | keep order:false, stats:pseudo, PartitionTableScan:true                                                                                                            |
+------------------------------------+---------+--------------+---------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------+
8 rows in set (3.06 sec)
tidb> show create table bank;
+-------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Table | Create Table                                                                                                                                                                                                                                                                                                                             |
+-------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| bank  | CREATE TABLE `bank` (
  `year` int(11) DEFAULT NULL,
  `month` varchar(32) DEFAULT NULL,
  `day` int(11) DEFAULT NULL,
  `profit` decimal(13,7) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin
PARTITION BY RANGE (`day`)
(PARTITION `p0` VALUES LESS THAN (1),
 PARTITION `pMax` VALUES LESS THAN (MAXVALUE)) |
+-------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)
```

**Comment by 7yyo** [comment] 2024-03-18 16:02
@AilinKid tiflash replica is ready. Why is it different from your test result
![Uploading Screenshot 2024-03-18 at 23.59.03.png…]()

**Comment by AilinKid** [comment] 2024-03-18 16:23
> @AilinKid tiflash replica is ready. Why is it different from your test result
> 
> ```sql
> MySQL [test]> CREATE TABLE bank (year INT, month VARCHAR(32), day INT, profit DECIMAL(13, 7)) PARTITION BY RANGE (`day`) (PARTITION `p0` VALUES LESS THAN (1), PARTITION `pMax` VALUES LESS THAN (MAXVALUE));
> Query OK, 0 rows affected (0.21 sec)
> 
> MySQL [test]> ALTER TABLE bank SET TIFLASH REPLICA 1;
> Query OK, 0 rows affected (0.15 sec)
> 
> MySQL [test]> select * from information_schema.tiflash_replica;
> +--------------+------------------------+----------+---------------+-----------------+-----------+----------+
> | TABLE_SCHEMA | TABLE_NAME             | TABLE_ID | REPLICA_COUNT | LOCATION_LABELS | AVAILABLE | PROGRESS |
> +--------------+------------------------+----------+---------------+-----------------+-----------+----------+
> | hybench      | customer               |      364 |             1 |                 |         1 |        1 |
> | hybench      | company                |      366 |             1 |                 |         1 |        1 |
> | hybench      | savingAccount          |      368 |             1 |                 |         1 |        1 |
> | hybench      | checkingAccount        |      370 |             1 |                 |         1 |        1 |
> | hybench      | transfer               |      372 |             1 |                 |         1 |        1 |
> | hybench      | checking               |      374 |             1 |                 |         1 |        1 |
> | hybench      | loanapps               |      376 |             1 |                 |         1 |        1 |
> | hybench      | loantrans              |      378 |             1 |                 |         1 |        1 |
> | test         | bank                   |      444 |             1 |                 |         1 |        1 |
> | tpcds        | dbgen_version          |      104 |             1 |                 |         1 |        1 |
> | tpcds        | customer_address       |      106 |             1 |                 |         1 |        1 |
> | tpcds        | customer_demographics  |      108 |             1 |                 |         1 |        1 |
> | tpcds        | date_dim               |      110 |             1 |                 |         1 |        1 |
> | tpcds        | warehouse              |      112 |             1 |                 |         1 |        1 |
> | tpcds        | ship_mode              |      114 |             1 |                 |         1 |        1 |
> | tpcds        | time_dim               |      116 |             1 |                 |         1 |        1 |
> | tpcds        | reason                 |      118 |             1 |                 |         1 |        1 |
> | tpcds        | income_band            |      120 |             1 |                 |         1 |        1 |
> | tpcds        | item                   |      122 |             1 |                 |         1 |        1 |
> | tpcds        | store                  |      124 |             1 |                 |         1 |        1 |
> | tpcds        | call_center            |      126 |             1 |                 |         1 |        1 |
> | tpcds        | customer               |      128 |             1 |                 |         1 |        1 |
> | tpcds        | web_site               |      130 |             1 |                 |         1 |        1 |
> | tpcds        | store_returns          |      132 |             1 |                 |         1 |        1 |
> | tpcds        | household_demographics |      134 |             1 |                 |         1 |        1 |
> | tpcds        | web_page               |      136 |             1 |                 |         1 |        1 |
> | tpcds        | promotion              |      138 |             1 |                 |         1 |        1 |
> | tpcds        | catalog_page           |      140 |             1 |                 |         1 |        1 |
> | tpcds        | inventory              |      142 |             1 |                 |         1 |        1 |
> | tpcds        | catalog_returns        |      144 |             1 |                 |         1 |        1 |
> | tpcds        | web_returns            |      146 |             1 |                 |         1 |        1 |
> | tpcds        | web_sales              |      148 |             1 |                 |         1 |        1 |
> | tpcds        | catalog_sales          |      150 |             1 |                 |         1 |        1 |
> | tpcds        | store_sales            |      152 |             1 |                 |         1 |        1 |
> +--------------+------------------------+----------+---------------+-----------------+-----------+----------+
> 34 rows in set (0.02 sec)
> 
> MySQL [test]> SELECT year, month, SUM(profit) AS profit from bank GROUP BY year, month WITH ROLLUP ORDER BY year desc, month desc;
> ERROR 1815 (HY000): Internal : Can't find a proper physical plan for this query
> ```

Checked, the v7.6 has some limitations about unionAll OP, where it's not supported to be pushed down to tiflash
check the detail code below if you are interested, that why normal table works
<img width="909" alt="image" src="https://github.com/pingcap/tidb/assets/15825830/9f053d6c-90f4-46ef-9f00-3bbf8440dcb1">

**Comment by winoros** [comment] 2024-03-18 20:23
@7yyo From the above discussion, i think you can try to analyze the table first.

It should be related to https://github.com/pingcap/tidb/issues/44262 and before https://github.com/pingcap/tidb/pull/51405, we can only fix it when there's at least one partition already analyzed The pull 51405 fixed the case when there is no global stats.

**Comment by AilinKid** [comment] 2024-03-19 03:05
@7yyo @akuluasan the conclusion is like the above, I'm gonna close this issue, thx

**Closed by AilinKid** 2024-03-19 03:05 UTC
Labels: type/bug, sig/planner
