### ISSUE TITLE
loader's  problem

### ISSUE THREAD

**Issue by April-Chan** [pingcap/tidb#6769] opened 2018-06-06 07:45 UTC
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
I have a TiDB cluster(3 TiDB nodes，3 PD nodes，3 TiKV nodes，CentOS 7.4）
I execute SQL in TIDB-Server like this:
>drop table table_name  (This is a big table , almost 400G ) 
then it works ,the table has been deleted, But TiKV storage decrease not immediately，it takes 4~5hours
then I use mydumper/loader tools to load this table again

2. What did you expect to see?
I see the load process running well

3. What did you see instead?
But the tidb log always has this message:
"region_cache.go:470: [info] drop regions of store 1 from cache due to request fail, err: rpc error: code = DeadlineExceeded desc = context deadline exceeded"

Is this a normal output?

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
2.0

**Comment by April-Chan** [comment] 2018-06-06 07:48
After I drop this table , TiKV storage has decreased , but regions count  never change

**Comment by zhexuany** [comment] 2018-06-07 03:13
@April-Chan 

 Thanks for using `TiDB`. 

When you delete table or say data from `TiDB`, it only marked as deleted which is known as logical delete. Physical delete need wait till next `GC` cycle. 

As of your question, Is it normal printing that log? The answer is yes. That log level is info, and will print something out when [OnRequestFail](https://github.com/pingcap/tidb/blob/master/store/tikv/region_cache.go#L453) being called.

**Comment by coocood** [comment] 2018-06-07 03:15
@April-Chan 
Can you provide the `iostat` result during loading with loader?
If the disk is too busy, this error can happen.

**Comment by April-Chan** [comment] 2018-06-07 07:06
@zhexuany @coocood 

Thanks for your help.
My loading process has been carried out for 28 hours and I have almost 66% done.
The following content is TiKV's io status.
-------------------------------------------------------------------------------------------------------------------
avg-cpu:  %user   %nice %system %iowait  %steal   %idle
          17.05    0.00    3.92   37.95    0.09   40.99

Device:         rrqm/s   wrqm/s     r/s     w/s    rMB/s    wMB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
vda               0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00
vdb               0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00
vdc               1.00   141.50  226.00  363.50    36.67   129.95   578.86    42.01   64.63   53.73   71.40   1.70 100.00

**Comment by coocood** [comment] 2018-06-11 11:23
@April-Chan 
Is the disk HDD or SSD.
If it is HDD, as we are not optimized for it, we can not provide any help.

**Comment by EamonZhang** [comment] 2018-11-14 17:11
+1

**Comment by shenli** [comment] 2018-11-14 17:20
@EamonZhang This is usually caused by the performance of your TiKV instance hardware. Please check our [hardware recommendation](https://github.com/pingcap/docs/blob/master/op-guide/recommendation.md).

**Comment by EamonZhang** [comment] 2018-11-14 19:44
@shenli  TiKV use RAID10 composed of four SSDs
from promethues view i/o util less than 7%
this cause error  2013, 'Lost connection to MySQL server during query'

**Comment by tiancaiamao** [comment] 2018-11-15 02:46
It's possibility that the 'Lost connection to MySQL server during query'  is  caused by other reason.
Would you please check the TiDB log and provide the `[error]` message ?

**Comment by tiancaiamao** [comment] 2018-11-15 02:48
Are you using loader to import data?
Did TiDB OOM at that time? Check the TiDB memory usage in grafana to verify that. @EamonZhang

**Comment by DorianZheng** [comment] 2018-11-15 02:56
@April-Chan Could you export the grafana view as PDF and send it to us, and TiDB's log, and TiKV's log and RocksDB's log. They are very helpful to investigate the problem. Maybe you can send them to my email zhengzhiquan@pingcap.com

**Comment by EamonZhang** [comment] 2018-11-16 00:58
@tiancaiamao

**Comment by tiancaiamao** [comment] 2018-11-16 02:42
Check TiDB log @EamonZhang 

> It's possibility that the 'Lost connection to MySQL server during query' is caused by other reason.
> Would you please check the TiDB log and provide the [error] message ?

**Comment by nullnotnil** [comment] 2020-07-30 00:11
I am going to close this issue as stale. Please feel free to re-open an issue if you have any further questions. Thanks!

**Closed by nullnotnil** 2020-07-30 00:11 UTC
Labels: type/enhancement
