### ISSUE TITLE
query is get the little number, but tidb returns the big more.

### ISSUE THREAD

**Issue by ljhmily** [pingcap/tidb#9091] opened 2019-01-16 09:06 UTC
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
i watn to delete my zabbix history data before timestamp 1544088416. 
so i execute select * from history where clock < 1544088416;
desc history;
+--------+---------------------+------+------+---------+-------+
| Field  | Type                | Null | Key  | Default | Extra |
+--------+---------------------+------+------+---------+-------+
| itemid | bigint(20) UNSIGNED | NO   | MUL  | NULL    |       |
| clock  | int(11)             | NO   | MUL  | 0       |       |
| value  | double(16,4)        | NO   |      | 0.0000  |       |
| ns     | int(11)             | NO   |      | 0       |       |
+--------+---------------------+------+------+---------+-------+
4 rows in set (0.00 sec)

2. What did you expect to see?
query return the results that clock < 1544088416.

3. What did you see instead?
tidb returns all clock > 1544088416.
mysql> select * from history where 'clock' < 1544088416 limit 10;
+---------+------------+-----------+-----------+
| itemid  | clock      | value     | ns        |
+---------+------------+-----------+-----------+
| 1293092 | 1544095243 | 5599.4671 | 331848192 |
| 1293095 | 1544095243 | 4656.8884 | 336142808 |
| 1293090 | 1544095243 | 4895.1658 | 340195103 |
| 1292775 | 1544095244 |    0.0000 | 345638243 |
| 1292771 | 1544095244 |    0.0000 | 350072583 |
| 1292776 | 1544095244 |    0.0000 | 354274111 |
| 1292780 | 1544095244 |    0.0000 | 358440530 |
| 1292781 | 1544095245 |    0.0000 | 364052713 |
| 1292802 | 1544095245 |    0.1700 | 381531368 |
| 1292803 | 1544095245 |    0.3300 | 397391908 |
+---------+------------+-----------+-----------+
10 rows in set, 1 warning (0.04 sec)
select 1544095243 - 1544088416;
+-------------------------+
| 1544095243 - 1544088416 |
+-------------------------+
|                    6827 |
+-------------------------+

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
Release Version: v2.1.0
Git Commit Hash: 08f0168a6caea0280d6157e5be69f2dc6fd0d5b3
Git Branch: release-2.1
UTC Build Time: 2018-11-30 11:39:09
GoVersion: go version go1.11.2 linux/amd64
Race Enabled: false
TiKV Min Version: 2.1.0-alpha.1-ff3dd160846b7d1aed9079c389fc188f7f5ea13e
Check Table Before Drop: false

**Comment by eurekaka** [comment] 2019-01-16 09:20
@ljhmily Thanks for your report.

Here is the minimal repro on master branch:
```
mysql> create table history(clock int(11));
Query OK, 0 rows affected (0.12 sec)

mysql> insert into history values(1544095243),(1544095243),(1544095243);
Query OK, 3 rows affected (0.00 sec)
Records: 3  Duplicates: 0  Warnings: 0

mysql> select * from history where 'clock' < 1544088416 limit 1;
+------------+
| clock      |
+------------+
| 1544095243 |
+------------+
1 row in set, 1 warning (0.00 sec)

mysql> show warnings;
+---------+------+----------------+
| Level   | Code | Message        |
+---------+------+----------------+
| Warning | 1265 | Data Truncated |
+---------+------+----------------+
1 row in set (0.00 sec)
```

Looks like it is a bug caused by overflow, we will fix this soon.

**Comment by eurekaka** [comment] 2019-01-16 09:32
@ljhmily Oh, it is not a bug, the result is caused by your SQL, you should use:
```
mysql> select * from history where clock < 1544088416 limit 1;
Empty set (0.00 sec)
```
instead of:
```
mysql> select * from history where 'clock' < 1544088416 limit 1;
+------------+
| clock      |
+------------+
| 1544095243 |
+------------+
1 row in set, 1 warning (0.00 sec)
```
since the result is as expected, close this issue.

**Closed** 2019-01-16 09:32 UTC
Labels: type/bug
