### ISSUE TITLE
HEX(LPAD) behavior doesn't match with both 5.7 and 8.0 

### ISSUE THREAD

**Issue by Alkaagr81** [pingcap/tidb#30728] opened 2021-12-14 23:19 UTC
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```sql
CREATE TABLE t1(c1 VARCHAR(10));
INSERT INTO t1 VALUES ('Alaska');
SELECT HEX(LPAD('', 42, REPLACE(COMPRESS(42),c1,''))) FROM t1;
SELECT HEX(LPAD('', 42, SUBSTRING_INDEX(COMPRESS(42),c1,1))) FROM t1;
SELECT HEX(LPAD('', 42, TRIM(x'ffff' FROM c1))) FROM t1;
SELECT LPAD('', 42, REPLACE(c1, 'las', x'ff')) FROM t1;
SELECT HEX(SUBSTRING_INDEX(_utf8mb4 x'41F09F8DA3F09F8DA3' , x'f0', 2)) FROM t1;
SELECT TRIM(BOTH x'f0' FROM _utf8mb4 x'F09F8DA3F09F8DA3');

```
### 2. What did you expect to see? (Required)
```sql

mysql> CREATE TABLE t1(c1 VARCHAR(10));
Query OK, 0 rows affected (0.01 sec)

mysql> INSERT INTO t1 VALUES ('Alaska');
Query OK, 1 row affected (0.00 sec)

mysql> SELECT HEX(LPAD('', 42, REPLACE(COMPRESS(42),c1,''))) FROM t1;
+--------------------------------------------------------------------------------------+
| HEX(LPAD('', 42, REPLACE(COMPRESS(42),c1,'')))                                       |
+--------------------------------------------------------------------------------------+
| 02000000789C33310200009C006702000000789C33310200009C006702000000789C33310200009C0067 |
+--------------------------------------------------------------------------------------+
1 row in set (0.00 sec)

mysql> SELECT HEX(LPAD('', 42, SUBSTRING_INDEX(COMPRESS(42),c1,1))) FROM t1;
+--------------------------------------------------------------------------------------+
| HEX(LPAD('', 42, SUBSTRING_INDEX(COMPRESS(42),c1,1)))                                |
+--------------------------------------------------------------------------------------+
| 02000000789C33310200009C006702000000789C33310200009C006702000000789C33310200009C0067 |
+--------------------------------------------------------------------------------------+
1 row in set (0.00 sec)

mysql> SELECT HEX(LPAD('', 42, TRIM(x'ffff' FROM c1))) FROM t1;
ERROR 3854 (HY000): Cannot convert string '\xFF\xFF' from binary to utf8mb4
mysql> SELECT LPAD('', 42, REPLACE(c1, 'las', x'ff')) FROM t1;
ERROR 3854 (HY000): Cannot convert string '\xFF' from binary to utf8mb4
mysql> SELECT HEX(SUBSTRING_INDEX(_utf8mb4 x'41F09F8DA3F09F8DA3' , x'f0', 2)) FROM t1;
ERROR 3854 (HY000): Cannot convert string '\xF0' from binary to utf8mb4
mysql> SELECT TRIM(BOTH x'f0' FROM _utf8mb4 x'F09F8DA3F09F8DA3');
ERROR 3854 (HY000): Cannot convert string '\xF0' from binary to utf8mb4


```
### 3. What did you see instead (Required)
```sql

mysql> CREATE TABLE t1(c1 VARCHAR(10));
Query OK, 0 rows affected (0.07 sec)

mysql> INSERT INTO t1 VALUES ('Alaska');
Query OK, 1 row affected (0.06 sec)

mysql> SELECT HEX(LPAD('', 42, REPLACE(COMPRESS(42),c1,''))) FROM t1;
+--------------------------------------------------------------------------------------+
| HEX(LPAD('', 42, REPLACE(COMPRESS(42),c1,'')))                                       |
+--------------------------------------------------------------------------------------+
| 02000000789C323102040000FFFF009C006702000000789C323102040000FFFF009C006702000000789C |
+--------------------------------------------------------------------------------------+
1 row in set (0.00 sec)

mysql> SELECT HEX(LPAD('', 42, SUBSTRING_INDEX(COMPRESS(42),c1,1))) FROM t1;
+--------------------------------------------------------------------------------------+
| HEX(LPAD('', 42, SUBSTRING_INDEX(COMPRESS(42),c1,1)))                                |
+--------------------------------------------------------------------------------------+
| 02000000789C323102040000FFFF009C006702000000789C323102040000FFFF009C006702000000789C |
+--------------------------------------------------------------------------------------+
1 row in set (0.00 sec)

mysql> SELECT HEX(LPAD('', 42, TRIM(x'ffff' FROM c1))) FROM t1;
+--------------------------------------------------------------------------------------+
| HEX(LPAD('', 42, TRIM(x'ffff' FROM c1)))                                             |
+--------------------------------------------------------------------------------------+
| 416C61736B61416C61736B61416C61736B61416C61736B61416C61736B61416C61736B61416C61736B61 |
+--------------------------------------------------------------------------------------+
1 row in set (0.01 sec)

mysql> SELECT LPAD('', 42, REPLACE(c1, 'las', x'ff')) FROM t1;
+--------------------------------------------+
| LPAD('', 42, REPLACE(c1, 'las', x'ff'))    |
+--------------------------------------------+
| A?kaA?kaA?kaA?kaA?kaA?kaA?kaA?kaA?kaA?kaA?            |
+--------------------------------------------+
1 row in set (0.00 sec)

mysql> SELECT HEX(SUBSTRING_INDEX(_utf8mb4 x'41F09F8DA3F09F8DA3' , x'f0', 2)) FROM t1;
+-----------------------------------------------------------------+
| HEX(SUBSTRING_INDEX(_utf8mb4 x'41F09F8DA3F09F8DA3' , x'f0', 2)) |
+-----------------------------------------------------------------+
| 41F09F8DA3                                                      |
+-----------------------------------------------------------------+
1 row in set (0.00 sec)

mysql> SELECT TRIM(BOTH x'f0' FROM _utf8mb4 x'F09F8DA3F09F8DA3');
+----------------------------------------------------+
| TRIM(BOTH x'f0' FROM _utf8mb4 x'F09F8DA3F09F8DA3') |
+----------------------------------------------------+
| ???🍣                                                   |
+----------------------------------------------------+
1 row in set (0.00 sec)


```
### 4. What is your TiDB version? (Required)

```sql
| Release Version: v5.3.0
Edition: Community
Git Commit Hash: 4a1b2e9fe5b5afb1068c56de47adb07098d768d6
Git Branch: heads/refs/tags/v5.3.0
UTC Build Time: 2021-11-24 13:31:24
GoVersion: go1.16.5
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false |
```

**Comment by aytrack** [comment] 2021-12-15 02:43
I can't reproduce 3-6 in master(
```sql
MySQL root@127.0.0.1:test>  SELECT HEX(LPAD('', 42, TRIM(x'ffff' FROM c1))) FROM t1;
(3854, "Cannot convert string 'FFFF' from binary to utf8mb4")
MySQL root@127.0.0.1:test> SELECT LPAD('', 42, REPLACE(c1, 'las', x'ff')) FROM t1;
(3854, "Cannot convert string 'FF' from binary to utf8mb4")
MySQL root@127.0.0.1:test> SELECT HEX(SUBSTRING_INDEX(_utf8mb4 x'41F09F8DA3F09F8DA3' , x'f0', 2)) FROM t1;
(3854, "Cannot convert string 'F0' from binary to utf8mb4")
MySQL root@127.0.0.1:test> SELECT TRIM(BOTH x'f0' FROM _utf8mb4 x'F09F8DA3F09F8DA3');
(3854, "Cannot convert string 'F0' from binary to utf8mb4")
MySQL root@127.0.0.1:test> select tidb_version()\G
***************************[ 1. row ]***************************
tidb_version() | Release Version: v5.4.0-alpha-395-gb62674529
Edition: Community
Git Commit Hash: b626745299655cc4894160d700b19f7838f93d38
Git Branch: master
UTC Build Time: 2021-12-14 07:26:42
GoVersion: go1.17.2
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
```
for 1 and 2, IMOH it's more reasonable in tidb
tidb
```sql
-- case 1
MySQL root@127.0.0.1:test> select REPLACE(COMPRESS(42),c1,'') from t1;
+----------------------------------------+
| REPLACE(COMPRESS(42),c1,'')            |
+----------------------------------------+
| 0x02000000789c323102040000ffff009c0067 |
+----------------------------------------+

1 row in set
Time: 0.009s
MySQL root@127.0.0.1:test> select lpad('', 42, 0x02000000789c323102040000ffff009c0067);
+----------------------------------------------------------------------------------------+
| lpad('', 42, 0x02000000789c323102040000ffff009c0067)                                   |
+----------------------------------------------------------------------------------------+
| 0x02000000789c323102040000ffff009c006702000000789c323102040000ffff009c006702000000789c |
+----------------------------------------------------------------------------------------+

1 row in set
Time: 0.006s
MySQL root@127.0.0.1:test> select hex(0x02000000789c323102040000ffff009c006702000000789c323102040000ffff009c006702000000789c);
+---------------------------------------------------------------------------------------------+
| hex(0x02000000789c323102040000ffff009c006702000000789c323102040000ffff009c006702000000789c) |
+---------------------------------------------------------------------------------------------+
| 02000000789C323102040000FFFF009C006702000000789C323102040000FFFF009C006702000000789C        |
+---------------------------------------------------------------------------------------------+

1 row in set
Time: 0.008s
MySQL root@127.0.0.1:test> select hex(lpad('', 42, 0x02000000789c323102040000ffff009c0067));
+--------------------------------------------------------------------------------------+
| hex(lpad('', 42, 0x02000000789c323102040000ffff009c0067))                            |
+--------------------------------------------------------------------------------------+
| 02000000789C323102040000FFFF009C006702000000789C323102040000FFFF009C006702000000789C |
+--------------------------------------------------------------------------------------+

1 row in set
Time: 0.009s
MySQL root@127.0.0.1:test> select hex(lpad('', 42, REPLACE(COMPRESS(42),c1,''))) from t1;
+--------------------------------------------------------------------------------------+
| hex(lpad('', 42, REPLACE(COMPRESS(42),c1,'')))                                       |
+--------------------------------------------------------------------------------------+
| 02000000789C323102040000FFFF009C006702000000789C323102040000FFFF009C006702000000789C |
+--------------------------------------------------------------------------------------+

-- case2
MySQL root@127.0.0.1:test> select SUBSTRING_INDEX(COMPRESS(42),c1,1) from t1;
+----------------------------------------+
| SUBSTRING_INDEX(COMPRESS(42),c1,1)     |
+----------------------------------------+
| 0x02000000789c323102040000ffff009c0067 |
+----------------------------------------+

1 row in set
Time: 0.008s
MySQL root@127.0.0.1:test> select lpad('', 42, 0x02000000789c323102040000ffff009c0067);
+----------------------------------------------------------------------------------------+
| lpad('', 42, 0x02000000789c323102040000ffff009c0067)                                   |
+----------------------------------------------------------------------------------------+
| 0x02000000789c323102040000ffff009c006702000000789c323102040000ffff009c006702000000789c |
+----------------------------------------------------------------------------------------+

1 row in set
Time: 0.009s
MySQL root@127.0.0.1:test> select hex(0x02000000789c323102040000ffff009c006702000000789c323102040000ffff009c006702
                       ->  000000789c);
+---------------------------------------------------------------------------------------------+
| hex(0x02000000789c323102040000ffff009c006702000000789c323102040000ffff009c006702000000789c) |
+---------------------------------------------------------------------------------------------+
| 02000000789C323102040000FFFF009C006702000000789C323102040000FFFF009C006702000000789C        |
+---------------------------------------------------------------------------------------------+

1 row in set
Time: 0.008s
MySQL root@127.0.0.1:test> SELECT HEX(LPAD('', 42, SUBSTRING_INDEX(COMPRESS(42),c1,1))) FROM t1;
+--------------------------------------------------------------------------------------+
| HEX(LPAD('', 42, SUBSTRING_INDEX(COMPRESS(42),c1,1)))                                |
+--------------------------------------------------------------------------------------+
| 02000000789C323102040000FFFF009C006702000000789C323102040000FFFF009C006702000000789C |
+--------------------------------------------------------------------------------------+


```
mysql 8.0.26
```sql
MySQL root@172.16.5.103:test> select REPLACE(COMPRESS(42),c1,'') from t1;
+--------------------------------+
| REPLACE(COMPRESS(42),c1,'')    |
+--------------------------------+
| 0x02000000789c33310200009c0067 |
+--------------------------------+

1 row in set
Time: 0.058s
MySQL root@172.16.5.103:test> select lpad('', 42, 0x02000000789c323102040000ffff009c0067);
+----------------------------------------------------------------------------------------+
| lpad('', 42, 0x02000000789c323102040000ffff009c0067)                                   |
+----------------------------------------------------------------------------------------+
| 0x02000000789c323102040000ffff009c006702000000789c323102040000ffff009c006702000000789c |
+----------------------------------------------------------------------------------------+

1 row in set
Time: 0.058s
MySQL root@172.16.5.103:test> select hex(0x02000000789c323102040000ffff009c006702000000789c323102040000ffff009c006702000000789c);
+---------------------------------------------------------------------------------------------+
| hex(0x02000000789c323102040000ffff009c006702000000789c323102040000ffff009c006702000000789c) |
+---------------------------------------------------------------------------------------------+
| 02000000789C323102040000FFFF009C006702000000789C323102040000FFFF009C006702000000789C        |
+---------------------------------------------------------------------------------------------+

1 row in set
Time: 0.056s
MySQL root@172.16.5.103:test> select hex(lpad('', 42, REPLACE(COMPRESS(42),c1,''))) from t1;
+--------------------------------------------------------------------------------------+
| hex(lpad('', 42, REPLACE(COMPRESS(42),c1,'')))                                       |
+--------------------------------------------------------------------------------------+
| 02000000789C33310200009C006702000000789C33310200009C006702000000789C33310200009C0067 |
+--------------------------------------------------------------------------------------+

1 row in set
Time: 0.054s

-- case2
MySQL root@172.16.5.103:test> select SUBSTRING_INDEX(COMPRESS(42),c1,1) from t1;
+------------------------------------+
| SUBSTRING_INDEX(COMPRESS(42),c1,1) |
+------------------------------------+
| 0x02000000789c33310200009c0067     |
+------------------------------------+

1 row in set
Time: 0.053s
MySQL root@172.16.5.103:test> select lpad('', 42, 0x02000000789c323102040000ffff009c0067);
+----------------------------------------------------------------------------------------+
| lpad('', 42, 0x02000000789c323102040000ffff009c0067)                                   |
+----------------------------------------------------------------------------------------+
| 0x02000000789c323102040000ffff009c006702000000789c323102040000ffff009c006702000000789c |
+----------------------------------------------------------------------------------------+

1 row in set
Time: 0.049s
MySQL root@172.16.5.103:test> select hex(0x02000000789c323102040000ffff009c006702000000789c323102040000ffff009c006702000000789c);
+---------------------------------------------------------------------------------------------+
| hex(0x02000000789c323102040000ffff009c006702000000789c323102040000ffff009c006702000000789c) |
+---------------------------------------------------------------------------------------------+
| 02000000789C323102040000FFFF009C006702000000789C323102040000FFFF009C006702000000789C        |
+---------------------------------------------------------------------------------------------+

1 row in set
Time: 0.084s
MySQL root@172.16.5.103:test> SELECT HEX(LPAD('', 42, SUBSTRING_INDEX(COMPRESS(42),c1,1))) FROM t1;
+--------------------------------------------------------------------------------------+
| HEX(LPAD('', 42, SUBSTRING_INDEX(COMPRESS(42),c1,1)))                                |
+--------------------------------------------------------------------------------------+
| 02000000789C33310200009C006702000000789C33310200009C006702000000789C33310200009C0067 |
+--------------------------------------------------------------------------------------+


```

**Comment by Defined2014** [comment] 2022-01-05 06:59
add some other cases

TiDB
```mysql
mysql> create table t (h enum('a一','b二','c三','d四') default 'c三');
Query OK, 0 rows affected (0.00 sec)

mysql> insert into t values ('a一');
Query OK, 1 row affected (0.00 sec)

mysql> select lpad(h, 5, 0xE4B880) from t;
+----------------------+
| lpad(h, 5, 0xE4B880) |
+----------------------+
| 一一一a一            |
+----------------------+
1 row in set (0.00 sec)
```

MySQL 8.0.27
```
mysql> select lpad(h, 5, 0xE4B880) from t;
+----------------------+
| lpad(h, 5, 0xE4B880) |
+----------------------+
| 一a一                |
+----------------------+
1 row in set (0.00 sec)
```

**Comment by solotzg** [comment] 2022-05-23 10:14
For current master branch:

```
MySQL [test]> CREATE TABLE t1(c1 VARCHAR(10));
Query OK, 0 rows affected (0.08 sec)

MySQL [test]> INSERT INTO t1 VALUES ('Alaska');
Query OK, 1 row affected (0.00 sec)

MySQL [test]> SELECT HEX(LPAD('', 42, REPLACE(COMPRESS(42),c1,''))) FROM t1;
+--------------------------------------------------------------------------------------+
| HEX(LPAD('', 42, REPLACE(COMPRESS(42),c1,'')))                                       |
+--------------------------------------------------------------------------------------+
| 02000000789C323102040000FFFF009C006702000000789C323102040000FFFF009C006702000000789C |
+--------------------------------------------------------------------------------------+
1 row in set (0.00 sec)

MySQL [test]> SELECT HEX(LPAD('', 42, SUBSTRING_INDEX(COMPRESS(42),c1,1))) FROM t1;
+--------------------------------------------------------------------------------------+
| HEX(LPAD('', 42, SUBSTRING_INDEX(COMPRESS(42),c1,1)))                                |
+--------------------------------------------------------------------------------------+
| 02000000789C323102040000FFFF009C006702000000789C323102040000FFFF009C006702000000789C |
+--------------------------------------------------------------------------------------+
1 row in set (0.00 sec)

MySQL [test]> SELECT HEX(LPAD('', 42, TRIM(x'ffff' FROM c1))) FROM t1;
ERROR 3854 (HY000): Cannot convert string '\xFF\xFF' from binary to utf8mb4
MySQL [test]> SELECT LPAD('', 42, REPLACE(c1, 'las', x'ff')) FROM t1;
ERROR 3854 (HY000): Cannot convert string '\xFF' from binary to utf8mb4
MySQL [test]> SELECT HEX(SUBSTRING_INDEX(_utf8mb4 x'41F09F8DA3F09F8DA3' , x'f0', 2)) FROM t1;
ERROR 3854 (HY000): Cannot convert string '\xF0' from binary to utf8mb4
MySQL [test]> SELECT TRIM(BOTH x'f0' FROM _utf8mb4 x'F09F8DA3F09F8DA3');
ERROR 3854 (HY000): Cannot convert string '\xF0' from binary to utf8mb4
MySQL [test]> select version();
+----------------------------+
| version()                  |
+----------------------------+
| 5.7.25-TiDB-v6.1.0-nightly |
+----------------------------+
1 row in set (0.00 sec)
```

The root cause is that the result of expression `COMPRESS()` is different with mysql.

```
MySQL [test]> SELECT LENGTH(COMPRESS(c1)) from t1;
+----------------------+
| LENGTH(COMPRESS(c1)) |
+----------------------+
|                   22 |
+----------------------+
1 row in set (0.00 sec)
```
but for mysql
```
mysql> SELECT LENGTH(COMPRESS(c1)) from t1;
+----------------------+
| LENGTH(COMPRESS(c1)) |
+----------------------+
|                   18 |
+----------------------+
1 row in set (0.00 sec)

mysql> select version();
+-----------+
| version() |
+-----------+
| 8.0.29    |
+-----------+
1 row in set (0.00 sec)
```

**Comment by wshwsh12** [comment] 2022-07-09 13:29
I don't think the `compress()` function needs to be exactly the same as the mysql result, but `compress()` is compatible with the zlib format. So I don't think this issue is a bug.
The reasons are as follows:
1. The current tidb uses golang's zlib library, which only guarantees that the result is compatible with the zlib format, and does not guarantee that all bytes in it are exactly the same.
2. Both mysql results and tidb results can be correctly uncompressed
3. Implementation details may be different for the different zlib library, or different version of the same zlib library. The results of running zlib with different running parameters(compress_level, flush_mode and so on) and with different versions of zlib may be different.
4. If we want to be completely consistent with mysql, we need to find which zlib library and version mysql uses, and use cgo to directly call the relevant library.

**Comment by zanmato1984** [comment] 2022-07-13 09:23
> I don't think the `compress()` function needs to be exactly the same as the mysql result, but `compress()` is compatible with the zlib format. So I don't think this issue is a bug. The reasons are as follows:
> 
> 1. The current tidb uses golang's zlib library, which only guarantees that the result is compatible with the zlib format, and does not guarantee that all bytes in it are exactly the same.
> 2. Both mysql results and tidb results can be correctly uncompressed
> 3. Implementation details may be different for the different zlib library, or different version of the same zlib library. The results of running zlib with different running parameters(compress_level, flush_mode and so on) and with different versions of zlib may be different.
> 4. If we want to be completely consistent with mysql, we need to find which zlib library and version mysql uses, and use cgo to directly call the relevant library.

+1.

According to MySQL doc https://dev.mysql.com/doc/refman/8.0/en/encryption-functions.html#function_compress, there is no specific description of how the compression should be conducted, so I would think this as an implementation detail.

I'm closing it as we don't consider it a bug. Feel free to reopen if anyone has other thoughts.

**Closed by zanmato1984** 2022-07-13 09:23 UTC
Labels: type/bug, sig/execution, severity/major, affects-4.0, affects-5.0, affects-5.1, affects-5.2, affects-5.3, affects-5.4, affects-6.0, affects-6.1
