### ISSUE TITLE
Lift the parser limitation on windows function keyword

### ISSUE THREAD

**Issue by dbsid** [pingcap/tidb#24756] opened 2021-05-19 09:42 UTC
## Bug Report

With window function enabled, below query from Jira failed as the LEAD column is the same as the windows function name LEAD(). On the production db, the database is forced to disable window function, other application can not use window function by default, need to lift the parser limitation on the window function. no such issue for builtin functions.
```
SELECT ID, pname, URL, LEAD, DESCRIPTION, pkey, pcounter, ASSIGNEETYPE, AVATAR, ORIGINALKEY, PROJECTTYPE FROM project ORDER BY pname (You have an error in your SQL syntax; check the manual that corresponds to your TiDB version for the right syntax to use line 1 column 28 near ", DESCRIPTION, pkey, pcounter, ASSIGNEETYPE, AVATAR, ORIGINALKEY, PROJECTTYPE FROM project ORDER BY pname
```
Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
tidb> create table t1(a int);
Query OK, 0 rows affected (0.09 sec)

tidb> select * from (select max(a) as 'lead' from t1) t where lead = 1;
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your TiDB version for the right syntax to use line 1 column 62 near "= 1"

tidb> select * from (select max(a) as `lead` from t1) t where `lead` = 1;
Empty set (0.00 sec)

tidb> select * from (select max(a) as 'max' from t1) t where max = 1;
Empty set (0.00 sec)
```
### 2. What did you expect to see? (Required)
below sql can execute successfully.
select * from (select max(a) as 'lead' from t1) t where lead = 1;

### 3. What did you see instead (Required)
syntax error

### 4. What is your TiDB version? (Required)

```
| Release Version: v4.0.0-beta.2-2487-g70f7884
Edition: Community
Git Commit Hash: 70f78847f463d9f1f4f6a8f329749762a71033ed
Git Branch: release-5.0-734084fa2bf2
UTC Build Time: 2021-05-10 14:50:14
GoVersion: go1.16
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false |
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.03 sec)
```

**Comment by ChenPeng2013** [comment] 2021-05-19 11:39
MySQL 8.0.21
```
mysql> drop table if exists t1;
Query OK, 0 rows affected (0.01 sec)

mysql> create table t1(a int);
Query OK, 0 rows affected (0.01 sec)

mysql> select * from (select max(a) as 'lead' from t1) t where lead = 1;
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '= 1' at line 1
mysql> select * from (select max(a) as `lead` from t1) t where `lead` = 1;
Empty set (0.00 sec)

mysql> select * from (select max(a) as 'max' from t1) t where max = 1;
Empty set (0.00 sec)

```

**Comment by aytrack** [comment] 2021-05-25 09:46
MySQL 8.0.23 has the same result, this may not a bug 
@XuHuaiyu  PTAL~

**Comment by jebter** [comment] 2024-06-06 02:31
The issue has not been updated for too long, so I will close it. If there are any updates, you can reopen it.

**Closed by jebter** 2024-06-06 02:31 UTC
Labels: type/question, sig/execution
