### ISSUE TITLE
clear available for tiflash when flashback a table

### ISSUE THREAD

**Issue by marsishandsome** [pingcap/tidb#15590] opened 2020-03-23 12:46 UTC
## Feature Request

**Describe the feature you'd like:**

 `available` should be `0` when after calling `flashback` 

```
create table t (c1 int, c2 varchar(64));
insert into t values(1, "abc");
ALTER TABLE t SET TIFLASH REPLICA 1;
drop table t;
flashback table t to t2;
select * from  information_schema.tiflash_replica;
```

![image](https://user-images.githubusercontent.com/5574887/77374679-5964d300-6da6-11ea-9430-7bf2ce5e661f.png)

**Comment by zz-jason** [comment] 2020-07-22 05:40
IMO, it's more like a bug other than a feature request.

**Comment by zz-jason** [comment] 2020-07-22 05:43
There are two options:

1. flashback the tiflash replicas
2. do not flashback the tiflash replicas, correct the tiflash replica information displayed in `information_schema.tiflash_replica` as this issue originally requested.

@bb7133 @ilovesoup PTAL

**Comment by zanmato1984** [comment] 2020-07-22 15:22
We studied this problem deeper back then and found this is not the root cause. This problem has been thoroughly fixed in these PRs based this [design](https://docs.google.com/document/d/1arw-ahHhkfInogRs6B9OOS6paD1Ap6dhfPYW4zgbIpk/edit):
https://github.com/pingcap/tics/pull/599
https://github.com/pingcap/tidb/pull/15699

So in a word, this issue is no long valid. We can close it.
@marsishandsome @zz-jason

**Closed** 2020-08-28 04:13 UTC
Labels: feature/discussing, type/feature-request
