### ISSUE TITLE
Possible performance issue when partition number is large

### ISSUE THREAD

**Issue by zhangjinpeng1987** [pingcap/tidb#13485] opened 2019-11-15 02:56 UTC
https://github.com/pingcap/tidb/blob/master/planner/core/logical_plan_builder.go#L2456 will iterator all partitions for each statement, if the statement is simple and the partition number is  large like 1024 the cost here  is not trivial.

**Comment by nullnotnil** [comment] 2020-08-06 15:53
Should this be closed as a duplicate of https://github.com/pingcap/tidb/issues/18548 ?

**Comment by qw4990** [comment] 2021-04-22 11:42
> Should this be closed as a duplicate of #18548 ?

Yes, this issue is duplicated with https://github.com/pingcap/tidb/issues/18548;

**Closed by qw4990** 2021-04-22 11:42 UTC
Labels: type/performance
