### ISSUE TITLE
`make gotest` failed on release-4.0

### ISSUE THREAD

**Issue by aytrack** [pingcap/tidb#29977] opened 2021-11-22 03:24 UTC
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
in ci https://ci.pingcap.net/blue/organizations/jenkins/tidb_ghpr_coverage/detail/tidb_ghpr_coverage/1263/pipeline
```bash
2021-11-20T01:06:58.850Z] Test args: [test -covermode=count -coverprofile=profile.coverprofile -outputdir=/home/jenkins/agent/workspace/tidb_ghpr_coverage/go/src/github.com/pingcap/tidb/tests/graceshutdown/ ./tests/graceshutdown -coverpkg=./...]

[2021-11-20T01:06:58.850Z] 2021/11/20 09:06:58 go: directory tests/graceshutdown is outside main module

[2021-11-20T01:06:58.850Z] 2021/11/20 09:06:58 ERROR:exit status 1

[2021-11-20T01:07:00.226Z] make: *** [gotest] Error 1

script returned exit code 2
```

**Comment by hawkingrei** [comment] 2021-11-25 14:05
it needs more log and information to discover the cause.

**Comment by bb7133** [comment] 2021-12-07 05:20
Close this issue since it cannot be reproduced.

**Closed by bb7133** 2021-12-07 05:20 UTC
Labels: type/bug, component/test, sig/sql-infra, severity/major, needs-more-info
