### ISSUE TITLE
runtime error: index out of range [5] with length 5

### ISSUE THREAD

**Issue by ChenPeng2013** [pingcap/tidb#28745] opened 2021-10-12 02:40 UTC
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

lastSQL="delete from partition table", i don't find the reproduce step

### 3. What did you see instead (Required)
runtime error: index out of range [5] with length 5
```
goroutine 85543875 [running]:
github.com/pingcap/tidb/server.(*clientConn).Run.func1(0x41e3890, 0xc02be21440, 0xc0467bed80)
	/home/jenkins/agent/workspace/build_tidb_multi_branch_master/go/src/github.com/pingcap/tidb/server/conn.go:918 +0xf5
panic(0x3a82180, 0xc0bf640510)
	/usr/local/go/src/runtime/panic.go:965 +0x1b9
github.com/pingcap/tidb/executor.(*ExecStmt).Exec.func1(0xc04e341ad0, 0xc060e4ca10, 0xc060e4c9f0)
	/home/jenkins/agent/workspace/build_tidb_multi_branch_master/go/src/github.com/pingcap/tidb/executor/adapter.go:338 +0x4d4
panic(0x3a82180, 0xc0bf640510)
	/usr/local/go/src/runtime/panic.go:965 +0x1b9
github.com/pingcap/tidb/util/chunk.MutRow.SetDatum(0xc08dfaebe0, 0x0, 0x5, 0x1, 0x49933, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/jenkins/agent/workspace/build_tidb_multi_branch_master/go/src/github.com/pingcap/tidb/util/chunk/mutrow.go:288 +0x76a
github.com/pingcap/tidb/util/chunk.MutRow.SetDatums(0xc08dfaebe0, 0x0, 0xc0b9626fc0, 0x6, 0x6)
	/home/jenkins/agent/workspace/build_tidb_multi_branch_master/go/src/github.com/pingcap/tidb/util/chunk/mutrow.go:282 +0x105
github.com/pingcap/tidb/table/tables.(*partitionedTable).locateHashPartition(0xc05c052b00, 0x4255118, 0xc04612de00, 0xc05a060780, 0xc0b9626fc0, 0x6, 0x6, 0x0, 0x0, 0x0)
	/home/jenkins/agent/workspace/build_tidb_multi_branch_master/go/src/github.com/pingcap/tidb/table/tables/partition.go:1064 +0x465
github.com/pingcap/tidb/table/tables.(*partitionedTable).locatePartition(0xc05c052b00, 0x4255118, 0xc04612de00, 0xc05a060780, 0xc0b9626fc0, 0x6, 0x6, 0x334785b, 0xc0bf7ec7e0, 0x0)
	/home/jenkins/agent/workspace/build_tidb_multi_branch_master/go/src/github.com/pingcap/tidb/table/tables/partition.go:924 +0x259
github.com/pingcap/tidb/table/tables.(*partitionedTable).RemoveRecord(0xc05c052b00, 0x4255118, 0xc04612de00, 0x42161f8, 0xc070c283b8, 0xc0b9626fc0, 0x6, 0x6, 0xc070c283b8, 0xc060e4c2b0)
	/home/jenkins/agent/workspace/build_tidb_multi_branch_master/go/src/github.com/pingcap/tidb/table/tables/partition.go:1167 +0x90
github.com/pingcap/tidb/executor.(*DeleteExec).removeRow(0xc0bf6aa1e0, 0x4255118, 0xc04612de00, 0x421b668, 0xc05c052b00, 0x42161f8, 0xc070c283b8, 0xc0b9626fc0, 0x6, 0x6, ...)
	/home/jenkins/agent/workspace/build_tidb_multi_branch_master/go/src/github.com/pingcap/tidb/executor/delete.go:208 +0xf5
github.com/pingcap/tidb/executor.(*DeleteExec).deleteOneRow(0xc0bf6aa1e0, 0x421b668, 0xc05c052b00, 0x4211320, 0xc0774be168, 0xc0b9626f00, 0xc0b9626fc0, 0x6, 0x6, 0xc060e4c3b0, ...)
	/home/jenkins/agent/workspace/build_tidb_multi_branch_master/go/src/github.com/pingcap/tidb/executor/delete.go:63 +0x105
github.com/pingcap/tidb/executor.(*DeleteExec).deleteSingleTableByChunk(0xc0bf6aa1e0, 0x41e3890, 0xc0bf1db5c0, 0x0, 0x2a5a8b6295bb00)
	/home/jenkins/agent/workspace/build_tidb_multi_branch_master/go/src/github.com/pingcap/tidb/executor/delete.go:113 +0x3c5
github.com/pingcap/tidb/executor.(*DeleteExec).Next(0xc0bf6aa1e0, 0x41e3890, 0xc0bf1db5c0, 0xc08dfae6e0, 0x0, 0xc060e4c500)
	/home/jenkins/agent/workspace/build_tidb_multi_branch_master/go/src/github.com/pingcap/tidb/executor/delete.go:51 +0x92
github.com/pingcap/tidb/executor.Next(0x41e3890, 0xc0bf1db5c0, 0x41e8878, 0xc0bf6aa1e0, 0xc08dfae6e0, 0x0, 0x0)
	/home/jenkins/agent/workspace/build_tidb_multi_branch_master/go/src/github.com/pingcap/tidb/executor/executor.go:286 +0x2de
github.com/pingcap/tidb/executor.(*ExecStmt).handleNoDelayExecutor(0xc04e341ad0, 0x41e3890, 0xc0bf1db5c0, 0x41e8878, 0xc0bf6aa1e0, 0x0, 0x0, 0x0, 0x0)
	/home/jenkins/agent/workspace/build_tidb_multi_branch_master/go/src/github.com/pingcap/tidb/executor/adapter.go:584 +0x33c
github.com/pingcap/tidb/executor.(*ExecStmt).handlePessimisticDML(0xc04e341ad0, 0x41e3890, 0xc0bf1db5c0, 0x41e8878, 0xc0bf6aa1e0, 0xc0515a2173a35850, 0x4a7c1153690c)
	/home/jenkins/agent/workspace/build_tidb_multi_branch_master/go/src/github.com/pingcap/tidb/executor/adapter.go:603 +0x185
github.com/pingcap/tidb/executor.(*ExecStmt).handleNoDelay(0xc04e341ad0, 0x41e3890, 0xc0bf1db5c0, 0x41e8878, 0xc0bf6aa1e0, 0x5fd5301, 0x41e3801, 0x0, 0x0, 0x0, ...)
	/home/jenkins/ag
```
### 4. What is your TiDB version? (Required)

```
Release Version: v5.3.0-alpha-248-g091ae3bde
Edition: Community
Git Commit Hash: 091ae3bde0a54b126f2f2ed275dd20b0986d74d3
Git Branch: master
UTC Build Time: 2021-09-29 08:42:56
GoVersion: go1.16.4
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: fals
```

**Comment by kennytm** [comment] 2021-10-15 04:55
do you have the schema of this hash-partitioned table though 👀

**Comment by mjonss** [comment] 2021-11-01 15:40
Some code reading according to the stack trace:
It is failing in chunk.MutRow.SetDatum() at line 1064 for a Hash partitioned table which has some kind of expression (not direct hash of an int column):
```golang
1062         evalBuffer := t.evalBufferPool.Get().(*chunk.MutRow)
1063         defer t.evalBufferPool.Put(evalBuffer)
1064         evalBuffer.SetDatums(r...)
```

Without knowing the partitioning expression and the query it is very hard to reproduce this bug. (Could it be a join? Union? Any select for update etc.)

Checking other issues for similar stack traces:
https://github.com/pingcap/tidb/issues/24262 - Range partitioned table, but `select for update`
https://github.com/pingcap/tidb/issues/28073 - Another issue for `select for update` (also see [this](https://github.com/pingcap/tidb/pull/28666#discussion_r727671014) comment in the proposed PR)

I think we should close this issue either as 'could not reproduce' or as a duplicate of #28073.

**Comment by bb7133** [comment] 2021-11-25 02:12
I will close this issue since it cannot be reproduced.

**Closed by bb7133** 2021-11-25 02:12 UTC
Labels: type/bug, sig/sql-infra, severity/major
