### ISSUE TITLE
Getting token duration increases a lot when the concurrency increases

### ISSUE THREAD

**Issue by zhangjinpeng1987** [pingcap/tidb#9124] opened 2019-01-19 12:12 UTC
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
Use sysbench to bench update statement. I have 32 tables, and each table has 1000,000 rows. I benching update statement with different concurrencies.

2. What did you expect to see?
The update QPS increases when the concurrency increases.

3. What did you see instead?
The update QPS drops when the concurrency increase from 1024 to 2048.
![update](https://user-images.githubusercontent.com/19700528/51426474-65935480-1c26-11e9-9b17-75d7ad61a570.jpeg)
<img width="669" alt="screen shot 2019-01-19 at 7 54 43 pm" src="https://user-images.githubusercontent.com/19700528/51426475-66c48180-1c26-11e9-87aa-550b37c1dc32.png">

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
pingcap@ip-172-16-30-32:/data1/latency/tidb1$ ./bin/tidb-server -V
Release Version: v3.0.0-beta
Git Commit Hash: ed5fae7aaded3b9f59733ef9dcf556ca285e9b14
Git Branch: HEAD
UTC Build Time: 2019-01-18 12:53:28
GoVersion: go version go1.11.2 linux/amd64
Race Enabled: false
TiKV Min Version: 2.1.0-alpha.1-ff3dd160846b7d1aed9079c389fc188f7f5ea13e
Check Table Before Drop: false

**Comment by lonng** [comment] 2019-01-20 16:13
Could you provide the configuration item `token-limit`.

**Comment by fzhedu** [comment] 2020-08-25 11:20
@zhangjinpeng1987 still exist? or close it.

**Comment by youjiali1995** [comment] 2020-11-12 10:59
I don't think it's a bug. It's by design that using token to limit concurrent executed session. The default value is 1000. The token wait duration should go up in proportion to the connection count.

**Closed** 2020-11-12 11:03 UTC
Labels: sig/transaction
