### ISSUE TITLE
DATE_FORMAT() inconsistent result between tidb and mysql(8.0 and 5.7) with 0000 year

### ISSUE THREAD

**Issue by ramanich1** [pingcap/tidb#30079] opened 2021-11-23 16:36 UTC
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```sql
SELECT DATE_FORMAT("0000-01-01",'%W %d %M %Y') as valid_date;
```
### 2. What did you expect to see? (Required)
```sql
mysql> SELECT DATE_FORMAT("0000-01-01",'%W %d %M %Y') as valid_date;
+------------------------+
| valid_date             |
+------------------------+
| Sunday 01 January 0000 |
+------------------------+
1 row in set (0.00 sec)
```
### 3. What did you see instead (Required)
```sql
mysql> SELECT DATE_FORMAT("0000-01-01",'%W %d %M %Y') as valid_date;
+--------------------------+
| valid_date               |
+--------------------------+
| Saturday 01 January 0000 |
+--------------------------+
1 row in set (0.00 sec
```
### 4. What is your TiDB version? (Required)
```sql
| Release Version: v5.4.0-alpha-67-g17edc5758
Edition: Community
Git Commit Hash: 17edc5758fbf865cada7e156318c41d3ee8a7501
Git Branch: master
UTC Build Time: 2021-11-16 02:57:45
GoVersion: go1.17.2
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false |
+--------------------------------
```

**Comment by morgo** [comment] 2021-11-23 16:40
I tried to do some quick googling to see what could be the cause of this. The day of the week in `0001` and prior might have multiple correct answers. In which case we can convert this to a compatibility-only issue.

**Comment by kennytm** [comment] 2021-11-23 17:45
The main issue here is that TiDB treats year 0000 as a leap year, while MySQL does not:

```sql
select date_format(a, '%W %d %M %Y') from (select '0000-02-28' a union select '0000-02-29' union select '0000-03-01') _ order by a;
```

<table><tr><th>MySQL<th>TiDB<tr><td>

```
+-------------------------------+
| date_format(a, '%W %d %M %Y') |
+-------------------------------+
| Tuesday 28 February 0000      |
| NULL                          |
| Wednesday 01 March 0000       |
+-------------------------------+
3 rows in set, 1 warning (0.02 sec)
```

<td>

```
+-------------------------------+
| date_format(a, '%W %d %M %Y') |
+-------------------------------+
| Monday 28 February 0000       |
| Tuesday 29 February 0000      |
| Wednesday 01 March 0000       |
+-------------------------------+
3 rows in set (0.00 sec)
```

</table>

Treating year 0 as leap year is the *correct* approach for the [proleptic Gregorian calendar](https://en.wikipedia.org/wiki/Proleptic_Gregorian_calendar). This is also the behavior of both Go and Rust (chrono), which get used by TiDB and TiKV.

> *This is the convention in astronomical year numbering and the international standard date system, ISO 8601. In these systems, the year 0 is a leap year.*

**I'd say [it is a bug of MySQL](https://bugs.mysql.com/bug.php?id=102639), not TiDB**, since MySQL claims that it is also using the [proleptic Gregorian calendar](https://dev.mysql.com/doc/refman/8.0/en/mysql-calendar.html). For comparison, SQLite3 also recognizes the day 0000-02-29:

```
sqlite> select strftime('%Y-%m-%d %w', '0000-02-28');
0000-02-28 1
sqlite> select strftime('%Y-%m-%d %w', '0000-02-29');
0000-02-29 2
sqlite> select strftime('%Y-%m-%d %w', '0000-03-01');
0000-03-01 3
```

In other RDBMS,

* PostgreSQL: year "1 BC" precedes "1 AD", but "1 BC" is a leap year.
* MS SQL: 0001-01-01 is the minimum date, so the problem doesn't arise.
* Oracle: year "-1" precedes "1", but Oracle uses the Julian calendar between 0001-01-01 and 1582-10-04, so the comparison isn't fair.

**Comment by morgo** [comment] 2021-11-23 23:15
@kennytm Thank you for the detailed response. OK I will close this as a bug for now.

**Closed by morgo** 2021-11-23 23:15 UTC
Labels: type/bug
