### ISSUE TITLE
br does not restore AUTO_INCREMENT correctly

### ISSUE THREAD

**Issue by overvenus** [pingcap/tidb#56801] opened 2024-10-23 07:20 UTC
### 1. Minimal reproduce step (Required)

Run [brie-acceptance-dailyrun@main](https://tcms.pingcap.net/dashboard/plans/9977073?planExecID=7650948), it fails at the last step [rowid-autoid-after-lighting-br](https://tcms.pingcap.net/dashboard/executions/case/12455553) .

### 2. What did you expect to see? (Required)

AUTO_INCREMENT is correctly restored .

### 3. What did you see instead (Required)

https://tcms.pingcap.net/api/v1/artifact-files/ks3/logs/2024-10-21/plan-exec-7650948-re0/plan-exec-7650948-re0-case-2130001-53-3503589016/main.log

2024-10-21T10:47:24.979Z	FATAL	7650948	lightning_rowid_autoid/main.go:91	ImportBasic failed	{"error": "verify query result failed, expected: 330001, actual CREATE TABLE `t1` (\n  `cacheid` int(11) NOT NULL AUTO_INCREMENT,\n  `rk` varchar(16) NOT NULL,\n  `cfq` varchar(10) NOT NULL,\n  `ts` bigint(20) NOT NULL,\n  `value` varchar(2048) DEFAULT NULL,\n  PRIMARY KEY (`cacheid`) /*T![clustered_index] CLUSTERED */\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin AUTO_INCREMENT=334001 /*T![auto_id_cache] AUTO_ID_CACHE=1 */", "errorVerbose": "verify query result failed, expected: 330001, actual CREATE TABLE `t1` (\n  `cacheid` int(11) NOT NULL AUTO_INCREMENT,\n  `rk` varchar(16) NOT NULL,\n  `cfq` varchar(10) NOT NULL,\n  `ts` bigint(20) NOT NULL,\n  `value` varchar(2048) DEFAULT NULL,\n  PRIMARY KEY (`cacheid`) /*T![clustered_index] CLUSTERED */\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin AUTO_INCREMENT=334001 /*T![auto_id_cache] AUTO_ID_CACHE=1 */\[ngithub.com/pingcap/test-infra/caselib/pkg/steps.verifyIncludeQueryResult.Execute\n\t/root/git/test-infra/caselib/pkg/steps/sql.go:613\ngithub.com/pingcap/test-infra/caselib/pkg/steps.withRecover\n\t/root/git/test-infra/caselib/pkg/steps/step.go:24\ngithub.com/pingcap/test-infra/caselib/pkg/steps.(*Serial).Execute\n\t/root/git/test-infra/caselib/pkg/steps/step.go:45\nmain.main\n\t/root/git/test-infra/caselib/case/lightning/lightning_rowid_autoid/main.go:90\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:267\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1650](http://ngithub.com/pingcap/test-infra/caselib/pkg/steps.verifyIncludeQueryResult.Execute/n/t/root/git/test-infra/caselib/pkg/steps/sql.go:613/ngithub.com/pingcap/test-infra/caselib/pkg/steps.withRecover/n/t/root/git/test-infra/caselib/pkg/steps/step.go:24/ngithub.com/pingcap/test-infra/caselib/pkg/steps.(*Serial).Execute/n/t/root/git/test-infra/caselib/pkg/steps/step.go:45/nmain.main/n/t/root/git/test-infra/caselib/case/lightning/lightning_rowid_autoid/main.go:90/nruntime.main/n/t/usr/local/go/src/runtime/proc.go:267/nruntime.goexit/n/t/usr/local/go/src/runtime/asm_amd64.s:1650)"}

### 4. What is your TiDB version? (Required)

BR: nightly 2024-10-21

**Comment by 3pointer** [comment] 2024-10-23 09:51
After https://github.com/pingcap/tidb/pull/56602 merged, the alloc ID logic of metakv has change. B Performing an alloc will cause the meta KV to advance by one more batch(4000). and Backup always rely on meta KV, because meta KV has snapshots.

Before this PR the meta kv after import is X. now is X + 4000.

However, this issue can also be considered expected behavior, as BR relies on meta KV as the source of truth. The actual value of meta KV has indeed increased.

**Comment by 3pointer** [comment] 2024-10-29 09:05
Consider this is a expected behavior and already fixed in test cases. I'm going to close this issue.

**Closed by 3pointer** 2024-10-29 09:05 UTC
Labels: type/bug, severity/major, component/br
