### ISSUE TITLE
clustered index + insert ignore... on duplicate key update return wrong result 

### ISSUE THREAD

**Issue by vivid392845427** [pingcap/tidb#28658] opened 2021-10-08 09:16 UTC
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
CREATE TABLE `tbl_24` (
  `col_60` varchar(510) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT 'H',
  `col_61` enum('Alice','Bob','Charlie','David') NOT NULL DEFAULT 'Alice',
  `col_62` char(26) COLLATE utf8_unicode_ci NOT NULL DEFAULT 'IuqBVyOjIZUhhBZv',
  `col_63` varchar(400) COLLATE utf8_unicode_ci NOT NULL DEFAULT 'TUgbGH',
  `col_64` varchar(77) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT 'KWkyVmMsUKtqsyQhV',
  `col_65` set('Alice','Bob','Charlie','David') NOT NULL DEFAULT 'David',
  PRIMARY KEY (`col_63`(1)) /*T![clustered_index] CLUSTERED */,
  UNIQUE KEY `idx_21` (`col_65`,`col_61`),
  UNIQUE KEY `idx_22` (`col_64`(1),`col_65`,`col_61`,`col_62`(3)),
  KEY `idx_23` (`col_64`(1),`col_62`(3),`col_61`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
insert ignore into tbl_24 (col_65) values ( 'David' ) , ( 'Charlie' ) , ( 'Alice' ) , ( 'Bob' ) on duplicate key update col_61 = 'Charlie', col_64 = 'dEimjuQoOsH', col_63 = 'TtxwVTHpzQykpcoAF';
 select * from tbl_24;
```

### 2. What did you expect to see? (Required)

```
mysql> insert ignore into tbl_24 (col_65) values ( 'David' ) , ( 'Charlie' ) , ( 'Alice' ) , ( 'Bob' ) on duplicate key update col_61 = 'Charlie', col_64 = 'dEimjuQoOsH', col_63 = 'TtxwVTHpzQykpcoAF';
Query OK, 3 rows affected (0.06 sec)
Records: 4  Duplicates: 3  Warnings: 0

mysql> select * from tbl_24;
+--------+---------+------------------+-------------------+-------------+--------+
| col_60 | col_61  | col_62           | col_63            | col_64      | col_65 |
+--------+---------+------------------+-------------------+-------------+--------+
| H      | Charlie | IuqBVyOjIZUhhBZv | TtxwVTHpzQykpcoAF | dEimjuQoOsH | David  |
+--------+---------+------------------+-------------------+-------------+--------+
1 row in set (0.01 sec)
```

### 3. What did you see instead (Required)

```
mysql> insert ignore into tbl_24 (col_65) values ( 'David' ) , ( 'Charlie' ) , ( 'Alice' ) , ( 'Bob' ) on duplicate key update col_61 = 'Charlie', col_64 = 'dEimjuQoOsH', col_63 = 'TtxwVTHpzQykpcoAF';
Query OK, 1 row affected, 3 warnings (0.01 sec)
Records: 4  Duplicates: 4  Warnings: 3

mysql> show warnings;
+---------+------+-------------------------------------------------------+
| Level   | Code | Message                                               |
+---------+------+-------------------------------------------------------+
| Warning | 1062 | Duplicate entry 'TtxwVTHpzQykpcoAF' for key 'PRIMARY' |
| Warning | 1062 | Duplicate entry 'TtxwVTHpzQykpcoAF' for key 'PRIMARY' |
| Warning | 1062 | Duplicate entry 'TtxwVTHpzQykpcoAF' for key 'PRIMARY' |
+---------+------+-------------------------------------------------------+
3 rows in set (0.00 sec)

mysql> select * from tbl_24;    
+--------+--------+------------------+--------+-------------------+--------+
| col_60 | col_61 | col_62           | col_63 | col_64            | col_65 |
+--------+--------+------------------+--------+-------------------+--------+
| H      | Alice  | IuqBVyOjIZUhhBZv | TUgbGH | KWkyVmMsUKtqsyQhV | David  |
+--------+--------+------------------+--------+-------------------+--------+
1 row in set (0.00 sec)
```

### 4. What is your TiDB version? (Required)

```
Release Version: v5.0.4-20210918
Edition: Community
Git Commit Hash: 560b0da8919063b02273d09876a11406eeb251bb
Git Branch: heads/refs/tags/v5.0.4-20210918
UTC Build Time: 2021-09-18 11:16:21
GoVersion: go1.13
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
```

**Comment by zyguan** [comment] 2021-12-30 09:35
duplicate of #28923

**Closed by zyguan** 2021-12-30 09:35 UTC
Labels: type/bug, sig/transaction, severity/moderate, affects-5.0
