### ISSUE TITLE
other error: unknown error StringError

### ISSUE THREAD

**Issue by javajeans** [pingcap/tidb#9908] opened 2019-03-27 06:37 UTC
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
（1）、这是表结构
```
CREATE TABLE `sys_user_wechat` (
  `id` varchar(32) NOT NULL DEFAULT '1',
  `nickname` varchar(100) DEFAULT NULL COMMENT '微信昵称',
  `open_id` varchar(50) NOT NULL COMMENT '微信openid',
  `user_id` varchar(32) NOT NULL COMMENT '用户id',
  `avatar_url` varchar(255) DEFAULT NULL COMMENT '微信头像',
  `remark` varchar(255) DEFAULT NULL COMMENT '备注',
  `created_time` datetime DEFAULT NULL,
  `created_by` varchar(32) DEFAULT NULL,
  `updated_time` datetime DEFAULT NULL,
  `updated_by` varchar(32) DEFAULT NULL,
  `country` varchar(20) DEFAULT NULL COMMENT '国家',
  `province` varchar(20) DEFAULT NULL COMMENT '省份',
  `city` varchar(20) DEFAULT NULL COMMENT '城市',
  `is_del` int(1) NOT NULL DEFAULT '1' COMMENT '删除状态',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

SET FOREIGN_KEY_CHECKS = 1;
```
数据超过2000000条，
执行sql语句：
```
select * from sys_user_wechat where open_id='o4Xv00IC1duOtC7Kvewpz2H5tuxI'
```
昨天还是正常的
今天却报这个错：
```
other error: unknown error StringError("[src/coprocessor/dag/executor/table_scan.rs:94]: unsupported data type `128`")
```
2. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
tidb是单机版：
Release Version: v2.1.0-rc.3-353-gef7082d

**Comment by jackysp** [comment] 2019-03-27 07:04
Hi @javajeans ,
Thanks for your report!
The returned error was from a TiKV cluster. What's your TiKV version?

**Comment by jackysp** [comment] 2019-03-27 07:27
PTAL @breeswish , thanks!

**Comment by javajeans** [comment] 2019-03-27 07:31
Hi @jackysp tikv version is Release Version:   3.0.0-alpha

**Comment by breeswish** [comment] 2019-03-27 07:38
Would you like to post the full output of `tikv-server --version`?

**Comment by javajeans** [comment] 2019-03-27 07:47
TiKV 
Release Version:   3.0.0-alpha
Git Commit Hash:   46cbb82bb8cff0a45ccfd67e35e49dc6e3c390b1
Git Commit Branch: master
UTC Build Time:    2018-12-23 05:07:50
Rust Version:      rustc 1.29.0-nightly (4f3c7a472 2018-07-17)

**Comment by breeswish** [comment] 2019-03-27 07:57
Looks like there are unexpected data in the cluster. Maybe caused by some bugs in inserting or updating. Would you like to add my wechat, so that we can talk and investigate this issue more efficiently: breezewish

**Comment by javajeans** [comment] 2019-03-27 08:58
在tikv/raft目录下的日志输出
```
(tikv_gc_leader_leas620190327-16:56:18 +0800 CSZCurrent GC worker leader lease. (DO NOT EDIT)"E
```
服务器内存只有16G   ，top下                                                                                                                                                                       
  ```                                                                                                                                                                                 
 4212 root      20   0 10.190g  36460   7520 S   9.0  0.2   2941:14 pd-server                                                                                                                                                                                  
 7148 root      20   0  548476 264772  16204 S   1.3  1.6   2:58.05 tidb-server                                                                                                                                                                                
18290 root      20   0  159008   3456   1600 S   1.3  0.0   0:13.41 top                                                                                                                                                                                        
 4232 root      20   0 13.864g 6.699g   4828 S   0.7 43.5   4151:56 tikv-server                                                                                                                                                                                
21021 root      20   0  158876   3452   1584 R   0.7  0.0   0:00.42 top       
```
是否是因为内存不够用,导致的

>微信已经加你

**Comment by crazycs520** [comment] 2019-03-27 11:51
@javajeans ， 昨天执行有问题的 SQL  （`select * from sys_user_wechat where open_id='o4Xv00IC1duOtC7Kvewpz2H5tuxI'`  ） 报错吗？

**Comment by nullnotnil** [comment] 2020-07-14 20:36
@javajeans Just following up, did you manage to identify the cause of this issue?

**Comment by jebter** [comment] 2024-06-05 06:51
The issue has not been updated for too long, so I will close it. If there are any updates, you can reopen it.

**Closed by jebter** 2024-06-05 06:51 UTC
Labels: type/question
