### ISSUE TITLE
Support implicit primary key

### ISSUE THREAD

**Issue by Deardrops** [pingcap/tidb#15403] opened 2020-03-16 08:28 UTC
## Feature Request

**Is your feature request related to a problem? Please describe:**

In MySQL 8.0, a table with no explicit primary key may still have an effective implicit primary key if it has any UNIQUE indexes on `NOT NULL` columns. In this case, the first such index places the same constraint on table rows as an explicit primary key and that index cannot be made invisible. Consider the following table definition: 
```sql
CREATE TABLE t2 (
  i INT NOT NULL,
  j INT NOT NULL,
  UNIQUE j_idx (j)
) ENGINE = InnoDB;
```
The key `j_idx` will became a primary key, even if we do not assign `primary key` explicitly.

**Describe the feature you'd like:**

In MySQL 8.0
```
mysql> show create table t;
+-------+--------------------------------------------------------------------------------------------------------------------------------------+
| Table | Create Table                                                                                                                         |
+-------+--------------------------------------------------------------------------------------------------------------------------------------+
| t     | CREATE TABLE `t` (
  `a` int(11) NOT NULL,
  UNIQUE KEY `a` (`a`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci |
+-------+--------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)

mysql> show keys from t;
+-------+------------+----------+--------------+-------------+-----------+-------------+----------+--------+------+------------+---------+---------------+---------+------------+
| Table | Non_unique | Key_name | Seq_in_index | Column_name | Collation | Cardinality | Sub_part | Packed | Null | Index_type | Comment | Index_comment | Visible | Expression |
+-------+------------+----------+--------------+-------------+-----------+-------------+----------+--------+------+------------+---------+---------------+---------+------------+
| t     |          0 | a        |            1 | a           | A         |           0 |     NULL |   NULL |      | BTREE      |         |               | YES     | NULL       |
+-------+------------+----------+--------------+-------------+-----------+-------------+----------+--------+------+------------+---------+---------------+---------+------------+
1 row in set (0.00 sec)

mysql> desc t;
+-------+---------+------+-----+---------+-------+
| Field | Type    | Null | Key | Default | Extra |
+-------+---------+------+-----+---------+-------+
| a     | int(11) | NO   | PRI | NULL    |       |
+-------+---------+------+-----+---------+-------+
1 row in set (0.01 sec)
mysql> alter table t alter index a invisible;
ERROR 3522 (HY000): A primary key index cannot be invisible

```

In TiDB:
```
mysql> create table t (a int not null, unique (a));
Query OK, 0 rows affected (0.11 sec)

mysql> show create table t;
+-------+-------------------------------------------------------------------------------------------------------------------------------+
| Table | Create Table                                                                                                                  |
+-------+-------------------------------------------------------------------------------------------------------------------------------+
| t     | CREATE TABLE `t` (
  `a` int(11) NOT NULL,
  UNIQUE KEY `a` (`a`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin |
+-------+-------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)

mysql> desc t;
+-------+---------+------+------+---------+-------+
| Field | Type    | Null | Key  | Default | Extra |
+-------+---------+------+------+---------+-------+
| a     | int(11) | NO   | UNI  | NULL    |       |
+-------+---------+------+------+---------+-------+
1 row in set (0.00 sec)

```

**Teachability, Documentation, Adoption, Migration Strategy:**

[MySQL document](https://dev.mysql.com/doc/refman/8.0/en/invisible-indexes.html)

**Comment by nullnotnil** [comment] 2020-08-06 16:04
This predates MySQL 8.0. InnoDB will promote the first not-null unique key to a primary key. I am going to mark this as a duplicate of: https://github.com/pingcap/tidb/issues/13635

I have proposed closing https://github.com/pingcap/tidb/issues/13635 as won't fix. Please comment if you agree/disagree. Thanks!

**Comment by morgo** [comment] 2020-12-07 03:11
Closing as a duplicate of https://github.com/pingcap/tidb/issues/13635 , per last comment. Thanks!

**Closed by morgo** 2020-12-07 03:11 UTC
Labels: type/compatibility, type/duplicate, type/enhancement
