### ISSUE TITLE
Inconsistent behavior of store `mocktikv` and `tikv`

### ISSUE THREAD

**Issue by IANTHEREAL** [pingcap/tidb#15124] opened 2020-03-04 07:00 UTC
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
if I use default store in tidb (mocktikv), I will get ["dump failed"] [error="err = Error 1105: can not get 'tikv_gc_safe_point'\

2. What did you expect to see?
`mocktikv` and `tikv` keep consistent behavior, because `dumpling` and `mydumper` doesn't which `store` used by tidb

detail also in https://github.com/pingcap/dumpling/issues/33

**Comment by nullnotnil** [comment] 2020-07-21 13:45
This is a duplicate of #8887 

I am going to close this issue, but feel free to reopen if you believe this is in error. Thanks!

**Closed by nullnotnil** 2020-07-21 13:45 UTC
Labels: type/bug
