### ISSUE TITLE
ASC and DESC after GROUP BY does not work.

### ISSUE THREAD

**Issue by SunRunAway** [pingcap/tidb#10810] opened 2019-06-14 03:38 UTC
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
```sql
mysql> SELECT sex FROM t1 GROUP BY sex DESC;
+------+
| sex  |
+------+
| M    |
| F    |
+------+
2 rows in set (0.00 sec)

mysql> SELECT sex FROM t1 GROUP BY sex DESC;
+------+
| sex  |
+------+
| F    |
| M    |
+------+
2 rows in set (0.00 sec)
```

2. What did you expect to see?

Outputs with descending order.

3. What did you see instead?

Outputs with inexplicit orders.

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

Git Commit Hash: b5dd1bdc7275f3200d829a6705c305da74fb4592
Git Branch: master
UTC Build Time: 2019-06-14 02:48:29
GoVersion: go version go1.12.1 darwin/amd64
Race Enabled: false
TiKV Min Version: 2.1.0-alpha.1-ff3dd160846b7d1aed9079c389fc188f7f5ea13e
Check Table Before Drop: false

**Comment by jackysp** [comment] 2019-06-14 13:34
Thanks, @SunRunAway !
Could you provide the test case you've used? The table schema, data, TiDB/TiKV config etc.

**Comment by jackysp** [comment] 2019-06-14 13:40
It will rise a syntax error in MySQL.
```
mysql> select * from t group by i desc;
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'desc' at line 1
```
I think TiDB just pass and ignore it.
Thanks for your report, @SunRunAway !

**Comment by morgo** [comment] 2019-06-14 14:37
Cross-linking to https://github.com/pingcap/tidb/issues/10522 - this relates to a behavior change between MySQL 5.7 and 8.0. We will need to decide how to handle it.

**Comment by SunRunAway** [comment] 2019-06-14 16:32
This is not the some issue. If TiDB were compatible with MySQL 5.7 in some way, the output should be ordered with ASC or DESC designators for GROUP BY columns.

**Comment by morgo** [comment] 2019-06-25 04:26
I think it is not good to add syntax which will be removed in the next version :-( But I will let @shenli or @zz-jason decide.

**Comment by nullnotnil** [comment] 2020-07-11 13:38
I am going to close this as a duplicate of https://github.com/pingcap/tidb/issues/10522

**Closed by nullnotnil** 2020-07-11 13:38 UTC
Labels: type/bug, type/compatibility, type/duplicate
