### ISSUE TITLE
Incorrect timestamp value when time_zone is set to America/New_York 

### ISSUE THREAD

**Issue by ChenPeng2013** [pingcap/tidb#19160] opened 2020-08-12 13:02 UTC
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
set time_zone="America/New_York";
create table t(a timestamp);
insert into t values("2020-03-08 02:51:21");
```

### 2. What did you expect to see? (Required)
```
mysql> insert into t values("2020-03-08 02:51:21");
Query OK, 1 row affected (0.01 sec)
```

### 3. What did you see instead (Required)
```
mysql> insert into t values("2020-03-08 02:51:21");
ERROR 1366 (HY000): Incorrect timestamp value: '2020-03-08 02:51:21' for column 'a' at row 1
```

### 4. What is your TiDB version? (Required)

```
Release Version: v4.0.3-62-g3948c7ba7-dirty
Edition: Community
Git Commit Hash: 3948c7ba7b5d4a081abf2162b791ab67fe650882
Git Branch: release-4.0
UTC Build Time: 2020-08-12 10:02:23
GoVersion: go1.14.6
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
```

**Comment by cfzjywxk** [comment] 2020-08-12 13:29
For the timezone set with EDT/EST, the clock [adjustment](http://www.webexhibits.org/daylightsaving/b.html) may change the time, and this will make `CoreTime`.`GoTime` check fails, which will report "wrong value to the client".

**Comment by bb7133** [comment] 2020-08-12 13:39
Why this is not expected? "2020-03-08 02:51:21" is not a valid time for New York because of [DST](https://en.wikipedia.org/wiki/Daylight_saving_time).

The behavior is compatible with MySQL.

**Comment by zyguan** [comment] 2020-08-12 14:25
https://en.wikipedia.org/wiki/Eastern_Time_Zone

**Comment by nullnotnil** [comment] 2020-08-12 16:49
For mysql, the timezone tables [need to be installed first](https://dev.mysql.com/doc/refman/8.0/en/mysql-tzinfo-to-sql.html).

I verified that MySQL 8.0.20 and MySQL 5.7.31 are consistent with TiDB:
```sql
mysql [localhost:5731] {msandbox} (test) > insert into t values("2020-03-08 02:51:21");
ERROR 1292 (22007): Incorrect datetime value: '2020-03-08 02:51:21' for column 'a' at row 1

mysql [localhost:8021] {msandbox} (test) > insert into t values("2020-03-08 02:51:21");
ERROR 1292 (22007): Incorrect datetime value: '2020-03-08 02:51:21' for column 'a' at row 1

tidb> insert into t values("2020-03-08 02:51:21");
ERROR 1366 (HY000): Incorrect timestamp value: '2020-03-08 02:51:21' for column 'a' at row 1
```

I am going to close this as 'not a bug'. Thanks!

**Closed by nullnotnil** 2020-08-12 16:49 UTC
Labels: type/bug
