### ISSUE TITLE
Potential race condition in CREATE TABLE

### ISSUE THREAD

**Issue by aphyr** [pingcap/tidb#10410] opened 2019-05-09 14:19 UTC
With TiDB 3.0.0-beta.1, on a five-node EC2 cluster running Debian Stretch, TiDB can return successfully from a `create table` command, then return `Table ... doesn't exist` errors when the same client attempts to insert a record into the table it just created.

1. What did you do?

Our Jepsen test runs the following pair of commands to verify the cluster is ready to serve requests:

```clj
          (j/execute! c ["create table if not exists jepsen_await (id int primary key, val int)"])
          (j/insert! c "jepsen_await" {:id  (swap! await-id inc)
                                       :val (rand-int 5)})
```

2. What did you expect to see?

If the `create table command completes`, one would expect the subsequent insert to observe that table's existence.

3. What did you see instead?

Instead, the `insert!` call throws:

`java.sql.SQLSyntaxErrorException: (conn=1) Table 'test.jepsen_await' doesn't exist`.

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

3.0.0-beta.1.

You can reproduce this problem with Jepsen dd9a7a53ddcbc8bf691134598f144e14213e241d by running something like

```
lein run test-all --concurrency 2n --time-limit 30
```

I haven't seen this in my LXC cluster, but on EC2, roughly 1 in 15 tests crash during cluster setup because of this behavior.

**Comment by aphyr** [comment] 2019-05-09 15:37
Here's a zip file with full logs! [20190508T051334.000Z.zip](https://github.com/pingcap/tidb/files/3162885/20190508T051334.000Z.zip

**Comment by shenli** [comment] 2019-05-09 15:55
@aphyr Thanks!

**Comment by aphyr** [comment] 2019-05-20 21:18
This has been tricky to reproduce, but I just hit another instance of it. This one happened in long-fork table initialization, which occurs *after* we've already successfully created and inserted records into the `await` table.

[20190520T205752.000Z.zip](https://github.com/pingcap/tidb/files/3199857/20190520T205752.000Z.zip)

**Comment by zimulala** [comment] 2019-06-06 08:52
@aphyr Thanks!
Background:
Currently, the DDL lease when doing boostrap is 100ms. When the bootstrap is completed, the DDL lease will become the value in the normal configuration. The default is 45s.
And the owner changes the state for the longest time waiting for 2 * lease to confirm the completion of the synchronization.

The scenario in which the problem occurred:
All TiDB servers will do boostrap operations. When other TiDB servers complete DDL and DML operations in boostrap and start receiving DDL operations from the client, the owner should also end the bootstrap, but due to a conflict when modifying the boostrap version, sleep 1s. In this 1s, there are DDL operations received by other TiDB servers.

This [PR #10029](https://github.com/pingcap/tidb/pull/10029)fixed this issue.

**Comment by shenli** [comment] 2019-06-10 06:46
hi @aphyr 
The issue is fixed. Should we close it now?

**Comment by aphyr** [comment] 2019-06-10 13:31
I haven't had time to confirm myself, but if you think it's fixed, you're welcome to close the issue!

**Comment by shenli** [comment] 2019-06-10 14:50
OK! We have tested it. 
If you have any more problem with 3.0.0-rc.2 or later version, please feel free to reopen this issue.
Thank you!

**Closed** 2019-06-10 14:50 UTC
Labels: type/bug
