### ISSUE TITLE
can't run multi schema change

### ISSUE THREAD

**Issue by kylezhang** [pingcap/tidb#5166] opened 2017-11-21 03:24 UTC
[can't support](https://github.com/pingcap/docs/blob/master/sql/mysql-compatibility.md#ddl)
can't run multi schema change， 
`multi schema change` feature is very necessary.
What time do you plan to support? Thanks！

**Comment by hanfei1991** [comment] 2017-11-21 07:47
We are planning to support this, please keep patient

**Comment by aheart** [comment] 2018-02-07 19:25
I'm very excited about TiDB, but without this feature it's difficult to use.
Eagerly waiting for this. :smile:
Thanks!

**Comment by ihipop** [comment] 2018-08-17 09:38
any update on this issue

**Comment by zhegexiaohuozi** [comment] 2018-09-20 08:58
any update on this issue ?

**Comment by zz-jason** [comment] 2018-09-20 15:57
@winkyao @zimulala PTAL

**Comment by decker502** [comment] 2018-10-29 13:15
any update on this issue ?

**Comment by zimulala** [comment] 2018-10-31 08:19
@decker502 
We will not support this operation for the time being.
If we start to support, we will update the progress here.

**Comment by serbaut** [comment] 2018-12-12 12:42
Grafana migrations depends on this feature.

**Comment by thinker0** [comment] 2019-03-18 09:09
any update on this issue ?

**Comment by winkyao** [comment] 2019-04-10 07:03
We are planning to solve this issue in 2019 Q3. Thanks for your attention @serbaut @thinker0

**Comment by Victorkangsh** [comment] 2019-07-14 13:09
It is now in the third quarter of 2019~

**Comment by bb7133** [comment] 2019-07-15 07:17
hi @Victorkangsh , currently we're discussing the plan for new features and the roadmap will be updated soon. Thank you!

**Comment by zimulala** [comment] 2020-02-13 02:33
Related issues: #5092

**Comment by protossyk** [comment] 2020-02-14 02:36
hi,any update on this issue?

**Comment by zimulala** [comment] 2020-02-14 02:40
We haven't dealt with it yet, but we are already sorting out related issues and plans. If you are interested, you can also participate. We will provide related design documents in the near future.

**Comment by roshanjonah** [comment] 2020-07-07 22:57
Can someone please move this to higher priority since nearly every single codebase does this and it always errors out?

**Comment by morgo** [comment] 2020-12-07 03:07
I am going to close this as a duplicate of https://github.com/pingcap/tidb/issues/14766

I realize this issue predates this, but #14766 is actively being worked on, and has a better break down of the sub-tasks involved. Thanks!

**Closed by morgo** 2020-12-07 03:07 UTC
Labels: sig/DDL, status/future, type/enhancement
