### ISSUE TITLE
[lightning] Estimate rowid might overflow when import data and auto fill int column.

### ISSUE THREAD

**Issue by fubinzh** [pingcap/tidb#28776] opened 2021-10-13 05:07 UTC
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
This issue was created according to ONCALL-3504

Using lightning to import data, before lightning import, create the schema in TiDB manually and adding an extra column: `id_auto_incr` int(11) NOT NULL AUTO_INCREMENT, during import, lightning will estimate the rowid and auto fill this column (as this column doesn't exists in data source), and rowid might overflow in some cases and result in data inconsistency.

### 2. What did you expect to see? (Required)
Lightning import should be successful and data consistency should be ensured.

### 3. What did you see instead (Required)
Lighting import failed with checksum mistch.

### 4. What is your TiDB version? (Required)
Lightning: 4.0.14

**Comment by buchuitoudegou** [comment] 2022-04-26 11:22
Possible root cause:
Lightning evaluates the data file's size and infers `PrevRowMax` and `RowIDMax` for each chunk. The `PrevRowMax` is assigned to `parser.lastRow.rowID` before reading and parsing the data file. 

After reading a row from the file, `parser.lastRow` is set this row, with `rowID = parser.lastRow.rowID++`. However, since `PrevRowMax` is an estimate, it obviously doesn't strictly equal the true rowID, and thus, we may have id much larger than what we expected.

Similarly, when `PrevRowMax` is over-estimated (e.g. overflows int(32)), we may probably make id exceeding the maximum of int.

It's intuitive to add a check or re-estimate these values, but would it be better to have a global ID allocator managing these stuff for us? /cc @gozssky @niubell

**Comment by D3Hunter** [comment] 2022-05-30 10:11
this issue affects 4.0/6.0, don't affects 5.x?

**Comment by buchuitoudegou** [comment] 2022-05-30 10:17
> this issue affects 4.0/6.0, don't affects 5.x?

It might affect all of them.

**Comment by buchuitoudegou** [comment] 2023-01-31 07:02
This issue has a workaround: setting the auto-increment key as bigint or unsigned bigint can allow tidb to have a larger key space so that the auto-increment key won't exceed the limit. 

https://github.com/pingcap/tidb/pull/34288 is not sophisticated enough so it was reverted temporarily. We will try to find out a better way to resolve it.

**Closed by buchuitoudegou** 2023-01-31 07:02 UTC
Labels: type/bug, severity/major, sig/migrate, component/lightning, affects-6.0, affects-6.1, affects-6.2, affects-6.3, affects-6.4, affects-6.5
