### ISSUE TITLE
Separator and order by not supported in group_concat

### ISSUE THREAD

**Issue by jackysp** [pingcap/tidb#4059] opened 2017-08-07 03:05 UTC
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

```sql
create table t1 (grp int, a bigint unsigned, c char(10) not null, d char(10) not null);
insert into t1 values (1,1,"a","a"); 
insert into t1 values (2,2,"b","a"); 
insert into t1 values (2,3,"c","b");
insert into t1 values (3,4,"E","a");
insert into t1 values (3,5,"C","b");
select grp,group_concat(c separator ",") from t1 group by grp;    
select grp,group_concat(c order by c) from t1 group by grp; 
```

2. What did you expect to see?

```
grp	group_concat(c separator ",")
1	a
2	b,c
3	E,C
grp	group_concat(c order by c)
1	a
2	b,c
3	C,E
```

3. What did you see instead?

```
ERROR 1105 (HY000) at line 7: line 0 column 35 near " ",") from t1 group by grp" (total length 61)
```

4. What version of TiDB are you using (`tidb-server -V`)?

**Comment by morgo** [comment] 2018-11-24 19:16
Separator is now supported, order by is parse but ignored:
```
tidb> select grp,group_concat(c separator "#") from t1 group by grp;    
+------+-------------------------------+
| grp  | group_concat(c separator "#") |
+------+-------------------------------+
|    1 | a                             |
|    3 | E#C                           |
|    2 | b#c                           |
+------+-------------------------------+
3 rows in set (0.01 sec)

tidb> select grp,group_concat(c order by c) from t1 group by grp; 
+------+----------------------------+
| grp  | group_concat(c order by c) |
+------+----------------------------+
|    1 | a                          |
|    3 | E,C                        |
|    2 | b,c                        |
+------+----------------------------+
3 rows in set (0.00 sec)
```

**Comment by morgo** [comment] 2018-11-24 19:18
ORDER BY is a duplicate of https://github.com/pingcap/tidb/issues/6838

I am going to close this issue now, as the new issue better describes the remaining scope.

**Closed by morgo** 2018-11-24 19:18 UTC
Labels: help wanted, type/compatibility
