### ISSUE TITLE
RC isolation lock behavior not compatible

### ISSUE THREAD

**Issue by you06** [pingcap/tidb#20731] opened 2020-10-30 02:37 UTC
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```sql
/* init */ drop table if exists t;
/* init */ create table t (id int primary key, v int, vv int, vvv int);

/* s1 */ SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED;
/* s2 */ SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED;
/* s1 */ begin;
/* s2 */ begin;
/* s1 */ insert into t values(1, 2, 3, 4);
/* s2 */ update t set id = 10, v = 20, vv = 30, vvv = 40 where id = 1;
/* s1 */ commit;
/* s2 */ commit;

/* s1 */ select * from t;
```

### 2. What did you expect to see? (Required)

The update statement is blocked by insert's lock and the result of table t is (10, 20, 30, 40).

### 3. What did you see instead (Required)

The update statement is not blocked and affected 0 rows, the result of table t is (1, 2, 3, 4).

### 4. What is your TiDB version? (Required)

```
Release Version: v4.0.0-beta.2-1419-g974c5fa78
Edition: Community
Git Commit Hash: 974c5fa78e69af35879da1494b771f498ebfb1b4
Git Branch: master
UTC Build Time: 2020-10-23 12:06:41
GoVersion: go1.13
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: fals
```

**Comment by nullnotnil** [comment] 2020-10-30 02:41
I believe this is currently [documented under #1](https://docs.pingcap.com/tidb/stable/pessimistic-transaction#difference-with-mysql-innodb) (tidb does not support gap locking), but could be made clearer.

@cfzjywxk is my understanding correct here?

**Comment by you06** [comment] 2020-10-30 02:44
This issue will not occur in RR isolation level, it seems it's caused by update statement does not read the lock in RC.

**Comment by cfzjywxk** [comment] 2020-10-30 03:15
> I believe this is currently [documented under #1](https://docs.pingcap.com/tidb/stable/pessimistic-transaction#difference-with-mysql-innodb) (tidb does not support gap locking), but could be made clearer.
> 
> @cfzjywxk is my understanding correct here?

@nullnotnil I think it's caused by the implementation [here](https://github.com/pingcap/tidb/blob/master/executor/point_get.go#L262)that non-exist key will not be locked in RC isolation level.

**Comment by jackysp** [comment] 2020-11-03 06:10
![image](https://user-images.githubusercontent.com/4352397/97954210-dd237b00-1ddd-11eb-86b2-1300eff07a80.png)
tested it with Oracle 11g, it is the same behavior with TiDB. So `id = 1` doesn't acquire the gap lock in MySQL. What's the lock type of it?

**Comment by jackysp** [comment] 2020-11-03 06:31
![image](https://user-images.githubusercontent.com/4352397/97955466-317c2a00-1de1-11eb-99e4-033d2cb1409e.png)
So does Postgres.

**Comment by you06** [comment] 2020-11-03 06:59
```
MySQL [test]> SELECT * FROM information_schema.INNODB_LOCKS\G;                                                                                                                                
*************************** 1. row ***************************                                                                                                                                
    lock_id: 1821:24:3:2                                                                                                                                                                      
lock_trx_id: 1821                                                                                                                                                                             
  lock_mode: X                                                                                                                                                                                
  lock_type: RECORD                                                                                                                                                                           
 lock_table: `test`.`t`                                                                                                                                                                       
 lock_index: PRIMARY                                                                                                                                                                          
 lock_space: 24                                                                                                                                                                               
  lock_page: 3                                                                                                                                                                                
   lock_rec: 2                                                                                                                                                                                
  lock_data: 1
*************************** 2. row ***************************
    lock_id: 1816:24:3:2
lock_trx_id: 1816
  lock_mode: X
  lock_type: RECORD
 lock_table: `test`.`t`
 lock_index: PRIMARY
 lock_space: 24
  lock_page: 3
   lock_rec: 2
  lock_data: 1
2 rows in set, 1 warning (0.001 sec)

MySQL [test]> SELECT * FROM information_schema.INNODB_TRX;                                      
+--------+-----------+---------------------+-----------------------+---------------------+------------+---------------------+--------------------------------------------------------------+---------------------+-------------------+-------------------+------------------+-----------------------+-----------------+-------------------+-------------------------+---------------------+-------------------+------------------------+----------------------------+---------------------------+---------------------------+------------------+----------------------------+
| trx_id | trx_state | trx_started         | trx_requested_lock_id | trx_wait_started    | trx_weight | trx_mysql_thread_id | trx_query                                                    | trx_operation_state | trx_tables_in_use | trx_tables_locked | trx_lock_structs | trx_lock_memory_bytes | trx_rows_locked | trx_rows_modified | trx_concurrency_tickets | trx_isolation_level | trx_unique_checks | trx_foreign_key_checks | trx_last_foreign_key_error | trx_adaptive_hash_latched | trx_adaptive_hash_timeout | trx_is_read_only | trx_autocommit_non_locking |
+--------+-----------+---------------------+-----------------------+---------------------+------------+---------------------+--------------------------------------------------------------+---------------------+-------------------+-------------------+------------------+-----------------------+-----------------+-------------------+-------------------------+---------------------+-------------------+------------------------+----------------------------+---------------------------+---------------------------+------------------+----------------------------+
| 1821   | LOCK WAIT | 2020-11-03 06:57:19 | 1821:24:3:2           | 2020-11-03 06:57:19 |          2 |                   4 | update t set id = 10, v = 20, vv = 30, vvv = 40 where id = 1 | starting index read |                 1 |                 1 |                2 |                  1136 |               1 |                 0 |                       0 | REPEATABLE READ     |                 1 |                      1 | NULL                       |                         0 |                         0 |                0 |                          0 |
| 1816   | RUNNING   | 2020-11-03 06:57:15 | NULL                  | NULL                |          3 |                   2 | SELECT * FROM information_schema.INNODB_TRX                  | NULL                |                 0 |                 1 |                2 |                  1136 |               1 |                 1 |                       0 | READ COMMITTED      |                 1 |                      1 | NULL                       |                         0 |                         0 |                0 |                          0 |
+--------+-----------+---------------------+-----------------------+---------------------+------------+---------------------+--------------------------------------------------------------+---------------------+-------------------+-------------------+------------------+-----------------------+-----------------+-------------------+-------------------------+---------------------+-------------------+------------------------+----------------------------+---------------------------+---------------------------+------------------+----------------------------+
```

It's record lock in MySQL.

**Comment by cfzjywxk** [comment] 2020-11-03 09:25
I think our current implementaion is aimed at `Oracle read consistency`. So do we just document this compatibility issue?

**Comment by jackysp** [comment] 2020-11-03 10:45
What do you think? @nullnotnil

**Comment by cfzjywxk** [comment] 2020-11-03 13:04
I changed it to compatibility issues.

**Comment by nullnotnil** [comment] 2020-11-03 14:43
Because it's a non-default, I agree with calling it a compatibility issue and not a bug. But it is confusing to document it as `Oracle read consistency`, since RC also exists in MySQL.

**Comment by jackysp** [comment] 2020-11-06 03:18
We could just describe our behavior, we don't need to emphasize consistency with Oracle.

**Comment by zyguan** [comment] 2022-09-23 02:55
@cfzjywxk , It seems to be fixed by https://github.com/pingcap/tidb/pull/36834 , we may close this issue and revert https://github.com/pingcap/automated-tests/pull/597?

**Comment by cfzjywxk** [comment] 2022-09-23 03:49
@TonsnakeLin @you06 
What do you think?

**Comment by TonsnakeLin** [comment] 2022-09-23 05:30
Yes, point-lock-read will lock the record first if it exists at RC isolation because of #36384. This issue can be fixed.
But for non-point-lock-read, it still reads first and then lock these records.

**Comment by you06** [comment] 2022-09-26 03:33
> But for non-point-lock-read, it still reads first and then lock these records.

MySQL does not block non-point-lock-read too. I think we can close this issue now.

**Closed** 2022-09-26 11:00 UTC
Labels: type/compatibility, sig/transaction
