### ISSUE TITLE
"explain extended" is not supported in TiDB

### ISSUE THREAD

**Issue by PerfectXD** [pingcap/tidb#9366] opened 2019-02-20 04:53 UTC
When running select ddl in SQLyog v8.14, software prompt error as below.
![image](https://user-images.githubusercontent.com/13029641/53067040-62cd9d00-350d-11e9-9d87-5b9ffd43f0a4.png)

After enable tidb_general_log，warning occurs in the log.
[tidb.log](https://github.com/pingcap/tidb/files/2883079/tidb.log)

**Comment by morgo** [comment] 2019-02-20 05:02
Duplicate of #3640.

Please note that the format of `EXPLAIN` in TiDB differs from MySQL.  The use case for `EXPLAIN EXTENDED` is to run `show warnings` after.

**Comment by zz-jason** [comment] 2020-04-03 08:30
close due to duplication.

**Closed by zz-jason** 2020-04-03 08:30 UTC
Labels: good-first-issue, help-wanted, type/new-feature
