### ISSUE TITLE
panic during information query schema

### ISSUE THREAD

**Issue by gregwebs** [pingcap/tidb#8130] opened 2018-10-31 18:54 UTC
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?

Creating an Invalid foreign key definition and then querying information_schema produces a server panic. 
 Minimal testcase:
```
CREATE TABLE parent (id INT NOT NULL, PRIMARY KEY (id));
CREATE TABLE child (id INT NOT NULL, parent_id INT NOT NULL, PRIMARY KEY(id));
ALTER TABLE child ADD FOREIGN KEY (foo) REFERENCES parent(foo);
SELECT TABLE_NAME,COLUMN_NAME,CONSTRAINT_NAME, REFERENCED_TABLE_NAME,REFERENCED_COLUMN_NAME FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE;
```

I also saw this panic when I queried with `WHERE   REFERENCED_TABLE_SCHEMA = '...' AND REFERENCED_TABLE_NAME = '...'`

2. What did you expect to see?

information schema output

3. What did you see instead?

The logs show the below

```
mysql     | 2018/10/31 18:46:21.299 adapter.go:293: [debug] con:1 ActivePendingTxn SELECT    TABLE_NAME,COLUMN_NAME,CONSTRAINT_NAME, REFERENCED_TABLE_NAME,REFERENCED_COLUMN_NAME FROM   INFORMATION_SCHEMA.KEY_COLUMN_USAGE
mysql     | 2018/10/31 18:46:21.299 adapter.go:372: [debug] [QUERY] cost_time:7.568µs  succ:true con:1 user:root@192.168.64.1 txn_start_ts:403966939968045056 database:dbaas sql:commit
mysql     | panic: runtime error: invalid memory address or nil pointer dereference
mysql     | [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xcaae9f]
mysql     | 
mysql     | goroutine 771 [running]:
mysql     | github.com/pingcap/tidb/infoschema.keyColumnUsageInTable(0xc000cb0c40, 0xc0007e32c0, 0x4, 0x5, 0xc0015c2840)
mysql     | 	/home/jenkins/workspace/build_tidb_2.1/go/src/github.com/pingcap/tidb/infoschema/tables.go:1263 +0xaff
mysql     | github.com/pingcap/tidb/infoschema.dataForKeyColumnUsage(0xc0015b6800, 0x5, 0x8, 0x10, 0xffffffffffffffff, 0x8)
mysql     | 	/home/jenkins/workspace/build_tidb_2.1/go/src/github.com/pingcap/tidb/infoschema/tables.go:1185 +0x14b
mysql     | github.com/pingcap/tidb/infoschema.(*infoschemaTable).getRows(0xc000d537c0, 0x1528c20, 0xc001041340, 0xc001559560, 0x5, 0x5, 0x4, 0x5, 0xc000d19df0, 0x40c498, ...)
mysql     | 	/home/jenkins/workspace/build_tidb_2.1/go/src/github.com/pingcap/tidb/infoschema/tables.go:1372 +0x11fc
mysql     | github.com/pingcap/tidb/infoschema.(*infoschemaTable).IterRecords(0xc000d537c0, 0x1528c20, 0xc001041340, 0x0, 0x0, 0x0, 0xc001559560, 0x5, 0x5, 0xc00155ebc0, ...)
mysql     | 	/home/jenkins/workspace/build_tidb_2.1/go/src/github.com/pingcap/tidb/infoschema/tables.go:1419 +0x84
mysql     | github.com/pingcap/tidb/executor.(*TableScanExec).nextChunk4InfoSchema(0xc001520b60, 0x7f1ead3b26a8, 0xc0015b62c0, 0xc001559260, 0x404c75, 0xc0015c2240)
mysql     | 	/home/jenkins/workspace/build_tidb_2.1/go/src/github.com/pingcap/tidb/executor/executor.go:916 +0x402
mysql     | github.com/pingcap/tidb/executor.(*TableScanExec).Next(0xc001520b60, 0x7f1ead3b26a8, 0xc0015b62c0, 0xc001559260, 0x0, 0x0)
mysql     | 	/home/jenkins/workspace/build_tidb_2.1/go/src/github.com/pingcap/tidb/executor/executor.go:887 +0x24c
mysql     | github.com/pingcap/tidb/executor.(*projectionInputFetcher).run(0xc0015c6090, 0x7f1ead3b26a8, 0xc0015b62c0)
mysql     | 	/home/jenkins/workspace/build_tidb_2.1/go/src/github.com/pingcap/tidb/executor/projection.go:285 +0x166
mysql     | created by github.com/pingcap/tidb/executor.(*ProjectionExec).prepare
mysql     | 	/home/jenkins/workspace/build_tidb_2.1/go/src/github.com/pingcap/tidb/executor/projection.go:225 +0x66e
mysql     | 2018/10/31 18:46:23.007 printer.go:39: [info] Welcome to TiDB.
```

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
2.1.0-rc.4
Also seen on 2.0.7

**Comment by gregwebs** [comment] 2018-10-31 19:11
I am adding foreign keys and then running this query: so I believe it is related to foreign keys. Another issue that I noticed is that tidb allows duplicate foreign keys.

```
mysql> SELECT    TABLE_NAME,COLUMN_NAME,CONSTRAINT_NAME, REFERENCED_TABLE_NAME,REFERENCED_COLUMN_NAME FROM   INFORMATION_SCHEMA.KEY_COLUMN_USAGE WHERE   REFERENCED_TABLE_SCHEMA = 'db';+------------+-------------+------------------------------------------+-----------------------+------------------------+
| TABLE_NAME | COLUMN_NAME | CONSTRAINT_NAME                          | REFERENCED_TABLE_NAME | REFERENCED_COLUMN_NAME |
+------------+-------------+------------------------------------------+-----------------------+------------------------+
| users      | deleted_id  | users_deleted_id_user_changes_id_foreign | user_changes          | id                     |
| users      | deleted_id  | users_deleted_id_user_changes_id_foreign | user_changes          | id                     |
| users      | deleted_id  | users_deleted_id_user_changes_id_foreign | user_changes          | id                     |
| users      | deleted_id  | users_deleted_id_user_changes_id_foreign | user_changes          | id                     |
| users      | deleted_id  | users_deleted_id_user_changes_id_foreign | user_changes          | id                     |
| users      | deleted_id  | users_deleted_id_user_changes_id_foreign | user_changes          | id                     |
+------------+-------------+------------------------------------------+-----------------------+------------------------+
```

**Comment by gregwebs** [comment] 2018-10-31 20:03
Okay, this seems to be a problem of invalid foreign keys blowing up. I am told we may have better validation on master.

```
mysql> CREATE TABLE parent (
    ->     id INT NOT NULL,
    ->     PRIMARY KEY (id)
    -> ) ENGINE=INNODB;
Query OK, 0 rows affected (0.04 sec)

mysql> CREATE TABLE child (     id INT,     parent_id INT, PRIMARY KEY (id));
Query OK, 0 rows affected (0.03 sec)

mysql> ALTER TABLE child ADD FOREIGN KEY (foo) references parent(foo);
Query OK, 0 rows affected (0.02 sec)

mysql> SELECT    TABLE_NAME,COLUMN_NAME,CONSTRAINT_NAME, REFERENCED_TABLE_NAME,REFERENCED_COLUMN_NAME FROM   INFORMATION_SCHEMA.KEY_COLUMN_USAGE;
ERROR 2013 (HY000): Lost connection to MySQL server during query
```

**Comment by morgo** [comment] 2018-10-31 20:23
I've updated the issue description to include the minimal test case.  I also changed the types to match on nullability.  I can no longer reproduce the test-case on the `master` branch (which recently added foreign key validation).

However, I reproduce a scenario of:
1. Create schema with TiDB 2.1-x (before foreign key validation).
2. Upgrade to 2.1-master
3. Query information schema

So _ideally_ we can create a fix for servers which upgrade and have corrupt meta data (to triage: how likely is this issue?)

**Comment by EamonZhang** [comment] 2018-11-23 06:14
a temporary solution
drop all foreign key , itdb does not support foreign key.

1 fetch all foreign key 
```
curl http://{TiDBIP}:10080/schema/{db}
```

2 delete foreign key

```
import sys
import json
sql_tpl = 'alter table %s drop foreign key %s'

if __name__ == '__main__':
    schemas = json.load(open(sys.argv[1]))
    for schema in schemas:
        if schema['fk_info']:
            for fk in schema['fk_info']:
                sql = sql_tpl % (schema['name']['O'], fk['fk_name']['O'])
                print(sql + ';')
```
mark

**Comment by nullnotnil** [comment] 2020-07-10 17:59
This cause of this issue has been resolved by validating meta data on creating tables. The panic was caused by an update by an earlier version.

Thus, I am going to close this issue now. Please feel free to re-open if you have any further questions. Thanks!

**Closed by nullnotnil** 2020-07-10 17:59 UTC
Labels: type/bug
