### ISSUE TITLE
Inconsistent Query Results with Logical Operations on JSON Data and IS_IPV4_MAPPED

### ISSUE THREAD

**Issue by dwenking** [pingcap/tidb#57805] opened 2024-11-28 12:48 UTC
## Bug Report

In TiDB, queries involving logical operations and JSON data return inconsistent results when executed on a view versus a materialized table. Specifically, the query on the materialized table (t1) returns 6 rows, while the equivalent query on the view returns 7 rows. 

### 1. Minimal reproduce step (Required)

Create table t0 and insert data:
```sql
CREATE TABLE t0 (c0 MEDIUMINT, c1 JSON);
INSERT INTO t0 (c0, c1) VALUES (7420571, 'true');
INSERT INTO t0 (c0, c1) VALUES (-3814254, '-30');
INSERT INTO t0 (c0, c1) VALUES (6737107, '"p"');
INSERT INTO t0 (c0, c1) VALUES (2132911, '[-25, -100]');
INSERT INTO t0 (c0, c1) VALUES (6587968, '"B"');
INSERT INTO t0 (c0, c1) VALUES (-1395065, 'false');
```

Create materialized table t1 and query it:
```sql
CREATE TABLE t1 (c0 bigint , c1 JSON);
INSERT INTO t1 SELECT (IS_IPV4_MAPPED(c0)) , c1 FROM t0 ;

my:root@127.0.0.1:4000=> SELECT c1 FROM t1 WHERE (((((c0) OR c1) <= ('"1"' OR (c0))) = (((c0) = c1) != ((c0) = ('100')))) OR (CASE WHEN (NULL <= c1) THEN ((-391983275431311411)) ELSE ((8114370851638574898)) END) IN (SELECT c1 FROM t1 WHERE (CASE WHEN ((c0) OR '1') THEN (('"h"')) ELSE (('-87')) END)));
  c1  
------
 true 
 -30 
 -9 
 true 
 -98 
 -66 
(6 rows)
```

Create t1 as view instead and query it using the same SELECT query:
```sql
CREATE VIEW t1 AS SELECT IS_IPV4_MAPPED(c0) AS c0, c1 FROM t0 ;

my:root@127.0.0.1:4000=> SELECT c1 FROM t1 WHERE (((((c0) OR c1) <= ('"1"' OR (c0))) = (((c0) = c1) != ((c0) = ('100')))) OR (CASE WHEN (NULL <= c1) THEN ((-391983275431311411)) ELSE ((8114370851638574898)) END) IN (SELECT c1 FROM t1 WHERE (CASE WHEN ((c0) OR '1') THEN (('"h"')) ELSE (('-87')) END)));
  c1   
-------
 true 
 -30 
 -9 
 true 
 -98 
 -66 
 false 
(7 rows)
```

### 2. What did you expect to see? (Required)
Both queries on the materialized table and the view should return identical results, as the logical conditions and data are equivalent.

### 3. What did you see instead (Required)
Query on the materialized table (t1) returns 6 rows.
Query on the view (t1) returns 7 rows, including an additional row with c1 = false.

### 4. What is your TiDB version? (Required)

```
my:root@127.0.0.1:4000=> SELECT tidb_version();
                      tidb_version()                       
-----------------------------------------------------------
 Release Version: v8.3.0                                  +
 Edition: Community                                       +
 Git Commit Hash: 1a0c3ac3292fff7742faa0c00a662ccb66ba40db+
 Git Branch: HEAD                                         +
 UTC Build Time: 2024-08-20 10:23:00                      +
 GoVersion: go1.21.10                                     +
 Race Enabled: false                                      +
 Check Table Before Drop: false                           +
 Store: tikv 
(1 row)
```

**Comment by yibin87** [comment] 2024-12-03 08:39
Not a bug, close it.

**Comment by yibin87** [comment] 2024-12-03 08:41
BTW, are you doing some researching for database tests? @dwenking

**Closed** 2024-12-03 08:40 UTC
Labels: type/bug, sig/execution

**Comment by dwenking** [comment] 2024-12-03 11:56
Thanks for this quick response, and yes, I am trying to identify potential logic bugs in databases by leveraging some data equivalence relationships. This is because I notice that in SQL queries, sometimes data that should be equal ends up returning different results.
