### ISSUE TITLE
FA when using greater than or less than

### ISSUE THREAD

**Issue by keeplearning20221** [pingcap/tidb#35021] opened 2022-05-30 03:25 UTC
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
1、CREATE TABLE `TBPC1560_1` (
  MULTI_TENANCY_ID char(5) NOT NULL DEFAULT ' ' ,
CST_ID char(18) NOT NULL DEFAULT ' ' ,
RCRD_EXPY_TMS datetime(3) NOT NULL DEFAULT '9999-12-31 23:59:59.999',
BSPD_ECD char(3) NOT NULL DEFAULT ' ' ,
RETPCD char(7) NOT NULL DEFAULT ' ' ,
SRCSYS_AR_ID varchar(100) NOT NULL DEFAULT ' ' ,
RSRV_CST_ID char(18) NOT NULL DEFAULT ' ',
AR_ID char(23) NOT NULL DEFAULT ' ' ,
ASPD_ECD char(8) NOT NULL DEFAULT ' ' ,
SRCSYS_AR_TPDS char(20) NOT NULL DEFAULT ' ' ,
PD_SIGN_IND char(1) NOT NULL DEFAULT ' ' ,
INR_AR_IND char(1) NOT NULL DEFAULT ' ' ,
CST_EXT_ACCNO varchar(40) DEFAULT NULL ,
AR_STCD char(6) NOT NULL DEFAULT ' ' ,
AR_EFDT char(8) NOT NULL DEFAULT ' ' ,
AR_EXDAT char(8) NOT NULL DEFAULT ' ' ,
AR_TMDT char(8) NOT NULL DEFAULT ' ' ,
CRT_INSID char(9) NOT NULL DEFAULT ' ' ,
CRT_EMPID char(8) NOT NULL DEFAULT ' ' ,
LAST_UDT_INSID char(9) NOT NULL DEFAULT ' ' ,
LAST_UDT_EMPID char(8) NOT NULL DEFAULT ' ' ,
CUR_STM_CRT_TMS datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ,
CUR_STM_UDT_TMS datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ,
LCL_YRMO_DAY char(8) NOT NULL DEFAULT ' ',
LCL_HR_GRD_SCND char(9) NOT NULL DEFAULT ' ' ,
CRT_STM_NO char(6) NOT NULL DEFAULT ' ',
UDT_STM_NO char(6) NOT NULL DEFAULT ' ',
SRCSYS_CRT_TMS datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ,
SRCSYS_UDT_TMS datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT ,
MTCH_DGR_PARVAL decimal(10,2) NOT NULL DEFAULT '0' ,
CLC_DT char(8) NOT NULL DEFAULT ' ' ,
  PRIMARY KEY (`CST_ID`,`RCRD_EXPY_TMS`,`BSPD_ECD`,`RETPCD`,`SRCSYS_AR_ID`,`MULTI_TENANCY_ID`) /*T![clustered_index] NONCLUSTERED */,
  KEY `TXPC15602` (`CST_EXT_ACCNO`),
  KEY `SRCSYS_AR_ID` (`SRCSYS_AR_ID`,`RSRV_CST_ID`,`SRCSYS_UDT_TMS`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin
PARTITION BY LIST COLUMNS(`MULTI_TENANCY_ID`)
(PARTITION `P1` VALUES IN ("CN000"),
 PARTITION `P2` VALUES IN ("DA001"),
 PARTITION `P3` VALUES IN ("DA002"),
 PARTITION `P4` VALUES IN ("DA003"),
 PARTITION `P5` VALUES IN ("DB001"),
 PARTITION `P6` VALUES IN ("DB002"),
 PARTITION `P7` VALUES IN ("DB003"),
 PARTITION `P8` VALUES IN ("DB004"),
 PARTITION `P9` VALUES IN ("DB005"),
 PARTITION `P10` VALUES IN ("DB006"),
 PARTITION `P11` VALUES IN ("DB007"),
 PARTITION `P12` VALUES IN ("DB008"),
 PARTITION `P13` VALUES IN ("DB009"),
 PARTITION `P14` VALUES IN ("DB010"),
 PARTITION `P15` VALUES IN ("DC001"),
 PARTITION `P16` VALUES IN ("DC002"),
 PARTITION `P17` VALUES IN ("DC003"),
 PARTITION `P18` VALUES IN ("DC004"),
 PARTITION `P19` VALUES IN ("DC005"),
 PARTITION `P20` VALUES IN ("DC006"),
 PARTITION `P21` VALUES IN ("DC007"),
 PARTITION `P22` VALUES IN ("DC008"),
 PARTITION `P23` VALUES IN ("DC009"),
 PARTITION `P24` VALUES IN ("DC010"),
 PARTITION `P25` VALUES IN ("DC011"),
 PARTITION `P26` VALUES IN ("DC012"),
 PARTITION `P27` VALUES IN ("DC013"),
 PARTITION `P28` VALUES IN ("DC014"),
 PARTITION `P29` VALUES IN ("DC015"),
 PARTITION `P30` VALUES IN ("DE001"),
 PARTITION `P31` VALUES IN ("DF001"),
 PARTITION `P32` VALUES IN ("DG001"),
 PARTITION `P33` VALUES IN ("DG002"),
 PARTITION `P34` VALUES IN ("DG003"),
 PARTITION `P35` VALUES IN ("DG004"),
 PARTITION `P36` VALUES IN ("DG005"),
 PARTITION `P37` VALUES IN ("DG006"),
 PARTITION `P38` VALUES IN ("DG007"),
 PARTITION `P39` VALUES IN ("DG008"),
 PARTITION `P40` VALUES IN ("DG009"),
 PARTITION `P41` VALUES IN ("DG010"),
 PARTITION `P42` VALUES IN ("DG011"),
 PARTITION `P43` VALUES IN ("DG012"),
 PARTITION `P44` VALUES IN ("DG013"),
 PARTITION `P45` VALUES IN ("DG014"),
 PARTITION `P46` VALUES IN ("DG025"),
 PARTITION `P47` VALUES IN ("DG026"),
 PARTITION `P48` VALUES IN ("DH004"),
 PARTITION `P49` VALUES IN ("PB001"),
 PARTITION `P50` VALUES IN ("PB002"))；
insert into TBPC1560_1 values ("DA003","024400000000000000","9999-12-31 23:59:59.999","ssd","0220001","查尫覯","049500000000000000","","5423","fdsvsdd","N","N","024400000000000000","ddd","20200101","22220202","21210101","555514751","58772574","555514751","58772574","2022-05-27 12:27:16.000","2022-05-27 12:27:16.000","20201111","122151111","457568","578265","2022-05-28 16:01:13.576","2022-05-27 12:27:16.000",53.30,"20220121");
insert into TBPC1560_1 values ("DA002","024400000000000000","9999-12-31 23:59:59.999","ssd","0220001","查尫覯","049500000000000000","","5423","fdsvsdd","N","N","024400000000000000","ddd","20200101","22220202","21210101","555514751","58772574","555514751","58772574","2022-05-27 12:27:16.000","2022-05-27 12:27:16.000","20201111","122151111","457568","578265","2022-05-28 16:01:13.576","2022-05-27 12:27:16.000",53.30,"20220121");
insert into TBPC1560_1 values ("DA001","024400000000000000","9999-12-31 23:59:59.999","ssd","0220001","查尫覯","049500000000000000","","5423","fdsvsdd","N","N","024400000000000000","ddd","20200101","22220202","21210101","555514751","58772574","555514751","58772574","2022-05-27 12:27:16.000","2022-05-27 12:27:16.000","20201111","122151111","457568","578265","2022-05-28 16:01:13.576","2022-05-27 12:27:16.000",53.30,"20220121");
insert into TBPC1560_1 values ("CN000","024400000000000000","9999-12-31 23:59:59.999","ssd","0220001","查尫覯","049500000000000000","","5423","fdsvsdd","N","N","024400000000000000","ddd","20200101","22220202","21210101","555514751","58772574","555514751","58772574","2022-05-27 12:27:16.000","2022-05-27 12:27:16.000","20201111","122151111","457568","578265","2022-05-28 16:01:13.576","2022-05-27 12:27:16.000",53.30,"20220121");
select count(*) from TBPC1560_1 where MULTI_TENANCY_ID >= "CN000" or MULTI_TENANCY_ID < "DA002";

```
### 2. What did you expect to see? (Required)
2
### 3. What did you see instead (Required)
ERROR 1300 (HY000): Invalid utf8mb4 character string: 'FA'

### 4. What is your TiDB version? (Required)

Release Version: v5.4.0
Edition: Community
Git Commit Hash: 55f3b24c1c9f506bd652ef1d162283541e428872
Git Branch: heads/refs/tags/v5.4.0
UTC Build Time: 2022-01-25 08:39:26
GoVersion: go1.16.4
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false |

**Comment by Defined2014** [comment] 2022-05-30 03:29
Maybe fixed by https://github.com/pingcap/tidb/issues/31721, try release-6.0 or newer.

**Comment by aytrack** [comment] 2022-05-30 09:03
can't reproduce on master, v6.0.0

**Closed** 2022-06-01 07:41 UTC
Labels: type/bug, sig/sql-infra, severity/moderate
