### ISSUE TITLE
Explain analyze delete executation is slow

### ISSUE THREAD

**Issue by Connor1996** [pingcap/tidb#37931] opened 2022-09-19 06:55 UTC
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

- sysbench prepare with 10000000 rows
- run 
```
for i in 1..1000 {
     mysql -uroot -D sbtest -e "explain analyze delete from sbtest where id < i * 10000;"
}
```

### 2. What did you expect to see? (Required)

The total process key is 10000

### 3. What did you see instead (Required)

The total process key is far beyond 10000, and the coprocess cache hit is 0. And if I sleep 1s between rounds, the total process key is 10000 and executes fast. 

![image](https://user-images.githubusercontent.com/13497871/190962419-7f0efa83-e2ae-443f-bc2b-49d5225eca75.png)

### 4. What is your TiDB version? (Required)

```
Release Version: v6.3.0-alpha
Edition: Community
Git Commit Hash: 8b5b724d8a932239303a1d0ba547323eb0e5161b
Git Branch: heads/refs/tags/v6.3.0-alpha
UTC Build Time: 2022-08-19 14:31:05
GoVersion: go1.18.5
Race Enabled: false
TiKV Min Version: 6.2.0-alpha
Check Table Before Drop: false
```

**Comment by Yisaer** [comment] 2022-09-27 08:14
We found that https://github.com/pingcap/tidb/pull/38044 can actually solve this problem. The root cause is that before `https://github.com/pingcap/tidb/pull/38044, the txn hasn't been committed while the next delete operation has begun which caused txn conflict to resolved lock.  After the fixing, the explain analyze dml will be commited before flushing result to the client, thus the issue is also be solved now.

![image](https://user-images.githubusercontent.com/13427348/192471456-f09b0c4b-0928-4685-bca8-a411c50429ab.png)

**Closed by Yisaer** 2022-09-27 08:14 UTC
Labels: type/bug, sig/planner, severity/major, may-affects-4.0, may-affects-5.1, may-affects-5.2, may-affects-5.3, may-affects-5.4, may-affects-5.0, may-affects-6.0, may-affects-6.1, may-affects-6.2, affects-6.3
