### ISSUE TITLE
dump proper information before OOM

### ISSUE THREAD

**Issue by zz-jason** [pingcap/tidb#9632] opened 2019-03-11 05:33 UTC
## Feature Request

**Is your feature request related to a problem? Please describe:**

see https://stackoverflow.com/questions/36436018/c-application-on-linux-on-hook-before-kill

**Describe the feature you'd like:**

We need to investigate what signals oom-killer sends to TiDB process before SIGKILL, if there is a SIGTERM or SIGINT, maybe we can dump some proper information to help identify the OOM reason

**Describe alternatives you've considered:**

Or we can monitor the memory consumption periodically outside the tidb process

**Teachability, Documentation, Adoption, Migration Strategy:**

No

**Comment by SunRunAway** [comment] 2020-05-27 06:10
Duplicate of #17095

**Closed by SunRunAway** 2020-05-27 06:10 UTC
