### ISSUE TITLE
ERROR 1105 (HY000): runtime error: index out of range [-1]

### ISSUE THREAD

**Issue by luyomo** [pingcap/tidb#25086] opened 2021-06-03 06:39 UTC
## Bug Report

I am testing the migration from mysql to tidb for icinga2.  Everything is fine until the data migration, but when I attempted to start the icinga2 web service, the following errors comes.
https://github.com/Icinga/icinga2
ERROR 1105 (HY000): runtime error: index out of range [-1]

### 1. Minimal reproduce step (Required)
Please find the attached file  reproduce.ddl and errorQuery.sql
1. Create DB objects  using reproduce.txt  
[reproduce.txt](https://github.com/pingcap/tidb/files/6589473/reproduce.txt)

2. Run the query from errorQuerty.txt
[errorQuery.txt](https://github.com/pingcap/tidb/files/6589474/errorQuery.txt)

### 2. What did you expect to see? (Required)
No error.

### 3. What did you see instead (Required)
ERROR 1105 (HY000): runtime error: index out of range [-1]

### 4. What is your TiDB version? (Required)
| Release Version: v5.0.1
Edition: Community
Git Commit Hash: 1145e347d3469d8e89f88dce86f6926ca44b3cd8
Git Branch: heads/refs/tags/v5.0.1
UTC Build Time: 2021-04-23 05:42:59
GoVersion: go1.13
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false

**Comment by aytrack** [comment] 2021-06-03 08:37
can reproduce on `5.0.1`, but can't reproduce on master and `5.0.2` freeze commit(f610f8bd01b09790f9915fd）

**Comment by luyomo** [comment] 2021-06-04 00:48
When can we get the 5.0.2 from tiup?
I would like to test it

**Comment by winoros** [comment] 2021-06-29 07:27
@luyomo Now you should get the 5.0.2 from tiup. If you have any question, please contact us :)

**Comment by yudongusa** [comment] 2021-08-25 02:36
@luyomo would you please verify if the issue is resolved? If so, please go ahead to close this issue.

**Comment by tisonkun** [comment] 2021-09-12 15:40
closed as marked as cannot reproduced. @luyomo feel free to reopen it if any further information missed.

**Closed by tisonkun** 2021-09-12 15:40 UTC
Labels: type/bug, invalid, sig/planner, severity/minor, status/can't-reproduce
