### ISSUE TITLE
Sudden increase of connections causes TiDB OOM

### ISSUE THREAD

**Issue by cosven** [pingcap/tidb#23712] opened 2021-03-30 16:11 UTC
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

1. deploy a v5.0.0-nightly tidb cluster with `3pd 2db 1ha 3kv`. The two TiDB instances run on a 8c16G docker container.
2. restore 2T tpcc data (about 6T data in cluster) with br
3. run `go-tpc -H x -P x-D tpcc30k tpcc run -T 1000 --warehouses 30000 --time 24h --ignore-error`

### 2. What did you expect to see? (Required)
I run go-tpc with 400 threads, and each tidb server memory only rises a little.
I think running go-tpc with 1000 threads should not cause tidb OOM.

### 3. What did you see instead (Required)
TiDB OOM.

Run go-tpc with 400 threads (reference)
![image](https://user-images.githubusercontent.com/4962134/113020647-5ff60980-91b5-11eb-924f-6ecfcce88eb3.png)

Run go-tpc with 1000 threads (unexpected OOM)
![image](https://user-images.githubusercontent.com/4962134/113020055-cdee0100-91b4-11eb-9511-97aab55ecebb.png)

Goroutine comparison
![image](https://user-images.githubusercontent.com/4962134/113021445-2bcf1880-91b6-11eb-9c3b-b2d00374b3e6.png)

### 4. What is your TiDB version? (Required)

```
[root@9166d82a1e94 ~]#  /disk1/deploy/tidb-4000/bin/tidb-server -V
Release Version: v5.0.0-nightly
Edition: Community
Git Commit Hash: 7e3d70d4b70d7a9328816991f76e191eb26986c0
Git Branch: heads/refs/tags/v5.0.0-nightly
UTC Build Time: 2021-03-27 01:22:18
GoVersion: go1.13
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
```

**Comment by mahjonp** [comment] 2021-03-31 08:41
@XuHuaiyu  OOM may be caused by this issue: #22132 I guess.

**Comment by XuHuaiyu** [comment] 2021-03-31 09:14
It's an expected phenomenon.
I've checked tidb.log.
- There are many `expensive_query` logs when the count of thread is 1000. But no `expensive_query` is recorded when the count of thread is 400. e.g.
```
[2021/03/30 23:24:18.501 +08:00] [WARN] [expensivequery.go:178] [expensive_query] [cost_time=60.010313187s] [cop_time=338.038957923s] [process_time=639.511s] [wait_time=8.54s] [request_count=341] [total_keys=498298] [process_keys=494000] [num_cop_tasks=341] [process_avg_time=1.875398826s] [process_p90_time=7.853s] [process_max_time=22.159s] [process_max_addr=10.0.2.76:20160] [wait_avg_time=0.025043988s] [wait_p90_time=0.078s] [wait_max_time=0.193s] [wait_max_addr=10.0.2.76:20160] [conn_id=4225] [user=root] [database=tpcc30k] [table_ids="[49,47,63]"] [index_names="[customer:PRIMARY,orders:idx_order,order_line:PRIMARY,history:idx_h_c_w_id]"] [txn_start_ts=423917728139576610] [mem_max="24652315 Bytes (23.5 MB)"] [sql="SELECT count(*) \n\tFROM (  SELECT  c.c_id, c.c_d_id, c.c_w_id, c.c_balance c1, \n\t\t\t\t   (SELECT sum(ol_amount) FROM orders STRAIGHT_JOIN order_line \n\t\t\t\t\t WHERE OL_W_ID=O_W_ID \n\t\t\t\t\t   AND OL_D_ID = O_D_ID \n\t\t\t\t\t   AND OL_O_ID = O_ID \n\t\t\t\t\t   AND OL_DELIVERY_D IS NOT NULL \n\t\t\t\t\t   AND O_W_ID=? \n\t\t\t\t\t   AND O_D_ID=c.C_D_ID \n\t\t\t\t\t   AND O_C_ID=c.C_ID) sm, (SELECT  sum(h_amount)  from  history \n\t\t\t\t\t\t\t\t\t\t\t\tWHERE H_C_W_ID=? \n\t\t\t\t\t\t\t\t\t\t\t\t  AND H_C_D_ID=c.C_D_ID \n\t\t\t\t\t\t\t\t\t\t\t\t  AND H_C_ID=c.C_ID) smh \n\t\t\t FROM customer c \n\t\t\tWHERE  c.c_w_id = ? ) t\n   WHERE c1<>sm-smh"]
```
- The pressure of the cluster is too high, which causes too many queries to run slowly. Thus the memory can not be free, and many goroutines can not exit.

**Comment by XuHuaiyu** [comment] 2021-03-31 09:30
<img width="881" alt="截屏2021-03-31 下午5 28 23" src="https://user-images.githubusercontent.com/9039012/113122946-b3fcfe80-9246-11eb-8863-0d4c676aa3d9.png">

**Comment by XuHuaiyu** [comment] 2021-03-31 09:30
This is a good test case when we support the backpressure mechanism.

**Comment by jebter** [comment] 2024-06-06 02:43
The issue has not been updated for too long, so I will close it. If there are any updates, you can reopen it.

**Closed by jebter** 2024-06-06 02:43 UTC
Labels: type/question
