### ISSUE TITLE
Can't find a proper physical plan for this query

### ISSUE THREAD

**Issue by Hanyu2015** [pingcap/tidb#8916] opened 2019-01-03 02:05 UTC
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
mysql>select * from trigger_depends where triggerid_down=397764;
ERROR 1815 (HY000): Internal : Can't find a proper physical plan for this query
2. What did you expect to see?
triggerdepid  triggerid_down triggerid_up
14429            397764              397769

3. What did you see instead?
ERROR 1815 (HY000): Internal : Can't find a proper physical plan for this query

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
v2.1.2-1-g8ba8096

**Comment by Hanyu2015** [comment] 2019-01-03 02:47
create table 'trigger_depends' ('triggerdepid' bigint(20) unsigned not null,'triggerid_down' bigint(20) unsigned not null, 'triggerid_up' unsigned not null,primary key ('triggerdepid'), unique key 'trigger_depends_1' ('triggerid_down','triggerid_up'), key 'trigger_depends_2' ('triggerid_up'))

**Comment by zz-jason** [comment] 2019-01-03 02:59
@Hanyu2015 Can not reproduce according to the create table statement and the sql you provided:
```sql
create table trigger_depends (
    triggerdepid bigint(20) unsigned not null,
    triggerid_down bigint(20) unsigned not null,
    triggerid_up bigint(20) unsigned not null, -- NOTE: this bigint(20) was added by me to escape the syntax error
    primary key (triggerdepid),
    unique key trigger_depends_1 (triggerid_down,triggerid_up),
    key trigger_depends_2 (triggerid_up)
)
```

on my laptop:
```sql
TiDB(root@127.0.0.1:test) > select * from trigger_depends where triggerid_down=397764;
Empty set (0.00 sec)
```

Could you provide us the full create table statement and the table statistics info to help us locate the issue and fix it ASAP? To obtain the create table statement, connect to the TiDB server with mysql client:

```sql
show create table trigger_depends\G
```

to download the table statistics info, open a terminal:
```sh
curl -G "http://${tidb-server-ip}:${tidb-server-status-port}/stats/dump/${db_name}/${table_name}" > trigger_depends.stats.json
```

**Comment by zz-jason** [comment] 2019-01-03 04:19
> I guess index on triggerid_down may be damaged, because !=,not in,< and >is well done, but = and in is wrong. how to repair it.
> and need user and password in this
> curl -G "http://${tidb-server-ip}:${tidb-server-status-port}/stats/dump/${db_name}/${table_name}" > trigger_depends.stats.json

What error does the above `curl` command return?

**Comment by Hanyu2015** [comment] 2019-01-03 07:19
run the command "analyze table trigger_depends", and then this problem is resolved. Thank you, but I don't know why this happened.

**Comment by lamxTyler** [comment] 2019-01-03 07:37
I think the problem depends on the stats, but it is lost after the analyze.

**Comment by zz-jason** [comment] 2019-01-07 02:52
@Hanyu2015 Can you reproduce this issue after `analyze table`?

**Comment by Hanyu2015** [comment] 2019-01-07 02:55
No, and it‘s ok now’

**Comment by zz-jason** [comment] 2019-01-07 02:58
> I think the problem depends on the stats, but it is lost after the analyze.

@lamxTyler Could you explain more?

**Comment by zz-jason** [comment] 2020-03-17 14:12
I'm going to close this issue due to can't reproduce. Feel free to reopen it once you met the same problem again.

**Closed by zz-jason** 2020-03-17 14:12 UTC
Labels: component/planner, type/bug
