### ISSUE TITLE
fatal error: concurrent map read and map write

### ISSUE THREAD

**Issue by tiancaiamao** [pingcap/tidb#14960] opened 2020-02-26 15:14 UTC
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

Run unit test

2. What did you expect to see?

all test passes

3. What did you see instead?

```
fatal error: concurrent map read and map write

goroutine 73 [running]:
runtime.throw(0x1d4dcff, 0x21)
        c:/go/src/runtime/panic.go:774 +0x79 fp=0xc0011c6bb8 sp=0xc0011c6b88 pc=0x433519
runtime.mapaccess1_faststr(0x1a31900, 0xc000253a10, 0x1d1f766, 0xb, 0x346d9e0)
        c:/go/src/runtime/map_faststr.go:21 +0x456 fp=0xc0011c6c28 sp=0xc0011c6bb8 pc=0x413a56
github.com/pingcap/tidb/util/collate.GetCollator(...)
        C:/project/src/github.com/pingcap/tidb/util/collate/collate.go:127
github.com/pingcap/tidb/types.CompareString(0xc0027baa17, 0x9, 0xc002ac0e90, 0x9, 0x0, 0x0, 0x0, 0xffffffffffffffff)
        C:/project/src/github.com/pingcap/tidb/types/compare.go:118 +0xef fp=0xc0011c6c70 sp=0xc0011c6c28 pc=0xd10f9f
github.com/pingcap/tidb/types.(*Datum).compareString(0xc002ad2370, 0xc0004dc500, 0xc002ac0e90, 0x9, 0x0, 0x0, 0x0)
        C:/project/src/github.com/pingcap/tidb/types/datum.go:603 +0x125 fp=0xc0011c6dc0 sp=0xc0011c6c70 pc=0xd1bd15
github.com/pingcap/tidb/types.(*Datum).compareBytes(0xc002ad2370, 0xc0004dc500, 0xc002ac0e90, 0x9, 0x9, 0x0, 0x0, 0x0)
        C:/project/src/github.com/pingcap/tidb/types/datum.go:631 +0x90 fp=0xc0011c6e30 sp=0xc0011c6dc0 pc=0xd1c520
github.com/pingcap/tidb/types.(*Datum).CompareDatum(0xc002ad2370, 0xc0004dc500, 0xc0011c6f50, 0x0, 0x0, 0x0)
        C:/project/src/github.com/pingcap/tidb/types/datum.go:505 +0x305 fp=0xc0011c6f08 sp=0xc0011c6e30 pc=0xd1ab45
github.com/pingcap/tidb/statistics.(*SortedBuilder).Iterate(0xc002e26040, 0x6, 0x0, 0x0, 0x0, 0x0, 0xc002ac0e90, 0x9, 0x9, 0x0, ...)
        C:/project/src/github.com/pingcap/tidb/statistics/builder.go:57 +0x91 fp=0xc0011c6f48 sp=0xc0011c6f08 pc=0x10ff4b1
github.com/pingcap/tidb/statistics.buildIndex(0x20b5de0, 0xc0011b0f60, 0x100, 0x1, 0x2061e00, 0xc001040000, 0x1, 0x1, 0x0, 0xc00020cfd0, ...)
        C:/project/src/github.com/pingcap/tidb/statistics/statistics_test.go:221 +0x301 fp=0xc0011c7088 sp=0xc0011c6f48 pc=0x113aae1
github.com/pingcap/tidb/statistics.(*testStatisticsSuite).TestBuild(0xc000346140, 0xc0000b2870)
        C:/project/src/github.com/pingcap/tidb/statistics/statistics_test.go:290 +0x119e fp=0xc0011c7af8 sp=0xc0011c7088 pc=0x113c0ee
runtime.call32(0xc000186090, 0xc00020c400, 0xc00020bea0, 0x1000000010)
        c:/go/src/runtime/asm_amd64.s:539 +0x42 fp=0xc0011c7b28 sp=0xc0011c7af8 pc=0x45fe22
reflect.Value.call(0x1c5bea0, 0xc000346140, 0x613, 0x1d120c4, 0x4, 0xc000e7bf18, 0x1, 0x1, 0x346fdc0, 0xc000e7bdb8, ...)
        c:/go/src/reflect/value.go:460 +0x5fd fp=0xc0011c7d48 sp=0xc0011c7b28 pc=0x4dd9bd
reflect.Value.Call(0x1c5bea0, 0xc000346140, 0x613, 0xc000e7bf18, 0x1, 0x1, 0x0, 0xc000201080, 0xc000e7be88)
        c:/go/src/reflect/value.go:321 +0xbb fp=0xc0011c7dc8 sp=0xc0011c7d48 pc=0x4dd17b
github.com/pingcap/check.(*suiteRunner).forkTest.func1(0xc0000b2870)
        C:/project/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:850 +0x5eb fp=0xc0011c7f40 sp=0xc0011c7dc8 pc=0x10f818b
github.com/pingcap/check.(*suiteRunner).forkCall.func1(0xc00023acf0, 0xc0000b2870, 0xc00198d120)
        C:/project/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:739 +0xe1 fp=0xc0011c7fc8 sp=0xc0011c7f40 pc=0x10f7901
runtime.goexit()
        c:/go/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc0011c7fd0 sp=0xc0011c7fc8 pc=0x461ba1
created by github.com/pingcap/check.(*suiteRunner).forkCall
        C:/project/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:734 +0x23a


goroutine 1 [chan receive]:
testing.(*T).Run(0xc000360300, 0x1d133b0, 0x5, 0x1db8e68, 0x49de1d)
        c:/go/src/testing/testing.go:961 +0x37e
testing.runTests.func1(0xc000360200)
        c:/go/src/testing/testing.go:1202 +0x7f
testing.tRunner(0xc000360200, 0xc0000a3d88)
        c:/go/src/testing/testing.go:909 +0xd0
testing.runTests(0xc0002049c0, 0x33e26f0, 0x1, 0x1, 0x0)
        c:/go/src/testing/testing.go:1200 +0x2ae
testing.(*M).Run(0xc000212100, 0x0)
        c:/go/src/testing/testing.go:1117 +0x17d
main.main()
        _testmain.go:116 +0x1c8

goroutine 23 [semacquire]:
sync.runtime_Semacquire(0xc0003b2e78)
        c:/go/src/runtime/sema.go:56 +0x49
sync.(*WaitGroup).Wait(0xc0003b2e70)
        c:/go/src/sync/waitgroup.go:130 +0x6b
github.com/pingcap/check.RunAll(0xc000421ef0, 0x0)
        C:/project/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/run.go:129 +0x502
github.com/pingcap/check.TestingT(0xc000360300)
        C:/project/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/run.go:99 +0x478
github.com/pingcap/tidb/statistics.TestT(0xc000360300)
        C:/project/src/github.com/pingcap/tidb/statistics/statistics_test.go:39 +0x32
testing.tRunner(0xc000360300, 0x1db8e68)
        c:/go/src/testing/testing.go:909 +0xd0
created by testing.(*T).Run
        c:/go/src/testing/testing.go:960 +0x357

goroutine 28 [select]:
github.com/pingcap/check.(*resultTracker)._loopRoutine(0xc00023ac60)
        C:/project/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:464 +0xe4
created by github.com/pingcap/check.(*resultTracker).start
        C:/project/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:444 +0x46
...
```

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

master 

commit 3b0fbc67b58950f76a7b5b966424282042d12b5b (HEAD -> master, origin/master, origin/HEAD)
Author: Zejun Li <lizejun@pingcap.com>
Date:   Wed Feb 26 20:55:00 2020 +0800

    tikv: reduce call of `WithLabelValues` in `doActionOnKeys` (#14938)

**Comment by wjhuang2016** [comment] 2020-02-27 02:28
Duplicate of #14949

**Closed by wjhuang2016** 2020-02-27 02:28 UTC
Labels: type/bug, type/duplicate
