### ISSUE TITLE
CI failed due to a potential deadlock in statistics/handle

### ISSUE THREAD

**Issue by zimulala** [pingcap/tidb#41011] opened 2023-02-02 11:11 UTC
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

Find in https://do.pingcap.net/jenkins/blue/organizations/jenkins/pingcap%2Ftidb%2Fghpr_check2/detail/ghpr_check2/12217/pipeline/

### 2. What did you expect to see? (Required)
no potential deadlock

### 3. What did you see instead (Required)
```
POTENTIAL DEADLOCK:
Previous place where the lock was grabbed
goroutine 622437 lock 0xc023795610
[2023/02/02 14:01:55.298 +08:00] [INFO] [2pc.go:1753] ["Schema changed for async commit txn"] [error="[domain:8027]Information schema is out of date: schema failed to update in 1 lease, please make sure TiDB can connect to TiKV"] [errorVerbose="[domain:8027]Information schema is out of date: schema failed to update in 1 lease, please make sure TiDB can connect to TiKV\ngithub.com/tikv/client-go/v2/txnkv/transaction.(*twoPhaseCommitter).checkSchemaValid\n\texternal/com_github_tikv_client_go_v2/txnkv/transaction/2pc.go:1746\ngithub.com/tikv/client-go/v2/txnkv/transaction.(*twoPhaseCommitter).calculateMaxCommitTS\n\texternal/com_github_tikv_client_go_v2/txnkv/transaction/2pc.go:1751\ngithub.com/tikv/client-g
o/v2/txnkv/transaction.(*twoPhaseCommitter).execute\n\texternal/com_github_tikv_client_go_v2/txnkv/transaction/2pc.go:1465\ngithub.com/tikv/client-go/v2/txnkv/transaction.(*KVTxn).Commit\n\texternal/com_github_tikv_client_go_v2/txnkv/transaction/txn.go:496\ngithub.com/pingcap/tidb/store/driver/txn.(*tikvTxn).Commit\n\tstore/driver/txn/txn_driver.go:95\ngithub.com/pingcap/tidb/session.(*LazyTxn).Commit\n\tsession/txn.go:425\ngithub.com/pingcap/tidb/session.(*session).commitTxnWithTemporaryData\n\tsession/session.go:832\ngithub.com/pingcap/tidb/session.(*session).doCommit\n\tsession/session.go:718\ngithub.com/pingcap/tidb/session.(*session).doCommitWithRetry\n\tsession/session.go:964\ngithub.com/pingcap/tidb/session.(*session).CommitTxn\n\tsession/session.go:1094\ngithub.com/pingcap/tidb/session.autoCommitAfterStmt\n\tsession/tidb.go:283\ngithub.com/pingcap/tidb/session.finishStmt\n\tsession/tidb.go:249\ngithub.com/pingcap/tidb/session.runStmt\n\tsession/session.go:2370\ngithub.com/pingcap/tidb/session.(*session).ExecuteStmt\n\tsession/session.go:2215\ngithub.com/pingcap/tidb/session.(*session).ExecuteInternal\n\tsession/session.go:1668\ngithub.com/pingcap/tidb/statistics/handle.finishTransaction\n\tstatistics/handle/ddl.go:341\ngithub.com/pingcap/tidb/statistics/handle.(*Handle).dumpTableStatCountToKV.func2\n\tstatistics/handle/update.go:542\ngithub.com/pingcap/tidb/statistics/handle.(*Handle).dumpTableStatCountToKV\n\tstatistics/handle/update.go:587\ngithub.com/pingcap/tidb/statistics/handle.(*Handle).DumpStatsDeltaToKV\n\tstatistics/handle/update.go:500\ngithub.com/pingcap/tidb/domain.(*Domain).updateStatsWorker\n\tdomain/domain.go:2074\ngithub.com/pingcap/tidb/domain.(*Domain).UpdateTableStatsLoop.func2\n\tdomain/domain.go:1913\ngithub.com/pingcap/tidb/util.(*WaitGroupEnhancedWrapper).Run.func1\n\tutil/wait_group_wrapper.go:96\nruntime.goexit\n\tGOROOT/src/runtime/asm_amd64.s:1594"] [startTS=439174482205343745]
statistics/handle/update.go:533 handle.(*Handle).dumpTableStatCountToKV ??? <<<<<
statistics/handle/update.go:500 handle.(*Handle).DumpStatsDeltaToKV ???
domain/domain.go:2074 domain.(*Domain).updateStatsWorker ???
domain/domain.go:1913 domain.(*Domain).UpdateTableStatsLoop.func2 ???
util/wait_group_wrapper.go:96 util.(*WaitGroupEnhancedWrapper).Run.func1 ???

Have been trying to lock it again for more than 20s
goroutine 622421 lock 0xc023795610
statistics/handle/handle.go:2390 handle.(*Handle).RefreshVars ??? <<<<<
domain/domain.go:1969 domain.(*Domain).loadStatsWorker ???
util/wait_group_wrapper.go:96 util.(*WaitGroupEnhancedWrapper).Run.func1 ???


Here is what goroutine 622437 doing now
goroutine 622437 [semacquire]:
sync.runtime_SemacquireMutex(0x405060700010203?, 0xb?, 0x6164707560207962?)
        GOROOT/src/runtime/sema.go:77 +0x25
sync.(*Mutex).lockSlow(0xc000915470)
        GOROOT/src/sync/mutex.go:171 +0x165
sync.(*Mutex).Lock(...)
        GOROOT/src/sync/mutex.go:90
github.com/sasha-s/go-deadlock.(*lockOrder).PreLock(0xc000915470, 0xc0e4b8ddf0?, {0x472a700?, 0xc005c76f78})
        external/com_github_sasha_s_go_deadlock/deadlock.go:251 +0xb4
github.com/sasha-s/go-deadlock.PreLock(...)
        external/com_github_sasha_s_go_deadlock/deadlock.go:131
github.com/sasha-s/go-deadlock.lock(0xc0e9b8a120, {0x472a700, 0xc005c76f78})
        external/com_github_sasha_s_go_deadlock/deadlock.go:147 +0x76
github.com/sasha-s/go-deadlock.(*RWMutex).Lock(...)
        external/com_github_sasha_s_go_deadlock/deadlock.go:89
github.com/pingcap/tidb/session.(*LazyTxn).cleanupStmtBuf(0xc005c76f10)
        session/txn.go:154 +0xd6
github.com/pingcap/tidb/session.(*LazyTxn).cleanup(0xc005c76f10)
        session/txn.go:559 +0x1e
github.com/pingcap/tidb/session.(*LazyTxn).reset(0xc0e95ec690?)
        session/txn.go:554 +0x1e
github.com/pingcap/tidb/session.(*LazyTxn).Commit(0xc005c76f10, {0x5266f98, 0xc0e8c5f2f0})
        session/txn.go:425 +0x69d
github.com/pingcap/tidb/session.(*session).commitTxnWithTemporaryData(0x5266f98?, {0x5266f98, 0xc0e8c5f2f0}, {0x52d74b8, 0xc005c76f10})
        session/session.go:832 +0x230
github.com/pingcap/tidb/session.(*session).doCommit(0xc005c76f00, {0x5266f98, 0xc0e8398210})
        session/session.go:718 +0xd85
github.com/pingcap/tidb/session.(*session).doCommitWithRetry(0xc005c76f00, {0x5266f98, 0xc0e8398210})
        session/session.go:964 +0x2d7
github.com/pingcap/tidb/session.(*session).CommitTxn(0xc005c76f00, {0x5266f98, 0xc0e626df50})
        session/session.go:1094 +0x238
github.com/pingcap/tidb/session.autoCommitAfterStmt({0x5266f98?, 0xc0e626df50?}, 0xc005c76f00, {0x0?, 0x0?}, {0x52792c0?, 0xc07526cd20})
        session/tidb.go:283 +0x40c
github.com/pingcap/tidb/session.finishStmt({0x5266f98, 0xc0e626df50}, 0xc005c76f00, {0x0, 0x0}, {0x52792c0, 0xc07526cd20?})
        session/tidb.go:249 +0x27f
github.com/pingcap/tidb/session.runStmt({0x5266f98, 0xc0e626df50}, 0xc005c76f00, {0x52792c0, 0xc07526cd20?})
        session/session.go:2370 +0x92d
github.com/pingcap/tidb/session.(*session).ExecuteStmt(0xc005c76f00, {0x5266f98, 0xc0e626df50}, {0x527fab8?, 0xc0e838e730?})
        session/session.go:2215 +0xb5e
github.com/pingcap/tidb/session.(*session).ExecuteInternal(0xc005c76f00, {0x5266f98, 0xc0e626df50}, {0x4acbe31, 0x6}, {0x0, 0x0, 0x0})
        session/session.go:1668 +0x3f2
github.com/pingcap/tidb/statistics/handle.finishTransaction({0x5266f98?, 0xc0e626df50?}, {0x526e5a0?, 0xc005c76f00?}, {0x0?, 0x0?})
        statistics/handle/ddl.go:341 +0xb5
github.com/pingcap/tidb/statistics/handle.(*Handle).dumpTableStatCountToKV.func2()
        statistics/handle/update.go:542 +0x39
github.com/pingcap/tidb/statistics/handle.(*Handle).dumpTableStatCountToKV(0xc023795600, 0x231, {0x140, 0x140, 0xc068c3f380, {0x0, 0x0, 0x0}, 0x0})
        statistics/handle/update.go:587 +0x57a
github.com/pingcap/tidb/statistics/handle.(*Handle).DumpStatsDeltaToKV(0xc023795600, 0x0)
        statistics/handle/update.go:500 +0x2f2
github.com/pingcap/tidb/domain.(*Domain).updateStatsWorker(0xc09c7ea480, {0x52d9040?, 0xc005c76f00?}, {0x5285d08?, 0xc0138a66e0?})
        domain/domain.go:2074 +0x6ba
github.com/pingcap/tidb/domain.(*Domain).UpdateTableStatsLoop.func2()
        domain/domain.go:1913 +0x2d
github.com/pingcap/tidb/util.(*WaitGroupEnhancedWrapper).Run.func1()
        util/wait_group_wrapper.go:96 +0x77
created by github.com/pingcap/tidb/util.(*WaitGroupEnhancedWrapper).Run
        util/wait_group_wrapper.go:91 +0xcc
```
### 4. What is your TiDB version? (Required)

https://github.com/pingcap/tidb/pull/40542

**Comment by hawkingrei** [comment] 2023-02-02 11:16
It can be recurrented by addindex test in the with-real-tikv tests.

**Comment by hawkingrei** [comment] 2024-02-20 04:16
I haven't seen this kind of error in a long time. If there are no updates the next time I check this issue, I will close the issue.

**Comment by qw4990** [comment] 2024-04-28 06:40
Can't reproduce it again, it might be fixed by https://github.com/pingcap/tidb/issues/46905

**Closed by qw4990** 2024-04-28 06:40 UTC
Labels: type/bug, sig/planner, component/test, severity/major, affects-6.6, affects-7.0, affects-7.1, affects-7.5, affects-8.1
