### ISSUE TITLE
index out of range [0] with length 0

### ISSUE THREAD

**Issue by gauss1314** [pingcap/tidb#16156] opened 2020-04-08 04:04 UTC
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. What did you do?

Run `/run-integration-copr-test` CI unstable.

### 2. What did you expect to see?

Test pass.

### 3. What did you see instead?

[2020-04-08T03:39:23.387Z] 2020/04/08 11:39:23 2020/04/08 11:39:19 Test fail: Outputs are not matching.

```
[2020-04-08T03:39:23.387Z] 2020/04/08 11:39:23 2020/04/08 11:39:19 Test fail: Outputs are not matching.
[2020-04-08T03:39:23.387Z] Test case: sql/randgen-topn/3_compare_1.sql
[2020-04-08T03:39:23.387Z] Statement: #819 -  SELECT STRCMP( '23:10:42.007765', `col_bigint_unsigned` ) AS field1, `col_varbinary_32` NOT LIKE `col_set` AS field2, `col_tinyint_unsigned_key` IS FALSE AS field3, ( INTERVAL( `col_bit`, ( INTERVAL( '2018-04-26 10:38:03.031949', `col_char_2`, NULL ) ), `col_varchar_1_key` ) ) NOT BETWEEN NULL AND NULL AS field4, COALESCE( '2018-04-27', -26901, ( `col_float_unsigned_key` <=> ( `col_float_unsigned_key` > 'pcbqbfmwpebbkyfsxemhlybhtahsdfttztbnrqjpdtwjharagadcroqtxlefjrhcokdymxvanwfvayfdbhtoxwppiavhgmizbrrxgafhbcxkosudjiyckygmuatynejcqwwbclkmfhgrrenyxlyawqekkchtjzebuphvkwswxbtqsjokzalmxfaklbeukgslyqnrheytuhbqsbseiojnyxesmnsdfyyisxjoljtdmdxwycmyxfnxnojmst' ) ), `col_binary_8_key`, `col_char_255` ) AS field5 FROM `table1000_int_autoinc` WHERE COALESCE( `col_blob`, '2030-01-04', `col_decimal_key` ) ORDER BY field1, field2, field3, field4, field5 LIMIT 3 /* QNO 824 CON_ID 112 */ ;
[2020-04-08T03:39:23.387Z] NoPushDown Output: 
[2020-04-08T03:39:23.387Z] Error 1105: runtime error: index out of range [0] with length 0
[2020-04-08T03:39:23.387Z] 
[2020-04-08T03:39:23.387Z] WithPushDown Output: 
[2020-04-08T03:39:23.387Z] field1	field2	field3	field4	field5
[2020-04-08T03:39:23.388Z] NULL	NULL	0	NULL	2018-04-27
[2020-04-08T03:39:23.388Z] NULL	NULL	0	NULL	2018-04-27
[2020-04-08T03:39:23.388Z] NULL	NULL	0	NULL	2018-04-27
```

### 4. What version of TiDB are you using? (`tidb-server -V` or run `select tidb_version();` on TiDB)

https://github.com/pingcap/tidb/pull/15540

**Comment by zz-jason** [comment] 2020-04-14 16:10
@XuHuaiyu PTAL

**Comment by zhongzc** [comment] 2020-04-17 07:26
Another similar case
```
[2020-04-17T06:45:18.318Z] Test case: sql/randgen-topn/3_compare_2.sql
[2020-04-17T06:45:18.318Z] Statement: #959 -  SELECT ( ( 'aiwmuqfchzszddfaqjdgkrjtyhfhgepsixklrmhckuspqsbokrrnpkdsxbjvezbeypduqxzeryrezolezoxmxflabucnzpgmasydurzmvfcbncknandqlmqvjswecspoxqcooxqjspycqobvdjofeqjf' != `col_timestamp_key` ) = ( INTERVAL( ( ( ( ( `col_decimal` <= `col_year` ) IN ( 0, '2011-07-07 21:08:02.017744', `col_tinyint_key` ) ) != 'h' ) NOT LIKE `col_decimal_unsigned` ), '1989-09-06', 'b', 0, `col_varbinary_32_key` ) ) ) <=> -6234389259164319744 AS field1 FROM `table1000_int_autoinc`  ORDER BY field1 LIMIT 1 /* QNO 961 CON_ID 196 */ ;
[2020-04-17T06:45:18.319Z] NoPushDown Output: 
[2020-04-17T06:45:18.319Z] field1
[2020-04-17T06:45:18.319Z] 0
[2020-04-17T06:45:18.319Z] 
[2020-04-17T06:45:18.319Z] 
[2020-04-17T06:45:18.319Z] WithPushDown Output: 
[2020-04-17T06:45:18.319Z] Error 1105: runtime error: index out of range [1] with length 1
```

**Comment by qw4990** [comment] 2020-04-21 11:21
Using the `copr-test` dataset, I can't reproduce the problem.
I think it may be fixed by some other PR and it is hard to investigate this problem if we can not reproduce it, so I close this issue now and if it occurs in the future, I will reopen this issue and investigate this problem again. @gauss1314

**Comment by qw4990** [comment] 2020-04-21 12:31
Here is a stack of this problem:
```
[2020-04-21T09:34:11.894Z] [2020/04/21 17:32:46.400 +08:00] [ERROR] [conn.go:730] ["command dispatched failed"] [conn=53] [connInfo="id:53, addr:127.0.0.1:12532 status:10, collation:utf8_general_ci, user:root"] [command=Query] [status="inTxn:0, autocommit:1"] [sql=" SELECT ( INTERVAL( ( `col_tinyint_unsigned` <> `col_char_2_key` ), NULL, `col_double_unsigned_key`, NULL, ( ( LEAST( `pk`, ( `col_time` > `col_tinyint_unsigned_key` ), `col_int_unsigned_key`, `col_decimal_unsigned`, `col_double_unsigned` ) ) LIKE `col_int` ) ) ) != ( INTERVAL( NULL, `col_char_2_key`, '2031-06-08 10:24:36.039888' ) ) AS field1 FROM `table1000_int_autoinc`  ORDER BY field1 LIMIT 4 /* QNO 15 CON_ID 196 */ ;"] [txn_mode=PESSIMISTIC] [err="runtime error: index out of range [1] with length 1
github.com/pingcap/tidb/executor.recoveryProjection
	/home/jenkins/agent/workspace/tidb_ghpr_integration_copr_test/tidb/executor/projection.go:440
github.com/pingcap/tidb/executor.(*projectionWorker).run.func1
	/home/jenkins/agent/workspace/tidb_ghpr_integration_copr_test/tidb/executor/projection.go:409
runtime.gopanic
	/usr/local/go/src/runtime/panic.go:679
runtime.goPanicIndex
	/usr/local/go/src/runtime/panic.go:75
github.com/pingcap/tidb/util/stringutil.DoMatch
	/home/jenkins/agent/workspace/tidb_ghpr_integration_copr_test/tidb/util/stringutil/string_util.go:243
github.com/pingcap/tidb/util/collate.(*binPattern).DoMatch
	/home/jenkins/agent/workspace/tidb_ghpr_integration_copr_test/tidb/util/collate/bin.go:69
github.com/pingcap/tidb/expression.(*builtinLikeSig).evalInt
	/home/jenkins/agent/workspace/tidb_ghpr_integration_copr_test/tidb/expression/builtin_like.go:95
github.com/pingcap/tidb/expression.(*ScalarFunction).EvalInt
	/home/jenkins/agent/workspace/tidb_ghpr_integration_copr_test/tidb/expression/scalar_function.go:349
github.com/pingcap/tidb/expression.(*builtinCastIntAsRealSig).evalReal
	/home/jenkins/agent/workspace/tidb_ghpr_integration_copr_test/tidb/expression/builtin_cast.go:461
github.com/pingcap/tidb/expression.(*ScalarFunction).EvalReal
	/home/jenkins/agent/workspace/tidb_ghpr_integration_copr_test/tidb/expression/scalar_function.go:354
github.com/pingcap/tidb/expression.(*builtinIntervalRealSig).binSearch
	/home/jenkins/agent/workspace/tidb_ghpr_integration_copr_test/tidb/expression/builtin_compare.go:943
github.com/pingcap/tidb/expression.(*builtinIntervalRealSig).vecEvalInt
	/home/jenkins/agent/workspace/tidb_ghpr_integration_copr_test/tidb/expression/builtin_compare_vec.go:469
github.com/pingcap/tidb/expression.(*ScalarFunction).VecEvalInt
	/home/jenkins/agent/workspace/tidb_ghpr_integration_copr_test/tidb/expression/scalar_function.go:51
github.com/pingcap/tidb/expression.(*builtinNEIntSig).vecEvalInt
	/home/jenkins/agent/workspace/tidb_ghpr_integration_copr_test/tidb/expression/builtin_compare_vec.go:329
github.com/pingcap/tidb/expression.(*ScalarFunction).VecEvalInt
	/home/jenkins/agent/workspace/tidb_ghpr_integration_copr_test/tidb/expression/scalar_function.go:51
github.com/pingcap/tidb/expression.evalOneVec
	/home/jenkins/agent/workspace/tidb_ghpr_integration_copr_test/tidb/expression/chunk_executor.go:123
github.com/pingcap/tidb/expression.(*defaultEvaluator).run
	/home/jenkins/agent/workspace/tidb_ghpr_integration_copr_test/tidb/expression/evaluator.go:51
github.com/pingcap/tidb/expression.(*EvaluatorSuite).Run
	/home/jenkins/agent/workspace/tidb_ghpr_integration_copr_test/tidb/expression/evaluator.go:123
github.com/pingcap/tidb/executor.(*projectionWorker).run
	/home/jenkins/agent/workspace/tidb_ghpr_integration_copr_test/tidb/executor/projection.go:426
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1357"]
```

It has the same root cause with issue https://github.com/pingcap/tidb/issues/15810, and can be solved by https://github.com/pingcap/tidb/pull/16600.

**Comment by zz-jason** [comment] 2020-04-21 14:07
@qw4990 Could you update the PR description of #16600, make GitHub be able to automatically close this issue when that PR is merged?

**Closed** 2020-05-06 13:22 UTC
Labels: component/expression, priority/P1, type/bug

**Comment by ChenPeng2013** [comment] 2020-05-22 03:30
I can't reproduce the problem
Verified on another similar issue https://github.com/pingcap/tidb/issues/15810
