### ISSUE TITLE
Trace UI broken

### ISSUE THREAD

**Issue by breeswish** [pingcap/tidb#10965] opened 2019-06-27 09:43 UTC
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

Following steps in https://github.com/pingcap/docs-cn/blob/master/dev/reference/sql/statements/trace.md

2. What did you expect to see?

Traces as shown in doc

3. What did you see instead?

![image](https://user-images.githubusercontent.com/1916485/60255731-dee45100-9902-11e9-9768-5b56312ee6fe.png)

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

```
$ bin/tidb-server -V       
Release Version: v3-21-g0d563f1e2-dirty
Git Commit Hash: 0d563f1e2d785d25cc812adae6e6c95514ba5f3d
Git Branch: master
UTC Build Time: 2019-06-27 07:39:20
GoVersion: go version go1.12.5 darwin/amd64
Race Enabled: false
TiKV Min Version: 2.1.0-alpha.1-ff3dd160846b7d1aed9079c389fc188f7f5ea13e
Check Table Before Drop: false
```

**Comment by tiancaiamao** [comment] 2019-07-01 05:47
I guess it's because the SQL output is truncated into multiple lines.
Would you please provide the json data? @breeswish

**Comment by breeswish** [comment] 2019-07-01 05:49
Any SQL doesn't work. I think the root cause should be in my posted image: it uses 0.0.0.0 for all assets, where in Mac 0.0.0.0 is not accessible.

**Comment by tiancaiamao** [comment] 2019-07-01 07:12
Get it. Thanks for your report, I'll fix it later.

**Comment by nullnotnil** [comment] 2020-07-12 20:04
I can confirm that `0.0.0.0` is still used for assets in master. Does it make sense to close this as won't fix, since GUI functions are now in the dashboard?

**Comment by breeswish** [comment] 2020-07-13 02:03
Currently Dashboard does not have trace UI, so that this functionality is not useable in fact. In 5.0 plans there is no trace UI as well. How about keeping it open until something has been planned (so that this issue can link to another open issue), or it is actually fixed?

**Comment by tiancaiamao** [comment] 2020-07-13 02:11
> How about keeping it open until something has been planned (so that this issue can link to another open issue), or it is actually fixed?

It sounds reasonable.

**Comment by tiancaiamao** [comment] 2020-11-27 11:25
I'd like to change the default output format of the trace statement to 'row', so as to avoid the troublesome JSON format output.

https://github.com/pingcap/parser/pull/1107

**Comment by bb7133** [comment] 2021-11-25 02:49
Close this issue because of #1107

**Closed by bb7133** 2021-11-25 02:49 UTC
Labels: type/bug, sig/sql-infra, severity/moderate
