### ISSUE TITLE
blocking issues at `TestT` of ddl/ddl_test.go

### ISSUE THREAD

**Issue by charlesxsh** [pingcap/tidb#27001] opened 2021-08-09 01:36 UTC
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
Run the test `TestT` of ddl/ddl_test.go.

### 2. What did you expect to see? (Required)
no blocking issue during/at the exit of testing.

### 3. What did you see instead (Required)
The blocking issues at

github.com/pingcap/badger@v1.5.1-0.20200908111422-2e78ee155d19/value.go:495
```go
func (req *request) Wait() error {
	req.Wg.Wait()   <------ line 495
	req.Entries = nil
	err := req.Err
	requestPool.Put(req)
	return err
}
```

github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:752
```go
func (runner *suiteRunner) runFunc(method *methodType, kind funcKind, testName string, logb *logger, dispatcher func(c *C)) *C {
	c := runner.forkCall(method, kind, testName, logb, dispatcher)
	<-c.done   <------ line 752
	return c
}
```
### 4. What is your TiDB version? (Required)
commit b8107d7

These blocking issues might or might not directly caused by the usages of third party libraries, please take a look and redirect to the corresponding repository if possible, thanks.

**Comment by bb7133** [comment] 2021-12-07 06:19
@charlesxsh  I cannot reproduce this issue for now, and I will close it for now. Feel free to reopen it if it can be reproduced, thanks!

**Closed by bb7133** 2021-12-07 06:19 UTC
Labels: type/bug, component/test, sig/sql-infra, severity/major
