### ISSUE TITLE
make test failed

### ISSUE THREAD

**Issue by ngaut** [pingcap/tidb#10187] opened 2019-04-18 05:19 UTC
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
make test

2. What did you expect to see?
all tests passed

3. What did you see instead?
a few tests failed

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
latest master, git hash 13290a239aff5eeb88199841de943d3a60600554

See the output of make test:
[test.log](https://github.com/pingcap/tidb/files/3092835/test.log)

**Comment by winoros** [comment] 2019-04-18 05:25
This may be caused by that the memory of your computer is not enough. You can try to clean the memory first.

**Comment by ngaut** [comment] 2019-04-18 05:45
There is another test failed too. 

FAIL: tidb_test.go:297: TidbTestSuite.TestTLS

tidb_test.go:351:
    c.Assert(err, IsNil)
... value *net.OpError = &net.OpError{Op:"remote error", Net:"", Source:net.Addr(nil), Addr:net.Addr(nil), Err:0x28} ("remote error: tls: handshake failure")

**Comment by ngaut** [comment] 2019-04-18 05:47
Why we need so much memory to do unit tests? Can we reduce the memory consuming?

**Comment by winoros** [comment] 2019-04-18 06:02
@ngaut 
I think this may not be caused by that the unit test needs a lot of memory. Just because the original memory usage before you run tests is high? 
There's a check when insert things into the LRU cache. If the used memory is higher than 90%. It will fail to insert.

For another problem, @tiancaiamao PTAL

**Comment by ngaut** [comment] 2019-04-18 08:53
Another failed test.

FAIL: session_fail_test.go:95: testSessionSuite.TestGetTSFailDirtyStateInretry

session_fail_test.go:105:
    tk.MustQuery(`select * from t`).Check(testkit.Rows("2"))
/go/src/github.com/pingcap/tidb/util/testkit/testkit.go:183:
    tk.c.Assert(errors.ErrorStack(err), check.Equals, "", comment)
... obtained string = "" +
...     "PD server timeout[try again later]\n" +
...     "github.com/pingcap/tidb/session.(*txnFuture).wait\n" +
...     "\t/go/src/github.com/pingcap/tidb/session/txn.go:361\n" +
...     "github.com/pingcap/tidb/session.(*TxnState).changePendingToValid\n" +
...     "\t/go/src/github.com/pingcap/tidb/session/txn.go:129\n" +
...     "github.com/pingcap/tidb/session.(*session).Txn\n" +
...     "\t/go/src/github.com/pingcap/tidb/session/session.go:1110\n" +
...     "github.com/pingcap/tidb/executor.(*executorBuilder).getStartTS\n" +
...     "\t/go/src/github.com/pingcap/tidb/executor/builder.go:1112\n" +
...     "github.com/pingcap/tidb/executor.(*executorBuilder).constructDAGReq\n" +
...     "\t/go/src/github.com/pingcap/tidb/executor/builder.go:1507\n" +
...     "github.com/pingcap/tidb/executor.buildNoRangeTableReader\n" +
...     "\t/go/src/github.com/pingcap/tidb/executor/builder.go:1629\n" +
...     "github.com/pingcap/tidb/executor.(*executorBuilder).buildTableReader\n" +
...     "\t/go/src/github.com/pingcap/tidb/executor/builder.go:1672\n" +
...     "github.com/pingcap/tidb/executor.(*executorBuilder).build\n" +
...     "\t/go/src/github.com/pingcap/tidb/executor/builder.go:174\n" +
...     "github.com/pingcap/tidb/executor.(*ExecStmt).buildExecutor\n" +
...     "\t/go/src/github.com/pingcap/tidb/executor/adapter.go:350\n" +
...     "github.com/pingcap/tidb/executor.(*ExecStmt).Exec\n" +
...     "\t/go/src/github.com/pingcap/tidb/executor/adapter.go:222\n" +
...     "github.com/pingcap/tidb/session.runStmt\n" +
...     "\t/go/src/github.com/pingcap/tidb/session/tidb.go:213\n" +
...     "github.com/pingcap/tidb/session.(*session).executeStatement\n" +
...     "\t/go/src/github.com/pingcap/tidb/session/session.go:907\n" +
...     "github.com/pingcap/tidb/session.(*session).execute\n" +
...     "\t/go/src/github.com/pingcap/tidb/session/session.go:981\n" +
...     "github.com/pingcap/tidb/session.(*session).Execute\n" +
...     "\t/go/src/github.com/pingcap/tidb/session/session.go:930\n" +
...     "github.com/pingcap/tidb/util/testkit.(*TestKit).Exec\n" +
...     "\t/go/src/github.com/pingcap/tidb/util/testkit/testkit.go:137\n" +
...     "github.com/pingcap/tidb/util/testkit.(*TestKit).MustQuery\n" +
...     "\t/go/src/github.com/pingcap/tidb/util/testkit/testkit.go:182\n" +
...     "github.com/pingcap/tidb/session_test.(*testSessionSuite).TestGetTSFailDirtyStateInretry\n" +
...     "\t/go/src/github.com/pingcap/tidb/session/session_fail_test.go:105\n" +
...     "reflect.Value.call\n" +
...     "\t/usr/local/go/src/reflect/value.go:447\n" +
...     "reflect.Value.Call\n" +
...     "\t/usr/local/go/src/reflect/value.go:308\n" +
...     "github.com/pingcap/check.(*suiteRunner).forkTest.func1\n" +
...     "\t/go/pkg/mod/github.com/pingcap/check@v0.0.0-20190102082844-67f458068fc8/check.go:836\n" +
...     "github.com/pingcap/check.(*suiteRunner).forkCall.func1\n" +
...     "\t/go/pkg/mod/github.com/pingcap/check@v0.0.0-20190102082844-67f458068fc8/check.go:730\n" +
...     "runtime.goexit\n" +
...     "\t/usr/local/go/src/runtime/asm_amd64.s:1337"
... expected string = ""
... sql:select * from t, args:[]


Full log:
[build_36404_step_102_container_0.txt](https://github.com/pingcap/tidb/files/3093536/build_36404_step_102_container_0.txt)

**Comment by ngaut** [comment] 2019-04-22 03:19
One more failed test.
See https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tidb_ghpr_unit_test/detail/tidb_ghpr_unit_test/2565/pipeline

**Comment by shenli** [comment] 2019-04-22 13:08
> One more failed test.
> See https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tidb_ghpr_unit_test/detail/tidb_ghpr_unit_test/2565/pipeline

Fixed in https://github.com/pingcap/tidb/pull/10211

**Closed** 2019-04-27 10:53 UTC
Labels: priority/P2, type/bug
