### ISSUE TITLE
(*MPPDataPacket).Unmarshal consumes too much memory and causes OOM

### ISSUE THREAD

**Issue by xuyifangreeneyes** [pingcap/tidb#37049] opened 2022-08-11 08:21 UTC
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
When generating the table `lineorder_flat` for SSB test, first use dumpling to export the join results and then use lightning to import the join results to TiDB. The first step(dumpling) can cause OOM when TiDB Server has 64GB memory. The join results are about 6 billion rows.
```
nohup ./dumpling -u root -P 4000 -h 127.0.0.1 --filetype csv -t 4 -r 8 -o /home/lineorder_flat -F256MiB --params "tidb_distsql_scan_concurrency=5,tidb_enable_chunk_rpc=0" --sql 'use ssb;set @@tidb_batch_insert=on;set @@global.tidb_enable_batch_dml=1;set @@tidb_dml_batch_size=1000;SELECT
l.LO_ORDERKEY AS LO_ORDERKEY,
l.LO_ORDERDATE AS LO_ORDERDATE,
l.LO_LINENUMBER AS LO_LINENUMBER,
l.LO_CUSTKEY AS LO_CUSTKEY,
l.LO_PARTKEY AS LO_PARTKEY,
l.LO_SUPPKEY AS LO_SUPPKEY,
l.LO_ORDERPRIORITY AS LO_ORDERPRIORITY,
l.LO_SHIPPRIORITY AS LO_SHIPPRIORITY,
l.LO_QUANTITY AS LO_QUANTITY,
l.LO_EXTENDEDPRICE AS LO_EXTENDEDPRICE,
l.LO_ORDTOTALPRICE AS LO_ORDTOTALPRICE,
l.LO_DISCOUNT AS LO_DISCOUNT,
l.LO_REVENUE AS LO_REVENUE,
l.LO_SUPPLYCOST AS LO_SUPPLYCOST,
l.LO_TAX AS LO_TAX,
l.LO_COMMITDATE AS LO_COMMITDATE,
l.LO_SHIPMODE AS LO_SHIPMODE,
c.C_NAME AS C_NAME,
c.C_ADDRESS AS C_ADDRESS,
c.C_CITY AS C_CITY,
c.C_NATION AS C_NATION,
c.C_REGION AS C_REGION,
c.C_PHONE AS C_PHONE,
c.C_MKTSEGMENT AS C_MKTSEGMENT,
s.S_NAME AS S_NAME,
s.S_ADDRESS AS S_ADDRESS,
s.S_CITY AS S_CITY,
s.S_NATION AS S_NATION,
s.S_REGION AS S_REGION,
s.S_PHONE AS S_PHONE,
p.P_NAME AS P_NAME,
p.P_MFGR AS P_MFGR,
p.P_CATEGORY AS P_CATEGORY,
p.P_BRAND AS P_BRAND,
p.P_COLOR AS P_COLOR,
p.P_TYPE AS P_TYPE,
p.P_SIZE AS P_SIZE,
p.P_CONTAINER AS P_CONTAINER
FROM lineorder AS l
INNER JOIN customer AS c ON c.C_CUSTKEY = l.LO_CUSTKEY
INNER JOIN supplier AS s ON s.S_SUPPKEY = l.LO_SUPPKEY
INNER JOIN part AS p ON p.P_PARTKEY = l.LO_PARTKEY' 2>&1 >nohup.log &
```

### 2. What did you expect to see? (Required)
Dumpling exports the join results successfully.

### 3. What did you see instead (Required)
OOM occurs when dumpling is exporting the join results. We can see from memory profiling that `(*MPPDataPacket).Unmarshal` consumes too much memory.

<img width="988" alt="mm1" src="https://user-images.githubusercontent.com/30385241/184091198-6de6e0b7-5c22-48e6-87db-9477f4bdef33.png">
<img width="115" alt="mm2" src="https://user-images.githubusercontent.com/30385241/184091207-96a1580a-6ad0-4970-8b34-6edaf9be2ffb.png">
<img width="302" alt="mm3" src="https://user-images.githubusercontent.com/30385241/184091217-adcca099-8861-4ed6-aff8-6616543b0c91.png">

### 4. What is your TiDB version? (Required)
v6.1.0

**Comment by xuyifangreeneyes** [comment] 2022-08-11 08:26
cc @XuHuaiyu

**Comment by wshwsh12** [comment] 2023-01-10 08:30
duplicate of https://github.com/pingcap/tidb/issues/34143

**Closed** 2023-01-10 08:30 UTC
Labels: type/bug, sig/execution, severity/moderate, component/tiflash, may-affects-4.0, may-affects-5.1, may-affects-5.2, may-affects-5.3, may-affects-5.4, may-affects-5.0, may-affects-6.0, affects-6.1, may-affects-6.2
