### ISSUE TITLE
Index fails when using ‘or’

### ISSUE THREAD

**Issue by Mingdr** [pingcap/tidb#12973] opened 2019-10-28 10:30 UTC
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
`
CREATE TABLE `index_a` (
  `a` varchar(20) DEFAULT NULL,
  `b` varchar(20) DEFAULT NULL,
  KEY `index_a` (`a`),
  KEY `index_b` (`b`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

insert into index_a select 'a','a';
insert into index_a select 'a','b';
insert into index_a select 'b','b';
insert into index_a select 'b','a';
insert into index_a select 'c','c';

EXPLAIN
select * from index_a force index (index_a,index_b) where (a = 'a' or b='b');
IndexLookUp_8	4.00	root	
├─IndexScan_5	5.00	cop	table:index_a, index:a, range:[NULL,+inf], keep order:false, stats:pseudo
└─Selection_7	4.00	cop	or(eq(test.index_a.a, "a"), eq(test.index_a.b, "b"))
  └─TableScan_6	5.00	cop	table:index_a, keep order:false, stats:pseudo
EXPLAIN
select * from index_a  where (a = 'a' or b='b');
TableReader_7	4.00	root	data:Selection_6
└─Selection_6	4.00	cop	or(eq(test.index_a.a, "a"), eq(test.index_a.b, "b"))
  └─TableScan_5	5.00	cop	table:index_a, range:[-inf,+inf], keep order:false, stats:pseudo
EXPLAIN
select * from index_a where a = 'a' ;
IndexLookUp_10	0.01	root	
├─IndexScan_8	0.01	cop	table:index_a, index:a, range:["a","a"], keep order:false, stats:pseudo
└─TableScan_9	0.01	cop	table:index_a, keep order:false, stats:pseudo
EXPLAIN
select * from index_a where b ='b';
IndexLookUp_10	0.01	root	
├─IndexScan_8	0.01	cop	table:index_a, index:b, range:["b","b"], keep order:false, stats:pseudo
└─TableScan_9	0.01	cop	table:index_a, keep order:false, stats:pseudo
`

2. What did you expect to see?
`IndexScan_5	5.00	cop	table:index_a, index:a, range:[NULL,+inf], keep order:false` maybe like 
`IndexScan_8	0.01	cop	table:index_a, index:a, range:["a","a"], keep order:false, stats:pseudo`
when I use  'force index (index_a,index_b) '.

3. What did you see instead?
`range:[NULL,+inf]`
It's deadly when there's a lot of data

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

Release Version: v3.0.4
Git Commit Hash: 694e086e7914a8fc0eb601327edb6bcc31d2c7f2
Git Branch: HEAD
UTC Build Time: 2019-10-08 08:13:34
GoVersion: go version go1.12.10 linux/amd64
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false

**Comment by francis0407** [comment] 2019-10-28 11:15
Actually, the query `select * from t where a = 'a' or b = 'b'` cannot use the index on 'a' or 'b'. When you use `force index (index_a,index_b)`, the `Selection` is on top of `TableScan`, not `IndexScan`.

I think this is NOT a BUG.

**Comment by Mingdr** [comment] 2019-10-29 04:06
> Actually, the query `select * from t where a = 'a' or b = 'b'` cannot use the index on 'a' or 'b'. When you use `force index (index_a,index_b)`, the `Selection` is on top of `TableScan`, not `IndexScan`.
> 
> I think this is NOT a BUG.

But  it can use the index correctly on mysql, mysql can use `range:["a","a"]`  but tidb use `range:[NULL,+inf]`.

**Comment by francis0407** [comment] 2019-10-29 04:56
I have tried this in MySQL, it doesn't use any of the index.
```
mysql> create table index_a (a varchar(20), b varchar(20), key index_a(a), key index_b(b));
Query OK, 0 rows affected (0.03 sec)

mysql> explain select * from index_a where a = 'a' or b = 'b';
+----+-------------+---------+------------+------+-----------------+------+---------+------+------+----------+-------------+
| id | select_type | table   | partitions | type | possible_keys   | key  | key_len | ref  | rows | filtered | Extra       |
+----+-------------+---------+------------+------+-----------------+------+---------+------+------+----------+-------------+
|  1 | SIMPLE      | index_a | NULL       | ALL  | index_a,index_b | NULL | NULL    | NULL |    1 |   100.00 | Using where |
+----+-------------+---------+------------+------+-----------------+------+---------+------+------+----------+-------------+
1 row in set, 1 warning (0.01 sec)
```

Are there anything I missed?

**Comment by SunRunAway** [comment] 2019-10-29 05:24
Is it a duplicate to https://github.com/pingcap/tidb/issues/9019 ? @francis0407

**Comment by francis0407** [comment] 2019-10-29 05:37
@SunRunAway Sure, `IndexMergePath` is a solution.

**Comment by Mingdr** [comment] 2019-10-29 05:55
> I have tried this in MySQL, it doesn't use any of the index.
> 
> ```
> mysql> create table index_a (a varchar(20), b varchar(20), key index_a(a), key index_b(b));
> Query OK, 0 rows affected (0.03 sec)
> 
> mysql> explain select * from index_a where a = 'a' or b = 'b';
> +----+-------------+---------+------------+------+-----------------+------+---------+------+------+----------+-------------+
> | id | select_type | table   | partitions | type | possible_keys   | key  | key_len | ref  | rows | filtered | Extra       |
> +----+-------------+---------+------------+------+-----------------+------+---------+------+------+----------+-------------+
> |  1 | SIMPLE      | index_a | NULL       | ALL  | index_a,index_b | NULL | NULL    | NULL |    1 |   100.00 | Using where |
> +----+-------------+---------+------------+------+-----------------+------+---------+------+------+----------+-------------+
> 1 row in set, 1 warning (0.01 sec)
> ```
> 
> Are there anything I missed?

use `force index (index_a,index_b)`

`EXPLAIN
select * from index_a force index (index_a,index_b) where (a = 'a' or b='b');`

**Comment by francis0407** [comment] 2019-10-29 06:00
OK, thanks. I reproduce the result, it uses a union on both keys. 
Then this issue is duplicate to #9019. We're already working on this. Thanks for your feedback again.

**Comment by Mingdr** [comment] 2019-10-29 06:03
> OK, thanks. I reproduce the result, it uses a union on both keys.
> Then this issue is duplicate to #9019. We're already working on this. Thanks for your feedback again.

Thanks ~~

**Comment by SunRunAway** [comment] 2019-10-29 06:27
Duplicate of #9010

**Closed** 2019-10-29 06:27 UTC
Labels: type/bug
