### ISSUE TITLE
unit test testPlanSuite.TestAggToCopHint fails

### ISSUE THREAD

**Issue by glorv** [pingcap/tidb#14730] opened 2020-02-11 08:45 UTC
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
```
[2020-02-11T06:53:33.178Z] ----------------------------------------------------------------------

[2020-02-11T06:53:33.178Z] FAIL: physical_plan_test.go:784: testPlanSuite.TestAggToCopHint

[2020-02-11T06:53:33.178Z] 

[2020-02-11T06:53:33.178Z] physical_plan_test.go:824:

[2020-02-11T06:53:33.178Z]     c.Assert(planString, Equals, output[i].Best, comment)

[2020-02-11T06:53:33.178Z] ... obtained string = "TableReader(Table(t))->Projection"

[2020-02-11T06:53:33.178Z] ... expected string = "TableReader(Table(t)->HashAgg)->HashAgg"

[2020-02-11T06:53:33.178Z] ... case:0 sql:select /*+ AGG_TO_COP(), HASH_AGG(), USE_INDEX(t) */ sum(a) from t group by a
[2020-02-11T06:53:33.178Z] ----------------------------------------------------------------------
```

2. What did you expect to see?

3. What did you see instead?

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
 https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tidb_ghpr_unit_test/detail/tidb_ghpr_unit_test/23709/pipeline/70
 https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tidb_ghpr_unit_test/detail/tidb_ghpr_unit_test/23697/pipeline/70

**Comment by SunRunAway** [comment] 2020-02-11 09:18
Duplicate of #14472

**Closed by SunRunAway** 2020-02-11 09:18 UTC
Labels: component/planner, component/test, type/bug
