### ISSUE TITLE
TiDB Dumpling: Not export lastest version when read historical data snapshot

### ISSUE THREAD

**Issue by noradomi** [pingcap/tidb#39578] opened 2022-12-02 04:44 UTC
### What is your TiDB version? 
```
Release Version: v5.4.1
Edition: Community
Git Commit Hash: be484475e76b3aaa2cad520111353c3327db35fa
Git Branch: heads/refs/tags/v5.4.1
UTC Build Time: 2022-05-07 04:31:32
GoVersion: go1.16.4
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
```
### What version of Dumpling are you using?
Same as TiDB version.

### What did you do?
I try to use Dumpling tool to export historical data of TiDB at a certain time [link](https://docs.pingcap.com/tidb/stable/dumpling-overview#export-historical-data-snapshot-of-tidb).

My database have two tables: account and transaction_log. Each transaction will include 2 operations: update account table + insert transaction_log for related account_ids.

| Account        | 
| ------------------- |
| id |
| balance            |
| recorded_time            |

| Transaction_log           | 
| ------------------- |
| id |
| sender_id            |
| receiver_id            |
| amount |
| recorded_time            |

I do dump all data of account table. We started dumpling at `2022-11-24 01:00:00` with snapshot time is set to `2022-11-24 00:00:00`. The `transaction_log` table show the last change related account_id = 1 occured at `2022-11-23 23:59:59.9690`. 

| id | sender_id | receiver_id | amount | recorded_time             |
|----|-----------|-------------|--------|---------------------------|
| 123  | 1         | 2           | 100    | 2022-11-23 23:59:59.9690	 |

So the last updated time of account_id = 1 will also be expected is `2022-11-23 23:59:59.9690`.  But the snapshot data after dumpling of table account show as below, the last updated at `2022-11-23 23:59:43.4700` means not include affect of above transaction `123`.

| id | balance | recorded_time             |
|----|---------|--------------------------|
| 1  | 1000     | 2022-11-23 23:59:43.4700 |

Note that the `recorded_time` field in both 2 tables is set the same by physical time extracted from `start_ts` value as the `@@tidb_current_ts` session variable inside a transaction.
So, the `2022-11-23 23:59:59.9690` must be latest version of stored data of account_id = 1 and it also < snapshot_time `2022-11-24 00:00:00`.

Note: Current we use optimistic transaction mode in TiDB.

### What did you expect to see? 
Dumpling data with snapshot time export lastest version of stored data.

### What did you see instead?
Dumpling data with snapshot time don't export lastest version of stored data.

**Comment by lance6716** [comment] 2022-12-02 10:10
Hi, can you set the session variable [tidb_snapshot](https://docs.pingcap.com/tidb/stable/system-variables#tidb_snapshot) manually and query the tables to see if transaction `123` is appeared in `Account`?

**Comment by noradomi** [comment] 2022-12-05 04:13
Hi @lance6716, currently I'm setting [tidb_gc_lifetime](https://docs.pingcap.com/tidb/v5.4/system-variables#tidb_gc_life_time-new-in-v50) to 12h -> so the historical data of 2022-11-23 now is removed.   
But by the way, the data of `transaction_log` table is just appended and with the `recorded_time` field - set by TSO value inside a transaction, I can ensure transaction `123` affected to DB at `2022-11-23 23:59:59.969` (less 31ms compared with snapshot time `2022-11-24 00:00:00`).

And I also check other accounts in dumpling data, I still see there is account with last updated time is `2022-11-23 23:59:59.9190`.  (less 81ms compared with snapshot time `2022-11-24 00:00:00`). So I don't know if this is a bug or can I know max limit lag between the snapshot time with TSO of an transaction in order to it appeared in historical data ? Because as TiDB document, it will read data from the latest version - TSO of transaction before snapshot timestamp. (https://docs.pingcap.com/tidb/stable/read-historical-data#how-tidb-reads-data-from-history-versions).

Note: here is my dumpling script:
```
./dumpling \
  -u "user_name" \
  -p "password" \
  -P "port" \
  -h "host" \
  -o . \
  -t 8 \
  -F 256MiB \
  --consistency snapshot \
  --snapshot "2022-11-24 00:00:00" \
  --filetype csv \
  --sql 'select * from `test.`account`;' \
  --output-filename-template 'test.account.{{.Index}}'
```

**Comment by lance6716** [comment] 2022-12-05 05:35
> We started dumpling at 2022-11-24 01:00:00 with snapshot time is set to 2022-11-24 00:00:00. The transaction_log table show the last change related account_id = 1 occured at 2022-11-23 23:59:59.9690

Is the posted content (id=123, ..., recorded_time=2022-11-23 23:59:59.9690) of `transaction_log` table read from TiDB or from dump data? Please check it in dump data and the expected behaviour is that it is not appeared both in `transaction_log` table and `account` table.

The reason is TiDB has two timestamps: start_ts and commit_ts, the snapshot time `2022-11-24 01:00:00` may be in the middle of the two timestamps of some transactions, so for these transactions they are not committed at the snapshot time. The interval of two timstamps is roughly equal to the "BEGIN" and "COMMIT" SQL statement wall time.

**Comment by noradomi** [comment] 2022-12-05 07:06
@lance6716 
> Is the posted content (id=123, ..., recorded_time=2022-11-23 23:59:59.9690) of transaction_log table read from TiDB or from dump data?
It read from TiDB, I just dump data of the `account` table.

> The reason is TiDB has two timestamps: start_ts and commit_ts, the snapshot time 2022-11-24 01:00:00 may be in the middle of the two timestamps of some transactions, so for these transactions they are not committed at the snapshot time.
Yes, I also gues so. In conclusion, the version of stored data in TiKV for historical data - [MVCC](https://docs.pingcap.com/tidbcloud/tidb-storage#mvcc) will be `commit_ts`, not`start_ts` in each transaction, right?  Our service is using `start_ts` for `recored_time` field and optimistic transaction. mode.

**Comment by lance6716** [comment] 2022-12-05 07:09
MVCC is more related to start_ts, but at `2022-11-24 01:00:00` the transaction is not committed so it's not visible to another transaction, otherwise we will see dirty data

**Comment by noradomi** [comment] 2022-12-05 07:38
@lance6716 The snapshot time is `2022-11-24 00:00:00`. `2022-11-24 01:00:00` is the time I run dump script.

> the transaction is not committed so it's not visible to another transaction, otherwise we will see dirty data.  

Okie, I got it. Because my logic currently based on more `start_ts`, but as your explain, `start_ts` is not completely the time data affected at DB, mean visible to other sessions. Is there a way to get `commit_ts` to set to `recored_time` field in my database ?

**Comment by lance6716** [comment] 2022-12-05 07:41
> Is there a way to get `commit_ts` to set to `recored_time` field in my database ?

No, `commit_ts` is not decided before COMMIT SQL statement, all your interactive transaction actions are performed before COMMIT so can't do it.

**Comment by tangenta** [comment] 2022-12-05 07:42
@noradomi  Maybe you can change your script to

```
./dumpling \
  ...
  --sql 'select * from `test.`account` where recorded_time < "2022-11-24 00:00:00";' \
  ...
```

**Comment by noradomi** [comment] 2022-12-05 07:56
@tangenta Thanks for your sugesstion, but my use case export all accounts data at cutoff time.

**Comment by noradomi** [comment] 2022-12-05 08:00
> No, commit_ts is not decided before COMMIT SQL statement, all your interactive transaction actions are performed before COMMIT so can't do it.

Thanks @lance6716. So I think this issue is not a bug. I'll close it. Thanks all.

**Closed** 2022-12-05 08:00 UTC
Labels: type/bug, severity/major, component/dumpling, may-affects-4.0, may-affects-5.1, may-affects-5.2, may-affects-5.3, may-affects-5.4, may-affects-5.0, may-affects-6.0, may-affects-6.1, may-affects-6.2, may-affects-6.3, may-affects-6.4, affects-6.5
