### ISSUE TITLE
Inappropriate error message: FUNCTION test.json_arrayagg does not exist

### ISSUE THREAD

**Issue by jebter** [pingcap/tidb#21560] opened 2020-12-08 09:02 UTC
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

drop table if exists t;
CREATE TABLE `t` (`a` int(11) DEFAULT NULL);
SELECT (SELECT 1 FROM t WHERE JSON_ARRAYAGG(1 IN (SELECT 1 FROM t)));
### 2. What did you expect to see? (Required)
Invalid use of group function
### 3. What did you see instead (Required)
FUNCTION test.json_arrayagg does not exist
### 4. What is your TiDB version? (Required)

Release Version: v4.0.9-dirty\nEdition: Community\nGit Commit Hash: f533a79253ff2b3b2d5077a259f1b28c7a1a313a\nGit Branch: HEAD\nUTC Build Time: 2020-12-01 10:45:15\nGoVersion: go1.13\nRace Enabled: false\nTiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306\nCheck Table Before Drop: false

**Comment by XuHuaiyu** [comment] 2020-12-10 13:11
Why does it need to return `Invalid use of group function` ?
TiDB does not support json_arrayagg, the error message seems to be acceptable.

**Comment by morgo** [comment] 2020-12-21 20:32
I am going to close this as a duplicate of https://github.com/pingcap/tidb/issues/19795

Because `json_arrayagg` is not implemented yet, it seems not practical that it can validate the correct use of the function. But please feel free to re-open if you disagree, thanks!

**Closed by morgo** 2020-12-21 20:32 UTC
Labels: severity/minor, sig/execution, type/bug, type/duplicate
