### ISSUE TITLE
lightning failed with error “tidb lightning encountered error: invalid duplicate-resolution 'record', please choose valid option between ['none', 'replace', 'error']”

### ISSUE THREAD

**Issue by Lily2025** [pingcap/tidb#51295] opened 2024-02-26 01:11 UTC
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1、lightning import

### 2. What did you expect to see? (Required)
lightning success

### 3. What did you see instead (Required)
lightning failed with error “tidb lightning encountered error: invalid duplicate-resolution 'record', please choose valid option between ['none', 'replace', 'error']”

### 4. What is your TiDB version? (Required)
./tidb-lightning -V
 Release Version: v8.0.0-alpha
Git Commit Hash: 2c46b8e0041822cb638b97b23a9399b27bc8b6b0
Git Branch: heads/refs/tags/v8.0.0-alpha
Go Version: go1.21.6
UTC Build Time: 2024-02-23 11:43:37
Race Enabled: false

./tidb-server -V
 Release Version: v8.0.0-alpha
Edition: Community
Git Commit Hash: 2c46b8e0041822cb638b97b23a9399b27bc8b6b0
Git Branch: heads/refs/tags/v8.0.0-alpha
UTC Build Time: 2024-02-23 11:46:36
GoVersion: go1.21.6
Race Enabled: false
Check Table Before Drop: false
Store: unistore
2024-02-26T04:47:44.393+0800

**Comment by lyzx2001** [comment] 2024-02-26 02:29
This is not a bug. Lightning's behavior has changed 
https://github.com/pingcap/tidb/pull/50806
`tikv-importer.duplicate-resolution` originally support `record`, `none`, `remove`, but now it has been changed that supports `none`, `replace`, `error`.
'record' in this issue is no longer supported.
Will close this issue once the docs pr is merged.

**Comment by D3Hunter** [comment] 2024-03-13 16:44
expected behavior

**Closed by D3Hunter** 2024-03-13 16:44 UTC
Labels: component/lightning
