### ISSUE TITLE
TiDB does not use index for WHERE (col1, col2) IN ((val1, val2), (val3, val4))?

### ISSUE THREAD

**Issue by hzj629206** [pingcap/tidb#10120] opened 2019-04-11 06:18 UTC
PRIMARY KEY is (col1, col2, col3)

it's very slow if use (col1, col2) IN ((val1, val2), (val3, val4)).
it's very fast if use col1 IN (val1, val3).

Is that the expected result?

**Comment by winoros** [comment] 2019-04-11 06:22
@hzj629206 
Please give us enough information.
Multiple-column IN clause can use index.

**Comment by hzj629206** [comment] 2019-04-11 06:29
···sql
CREATE TABLE `entity_tag_tab` (
  `entity_id` bigint(20) UNSIGNED NOT NULL,
  `entity_type` char(8) NOT NULL,
  `tag_id` bigint(20) UNSIGNED NOT NULL,
  `region` char(4) NOT NULL,
  `status` tinyint(3) UNSIGNED NOT NULL DEFAULT '1',
  `expiry_time` bigint(20) UNSIGNED NOT NULL DEFAULT '0',
  `create_time` bigint(20) UNSIGNED NOT NULL,
  `update_time` bigint(20) UNSIGNED NOT NULL,
  PRIMARY KEY (`entity_id`,`entity_type`,`tag_id`),
  KEY `idx_tag_id` (`tag_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin
```

insert 20m rows.

Query:
mysql> SELECT entity_id, entity_type, tag_id, region, status, expiry_time, create_time, update_time FROM entity_tag_tab WHERE (entity_id, entity_type) IN ((4697667, 'user'), (9584774, 'user'), (4553841, 'user'), (8847182, 'user'), (3492552, 'user'), (6539907, 'user'), (1562724, 'user'), (8885005, 'user'), (8563382, 'user'), (7259231, 'user')) and region = 'SG' and status = 1;
+-----------+-------------+---------+--------+--------+-------------+-------------+-------------+
| entity_id | entity_type | tag_id  | region | status | expiry_time | create_time | update_time |
+-----------+-------------+---------+--------+--------+-------------+-------------+-------------+
|   6539907 | user        | 1000000 | SG     |      1 |           0 |           0 |           0 |
|   6539907 | user        | 1000001 | SG     |      1 |           0 |           0 |           0 |
|   1562724 | user        | 1000000 | SG     |      1 |           0 |           0 |           0 |
|   1562724 | user        | 1000001 | SG     |      1 |           0 |           0 |           0 |
|   4553841 | user        | 1000000 | SG     |      1 |           0 |           0 |           0 |
|   4553841 | user        | 1000001 | SG     |      1 |           0 |           0 |           0 |
|   8563382 | user        | 1000000 | SG     |      1 |           0 |           0 |           0 |
|   8563382 | user        | 1000001 | SG     |      1 |           0 |           0 |           0 |
|   9584774 | user        | 1000000 | SG     |      1 |           0 |           0 |           0 |
|   9584774 | user        | 1000001 | SG     |      1 |           0 |           0 |           0 |
|   4697667 | user        | 1000000 | SG     |      1 |           0 |           0 |           0 |
|   4697667 | user        | 1000001 | SG     |      1 |           0 |           0 |           0 |
|   8847182 | user        | 1000000 | SG     |      1 |           0 |           0 |           0 |
|   8847182 | user        | 1000001 | SG     |      1 |           0 |           0 |           0 |
|   3492552 | user        | 1000000 | SG     |      1 |           0 |           0 |           0 |
|   3492552 | user        | 1000001 | SG     |      1 |           0 |           0 |           0 |
|   8885005 | user        | 1000000 | SG     |      1 |           0 |           0 |           0 |
|   8885005 | user        | 1000001 | SG     |      1 |           0 |           0 |           0 |
|   7259231 | user        | 1000000 | SG     |      1 |           0 |           0 |           0 |
|   7259231 | user        | 1000001 | SG     |      1 |           0 |           0 |           0 |
+-----------+-------------+---------+--------+--------+-------------+-------------+-------------+
20 rows in set (4.29 sec)

**Comment by hzj629206** [comment] 2019-04-11 06:33
Single column for IN clause.
```
mysql> SELECT entity_id, entity_type, tag_id, region, status, expiry_time, create_time, update_time FROM entity_tag_tab WHERE entity_id IN (4697667, 9584774, 4553841, 8847182, 3492552, 6539907, 1562724, 8885005, 8563382, 7259231) and region = 'SG' and status = 1
    -> ;
+-----------+-------------+---------+--------+--------+-------------+-------------+-------------+
| entity_id | entity_type | tag_id  | region | status | expiry_time | create_time | update_time |
+-----------+-------------+---------+--------+--------+-------------+-------------+-------------+
|   1562724 | user        | 1000000 | SG     |      1 |           0 |           0 |           0 |
|   1562724 | user        | 1000001 | SG     |      1 |           0 |           0 |           0 |
|   4697667 | user        | 1000000 | SG     |      1 |           0 |           0 |           0 |
|   4697667 | user        | 1000001 | SG     |      1 |           0 |           0 |           0 |
|   3492552 | user        | 1000000 | SG     |      1 |           0 |           0 |           0 |
|   3492552 | user        | 1000001 | SG     |      1 |           0 |           0 |           0 |
|   8885005 | user        | 1000000 | SG     |      1 |           0 |           0 |           0 |
|   8885005 | user        | 1000001 | SG     |      1 |           0 |           0 |           0 |
|   8563382 | user        | 1000000 | SG     |      1 |           0 |           0 |           0 |
|   8563382 | user        | 1000001 | SG     |      1 |           0 |           0 |           0 |
|   6539907 | user        | 1000000 | SG     |      1 |           0 |           0 |           0 |
|   6539907 | user        | 1000001 | SG     |      1 |           0 |           0 |           0 |
|   8847182 | user        | 1000000 | SG     |      1 |           0 |           0 |           0 |
|   8847182 | user        | 1000001 | SG     |      1 |           0 |           0 |           0 |
|   9584774 | user        | 1000000 | SG     |      1 |           0 |           0 |           0 |
|   9584774 | user        | 1000001 | SG     |      1 |           0 |           0 |           0 |
|   4553841 | user        | 1000000 | SG     |      1 |           0 |           0 |           0 |
|   4553841 | user        | 1000001 | SG     |      1 |           0 |           0 |           0 |
|   7259231 | user        | 1000000 | SG     |      1 |           0 |           0 |           0 |
|   7259231 | user        | 1000001 | SG     |      1 |           0 |           0 |           0 |
+-----------+-------------+---------+--------+--------+-------------+-------------+-------------+
20 rows in set (0.01 sec)
```

**Comment by hzj629206** [comment] 2019-04-11 06:34
Slow log:

2019/04/11 11:00:00.299 adapter.go:391: [warning] [SLOW_QUERY] cost_time:4.158431763s process_time:41.276s wait_time:8ms request_count:22 total_keys:20000022 processed_keys:20000000 succ:true con:40078188 user:shopee_tag_attr_rw@10.70.9.6 txn_start_ts:407621231210660128 database:shopee_tag_attr_db table_ids:[87],sql:SELECT entity_id, entity_type, tag_id, region, status, expiry_time, create_time, update_time FROM entity_tag_tab WHERE (entity_id, entity_type) IN ((?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?)) and region = ? and status = ? [arguments: 4697667, user, 9584774, user, 4553841, user, 8847182, user, 3492552, user, 6539907, user, 1562724, user, 8885005, user, 8563382, user, 7259231, user, SG, 1]

**Comment by winoros** [comment] 2019-04-11 06:34
Please answer the questions in `performance issue` template.

- What version of TiDB are you using?


- For a specific slow SQL query, please provide the following information:
    - Whether you analyzed the tables involved in the query and how long it is after you ran the last `ANALYZE`.
    - Whether this SQL query always or occasionally runs slowly.
    - The `EXPLAIN ANALYZE` result of this query if your TiDB version is higher than 2.1, or you can just provide the `EXPLAIN` result.

**Comment by lysu** [comment] 2019-04-11 06:51
@hzj629206  for your slow log it doesn't use index, but I can not reproduct in myself's env.

please execute to see plan

```sql
explain analyze SELECT entity_id, entity_type, tag_id, region, status, expiry_time, create_time, update_time FROM entity_tag_tab WHERE (entity_id, entity_type) IN ((4697667, 'user'), (9584774, 'user'), (4553841, 'user'), (8847182, 'user'), (3492552, 'user'), (6539907, 'user'), (1562724, 'user'), (8885005, 'user'), (8563382, 'user'), (7259231, 'user')) and region = 'SG' and status = 1;
```

and also give us the statistics data of the involved tables
```sh
curl -G "http://${tidb-server-ip}:${tidb-server-status-port}/stats/dump/${db_name}/${table_name}" > ${table_name}_stats.json
```

thanks.

**Comment by hzj629206** [comment] 2019-04-11 07:18
What version of TiDB are you using?
    2.1.5

Whether you analyzed the tables involved in the query and how long it is after you ran the last ANALYZE.
    No.

Whether this SQL query always or occasionally runs slowly.
    Always.

The EXPLAIN ANALYZE result of this query if your TiDB version is higher than 2.1, or you can just provide the EXPLAIN result.
```
mysql> EXPLAIN ANALYZE SELECT entity_id, entity_type, tag_id, region, status, expiry_time, create_time, update_time FROM entity_tag_tab WHERE (entity_id, entity_type) IN ((4697667, 'user'), (9584774, 'user'), (4553841, 'user'), (8847182, 'user'), (3492552, 'user'), (6539907, 'user'), (1562724, 'user'), (8885005, 'user'), (8563382, 'user'), (7259231, 'user')) and region = 'SG' and status = 1;
+---------------------+-------------+------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------+
| id                  | count       | task | operator info                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    | execution info                      |
+---------------------+-------------+------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------+
| TableReader_7       | 16000000.00 | root | data:Selection_6                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 | time:4.314577216s, loops:2, rows:20 |
| └─Selection_6   | 16000000.00 | cop  | eq(shopee_tag_attr_db.entity_tag_tab.region, "SG"), eq(shopee_tag_attr_db.entity_tag_tab.status, 1), or(or(or(and(eq(shopee_tag_attr_db.entity_tag_tab.entity_id, 4697667), eq(shopee_tag_attr_db.entity_tag_tab.entity_type, "user")), and(eq(shopee_tag_attr_db.entity_tag_tab.entity_id, 9584774), eq(shopee_tag_attr_db.entity_tag_tab.entity_type, "user"))), or(and(eq(shopee_tag_attr_db.entity_tag_tab.entity_id, 4553841), eq(shopee_tag_attr_db.entity_tag_tab.entity_type, "user")), or(and(eq(shopee_tag_attr_db.entity_tag_tab.entity_id, 8847182), eq(shopee_tag_attr_db.entity_tag_tab.entity_type, "user")), and(eq(shopee_tag_attr_db.entity_tag_tab.entity_id, 3492552), eq(shopee_tag_attr_db.entity_tag_tab.entity_type, "user"))))), or(or(and(eq(shopee_tag_attr_db.entity_tag_tab.entity_id, 6539907), eq(shopee_tag_attr_db.entity_tag_tab.entity_type, "user")), and(eq(shopee_tag_attr_db.entity_tag_tab.entity_id, 1562724), eq(shopee_tag_attr_db.entity_tag_tab.entity_type, "user"))), or(and(eq(shopee_tag_attr_db.entity_tag_tab.entity_id, 8885005), eq(shopee_tag_attr_db.entity_tag_tab.entity_type, "user")), or(and(eq(shopee_tag_attr_db.entity_tag_tab.entity_id, 8563382), eq(shopee_tag_attr_db.entity_tag_tab.entity_type, "user")), and(eq(shopee_tag_attr_db.entity_tag_tab.entity_id, 7259231), eq(shopee_tag_attr_db.entity_tag_tab.entity_type, "user")))))) |                                     |
|   └─TableScan_5 | 20000000.00 | cop  | table:entity_tag_tab, range:[-inf,+inf], keep order:false                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |                                     |
+---------------------+-------------+------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------+
3 rows in set (4.32 sec)
```

**Comment by hzj629206** [comment] 2019-04-11 07:22
It's fast if we use `force index (primary)`

```
explain analyze SELECT entity_id, entity_type, tag_id, region, status, expiry_time, create_time, update_time FROM entity_tag_tab force index (primary) WHERE (entity_id, entity_type) IN ((4697667, 'user'), (9584774, 'user'), (4553841, 'user'), (8847182, 'user'), (3492552, 'user'), (6539907, 'user'), (1562724, 'user'), (8885005, 'user'), (8563382, 'user'), (7259231, 'user')) and region = 'SG' and status = 1;
+-----------------------+-------------+------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------+
| id                    | count       | task | operator info                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    | execution info                    |
+-----------------------+-------------+------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------+
| IndexLookUp_9         | 16000000.00 | root |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  | time:3.087876ms, loops:2, rows:20 |
| ├─Selection_7     | 16000000.00 | cop  | or(or(or(and(eq(tag_attr_db.entity_tag_tab.entity_id, 4697667), eq(tag_attr_db.entity_tag_tab.entity_type, "user")), and(eq(tag_attr_db.entity_tag_tab.entity_id, 9584774), eq(tag_attr_db.entity_tag_tab.entity_type, "user"))), or(and(eq(tag_attr_db.entity_tag_tab.entity_id, 4553841), eq(tag_attr_db.entity_tag_tab.entity_type, "user")), or(and(eq(tag_attr_db.entity_tag_tab.entity_id, 8847182), eq(tag_attr_db.entity_tag_tab.entity_type, "user")), and(eq(tag_attr_db.entity_tag_tab.entity_id, 3492552), eq(tag_attr_db.entity_tag_tab.entity_type, "user"))))), or(or(and(eq(tag_attr_db.entity_tag_tab.entity_id, 6539907), eq(tag_attr_db.entity_tag_tab.entity_type, "user")), and(eq(tag_attr_db.entity_tag_tab.entity_id, 1562724), eq(tag_attr_db.entity_tag_tab.entity_type, "user"))), or(and(eq(tag_attr_db.entity_tag_tab.entity_id, 8885005), eq(tag_attr_db.entity_tag_tab.entity_type, "user")), or(and(eq(tag_attr_db.entity_tag_tab.entity_id, 8563382), eq(tag_attr_db.entity_tag_tab.entity_type, "user")), and(eq(tag_attr_db.entity_tag_tab.entity_id, 7259231), eq(tag_attr_db.entity_tag_tab.entity_type, "user")))))) |                                   |
| │ └─IndexScan_5 | 20000000.00 | cop  | table:entity_tag_tab, index:entity_id, entity_type, tag_id, range:[1562724,1562724], [3492552,3492552], [4553841,4553841], [4697667,4697667], [6539907,6539907], [7259231,7259231], [8563382,8563382], [8847182,8847182], [8885005,8885005], [9584774,9584774], keep order:false                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |                                   |
| └─Selection_8     | 16000000.00 | cop  | eq(tag_attr_db.entity_tag_tab.region, "SG"), eq(tag_attr_db.entity_tag_tab.status, 1)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |                                   |
|   └─TableScan_6   | 16000000.00 | cop  | table:entity_tag_tab, keep order:false                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |                                   |
+-----------------------+-------------+------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------+
5 rows in set (0.01 sec)
```

**Comment by winoros** [comment] 2019-04-11 07:22
@hzj629206 
You can try to analyze it first.
This should solve your problem.

**Comment by hzj629206** [comment] 2019-04-11 07:33
@winoros 
Still has the problem after analyze table.
We will try to use `force index (primary)` first.


[entity_tag_tab_stats.json.zip](https://github.com/pingcap/tidb/files/3067436/entity_tag_tab_stats.json.zip)

**Comment by winoros** [comment] 2019-04-11 09:41
@hzj629206 
Sorry for your inconvenience. Seems that this is row count estimation bug. We'll dig into it soon.

**Comment by nullnotnil** [comment] 2020-07-12 19:39
I have verified that I can reproduce this in TiDB 2.1.5 with my testcase below. I can not reproduce in master however, so it looks like it has been fixed:

```sql
DROP TABLE IF EXISTS t1;
CREATE TABLE t1 (
  a bigint(20) UNSIGNED NOT NULL auto_increment,
  b char(8) NOT NULL,
  c bigint(20) UNSIGNED NOT NULL,
  d char(4) NOT NULL,
  e tinyint(3) UNSIGNED NOT NULL DEFAULT '1',
  pad1 bigint(20) UNSIGNED NOT NULL DEFAULT '0',
  pad2 bigint(20) UNSIGNED NOT NULL,
  pad3 bigint(20) UNSIGNED NOT NULL,
  PRIMARY KEY (a,b,c),
  KEY (c)
);

INSERT INTO t1 (a,b,c,d,e,pad1,pad2,pad3) SELECT NULL, 'user', 1, 'SG', 1, 0, 0, 0 FROM dual;
INSERT INTO t1 (a,b,c,d,e,pad1,pad2,pad3) SELECT NULL, 'user', 1, 'SG', 1, 0, 0, 0 FROM t1 a JOIN t1 b JOIN t1 c LIMIT 10000;
INSERT INTO t1 (a,b,c,d,e,pad1,pad2,pad3) SELECT NULL, 'user', 1, 'SG', 1, 0, 0, 0 FROM t1 a JOIN t1 b JOIN t1 c LIMIT 10000;
INSERT INTO t1 (a,b,c,d,e,pad1,pad2,pad3) SELECT NULL, 'user', 1, 'SG', 1, 0, 0, 0 FROM t1 a JOIN t1 b JOIN t1 c LIMIT 10000;
INSERT INTO t1 (a,b,c,d,e,pad1,pad2,pad3) SELECT NULL, 'user', 1, 'SG', 1, 0, 0, 0 FROM t1 a JOIN t1 b JOIN t1 c LIMIT 10000;
INSERT INTO t1 (a,b,c,d,e,pad1,pad2,pad3) SELECT NULL, 'user', 1, 'SG', 1, 0, 0, 0 FROM t1 a JOIN t1 b JOIN t1 c LIMIT 10000;
INSERT INTO t1 (a,b,c,d,e,pad1,pad2,pad3) SELECT NULL, 'user', 1, 'SG', 1, 0, 0, 0 FROM t1 a JOIN t1 b JOIN t1 c LIMIT 10000;
SELECT SLEEP(1);
ANALYZE TABLE t1;
SELECT SLEEP(1);
```

Against TiDB 2.1.5:
```sql

mysql> select version();
+-------------------------------+
| version()                     |
+-------------------------------+
| 5.7.10-TiDB-v2.1.5-1-g0bd6b1b |
+-------------------------------+
1 row in set (0.00 sec)

mysql> EXPLAIN SELECT * FROM t1 WHERE  (a,b) IN ((4697667, 'user'), (9584774, 'user'), (4553841, 'user'), (8847182, 'user'), (3492552, 'user'), (6539907, 'user'), (1562724, 'user'), (8885005, 'user'), (8563382, 'user'), (7259231, 'user'))  AND d = 'SG'  AND e = 1;
+---------------------+----------+------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| id                  | count    | task | operator info                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
+---------------------+----------+------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| TableReader_7       | 49616.00 | root | data:Selection_6                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
| └─Selection_6       | 49616.00 | cop  | eq(test.t1.d, "SG"), eq(test.t1.e, 1), or(or(or(and(eq(test.t1.a, 4697667), eq(test.t1.b, "user")), and(eq(test.t1.a, 9584774), eq(test.t1.b, "user"))), or(and(eq(test.t1.a, 4553841), eq(test.t1.b, "user")), or(and(eq(test.t1.a, 8847182), eq(test.t1.b, "user")), and(eq(test.t1.a, 3492552), eq(test.t1.b, "user"))))), or(or(and(eq(test.t1.a, 6539907), eq(test.t1.b, "user")), and(eq(test.t1.a, 1562724), eq(test.t1.b, "user"))), or(and(eq(test.t1.a, 8885005), eq(test.t1.b, "user")), or(and(eq(test.t1.a, 8563382), eq(test.t1.b, "user")), and(eq(test.t1.a, 7259231), eq(test.t1.b, "user")))))) |
|   └─TableScan_5     | 62020.00 | cop  | table:t1, range:[-inf,+inf], keep order:false                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
+---------------------+----------+------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
3 rows in set (0.00 sec)
```

Against master:

```sql
mysql> EXPLAIN SELECT * FROM t1 WHERE  (a,b) IN ((4697667, 'user'), (9584774, 'user'), (4553841, 'user'), (8847182, 'user'), (3492552, 'user'), (6539907, 'user'), (1562724, 'user'), (8885005, 'user'), (8563382, 'user'), (7259231, 'user'))  AND d = 'SG'  AND e = 1;
+----------------------------+---------+-----------+----------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| id                         | estRows | task      | access object                    | operator info                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
+----------------------------+---------+-----------+----------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| IndexLookUp_12             | 0.02    | root      |                                  |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |
| ├─Selection_10(Build)      | 0.02    | cop[tikv] |                                  | or(or(or(and(eq(test.t1.a, 4697667), eq(test.t1.b, "user")), and(eq(test.t1.a, 9584774), eq(test.t1.b, "user"))), or(and(eq(test.t1.a, 4553841), eq(test.t1.b, "user")), or(and(eq(test.t1.a, 8847182), eq(test.t1.b, "user")), and(eq(test.t1.a, 3492552), eq(test.t1.b, "user"))))), or(or(and(eq(test.t1.a, 6539907), eq(test.t1.b, "user")), and(eq(test.t1.a, 1562724), eq(test.t1.b, "user"))), or(and(eq(test.t1.a, 8885005), eq(test.t1.b, "user")), or(and(eq(test.t1.a, 8563382), eq(test.t1.b, "user")), and(eq(test.t1.a, 7259231), eq(test.t1.b, "user")))))) |
| │ └─IndexRangeScan_8       | 0.03    | cop[tikv] | table:t1, index:PRIMARY(a, b, c) | range:[1562724,1562724], [3492552,3492552], [4553841,4553841], [4697667,4697667], [6539907,6539907], [7259231,7259231], [8563382,8563382], [8847182,8847182], [8885005,8885005], [9584774,9584774], keep order:false                                                                                                                                                                                                                                                                                                                                                       |
| └─Selection_11(Probe)      | 0.02    | cop[tikv] |                                  | eq(test.t1.d, "SG"), eq(test.t1.e, 1)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
|   └─TableRowIDScan_9       | 0.02    | cop[tikv] | table:t1                         | keep order:false                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
+----------------------------+---------+-----------+----------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
5 rows in set (0.00 sec)

mysql> select tidb_version()\G
*************************** 1. row ***************************
tidb_version(): Release Version: v4.0.0-beta.2-750-g8a661044c
Edition: Community
Git Commit Hash: 8a661044cedf8daad1de4fbf79a390962b6f6c3b
Git Branch: master
UTC Build Time: 2020-07-10 10:52:37
GoVersion: go1.13
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
1 row in set (0.00 sec)
```

I am going to close this issue now, but please feel free to reopen if you have any further questions. Thanks!

**Closed by nullnotnil** 2020-07-12 19:39 UTC
Labels: type/bug, type/question
