### ISSUE TITLE
The result of comparing two string is wrong in some cases

### ISSUE THREAD

**Issue by qw4990** [pingcap/tidb#13017] opened 2019-10-30 06:32 UTC
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
```
select "mvoiglopb">="UebLHwFSV";
```

2. What did you expect to see?
In MySQL:
```
mysql> select "mvoiglopb">="UebLHwFSV";
+--------------------------+
| "mvoiglopb">="UebLHwFSV" |
+--------------------------+
|                        0 |
+--------------------------+
```

3. What did you see instead?
In TiDB:
```
mysql> select "mvoiglopb">="UebLHwFSV";
+--------------------------+
| "mvoiglopb">="UebLHwFSV" |
+--------------------------+
|                        1 |
+--------------------------+
```

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

**Comment by nullnotnil** [comment] 2020-07-16 18:35
This is the result of collations. Here is an example in MySQL 8.0:

```sql
mysql [localhost:8021] {msandbox} (test) > select "mvoiglopb">="UebLHwFSV";
+--------------------------+
| "mvoiglopb">="UebLHwFSV" |
+--------------------------+
|                        0 |
+--------------------------+
1 row in set (0.00 sec)

mysql [localhost:8021] {msandbox} (test) > select _binary "mvoiglopb" >= _binary "UebLHwFSV";
+--------------------------------------------+
| _binary "mvoiglopb" >= _binary "UebLHwFSV" |
+--------------------------------------------+
|                                          1 |
+--------------------------------------------+
1 row in set (0.00 sec)
```

I can get the same behavior in TiDB with the following steps:

1. Set  `new_collations_enabled_on_first_bootstrap = true` and bootstrap a fresh tidb cluster.
2. Change the collation with `set names utf8 collate utf8_general_ci;`

Example:

```sql
mysql> set names utf8 collate utf8_general_ci;
Query OK, 0 rows affected (0.00 sec)

mysql> select "mvoiglopb">="UebLHwFSV";
+--------------------------+
| "mvoiglopb">="UebLHwFSV" |
+--------------------------+
|                        0 |
+--------------------------+
1 row in set (0.00 sec)

mysql> select tidb_version()\G
*************************** 1. row ***************************
tidb_version(): Release Version: v4.0.0-beta.2-782-gb72e47e6d
Edition: Community
Git Commit Hash: b72e47e6db8863c08e47714391cf937b0f1c3269
Git Branch: master
UTC Build Time: 2020-07-15 01:26:06
GoVersion: go1.13
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
1 row in set (0.00 sec)
```

It is not the default (yet), but I believe this can be closed as a duplicate of https://github.com/pingcap/tidb/issues/7519

**Closed by nullnotnil** 2020-07-16 18:35 UTC
Labels: type/bug
