### ISSUE TITLE
TiKV doesn't support ENUM's calculation logic hence index is unused

### ISSUE THREAD

**Issue by jborg** [pingcap/tidb#14558] opened 2020-01-20 10:22 UTC
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

Indices created on enum columns (both single column indices and multi column indices) seems to be ignored by the query planner and the result is fetched using inefficient table scans.

```sql
create table enum_index_test (
	id int primary key,
	a varchar(40),
	d date,
	e enum('E', 'E2', 'E3'),
	v varchar(1),
	key e (e),
	key v (v),
	key ae (a, e),
	key av (a, v)
)
--------------

--------------
insert into enum_index_test(id, a, e, v) values
(1, 'A', 'E', 'V'),
(2, 'A', 'E', 'V'),
(3, 'A', 'E', 'V'),
(4, 'A', 'E', 'V'),
(5, 'A', 'E', 'V'),
(6, 'A', 'E', 'V')
--------------

--------------
explain select count(*) from enum_index_test where v='V'
--------------

id	count	task	operator info
StreamAgg_17	1.00	root	funcs:count(col_0)
└─IndexReader_18	1.00	root	index:StreamAgg_9
  └─StreamAgg_9	1.00	cop	funcs:count(1)
    └─IndexScan_16	10.00	cop	table:enum_index_test, index:v, range:["V","V"], keep order:false, stats:pseudo
--------------
explain select count(*) from enum_index_test where e='E'
--------------

id	count	task	operator info
StreamAgg_10	1.00	root	funcs:count(1)
└─Selection_16	8000.00	root	eq(ssi_test.enum_index_test.e, "E")
  └─IndexReader_18	10000.00	root	index:IndexScan_17
    └─IndexScan_17	10000.00	cop	table:enum_index_test, index:e, range:[NULL,+inf], keep order:false, stats:pseudo
--------------
explain select count(*) from enum_index_test where a='A' and v='V'
--------------

id	count	task	operator info
StreamAgg_10	1.00	root	funcs:count(1)
└─IndexReader_15	0.10	root	index:IndexScan_14
  └─IndexScan_14	0.10	cop	table:enum_index_test, index:a, v, range:["A" "V","A" "V"], keep order:false, stats:pseudo
--------------
explain select count(*) from enum_index_test where a='A' and e='E'
--------------

id	count	task	operator info
StreamAgg_10	1.00	root	funcs:count(1)
└─Selection_14	8.00	root	eq(ssi_test.enum_index_test.e, "E")
  └─IndexReader_16	10.00	root	index:IndexScan_15
    └─IndexScan_15	10.00	cop	table:enum_index_test, index:a, e, range:["A","A"], keep order:false, stats:pseudo
```

2. What did you expect to see?

I expected to see the index being  used the same was as for columns of different data types (varchar, date, ...)

3. What did you see instead?
I observed no difference in query response times with or without these indicies

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
```
| Release Version: v3.0.9
Git Commit Hash: bf155a7773d8978e7f80e2c7055c46da73c8bcc3
Git Branch: HEAD
UTC Build Time: 2020-01-14 12:55:23
GoVersion: go version go1.13 linux/amd64
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false |
```

## SIG slack channel

 [#sig-planner](https://slack.tidb.io/invite?team=tidb-community&channel=sig-planner&ref=high-performance)

## Score

- 300

## Mentor

* @lzmhhh123

**Comment by wwar** [comment] 2020-01-21 01:31
I played with your test-case a little to make sure the index was selective. TiDB will not pick the index on `e` even if there is a `FORCE INDEX`:

```
DROP TABLE IF EXISTS t1;
CREATE TABLE t1 (
 id INT NOT NULL primary key auto_increment,
 a varchar(40),
 e enum('A', 'B', 'C', 'D', 'E', 'F'),
 v varchar(1),
 key e (e),
 key v (v),
 key ae (a, e),
 key av (a, v)
);

INSERT INTO t1 (a, e, v) VALUES
('A', 'A', 'A'),
('B', 'B', 'B'),
('C', 'C', 'C'),
('D', 'D', 'D'),
('E', 'E', 'E'),
('F', 'F', 'F');

ANALYZE TABLE t1;

EXPLAIN ANALYZE SELECT * FROM t1 WHERE v='V';
EXPLAIN ANALYZE SELECT * FROM t1 WHERE e='E';
EXPLAIN ANALYZE SELECT * FROM t1 WHERE a='A' and v='V';
EXPLAIN ANALYZE SELECT * FROM t1 WHERE a='A' and e='E';
EXPLAIN ANALYZE SELECT * FROM t1 FORCE INDEX (e) WHERE e='E';
```

Output:
```
mysql> EXPLAIN ANALYZE SELECT * FROM t1 WHERE v='V';
+-------------------+-------+-----------+------------------------------------------------------+--------------------------------------------------------------------------------+-----------+------+
| id                | count | task      | operator info                                        | execution info                                                                 | memory    | disk |
+-------------------+-------+-----------+------------------------------------------------------+--------------------------------------------------------------------------------+-----------+------+
| IndexLookUp_10    | 0.00  | root      |                                                      | time:540.993µs, loops:1, rows:0, rpc num: 1, rpc time:430.023µs, proc keys:0   | 178 Bytes | N/A  |
| ├─IndexScan_8     | 0.00  | cop[tikv] | table:t1, index:v, range:["V","V"], keep order:false | time:0s, loops:1, rows:0                                                       | N/A       | N/A  |
| └─TableScan_9     | 0.00  | cop[tikv] | table:t1, keep order:false                           | time:0s, loops:0, rows:0                                                       | N/A       | N/A  |
+-------------------+-------+-----------+------------------------------------------------------+--------------------------------------------------------------------------------+-----------+------+
3 rows in set (0.00 sec)

mysql> EXPLAIN ANALYZE SELECT * FROM t1 WHERE e='E';
+---------------------+-------+-----------+-----------------------------------------------+--------------------------------------------------------------------------------+---------------+------+
| id                  | count | task      | operator info                                 | execution info                                                                 | memory        | disk |
+---------------------+-------+-----------+-----------------------------------------------+--------------------------------------------------------------------------------+---------------+------+
| Selection_5         | 4.80  | root      | eq(test.t1.e, "E")                            | time:643.195µs, loops:2, rows:1                                                | 1.81640625 KB | N/A  |
| └─TableReader_7     | 6.00  | root      | data:TableScan_6                              | time:614.801µs, loops:3, rows:6, rpc num: 1, rpc time:563.044µs, proc keys:6   | 263 Bytes     | N/A  |
|   └─TableScan_6     | 6.00  | cop[tikv] | table:t1, range:[-inf,+inf], keep order:false | time:0s, loops:7, rows:6                                                       | N/A           | N/A  |
+---------------------+-------+-----------+-----------------------------------------------+--------------------------------------------------------------------------------+---------------+------+
3 rows in set (0.00 sec)

mysql> EXPLAIN ANALYZE SELECT * FROM t1 WHERE a='A' and v='V';
+-------------------+-------+-----------+-----------------------------------------------------------------+--------------------------------------------------------------------------------+-----------+------+
| id                | count | task      | operator info                                                   | execution info                                                                 | memory    | disk |
+-------------------+-------+-----------+-----------------------------------------------------------------+--------------------------------------------------------------------------------+-----------+------+
| IndexLookUp_10    | 0.00  | root      |                                                                 | time:443.708µs, loops:1, rows:0, rpc num: 1, rpc time:355.412µs, proc keys:0   | 194 Bytes | N/A  |
| ├─IndexScan_8     | 0.00  | cop[tikv] | table:t1, index:a, v, range:["A" "V","A" "V"], keep order:false | time:0s, loops:1, rows:0                                                       | N/A       | N/A  |
| └─TableScan_9     | 0.00  | cop[tikv] | table:t1, keep order:false                                      | time:0s, loops:0, rows:0                                                       | N/A       | N/A  |
+-------------------+-------+-----------+-----------------------------------------------------------------+--------------------------------------------------------------------------------+-----------+------+
3 rows in set (0.00 sec)

mysql> EXPLAIN ANALYZE SELECT * FROM t1 WHERE a='A' and e='E';
+-----------------------+-------+-----------+-----------------------------------------------+--------------------------------------------------------------------------------+---------------+------+
| id                    | count | task      | operator info                                 | execution info                                                                 | memory        | disk |
+-----------------------+-------+-----------+-----------------------------------------------+--------------------------------------------------------------------------------+---------------+------+
| Selection_5           | 0.80  | root      | eq(test.t1.e, "E")                            | time:601.026µs, loops:1, rows:0                                                | 1.81640625 KB | N/A  |
| └─TableReader_8       | 1.00  | root      | data:Selection_7                              | time:578.253µs, loops:2, rows:1, rpc num: 1, rpc time:521.817µs, proc keys:6   | 188 Bytes     | N/A  |
|   └─Selection_7       | 1.00  | cop[tikv] | eq(test.t1.a, "A")                            | time:0s, loops:2, rows:1                                                       | N/A           | N/A  |
|     └─TableScan_6     | 6.00  | cop[tikv] | table:t1, range:[-inf,+inf], keep order:false | time:0s, loops:7, rows:6                                                       | N/A           | N/A  |
+-----------------------+-------+-----------+-----------------------------------------------+--------------------------------------------------------------------------------+---------------+------+
4 rows in set (0.01 sec)

mysql> EXPLAIN ANALYZE SELECT * FROM t1 FORCE INDEX (e) WHERE e='E';
+---------------------+-------+-----------+--------------------------------------------------------+--------------------------------------------------------------------------------+---------------+------+
| id                  | count | task      | operator info                                          | execution info                                                                 | memory        | disk |
+---------------------+-------+-----------+--------------------------------------------------------+--------------------------------------------------------------------------------+---------------+------+
| Selection_5         | 4.80  | root      | eq(test.t1.e, "E")                                     | time:1.039646ms, loops:2, rows:1                                               | 1.81640625 KB | N/A  |
| └─IndexLookUp_8     | 6.00  | root      |                                                        | time:1.023935ms, loops:3, rows:6, rpc num: 1, rpc time:440.683µs, proc keys:6  | 9.91015625 KB | N/A  |
|   ├─IndexScan_6     | 6.00  | cop[tikv] | table:t1, index:e, range:[NULL,+inf], keep order:false | time:0s, loops:7, rows:6                                                       | N/A           | N/A  |
|   └─TableScan_7     | 6.00  | cop[tikv] | table:t1, keep order:false                             | time:0s, loops:7, rows:6                                                       | N/A           | N/A  |
+---------------------+-------+-----------+--------------------------------------------------------+--------------------------------------------------------------------------------+---------------+------+
4 rows in set (0.00 sec)

```

**Comment by winoros** [comment] 2020-02-03 10:52
@jborg @wwar Yeah, this is a known issue. We're going to support it this year.

**Comment by morgo** [comment] 2021-07-29 00:27
Here is an update to the EXPLAIN output in master:
```sql
mysql> EXPLAIN ANALYZE SELECT * FROM t1 WHERE v='V';
+-------------------------------+---------+---------+-----------+----------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------+-----------+------+
| id                            | estRows | actRows | task      | access object        | execution info                                                                                                                                                                                                                                                                                                                                   | operator info                     | memory    | disk |
+-------------------------------+---------+---------+-----------+----------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------+-----------+------+
| IndexLookUp_10                | 0.00    | 0       | root      |                      | time:284.8µs, loops:1,  table_task: {total_time: 1.36ms, num: 0, concurrency: 5}                                                                                                                                                                                                                                                                 |                                   | 185 Bytes | N/A  |
| ├─IndexRangeScan_8(Build)     | 0.00    | 0       | cop[tikv] | table:t1, index:v(v) | time:223.3µs, loops:1, cop_task: {num: 1, max: 183.2µs, proc_keys: 0, rpc_num: 1, rpc_time: 174.4µs, copr_cache_hit_ratio: 0.00}, tikv_task:{time:0s, loops:1}, scan_detail: {total_process_keys: 0, total_keys: 1, rocksdb: {delete_skipped_count: 0, key_skipped_count: 0, block: {cache_hit_count: 0, read_count: 0, read_byte: 0 Bytes}}}    | range:["V","V"], keep order:false | N/A       | N/A  |
| └─TableRowIDScan_9(Probe)     | 0.00    | 0       | cop[tikv] | table:t1             |                                                                                                                                                                                                                                                                                                                                                  | keep order:false                  | N/A       | N/A  |
+-------------------------------+---------+---------+-----------+----------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------+-----------+------+
3 rows in set (0.00 sec)

mysql> EXPLAIN ANALYZE SELECT * FROM t1 WHERE e='E';
+-------------------------+---------+---------+-----------+---------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------+-----------+------+
| id                      | estRows | actRows | task      | access object | execution info                                                                                                                                                                                              | operator info      | memory    | disk |
+-------------------------+---------+---------+-----------+---------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------+-----------+------+
| TableReader_7           | 1.00    | 1       | root      |               | time:309.2µs, loops:2, cop_task: {num: 1, max: 263.4µs, proc_keys: 6, rpc_num: 1, rpc_time: 255.5µs, copr_cache_hit_ratio: 0.00}                                                                            | data:Selection_6   | 295 Bytes | N/A  |
| └─Selection_6           | 1.00    | 1       | cop[tikv] |               | tikv_task:{time:0s, loops:1}, scan_detail: {total_process_keys: 6, total_keys: 7, rocksdb: {delete_skipped_count: 0, key_skipped_count: 6, block: {cache_hit_count: 0, read_count: 0, read_byte: 0 Bytes}}} | eq(test.t1.e, "E") | N/A       | N/A  |
|   └─TableFullScan_5     | 6.00    | 6       | cop[tikv] | table:t1      | tikv_task:{time:0s, loops:1}                                                                                                                                                                                | keep order:false   | N/A       | N/A  |
+-------------------------+---------+---------+-----------+---------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------+-----------+------+
3 rows in set (0.00 sec)

mysql> EXPLAIN ANALYZE SELECT * FROM t1 WHERE a='A' and v='V';
+-------------------------------+---------+---------+-----------+--------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------+-----------+------+
| id                            | estRows | actRows | task      | access object            | execution info                                                                                                                                                                                                                                                                                                                                   | operator info                             | memory    | disk |
+-------------------------------+---------+---------+-----------+--------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------+-----------+------+
| IndexLookUp_10                | 0.00    | 0       | root      |                          | time:327.5µs, loops:1,  table_task: {total_time: 1.58ms, num: 0, concurrency: 5}                                                                                                                                                                                                                                                                 |                                           | 195 Bytes | N/A  |
| ├─IndexRangeScan_8(Build)     | 0.00    | 0       | cop[tikv] | table:t1, index:av(a, v) | time:260.8µs, loops:1, cop_task: {num: 1, max: 224.6µs, proc_keys: 0, rpc_num: 1, rpc_time: 216.9µs, copr_cache_hit_ratio: 0.00}, tikv_task:{time:0s, loops:1}, scan_detail: {total_process_keys: 0, total_keys: 1, rocksdb: {delete_skipped_count: 0, key_skipped_count: 0, block: {cache_hit_count: 0, read_count: 0, read_byte: 0 Bytes}}}    | range:["A" "V","A" "V"], keep order:false | N/A       | N/A  |
| └─TableRowIDScan_9(Probe)     | 0.00    | 0       | cop[tikv] | table:t1                 |                                                                                                                                                                                                                                                                                                                                                  | keep order:false                          | N/A       | N/A  |
+-------------------------------+---------+---------+-----------+--------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------+-----------+------+
3 rows in set (0.00 sec)

mysql> EXPLAIN ANALYZE SELECT * FROM t1 WHERE a='A' and e='E';
+-------------------------------+---------+---------+-----------+--------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------+-----------+------+
| id                            | estRows | actRows | task      | access object            | execution info                                                                                                                                                                                                                                                                                                                                 | operator info                             | memory    | disk |
+-------------------------------+---------+---------+-----------+--------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------+-----------+------+
| IndexLookUp_10                | 0.00    | 0       | root      |                          | time:294.5µs, loops:1,  table_task: {total_time: 1.41ms, num: 0, concurrency: 5}                                                                                                                                                                                                                                                               |                                           | 194 Bytes | N/A  |
| ├─IndexRangeScan_8(Build)     | 0.00    | 0       | cop[tikv] | table:t1, index:ae(a, e) | time:239µs, loops:1, cop_task: {num: 1, max: 209.1µs, proc_keys: 0, rpc_num: 1, rpc_time: 202.2µs, copr_cache_hit_ratio: 0.00}, tikv_task:{time:0s, loops:1}, scan_detail: {total_process_keys: 0, total_keys: 1, rocksdb: {delete_skipped_count: 0, key_skipped_count: 0, block: {cache_hit_count: 0, read_count: 0, read_byte: 0 Bytes}}}    | range:["A" "E","A" "E"], keep order:false | N/A       | N/A  |
| └─TableRowIDScan_9(Probe)     | 0.00    | 0       | cop[tikv] | table:t1                 |                                                                                                                                                                                                                                                                                                                                                | keep order:false                          | N/A       | N/A  |
+-------------------------------+---------+---------+-----------+--------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------+-----------+------+
3 rows in set (0.00 sec)

mysql> EXPLAIN ANALYZE SELECT * FROM t1 FORCE INDEX (e) WHERE e='E';
+-------------------------------+---------+---------+-----------+----------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------+---------+------+
| id                            | estRows | actRows | task      | access object        | execution info                                                                                                                                                                                                                                                                                                                                   | operator info                     | memory  | disk |
+-------------------------------+---------+---------+-----------+----------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------+---------+------+
| IndexLookUp_7                 | 1.00    | 1       | root      |                      | time:834.9µs, loops:2, index_task: {total_time: 408.6µs, fetch_handle: 398.7µs, build: 1.3µs, wait: 8.52µs}, table_task: {total_time: 2.52ms, num: 1, concurrency: 5}                                                                                                                                                                            |                                   | 10.2 KB | N/A  |
| ├─IndexRangeScan_5(Build)     | 1.00    | 1       | cop[tikv] | table:t1, index:e(e) | time:395.2µs, loops:3, cop_task: {num: 1, max: 343.1µs, proc_keys: 1, rpc_num: 1, rpc_time: 331.3µs, copr_cache_hit_ratio: 0.00}, tikv_task:{time:0s, loops:1}, scan_detail: {total_process_keys: 1, total_keys: 2, rocksdb: {delete_skipped_count: 0, key_skipped_count: 1, block: {cache_hit_count: 0, read_count: 0, read_byte: 0 Bytes}}}    | range:["E","E"], keep order:false | N/A     | N/A  |
| └─TableRowIDScan_6(Probe)     | 1.00    | 1       | cop[tikv] | table:t1             | time:292.3µs, loops:2, cop_task: {num: 1, max: 258.9µs, proc_keys: 1, rpc_num: 1, rpc_time: 252.7µs, copr_cache_hit_ratio: 0.00}, tikv_task:{time:0s, loops:1}, scan_detail: {total_process_keys: 1, total_keys: 1, rocksdb: {delete_skipped_count: 0, key_skipped_count: 0, block: {cache_hit_count: 0, read_count: 0, read_byte: 0 Bytes}}}    | keep order:false                  | N/A     | N/A  |
+-------------------------------+---------+---------+-----------+----------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------+---------+------+
3 rows in set (0.00 sec)
```

So what this is showing is different to the earlier output; tikv is able to use the index on `(e)`, but it won't be selected without `FORCE INDEX (e)`. This is not a bug however; the clustered index is more efficient here since all the data is in one region.

If I try some other examples, it uses the index fine:

```sql
mysql> EXPLAIN ANALYZE SELECT count(*) FROM t1 WHERE e='E';
+-----------------------------+---------+---------+-----------+----------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------+-----------+------+
| id                          | estRows | actRows | task      | access object        | execution info                                                                                                                                                                                              | operator info                     | memory    | disk |
+-----------------------------+---------+---------+-----------+----------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------+-----------+------+
| StreamAgg_17                | 1.00    | 1       | root      |                      | time:472.8µs, loops:2                                                                                                                                                                                       | funcs:count(Column#7)->Column#5   | 380 Bytes | N/A  |
| └─IndexReader_18            | 1.00    | 1       | root      |                      | time:469.5µs, loops:2, cop_task: {num: 1, max: 397.7µs, proc_keys: 1, rpc_num: 1, rpc_time: 379.2µs, copr_cache_hit_ratio: 0.00}                                                                            | index:StreamAgg_9                 | 220 Bytes | N/A  |
|   └─StreamAgg_9             | 1.00    | 1       | cop[tikv] |                      | tikv_task:{time:0s, loops:1}, scan_detail: {total_process_keys: 1, total_keys: 2, rocksdb: {delete_skipped_count: 0, key_skipped_count: 1, block: {cache_hit_count: 0, read_count: 0, read_byte: 0 Bytes}}} | funcs:count(1)->Column#7          | N/A       | N/A  |
|     └─IndexRangeScan_16     | 2.00    | 1       | cop[tikv] | table:t1, index:e(e) | tikv_task:{time:0s, loops:1}                                                                                                                                                                                | range:["E","E"], keep order:false | N/A       | N/A  |
+-----------------------------+---------+---------+-----------+----------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------+-----------+------+
4 rows in set (0.00 sec)
```

So I am going to go ahead and close this. If you discover another issue, please feel free to open a new issue. Thanks!

**Closed by morgo** 2021-07-29 00:27 UTC
Labels: challenge-program, help wanted, sig/planner, type/feature-request

**Comment by morgo** [comment] 2021-07-29 00:34
The related issue to track the work is: https://github.com/pingcap/tidb/issues/23619
