### ISSUE TITLE
tidb oom when insert 4m big value

### ISSUE THREAD

**Issue by Lily2025** [pingcap/tidb#36503] opened 2022-07-25 02:15 UTC
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
tidb：8core 32GB
insert 4m big value with 256 Concurrency
code：
https://github.com/pingcap/endless/blob/master/pkg/workload/append.go

### 2. What did you expect to see? (Required)
tidb shoud not oom

### 3. What did you see instead (Required)
After running for a while, one tidb oom
![SgMUMT1bv3](https://user-images.githubusercontent.com/84712107/180680119-2115e8fc-a98c-413e-8d44-6cbffbc68035.jpg)
w := workload.AppendWorkload{
		DB:          db,
		Concurrency: 256,
		Tables:      256,
		PadLength:   4000000,
	}
    	Try(w.Prepare())
		w.Run(gctx)

### 4. What is your TiDB version? (Required)
./tidb-server -V
 Release Version: v6.2.0-alpha
Edition: Community
Git Commit Hash: 28a8ffcf67f9b1979920d03c29a54842314aa921
Git Branch: heads/refs/tags/v6.2.0-alpha
UTC Build Time: 2022-07-23 11:07:09
GoVersion: go1.18.2
Race Enabled: false
TiKV Min Version: 6.2.0-alpha
Check Table Before Drop: false
Store: unistore

**Comment by XuHuaiyu** [comment] 2022-07-25 08:36
reproducible script:
[main.txt](https://github.com/pingcap/tidb/files/9179435/main.txt)

**Comment by XuHuaiyu** [comment] 2022-07-25 08:44
1. The dashboard shows that inuse space is about 7GB~13GB.
 
<img width="875" alt="截屏2022-07-25 下午4 39 23" src="https://user-images.githubusercontent.com/9039012/180735201-ab388f2f-d4bf-40b4-87b5-83354a3e6df1.png">

2. We can only see ~5.6GB inuse memory space from the profile
<img width="1702" alt="截屏2022-07-25 下午4 37 59" src="https://user-images.githubusercontent.com/9039012/180735226-6b8dc2f0-a3a5-4d49-a8b1-9a0e5389029c.png">

3. We can see from the alloc_space that `GetTextToLog` allocates too many small objects, which are GCed thus we can not see from the profile inuse space.
<img width="1147" alt="截屏2022-07-25 下午4 42 55" src="https://user-images.githubusercontent.com/9039012/180735864-c129b42b-ba75-483d-aeda-01dfb35620b2.png">

**Comment by tiancaiamao** [comment] 2022-07-26 04:08
After analyzing the [heap profile](https://github.com/pingcap/tidb/files/9179498/heap_tidb_172.16.4.7_4040_1658737560.txt), I find the memory usage is expected.

Maybe you can try the non-prepared SQL, it might reduce the memory by more than a half.

**Comment by tiancaiamao** [comment] 2022-07-26 04:10
Or a tiny optimization could be, after `handleStmtExecute`, we clean up the params for the prepared statment. @qw4990

**Comment by qw4990** [comment] 2022-08-18 03:05
> Or a tiny optimization could be, after `handleStmtExecute`, we clean up the params for the prepared statment. @qw4990

OK, I'll take a look at this in Sprint10. It should be an enhancement instead of a bug.

**Comment by tiancaiamao** [comment] 2022-09-29 00:13
After https://github.com/pingcap/tidb/pull/33651, the reproduce script fail to run.

**Comment by tiancaiamao** [comment] 2023-09-06 11:09
I test this again with tiup nightly...
Since the nightly use general plan cache,  the performance should be better
(nightly, not master because master disable it https://github.com/pingcap/tidb/pull/46504)

I have some new findings.
The actually inuse memory is 6G (<7G) stably, and the RSS is 27G ...
'reserved by Go' takes too much memory

And after I run  "set @@global.tidb_enable_gogc_tuner = 0",  the memory usage decrease a lot!
From 29G -> 15G, as you see from the below picture.

![image](https://github.com/pingcap/tidb/assets/1420062/167be007-418d-454a-8639-5027e81af667)

And the 'reserved-by-go' nearly gone.


So this OOM issue is by the gctunner feature, and we can workaround it, close this issue.

**Closed by tiancaiamao** 2023-09-06 11:09 UTC
Labels: type/enhancement, sig/planner, epic/plan-cache
