### ISSUE TITLE
Digester produces invalid sql for selecting global variables

### ISSUE THREAD

**Issue by wwar** [pingcap/tidb#18224] opened 2020-06-28 01:08 UTC
### 1. Minimal reproduce step (Required)

The digester produces an invalid SQL for the following statement:

```sql
SELECT @@global.tidb_stmt_summary_refresh_interval AS value
```

This statement is [generated by the tidb-dashboard](https://github.com/pingcap-incubator/tidb-dashboard/blob/df682d9eb42a34bf53cd9aec113cc8bf4dbe8865/pkg/apiserver/statement/queries.go#L34-L50).

I have another digester bug in https://github.com/pingcap/tidb/issues/14241 - it is annoying when the syntax generated back is invalid.

### 2. What did you expect to see? (Required)

```sql
SELECT @@global.tidb_stmt_summary_refresh_interval AS value
```

### 3. What did you see instead (Required)

There is a space between the two @ symbols:

```sql
SELECT @ @global.tidb_stmt_summary_refresh_interval AS value
```

### 4. Affected version (Required)

```
mysql> select tidb_version()\G
*************************** 1. row ***************************
tidb_version(): Release Version: v4.0.0-beta.2-684-gf590d74e1
Edition: Community
Git Commit Hash: f590d74e158cf4e33555bfeb8f88971af5956697
Git Branch: master
UTC Build Time: 2020-06-27 02:29:48
GoVersion: go1.13.8
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
1 row in set (0.00 sec)
```

**Comment by wjhuang2016** [comment] 2020-11-16 09:33
@nullnotnil I can't reproduce it in both v4.0.8 and master, could you reproduce it?

**Comment by crazycs520** [comment] 2020-11-16 09:42
@wjhuang2016 I can reproduce it, It may be caused by dashboard format SQL before display.

![image](https://user-images.githubusercontent.com/26020263/99237183-1b378a80-2833-11eb-8394-0bd4dafd0bfb.png)

**Comment by wjhuang2016** [comment] 2020-11-16 10:57
I move it to the dashboard's repo and close it now.

**Closed by wjhuang2016** 2020-11-16 10:57 UTC
Labels: component/parser, severity/major, sig/DDL
