### ISSUE TITLE
TiDB is case insensitive to schema/table name while MySQL 5.7/8.0 is case sentive by default

### ISSUE THREAD

**Issue by ericsyh** [pingcap/tidb#10817] opened 2019-06-15 09:47 UTC
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

Tested on MySQL 8.0 
```
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 8
Server version: 8.0.16 MySQL Community Server - GPL

Copyright (c) 2000, 2019, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> create database T;
Query OK, 1 row affected (0.28 sec)

mysql> create database t;
Query OK, 1 row affected (0.03 sec)

mysql> show databases;
+--------------------+
| Database           |
+--------------------+
| T                  |
| information_schema |
| mysql              |
| performance_schema |
| sys                |
| t                  |
+--------------------+
6 rows in set (0.01 sec)
```
Tested on MySQL 5.7 
```
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 3
Server version: 5.7.26-0ubuntu0.18.04.1 (Ubuntu)

Copyright (c) 2000, 2019, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> create database T;
Query OK, 1 row affected (0.00 sec)

mysql> create database t;
Query OK, 1 row affected (0.00 sec)

mysql> show databases;
+--------------------+
| Database           |
+--------------------+
| information_schema |
| T                  |
| _gravity           |
| ericsyh            |
| helloJiu           |
| mysql              |
| performance_schema |
| sys                |
| t                  |
+--------------------+
9 rows in set (0.00 sec)
```
Tested on TiDB:
```
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 4
Server version: 5.7.25-TiDB-v3.0.0-rc.1-191-gbb3a92d70 MySQL Community Server (Apache License 2.0)

Copyright (c) 2000, 2019, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> create database T;
Query OK, 0 rows affected (0.26 sec)

mysql> create database t;
ERROR 1007 (HY000): Can't create database 't'; database exists
```

2. What did you expect to see?
TiDB should be case sensitive to schema/table name like MySQL by default.

3. What did you see instead?
TiDB should is case sensitive  to schema/table name by by default.

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

```
| Release Version: v3.0.0-rc.1-191-gbb3a92d70
Git Commit Hash: bb3a92d70f018bf11fe630f7e0328c6a95b10dd0
Git Branch: master
UTC Build Time: 2019-06-14 07:48:18
GoVersion: go version go1.12 linux/amd64
Race Enabled: false
TiKV Min Version: 2.1.0-alpha.1-ff3dd160846b7d1aed9079c389fc188f7f5ea13e
Check Table Before Drop: false |
```

**Comment by morgo** [comment] 2019-06-15 14:18
Note that this is currently [documented here](https://pingcap.com/docs/dev/reference/mysql-compatibility/#default-differences):
```
Default value of lower_case_table_names:
The default value in TiDB is 2 and currently TiDB only supports 2.
The default value in MySQL:
On Linux: 0
On Windows: 1
On macOS: 2
```

**Comment by ericsyh** [comment] 2019-06-15 14:22
I see. Thx Morgan.

**Comment by morgo** [comment] 2019-06-15 14:24
I didn't mean for you to have to close it :-) Perhaps we can leave an issue open so that users can comment if this issue affects them?

**Comment by ericsyh** [comment] 2019-06-15 14:36
Sounds reasonable :)  I reopen this issue. 
And users currently can use [DM table-routing](https://pingcap.com/docs/dev/reference/tools/data-migration/features/overview/#table-routing) if their MySQL schema/table names will conflict in TiDB.

**Comment by morgo** [comment] 2020-12-07 17:46
Closing as a duplicate of https://github.com/pingcap/tidb/issues/5714

**Closed by morgo** 2020-12-07 17:46 UTC
Labels: sig/DDL, type/compatibility
