### ISSUE TITLE
some errors for cancel ddl jobs

### ISSUE THREAD

**Issue by aytrack** [pingcap/tidb#50612] opened 2024-01-21 07:02 UTC
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1. add index with multi-schema change, using local sort Distributed eXecution Framework (DXF)
2. cancel the ddl jobs for step1 ddl jobs
3. add index like step1
4. 

### 3. What did you see instead (Required)
1. after cancel the ddl jobs, `admin show ddl jobs` show the first add index ddl job already in `cancelled` and `rollbackdone`
![图片](https://github.com/pingcap/tidb/assets/10184437/f7aa1015-eb0a-4594-b103-c74a9e5aa8bc)

2. execute drop index for the duplicate index, readd index 
- from `show ddl jobs` this job state is running
- but check from `mysql.tidb_background_subtask` show the new job subtask state is cancelled or reverting.
- a subtask of first ddl job is revert-pending
- check log， found the first ddl job is not cancelled
![图片](https://github.com/pingcap/tidb/assets/10184437/7ec66b45-5b7d-4def-936d-bb90932dddcf)

### 4. What is your TiDB version? (Required)
master https://github.com/pingcap/tidb/commit/6db1d6b79c2855cf022f04ced86af3e6bc8b0dcf

**Comment by wjhuang2016** [comment] 2024-05-11 02:54
Close it since we can't reproduce it.

**Closed by wjhuang2016** 2024-05-11 02:54 UTC
Labels: type/bug, severity/major, may-affects-5.4, may-affects-6.1, may-affects-6.5, may-affects-7.1, component/ddl, may-affects-7.5, affects-8.1
