### ISSUE TITLE
Panic when llogExpensiveQuery

### ISSUE THREAD

**Issue by crazycs520** [pingcap/tidb#18464] opened 2020-07-09 13:40 UTC
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

This is panic when I use TiDB Dashboard.

Related TiDB log is here:

```sql
[2020/07/09 21:12:26.334 +08:00] [ERROR] [coprocessor.go:673] ["copIteratorWork meet panic"] [r={}] ["stack trace"="github.com/pingcap/tidb/store/tikv.(*copIteratorWorker).handleTask.func1
	/home/pingcap/cs/tidb/store/tikv/coprocessor.go:675
runtime.gopanic
	/usr/local/go1.13.11/src/runtime/panic.go:679
runtime.assertE2I
	/usr/local/go1.13.11/src/runtime/iface.go:475
github.com/pingcap/tidb/planner/core.GetStatsInfo
	/home/pingcap/cs/tidb/planner/core/util.go:232
github.com/pingcap/tidb/util/expensivequery.genLogFields
	/home/pingcap/cs/tidb/util/expensivequery/expensivequery.go:112
github.com/pingcap/tidb/util/expensivequery.logExpensiveQuery
	/home/pingcap/cs/tidb/util/expensivequery/expensivequery.go:168
github.com/pingcap/tidb/util/expensivequery.(*Handle).LogOnQueryExceedMemQuota
	/home/pingcap/cs/tidb/util/expensivequery/expensivequery.go:101
github.com/pingcap/tidb/util/memory.(*PanicOnExceed).Action
	/home/pingcap/cs/tidb/util/memory/action.go:94
github.com/pingcap/tidb/util/memory.(*Tracker).Consume
	/home/pingcap/cs/tidb/util/memory/tracker.go:226
github.com/pingcap/tidb/store/tikv.(*copIteratorWorker).sendToRespCh
	/home/pingcap/cs/tidb/store/tikv/coprocessor.go:597
github.com/pingcap/tidb/store/tikv.(*copIteratorWorker).handleCopResponse
	/home/pingcap/cs/tidb/store/tikv/coprocessor.go:1042
github.com/pingcap/tidb/store/tikv.(*copIteratorWorker).handleTaskOnce
	/home/pingcap/cs/tidb/store/tikv/coprocessor.go:772
github.com/pingcap/tidb/store/tikv.(*copIteratorWorker).handleTask
	/home/pingcap/cs/tidb/store/tikv/coprocessor.go:686
github.com/pingcap/tidb/store/tikv.(*copIteratorWorker).run
	/home/pingcap/cs/tidb/store/tikv/coprocessor.go:493"]
[2020/07/09 21:12:26.335 +08:00] [ERROR] [conn.go:737] ["command dispatched failed"] [conn=7381] [connInfo="id:7381, addr:172.16.4.4:43618 status:10, collation:utf8mb4_general_ci, user:root"] [command=Execute] [status="inTxn:0, autocommit:1"] [sql="SELECT *, (unix_timestamp(Time) + 0E0) as timestamp FROM `INFORMATION_SCHEMA`.`CLUSTER_SLOW_QUERY`  WHERE (time between from_unixtime(?) and from_unixtime(?)) AND (DB IN (?,?,?)) ORDER BY Query_time desc LIMIT 100 [arguments: (1594298496, 1594300296, sbtest, test, tpch)]"] [txn_mode=PESSIMISTIC] [err="interface conversion: interface is nil, not core.Plan
github.com/pingcap/tidb/store/tikv.(*copIteratorWorker).handleTask.func1
	/home/pingcap/cs/tidb/store/tikv/coprocessor.go:676
runtime.gopanic
	/usr/local/go1.13.11/src/runtime/panic.go:679
runtime.assertE2I
	/usr/local/go1.13.11/src/runtime/iface.go:475
github.com/pingcap/tidb/planner/core.GetStatsInfo
	/home/pingcap/cs/tidb/planner/core/util.go:232
github.com/pingcap/tidb/util/expensivequery.genLogFields
	/home/pingcap/cs/tidb/util/expensivequery/expensivequery.go:112
github.com/pingcap/tidb/util/expensivequery.logExpensiveQuery
	/home/pingcap/cs/tidb/util/expensivequery/expensivequery.go:168
github.com/pingcap/tidb/util/expensivequery.(*Handle).LogOnQueryExceedMemQuota
	/home/pingcap/cs/tidb/util/expensivequery/expensivequery.go:101
github.com/pingcap/tidb/util/memory.(*PanicOnExceed).Action
	/home/pingcap/cs/tidb/util/memory/action.go:94
github.com/pingcap/tidb/util/memory.(*Tracker).Consume
	/home/pingcap/cs/tidb/util/memory/tracker.go:226
github.com/pingcap/tidb/store/tikv.(*copIteratorWorker).sendToRespCh
	/home/pingcap/cs/tidb/store/tikv/coprocessor.go:597
github.com/pingcap/tidb/store/tikv.(*copIteratorWorker).handleCopResponse
	/home/pingcap/cs/tidb/store/tikv/coprocessor.go:1042
github.com/pingcap/tidb/store/tikv.(*copIteratorWorker).handleTaskOnce
	/home/pingcap/cs/tidb/store/tikv/coprocessor.go:772
github.com/pingcap/tidb/store/tikv.(*copIteratorWorker).handleTask
	/home/pingcap/cs/tidb/store/tikv/coprocessor.go:686
github.com/pingcap/tidb/store/tikv.(*copIteratorWorker).run
	/home/pingcap/cs/tidb/store/tikv/coprocessor.go:493
runtime.goexit
	/usr/local/go1.13.11/src/runtime/asm_amd64.s:1357
SELECT *, (unix_timestamp(Time) + 0E0) as timestamp FROM `INFORMATION_SCHEMA`.`CLUSTER_SLOW_QUERY`  WHERE (time between from_unixtime(?) and from_unixtime(?)) AND (DB IN (?,?,?)) ORDER BY Query_time desc LIMIT 100 [arguments: (1594298496, 1594300296, sbtest, test, tpch)]"]
[2020/07/09 21:12:26.335 +08:00] [INFO] [server.go:391] ["connection closed"] [conn=7381]

```

### 4. Affected version (Required)

master branch.

Git hash: da90b23e6af6ad6bf8091a90654827a1e405b780

**Comment by SunRunAway** [comment] 2020-07-10 08:30
Duplicate of #17419

**Closed by SunRunAway** 2020-07-10 08:30 UTC
Labels: component/executor, type/bug
