### ISSUE TITLE
Crash in lockstore.(*arena).get

### ISSUE THREAD

**Issue by secsys-go** [pingcap/tidb#39060] opened 2022-11-10 07:00 UTC
## Bug Report

We used the Fuzz engine to modify some Test(TestReplace) data, and then the following crash appeared. We hope to get the help of the developer to confirm whether it is a real bug.

### 1. Minimal reproduce step (Required)

Simplified Test Code

```go
NewMemStore(0)
```

### 2. What did you expect to see? (Required)

Test Passed

### 3. What did you see instead (Required)

Crash Log

```go
panic: runtime error: index out of range [-1] [recovered]
	panic: runtime error: index out of range [-1]

goroutine 6 [running]:
testing.tRunner.func1.2({0x63bd00, 0xc00001a330})
	/home/gogen/.local/go/src/testing/testing.go:1209 +0x24e
testing.tRunner.func1()
	/home/gogen/.local/go/src/testing/testing.go:1212 +0x218
panic({0x63bd00, 0xc00001a330})
	/home/gogen/.local/go/src/runtime/panic.go:1038 +0x215
github.com/pingcap/tidb/store/mockstore/unistore/lockstore.(*arena).get(0xc000012500, 0x90, 0x203000)
	/home/gogen/workspace/gowork/src/topproj/tidb/store/mockstore/unistore/lockstore/arena.go:79 +0x250
github.com/pingcap/tidb/store/mockstore/unistore/lockstore.(*MemStore).newNode(0xc000111650, 0xc0000124b0, {0x0, 0x0, 0xc0000e5e58}, {0x0, 0x0, 0x639ae0}, 0x10)
	/home/gogen/workspace/gowork/src/topproj/tidb/store/mockstore/unistore/lockstore/lockstore.go:366 +0x372
github.com/pingcap/tidb/store/mockstore/unistore/lockstore.(*MemStore).setHeadNode(0xc000111650)
	/home/gogen/workspace/gowork/src/topproj/tidb/store/mockstore/unistore/lockstore/lockstore.go:118 +0x3b
github.com/pingcap/tidb/store/mockstore/unistore/lockstore.NewMemStore(0x0)
	/home/gogen/workspace/gowork/src/topproj/tidb/store/mockstore/unistore/lockstore/lockstore.go:113 +0x20f
github.com/pingcap/tidb/store/mockstore/unistore/lockstore.FuzzTestReplace({0xc000206000, 0x0, 0x200})
	/home/gogen/workspace/gowork/src/topproj/tidb/store/mockstore/unistore/lockstore/lockstore_test.go_TestReplace_test.go:29 +0xac
```

### 4. What is your TiDB version? (Required)

9c4f94dd70010806710153d27fd5b734f99c4cb1

**Comment by YangKeao** [comment] 2022-11-11 05:35
I think `NewMemStore` should accept an argument greater than 1. It's not a bug so I'll close this issue. If anyone has further consideration, feel free to reopen this issue and comment with your findings :smiley: .

----

BTW, @secsys-go, I've seen you created a lot of interesting issues :heart:, which are created through modifying the test procedure. Some of these problems are meaningful, while some of them are too trivial (as programmers always have some convention about the arguments of functions / variables...), and fuzz test is always hard in this situation :cry: .

I'm also interested about the strategy / technology you are using. Are you automatically modifying test codes? So cool :+1:  .

If you need more help from us, feel free to open new issues or contact us through email.

**Closed by YangKeao** 2022-11-11 05:35 UTC
Labels: type/bug
