### ISSUE TITLE
TiDBRestrictedReadOnly should be checked on commit

### ISSUE THREAD

**Issue by morgo** [pingcap/tidb#32895] opened 2022-03-08 05:00 UTC
## Enhancement

The problem is that the value of restricted-read-only is only checked when the statement is optimized. The worst case is a long running auto-commit statement, since it will check at the start, but not before the statement commits.

I did a quick test with a simple auto-commit insert that takes 10 seconds:

```sql
insert into t1 values (sleep(10));
```

I think the fix is really easy. We should check again at commit time for any user-generated commits (i.e. not restricted):

```sql
morgo@ubuntu:~/go/src/github.com/morgo/tidb$ git diff
diff --git a/session/session.go b/session/session.go
index c195691fa..b725c48f1 100644
--- a/session/session.go
+++ b/session/session.go
@@ -524,9 +524,16 @@ func (s *session) doCommit(ctx context.Context) error {
                s.sessionVars.SetInTxn(false)
                s.ClearDiskFullOpt()
        }()
+       // check if the transaction is read-only
        if s.txn.IsReadOnly() {
                return nil
        }
+       // check if the cluster is read-only
+       if variable.RestrictedReadOnly.Load() && !s.sessionVars.InRestrictedSQL {
+               s.RollbackTxn(ctx)
+               return errors.New("we are in read_only_mode")
+       }
+
        err := s.checkPlacementPolicyBeforeCommit()
        if err != nil {
                return err
```

This will reduce the scenarios where restricted read-only differs from MySQL significantly.

**Comment by morgo** [comment] 2022-03-08 05:01
@ichn-hu what do you think?

**Comment by ichn-hu** [comment] 2022-03-08 05:05
you mean, the problem is, for a long-running transaction that starts before the enabling of the read-only mode, although the read-only is enabled, it would still be committed because we only check read-only at start?

**Comment by morgo** [comment] 2022-03-08 22:55
> you mean, the problem is, for a long-running transaction that starts before the enabling of the read-only mode, although the read-only is enabled, it would still be committed because we only check read-only at start?

That's right. Or more specifically it is a long-running auto-commit transaction. i.e. there is no `COMMIT` statement which is executed later which will check the flag again.

The common scenario is a long running delete or update statement.

**Closed** 2022-06-22 12:32 UTC
Labels: type/enhancement
