### ISSUE TITLE
json type exported by mydumper, but can't be executed in TIDB

### ISSUE THREAD

**Issue by jianhaiqing** [pingcap/tidb#8701] opened 2018-12-16 02:57 UTC
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

DDL:
```
CREATE TABLE my_dict  (
  id int(11) NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  dict_value json NOT NULL COMMENT 'key对应的值',
  create_time datetime NOT NULL COMMENT '创建时间',
  update_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  is_deleted tinyint(1) DEFAULT '0' COMMENT '是否已经被删除',
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
```
sql generated by mydumper:

```text
/*!40101 SET NAMES binary*/;
/*!40014 SET FOREIGN_KEY_CHECKS=0*/;
INSERT INTO `my_dict` VALUES
(5,CONVERT("[\"课堂表现积极\", \"值得表扬\", \"上课不认真\", \"作业认真完成\", \"作业没有完成\", \"望家长多关注\", \"再接再厉\", \"态度端正\", \"课上认真听讲\", \"期待你更好的表现\", \"希望能有所进步\", \"要多加注意\", \"进步很大\", \"主动服务大家\", \"表现不错\"]" USING UTF8MB4),"2018-01-30 16:19:46","2018-02-02 19:46:49",0);
```
2. What did you expect to see?

`sql exported by mydumper can be loaded into TIDB.`

3. What did you see instead?

`ERROR 1105 (HY000): line 1 column 5 near " /data/tidb/mydumper/my_dict.sql" (total length 65)`

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

```
 Release Version: v2.1.1
Git Commit Hash: 990f859384b834fe5edf1410d2a4142def5c3fa9
Git Branch: release-2.1
UTC Build Time: 2018-12-12 10:57:44
GoVersion: go version go1.11.2 linux/amd64
Race Enabled: false
TiKV Min Version: 2.1.0-alpha.1-ff3dd160846b7d1aed9079c389fc188f7f5ea13e
Check Table Before Drop: false
```

**Comment by shenli** [comment] 2018-12-16 03:46
@jianhaiqing Thanks for your feedback. We will take a look.

**Comment by lysu** [comment] 2018-12-17 03:19
@jianhaiqing hi, what load command do you used(I can't reproduce problem by `source [file]`)? 

and could you provide the tidb-server log during `ERROR 1105 (HY000): line 1 column 5 near " /data/tidb/mydumper/my_dict.sql" (total length 65)`

thanks~

**Comment by jianhaiqing** [comment] 2018-12-18 04:20
I can't reproduce either.
[https://github.com/pingcap/tidb-tools/issues/144](Maybe it's the same as this issue.)
I definitely use source to load the sql, and it failed. But the test machine is destroyed.
We can close the issue.

**Comment by nullnotnil** [comment] 2020-07-10 17:48
Closing this issue per the last comment.

**Closed by nullnotnil** 2020-07-10 17:48 UTC
Labels: type/bug, type/compatibility
