### ISSUE TITLE
Although the CASE WHEN clause returns the same value as the direct concatenation, FIELD yields different results in each case

### ISSUE THREAD

**Issue by akuluasan** [pingcap/tidb#56553] opened 2024-10-11 03:24 UTC
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```sql
select FIELD((case when true then ('i' || 'o') else '0' end), 'c') as c0;
select FIELD(('i' || 'o'), 'c') as c0;

```

### 2. What did you expect to see? (Required)
The condition for CASE WHEN is TRUE, so this clause should return the result of ('i' || 'o'). This statement should return the same value as select FIELD(('i' || 'o'), 'c') as c0;, but the actual result is not the same.
They should return the same result

### 3. What did you see instead (Required)
```sql
 select FIELD((case when true then ('i' || 'o') else '0' end), 'c') as c0; 
+----+
| c0 |
+----+
|  0 |
+----+
1 row in set, 2 warnings (0.00 sec)

 select FIELD(('i' || 'o'), 'c') as c0;
+----+
| c0 |
+----+
|  1 |
+----+

```

### 4. What is your TiDB version? (Required)

```
 select version();
+--------------------+
| version()          |
+--------------------+
| 8.0.11-TiDB-v7.5.1 |
+--------------------+
1 row in set (0.00 sec)

```

**Comment by windtalker** [comment] 2024-10-15 07:15
The root cause is, for 
`select FIELD((case when true then ('i' || 'o') else '0' end), 'c') as c0; `
The return type of `case when true then ('i' || 'o') else '0' end` is the super type of `('i' || 'o')` and `'0'`
type of `('i' || 'o')` is int, and type of `'0'` is string, so the return type of `case when true then ('i' || 'o') else '0' end` is string,
FIELD(string, 'c') will be evaluated as 
https://github.com/pingcap/tidb/blob/cf5e1baecbffbf9ea1f72cffa71705d206490617/pkg/expression/builtin_string.go#L2625
The return value of `case when true then ('i' || 'o') else '0' end` is `'0'`, and `'0' != 'c'`, so
`select FIELD((case when true then ('i' || 'o') else '0' end), 'c') as c0; ` returns 0
For `select FIELD(('i' || 'o'), 'c') as c0;`
The return type of `('i' || 'o')` is int, so the FIELD is actually FIELD(int, 'c'), and it will be evaluated as
https://github.com/pingcap/tidb/blob/cf5e1baecbffbf9ea1f72cffa71705d206490617/pkg/expression/builtin_string.go#L2596
Both `('i' || 'o')` and `'c'` will be converted to real, it actually convert the orignal function to `FIELD(0, 0)`, since `0 == 0`, it returns 1.
I test this in MySQL 8.0.27, and the behavior is the same as TiDB.
So I will close this issue as not a bug.

**Closed by windtalker** 2024-10-15 07:15 UTC
Labels: type/bug, sig/execution, severity/major, may-affects-5.4, may-affects-6.1, may-affects-6.5, may-affects-7.1, may-affects-7.5, may-affects-8.1, impact/wrong-result

**Comment by akuluasan** [comment] 2024-10-27 12:21
@windtalker Yes, it's consistent with MySQL. I came across this [bug report](https://bugs.mysql.com/bug.php?id=112149) for MySQL and found that TiDB exhibited the same performance. MySQL also confirmed the bug report. Therefore, I tested it and decided to submit it here.

**Comment by windtalker** [comment] 2024-10-28 00:32
> @windtalker Yes, it's consistent with MySQL. I came across this [bug report](https://bugs.mysql.com/bug.php?id=112149) for MySQL and found that TiDB exhibited the same performance. MySQL also confirmed the bug report. Therefore, I tested it and decided to submit it here.

Thanks for your explaination. In my opinion it is hardly to say that this is an inconsistent bug, the reason that you think it should be an inconsistent bug is that `case when true then ('i' || 'o') else '0' end` should return exactly the same thing as `('i' || 'o')`, which unfortunately is not true, because the return type of `case when true then ('i' || 'o') else '0' end` and `('i' || 'o')` is not the same.
