### ISSUE TITLE
Incompatible behavior with utf8 charset

### ISSUE THREAD

**Issue by espresso98** [pingcap/tidb#32606] opened 2022-02-24 07:15 UTC
### 1. Minimal reproduce step
```sql
create table t1 (a char(10), key(a)) character set utf8;
insert into t1 values ("a"),("abc"),("abcd"),("hello"),("test");
select * from t1 where a like "abc%";
select * from t1 where a like concat("abc","%");
select * from t1 where a like "ABC%";
```
### 2. What did you expect to see? 
```sql
mysql> select * from t1 where a like "abc%";
+------+
| a    |
+------+
| abc  |
| abcd |
+------+
2 rows in set (0.00 sec)

mysql> select * from t1 where a like concat("abc","%");
+------+
| a    |
+------+
| abc  |
| abcd |
+------+
2 rows in set (0.00 sec)

mysql> select * from t1 where a like "ABC%";
+------+
| a    |
+------+
| abc  |
| abcd |
+------+
2 rows in set (0.00 sec)
```

### 3. What did you see instead 
```sql
tidb> select * from t1 where a like "abc%";
+------+
| a    |
+------+
| abc  |
| abcd |
+------+
2 rows in set (0.01 sec)

tidb> select * from t1 where a like concat("abc","%");
+------+
| a    |
+------+
| abc  |
| abcd |
+------+
2 rows in set (0.00 sec)

tidb> select * from t1 where a like "ABC%";
Empty set (0.01 sec)
```

### 4. What is your TiDB version? 
```
tidb_version(): Release Version: v5.5.0-alpha-210-g11f4ca802
Edition: Community
Git Commit Hash: 11f4ca802083ee38d5972730ba8f9b72395316fb
Git Branch: master
UTC Build Time: 2022-02-24 04:52:01
GoVersion: go1.17.2
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
```

**Comment by aytrack** [comment] 2022-02-24 09:50
the default collation for `utf8` in mysql is  `utf8_general_ci` but in tidb is `utf8_bin`. The result is depend on the collation.

mysql :
```sql 
mysql> show collation where charset = 'utf8' and `Default` = 'Yes';
+-----------------+---------+----+---------+----------+---------+---------------+
| Collation       | Charset | Id | Default | Compiled | Sortlen | Pad_attribute |
+-----------------+---------+----+---------+----------+---------+---------------+
| utf8_general_ci | utf8    | 33 | Yes     | Yes      |       1 | PAD SPACE     |
+-----------------+---------+----+---------+----------+---------+---------------+
1 row in set (0.05 sec)

mysql> show create table t1;
+-------+----------------------------------------------------------------------------------------------------------+
| Table | Create Table                                                                                             |
+-------+----------------------------------------------------------------------------------------------------------+
| t1    | CREATE TABLE `t1` (
  `a` char(10) DEFAULT NULL,
  KEY `a` (`a`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 |
+-------+----------------------------------------------------------------------------------------------------------+
1 row in set (0.04 sec)

```

tidb:
```sql
MySQL root@127.0.0.1:test> show create table t1\G
***************************[ 1. row ]***************************
Table        | t1
Create Table | CREATE TABLE `t1` (
  `a` char(10) DEFAULT NULL,
  KEY `a` (`a`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin

1 row in set
Time: 0.008s
MySQL root@127.0.0.1:test> show collation where charset = 'utf8' and `Default` = 'Yes';
+-----------+---------+----+---------+----------+---------+
| Collation | Charset | Id | Default | Compiled | Sortlen |
+-----------+---------+----+---------+----------+---------+
| utf8_bin  | utf8    | 83 | Yes     | Yes      | 1       |
+-----------+---------+----+---------+----------+---------+
```

**Comment by aytrack** [comment] 2022-02-24 09:51
close this since it's not a bug, please feel free to reopen this if you have any questions.

**Closed by aytrack** 2022-02-24 09:51 UTC
Labels: type/bug
