### ISSUE TITLE
execute the same SQL repeatedly got oom error

### ISSUE THREAD

**Issue by aytrack** [pingcap/tidb#39163] opened 2022-11-15 10:36 UTC
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```sql
use test;
drop table if exists t1, t2;
create table t1(a int, index(a));
create table t2(a int, index(a));
insert t1 values(1), (2);
insert t2 values (1), (1), (2), (2);

set @@tidb_mem_quota_query=8000;
select /*+ inl_merge_join(t2)*/ * from t1 join t2 on t1.a = t2.a;  -- execute many times.
...
select /*+ inl_merge_join(t2)*/ * from t1 join t2 on t1.a = t2.a;
```

### 2. What did you expect to see? (Required)
always execute success
### 3. What did you see instead (Required)
got oom error after some times
```sql
TiDB root@127.0.0.1:test>  select /*+ inl_merge_join(t2)*/ * from t1 join t2 on t1.a = t2.a;
(1105, 'Out Of Memory Quota![conn_id=2199023255959]')

```
### 4. What is your TiDB version? (Required)
```sql
***************************[ 1. row ]***************************
tidb_version() | Release Version: v6.4.0
Edition: Community
Git Commit Hash: cf36a9ce2fe1039db3cf3444d51930b887df18a1
Git Branch: heads/refs/tags/v6.4.0
UTC Build Time: 2022-11-13 05:15:26
GoVersion: go1.19.2
Race Enabled: false
TiKV Min Version: 6.2.0-alpha
Check Table Before Drop: false
Store: unistore
```

**Comment by xuyifangreeneyes** [comment] 2022-11-15 11:15
I found that the issue happens after https://github.com/pingcap/tidb/pull/38607 by binary search of commit history.

**Comment by keeplearning20221** [comment] 2022-11-16 02:24
This meets the design expectations of chunk reuse.Chunk reuse will cache the previously applied chunks and distribute them to subsequent sql.The chunk requested in chunk reuse may be larger than the requested capacity (the maximum capacity is affected by tidb_max_chunk_size).

**Comment by xuyifangreeneyes** [comment] 2022-12-13 09:30
As @keeplearning20221 said, it is not a bug. So I close it.

**Closed by xuyifangreeneyes** 2022-12-13 09:30 UTC
Labels: type/bug, sig/planner, severity/moderate, affects-6.4
