### ISSUE TITLE
Automatic Partition Maintenance

### ISSUE THREAD

**Issue by ethan7811** [pingcap/tidb#22441] opened 2021-01-20 03:20 UTC
## Feature Request

**Is your feature request related to a problem? Please describe:**

**Describe the feature you'd like:**

For time range partitioned table,  tidb does not have a mechanism to  automatic drop partition after xx days and add new partition for new day (which can implemented by stored procedure and event), so how can i maintain fix days partition automatically in tidb?

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by morgo** [comment] 2021-01-22 01:56
I think this is a duplicate of https://github.com/pingcap/tidb/issues/19132 , would you agree?

The title says "add partition automatically", but the feature request refers to INTERVAL PARTITIONING and ttl tables.

**Comment by zz-jason** [comment] 2021-04-21 11:31
Yes, I think we can track the progress in https://github.com/pingcap/tidb/issues/19132

**Closed by zz-jason** 2021-04-21 11:32 UTC
Labels: type/feature-request
