### ISSUE TITLE
SQL with join just can run one time.

### ISSUE THREAD

**Issue by DavisLinDB** [pingcap/tidb#3003] opened 2017-04-06 08:47 UTC
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
我有兩張測試表, testdata, customer
testdata有2727680筆資料
customer有6筆資料

select testdata.username1, customer.cid from testdata join customer on testdata.username1 = customer
.username1 limit 10;

用mysql client執行上述語句後, 會產生正確結果, 但是接下來就無法再下其他SQl語句了, 除非中斷連線退出mysql client重新連入才能再執行SQL語句

在改變limit後的筆數時會發生這問題

2. What did you expect to see?
結果產生後, 可以繼續操作

3. What did you see instead?
mysql client無法操作, 只能中斷連線退出

4. What version of Go are you using (`go version`)?

PD (pd1, pd2, pd3)在3台單獨linux vm, 
TiKV (tikv1, tikv2, tikv3)在另三台linux VM, 
TiDB和mysql client在一台linux VM
一共7台linux vm
各台都是1x vCore CPU, 3.75G Ram, 10G SSD, 執行CentOS 7

**Comment by shenli** [comment] 2017-04-06 09:33
@DavisLinDB Please check the tcp keep alive time of your OS. It seems that the connection is closed.

**Comment by DavisLinDB** [comment] 2017-04-06 09:46
![db](https://cloud.githubusercontent.com/assets/26958647/24747943/959dd832-1af0-11e7-9554-fbd1c8347e1c.jpg)

前一句的limit 10結果出來馬上又下了一句limit 100的, 就沒反應了, 是tcp keep alive time的問題嗎?

**Comment by shenli** [comment] 2017-04-06 09:53
Maybe it is because of server is busy. You can use a better machine and try again. 
"一共7台linux vm
各台都是1x vCore CPU, 3.75G Ram, 10G SSD, 執行CentOS 7"

May I have the log of tidb-server when you run the second sql.

**Comment by DavisLinDB** [comment] 2017-04-06 10:02
請問 tidb-server 的log存在哪裏呢? 或者我要在啟動tidb-server時下什麼指令存下log?

**Comment by shenli** [comment] 2017-04-06 10:05
You can use [--log-file](https://github.com/pingcap/docs/blob/master/op-guide/configuration.md#--log-file) to specify the log file. Or the log will be in stderr.

**Comment by DavisLinDB** [comment] 2017-04-07 01:41
2017/04/07 01:28:57 printer.go:31: [info] Welcome to TiDB.
2017/04/07 01:28:57 printer.go:32: [info] Version:
2017/04/07 01:28:57 printer.go:33: [info] Git Commit Hash: e61cd61f81fd52e539acba883071be7d124e7960
2017/04/07 01:28:57 printer.go:34: [info] UTC Build Time:  2017-03-31 06:54:56
2017/04/07 01:28:57 client.go:97: [info] [pd] create pd client with endpoints [10.140.0.2:2379 10.140.0.3:2379 10.14
0.0.4:2379]
2017/04/07 01:28:57 client.go:179: [info] [pd] leader switches to: http://10.140.0.2:2379, previous: 
2017/04/07 01:28:57 client.go:115: [info] [pd] init cluster id 6405041683590124495
2017/04/07 01:28:57 gc_worker.go:104: [info] [gc worker] 56d181d4ea40002 start.
2017/04/07 01:28:57 tidb.go:68: [info] store tikv-6405041683590124495 new domain, lease 1s
2017/04/07 01:28:57 ddl.go:177: [info] start DDL:97f2f75f-30d3-46a6-bd1d-af7c33a0afd9
2017/04/07 01:28:57 domain.go:89: [info] [ddl] full load InfoSchema from version 0 to 19, in 6.096824ms
2017/04/07 01:28:57 server.go:152: [info] Server run MySQL Protocol Listen at [0.0.0.0:4000]
2017/04/07 01:28:57 main.go:203: [info] disable Prometheus push client 
2017/04/07 01:28:57 client.go:97: [info] [pd] create pd client with endpoints [10.140.0.2:2379 10.140.0.3:2379 10.14
0.0.4:2379]
2017/04/07 01:28:57 systime_mon.go:11: [info] start system time monitor 
2017/04/07 01:28:57 client.go:179: [info] [pd] leader switches to: http://10.140.0.2:2379, previous: 
2017/04/07 01:28:57 client.go:115: [info] [pd] init cluster id 6405041683590124495
2017/04/07 01:28:57 http_status.go:78: [info] Listening on :10080 for status and metrics report.
2017/04/07 01:29:09 server.go:117: [info] [1] new connection 127.0.0.1:46730
2017/04/07 01:29:54 coprocessor.go:315: [info] [TIME_COP_TASK] 1.18723117s region(2 3 2) ranges(1) store(10.140.0.6:
20160)
2017/04/07 01:29:55 coprocessor.go:315: [info] [TIME_COP_TASK] 1.376834167s region(1005 3 4) ranges(1) store(10.140.0.7:20160)
2017/04/07 01:29:55 coprocessor.go:315: [info] [TIME_COP_TASK] 1.437676758s region(1009 3 4) ranges(1) store(10.140.0.5:20160)
2017/04/07 01:29:55 pd.go:84: [warning] get timestamp too slow: 54.129566ms
2017/04/07 01:29:55 coprocessor.go:315: [info] [TIME_COP_TASK] 1.946615021s region(1001 3 3) ranges(1) store(10.140.0.5:20160)
2017/04/07 01:34:52 server.go:117: [info] [2] new connection 127.0.0.1:47172
2017/04/07 01:34:52 server.go:212: [info] [2] close connection
2017/04/07 01:34:55 server.go:117: [info] [3] new connection 127.0.0.1:47176
2017/04/07 01:34:55 server.go:212: [info] [3] close connection

在2017/04/07 01:29:55下第二次SQL時就沒回應了
等到01:34:52還沒回應按Ctrl+C中斷連線退出mysql client

**Comment by ngaut** [comment] 2017-05-04 01:37
Ping @shenli

**Comment by shenli** [comment] 2017-05-04 02:13
@DavisLinDB Could you reproduce this bug on the latest master?

**Comment by shenli** [comment] 2017-05-04 02:57
@DavisLinDB Could you reproduce this bug on the latest master?

**Comment by DavisLinDB** [comment] 2017-05-05 02:38
same problem.

my test case:

2017/05/05 01:33:38 printer.go:31: [info] Welcome to TiDB.
2017/05/05 01:33:38 printer.go:32: [info] Version:
2017/05/05 01:33:38 printer.go:33: [info] Git Commit Hash: ec4eb933fa6786473ee31485c3d317ede63da5ac
2017/05/05 01:33:38 printer.go:34: [info] UTC Build Time:  2017-05-02 03:02:10

create table customer2 (cid bigint AUTO_INCREMENT NOT NULL PRIMARY KEY, username varchar(64),username2 varchar(64),username3 varchar(64),username4 varchar(64));
insert into customer2 (username,username2,username3,username4) values ('aaa','aaa','aaa','aaa');
insert into customer2 (username,username2,username3,username4) values ('b','b','b','b');
insert into customer2 (username,username2,username3,username4) values ('d','d','d','d');
insert into customer2 (username,username2,username3,username4) values ('d','d','d','d');
insert into customer2 (username,username2,username3,username4) values ('e','e','e','e');
insert into customer2 (username,username2,username3,username4) select username,username2,username3,username4 from customer2;
Using select/insert until customer2 table have 1 million records.

create table testdata (id bigint not null primary key AUTO_INCREMENT, cid bigint, agold decimal(18,6), bgold decimal(18,6) );
Insert into testdata (cid, agold, bgold) values (1,100,200);
Insert into testdata (cid, agold, bgold) values (2,100,200);
Insert into testdata (cid, agold, bgold) values (3,100,200);
Insert into testdata (cid, agold, bgold) values (4,100,200);
Insert into testdata (cid, agold, bgold) values (5,100,200);
Insert into testdata (cid, agold, bgold) values (6,100,200);
Insert into testdata (cid, agold, bgold) values (7,100,200);
Insert into testdata (cid, agold, bgold) values (8,100,200);
Insert into testdata (cid, agold, bgold) values (9,100,200);
Insert into testdata (cid, agold, bgold) values (10,100,200);
insert into testdata (cid, agold, bgold) select cid, agold, bgold from testdata limit 300000;
Using select/insert until testdata table have 1 million records.

select testdata.cid, customer2.username from testdata join customer2 on testdata.cid = customer2.cid limit 100;

First time, I got result:
.....
|    6 | aaa      |
|    7 | b        |
|    8 | d        |
|    9 | d        |
|   10 | e        |
|    1 | aaa      |
|    2 | b        |
+------+----------+
100 rows in set (3.47 sec)

Second time, no response.

log file:
2017/05/05 02:25:15 coprocessor.go:319: [info] [TIME_COP_TASK] 2.4486359s region(2005 3 5) ranges(1) store(10.140.0.
7:20160)
2017/05/05 02:25:15 coprocessor.go:319: [info] [TIME_COP_TASK] 2.624122331s region(2013 3 7) ranges(1) store(10.140.
0.7:20160)
2017/05/05 02:25:15 pd.go:84: [warning] get timestamp too slow: 43.9626ms
2017/05/05 02:25:16 distsql.go:912: [info] [4] [TIME_TABLE_SCAN] time: 3.455802285s, table: customer2(33), partials:
 1, concurrency: 10, start_ts: 391630320455647233, rows: 527680
2017/05/05 02:25:16 pd.go:84: [warning] get timestamp too slow: 31.372619ms
2017/05/05 02:29:00 gc_worker.go:186: [info] [gc worker] 56f59240e480002 starts GC job, safePoint: 39163022302982963
2
2017/05/05 02:29:00 gc_worker.go:287: [info] [gc worker] 56f59240e480002 start resolve locks, safePoint: 39163022302
9829632.

still using 7 VMs (3 PDs, 3 TiKVs, 1 TiDB).
each VM 1 vCore CPU, 4G Ram, 32G SSD.
I hope these should satisfy the simple test, but still no response second times.

**Comment by DavisLinDB** [comment] 2017-05-08 03:28
explain the select statement:

MariaDB:
MariaDB [test]> explain select * from testdata join customer2 on testdata.id = customer2.cid limit 100;
+------+-------------+-----------+--------+---------------+---------+---------+--------------------+---------+------
-+
| id   | select_type | table     | type   | possible_keys | key     | key_len | ref                | rows    | Extra
 |
+------+-------------+-----------+--------+---------------+---------+---------+--------------------+---------+------
-+
|    1 | SIMPLE      | customer2 | ALL    | PRIMARY       | NULL    | NULL    | NULL               | 1311108 |      
 |
|    1 | SIMPLE      | testdata  | eq_ref | PRIMARY       | PRIMARY | 8       | test.customer2.cid |       1 |      
 |
+------+-------------+-----------+--------+---------------+---------+---------+--------------------+---------+------
-+

TiDB:
explain select * from teTidstdata join customer2 on testdata.id = customer2.cid limit 100;
+----------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------+
| ID             | Json                                                                                                                                                                                                                                                              | ParentID       |
+----------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------+
| TableScan_6    | {
    "db": "test",
    "table": "testdata",
    "desc": false,
    "keep order": false,
    "push down info": {
        "limit": 0,
        "access conditions": null,
        "index filter conditions": null,
        "table filter conditions": null
    }
}  | HashLeftJoin_8 |
| TableScan_7    | {
    "db": "test",
    "table": "customer2",
    "desc": false,
    "keep order": false,
    "push down info": {
        "limit": 0,
        "access conditions": null,
        "index filter conditions": null,
        "table filter conditions": null
    }
} | HashLeftJoin_8 |
| HashLeftJoin_8 | {
    "eqCond": [
        "eq(test.testdata.id, test.customer2.cid)"
    ],
    "leftCond": null,
    "rightCond": null,
    "otherCond": null,
    "leftPlan": "TableScan_6",
    "rightPlan": "TableScan_7"
}                                                   | Limit_9        |
| Limit_9        | {
    "limit": 100,
    "offset": 0,
    "child": "HashLeftJoin_8"
}                                                                                                                   
                                                                           |                |
+----------------+--------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------------------------
---------------------------------------------+----------------+
4 rows in set (0.00 sec)

**Comment by shenli** [comment] 2017-05-08 03:30
@DavisLinDB Thanks! We will look into this issue and keep you updated.

**Comment by DavisLinDB** [comment] 2017-05-08 03:31
select * from teTidstdata join customer2 on testdata.id = customer2.cid limit 100;
execution time:

MariaDB:
| 144 |    5 | 100.000000 | 200.000000 | 144 | d        | d         | d         | d         |
| 145 |    6 | 100.000000 | 200.000000 | 145 | d        | d         | d         | d         |
| 146 |    7 | 100.000000 | 200.000000 | 146 | e        | e         | e         | e         |
| 147 |    8 | 100.000000 | 200.000000 | 147 | aaa      | aaa       | aaa       | aaa       |
+-----+------+------------+------------+-----+----------+-----------+-----------+-----------+
100 rows in set (0.00 sec)

TiDB:
| 220 |   10 | 100.000000 | 200.000000 | 220 | e        | e         | e         | e         |
| 221 |    1 | 100.000000 | 200.000000 | 221 | aaa      | aaa       | aaa       | aaa       |
| 222 |    2 | 100.000000 | 200.000000 | 222 | b        | b         | b         | b         |
| 223 |    3 | 100.000000 | 200.000000 | 223 | d        | d         | d         | d         |
+-----+------+------------+------------+-----+----------+-----------+-----------+-----------+
100 rows in set (27.87 sec)

Why TiDB exection time so long?

**Comment by shenli** [comment] 2017-05-08 05:11
@DavisLinDB We have a few Join operators. The default one is HashJoin. But in this case, it seems that IndexLookupJoin is better. Try this:
select /*+ TIDB_INLJ(customer2) */ * from teTidstdata join customer2 on testdata.id = customer2.cid limit 100;
Please show the explain result and running time of this statement.
For more information about IndexLookupJoin, please check https://github.com/pingcap/docs-cn/blob/master/sql/tidb-specific.md#tidb_inljt1-t2

**Comment by DavisLinDB** [comment] 2017-05-08 05:33
executon time:
| 345 |    5 | 100.000000 | 200.000000 | 345 | e        | e         | e         | e         |
| 346 |    6 | 100.000000 | 200.000000 | 346 | aaa      | aaa       | aaa       | aaa       |
| 347 |    7 | 100.000000 | 200.000000 | 347 | b        | b         | b         | b         |
+-----+------+------------+------------+-----+----------+-----------+-----------+-----------+
100 rows in set (36.55 sec)

execution plan:
explain select /*+ TIDB_INLJ(customer2) */ * from testdata join customer2 on testdata.id = customer2.cid limit
 100;
+----------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------+
| ID             | Json                                                                                                                                                                                                                                                              | ParentID       |
+----------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------+
| TableScan_6    | {
    "db": "test",
    "table": "testdata",
    "desc": false,
    "keep order": false,
    "push down info": {
        "limit": 0,
        "access conditions": null,
        "index filter conditions": null,
        "table filter conditions": null
    }
}  | HashLeftJoin_8 |
| TableScan_7    | {
    "db": "test",
    "table": "customer2",
    "desc": false,
    "keep order": false,
    "push down info": {
        "limit": 0,
        "access conditions": null,
        "index filter conditions": null,
        "table filter conditions": null
    }
} | HashLeftJoin_8 |
| HashLeftJoin_8 | {
    "eqCond": [
        "eq(test.testdata.id, test.customer2.cid)"
    ],
    "leftCond": null,
    "rightCond": null,
    "otherCond": null,
    "leftPlan": "TableScan_6",
    "rightPlan": "TableScan_7"
}                                                   | Limit_9        |
| Limit_9        | {
    "limit": 100,
    "offset": 0,
    "child": "HashLeftJoin_8"
}                                                                                                                   
                                                                           |                |
+----------------+--------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------------------------
---------------------------------------------+----------------+

**Comment by shenli** [comment] 2017-05-08 05:39
@DavisLinDB Seems your tidb-sever do not support IndexLookupJoin operator. Please upgrade your tidb-server/pd-server/tikv-server to the latest version.
Just download the latest package, then replace the binaries and restart the service.

**Comment by DavisLinDB** [comment] 2017-05-08 05:41
@shenli

Does this docker image not latest?

docker pull pingcap/tidb:latest
docker run --name tidb-server -d -p 4000:4000 pingcap/tidb:latest

**Comment by shenli** [comment] 2017-05-08 05:42
Yes, but you also need to update pd and tikv.

**Comment by DavisLinDB** [comment] 2017-05-08 06:27
@shenli 

with /*+ TIDB_INLJ(customer2) */
| 465 |    5 | 100.000000 | 200.000000 | 465 | e        | e         | e         | e         |
| 466 |    6 | 100.000000 | 200.000000 | 466 | aaa      | aaa       | aaa       | aaa       |
| 467 |    7 | 100.000000 | 200.000000 | 467 | b        | b         | b         | b         |
+-----+------+------------+------------+-----+----------+-----------+-----------+-----------+
100 rows in set (6.29 sec)

without /*+ TIDB_INLJ(customer2) */
| 465 |    5 | 100.000000 | 200.000000 | 465 | e        | e         | e         | e         |
| 466 |    6 | 100.000000 | 200.000000 | 466 | aaa      | aaa       | aaa       | aaa       |
| 467 |    7 | 100.000000 | 200.000000 | 467 | b        | b         | b         | b         |
+-----+------+------------+------------+-----+----------+-----------+-----------+-----------+
100 rows in set (5.29 sec)

with /*+ TIDB_INLJ(customer2) */
explain select /*+ TIDB_INLJ(customer2) */ * from testdata join customer2 on testdata.id = customer2.c
id limit 100;
+----------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------+
| ID             | Json                                                                                                                                                                                                                                                              | ParentID       |
+----------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------+
| TableScan_6    | {
    "db": "test",
    "table": "testdata",
    "desc": false,
    "keep order": false,
    "push down info": {
        "limit": 0,
        "access conditions": null,
        "index filter conditions": null,
        "table filter conditions": null
    }
}  | HashLeftJoin_8 |
| TableScan_7    | {
    "db": "test",
    "table": "customer2",
    "desc": false,
    "keep order": false,
    "push down info": {
        "limit": 0,
        "access conditions": null,
        "index filter conditions": null,
        "table filter conditions": null
    }
} | HashLeftJoin_8 |
| HashLeftJoin_8 | {
    "eqCond": [
        "eq(test.testdata.id, test.customer2.cid)"
    ],
    "leftCond": null,
    "rightCond": null,
    "otherCond": null,
    "leftPlan": "TableScan_6",
    "rightPlan": "TableScan_7"
}                                                   | Limit_9        |
| Limit_9        | {
    "limit": 100,
    "offset": 0,
    "child": "HashLeftJoin_8"
}                                                                                                                   
                                                                           |                |
+----------------+--------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------------------------
---------------------------------------------+----------------+
4 rows in set (0.00 sec)

without /*+ TIDB_INLJ(customer2) */
explain select * from testdata join customer2 on testdata.id = customer2.cid limit 100;
+----------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------+
| ID             | Json                                                                                                                                                                                                                                                              | ParentID       |
+----------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------+
| TableScan_6    | {
    "db": "test",
    "table": "testdata",
    "desc": false,
    "keep order": false,
    "push down info": {
        "limit": 0,
        "access conditions": null,
        "index filter conditions": null,
        "table filter conditions": null
    }
}  | HashLeftJoin_8 |
| TableScan_7    | {
    "db": "test",
    "table": "customer2",
    "desc": false,
    "keep order": false,
    "push down info": {
        "limit": 0,
        "access conditions": null,
        "index filter conditions": null,
        "table filter conditions": null
    }
} | HashLeftJoin_8 |
| HashLeftJoin_8 | {
    "eqCond": [
        "eq(test.testdata.id, test.customer2.cid)"
    ],
    "leftCond": null,
    "rightCond": null,
    "otherCond": null,
    "leftPlan": "TableScan_6",
    "rightPlan": "TableScan_7"
}                                                   | Limit_9        |
| Limit_9        | {
    "limit": 100,
    "offset": 0,
    "child": "HashLeftJoin_8"
}                                                                                                                   
                                                                           |                |
+----------------+--------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------------------------
---------------------------------------------+----------------+
4 rows in set (0.01 sec)

I use 7 VMs group to test because I don't know how to update docker file.  Each VM is google compute engine's n1-standard-1 (1 vCPU, 3.75G Ram, 32G SSD).

I regot latest package tar.gz from here:
wget http://download.pingcap.org/tidb-latest-linux-amd64.tar.gz

Reinstall all PDs, TiDB, TiKVs.

TiDB version:
2017/05/08 05:51:39 printer.go:31: [info] Welcome to TiDB.
2017/05/08 05:51:39 printer.go:32: [info] Version:
2017/05/08 05:51:39 printer.go:33: [info] Git Commit Hash: 10fc9fcd442629105cbedc072358775fe55e96c9
2017/05/08 05:51:39 printer.go:34: [info] UTC Build Time:  2017-05-04 12:07:53

**Comment by shenli** [comment] 2017-05-08 06:33
@DavisLinDB Could you show me the result of `show create table customer2 ` and `show create table testdata`.
How many rows are there in testdata and customer2?

**Comment by DavisLinDB** [comment] 2017-05-08 06:43
@shenli 

According the url you give, I use --comments param.  It's better!!  But still not good as MariaDB.

|  98 |    8 | 100.000000 | 200.000000 |  98 | d        | d         | d         | d         |
|  99 |    9 | 100.000000 | 200.000000 |  99 | d        | d         | d         | d         |
| 100 |   10 | 100.000000 | 200.000000 | 100 | e        | e         | e         | e         |
+-----+------+------------+------------+-----+----------+-----------+-----------+-----------+
100 rows in set (1.22 sec)
MySQL [test]> explain select /*+ TIDB_INLJ(customer2) */ * from testdata join customer2 on testdata.id = customer2.c
id limit 100;
+-------------+-----------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------------------------
----------------------------------------------+-------------+
| ID          | Json                                                                                                
                                                                                                                    
                                              | ParentID    |
+-------------+-----------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------------------------
----------------------------------------------+-------------+
| TableScan_9 | {
    "db": "test",
    "table": "testdata",
    "desc": false,
    "keep order": false,
    "push down info": {
        "limit": 0,
    }
        "access conditions": null,
        "index filter conditions": null,
        "table filter conditions": null
    }
}      | Selection_8 |
| Selection_8 | {
    "condition": [
        "eq(test.testdata.id, test.customer2.cid)"
    ],
    "scanController": true,
    "child": "TableScan_9"
}                                                                                                                               | Apply_11    |
| TableScan_7 | {
    "db": "test",
    "table": "customer2",
    "desc": false,
    "keep order": false,
    "push down info": {
        "limit": 0,
        "access conditions": null,
        "index filter conditions": null,
        "table filter conditions": null
    }
}     | Apply_11    |
| Apply_11    | {
    "innerPlan": "Selection_8",
    "outerPlan": "TableScan_7",
    "join": {
        "eqCond": null,
        "leftCond": null,
        "rightCond": null,
        "otherCond": null,
        "leftPlan": "Selection_8",
        "rightPlan": "TableScan_7"
    }
} | Limit_12    |
| Limit_12    | {
    "limit": 100,
    "offset": 0,
    "child": "Apply_11"
}                                                                                                                                                                                                        |             |
+-------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------+
5 rows in set (0.00 sec)

the table counts:


MySQL [test]> select count(*) from testdata;
+----------+
| count(*) |
+----------+
|  1227680 |
+----------+
1 row in set (1.45 sec)
MySQL [test]> select count(*) from customer2;
+----------+
| count(*) |
+----------+
|  1127680 |
+----------+
1 row in set (0.91 sec)

**Comment by DavisLinDB** [comment] 2017-05-08 06:45
MySQL [test]> show create table customer2;
+-----------+-------------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------+
| Table     | Create Table                                                                                          
                                                                                                                    
                                                                                       |
+-----------+-------------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------+
| customer2 | CREATE TABLE `customer2` (
  `cid` bigint(21) NOT NULL AUTO_INCREMENT,
  `username` varchar(64) DEFAULT NULL,
  `username2` varchar(64) DEFAULT NULL,
  `username3` varchar(64) DEFAULT NULL,
  `username4` varchar(64) DEFAULT NULL,
 PRIMARY KEY (`cid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin |
+-----------+-------------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------+
1 row in set (0.00 sec)
MySQL [test]> show create table testdata;
+----------+--------------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------------------------
---------------------------------+
| Table    | Create Table                                                                                           
                                                                                                                    
                                 |
+----------+--------------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------------------------
---------------------------------+
| testdata | CREATE TABLE `testdata` (
  `bgold` decimal(18,6) DEFAULT NULL,
  `id` bigint(21) NOT NULL AUTO_INCREMENT,
  `cid` bigint(21) DEFAULT NULL,
  `agold` decimal(18,6) DEFAULT NULL,
  `bgold` decimal(18,6) DEFAULT NULL,
 PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin |
+----------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)

**Comment by shenli** [comment] 2017-05-08 07:11
@DavisLinDB I see. Please try: select /*+ TIDB_SMJ(testdata , customer2) */ * from testdata join customer2 on testdata.id = customer2.cid limit 100;
Please show me the explain result and running time.

**Comment by DavisLinDB** [comment] 2017-05-08 07:16
@shenli 

|  98 |    8 | 100.000000 | 200.000000 |  98 | d        | d         | d         | d         |
|  99 |    9 | 100.000000 | 200.000000 |  99 | d        | d         | d         | d         |
| 100 |   10 | 100.000000 | 200.000000 | 100 | e        | e         | e         | e         |
+-----+------+------------+------------+-----+----------+-----------+-----------+-----------+
100 rows in set (1.02 sec)
MySQL [test]> explain select /*+ TIDB_SMJ(testdata , customer2) */ * from testdata join customer2 on testdata.id = c
ustomer2.cid limit 100;
+--------------+----------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------------------------
------------------------------------------+-------------+
| ID           | Json                                                                                               
                                                                                                                    
                                          | ParentID    |
+--------------+----------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------------------------
------------------------------------------+-------------+
| TableScan_9  | {
    "db": "test",
    "table": "testdata",
    "desc": false,
    "keep order": true,
    "push down info": {
        "limit": 0,
        "access conditions": null,
        "index filter conditions": null,
        "table filter conditions": null
}                                                                                                                   
    }
}  | MergeJoin_6 |
| TableScan_12 | {
    "db": "test",
    "table": "customer2",
    "desc": false,
    "keep order": true,
    "push down info": {
        "limit": 0,
        "access conditions": null,
        "index filter conditions": null,
        "table filter conditions": null
    }
} | MergeJoin_6 |
| MergeJoin_6  | {
    "eqCond": [
        "eq(test.testdata.id, test.customer2.cid)"
    ],
    "leftCond": null,
    "rightCond": null,
    "otherCond": [],
    "leftPlan": "TableScan_9",
    "rightPlan": "TableScan_12",
    "desc": "false"
}                              | Limit_13    |
| Limit_13     | {
    "limit": 100,
    "offset": 0,
    "child": "MergeJoin_6"
}                                                                                                                                                                                                |             |
+--------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------+
4 rows in set (0.00 sec)

**Comment by DavisLinDB** [comment] 2017-05-08 07:22
execution time not stable.
same statement result from 0.99s~3.04s.

MySQL [test]> select /*+ TIDB_SMJ(testdata , customer2) */ * from testdata join customer2 on testdata.id = customer2
.cid limit 100,1;
+-----+------+------------+------------+-----+----------+-----------+-----------+-----------+
| id  | cid  | agold      | bgold      | cid | username | username2 | username3 | username4 |
+-----+------+------------+------------+-----+----------+-----------+-----------+-----------+
| 101 |    1 | 100.000000 | 200.000000 | 101 | aaa      | aaa       | aaa       | aaa       |
+-----+------+------------+------------+-----+----------+-----------+-----------+-----------+
1 row in set (0.99 sec)
MySQL [test]> select /*+ TIDB_SMJ(testdata , customer2) */ * from testdata join customer2 on testdata.id = customer2
.cid limit 100,1;
+-----+------+------------+------------+-----+----------+-----------+-----------+-----------+
| id  | cid  | agold      | bgold      | cid | username | username2 | username3 | username4 |
+-----+------+------------+------------+-----+----------+-----------+-----------+-----------+
| 101 |    1 | 100.000000 | 200.000000 | 101 | aaa      | aaa       | aaa       | aaa       |
+-----+------+------------+------------+-----+----------+-----------+-----------+-----------+
1 row in set (3.04 sec)
MySQL [test]> select /*+ TIDB_SMJ(testdata , customer2) */ * from testdata join customer2 on testdata.id = customer2
.cid limit 100,1;
+-----+------+------------+------------+-----+----------+-----------+-----------+-----------+
| id  | cid  | agold      | bgold      | cid | username | username2 | username3 | username4 |
+-----+------+------------+------------+-----+----------+-----------+-----------+-----------+
| 101 |    1 | 100.000000 | 200.000000 | 101 | aaa      | aaa       | aaa       | aaa       |
+-----+------+------------+------------+-----+----------+-----------+-----------+-----------+
1 row in set (2.87 sec)

=====================================================

INLJ() result:

MySQL [test]> select /*+ TIDB_INLJ(testdata , customer2) */ * from testdata join customer2 on testdata.id = customer
2.cid limit 100,1;
+-----+------+------------+------------+-----+----------+-----------+-----------+-----------+
| id  | cid  | agold      | bgold      | cid | username | username2 | username3 | username4 |
+-----+------+------------+------------+-----+----------+-----------+-----------+-----------+
| 101 |    1 | 100.000000 | 200.000000 | 101 | aaa      | aaa       | aaa       | aaa       |
+-----+------+------------+------------+-----+----------+-----------+-----------+-----------+
1 row in set (0.89 sec)
MySQL [test]> select /*+ TIDB_INLJ(testdata , customer2) */ * from testdata join customer2 on testdata.id = customer
2.cid limit 100,1;
+-----+------+------------+------------+-----+----------+-----------+-----------+-----------+
| id  | cid  | agold      | bgold      | cid | username | username2 | username3 | username4 |
+-----+------+------------+------------+-----+----------+-----------+-----------+-----------+
| 101 |    1 | 100.000000 | 200.000000 | 101 | aaa      | aaa       | aaa       | aaa       |
+-----+------+------------+------------+-----+----------+-----------+-----------+-----------+
1 row in set (1.52 sec)
MySQL [test]> select /*+ TIDB_INLJ(testdata , customer2) */ * from testdata join customer2 on testdata.id = customer
2.cid limit 100,1;
+-----+------+------------+------------+-----+----------+-----------+-----------+-----------+
| id  | cid  | agold      | bgold      | cid | username | username2 | username3 | username4 |
+-----+------+------------+------------+-----+----------+-----------+-----------+-----------+
| 101 |    1 | 100.000000 | 200.000000 | 101 | aaa      | aaa       | aaa       | aaa       |
+-----+------+------------+------------+-----+----------+-----------+-----------+-----------+
1 row in set (1.87 sec)

**Comment by ngaut** [comment] 2018-10-23 06:53
It should be very fast now, please feel free to reopen the issue.

**Closed by ngaut** 2018-10-23 06:53 UTC
