### ISSUE TITLE
goleak: goroutine in state sync.Cond.Wait, 5 minutes, with sync.runtime_notifyListWait on top of the stack

### ISSUE THREAD

**Issue by YangKeao** [pingcap/tidb#41777] opened 2023-02-28 07:03 UTC
A goroutine leak is found in test: https://do.pingcap.net/jenkins/blue/organizations/jenkins/pingcap%2Ftidb%2Fghpr_check2/detail/ghpr_check2/15046/pipeline

```
goleak: Errors on successful test run: found unexpected goroutines:

[Goroutine 454293 in state sync.Cond.Wait, 5 minutes, with sync.runtime_notifyListWait on top of the stack:

goroutine 454293 [sync.Cond.Wait, 5 minutes]:

sync.runtime_notifyListWait(0xc0105b5210, 0x0)

	GOROOT/src/runtime/sema.go:527 +0x14c

sync.(*Cond).Wait(0xc002341f70?)

	GOROOT/src/sync/cond.go:70 +0x8c

google.golang.org/grpc/internal/transport.(*http2Client).keepalive(0xc00c758b40)

	external/org_golang_google_grpc/internal/transport/http2_client.go:1693 +0x245

created by google.golang.org/grpc/internal/transport.newHTTP2Client

	external/org_golang_google_grpc/internal/transport/http2_client.go:386 +0x1dcc

]
```

**Comment by jackysp** [comment] 2023-10-14 22:16
It should also affect v6.5.

**Comment by tiancaiamao** [comment] 2024-01-12 07:23
This seems to be a grpc leak and the recent leak I known is this one https://github.com/pingcap/tidb/pull/48870
I'm not sure they are related.

Can't reproduce and from the above information provided, I have no idea how to debug this issue.
So close it.

**Closed by tiancaiamao** 2024-01-12 07:23 UTC
Labels: type/bug, component/test, sig/sql-infra, severity/major, affects-6.5, affects-7.0, affects-7.1, affects-7.5
