### ISSUE TITLE
execute 'use DB' with 145K tables in it cause mysql client hang 

### ISSUE THREAD

**Issue by tiancaiamao** [pingcap/tidb#49272] opened 2023-12-08 04:05 UTC
## Enhancement

```
mysql> use test;
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A
```

**Comment by lance6716** [comment] 2023-12-11 09:43
> You can turn off this feature to get a quicker startup with -A

Seems it's caused by MySQL client prefetching all table structures under the DB?

**Comment by dveeden** [comment] 2024-03-18 07:18
Would be useful to have a network packet trace (without TLS) to see what really happens.

**Comment by bb7133** [comment] 2024-04-09 18:34
> ＠bb7133 Do you know the protocol detail behand this？

Yes, this is expected for 'interactive client' of MySQL, by default `use $DATABASE` sends `COM_FIELD_LIST` for each table of a database, which might be very slow when you have a lot of tables.

This is an expected behavior of MySQL protocol IMO, and it will not be a problem for 'non-interactive clients' like connectors, so I think we can close this issue.

**Closed by bb7133** 2024-04-09 18:34 UTC
Labels: type/enhancement, component/mysql-protocol
