### ISSUE TITLE
slow query in dashboard show a lot of ';'

### ISSUE THREAD

**Issue by xiongjiwei** [pingcap/tidb#54190] opened 2024-06-25 03:15 UTC
## Bug Report

Please answer these questions before submitting your issue. Thanks!

<img width="1058" alt="image" src="https://github.com/pingcap/tidb/assets/20839912/c913f60f-ec71-4e39-bfc9-e8934477d75a">

use tiup deploy a v8.1 cluster and do nothing

**Comment by jebter** [comment] 2024-06-25 06:58
duplicate of https://github.com/pingcap/tidb/issues/52743

**Closed** 2024-06-28 07:34 UTC
Labels: type/bug, sig/sql-infra, severity/major, affects-8.1
