### ISSUE TITLE
parser: STRAIGHT_JOIN and SQL_SMALL_RESULT cannot be used at the same time

### ISSUE THREAD

**Issue by fzhedu** [pingcap/tidb#13750] opened 2019-11-26 10:29 UTC
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
```
create table t;
insert into t values(1);
```
2. What did you expect to see?
Results from Mysql:
```
mysql> select STRAIGHT_JOIN SQL_SMALL_RESULT count(*) from t;
+----------+
| count(*) |
+----------+
|        1 |
+----------+
1 row in set (0.00 sec)
```

3. What did you see instead?
Results: from TiDB:
```
select STRAIGHT_JOIN SQL_SMALL_RESULT count(*) from t;
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your TiDB version for the right syntax to use line 1 column 37 near "SQL_SMALL_RESULT count(*) from t" 
```

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
[tidb@VM2 bin]$ ./tidb-server -V
2019-11-26 18:27:18.059136 I | maxprocs: Leaving GOMAXPROCS=8: CPU quota undefined
Release Version: 
Git Commit Hash: 
Git Branch: 
UTC Build Time: 2019-11-22 02:54:53
GoVersion: go version go1.13.3 linux/amd64
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false

**Comment by nullnotnil** [comment] 2020-07-16 15:40
Verified against master as described:
```sql
drop table if exists t;
create table t (a int);
insert into t values(1);
select STRAIGHT_JOIN SQL_SMALL_RESULT count(*) from t;

..

mysql> select STRAIGHT_JOIN SQL_SMALL_RESULT count(*) from t;
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your TiDB version for the right syntax to use line 1 column 37 near "SQL_SMALL_RESULT count(*) from t" 
mysql> select tidb_version()\G
*************************** 1. row ***************************
tidb_version(): Release Version: v4.0.0-beta.2-771-gca41972fb
Edition: Community
Git Commit Hash: ca41972fbac068c8a5de107d9075f09ac68842ac
Git Branch: master
UTC Build Time: 2020-07-14 02:41:21
GoVersion: go1.13
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
1 row in set (0.00 sec)
```

**Comment by morgo** [comment] 2020-12-03 22:43
This is actually a duplicate of https://github.com/pingcap/tidb/issues/20133 - the options in TiDB have a specific order requirement, but MySQL does not. See the following testcase:

```sql
drop table if exists t;
create table t (a int);
insert into t values(1);
select STRAIGHT_JOIN SQL_SMALL_RESULT count(*) from t;
select SQL_SMALL_RESULT STRAIGHT_JOIN count(*) from t;

..

mysql> select STRAIGHT_JOIN SQL_SMALL_RESULT count(*) from t;
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your TiDB version for the right syntax to use line 1 column 37 near "SQL_SMALL_RESULT count(*) from t" 
mysql> select SQL_SMALL_RESULT STRAIGHT_JOIN count(*) from t;
+----------+
| count(*) |
+----------+
|        1 |
+----------+
1 row in set (0.01 sec)

mysql> SELECT tidb_version()\G
*************************** 1. row ***************************
tidb_version(): Release Version: v4.0.0-beta.2-1689-g2f33d57db
Edition: Community
Git Commit Hash: 2f33d57db1e72d03929b76b9481ddf31aed3d762
Git Branch: master
UTC Build Time: 2020-12-01 13:11:19
GoVersion: go1.13
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
1 row in set (0.00 sec)
```

**Closed** 2020-12-07 17:41 UTC
Labels: component/parser, severity/moderate, type/bug, type/compatibility, type/duplicate
