### ISSUE TITLE
DB::TiFlashException: EQJson is not supported.

### ISSUE THREAD

**Issue by apollodafoni** [pingcap/tidb#56282] opened 2024-09-25 03:41 UTC
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
set tidb_cost_model_version=1;
set tidb_enforce_mpp=1;
create table t(a int, b json);
alter table t set tiflash replica 1;
insert into t values (10, '{"test":8.437e-5}');
insert into t values (10, '{"name":"value"}'), (11, '{\"asdf\":true}'), (13, '{\"input1\":\"\\u00f6\"}');
select JSON_EXTRACT(b, '$.name') = 'value' from t where a = 10;
```

### 2. What did you expect to see? (Required)
JSON_EXTRACT(b, '$.name') = 'value'
NULL
1
### 3. What did you see instead (Required)
ERROR 1105 (HY000): other error for mpp stream: Code: 0, e.displayText() = DB::TiFlashException: EQJson is not supported., e.what() = DB::TiFlashException,
### 4. What is your TiDB version? (Required)

Release Version: v8.4.0-alpha
Edition: Community
Git Commit Hash: d99d4451bc6852e07329157ef96600a182325741
Git Branch: heads/refs/tags/v8.4.0-alpha
UTC Build Time: 2024-09-19 10:28:59
GoVersion: go1.23.1
Race Enabled: false
Check Table Before Drop: false
Store: tikv

**Comment by windtalker** [comment] 2024-09-26 02:15
TiDB disable pushdown EQJson in ff1f8621178f2017cbf34b7e4b19870dbdbdb826, this issue is caused by mismatched versions of TiDB and TiFlash. Close it as not a bug

**Closed by windtalker** 2024-09-26 02:15 UTC
Labels: type/bug, severity/major, component/tiflash, may-affects-5.4, may-affects-6.1, may-affects-6.5, may-affects-7.1, may-affects-7.5, may-affects-8.1
