### ISSUE TITLE
Change table schema end up inconsistency

### ISSUE THREAD

**Issue by xbddc** [pingcap/tidb#11656] opened 2019-08-07 06:26 UTC
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

I ran a `ALTER TABLE` query to modify table schema, but only one of the TiDB services returns correct table schema after this mutation, the other TiDBs remain unchanged.

```
`ALTER TABLE `test` ADD `aaa` INT  NULL  DEFAULT NULL  AFTER `id`;`
`ALTER TABLE `test` ADD `ccc` INT  NULL  DEFAULT NULL  AFTER `aaa`;`
```

2. What did you expect to see?

`SELECT @@global.hostname; USE test; SHOW CREATE TABLE test`

```
@@global.hostname
tidb1
Table   Create Table
test    CREATE TABLE `test` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `aaa` int(11) DEFAULT NULL,
  `ccc` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin
```

```
@@global.hostname
tidb2
Table   Create Table
test    CREATE TABLE `test` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `aaa` int(11) DEFAULT NULL,
  `ccc` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin
```

```
@@global.hostname
tidb3
Table   Create Table
test    CREATE TABLE `test` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `aaa` int(11) DEFAULT NULL,
  `ccc` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin
```

3. What did you see instead?

`SELECT @@global.hostname; USE test; SHOW CREATE TABLE test`

```
@@global.hostname
tidb1
Table   Create Table
test    CREATE TABLE `test` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin
```

```
@@global.hostname
tidb2
Table   Create Table
test    CREATE TABLE `test` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `aaa` int(11) DEFAULT NULL,
  `ccc` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin
```

```
@@global.hostname
tidb3
Table   Create Table
test    CREATE TABLE `test` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin
```

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

```
Release Version: v3.0.2
Git Commit Hash: 94498e7d06a244196bb41c3a05dd4c1f6903099a
Git Branch: HEAD
UTC Build Time: 2019-08-07 02:35:52
GoVersion: go version go1.12 linux/amd64
Race Enabled: false
TiKV Min Version: 2.1.0-alpha.1-ff3dd160846b7d1aed9079c389fc188f7f5ea13e
Check Table Before Drop: false
```

**Comment by zimulala** [comment] 2019-08-08 09:26
@xbddc Thanks for your feedback!
Did you execute "SHOW CREATE TABLE test" after the two "alter table"s were executed successfully?

**Comment by xbddc** [comment] 2019-08-08 10:44
Yes, the instance I connected to shows correct table schema (as `tidb2` in section 3 above)

**Comment by zimulala** [comment] 2019-08-08 11:51
@xbddc 
How long has this been maintained? Could this scene be reproduced? If it can be reproduced, please describe the steps to me.

**Comment by xbddc** [comment] 2019-08-08 12:37
1. Append another TiDB service in `docker-compse.yml` and launch it

```
$ git clone https://github.com/pingcap/tidb-docker-compose
$ cd tidb-docker-compose && cat >> docker-compose.yml << EOF
  tidb2:
    image: pingcap/tidb:latest
    ports:
      - "4001:4000"
      - "10081:10080"
    volumes:
      - ./config/tidb.toml:/tidb.toml:ro
      - ./logs:/logs
    command:
      - --store=tikv
      - --path=pd0:2379,pd1:2379,pd2:2379
      - --config=/tidb.toml
      - --log-file=/logs/tidb.log
    depends_on:
      - "tikv0"
      - "tikv1"
      - "tikv2"
    restart: on-failure
EOF

$ docker-compose up
``` 

2. Create test table

```
mysql -h localhost -P 4000 -e "CREATE TABLE test.test (
  id int(11) unsigned NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin"
```

3. Query two TiDBs respectively

```
mysql -h localhost -P 4000 -e "SHOW CREATE TABLE test.test"
```

```
mysql -h localhost -P 4001 -e "SHOW CREATE TABLE test.test"
```

One of them will return `ERROR 1146 (42S02) at line 1: Table 'test.test' doesn't exist` but we just created at step 2.

**Comment by zimulala** [comment] 2019-08-09 09:54
@xbddc 

> One of them will return ERROR 1146 (42S02) at line 1: Table 'test.test' doesn't exist but we just created at step 2.

Could you reproduce it? If you can, please show the result of "admin show ddl jobs"

**Comment by xbddc** [comment] 2019-08-12 03:21
The second one (port 4001) return the error, and no any new message appeared in `logs/` and `docker-compose`'s output during this query, couldn't you reproduce at your box?

**Comment by xbddc** [comment] 2019-09-04 06:47
@zimulala 
Any updates?

**Comment by zimulala** [comment] 2024-03-22 09:52
I am very sorry that I did not reproduce this problem before and did not reply in time. Since it was a long time ago, I will close this question first and raise the issue again if you encounter any related problems.

**Closed by zimulala** 2024-03-22 09:52 UTC
Labels: type/question
