### ISSUE TITLE
DATA RACE in testInfoschemaTableSuite.TestPartitionsTable

### ISSUE THREAD

**Issue by tiancaiamao** [pingcap/tidb#15252] opened 2020-03-10 05:02 UTC
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?

Find in https://github.com/pingcap/tidb/pull/15227

2. What did you expect to see?

FAIL: infoschema_reader_test.go:266: testInfoschemaTableSuite.TestPartitionsTable

3. What did you see instead?

```
[2020-03-10T03:44:10.568Z] WARNING: DATA RACE
[2020-03-10T03:44:10.568Z] Write at 0x0000056736a0 by goroutine 400:
[2020-03-10T03:44:10.568Z]   github.com/pingcap/tidb/executor_test.(*testInfoschemaTableSuite).TestPartitionsTable()
[2020-03-10T03:44:10.568Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/infoschema_reader_test.go:269 +0x8d
[2020-03-10T03:44:10.568Z]   runtime.call32()
[2020-03-10T03:44:10.568Z]       /usr/local/go/src/runtime/asm_amd64.s:539 +0x3a
[2020-03-10T03:44:10.568Z]   reflect.Value.Call()
[2020-03-10T03:44:10.568Z]       /usr/local/go/src/reflect/value.go:321 +0xd3
[2020-03-10T03:44:10.568Z]   github.com/pingcap/check.(*suiteRunner).forkTest.func1()
[2020-03-10T03:44:10.568Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:850 +0x9aa
[2020-03-10T03:44:10.568Z]   github.com/pingcap/check.(*suiteRunner).forkCall.func1()
[2020-03-10T03:44:10.568Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:739 +0x113
[2020-03-10T03:44:10.568Z] 
[2020-03-10T03:44:10.568Z] Previous read at 0x0000056736a0 by goroutine 316:
[2020-03-10T03:44:10.568Z]   [failed to restore the stack]
[2020-03-10T03:44:10.568Z] 
[2020-03-10T03:44:10.568Z] Goroutine 400 (running) created at:
[2020-03-10T03:44:10.568Z]   github.com/pingcap/check.(*suiteRunner).forkCall()
[2020-03-10T03:44:10.568Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:734 +0x4a3
[2020-03-10T03:44:10.568Z]   github.com/pingcap/check.(*suiteRunner).forkTest()
[2020-03-10T03:44:10.568Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:832 +0x1b9
[2020-03-10T03:44:10.568Z]   github.com/pingcap/check.(*suiteRunner).doRun()
[2020-03-10T03:44:10.568Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:666 +0x13a
[2020-03-10T03:44:10.568Z]   github.com/pingcap/check.(*suiteRunner).asyncRun.func1()
[2020-03-10T03:44:10.568Z]       /home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:650 +0xf7
```

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

**Comment by SunRunAway** [comment] 2020-03-10 11:20
Duplicate of #15226

**Closed by SunRunAway** 2020-03-10 11:20 UTC
Labels: component/test, type/bug
