### ISSUE TITLE
v4.0.12, transaction will be executed as 'pessimistic' mode even though specified as optimistic mode in "begin", when autocommit=0

### ISSUE THREAD

**Issue by seiya-annie** [pingcap/tidb#49580] opened 2023-12-19 06:41 UTC
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

create table t (id int key);
set @@tidb_disable_txn_auto_retry=0;
set autocommit=0;
begin optimistic;
insert into t values (1);
insert into t values (2);
select * from t for update;
insert into t values (3);
insert into t values (4);
commit;
select * from t;

### 2. What did you expect to see? (Required)
mysql> select * from t for update;
ERROR 1105 (HY000): statement count 4 exceeds the transaction limitation, transaction has been rollback, autocommit = true

### 3. What did you see instead (Required)
mysql> select * from t for update;
+----+
| id |
+----+
|  1 |
|  2 |
+----+
2 rows in set (0.00 sec)

transaction will be executed as 'pessimistic' mode even though specified as optimistic mode in "begin", when autocommit=0;
### 4. What is your TiDB version? (Required)

v4.0.12

**Comment by crazycs520** [comment] 2023-12-20 09:55
This is not a bug. It doesn't have any effect.

**Comment by crazycs520** [comment] 2023-12-20 09:58
```sql
set autocommit=0;
begin optimistic;
```

The issue is after `set autocommit=0`, use `begin optimistic` to start a new transaction is still a pessimistic txn, not optimistic txn.

**Comment by jebter** [comment] 2024-09-04 03:40
The issue has not been updated for too long, so I will close it，if there are any updates, you can reopen it.

**Closed by jebter** 2024-09-04 03:40 UTC
Labels: type/question, sig/transaction
