### ISSUE TITLE
planner, executor: Correlated subqueries error when using indexing columns

### ISSUE THREAD

**Issue by fzhedu** [pingcap/tidb#13758] opened 2019-11-26 13:54 UTC
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
```
CREATE TABLE `table30_int_autoinc` (
  `col_int` int(11) DEFAULT NULL,
  `col_varchar_binary_not_null` varbinary(1) NOT NULL,
  `col_int_key` int(11) DEFAULT NULL,
  `col_int_not_null` int(11) NOT NULL,
  `pk` int(11) NOT NULL AUTO_INCREMENT,
  `col_int_not_null_key` int(11) NOT NULL,
  `col_varchar_binary` varbinary(1) DEFAULT NULL,
  `col_varchar_binary_key` varbinary(1) DEFAULT NULL,
  `col_varchar_binary_not_null_key` varbinary(1) NOT NULL,
  PRIMARY KEY (`pk`),
  KEY `col_int_key` (`col_int_key`),
  KEY `col_int_not_null_key` (`col_int_not_null_key`),
  KEY `col_varchar_binary_key` (`col_varchar_binary_key`),
  KEY `col_varchar_binary_not_null_key` (`col_varchar_binary_not_null_key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin AUTO_INCREMENT=2000001;

INSERT INTO `table30_int_autoinc` VALUES (NULL,_binary 'y',-956825600,2076311552,1,1141047296,_binary 't',_binary 'h',_binary 'w');
INSERT INTO `table30_int_autoinc` VALUES (NULL,_binary 'x',0,2,2,1,_binary 'f',_binary 's',_binary 'a');
INSERT INTO `table30_int_autoinc` VALUES (3,_binary 'j',6,1969029120,3,7,_binary 's',_binary 'i',_binary 'y');
INSERT INTO `table30_int_autoinc` VALUES (6,_binary 'n',NULL,8,4,2,_binary 'e',_binary 'w',_binary 'g');
INSERT INTO `table30_int_autoinc` VALUES (2,_binary 't',NULL,-1457782784,5,1,_binary 's',_binary 'I',_binary 't');
INSERT INTO `table30_int_autoinc` VALUES (8,_binary 'a',NULL,757137408,6,9,_binary 'm',_binary 'h',_binary 't');
INSERT INTO `table30_int_autoinc` VALUES (-1465647104,_binary 's',NULL,1,7,6,_binary 'w',_binary 't',_binary 'z');
INSERT INTO `table30_int_autoinc` VALUES (0,_binary 'f',2053308416,-291241984,8,4,_binary 'k',_binary 'y',_binary 'b');
INSERT INTO `table30_int_autoinc` VALUES (-1808990208,_binary 'a',NULL,489684992,9,-97648640,_binary 'u',_binary 'm',_binary 'h');
INSERT INTO `table30_int_autoinc` VALUES (-656408576,_binary 'w',-231342080,6,10,220332032,_binary 'l',_binary 'g',_binary 'm');
INSERT INTO `table30_int_autoinc` VALUES (6,_binary 'd',2,3,11,6,_binary 'l',_binary 'd',_binary 'a');
INSERT INTO `table30_int_autoinc` VALUES (630063104,_binary 'a',NULL,-104660992,12,494862336,_binary 'n',_binary 'o',_binary 'r');
INSERT INTO `table30_int_autoinc` VALUES (406978560,_binary 'z',818216960,-1689255936,13,1,_binary 'o',_binary 'e',_binary 'u');
INSERT INTO `table30_int_autoinc` VALUES (-514719744,_binary 'h',109838336,83951616,14,1,_binary 'n',_binary 'h',_binary 'n');
INSERT INTO `table30_int_autoinc` VALUES (1240924160,_binary 'g',1290993664,618987520,15,-853213184,_binary 'w',_binary 'l',_binary 'h');
INSERT INTO `table30_int_autoinc` VALUES (-609353728,_binary 'u',NULL,1388773376,16,-2036006912,_binary 'w',_binary 'i',_binary 's');
INSERT INTO `table30_int_autoinc` VALUES (0,_binary 'i',-1195769856,1591934976,17,3,_binary 'd',_binary 'z',_binary 'y');
INSERT INTO `table30_int_autoinc` VALUES (NULL,_binary 'x',NULL,425197568,18,1,_binary 'l',_binary 'o',_binary 't');
INSERT INTO `table30_int_autoinc` VALUES (NULL,_binary 'p',4,1967128576,19,1956773888,_binary 's',_binary 'w',_binary 'r');
INSERT INTO `table30_int_autoinc` VALUES (-2032271360,_binary 'a',8,8,20,648609792,_binary 'c',_binary 'w',_binary 'c');
INSERT INTO `table30_int_autoinc` VALUES (1962606592,_binary 'v',NULL,8,21,1654784000,_binary 'w',_binary 'a',_binary 'e');

create table s (a int);
insert into s values(1),(null;
```
2. What did you expect to see?
```
mysql> SELECT (SELECT MIN(col_int_not_null_key ) FROM table30_int_autoinc  WHERE col_int_key >= s.a ) AS field FROM s ;
+------------+
| field      |
+------------+
| -853213184 |
|       NULL |
+------------+
2 rows in set (0.00 sec)
```

3. What did you see instead?
```
mysql> analyze table table30_int_autoinc;
Query OK, 0 rows affected (0.20 sec)

mysql> SELECT (SELECT MIN(col_int_not_null_key ) FROM table30_int_autoinc  WHERE col_int_key >= s.a ) AS field FROM s ;
+------------+
| field      |
+------------+
| -853213184 |
|          1 |
+------------+
2 rows in set (0.00 sec)
```
4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
 5.7.25-TiDB-v4.0.0-alpha-959-gaf2a2c532

**Comment by nullnotnil** [comment] 2020-07-18 02:46
I can confirm this exists in master. I've been able to simplify the test a little:
```sql
DROP TABLE IF EXISTS t1, t2;
CREATE TABLE t1 (
  `pk` int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `col_int_not_null_key` int(11) NOT NULL,
  `col_int_key` int(11) DEFAULT NULL,
  KEY `col_int_key` (`col_int_key`),
  KEY `col_int_not_null_key` (`col_int_not_null_key`)
);

INSERT INTO `t1` VALUES (1,1141047296,-956825600),(2,1,0),(3,7,6),(4,2,NULL),(5,1,NULL),(6,9,NULL),(7,6,NULL),(8,4,2053308416),(9,-97648640,NULL);

CREATE TABLE t2 (a INT);
INSERT INTO t2 VALUES (1), (NULL);

SELECT (SELECT MIN(col_int_not_null_key) FROM t1 WHERE col_int_key >= t2.a ) AS field FROM t2;
SELECT MIN(col_int_not_null_key) FROM t1 WHERE col_int_key >= NULL;

..

mysql> SELECT (SELECT MIN(col_int_not_null_key) FROM t1 WHERE col_int_key >= t2.a ) AS field FROM t2;
+-------+
| field |
+-------+
|     4 |
|     7 |
+-------+
2 rows in set (0.01 sec)

mysql> SELECT MIN(col_int_not_null_key) FROM t1 WHERE col_int_key >= NULL;
+---------------------------+
| MIN(col_int_not_null_key) |
+---------------------------+
|                      NULL |
+---------------------------+
1 row in set (0.00 sec)

mysql> 
mysql> SELECT tidb_version()\G
*************************** 1. row ***************************
tidb_version(): Release Version: v4.0.0-beta.2-782-gb72e47e6d
Edition: Community
Git Commit Hash: b72e47e6db8863c08e47714391cf937b0f1c3269
Git Branch: master
UTC Build Time: 2020-07-15 01:26:06
GoVersion: go1.13
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
1 row in set (0.01 sec)

```

**Comment by qw4990** [comment] 2020-07-30 03:12
@rebelice and I will fix this soon.

**Comment by nullnotnil** [comment] 2020-08-03 21:48
There is another issue with nullability correctness in https://github.com/pingcap/tidb/issues/3773

I don't want to assume they are the same issue, but it would be great to get both addressed. Thanks!

**Comment by SunRunAway** [comment] 2020-08-11 04:09
> There is another issue with nullability correctness in #3773
> 
> I don't want to assume they are the same issue, but it would be great to get both addressed. Thanks!

@fzhedu Would you like to take a look?

**Comment by eurekaka** [comment] 2020-08-27 11:33
A minimal reproduction step:

```sql
DROP TABLE IF EXISTS t1, t2;
CREATE TABLE t1 (
  `pk` int(11) PRIMARY KEY,
  `a` int(11) NOT NULL,
  `b` int(11),
  KEY `idx_b` (`b`),
  KEY `idx_a` (`a`)
);

INSERT INTO `t1` VALUES (1,1,0),(2,7,6),(3,2,NULL),(4,1,NULL),(5,4,5);

CREATE TABLE t2 (a INT);
INSERT INTO t2 VALUES (1),(NULL);

SELECT (SELECT a FROM t1 use index(idx_a) WHERE b >= t2.a order by a limit 1) AS field FROM t2;
```

Note that, if we directly use `SELECT (SELECT a FROM t1 WHERE b >= t2.a order by a limit 1) AS field FROM t2;`, it would produce wrong result firstly, after several seconds, it would produce correct results. The reason is that the plan is `IndexLookUp` instead of `TableScan` for the first several executions, and after the stats delta has been dumped, the plan is changed to `TableScan`, and the wrong result only occurs for the `IndexLookUp` plan. We add a SQL hint to force using `IndexLookUp` for stable reproduction.

The root cause of this issue is same as https://github.com/pingcap/tidb/issues/19372, and it can be fixed by https://github.com/pingcap/tidb/pull/19496 as well.

**Closed by eurekaka** 2020-08-27 11:33 UTC
Labels: Priority/P1, correctness, severity/critical, sig/execution, sig/planner, type/bug
