### ISSUE TITLE
executor test fail in ci

### ISSUE THREAD

**Issue by cfzjywxk** [pingcap/tidb#18198] opened 2020-06-24 06:48 UTC
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 2. What did you expect to see? (Required)

All tests passed

### 3. What did you see instead (Required)

Seems something wrong in `MockRegionManager` in `unistore`

```
[2020-06-24T04:31:49.922Z] 
[2020-06-24T04:31:49.922Z] goroutine 96144 [running]:
[2020-06-24T04:31:49.922Z] github.com/pingcap/badger.(*DB).sendToWriteCh(0xc06edfd200, 0xc076685bc0, 0x3, 0x3, 0x1, 0x8, 0x9)
[2020-06-24T04:31:49.922Z] 	/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/pkg/mod/github.com/pingcap/badger@v1.5.1-0.20200604041313-19c397305fcc/db.go:764 +0xe3
[2020-06-24T04:31:49.922Z] github.com/pingcap/badger.(*Txn).Commit(0xc07667f050, 0x0, 0x0)
[2020-06-24T04:31:49.922Z] 	/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/pkg/mod/github.com/pingcap/badger@v1.5.1-0.20200604041313-19c397305fcc/transaction.go:502 +0x542
[2020-06-24T04:31:49.922Z] github.com/pingcap/badger.(*DB).Update(0xc06edfd200, 0xc0766b5c30, 0x0, 0x0)
[2020-06-24T04:31:49.922Z] 	/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/pkg/mod/github.com/pingcap/badger@v1.5.1-0.20200604041313-19c397305fcc/transaction.go:587 +0xbe
[2020-06-24T04:31:49.922Z] github.com/ngaut/unistore/tikv.(*MockRegionManager).saveRegions(0xc06f1135e0, 0xc076513f40, 0x2, 0x2, 0xc07654da40, 0x0)
[2020-06-24T04:31:49.922Z] 	/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/pkg/mod/github.com/ngaut/unistore@v0.0.0-20200604061006-d8e9dc0ad154/tikv/mock_region.go:458 +0x9f
[2020-06-24T04:31:49.922Z] github.com/ngaut/unistore/tikv.(*MockRegionManager).splitKeys(0xc06f1135e0, 0xc076685b80, 0x0, 0x0, 0x9, 0x9, 0xc0993fe240, 0x12, 0x12)
[2020-06-24T04:31:49.922Z] 	/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/pkg/mod/github.com/ngaut/unistore@v0.0.0-20200604061006-d8e9dc0ad154/tikv/mock_region.go:401 +0x339
[2020-06-24T04:31:49.922Z] github.com/ngaut/unistore/tikv.(*MockRegionManager).SplitRegion(0xc06f1135e0, 0xc076598120, 0x0)
[2020-06-24T04:31:49.922Z] 	/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/pkg/mod/github.com/ngaut/unistore@v0.0.0-20200604061006-d8e9dc0ad154/tikv/mock_region.go:290 +0x25d
[2020-06-24T04:31:49.922Z] github.com/ngaut/unistore/tikv.(*Server).SplitRegion(...)
[2020-06-24T04:31:49.922Z] 	/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/pkg/mod/github.com/ngaut/unistore@v0.0.0-20200604061006-d8e9dc0ad154/tikv/server.go:500
[2020-06-24T04:31:49.922Z] github.com/pingcap/tidb/store/mockstore/unistore.(*RPCClient).SendRequest(0xc067585340, 0x3d89da0, 0xc076686a80, 0xc068f198c0, 0x6, 0xc07667af20, 0x4a817c800, 0x4a817c800, 0x0, 0x0)
[2020-06-24T04:31:49.922Z] 	/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/store/mockstore/unistore/rpc.go:169 +0x1941
[2020-06-24T04:31:49.922Z] github.com/pingcap/tidb/store/tikv.reqCollapse.SendRequest(0x3d54760, 0xc067585340, 0x3d89da0, 0xc076686a80, 0xc068f198c0, 0x6, 0xc07667af20, 0x4a817c800, 0x0, 0x0, ...)
[2020-06-24T04:31:49.922Z] 	/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/store/tikv/client_collapse.go:49 +0x12a
[2020-06-24T04:31:49.922Z] github.com/pingcap/tidb/store/tikv.(*RegionRequestSender).sendReqToRegion(0xc0766b6798, 0xc07667d180, 0xc07669c370, 0xc07667af20, 0x4a817c800, 0x0, 0x0, 0x0, 0x0)
[2020-06-24T04:31:49.922Z] 	/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/store/tikv/region_request.go:253 +0x103
[2020-06-24T04:31:49.922Z] github.com/pingcap/tidb/store/tikv.(*RegionRequestSender).SendReqCtx(0xc0766b6798, 0xc07667d180, 0xc07667af20, 0x50, 0x1, 0x1, 0x4a817c800, 0xc07668f300, 0x39, 0x325e6a0, ...)
[2020-06-24T04:31:49.923Z] 	/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/store/tikv/region_request.go:216 +0x386
[2020-06-24T04:31:49.923Z] github.com/pingcap/tidb/store/tikv.(*RegionRequestSender).SendReq(...)
[2020-06-24T04:31:49.923Z] /home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/store/tikv/region_request.go:126
[2020-06-24T04:31:49.923Z] github.com/pingcap/tidb/store/tikv.(*tikvStore).batchSendSingleRegion(0xc07aab8e00, 0xc07667d180, 0x50, 0x1, 0x1, 0xc076685a20, 0x1, 0x1, 0x0, 0x0, ...)
[2020-06-24T04:31:49.923Z] 	/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/store/tikv/split_region.go:122 +0x2aa
[2020-06-24T04:31:49.923Z] github.com/pingcap/tidb/store/tikv.(*tikvStore).splitBatchRegionsReq(0xc07aab8e00, 0xc07667d180, 0xc0766856e0, 0x1, 0x1, 0x0, 0x0, 0xc07668f000, 0xc076513e20)
[2020-06-24T04:31:49.923Z] 	/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/store/tikv/split_region.go:63 +0xebf
[2020-06-24T04:31:49.923Z] github.com/pingcap/tidb/store/tikv.(*tikvStore).batchSendSingleRegion(0xc07aab8e00, 0xc07667d180, 0x4e, 0x1, 0x1, 0xc0766856e0, 0x1, 0x1, 0x0, 0x0, ...)
[2020-06-24T04:31:49.923Z] 	/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/store/tikv/split_region.go:140 +0x173b
[2020-06-24T04:31:49.923Z] github.com/pingcap/tidb/store/tikv.(*tikvStore).splitBatchRegionsReq(0xc07aab8e00, 0xc07667d180, 0xc076685680, 0x1, 0x1, 0x203000, 0x3496440, 0xc000054001, 0x203017)
[2020-06-24T04:31:49.923Z] 	/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/store/tikv/split_region.go:63 +0xebf
[2020-06-24T04:31:49.923Z] github.com/pingcap/tidb/store/tikv.(*tikvStore).SplitRegions(0xc07aab8e00, 0x3d89da0, 0xc076686a80, 0xc076685680, 0x1, 0x1, 0xc00418b500, 0xc00418b6a0, 0x13853d4, 0xc076686a90, ...)
[2020-06-24T04:31:49.923Z] 	/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/store/tikv/split_region.go:198 +0x11b
[2020-06-24T04:31:49.923Z] github.com/pingcap/tidb/ddl.splitRecordRegion(0x3d89da0, 0xc076686a80, 0x7f8b9c15b680, 0xc07aab8e00, 0x65, 0xc076513d00, 0x0)
[2020-06-24T04:31:49.923Z] 	/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/ddl/split_region.go:101 +0xfa
[2020-06-24T04:31:49.923Z] github.com/pingcap/tidb/ddl.splitTableRegion(0x3dda500, 0xc0759ab900, 0x7f8b9c15b680, 0xc07aab8e00, 0xc076395e40, 0xc07651ad00)
[2020-06-24T04:31:49.923Z] 	/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/ddl/split_region.go:46 +0x135
[2020-06-24T04:31:49.923Z] github.com/pingcap/tidb/ddl.(*ddl).preSplitAndScatter.func2()
[2020-06-24T04:31:49.923Z] 	/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/ddl/ddl_api.go:1711 +0x56
[2020-06-24T04:31:49.923Z] created by github.com/pingcap/tidb/ddl.(*ddl).preSplitAndScatter
[2020-06-24T04:31:49.923Z] 	/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/ddl/ddl_api.go:1716 +0x34f
[2020-06-24T04:31:49.923Z] FAIL	github.com/pingcap/tidb/executor	15.162s
```
### 4. Affected version (Required)

master branch

**Comment by bobotu** [comment] 2020-06-30 06:21
Duplicate of https://github.com/pingcap/tidb/issues/18236

**Closed by bobotu** 2020-06-30 06:21 UTC
Labels: component/DDL, type/bug
