### ISSUE TITLE
QPS drop to zero when add column

### ISSUE THREAD

**Issue by Lily2025** [pingcap/tidb#30940] opened 2021-12-22 08:38 UTC
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
oltp_fun_002
1、run sysbench
2、add column for all tables
sysbench --mysql-user=root --db-driver=mysql --time=0 --report-interval=10 --mysql-db=test --mysql-host=tc-tidb.endless-oltp--tps-512791-1-934 --mysql-port=4000 --threads=512 --tables=32 --table-size=10000000 --mysql-ignore-errors=2013,1213,1105,8028,9007 --rand-type=pareto oltp_read_write run

### 2. What did you expect to see? (Required)
qps can not drop to zero

### 3. What did you see instead (Required)
QPS drop to zero
![xPLeCuNpPo](https://user-images.githubusercontent.com/84712107/147062505-a1b3aefe-8dbb-4939-94f0-54a0661ccecc.png)
![image](https://user-images.githubusercontent.com/84712107/147069690-54c8c50a-1ea4-4077-916e-a2a8ea2d1aa8.png)
![middle_img_v2_5dba459f-8cf9-434a-b27c-59de5382776g](https://user-images.githubusercontent.com/84712107/147062536-4eff70ea-f5fb-4263-98eb-92f930c39e08.png)

### 4. What is your TiDB version? (Required)
 # ./tidb-server -V
Release Version: v5.0.6
Edition: Community
Git Commit Hash: 181b4c280dfad2da8fe8e52d76436b8ad06e90ae
Git Branch: heads/refs/tags/v5.0.6
UTC Build Time: 2021-12-21 09:10:51
GoVersion: go1.13
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false

**Comment by you06** [comment] 2021-12-23 06:17
IMO, the problem is TiDB internally panics. This issue is already fixed in master by #26759. In my test, sysbench quits when meeting internal panic with error `state = 'HY000': MySQL server has gone away`, after restarting sysbench, it works well.

**Closed** 2021-12-23 11:42 UTC
Labels: type/bug, sig/transaction, severity/critical, found/automation
