### ISSUE TITLE
Cannot convert NULL value to non-Nullable type

### ISSUE THREAD

**Issue by lilinghai** [pingcap/tidb#46036] opened 2023-08-14 01:53 UTC
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```sql
CREATE TABLE `tbl_8` (
  `col_40` varchar(458) NOT NULL,
  `col_41` float DEFAULT NULL,
  `col_42` varchar(111) NOT NULL DEFAULT 'iFN1*3sU',
  `col_43` mediumint(9) NOT NULL DEFAULT '3553140',
  `col_44` time NOT NULL,
  `col_45` bigint(20) NOT NULL,
  KEY `idx_9` (`col_45`,`col_43`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin
PARTITION BY HASH (`col_45`) PARTITIONS 4;
alter table tbl_8 set tiflash replica 2;
INSERT INTO `tbl_8` VALUES ('=GPHkJhQEvthZg',5179.665,'jS!(Nm',-2120296,'08:56:04',338028899087627200),('V)B6ZKeky2d',6278.734,')(EvEb07Mw)GnUQ',-1058896,'06:31:32',2571303734092370492),('em7PS5@Ira',6743.1997,'E2ia-YVN',7989377,'12:03:00',-7390014158604252544),('KGMAdJVv#+J1)sC',8819.91,'m^RQs',1690316,'06:51:08',5046011724462682480),('L^OtfWWS^(IBT%B^',9423.195,')r',-7877560,'17:51:04',-6651664756053734244),('B!q7ni$8',7396.6636,'XRmZFXUZaEcu4LO',921086,'05:11:22',1841830216084189048),('w)~2JcaWtb2qpQi$f',NULL,'MzXJtJhuof6L0q',-7351114,'00:22:40',-4134646251075020020),('VeLJbIQ',3445.3967,'zYK-e5yn^w0vA@vx',-5166261,'21:30:16',-4243775564670467864),('gA@n3VOPUYw0c8#lN&w',4630.046,'',-6951287,'19:35:27',-1908349067557384620),('Boj*~^xY',6371.8423,'if*vt&$O',7706481,'14:10:38',2437836432393327436),('KFX)j^OMcN*Ce_ust',8759.594,'#4jDl_eMA+Z',-2190749,'19:42:59',-7820544676733484816),('9v^@Bj~ovm',321.20087,'#',-8271936,'19:31:38',4480852144829163268),('j4ShLS#I3i-A',655.0054,'4Tak@qV$gkb+-q(T',3880312,'07:02:13',-7743351979331151484),('LY3j!aJRp1',5958.407,'*5WUbTx7PyK',602349,'08:44:00',2173868303747569108),('o+oSN-%wdHLFm-a',6151.7607,'RX8+~GrxH5ofV&',-3296145,'03:46:31',-7106174330443554080),('q9kW%',6595.108,'rny',4982212,'13:33:36',-1445134017111297984),('TPZKXMJxKX+)VR-*c&',4500.79,'',6762750,'02:01:17',1434473669342903100),('k$Mmujg-x37I',6393.1567,'$fq@v3K~Pd',-7604473,'16:12:53',-6709530699078870900),('hIA_5kWDX05-RjO',NULL,'+@@@QXk*z',-3887984,'16:19:53',-8385756106970774676),('rPaXqiqhF612',6649.347,'1W7K#!$',-3873024,'10:47:23',-4447175961614938472),('@T2O6w!ylncl',3621.2922,'wqCD_IX6JHCR^J6us*',2126374,'16:22:11',8011146357620390652),('rRX)a3HnXqEEn$@D',4798.8135,'uv',-8212211,'10:47:40',6128497060460282048),('',1977.1954,'&55MBG#8wZY3~BYET',7419678,'14:52:13',7696268829272698672),('MtULlXl6Fxo3',5360.303,'7%(',-5788362,'11:26:34',-6374091592178839416),('3ZAGtG',3855.9634,'O_@(bA~S&KU&m9',-4210011,'23:13:08',1759747767687814160),('G',2459.9434,'',-4622570,'10:57:37',5709316764785406585),('=)GLY2(~R1_dh5Z',2932.402,'@Eui%v@SKD',-807850,'20:41:15',6293198755286357649),('nPS#K',9846.776,'ogDPn',-2117004,'06:32:12',-2329090878910299113),('',2852.7864,'i-',-212049,'17:04:44',-4646052692363098317),('ySgzGJWcKH',NULL,'-hYMNg-$)yRH',4690657,'00:42:09',-4678412352287148417),('I~DI@^exABo2',3043.8372,'-r4giXl',-3884411,'21:43:00',8123126606494729237),('aaFSvFfahBHy%G~DGM',7254.024,'r7vzk~pM',-581478,'15:33:40',7126318100926288305),('VMJP',6580.548,'xn6if!B%F86pj@EPJO',2639828,'04:13:07',-1342097802291844877),('29D',554.0977,'iV',-6109503,'14:41:11',8756157693268416077),('uv$',1843.3385,'',-2678657,'20:44:02',-5641008095312192737),('cP6LU6T6WjByL',9666.129,'8t^yL-',4628161,'15:50:22',4277666137792104129),(')-eLYw',7773.322,'px',-5808514,'11:27:29',8869542245708778433),('%%&$f5c$=JYMCPGTjnv',1463.6615,'NlHfA~s)Ip~',-4705449,'04:28:21',-2058247715361718209),('=affFpsnV*dLLXPCNH',2763.1536,'wFi(e',-1483576,'16:37:10',6731434666743389121),('5iY&Cn=+4D*EW&',1355.561,'+mCVlkN',6971416,'21:37:14',3510770884127774345),('pgkb',9018.637,'t8gT3UF',1168463,'06:37:54',2921172578182105849),('km^df@UFq3zQMQfDW',514.24854,'Hx(ynq=@*U27aV',3890365,'19:59:06',-8621114752157091665),('_z',74.83859,'pP',-20828,'14:07:38',-4261311537938610577),('twS9C',5378.894,'&L6Hu##c*Lymf$GO+&2',-5690948,'18:33:54',-6883740525186644809),('o7g#axUxQSUKk',4687.318,'9X8IyFA',-409932,'18:45:06',2054110936939509357),('AU&Ki#hSwsB+gza8q20',3212.547,'h8rg0L~Fge58RB7*xqE',4797753,'16:07:35',-2263873923073667297),('Ktc*fc',350.87222,'bdIk-^',5556215,'17:42:14',-98141625912699257),('SuA0Q+#~Xs(B9r55Gr^',9033.003,'94qIixWPNCl',-7714493,'06:48:29',-3781672678665749797),('',2428.0532,'QaE^qFO^BX(fT+Mmh',-2843339,'13:42:20',-3081725921464118089),('Rr^2MYMs3lH(Of_fx',5676.486,'H(ruEAiQ',-5843111,'20:02:24',2300079621216901349),('oc!K!',2733.982,'&',6236651,'15:31:51',5459219024293844801),('4G+wH&w7mbeIs6(',9588.545,'Tht48K&',-3411208,'08:50:08',-7480107041599924670),('kl^Uf)=$DMX9yhK#t=',3115.9636,'kmCKUuvq1eNw8*Tl@um',7299396,'14:45:13',-6057546881302306258),('yNTxb@JMCP',9987.3545,'uJ7-Kllh0',3714263,'23:42:09',-5370681085006526677),('8=',1667.8577,'3U3R#!u1e2Hp6_5e',2064746,'01:59:51',-91288124062352742),('DLCj^KW',6739.944,'itIcl8^VvQa7CD',-4812866,'02:15:22',3380604527175261710),('',1852.2058,'Fh_IDp',5142299,'09:33:24',-3762137961195030594),('q_4EOrP8tA3_-@',6194.7017,'+N^_X644=O6',5187766,'11:50:18',-3177087054146431974),('fENy0QEPus&',9356.678,'k1P',-1039606,'02:31:57',892568112345307838),('8YPNWtkKcr+AE',2233.7056,'Ug0psRR',-6803590,'06:10:44',-1138748116936933546),('5YY8g4puY79JsrI',6317.3877,'+f79',2291568,'09:36:36',-1019189738819386779),('fUw-8',337.54865,'oT',2307715,'04:46:07',6464362343549968563),('(ee-2',6490.8735,'Dbo5r~Fzka1',1609453,'11:55:11',5963395930544802438),('',226.11055,'0BLo',7984398,'13:14:56',-4869895561002911162),('d!Wo~U4dYs-J',6881.4927,'EV5rN)tYhXGpDjpH',6647939,'13:55:16',-2849549537222774238),('d3+)!(',7182.3354,'pFE%AY',5425009,'02:49:34',8835659798387021342),('G',5061.419,'0nVF4CMT',4507387,'11:54:14',6114335631540657274),('Cfa5kqAkWy95YqU',9103.984,'1mrb3BCHMQs20XG',58527,'04:40:53',-361786003703822426),('aRCi9KZbc1Sgh',5166.7397,'WdZMwbGx@HP_p',375076,'20:24:45',-5547804020778332354),('olIbnw4L',2908.1826,'@oQ!GcOLm+B5cmkTQ2',1631324,'10:55:15',-2923344686690975018),('OlE1',4334.8735,'UyX_pa6Wv7+syMm@&N',4679706,'19:00:00',-6298652807647120078),('U6cGQn',2510.767,'GXtp&R^Oa',-7899693,'05:42:48',-2339929567798716670),('^tQI~^cnz',682.71173,'',6620885,'00:45:56',3093076934907931126),('Q0G^E4*4&LqBP9apE&',6631.0225,'N#QlfGew((l*%2a~',-4085180,'01:13:43',7766842420294119610),('ATYtTRO0B%)$',5414.077,'aJ',-3173367,'03:03:08',-400804813741500827),('Q',2675.4163,'Y0Tb*#',-45471,'21:25:22',7654715287555155027),('',7090.0083,'0',8148165,'03:56:35',2697186376911363899),('ND@6tY!t&5',715.2726,'kq2yn1*',99490,'01:59:40',539042550017403935),('=%SfPzIdR$wRRxI^G!@',9060.932,'UvOW&H!',7014342,'20:46:45',5530837369326901655),('#j@7I^z*S6@(',1024.1294,'CKcL-',4115885,'04:49:27',-6787298716326700470),('F%f3Lq2V#ICtzCT',3262.1316,'djcraf8v',1927636,'13:57:42',-1821117956266751170),('vcCgtx@Q',3792.6401,'fDTe*wU4pn',1419729,'11:16:18',-1043148035012986403),('',5762.6807,'%X~cqLfiw',5145246,'06:12:37',808246623763694779),('KEQCFkDd(1EcwwWhln',3434.693,'',-5565122,'14:20:42',-6064971704096956559),('PrTdoI',8670.623,'q6$3$scj6I!YS_',1825125,'04:28:41',8110279582179675735),('lm@5rak@%V',307.58096,'IxVF%oYTE3',3235806,'06:23:19',-2864762221490036775),('MiAXVUVwrXEFgIZEnhH',5960.0273,'Knry',7600529,'09:52:40',4034887774080085783),('mvP(x%F',8867.511,'4IYAhZc)iHS3cd4&9',-1275057,'10:07:34',-3411449689809211675),('5eFy$&%ROX_U#J1$WL',2995.6526,'j',4649636,'02:37:49',5695836773441640103),('VxbP!pLCG(Q',5669.1294,'cS5lAkloseXdIo(Mk*+',304608,'14:50:25',3042957135756739359),('SGC',5608.3853,'i_',-682665,'17:42:42',4759259307338350043),('jf*C',3977.1316,'y9XEf9z*ij&j9_8',2002027,'15:19:59',-143524944093002083),('l',5450.965,'j+N_Ee=u',-4215879,'08:18:47',-176984012264503727),('K+t',4909.818,'h=^eVALk',-748217,'12:31:48',-7435911481956789547),('q8Hz#amC_s^2os8A0f',9915.754,'zO+7$DLE+Do~+w(i',-7637084,'04:14:29',-2514623631477366923),('4ON(#$kPBKP',9159.416,'rVg5',-2034036,'03:28:01',1854008589141474159),('Zj',600.502,'IXv8^',-6100764,'23:00:34',-1364625530845575247),('EpM7H=oj5E',5469.706,'&HYgZn54Lhv',-4810500,'02:49:22',209023013769403631),('Rr_)mWsXg',469.4744,'3Dnm',2340354,'18:43:44',6640645750825696999),('J20LIszeu2',3674.579,'vq*t$l-a6amZa!ew%m',-6340911,'12:52:21',3032048411689238875),('C277GY=C3',4209.1113,'50Flm',4799666,'07:01:46',-5580692709870959723),('cbWPr',2227.1572,'3DG9',-1325805,'15:51:52',-8724753311902125059),('nhq^&UXF@L7',90.01231,'knwJbZNJ0Ruk',7555272,'13:08:57',-8799732032283605811),('cc',4929.6895,'_CX(30Fk=F',-688288,'16:02:03',8502551930618839699),('wOI',4566.475,'',-7530336,'20:24:31',6805065299504332475),('DW',9225.482,'oht*dH',-7491962,'11:20:04',9140759627530759667),('X+e8RSY!3',8176.8853,'_AbG5IyCtf$~_4QKUo',-7084780,'21:57:46',-423745007468119603),('uoM@=m',7208.6924,'ShDU',-6815749,'08:22:31',-2727910521975210879),('%eNe6QU#^NBQuFkq$e',6021.593,'mR-+#6Pr-=ymu',320105,'23:02:15',1748191709845824359),('sks=D8msp#I3',1439.4464,'V',1524143,'10:42:57',-2668953418573023651),('+c-weMy)-3ca*)=kxr_',3565.5862,'JC8_OoR80tp',-4778358,'23:39:32',5605841681597730799),('',3932.6062,'x1Ur4Og',2893612,'06:08:40',-3681324033143531755),('nxBR(Z&-IFz',2559.1316,'c(P',6127501,'13:20:45',5632793438298386431);
select    lag( tbl_8.col_43 , 6 ,NULL) over w as r0 from tbl_8 where not( tbl_8.col_44 between '08:17:52.00' and '05:02:37.00' )  window w as (  order by col_44,col_42,col_40,col_41,col_45,col_43 rows between 2 preceding and current row ) order by r0;
```
### 2. What did you expect to see? (Required)
query successfully
### 3. What did you see instead (Required)
ERROR 1105 (HY000): other error for mpp stream: Code: 349, e.displayText() = DB::Exception: Cannot convert NULL value to non-Nullable type, e.what() = DB::Exception,
### 4. What is your TiDB version? (Required)

Release Version: v7.4.0-alpha
Edition: Community
Git Commit Hash: 92b5a676068613bffac6059e4826d7da59ac242d
Git Branch: heads/refs/tags/v7.4.0-alpha
UTC Build Time: 2023-08-13 11:44:40
GoVersion: go1.21.0
Race Enabled: false
Check Table Before Drop: false

**Comment by seiya-annie** [comment] 2023-08-15 00:03
@lilinghai can't reproduce in 0814 nightly
please upload tidb.log

**Comment by windtalker** [comment] 2023-08-15 06:15
close as duplicated with https://github.com/pingcap/tidb/issues/46050, should be fixed by https://github.com/pingcap/tidb/pull/46051

**Closed by windtalker** 2023-08-15 06:15 UTC
Labels: type/bug, sig/execution, severity/major, may-affects-5.2, may-affects-5.3, may-affects-5.4, may-affects-6.1, may-affects-6.5, may-affects-7.1
