### ISSUE TITLE
Latency commit and prewrite  from TiDB to TiKV increased abnormally

### ISSUE THREAD

**Issue by phamtai97** [pingcap/tidb#27647] opened 2021-08-28 07:07 UTC
Hi all.

I monitored the TiDB dashboard and found the KV duration pannel to be rather unusual:
<img width="680" alt="Screen Shot 2021-08-28 at 1 41 29 PM" src="https://user-images.githubusercontent.com/38773351/131209585-20f28a3f-8950-4b6e-a154-4e94f3c0059a.png">

It has a regular repeating pattern. I monitor the metric of TiDB and TiKV and see everything as normal. I don't know if there is any problem that can affect the KV duration metric.

Can you help me to see which dashboard is the cause or the causes of that problem?

I use TiDB version 3.012.

**Comment by phamtai97** [comment] 2021-09-08 10:00
Hi all
I simulated the following:
- I create a table with 16 fields.
- I update 2-3 fields on 128 rows concurrently with 1k TPS.
- Besides, I also use the Sum statement for the values of those 2-3 fields of 128 rows.
- Then, I monitor and see the above issue.

**Comment by phamtai97** [comment] 2021-09-10 08:59
Can you help me? @tiancaiamao

**Comment by tiancaiamao** [comment] 2021-09-10 12:54
> I update 2-3 fields on 128 rows concurrently with 1k TPS.

How large is the table? do you mean the whole table is 128 rows? or just pick 128 rows randomly?

From the KV Request Duration metrics, this is caused by TiKV, maybe by some background periodic task?

Here is a tool to collect the metrics, if you can update the metrics data, it would be very helpful for us to analyze:
https://metricstool.pingcap.com/#backup-with-dev-tools

@phamtai97

**Comment by phamtai97** [comment] 2021-09-11 17:06
Hi @tiancaiamao

The size of the table is about 30 million rows.
I selected the previous 128 lines out of 30 million lines for benchmarking. Then, I updated those 128 lines by updating 2 fields including a field1 for adding or subtracting and a field2 containing the time value of that update. TPS of the update flow is about 1k  TPS.
Also while running the update benchmark command I called the query command as follows:
```sql
SELECT SUM(field1) AS total, MAX(field2) AS modified_time  FROM  table_test  WHERE  id IN (?, ?. ... ?)" // IN id of 128 above rows.
```
TPS of the above query is about 400-500 TPS.

**Comment by phamtai97** [comment] 2021-09-14 16:12
@tiancaiamao

**Comment by tiancaiamao** [comment] 2021-09-25 00:44
In v3.0 TiDB read will block write.
Maybe you can try v4.x whose read doesn't block write, and v5.x which have the async commit feature make the write latency much lower.

**Comment by tiancaiamao** [comment] 2021-09-25 00:50
If there is no `Sum` statement, is the latency jitter still there?

**Comment by phamtai97** [comment] 2021-09-26 15:21
Can you give me the documentation for the write statement block read statement section?

**Comment by tiancaiamao** [comment] 2021-09-27 11:00
> Can you give me the documentation for the write statement block read statement section?

There is not documentation. It's the implementation detail of the old version TiDB.
You can't reproduce the block use those simple query.

The block happens only when transaction A read a key, and transaction B is doing 2PC to modify the key.

```
BEGIN;
UPDATE table_test SET field1= field1 + ?, field2=? WHERE id=?;
COMMIT;           // After this command, 2PC is in process ... it takes maybe 2ms? and during which if the other `Sum(field1)` read query happen simultaneously, the read will sleep and retry ... (the block)
```

**Comment by phamtai97** [comment] 2021-09-27 18:39
So, I have some cases:
- If the read statement is not the transaction, the write statement is the transaction.
- If the read statement is not the transaction, the write statement is not the transaction.
- If the read statement is the transaction, the write statement is not the transaction.
- If the read statement is the transaction, the write statement is the transaction.
(read and write performs on the same key)

The above cases on the write section all block read, right?

**Comment by tiancaiamao** [comment] 2021-09-28 02:16
Optimistic transaction means there is no interaction with TiKV .... util the final "Commit" command.
That means:

begin;   // no block
read from tikv   // no block
write to tikv    // no block ... actually the written keys is cached in the tidb memory
update = read + write // no block ...   changes cached in tidb
commit;  // ----- this is the real interaction with tikv, and the real optimisitc transaction...


autocommit = true
insert into t values (xxx);  
// it's equal to 'begin; insert into t values (xxx); commit'  but the 'begin/commit' is by internal tidb rather than by the user.
// it's also write to tikv in the end commit operation.

I think I use "block" and it's misleading ... 
it's better to say "read-write conflict" when read request and write request reach to tikv simultaneously.
In optimistic transaction, the write is not send to tikv when "begin" is called, so it will not "lock" the whole read

**Comment by phamtai97** [comment] 2021-09-28 11:12
Oh, Thank you. 
I find the document: https://docs.pingcap.com/tidb/v3.0/optimistic-transaction that shows detail the flow of the transaction.

**Comment by phamtai97** [comment] 2021-11-10 02:09
Hi @tiancaiamao, 
I read the Async commit in v5.0 at the blog:
- https://pingcap.com/blog/async-commit-the-accelerator-for-transaction-commit-in-tidb-5.0
- https://github.com/tikv/sig-transaction/blob/master/design/async-commit/parallel-commit-known-issues-and-solutions.md

So, I find the reading still has to wait until the prewrite is complete. For example:
- The prewrite of txn1 locks the key 'K' with min_commit_ts = 1 and it is not complete prewrite phase, then the read of txn2 wants to read the key 'K' at the ts=2. txn2 see the key 'K' is locked by the txn1, so the read must wait. Is what I understand correct? And it increases latency.

**Comment by phamtai97** [comment] 2021-11-11 07:54
@tiancaiamao  pls.

**Comment by tiancaiamao** [comment] 2021-11-11 11:29
> https://github.com/tikv/sig-transaction/blob/master/design/async-commit/parallel-commit-known-issues-and-solutions.md

This one is quite outdated. It's some notes before (or during) we implement async commit.

==========================

> https://en.pingcap.com/blog/async-commit-the-accelerator-for-transaction-commit-in-tidb-5.0

This is the canonical blog and it's content is still update-to-date.

You can read the "how-to-determine-the-commit-ts-of-a-transaction" carefully, and get familiar with the Min Commit TS concept, this is very important to understand how read doesn't block write.

- The prewrite of txn1 locks the key 'K' with min_commit_ts = 1 and it is not complete prewrite phase, then the read of txn2 wants to read the key 'K' at the ts=2. txn2 see the key 'K' is locked by the txn1, so the read push the min_commit_ts to 3 and it can still read without block...

**Comment by phamtai97** [comment] 2021-11-11 14:58
Oh. I will read the blog carefully.  So, I see the note of the above [blogs](https://en.pingcap.com/blog/async-commit-the-accelerator-for-transaction-commit-in-tidb-5.0#fn-2):
>In the prewriting process, to prevent that a more recent snapshot read breaks this constraint, TiKV adds a memory lock to the prewrite key and temporarily blocks the read requests whose Start TSs are greater than or equal to the Min Commit TS.

In this case, the read txn must wait for the memory lock to be released. If so,the read txn will still be blocked.

**Comment by tiancaiamao** [comment] 2021-11-11 16:59
So you misunderstand the lock in a operation system(the **memory lock** here), and the transaction lock.

Imagine you have a variable called `MaxTS`, there is only one global variable of it.
And you have many **concurrent query**, all of them want to modify `MaxTS`.
Each query come with its own `ts`, and the code logic is:

```
if ts > MaxTS {
      MaxTS = ts
}
```

If there is no **lock** to protect this concurrent query operation, you'll find `MaxTS` may even decrease sometime! That's unacceptable... 

The above example illustrate a scene **memory lock** is necessary.
That's come back to the blog.

The constraint is: min commit ts of a prewrite operation < MaxTS
MaxTS is constantly changing (by different concurrenty read query), and **prewrite take some time to finish** ... how can we guarantee that when we start to handle prewrite the constraint hold, and when the prewrite finish, the constraint still hold?

So we need a lock ...to prevent prewrite operation conflict with the concurrent change MaxTS operation (read query, to be exact)...  that's it.

The prewrite operation is fast enough, it's a memory lock to provide concurrent security

**Comment by phamtai97** [comment] 2021-11-12 01:01
Tks @tiancaiamao very much. I'm misunderstanding the memory lock and the txn lock in this case.

**Comment by jebter** [comment] 2024-06-06 03:29
The issue has not been updated for too long, so I will close it. If there are any updates, you can reopen it.

**Closed by jebter** 2024-06-06 03:29 UTC
Labels: type/question, component/tikv
