### ISSUE TITLE
union scan result error when using dynamic mode

### ISSUE THREAD

**Issue by ChenPeng2013** [pingcap/tidb#26719] opened 2021-07-29 03:30 UTC
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
use test;
drop table if exists t;
set tidb_partition_prune_mode=dynamic;

CREATE TABLE t( id INT NOT NULL, store_id INT NOT NULL) PARTITION BY RANGE (store_id) ( 
  PARTITION p0 VALUES LESS THAN (6), 
  PARTITION p1 VALUES LESS THAN (11), 
  PARTITION p2 VALUES LESS THAN (16));

insert into t values(1,1), (5,5);
insert into t values(-1,-10), (10,10), (11, 12);
begin;
delete from t where id in(1);
insert into t values(1, 1);
delete from t where id in(1);
select * from t PARTITION(p0) order by id;
commit;
```

### 2. What did you expect to see? (Required)
```
mysql> begin;
Query OK, 0 rows affected (0.00 sec)

mysql> delete from t where id in(1);
Query OK, 1 row affected (0.00 sec)

mysql> insert into t values(1, 1);
Query OK, 1 row affected (0.00 sec)

mysql> delete from t where id in(1);
Query OK, 2 rows affected (0.00 sec)

mysql> select * from t PARTITION(p0) order by id;
+----+----------+
| id | store_id |
+----+----------+
| -1 |      -10 |
|  5 |        5 |
+----+----------+
2 rows in set (0.00 sec)

mysql> commit;
Query OK, 0 rows affected (0.00 sec)
```

### 3. What did you see instead (Required)
release-5.0 & release-5.1 & master
```
mysql> begin;
Query OK, 0 rows affected (0.00 sec)

mysql> delete from t where id in(1);
Query OK, 1 row affected (0.00 sec)

mysql> insert into t values(1, 1);
Query OK, 1 row affected (0.00 sec)

mysql> delete from t where id in(1);
Query OK, 2 rows affected (0.00 sec)

mysql> select * from t PARTITION(p0) order by id;
+----+----------+
| id | store_id |
+----+----------+
| -1 |      -10 |
|  1 |        1 |
|  5 |        5 |
+----+----------+
3 rows in set (0.00 sec)

mysql> commit;
Query OK, 0 rows affected (0.00 sec)
```

### 4. What is your TiDB version? (Required)

```
Release Version: v5.1.0-66-g797bddd25
Edition: Community
Git Commit Hash: 797bddd25310ed42f0791c8eccb78be8cce2f502
Git Branch: release-5.1
UTC Build Time: 2021-07-29 03:28:11
GoVersion: go1.16.5
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
```

**Comment by ChenPeng2013** [comment] 2021-07-29 03:32
Dynamic Pruning Mode for Partitioned Tables  is experimental feature

**Comment by qw4990** [comment] 2021-07-30 02:55
A minimal reproducible case:
```
create table tx (a int) partition by range (a) (partition p0 values less than (10), partition p1 values less than (20));
insert into tx values (1);

set tidb_partition_prune_mode=dynamic;
begin;
delete from tx where a in (1);
select * from tx PARTITION(p0);
rollback;
```

**Comment by qw4990** [comment] 2021-07-30 08:33
Root Cause: 
1. When processing a selection in a transaction, `UnionScan` encodes rows into keys and looks up them in its buffer to check if these rows have been deleted(see [here](https://github.com/pingcap/tidb/blob/release-5.1/executor/union_scan.go#L222)); 
2. When encoding these rows, their partition table IDs are needed, but in `dynamic-mode`, `UnionScan` cannot know the actual partition table IDs of these rows now;

Related Problem: `Select for Update` has the same problem, and it is fixed by https://github.com/pingcap/tidb/pull/21148;

Solution: Fixing it thoroughly is a little complicated and has more risks, so now we decided to just quick fix it by disabling `dynamic-mode` in transactions, and fix it thoroughly next Sprint.

**Closed** 2021-08-04 06:47 UTC
Labels: need-more-info, severity/critical, sig/planner, type/bug
