### ISSUE TITLE
Region cache outdated after scale-in TiFlash nodes

### ISSUE THREAD

**Issue by tangenta** [pingcap/tidb#38929] opened 2022-11-07 05:45 UTC
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

1. Starts a TiDB cluster with 2 TiFlash nodes.
2. Scale in a Tiflash node.
3. Scale out a TiFlash node with a different address.

```
set @@session.tidb_allow_mpp=1;
set @@session.tidb_enforce_mpp=1;
set @@tidb_partition_prune_mode=dynamic;
```

Execute the MPP query, it is slow and prints log:

```
[batch_coprocessor.go:357] ["Store is not ready"] ["store address"=xxx.xxx.xxx.xxx:xxxx] ["err message"="rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial tcp xxx.xxx.xxx.xxx:xxxx: connect: connection timed out\""]
```

### 2. What did you expect to see? (Required)

No error.

### 3. What did you see instead (Required)

"Store is not ready" error.

### 4. What is your TiDB version? (Required)

v5.4.1

**Comment by guo-shaoge** [comment] 2023-09-27 09:21
The error log `Store is not ready` is normal, because [`mpp_probe`](https://github.com/pingcap/tidb/blob/master/store/copr/mpp_probe.go#L142) will keep probing the scaled in tiflash for an hour.

But I cannot reproduce the slow mpp query using tpch1.

**Comment by guo-shaoge** [comment] 2023-09-27 09:28
Maybe fixed by https://github.com/pingcap/tidb/pull/39932.
Also I failed to reproduce this problem using the steps in the issue description for v7.4.0.

**Closed by guo-shaoge** 2023-09-27 09:28 UTC
Labels: type/bug, sig/execution, severity/moderate, affects-5.4, may-affects-4.0, may-affects-5.1, may-affects-5.2, may-affects-5.3, may-affects-5.0, may-affects-6.0, affects-6.1, may-affects-6.2, may-affects-6.3, affects-6.5
