### ISSUE TITLE
The number of regions keeps increasing

### ISSUE THREAD

**Issue by dabaosun** [pingcap/tidb#5915] opened 2018-02-27 05:38 UTC
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
Drop one database, and then re-create it.

2. What did you expect to see?
The number of regions should be reset. And the storage is recycled,

3. What did you see instead?
After several days of the drop operations, the storage is recycled ,But the number of regions keeps increasing.

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
'Release Version: v1.0.7-1-g4913f64\nGit Commit Hash: 4913f64c14f6b8e5761414def9fac3c477626f74\nGit Branch: release-1.0\nUTC Build Time: 2018-01-25 06:59:40'

**Comment by zhexuany** [comment] 2018-02-27 05:42
> What did you expect to see?
The number of regions should be reset. And the storage is recycled,

This is wrong. When you drop one databases, it is only logically dropped not physically. physically dropping is running background. We added a feature call `batch delete` to improve performance of this operation.

**Comment by zhexuany** [comment] 2018-02-27 05:42
I am closing this issue since it is not a bug report or a improvement proposal but please feel free to reopen this issue if you feel like you want to add more stuff.

**Closed by zhexuany** 2018-02-27 05:42 UTC

**Comment by dabaosun** [comment] 2018-02-27 06:28
Thanks your response. 
I understand the physically dropping is running background. However, I'm confused that After several days, why the storage was recycled , but the number of regions not. One and more days are not enough for the background dropping?  Since the storage size was recycled, then the background operations seem be working, but why the number of regions was not decreased.

**Comment by dabaosun** [comment] 2018-02-27 06:30
Thanks.
