### ISSUE TITLE
optimize the cost of compile on table with a large number of columns

### ISSUE THREAD

**Issue by dbsid** [pingcap/tidb#52112] opened 2024-03-26 10:15 UTC
## Enhancement

On a table t with 549 columns, running query like `select * from t limit 1`, high cpu cost(45%) on planner.buildLogicalPlan is observed.
Would like to optimizer the cpu cost for this case.

![image](https://github.com/pingcap/tidb/assets/2316425/a8dcfb38-1088-4d59-b2c3-5e75c2350722)
![image](https://github.com/pingcap/tidb/assets/2316425/50a6194d-bb8a-4997-8181-9a14af48ae0f)

**Comment by Rustin170506** [comment] 2024-08-20 07:39
I cannot reproduce this issue. I tried following steps:
1. Create a v8.2.0 cluser: `tiup cluster deploy upstream v8.2.0 upstream.yaml -p &&tiup cluster start upstream`
2. Create a table with 1000 columns:
```rust
---cargo
[dependencies]
clap = { version = "4.2", features = ["derive"] }
sqlx = { version = "0.7", features = ["runtime-tokio-rustls", "mysql"] }
tokio = { version = "1", features = ["full", "rt-multi-thread"] }
---

use clap::Parser;
use sqlx::mysql::MySqlPoolOptions;
use tokio::time::Instant;

#[derive(Parser, Debug)]
#[command(version)]
struct Args {
    #[arg(short, long, help = "MySQL connection string")]
    database_url: String,
}

async fn create_large_table(pool: &sqlx::MySqlPool) -> Result<(), sqlx::Error> {
    let mut query = String::from("CREATE TABLE IF NOT EXISTS large_table (");

    for i in 1..=1000 {
        query.push_str(&format!("column_{} VARCHAR(255)", i));
        if i < 1000 {
            query.push_str(", ");
        }
    }

    query.push_str(")");

    sqlx::query(&query)
        .execute(pool)
        .await?;

    println!("Created table with 1000 columns.");
    Ok(())
}

#[tokio::main]
async fn main() -> Result<(), sqlx::Error> {
    let args = Args::parse();
    let pool = MySqlPoolOptions::new()
        .max_connections(5)
        .connect(&args.database_url)
        .await?;

    let start_time = Instant::now();

    create_large_table(&pool).await?;

    let duration = start_time.elapsed();
    println!("Finished creating the table in {:?}.", duration);

    Ok(())
}
```
3. Try running the SQL: `select * from large_table limit 1;` couple of times.
4. Check the profile:
<img width="1710" alt="image" src="https://github.com/user-attachments/assets/dd41d848-6cc8-4330-b880-d5f7ccbc49df">
```SQL
MySQL [test]> select * from large_table limit 1;
Empty set (0.03 sec)
```
5. Check the metrics:
<img width="915" alt="image" src="https://github.com/user-attachments/assets/fdade8cc-7f75-461b-bbba-f4fb3a5146d0">

**Comment by Rustin170506** [comment] 2024-08-20 07:42
@dbsid I am going to close this issue. If you can still reproduce this issue please feel free to open it with more detailed information. Thank you!

**Comment by Rustin170506** [comment] 2024-08-20 08:06
I can still try to make it better.

**Closed** 2024-08-21 09:42 UTC
Labels: type/enhancement, sig/planner
