### ISSUE TITLE
interface conversion: interface {} is nil, not *memory.bytesLimits

### ISSUE THREAD

**Issue by darkelf21cn** [pingcap/tidb#42302] opened 2023-03-16 03:39 UTC
## Bug Report

A suspicious error shows in tidb.log during service startup. 

### 3. What did you see instead (Required)
[2023/03/16 03:24:31.135 +00:00] [ERROR] [projection.go:462] ["projection executor panicked"] [error="interface conversion: interface {} is nil, not *memory.bytesLimits"] [stack="github.com/pingcap/tidb/executor.recoveryProjection\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/executor/projection.go:462\ngithub.com/pingcap/tidb/executor.(*projectionInputFetcher).run.func1\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/executor/projection.go:360\nruntime.gopanic\n\t/usr/local/go/src/runtime/panic.go:884\nruntime.panicdottypeE\n\t/usr/local/go/src/runtime/iface.go:262\ngithub.com/pingcap/tidb/util/memory.(*Tracker).Consume\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/util/memory/tracker.go:409\ngithub.com/pingcap/tidb/executor.(*projectionInputFetcher).run\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/executor/projection.go:386"]
[2023/03/16 03:24:47.583 +00:00] [ERROR] [domain.go:1880] ["init stats info failed"] ["take time"=35.718686448s] [error="interface conversion: interface {} is nil, not *memory.bytesLimits"]

[tidb.log](https://github.com/pingcap/tidb/files/10986324/tidb.log)

### 4. What is your TiDB version? (Required)
Release Version: v6.5.0
Edition: Community
Git Commit Hash: 706c3fa3c526cdba5b3e9f066b1a568fb96c56e3
Git Branch: heads/refs/tags/v6.5.0
UTC Build Time: 2022-12-27 03:50:44
GoVersion: go1.19.3
Race Enabled: false
TiKV Min Version: 6.2.0-alpha
Check Table Before Drop: false
Store: tikv

**Comment by xuyifangreeneyes** [comment] 2023-03-16 08:46
@darkelf21cn Is the issue reproducible?

**Comment by xuyifangreeneyes** [comment] 2023-03-16 12:34
I downgrade the issue to major for two reasons:
1. We haven't found a way to reproduce it yet.
2. Even if `InitStats` fails, stats can still be loaded when `loadStasWorker` calls `Handle.Update`.

**Comment by lcwangchao** [comment] 2023-07-31 08:25
6.5.2 still has this problem, it panics here:

https://github.com/pingcap/tidb/blob/697652f90dc7f03a381ac0eb17ba0781d886010a/util/memory/tracker.go#L412

which is invoked by `ProjectionExec` here:

https://github.com/pingcap/tidb/blob/29116c0256c52b224da2b34d712c1063d171c0ad/executor/projection.go#L379

I read some related codes but did not found why it happens...

@XuHuaiyu could you take a look?

**Comment by chrysan** [comment] 2023-11-16 03:51
Close it since it cannot be reproduced. Will reopen it when we met it again.

**Closed by chrysan** 2023-11-16 03:51 UTC
Labels: type/bug, sig/planner, severity/major, may-affects-4.0, may-affects-5.1, may-affects-5.2, may-affects-5.3, may-affects-5.4, may-affects-5.0, may-affects-6.1, affects-6.5, affects-7.0, affects-7.1, affects-7.5
