### ISSUE TITLE
Installing TiDB database quick start guide operation cannot start TiDB

### ISSUE THREAD

**Issue by xiangHannibal** [pingcap/tidb#16971] opened 2020-05-04 09:01 UTC
## Development Task
Starting component pd
	Starting instance pd 127.0.0.1:2379
	Start pd 127.0.0.1:2379 success
Starting component node_exporter
	Starting instance 127.0.0.1
	Start 127.0.0.1 success
Starting component blackbox_exporter
	Starting instance 127.0.0.1
	Start 127.0.0.1 success
Starting component tikv
	Starting instance tikv 127.0.0.1:20162
	Starting instance tikv 127.0.0.1:20160
	Starting instance tikv 127.0.0.1:20161
	Start tikv 127.0.0.1:20160 success
	Start tikv 127.0.0.1:20162 success
	Start tikv 127.0.0.1:20161 success
Starting component tidb
	Starting instance tidb 127.0.0.1:4000
	tidb 127.0.0.1:4000 failed to start: timed out waiting for port 4000 to be started after 1m0s, please check the log of the instance

Error: failed to start: failed to start tidb: 	tidb 127.0.0.1:4000 failed to start: timed out waiting for port 4000 to be started after 1m0s, please check the log of the instance: timed out waiting for port 4000 to be started after 1m0s

Verbose debug logs has been written to /root/logs/tiup-cluster-debug-2020-05-04-16-46-55.log.
Error: run `/root/.tiup/components/cluster/v0.6.0/cluster` (wd:/root/.tiup/data/Ry0VxaD) failed: exit status 1

/root/logs/tiup-cluster-debug-2020-05-04-16-46-55.log 内容：
2020-05-04T16:46:55.028+0800    DEBUG   TaskFinish      {"task": "ClusterOperate: operation=StartOperation, options={Roles:[] Nodes:[] Force:false Timeout:0}", "error": "failed to start: failed to start tidb: \ttidb 127.0.0.1:4000 failed to start: timed out waiting for port 4000 to be started after 1m0s, please check the log of the instance: timed out waiting for port 4000 to be started after 1m0s", "errorVerbose": "timed out waiting for port 4000 to be started after 1m0s\ngithub.com/pingcap-incubator/tiup-cluster/pkg/module.(*WaitFor).Execute\n\t/home/jenkins/agent/workspace/tiup-cluster-release/pkg/module/wait_for.go:89\ngithub.com/pingcap-incubator/tiup-cluster/pkg/meta.PortStarted\n\t/home/jenkins/agent/workspace/tiup-cluster-release/pkg/meta/logic.go:106\ngithub.com/pingcap-incubator/tiup-cluster/pkg/meta.(*instance).Ready\n\t/home/jenkins/agent/workspace/tiup-cluster-release/pkg/meta/logic.go:135\ngithub.com/pingcap-incubator/tiup-cluster/pkg/operation.startInstance\n\t/home/jenkins/agent/workspace/tiup-cluster-release/pkg/operation/action.go:421\ngithub.com/pingcap-incubator/tiup-cluster/pkg/operation.StartComponent.func1\n\t/home/jenkins/agent/workspace/tiup-cluster-release/pkg/operation/action.go:454\ngolang.org/x/sync/errgroup.(*Group).Go.func1\n\t/go/pkg/mod/golang.org/x/sync@v0.0.0-20190911185100-cd5d95a43a6e/errgroup/errgroup.go:57\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1357\n\ttidb 127.0.0.1:4000 failed to start: timed out waiting for port 4000 to be started after 1m0s, please check the log of the instance\nfailed to start tidb\nfailed to start"}
2020-05-04T16:46:55.032+0800    INFO    Execute command finished        {"code": 1, "error": "failed to start: failed to start tidb: \ttidb 127.0.0.1:4000 failed to start: timed out waiting for port 4000 to be started after 1m0s, please check the log of the instance: timed out waiting for port 4000 to be started after 1m0s", "errorVerbose": "timed out waiting for port 4000 to be started after 1m0s\ngithub.com/pingcap-incubator/tiup-cluster/pkg/module.(*WaitFor).Execute\n\t/home/jenkins/agent/workspace/tiup-cluster-release/pkg/module/wait_for.go:89\ngithub.com/pingcap-incubator/tiup-cluster/pkg/meta.PortStarted\n\t/home/jenkins/agent/workspace/tiup-cluster-release/pkg/meta/logic.go:106\ngithub.com/pingcap-incubator/tiup-cluster/pkg/meta.(*instance).Ready\n\t/home/jenkins/agent/workspace/tiup-cluster-release/pkg/meta/logic.go:135\ngithub.com/pingcap-incubator/tiup-cluster/pkg/operation.startInstance\n\t/home/jenkins/agent/workspace/tiup-cluster-release/pkg/operation/action.go:421\ngithub.com/pingcap-incubator/tiup-cluster/pkg/operation.StartComponent.func1\n\t/home/jenkins/agent/workspace/tiup-cluster-release/pkg/operation/action.go:454\ngolang.org/x/sync/errgroup.(*Group).Go.func1\n\t/go/pkg/mod/golang.org/x/sync@v0.0.0-20190911185100-cd5d95a43a6e/errgroup/errgroup.go:57\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1357\n\ttidb 127.0.0.1:4000 failed to start: timed out waiting for port 4000 to be started after 1m0s, please check the log of the instance\nfailed to start tidb\nfailed to start"}
~                                                                                                                                                                         
~

**Comment by hzliangbin** [comment] 2020-05-06 02:01
@xiangHannibal More detail needed.Such as docs you followed,  enviroment, version etc.

**Comment by shenoy-anurag** [comment] 2020-10-20 12:05
I'm facing the same issue.

OS: Ubuntu 18.04
Ti Version: 4.0.7

Docs followed: https://docs.pingcap.com/tidb/stable/production-deployment-using-tiup

Topology:
1 pd, 1 Tidb, 3 TiKV, 1 TiFlash all on single machine for testing.

Error on control machine:
`INFO    Execute command finished        {"code": 1, "error": "failed to start tidb: \ttidb 127.0.0.1:4000 failed to start: timed out waiting for port 4000 to be started after 2m0s, please check the log of the instance: timed out waiting for port 4000 to be started after 2m0s", "errorVerbose": "timed out waiting for port 4000 to be started after 2m0s\ngithub.com/pingcap/tiup/pkg/cluster/module.(*WaitFor).Execute\n\tgithub.com/pingcap/tiup@/pkg/cluster/module/wait_for.go:90\ngithub.com/pingcap/tiup/pkg/cluster/spec.PortStarted\n\tgithub.com/pingcap/tiup@/pkg/cluster/spec/instance.go:101\ngithub.com/pingcap/tiup/pkg/cluster/spec.(*BaseInstance).Ready\n\tgithub.com/pingcap/tiup@/pkg/cluster/spec/instance.go:132\ngithub.com/pingcap/tiup/pkg/cluster/operation.startInstance\n\tgithub.com/pingcap/tiup@/pkg/cluster/operation/action.go:563\ngithub.com/pingcap/tiup/pkg/cluster/operation.StartComponent.func1\n\tgithub.com/pingcap/tiup@/pkg/cluster/operation/action.go:678\ngolang.org/x/sync/errgroup.(*Group).Go.func1\n\tgolang.org/x/sync@v0.0.0-20190911185100-cd5d95a43a6e/errgroup/errgroup.go:57\nruntime.goexit\n\truntime/asm_amd64.s:1357\n\ttidb 127.0.0.1:4000 failed to start: timed out waiting for port 4000 to be started after 2m0s, please check the log of the instance\nfailed to start tidb"}`

TiDB logs on server:
`[error="other error: [components/tidb_query/src/expr/ctx.rs:87]: unknown or incorrect time zone: posixrules"]
[2020/10/20 07:24:51.093 -04:00] [FATAL] [terror.go:257] ["unexpected error"] [error="other error: [components/tidb_query/src/expr/ctx.rs:87]: unknown or incorrect time zone: posixrules"] [stack="github.com/pingcap/parser/terror.MustNil\n\t/home/jenkins/agent/workspace/tidb_v4.0.7/go/pkg/mod/github.com/pingcap/parser@v0.0.0-20200921063432-e220cfcfd026/terror/terror.go:257\nmain.createStoreAndDomain\n\t/home/jenkins/agent/workspace/tidb_v4.0.7/go/src/github.com/pingcap/tidb/tidb-server/main.go:259\nmain.main\n\t/home/jenkins/agent/workspace/tidb_v4.0.7/go/src/github.com/pingcap/tidb/tidb-server/main.go:179\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:203"] [stack="github.com/pingcap/parser/terror.MustNil\n\t/home/jenkins/agent/workspace/tidb_v4.0.7/go/pkg/mod/github.com/pingcap/parser@v0.0.0-20200921063432-e220cfcfd026/terror/terror.go:257\nmain.createStoreAndDomain\n\t/home/jenkins/agent/workspace/tidb_v4.0.7/go/src/github.com/pingcap/tidb/tidb-server/main.go:259\nmain.main\n\t/home/jenkins/agent/workspace/tidb_v4.0.7/go/src/github.com/pingcap/tidb/tidb-server/main.go:179\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:203"]`

Issue seems to be caused by the fact that certain time-zones have a symlink to posixrules. 

TiUP go script seems to be recursively reading /etc/localtime and then when a timezone ends at a symlink to posixrules, TiDB is unable to figure out the actual timezone as 'posixrules' is not a valid time zone.

Seems to be similar to this issue:
https://github.com/HowardHinnant/date/issues/252

**Comment by gitduk** [comment] 2022-12-06 07:58
> I'm facing the same issue.
> 
> OS: Ubuntu 18.04 Ti Version: 4.0.7
> 
> Docs followed: https://docs.pingcap.com/tidb/stable/production-deployment-using-tiup
> 
> Topology: 1 pd, 1 Tidb, 3 TiKV, 1 TiFlash all on single machine for testing.
> 
> Error on control machine: `INFO Execute command finished {"code": 1, "error": "failed to start tidb: \ttidb 127.0.0.1:4000 failed to start: timed out waiting for port 4000 to be started after 2m0s, please check the log of the instance: timed out waiting for port 4000 to be started after 2m0s", "errorVerbose": "timed out waiting for port 4000 to be started after 2m0s\ngithub.com/pingcap/tiup/pkg/cluster/module.(*WaitFor).Execute\n\tgithub.com/pingcap/tiup@/pkg/cluster/module/wait_for.go:90\ngithub.com/pingcap/tiup/pkg/cluster/spec.PortStarted\n\tgithub.com/pingcap/tiup@/pkg/cluster/spec/instance.go:101\ngithub.com/pingcap/tiup/pkg/cluster/spec.(*BaseInstance).Ready\n\tgithub.com/pingcap/tiup@/pkg/cluster/spec/instance.go:132\ngithub.com/pingcap/tiup/pkg/cluster/operation.startInstance\n\tgithub.com/pingcap/tiup@/pkg/cluster/operation/action.go:563\ngithub.com/pingcap/tiup/pkg/cluster/operation.StartComponent.func1\n\tgithub.com/pingcap/tiup@/pkg/cluster/operation/action.go:678\ngolang.org/x/sync/errgroup.(*Group).Go.func1\n\tgolang.org/x/sync@v0.0.0-20190911185100-cd5d95a43a6e/errgroup/errgroup.go:57\nruntime.goexit\n\truntime/asm_amd64.s:1357\n\ttidb 127.0.0.1:4000 failed to start: timed out waiting for port 4000 to be started after 2m0s, please check the log of the instance\nfailed to start tidb"}`
> 
> TiDB logs on server: `[error="other error: [components/tidb_query/src/expr/ctx.rs:87]: unknown or incorrect time zone: posixrules"] [2020/10/20 07:24:51.093 -04:00] [FATAL] [terror.go:257] ["unexpected error"] [error="other error: [components/tidb_query/src/expr/ctx.rs:87]: unknown or incorrect time zone: posixrules"] [stack="github.com/pingcap/parser/terror.MustNil\n\t/home/jenkins/agent/workspace/tidb_v4.0.7/go/pkg/mod/github.com/pingcap/parser@v0.0.0-20200921063432-e220cfcfd026/terror/terror.go:257\nmain.createStoreAndDomain\n\t/home/jenkins/agent/workspace/tidb_v4.0.7/go/src/github.com/pingcap/tidb/tidb-server/main.go:259\nmain.main\n\t/home/jenkins/agent/workspace/tidb_v4.0.7/go/src/github.com/pingcap/tidb/tidb-server/main.go:179\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:203"] [stack="github.com/pingcap/parser/terror.MustNil\n\t/home/jenkins/agent/workspace/tidb_v4.0.7/go/pkg/mod/github.com/pingcap/parser@v0.0.0-20200921063432-e220cfcfd026/terror/terror.go:257\nmain.createStoreAndDomain\n\t/home/jenkins/agent/workspace/tidb_v4.0.7/go/src/github.com/pingcap/tidb/tidb-server/main.go:259\nmain.main\n\t/home/jenkins/agent/workspace/tidb_v4.0.7/go/src/github.com/pingcap/tidb/tidb-server/main.go:179\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:203"]`
> 
> Issue seems to be caused by the fact that certain time-zones have a symlink to posixrules.
> 
> TiUP go script seems to be recursively reading /etc/localtime and then when a timezone ends at a symlink to posixrules, TiDB is unable to figure out the actual timezone as 'posixrules' is not a valid time zone.
> 
> Seems to be similar to this issue: [HowardHinnant/date#252](https://github.com/HowardHinnant/date/issues/252)

老哥，解决没，遇到一模一样问题，头都大了。

**Comment by jebter** [comment] 2024-06-06 03:53
Please post your problem to https://asktug.com. They would reply to your problem ASAP.I will close this issue. If there are any updates, you can reopen it.

**Closed by jebter** 2024-06-06 03:53 UTC
Labels: type/question
