### ISSUE TITLE
PD Server Timeout under high write pressure

### ISSUE THREAD

**Issue by sticnarf** [pingcap/tidb#24615] opened 2021-05-13 07:17 UTC
### 1. Minimal reproduce step (Required)

Keeps giving TiKV huge write load. I run with uniform workload in pingcap/tipocket#410.

### 3. What did you see instead (Required)

The client receives lots of `Error 9001: PD server timeout`.

The TiDB log shows a lot of `region not found for key`:

```
[2021/05/13 14:29:06.333 +08:00] [WARN] [backoff.go:332] ["pdRPC backoffer.maxSleep 82000ms is exceeded, errors:\nregion not found for key \"t\\x80\\x00\\x00\\x00\\x00\\x00\\x00\\xad_r\\x01947df4c0\\xff-475e-42\\xffc9-9776-\\xfff58a5b2b
\\xfff401\\x00\\x00\\x00\\x00\\xfb\" at 2021-05-13T14:29:01.421081901+08:00\nregion not found for key \"t\\x80\\x00\\x00\\x00\\x00\\x00\\x00\\xad_r\\x01947df4c0\\xff-475e-42\\xffc9-9776-\\xfff58a5b2b\\xfff401\\x00\\x00\\x00\\x00\\xfb\"
at 2021-05-13T14:29:03.423427071+08:00\nregion not found for key \"t\\x80\\x00\\x00\\x00\\x00\\x00\\x00\\xad_r\\x01947df4c0\\xff-475e-42\\xffc9-9776-\\xfff58a5b2b\\xfff401\\x00\\x00\\x00\\x00\\xfb\" at 2021-05-13T14:29:06.333751911+08:0
0"]
[2021/05/13 14:29:06.408 +08:00] [WARN] [backoff.go:332] ["pdRPC backoffer.maxSleep 82000ms is exceeded, errors:\nregion not found for key \"t\\x80\\x00\\x00\\x00\\x00\\x00\\x00\\xad_r\\x0195e09e4f\\xff-c69a-4f\\xff11-b285-\\xff64127ddb
\\xff4e90\\x00\\x00\\x00\\x00\\xfb\" at 2021-05-13T14:29:02.59465437+08:00\nregion not found for key \"t\\x80\\x00\\x00\\x00\\x00\\x00\\x00\\xad_r\\x0195e09e4f\\xff-c69a-4f\\xff11-b285-\\xff64127ddb\\xff4e90\\x00\\x00\\x00\\x00\\xfb\" a
t 2021-05-13T14:29:04.788023854+08:00\nregion not found for key \"t\\x80\\x00\\x00\\x00\\x00\\x00\\x00\\xad_r\\x0195e09e4f\\xff-c69a-4f\\xff11-b285-\\xff64127ddb\\xff4e90\\x00\\x00\\x00\\x00\\xfb\" at 2021-05-13T14:29:06.408440977+08:00
"]
[2021/05/13 14:29:06.429 +08:00] [WARN] [backoff.go:332] ["pdRPC backoffer.maxSleep 82000ms is exceeded, errors:\nregion not found for key \"t\\x80\\x00\\x00\\x00\\x00\\x00\\x00\\xad_r\\x0195c15ce1\\xff-5ab2-48\\xfff7-907e-\\xffce9f32bc
\\xff0188\\x00\\x00\\x00\\x00\\xfb\" at 2021-05-13T14:29:02.652255463+08:00\nregion not found for key \"t\\x80\\x00\\x00\\x00\\x00\\x00\\x00\\xad_r\\x0195c15ce1\\xff-5ab2-48\\xfff7-907e-\\xffce9f32bc\\xff0188\\x00\\x00\\x00\\x00\\xfb\"
at 2021-05-13T14:29:04.816532004+08:00\nregion not found for key \"t\\x80\\x00\\x00\\x00\\x00\\x00\\x00\\xad_r\\x0195c15ce1\\xff-5ab2-48\\xfff7-907e-\\xffce9f32bc\\xff0188\\x00\\x00\\x00\\x00\\xfb\" at 2021-05-13T14:29:06.429102918+08:0
0"]
[2021/05/13 14:29:06.451 +08:00] [WARN] [backoff.go:332] ["pdRPC backoffer.maxSleep 82000ms is exceeded, errors:\nregion not found for key \"t\\x80\\x00\\x00\\x00\\x00\\x00\\x00\\xad_r\\x0195bc137c\\xff-63ad-4a\\xffea-84a3-\\xff914ecd41
\\xff69c9\\x00\\x00\\x00\\x00\\xfb\" at 2021-05-13T14:29:02.687878166+08:00\nregion not found for key \"t\\x80\\x00\\x00\\x00\\x00\\x00\\x00\\xad_r\\x0195bc137c\\xff-63ad-4a\\xffea-84a3-\\xff914ecd41\\xff69c9\\x00\\x00\\x00\\x00\\xfb\"
at 2021-05-13T14:29:04.243187839+08:00\nregion not found for key \"t\\x80\\x00\\x00\\x00\\x00\\x00\\x00\\xad_r\\x0195bc137c\\xff-63ad-4a\\xffea-84a3-\\xff914ecd41\\xff69c9\\x00\\x00\\x00\\x00\\xfb\" at 2021-05-13T14:29:06.451744923+08:0
0"]
[2021/05/13 14:29:06.479 +08:00] [WARN] [backoff.go:332] ["pdRPC backoffer.maxSleep 82000ms is exceeded, errors:\nregion not found for key \"t\\x80\\x00\\x00\\x00\\x00\\x00\\x00\\xad_r\\x01946864ea\\xff-cb21-40\\xffda-a5bc-\\xff687d7dba
\\xff126d\\x00\\x00\\x00\\x00\\xfb\" at 2021-05-13T14:29:03.402861941+08:00\nregion not found for key \"t\\x80\\x00\\x00\\x00\\x00\\x00\\x00\\xad_r\\x01946864ea\\xff-cb21-40\\xffda-a5bc-\\xff687d7dba\\xff126d\\x00\\x00\\x00\\x00\\xfb\"
at 2021-05-13T14:29:04.956314969+08:00\nregion not found for key \"t\\x80\\x00\\x00\\x00\\x00\\x00\\x00\\xad_r\\x01946864ea\\xff-cb21-40\\xffda-a5bc-\\xff687d7dba\\xff126d\\x00\\x00\\x00\\x00\\xfb\" at 2021-05-13T14:29:06.479773509+08:0
0"]
[2021/05/13 14:29:06.480 +08:00] [INFO] [region_cache.go:485] ["invalidate current region, because others failed on same store"] [region=23209] [store=127.0.0.1:20161]
[2021/05/13 14:29:06.483 +08:00] [WARN] [backoff.go:332] ["pdRPC backoffer.maxSleep 82000ms is exceeded, errors:\nregion not found for key \"t\\x80\\x00\\x00\\x00\\x00\\x00\\x00\\xad_r\\x01957017f7\\xff-30b6-48\\xffde-93fa-\\xffc8c3cfaa\\xff3edc\\x00\\x00\\x00\\x00\\xfb\" at 2021-05-13T14:29:02.148425938+08:00\nregion not found for key \"t\\x80\\x00\\x00\\x00\\x00\\x00\\x00\\xad_r\\x01957017f7\\xff-30b6-48\\xffde-93fa-\\xffc8c3cfaa\\xff3edc\\x00\\x00\\x00\\x00\\xfb\"
```

### 4. What is your TiDB version? (Required)

A recent master.
TiDB: 075df515e4620255a423ab2a9d6b23ab3e4279a1
PD: a052077da543d4018ee41ffd56fcd498289844a3

**Comment by HunDunDM** [comment] 2021-07-09 07:36
After the Region is split into two, if there is only one reporting heartbeat, a Range hole will appear on the PD side. Is it possible that TiKV is too busy to cause this phenomenon?

**Comment by sticnarf** [comment] 2021-07-09 07:56
> After the Region is split into two, if there is only one reporting heartbeat, a Range hole will appear on the PD side. Is it possible that TiKV is too busy to cause this phenomenon?

Yes. This problem is probably because the raftstore stalls.

**Comment by nolouch** [comment] 2021-12-13 09:34
can we reproduce it?

**Comment by sticnarf** [comment] 2021-12-13 09:53
The issue was reported months ago, before the scheduler flow control implemented in TiKV. The probability of the problem should be quite low because it is less likely that the raftstore is stuck for a long time. 

The known problems includes loading evicted entries makes the apply threads slow.

**Comment by nolouch** [comment] 2021-12-15 07:23
I'm going to close this issue because there is no more information, and we can reopen it if you have any problems.

**Closed by nolouch** 2021-12-15 07:23 UTC
Labels: type/bug, severity/major, component/pd
