### ISSUE TITLE
The result is null when we execute command  "show variables like 'tidb_enable_window_function'" and  "show variables like 'tidb_enable_mutation_checker'"';

### ISSUE THREAD

**Issue by sylar8023baby** [pingcap/tidb#34060] opened 2022-04-18 03:50 UTC
### 1. Minimal reproduce step (Required)

// when we execute command "show variables like  ..." ,the result is "Empty set"

mysql> show variables like 'tidb_txn_assertion_level';
Empty set (0.01 sec)

mysql> show variables like '%tidb_enable_mutation_checker%';
Empty set (0.01 sec)

//  when we execute command "select @@... , the result is seemd right.

mysql> select @@tidb_txn_assertion_level;
+----------------------------+
| @@tidb_txn_assertion_level |
+----------------------------+
| FAST                       |
+----------------------------+
1 row in set (0.00 sec)

mysql> select @@tidb_enable_mutation_checker;
+--------------------------------+
| @@tidb_enable_mutation_checker |
+--------------------------------+
|                              1 |
+--------------------------------+
1 row in set (0.00 sec)

mysql>
### 2. What did you expect to see? (Required)

It should  return  system variables where we are selecting.

### 3. What did you see instead (Required)

It actully returns "Empty set ".

### 4. What is your TiDB version? (Required)

// tidb version

mysql> select tidb_version();
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
--------------------------------------------------+
| tidb_version()
                                                  |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
--------------------------------------------------+
| Release Version: v6.0.0
Edition: Community
Git Commit Hash: 36a9810441ca0e496cbd22064af274b3be771081
Git Branch: heads/refs/tags/v6.0.0
UTC Build Time: 2022-03-31 10:33:28
GoVersion: go1.18
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
--------------------------------------------------+

**Comment by Defined2014** [comment] 2022-04-18 03:59
I think it's by design. Because `TiDBTxnAssertionLevel` and `TiDBEnableMutationChecker` are hidden sysvars. cc @morgo

**Comment by morgo** [comment] 2022-04-18 04:21
Yes that's right - it's currently by design. We do have plans to fix it in future though, and no longer hide sysvars. See: https://github.com/pingcap/tidb/blob/master/docs/design/2021-07-29-hidden-sysvars.md

**Comment by sylar8023baby** [comment] 2022-04-18 05:59
Thank you

**Comment by Defined2014** [comment] 2022-07-04 06:47
It fixed by https://github.com/pingcap/tidb/pull/35740, so close this issue.

**Closed by Defined2014** 2022-07-04 06:47 UTC
Labels: type/bug, severity/moderate
